-- 029_science_general_en.sql
-- MindScrolling — Science Mode: general_science EN (250 quotes)
-- Topics: scientific method, discoveries, nature, evolution, biology, chemistry,
--         environment, medicine, neuroscience, genetics, ecology, geology,
--         paleontology, astronomy basics
--
-- All rows:
--   category       = 'philosophy'
--   swipe_dir      = 'down'
--   pack_name      = 'free'
--   is_premium     = false
--   is_hidden_mode = true
--   locked_by      = 'science'
-- Run in Supabase SQL Editor

BEGIN;

-- ══════════════════════════════════════════════════════════════════════════════
-- GENERAL SCIENCE — ENGLISH (250 quotes)
-- ══════════════════════════════════════════════════════════════════════════════

INSERT INTO quotes (id, text, author, category, lang, swipe_dir, pack_name, is_premium, content_type, sub_category, tags, is_hidden_mode, locked_by) VALUES

-- Carl Sagan (1–12)
(gen_random_uuid(), 'The nitrogen in our DNA, the calcium in our teeth, the iron in our blood, the carbon in our apple pies were made in the interiors of collapsing stars.', 'Carl Sagan', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'For small creatures such as we, the vastness is bearable only through love.', 'Carl Sagan', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'curiosity', 'learning'], true, 'science'),
(gen_random_uuid(), 'We have also arranged things so that almost no one understands science and technology. This is a prescription for disaster.', 'Carl Sagan', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'learning', 'self_improvement'], true, 'science'),
(gen_random_uuid(), 'Absence of evidence is not evidence of absence.', 'Carl Sagan', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'curiosity', 'learning'], true, 'science'),
(gen_random_uuid(), 'We are a way for the cosmos to know itself.', 'Carl Sagan', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'The fact that some geniuses were laughed at does not imply that all who are laughed at are geniuses.', 'Carl Sagan', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'learning', 'self_improvement'], true, 'science'),
(gen_random_uuid(), 'Skeptical scrutiny is the means, in both science and religion, by which deep thoughts can be winnowed from deep nonsense.', 'Carl Sagan', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'curiosity', 'learning'], true, 'science'),
(gen_random_uuid(), 'Books are like seeds. They can lie dormant for centuries and then flower in the most unpromising soil.', 'Carl Sagan', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['learning', 'wisdom', 'curiosity'], true, 'science'),
(gen_random_uuid(), 'Science is not only compatible with spirituality; it is a profound source of spirituality.', 'Carl Sagan', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'curiosity', 'learning'], true, 'science'),
(gen_random_uuid(), 'An organism at war with itself is doomed.', 'Carl Sagan', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'learning', 'self_improvement'], true, 'science'),
(gen_random_uuid(), 'The beauty of a living thing is not the atoms that go into it, but the way those atoms are put together.', 'Carl Sagan', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'If we long to believe that the stars rise and set for us, that we are the reason there is a universe, astronomy is not for you.', 'Carl Sagan', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'curiosity', 'learning'], true, 'science'),

-- Neil deGrasse Tyson (13–22)
(gen_random_uuid(), 'When you are scientifically literate, the world looks very different to you.', 'Neil deGrasse Tyson', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['learning', 'wisdom', 'self_improvement'], true, 'science'),
(gen_random_uuid(), 'The universe is under no obligation to make sense to you.', 'Neil deGrasse Tyson', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'curiosity', 'learning'], true, 'science'),
(gen_random_uuid(), 'NASA''s Hubble Space Telescope has shown us that the universe is old, large, and violent.', 'Neil deGrasse Tyson', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'learning', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'Exploration is not a choice, really; it''s an imperative.', 'Neil deGrasse Tyson', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'discipline', 'learning'], true, 'science'),
(gen_random_uuid(), 'The atoms of our bodies are traceable to stars that manufactured them in their cores.', 'Neil deGrasse Tyson', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'Every mystery ever solved has turned out to be not magic but the triumph of careful thinking.', 'Neil deGrasse Tyson', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'learning', 'focus'], true, 'science'),
(gen_random_uuid(), 'Kids should be allowed to break stuff more often. That''s a consequence of exploration.', 'Neil deGrasse Tyson', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'creativity', 'learning'], true, 'science'),
(gen_random_uuid(), 'I dream of a world where the truth is what shapes people''s politics, rather than politics shaping what people think is true.', 'Neil deGrasse Tyson', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'learning', 'self_improvement'], true, 'science'),
(gen_random_uuid(), 'Equipped with his five senses, man explores the universe around him and calls the adventure science.', 'Neil deGrasse Tyson', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'learning', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'The act of turning the unknown into the known is a fundamentally human endeavor.', 'Neil deGrasse Tyson', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'learning', 'wisdom'], true, 'science'),

-- Richard Dawkins (23–32)
(gen_random_uuid(), 'The feeling of awed wonder that science can give us is one of the highest experiences of which the human psyche is capable.', 'Richard Dawkins', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'We are survival machines — robot vehicles blindly programmed to preserve the selfish molecules known as genes.', 'Richard Dawkins', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'Natural selection is anything but random.', 'Richard Dawkins', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'curiosity', 'learning'], true, 'science'),
(gen_random_uuid(), 'Science feeds on mystery. As soon as mystery disappears, science moves elsewhere.', 'Richard Dawkins', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'learning', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'Evolution could so easily be disproved if just a single fossil turned up in the wrong date order.', 'Richard Dawkins', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['learning', 'wisdom', 'curiosity'], true, 'science'),
(gen_random_uuid(), 'The universe we observe has precisely the properties we should expect if there is, at bottom, no design, no purpose, no evil and no good — nothing but blind, pitiless indifference.', 'Richard Dawkins', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'curiosity', 'learning'], true, 'science'),
(gen_random_uuid(), 'Geology shows that fossils are of different ages. Paleontology shows a fossil sequence; the youngest fossils are most like modern animals.', 'Richard Dawkins', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['learning', 'curiosity', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'Viruses are not living things in the way that animals are living things.', 'Richard Dawkins', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['learning', 'curiosity', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'One of the things that is wrong with religion is that it teaches us to be satisfied with answers which are not really answers at all.', 'Richard Dawkins', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'learning', 'curiosity'], true, 'science'),
(gen_random_uuid(), 'We are all related by blood to a common ancestor who lived perhaps 10,000 years ago.', 'Richard Dawkins', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),

-- Jane Goodall (33–41)
(gen_random_uuid(), 'You cannot get through a single day without having an impact on the world around you. What you do makes a difference.', 'Jane Goodall', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'self_improvement', 'discipline'], true, 'science'),
(gen_random_uuid(), 'Every individual matters. Every individual has a role to play. Every individual makes a difference.', 'Jane Goodall', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'self_improvement', 'learning'], true, 'science'),
(gen_random_uuid(), 'What you do makes a difference, and you have to decide what kind of difference you want to make.', 'Jane Goodall', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'self_improvement', 'discipline'], true, 'science'),
(gen_random_uuid(), 'Only if we understand, will we care. Only if we care, will we help. Only if we help, shall all be saved.', 'Jane Goodall', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'learning', 'self_improvement'], true, 'science'),
(gen_random_uuid(), 'The least I can do is speak out for those who cannot speak for themselves.', 'Jane Goodall', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'discipline', 'self_improvement'], true, 'science'),
(gen_random_uuid(), 'Animals have personalities and minds and feelings; science is gradually proving what we knew all along.', 'Jane Goodall', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'My mission is to create a world where we can live in harmony with nature.', 'Jane Goodall', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'learning', 'self_improvement'], true, 'science'),
(gen_random_uuid(), 'We have the choice to use the gift of our life to make the world a better place — or not to bother.', 'Jane Goodall', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'self_improvement', 'discipline'], true, 'science'),
(gen_random_uuid(), 'I spent years in the forest learning from chimpanzees what it means to be a social animal.', 'Jane Goodall', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'learning', 'wisdom'], true, 'science'),

-- Rachel Carson (42–50)
(gen_random_uuid(), 'The more clearly we can focus our attention on the wonders and realities of the universe about us, the less taste we shall have for destruction.', 'Rachel Carson', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'curiosity', 'learning'], true, 'science'),
(gen_random_uuid(), 'In every curving beach, in every grain of sand, there is a story of the Earth.', 'Rachel Carson', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'Those who contemplate the beauty of the earth find reserves of strength that will endure as long as life lasts.', 'Rachel Carson', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'learning', 'curiosity'], true, 'science'),
(gen_random_uuid(), 'If a child is to keep alive his inborn sense of wonder, he needs the companionship of at least one adult who can share it.', 'Rachel Carson', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'learning', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'I believe natural beauty has a necessary place in the spiritual development of any individual or any society.', 'Rachel Carson', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'curiosity', 'learning'], true, 'science'),
(gen_random_uuid(), 'One way to open your eyes is to ask yourself, what if I had never seen this before? What if I knew I would never see it again?', 'Rachel Carson', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'Man''s attitude toward nature is today critically important simply because we have now acquired a fateful power to alter and destroy nature.', 'Rachel Carson', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'learning', 'self_improvement'], true, 'science'),
(gen_random_uuid(), 'The ocean is a place of paradoxes. It is the home of the great white shark and also of the helpless jellyfish.', 'Rachel Carson', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'It is a wholesome and necessary thing for us to turn again to the earth and in the contemplation of her beauties to know wonder and humility.', 'Rachel Carson', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'curiosity', 'learning'], true, 'science'),

-- David Attenborough (51–59)
(gen_random_uuid(), 'It''s surely our responsibility to do everything within our power to create a planet that provides a home not just for us, but for all life on Earth.', 'David Attenborough', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'self_improvement', 'discipline'], true, 'science'),
(gen_random_uuid(), 'No one will protect what they don''t care about; and no one will care about what they have never experienced.', 'David Attenborough', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'learning', 'curiosity'], true, 'science'),
(gen_random_uuid(), 'An understanding of the natural world is a source of not only great curiosity but great fulfillment.', 'David Attenborough', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'If we don''t take action, the collapse of our civilisations and the extinction of much of the natural world is on the horizon.', 'David Attenborough', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'self_improvement', 'discipline'], true, 'science'),
(gen_random_uuid(), 'The natural world is the greatest source of excitement; the greatest source of visual beauty; the greatest source of intellectual interest.', 'David Attenborough', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'We must act now to safeguard our future and that of all life on Earth.', 'David Attenborough', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['discipline', 'self_improvement', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'I think sometimes we need to step back and just let nature take its course.', 'David Attenborough', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'curiosity', 'learning'], true, 'science'),
(gen_random_uuid(), 'Animals are the most honest things on this planet.', 'David Attenborough', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'curiosity', 'learning'], true, 'science'),
(gen_random_uuid(), 'We are at a unique stage in our history. Never before have we had such an awareness of what we are doing to the planet.', 'David Attenborough', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'learning', 'self_improvement'], true, 'science'),

-- E.O. Wilson (60–68)
(gen_random_uuid(), 'Biodiversity is the totality of all inherited variation in the life forms of Earth.', 'E.O. Wilson', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'learning', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'In the attempt to make scientific discoveries, every problem is an opportunity, and the more difficult the problem, the greater will be the prestige of its solution.', 'E.O. Wilson', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['discipline', 'learning', 'curiosity'], true, 'science'),
(gen_random_uuid(), 'The world is not made of atoms but of stories.', 'E.O. Wilson', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'curiosity', 'learning'], true, 'science'),
(gen_random_uuid(), 'We are drowning in information, while starving for wisdom.', 'E.O. Wilson', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'learning', 'self_improvement'], true, 'science'),
(gen_random_uuid(), 'The human brain was not designed to grasp the true nature of reality.', 'E.O. Wilson', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'Nature holds the key to our aesthetic, intellectual, cognitive and even spiritual satisfaction.', 'E.O. Wilson', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'curiosity', 'learning'], true, 'science'),
(gen_random_uuid(), 'If all mankind were to disappear, the world would regenerate back to the rich state of equilibrium that existed ten thousand years ago.', 'E.O. Wilson', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'curiosity', 'learning'], true, 'science'),
(gen_random_uuid(), 'The real problem of humanity is the following: we have paleolithic emotions; medieval institutions; and god-like technology.', 'E.O. Wilson', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'learning', 'self_improvement'], true, 'science'),
(gen_random_uuid(), 'Put your hand on a hot stove for a minute, and it seems like an hour. Sit with a pretty girl for an hour, and it seems like a minute. That''s relativity — but biology plays a role too.', 'E.O. Wilson', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),

-- Stephen Jay Gould (69–76)
(gen_random_uuid(), 'Evolution is a process of constant branching and expansion.', 'Stephen Jay Gould', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'learning', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'I am, somehow, less interested in the weight and convolutions of Einstein''s brain than in the near certainty that people of equal talent have lived and died in cotton fields and sweatshops.', 'Stephen Jay Gould', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'learning', 'self_improvement'], true, 'science'),
(gen_random_uuid(), 'Science is not a heartless pursuit of objective information; it is a creative human activity.', 'Stephen Jay Gould', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['creativity', 'learning', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'We are the offspring of history, and must establish our own paths in this most diverse and interesting of conceivable universes.', 'Stephen Jay Gould', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'self_improvement', 'learning'], true, 'science'),
(gen_random_uuid(), 'The most erroneous stories are those we think we know best — and therefore never scrutinize or question.', 'Stephen Jay Gould', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'curiosity', 'learning'], true, 'science'),
(gen_random_uuid(), 'Humans are not the end result of predictable evolutionary progress, but rather a fortuitous cosmic afterthought.', 'Stephen Jay Gould', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'In science, ''fact'' can only mean ''confirmed to such a degree that it would be perverse to withhold provisional assent.''', 'Stephen Jay Gould', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'learning', 'curiosity'], true, 'science'),
(gen_random_uuid(), 'Paleontology is the study of life''s history written in stone.', 'Stephen Jay Gould', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'learning', 'wisdom'], true, 'science'),

-- Oliver Sacks (77–84)
(gen_random_uuid(), 'The brain is the most complex thing in the universe and it''s right behind your forehead.', 'Oliver Sacks', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'One must try, in one''s own life, to have a share of the adventure of the mind.', 'Oliver Sacks', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'learning', 'self_improvement'], true, 'science'),
(gen_random_uuid(), 'Medicine is an art and it requires that we use our full humanity.', 'Oliver Sacks', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'learning', 'creativity'], true, 'science'),
(gen_random_uuid(), 'I have had a love affair with chemistry since the age of ten.', 'Oliver Sacks', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'learning', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'To be ourselves we must have ourselves — possess, if need be re-possess, our life-stories.', 'Oliver Sacks', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'self_improvement', 'learning'], true, 'science'),
(gen_random_uuid(), 'Each of us is a unique story written by life and environment.', 'Oliver Sacks', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'curiosity', 'learning'], true, 'science'),
(gen_random_uuid(), 'Neuroscience is now generating explanations for phenomena that were once entirely mysterious.', 'Oliver Sacks', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'learning', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'The brain''s ability to adapt and change is one of the most extraordinary things in all of science.', 'Oliver Sacks', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),

-- Linus Pauling (85–91)
(gen_random_uuid(), 'Satisfaction of one''s curiosity is one of the greatest sources of happiness in life.', 'Linus Pauling', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'The way to get good ideas is to get lots of ideas and throw away the bad ones.', 'Linus Pauling', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['creativity', 'learning', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'Chemistry is the science of matter, but I prefer to think of it as the science of change.', 'Linus Pauling', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'Do unto others as you would have them do unto you — and this is as valid in science as anywhere else.', 'Linus Pauling', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'learning', 'self_improvement'], true, 'science'),
(gen_random_uuid(), 'The best way to have a good idea is to have lots of ideas.', 'Linus Pauling', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['creativity', 'learning', 'curiosity'], true, 'science'),
(gen_random_uuid(), 'Science is the search for truth — it is not a game in which one tries to beat his opponent.', 'Linus Pauling', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'learning', 'discipline'], true, 'science'),
(gen_random_uuid(), 'Every molecule in the body was once a part of food; food is, therefore, the source of all structures.', 'Linus Pauling', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'learning', 'wisdom'], true, 'science'),

-- Jonas Salk (92–97)
(gen_random_uuid(), 'The reward for work well done is the opportunity to do more.', 'Jonas Salk', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['discipline', 'self_improvement', 'focus'], true, 'science'),
(gen_random_uuid(), 'If a doctor can give you a polio vaccine, why can''t we give people wisdom?', 'Jonas Salk', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'curiosity', 'learning'], true, 'science'),
(gen_random_uuid(), 'The people who make a difference in your life are not the ones with the most credentials, but the ones who care.', 'Jonas Salk', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'self_improvement', 'learning'], true, 'science'),
(gen_random_uuid(), 'What we need is not a political leader but a wise man. And wise men are found not in politics but in science.', 'Jonas Salk', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'learning', 'curiosity'], true, 'science'),
(gen_random_uuid(), 'Good parents give their children roots and wings: roots to know where home is, wings to fly away and exercise what''s been taught them.', 'Jonas Salk', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'learning', 'self_improvement'], true, 'science'),
(gen_random_uuid(), 'Hope lies in dreams, in imagination, and in the courage of those who dare to make dreams into reality.', 'Jonas Salk', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['creativity', 'discipline', 'self_improvement'], true, 'science'),

-- Louis Pasteur (98–105)
(gen_random_uuid(), 'In the fields of observation, chance favors only the prepared mind.', 'Louis Pasteur', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'learning', 'focus'], true, 'science'),
(gen_random_uuid(), 'Science knows no country, because knowledge belongs to humanity, and is the torch which illuminates the world.', 'Louis Pasteur', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'learning', 'curiosity'], true, 'science'),
(gen_random_uuid(), 'Do not let it be imagined that one''s love for science is incompatible with men''s love for mankind.', 'Louis Pasteur', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'learning', 'self_improvement'], true, 'science'),
(gen_random_uuid(), 'One must work; one must work. I have done what I could.', 'Louis Pasteur', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['discipline', 'focus', 'self_improvement'], true, 'science'),
(gen_random_uuid(), 'The universe is asymmetric and I am persuaded that life, as it is known to us, is a direct result of the asymmetry of the universe.', 'Louis Pasteur', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'A bottle of wine contains more philosophy than all the books in the world.', 'Louis Pasteur', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'curiosity', 'learning'], true, 'science'),
(gen_random_uuid(), 'When meditating over a disease, I never think of finding a remedy for it, but instead a means of preventing it.', 'Louis Pasteur', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'discipline', 'focus'], true, 'science'),
(gen_random_uuid(), 'Gentlemen, it is the microbes who will have the last word.', 'Louis Pasteur', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'curiosity', 'learning'], true, 'science'),

-- Charles Darwin (106–114)
(gen_random_uuid(), 'I have called this principle, by which each slight variation, if useful, is preserved, by the term Natural Selection.', 'Charles Darwin', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'learning', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'False facts are highly injurious to the progress of science, for they often endure long.', 'Charles Darwin', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'learning', 'curiosity'], true, 'science'),
(gen_random_uuid(), 'How paramount the future is to the present when one is surrounded by children.', 'Charles Darwin', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'learning', 'curiosity'], true, 'science'),
(gen_random_uuid(), 'It is not the strongest or the most intelligent who will survive but those who can best manage change.', 'Charles Darwin', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'self_improvement', 'discipline'], true, 'science'),
(gen_random_uuid(), 'To kill an error is as good a service as, and sometimes even better than, the establishing of a new truth or fact.', 'Charles Darwin', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'learning', 'focus'], true, 'science'),
(gen_random_uuid(), 'There is grandeur in this view of life, with its several powers, having been originally breathed into a few forms or into one.', 'Charles Darwin', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'I have steadily endeavoured to keep my mind free so as to give up any hypothesis, however much beloved, as soon as facts are shown to be opposed to it.', 'Charles Darwin', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'learning', 'discipline'], true, 'science'),
(gen_random_uuid(), 'The mystery of the beginning of all things is insoluble by us; and I for one must be content to remain an agnostic.', 'Charles Darwin', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'curiosity', 'learning'], true, 'science'),
(gen_random_uuid(), 'We stopped looking for monsters under our bed when we realized that they could be inside us.', 'Charles Darwin', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'self_improvement', 'learning'], true, 'science'),

-- Marie Curie (115–121)
(gen_random_uuid(), 'Life is not easy for any of us. But what of that? We must have perseverance and above all confidence in ourselves.', 'Marie Curie', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['discipline', 'self_improvement', 'focus'], true, 'science'),
(gen_random_uuid(), 'I am among those who think that science has great beauty. A scientist in his laboratory is not only a technician: he is also a child placed before natural phenomena which impress him like a fairy tale.', 'Marie Curie', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'You must never be fearful about what you are doing when it is right.', 'Marie Curie', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'discipline', 'self_improvement'], true, 'science'),
(gen_random_uuid(), 'Radioactivity is not the cause of illness; it is the source of cures.', 'Marie Curie', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'First principle: never to let one''s self be beaten down by persons or by events.', 'Marie Curie', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['discipline', 'focus', 'self_improvement'], true, 'science'),
(gen_random_uuid(), 'A scientist in a laboratory is not only a technician; he is also a child placed before natural phenomena.', 'Marie Curie', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'In science, we must be interested in things, not in persons.', 'Marie Curie', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['focus', 'discipline', 'learning'], true, 'science'),

-- Rosalind Franklin (122–127)
(gen_random_uuid(), 'Science and everyday life cannot and should not be separated.', 'Rosalind Franklin', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'learning', 'curiosity'], true, 'science'),
(gen_random_uuid(), 'In my view, all that is necessary for faith is the belief that by doing our best we shall succeed in our aims: the improvement of mankind.', 'Rosalind Franklin', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'self_improvement', 'discipline'], true, 'science'),
(gen_random_uuid(), 'The data tells the story; trust the data over the hypothesis.', 'Rosalind Franklin', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'focus', 'learning'], true, 'science'),
(gen_random_uuid(), 'Crystallography is the art of reading the atomic structure of matter.', 'Rosalind Franklin', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'learning', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'The path to discovery is paved with precise observation and the courage to follow evidence wherever it leads.', 'Rosalind Franklin', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['discipline', 'focus', 'learning'], true, 'science'),
(gen_random_uuid(), 'I do not think I am unusual in finding my work more interesting than most diversions.', 'Rosalind Franklin', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['focus', 'discipline', 'curiosity'], true, 'science'),

-- Alexander Fleming (128–133)
(gen_random_uuid(), 'One sometimes finds what one is not looking for.', 'Alexander Fleming', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'It is the lone worker who makes the first advance in a subject; the details may be worked out by a team, but the prime idea is due to the enterprise, thought, and perception of an individual.', 'Alexander Fleming', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['discipline', 'creativity', 'focus'], true, 'science'),
(gen_random_uuid(), 'A good gulp of hot whiskey at bedtime — it''s not very scientific, but it helps.', 'Alexander Fleming', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'curiosity', 'learning'], true, 'science'),
(gen_random_uuid(), 'Penicillin cures, but wine makes people happy.', 'Alexander Fleming', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'curiosity', 'learning'], true, 'science'),
(gen_random_uuid(), 'Never neglect an extraordinary appearance or happening.', 'Alexander Fleming', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'The unprepared mind cannot see the outstretched hand of opportunity.', 'Alexander Fleming', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'learning', 'focus'], true, 'science'),

-- Gregor Mendel (134–138)
(gen_random_uuid(), 'My time will come.', 'Gregor Mendel', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['discipline', 'focus', 'self_improvement'], true, 'science'),
(gen_random_uuid(), 'Traits are passed from parents to offspring through invisible units we now call genes.', 'Gregor Mendel', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'learning', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'The pea plant''s simple traits carry profound truths about heredity.', 'Gregor Mendel', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'The value of an experiment is not merely in discovering facts but in understanding their meaning.', 'Gregor Mendel', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'learning', 'curiosity'], true, 'science'),
(gen_random_uuid(), 'Patient and systematic observation is the foundation of all natural science.', 'Gregor Mendel', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['discipline', 'focus', 'learning'], true, 'science'),

-- Barbara McClintock (139–144)
(gen_random_uuid(), 'If you know you are on the right track, if you have this inner knowledge, then nobody can turn you off regardless of what they say.', 'Barbara McClintock', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['discipline', 'focus', 'self_improvement'], true, 'science'),
(gen_random_uuid(), 'I was just so interested in what I was doing I could hardly wait to get up in the morning and get at it.', 'Barbara McClintock', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'focus', 'discipline'], true, 'science'),
(gen_random_uuid(), 'Every time I walk out on the maize field, I learn something new about how genes work.', 'Barbara McClintock', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'learning', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'Genes are not just fixed points on a chromosome; they can jump.', 'Barbara McClintock', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'The important thing is to develop the capacity to see.', 'Barbara McClintock', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['focus', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'You have to be able to hear what the material is telling you.', 'Barbara McClintock', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['focus', 'wisdom', 'learning'], true, 'science'),

-- James Watson (145–149)
(gen_random_uuid(), 'The double helix is indeed a beautiful structure and it is also a beautiful idea.', 'James Watson', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'Science moves with the spirit of an adventure characterized both by youthful arrogance and by the belief that the truth, once found, will be simple as well as pretty.', 'James Watson', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'learning', 'creativity'], true, 'science'),
(gen_random_uuid(), 'Every time you understand something, religion becomes less likely.', 'James Watson', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'learning', 'curiosity'], true, 'science'),
(gen_random_uuid(), 'DNA is the master molecule of life. It governs everything.', 'James Watson', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'To succeed in science, you need ambition, curiosity, and a willingness to fail.', 'James Watson', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['discipline', 'curiosity', 'self_improvement'], true, 'science'),

-- Thomas Huxley (150–156)
(gen_random_uuid(), 'The great end of life is not knowledge but action.', 'Thomas Huxley', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['discipline', 'self_improvement', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'Try to learn something about everything and everything about something.', 'Thomas Huxley', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['learning', 'curiosity', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'The chess-board is the world; the pieces are the phenomena of the universe; the rules of the game are what we call the laws of nature.', 'Thomas Huxley', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'curiosity', 'learning'], true, 'science'),
(gen_random_uuid(), 'The deepest sin against the human mind is to believe things without evidence.', 'Thomas Huxley', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'learning', 'curiosity'], true, 'science'),
(gen_random_uuid(), 'Size is not grandeur, and territory does not make a nation.', 'Thomas Huxley', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'learning', 'curiosity'], true, 'science'),
(gen_random_uuid(), 'Science is organized common sense where many a beautiful theory was killed by an ugly fact.', 'Thomas Huxley', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'learning', 'curiosity'], true, 'science'),
(gen_random_uuid(), 'My business is to teach my aspirations to conform themselves to fact, not to try and make facts harmonize with my aspirations.', 'Thomas Huxley', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['discipline', 'wisdom', 'learning'], true, 'science'),

-- Robert Hooke (157–161)
(gen_random_uuid(), 'The cells of plants are the fundamental units of all living organisms.', 'Robert Hooke', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'Every minute of observation reveals something that wasn''t visible before.', 'Robert Hooke', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'focus', 'learning'], true, 'science'),
(gen_random_uuid(), 'The microscope is a miracle of human ingenuity: it opens a world invisible to the naked eye.', 'Robert Hooke', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'Nature is never idle; it is forever building or destroying.', 'Robert Hooke', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'curiosity', 'learning'], true, 'science'),
(gen_random_uuid(), 'As the extension, so the force — all of nature obeys simple mathematical rules.', 'Robert Hooke', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'learning', 'curiosity'], true, 'science'),

-- Antoine Lavoisier (162–167)
(gen_random_uuid(), 'Nothing is created, nothing is lost; everything is transformed.', 'Antoine Lavoisier', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'curiosity', 'learning'], true, 'science'),
(gen_random_uuid(), 'I have more memories than if I had lived a thousand years — chemistry teaches us that matter persists.', 'Antoine Lavoisier', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'curiosity', 'learning'], true, 'science'),
(gen_random_uuid(), 'Chemistry is the study of the transformations of matter, which are infinite.', 'Antoine Lavoisier', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'learning', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'To call in the statistician after the experiment is done may be no more than asking him to perform a post-mortem examination.', 'Antoine Lavoisier', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['discipline', 'wisdom', 'focus'], true, 'science'),
(gen_random_uuid(), 'We must trust to nothing but facts: these are presented to us by nature and cannot deceive.', 'Antoine Lavoisier', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'learning', 'discipline'], true, 'science'),
(gen_random_uuid(), 'Oxygen is not just an element; it is the breath of life itself.', 'Antoine Lavoisier', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),

-- Michael Faraday (168–174)
(gen_random_uuid(), 'Nothing is too wonderful to be true if it be consistent with the laws of nature.', 'Michael Faraday', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'The laws of nature, as we understand them, are the foundation of our knowledge of natural things.', 'Michael Faraday', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'learning', 'curiosity'], true, 'science'),
(gen_random_uuid(), 'Work. Finish. Publish.', 'Michael Faraday', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['discipline', 'focus', 'self_improvement'], true, 'science'),
(gen_random_uuid(), 'The beauty of electricity, or of any other force, is not that the power is mysterious, but that it is understandable.', 'Michael Faraday', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'All my discoveries have been made in answer to prayer.', 'Michael Faraday', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'curiosity', 'learning'], true, 'science'),
(gen_random_uuid(), 'The important thing in science is not so much to obtain new facts as to discover new ways of thinking about them.', 'Michael Faraday', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['creativity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'The philosopher should be a man willing to listen to every suggestion, but determined to judge for himself.', 'Michael Faraday', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'learning', 'self_improvement'], true, 'science'),

-- Nikola Tesla (175–181)
(gen_random_uuid(), 'The present is theirs; the future, for which I really worked, is mine.', 'Nikola Tesla', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['discipline', 'focus', 'self_improvement'], true, 'science'),
(gen_random_uuid(), 'If you want to find the secrets of the universe, think in terms of energy, frequency and vibration.', 'Nikola Tesla', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'The day science begins to study non-physical phenomena, it will make more progress in one decade than in all the previous centuries of its existence.', 'Nikola Tesla', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'My brain is only a receiver; in the universe there is a core from which we obtain knowledge, strength, and inspiration.', 'Nikola Tesla', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'Of all the frictional resistances, the one that most retards human movement is ignorance.', 'Nikola Tesla', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'learning', 'self_improvement'], true, 'science'),
(gen_random_uuid(), 'I do not think there is any thrill that can go through the human heart like that felt by the inventor as he sees some creation of the brain unfolding to success.', 'Nikola Tesla', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['creativity', 'curiosity', 'focus'], true, 'science'),
(gen_random_uuid(), 'The scientists of today think deeply instead of clearly. One must be sane to think clearly, but one can think deeply and be quite insane.', 'Nikola Tesla', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'curiosity', 'learning'], true, 'science'),

-- Isaac Asimov (182–190)
(gen_random_uuid(), 'The saddest aspect of life right now is that science gathers knowledge faster than society gathers wisdom.', 'Isaac Asimov', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'learning', 'self_improvement'], true, 'science'),
(gen_random_uuid(), 'Self-education is, I firmly believe, the only kind of education there is.', 'Isaac Asimov', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['learning', 'self_improvement', 'discipline'], true, 'science'),
(gen_random_uuid(), 'There is a cult of ignorance in the United States, and there always has been. Anti-intellectualism has been a constant thread winding its way through our political and cultural life.', 'Isaac Asimov', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'learning', 'self_improvement'], true, 'science'),
(gen_random_uuid(), 'Life is pleasant. Death is peaceful. It''s the transition that''s troublesome.', 'Isaac Asimov', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'curiosity', 'learning'], true, 'science'),
(gen_random_uuid(), 'People who think they know everything are a great annoyance to those of us who do.', 'Isaac Asimov', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'learning', 'self_improvement'], true, 'science'),
(gen_random_uuid(), 'Writing, to me, is simply thinking through my fingers.', 'Isaac Asimov', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['creativity', 'focus', 'learning'], true, 'science'),
(gen_random_uuid(), 'I believe in evidence. I believe in observation, measurement, and reasoning, confirmed by independent observers.', 'Isaac Asimov', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'learning', 'discipline'], true, 'science'),
(gen_random_uuid(), 'Any planet is ''Earth'' to those that live on it.', 'Isaac Asimov', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'It is change, continuing change, inevitable change, that is the dominant factor in society today.', 'Isaac Asimov', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'self_improvement', 'learning'], true, 'science'),

-- Arthur C. Clarke (191–198)
(gen_random_uuid(), 'Any sufficiently advanced technology is indistinguishable from magic.', 'Arthur C. Clarke', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'The only way of discovering the limits of the possible is to venture a little way past them into the impossible.', 'Arthur C. Clarke', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'discipline', 'self_improvement'], true, 'science'),
(gen_random_uuid(), 'The greatest tragedy in mankind''s entire history may be the hijacking of morality by religion.', 'Arthur C. Clarke', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'learning', 'curiosity'], true, 'science'),
(gen_random_uuid(), 'Two possibilities exist: either we are alone in the Universe or we are not. Both are equally terrifying.', 'Arthur C. Clarke', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'How inappropriate to call this planet Earth when it is clearly Ocean.', 'Arthur C. Clarke', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'When a distinguished but elderly scientist states that something is possible, he is almost certainly right. When he states that something is impossible, he is very probably wrong.', 'Arthur C. Clarke', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'learning', 'curiosity'], true, 'science'),
(gen_random_uuid(), 'Science can destroy religion by ignoring it as well as by disproving its tenets.', 'Arthur C. Clarke', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'learning', 'curiosity'], true, 'science'),
(gen_random_uuid(), 'I''m convinced that the universe is teeming with life, much of it far beyond what we imagine.', 'Arthur C. Clarke', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),

-- Additional general science — mixed authors (199–250)
(gen_random_uuid(), 'The whole of science is nothing more than a refinement of everyday thinking.', 'Albert Einstein', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'learning', 'curiosity'], true, 'science'),
(gen_random_uuid(), 'The most beautiful thing we can experience is the mysterious. It is the source of all true art and science.', 'Albert Einstein', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'creativity', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'Compound interest is the eighth wonder of the world — but so is the compounding of knowledge.', 'Albert Einstein', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['learning', 'wisdom', 'self_improvement'], true, 'science'),
(gen_random_uuid(), 'The important thing is not to stop questioning. Curiosity has its own reason for existing.', 'Albert Einstein', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'If we knew what we were doing, it would not be called research.', 'Albert Einstein', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'learning', 'creativity'], true, 'science'),
(gen_random_uuid(), 'Logic will get you from A to B. Imagination will take you everywhere.', 'Albert Einstein', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['creativity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'Ecology is the study of relationships, and the most complex relationship is the one between humanity and the rest of life on Earth.', 'E.O. Wilson', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'Biological diversity is the key to the maintenance of the world as we know it.', 'E.O. Wilson', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'curiosity', 'learning'], true, 'science'),
(gen_random_uuid(), 'The variety of life on this planet is its greatest gift.', 'David Attenborough', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'Evolution is not a force but a process. Not a cause but a law.', 'John Morley', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'curiosity', 'learning'], true, 'science'),
(gen_random_uuid(), 'Genetics is the key to understanding who we are and where we came from.', 'James Watson', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'learning', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'The fossil record is the biography of life on Earth, written in stone.', 'Stephen Jay Gould', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'Geology is the study of pressure and time. That''s all it takes really — pressure, and time.', 'Stephen Jay Gould', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'discipline', 'learning'], true, 'science'),
(gen_random_uuid(), 'Medicine is not only a science; it is also an art. It does not consist of compounding pills and plasters, but deals with the very processes of life.', 'Paracelsus', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'learning', 'creativity'], true, 'science'),
(gen_random_uuid(), 'Wherever the art of medicine is loved, there is also a love of humanity.', 'Hippocrates', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'learning', 'self_improvement'], true, 'science'),
(gen_random_uuid(), 'Life is short, and art long; the crisis fleeting; experience perilous, and decision difficult.', 'Hippocrates', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'discipline', 'focus'], true, 'science'),
(gen_random_uuid(), 'Let food be thy medicine and medicine be thy food.', 'Hippocrates', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'self_improvement', 'learning'], true, 'science'),
(gen_random_uuid(), 'Natural forces within us are the true healers of disease.', 'Hippocrates', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'curiosity', 'learning'], true, 'science'),
(gen_random_uuid(), 'The greatest medicine of all is to teach people how not to need it.', 'Hippocrates', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'learning', 'self_improvement'], true, 'science'),
(gen_random_uuid(), 'A physician who is a lover of wisdom is the equal of a god.', 'Hippocrates', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'learning', 'curiosity'], true, 'science'),
(gen_random_uuid(), 'The brain is the last and greatest biological frontier, the most complex thing we have yet discovered in our universe.', 'James Watson', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'Neurons that fire together wire together — this is the basis of all learning.', 'Oliver Sacks', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['learning', 'curiosity', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'The stars are the land-marks of the universe.', 'Arthur C. Clarke', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'Astronomy compels the soul to look upward, and leads us from this world to another.', 'Plato', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'We are all astronomers, in the sense that we are all compelled to look upward and wonder.', 'Neil deGrasse Tyson', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'A world without microbes is a world without life as we know it.', 'Louis Pasteur', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'learning', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'The discovery of the structure of DNA was a triumph of the scientific method.', 'Rosalind Franklin', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'learning', 'discipline'], true, 'science'),
(gen_random_uuid(), 'Science is the poetry of reality.', 'Richard Dawkins', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['creativity', 'wisdom', 'curiosity'], true, 'science'),
(gen_random_uuid(), 'An understanding of the atom is not merely a matter of physics; it is the understanding of life itself.', 'Linus Pauling', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'All science is either physics or stamp collecting.', 'Ernest Rutherford', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'curiosity', 'learning'], true, 'science'),
(gen_random_uuid(), 'Science is the systematic classification of experience.', 'George Henry Lewes', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'learning', 'discipline'], true, 'science'),
(gen_random_uuid(), 'Equipped with our five senses, we are not simply spectators of the universe — we are participants.', 'Carl Sagan', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'In science, one tries to tell people, in such a way as to be understood by everyone, something that no one ever knew before.', 'Paul Dirac', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'learning', 'curiosity'], true, 'science'),
(gen_random_uuid(), 'The scientist does not study nature because it is useful to do so. He studies it because he takes pleasure in it, and he takes pleasure in it because it is beautiful.', 'Henri Poincare', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'Science is built up of facts, as a house is built of stones; but an accumulation of facts is no more a science than a heap of stones is a house.', 'Henri Poincare', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'learning', 'creativity'], true, 'science'),
(gen_random_uuid(), 'Doubt is the father of invention.', 'Galileo Galilei', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'creativity', 'learning'], true, 'science'),
(gen_random_uuid(), 'And yet it moves.', 'Galileo Galilei', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['discipline', 'wisdom', 'curiosity'], true, 'science'),
(gen_random_uuid(), 'Nature is relentless and unchangeable, and it is indifferent as to whether its hidden reasons and actions are understandable to man or not.', 'Galileo Galilei', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'curiosity', 'learning'], true, 'science'),
(gen_random_uuid(), 'I think nature''s imagination is so much greater than man''s — she''s never going to let us relax.', 'Richard Feynman', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'When you get as abstract as you want, you lose something of the thrill of scientific discovery.', 'Richard Feynman', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'learning', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'The most powerful tool we have is our ability to change our minds.', 'Jane Goodall', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'self_improvement', 'learning'], true, 'science'),
(gen_random_uuid(), 'We need the tonic of wildness — to wade sometimes in marshes where the bittern and the meadow-hen lurk.', 'Henry David Thoreau', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'What is life? It is the flash of a firefly in the night. It is the breath of a buffalo in the wintertime.', 'Crowfoot', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'curiosity', 'learning'], true, 'science'),
(gen_random_uuid(), 'The history of science is the history of humanity''s attempt to understand the patterns of nature.', 'Isaac Asimov', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'learning', 'curiosity'], true, 'science'),
(gen_random_uuid(), 'The universe is a single atom: the convergence of science and spirituality.', 'Tenzin Gyatso', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'curiosity', 'learning'], true, 'science'),
(gen_random_uuid(), 'What is now proved was once only imagined.', 'William Blake', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['creativity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'Energy cannot be created or destroyed; it can only be changed from one form to another.', 'Albert Einstein', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'curiosity', 'learning'], true, 'science'),
(gen_random_uuid(), 'The cosmos is all that is or ever was or ever will be.', 'Carl Sagan', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'curiosity', 'learning'], true, 'science'),
(gen_random_uuid(), 'Science is a verb, not a noun — it is the active pursuit of understanding.', 'Neil deGrasse Tyson', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['learning', 'curiosity', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'We do not inherit the earth from our ancestors; we borrow it from our children.', 'Rachel Carson', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'self_improvement', 'learning'], true, 'science'),
(gen_random_uuid(), 'The aim of science is to seek the simplest explanations of complex facts. Seek simplicity and distrust it.', 'Alfred North Whitehead', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'learning', 'focus'], true, 'science'),
(gen_random_uuid(), 'In questions of science, the authority of a thousand is not worth the humble reasoning of a single individual.', 'Galileo Galilei', 'philosophy', 'en', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'curiosity', 'learning'], true, 'science')

ON CONFLICT (text, author) DO NOTHING;

COMMIT;
