-- 031_coding_fundamentals_en.sql
-- MindScrolling — Coding Mode: Fundamentals batch (English)
-- 250 quotes: algorithms, data structures, clean code, refactoring, testing,
--   debugging, problem solving, computational thinking, abstraction,
--   encapsulation, recursion, sorting, Big O, design patterns, SOLID, DRY,
--   KISS, software craftsmanship
--
-- All rows:
--   category       = 'philosophy'
--   lang           = 'en'
--   swipe_dir      = 'down'
--   pack_name      = 'free'
--   is_premium     = false
--   content_type   = 'coding'
--   sub_category   = 'fundamentals'
--   is_hidden_mode = true
--   locked_by      = 'coding'
-- Run in Supabase SQL Editor

BEGIN;

-- ══════════════════════════════════════════════════════════════════════════════
-- CODING FUNDAMENTALS — ENGLISH (250 quotes)
-- ══════════════════════════════════════════════════════════════════════════════

INSERT INTO quotes (id, text, author, category, lang, swipe_dir, pack_name, is_premium, content_type, sub_category, tags, is_hidden_mode, locked_by) VALUES

-- Donald Knuth (1–18)
(gen_random_uuid(), 'An algorithm must be seen to be believed.', 'Donald Knuth', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['learning', 'wisdom', 'curiosity'], true, 'coding'),
(gen_random_uuid(), 'Premature optimization is the root of all evil.', 'Donald Knuth', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['wisdom', 'discipline', 'focus'], true, 'coding'),
(gen_random_uuid(), 'Beware of bugs in the above code; I have only proved it correct, not tried it.', 'Donald Knuth', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['wisdom', 'curiosity', 'learning'], true, 'coding'),
(gen_random_uuid(), 'The process of preparing programs for a digital computer is especially attractive because it not only can be economically and scientifically rewarding, it can also be an aesthetic experience.', 'Donald Knuth', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['creativity', 'wisdom', 'learning'], true, 'coding'),
(gen_random_uuid(), 'Science is what we understand well enough to explain to a computer. Art is everything else we do.', 'Donald Knuth', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['creativity', 'wisdom', 'learning'], true, 'coding'),
(gen_random_uuid(), 'The art of programming is the art of organizing complexity.', 'Donald Knuth', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline', 'wisdom', 'focus'], true, 'coding'),
(gen_random_uuid(), 'People who are more than casually interested in computers should have at least some idea of what the underlying hardware is like.', 'Donald Knuth', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['learning', 'wisdom', 'curiosity'], true, 'coding'),
(gen_random_uuid(), 'Let us change our traditional attitude to the construction of programs: Instead of imagining that our main task is to instruct a computer what to do, let us concentrate rather on explaining to human beings what we want a computer to do.', 'Donald Knuth', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['wisdom', 'creativity', 'learning'], true, 'coding'),
(gen_random_uuid(), 'A mathematical formula should never be ''owned'' by anybody! Mathematics belongs to God.', 'Donald Knuth', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['wisdom', 'curiosity', 'learning'], true, 'coding'),
(gen_random_uuid(), 'If you find that you''re spending almost all your time on theory, start turning some attention to practical things; it will improve your theories.', 'Donald Knuth', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline', 'self_improvement', 'wisdom'], true, 'coding'),
(gen_random_uuid(), 'Random numbers should not be generated with a method chosen at random.', 'Donald Knuth', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['wisdom', 'discipline', 'focus'], true, 'coding'),
(gen_random_uuid(), 'The best programs are written so that computing machines can perform them quickly and so that human beings can understand them clearly.', 'Donald Knuth', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['wisdom', 'creativity', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'I have only made this letter longer because I have not had the time to make it shorter — and the same is true of software design.', 'Donald Knuth', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline', 'wisdom', 'focus'], true, 'coding'),
(gen_random_uuid(), 'Computers are good at following instructions, but not at reading your mind.', 'Donald Knuth', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['wisdom', 'learning', 'curiosity'], true, 'coding'),
(gen_random_uuid(), 'Continuous attention to technical excellence and good design enhances agility.', 'Donald Knuth', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline', 'wisdom', 'focus'], true, 'coding'),
(gen_random_uuid(), 'Software is hard. It''s harder than anything else I''ve ever had to do.', 'Donald Knuth', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline', 'wisdom', 'self_improvement'], true, 'coding'),
(gen_random_uuid(), 'The real problem is that programmers have spent far too much time worrying about efficiency in the wrong places and at the wrong times.', 'Donald Knuth', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['wisdom', 'discipline', 'focus'], true, 'coding'),
(gen_random_uuid(), 'An algorithm is a finite set of rules that gives a sequence of operations for solving a specific type of problem.', 'Donald Knuth', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['learning', 'wisdom', 'curiosity'], true, 'coding'),

-- Robert C. Martin (19–36)
(gen_random_uuid(), 'Clean code always looks like it was written by someone who cares.', 'Robert C. Martin', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline', 'wisdom', 'focus'], true, 'coding'),
(gen_random_uuid(), 'The only way to make the deadline — the only way to go fast — is to keep the code as clean as possible at all times.', 'Robert C. Martin', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline', 'focus', 'wisdom'], true, 'coding'),
(gen_random_uuid(), 'Truth can only be found in one place: the code.', 'Robert C. Martin', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['wisdom', 'discipline', 'learning'], true, 'coding'),
(gen_random_uuid(), 'A function should do one thing, do it well, and do it only.', 'Robert C. Martin', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline', 'focus', 'wisdom'], true, 'coding'),
(gen_random_uuid(), 'The first rule of functions is that they should be small. The second rule of functions is that they should be smaller than that.', 'Robert C. Martin', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline', 'wisdom', 'focus'], true, 'coding'),
(gen_random_uuid(), 'You are not done when it works. You are done when it is right.', 'Robert C. Martin', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline', 'wisdom', 'self_improvement'], true, 'coding'),
(gen_random_uuid(), 'Writing clean code is what you must do in order to call yourself a professional.', 'Robert C. Martin', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline', 'wisdom', 'self_improvement'], true, 'coding'),
(gen_random_uuid(), 'The ratio of time spent reading code versus writing is well over 10 to 1. We are constantly reading old code as part of the effort to write new code.', 'Robert C. Martin', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['learning', 'discipline', 'wisdom'], true, 'coding'),
(gen_random_uuid(), 'Leave the campground cleaner than you found it.', 'Robert C. Martin', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline', 'self_improvement', 'focus'], true, 'coding'),
(gen_random_uuid(), 'Any fool can write code that a computer can understand. Good programmers write code that humans can understand.', 'Robert C. Martin', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['wisdom', 'discipline', 'creativity'], true, 'coding'),
(gen_random_uuid(), 'The purpose of software testing is to find failures so that defects may be discovered and corrected.', 'Robert C. Martin', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline', 'learning', 'focus'], true, 'coding'),
(gen_random_uuid(), 'Test code is just as important as production code. It is not a second-class citizen.', 'Robert C. Martin', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline', 'wisdom', 'focus'], true, 'coding'),
(gen_random_uuid(), 'Refactoring is the process of changing a software system in such a way that it does not alter the external behavior of the code yet improves its internal structure.', 'Robert C. Martin', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline', 'wisdom', 'self_improvement'], true, 'coding'),
(gen_random_uuid(), 'It is not enough to write the tests — you must also write tests for the tests. Just kidding. But run them constantly.', 'Robert C. Martin', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline', 'focus', 'learning'], true, 'coding'),
(gen_random_uuid(), 'Good architecture allows major decisions to be deferred.', 'Robert C. Martin', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['wisdom', 'discipline', 'focus'], true, 'coding'),
(gen_random_uuid(), 'Duplication is the primary enemy of a well-designed system.', 'Robert C. Martin', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline', 'wisdom', 'focus'], true, 'coding'),
(gen_random_uuid(), 'One broken window — a badly designed piece of code, a poor decision — tells us the system is in decay.', 'Robert C. Martin', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['wisdom', 'discipline', 'self_improvement'], true, 'coding'),
(gen_random_uuid(), 'Before you can make code cleaner, you have to make it correct.', 'Robert C. Martin', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline', 'wisdom', 'focus'], true, 'coding'),

-- Andrew Hunt & David Thomas (37–50)
(gen_random_uuid(), 'Don''t repeat yourself. Every piece of knowledge must have a single, unambiguous, authoritative representation within a system.', 'Andrew Hunt', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline', 'wisdom', 'focus'], true, 'coding'),
(gen_random_uuid(), 'Fix the problem, not the blame.', 'Andrew Hunt', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['wisdom', 'discipline', 'self_improvement'], true, 'coding'),
(gen_random_uuid(), 'Don''t live with broken windows. Fix bad designs, wrong decisions, and poor code when you see them.', 'Andrew Hunt', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline', 'self_improvement', 'focus'], true, 'coding'),
(gen_random_uuid(), 'Be a catalyst for change. You can''t force change on people. Instead, show them how the future might be and help them participate in creating it.', 'Andrew Hunt', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['wisdom', 'creativity', 'self_improvement'], true, 'coding'),
(gen_random_uuid(), 'A good design is easier to change than a bad design.', 'David Thomas', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['wisdom', 'discipline', 'focus'], true, 'coding'),
(gen_random_uuid(), 'Prototype to learn. Code to deploy.', 'David Thomas', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['learning', 'discipline', 'focus'], true, 'coding'),
(gen_random_uuid(), 'Critically analyze what you read and hear. Don''t be swayed by vendors, media hype, or dogma.', 'David Thomas', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['wisdom', 'curiosity', 'learning'], true, 'coding'),
(gen_random_uuid(), 'You have agency. Always remember that you can always do something about the situation you are in.', 'Andrew Hunt', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['wisdom', 'self_improvement', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'Invest regularly in your knowledge portfolio. Make learning a habit.', 'Andrew Hunt', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['learning', 'self_improvement', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'Think of code as something that tends toward entropy. If you neglect it, it decays.', 'David Thomas', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline', 'wisdom', 'self_improvement'], true, 'coding'),
(gen_random_uuid(), 'Build software like you would build a town: a little at a time, with thought and care.', 'Andrew Hunt', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline', 'creativity', 'wisdom'], true, 'coding'),
(gen_random_uuid(), 'Abstractions live longer than details. Invest in abstractions.', 'David Thomas', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['wisdom', 'learning', 'focus'], true, 'coding'),
(gen_random_uuid(), 'The best code is no code at all. Every new line of code you willingly bring into the world is code that has to be debugged, code that has to be read and understood, code that has to be supported.', 'Andrew Hunt', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['wisdom', 'discipline', 'focus'], true, 'coding'),
(gen_random_uuid(), 'Make it work, make it right, make it fast — in that order.', 'David Thomas', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline', 'wisdom', 'focus'], true, 'coding'),

-- Frederick Brooks (51–60)
(gen_random_uuid(), 'The hardest single part of building a software system is deciding precisely what to build.', 'Frederick Brooks', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['wisdom', 'focus', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'Adding manpower to a late software project makes it later.', 'Frederick Brooks', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['wisdom', 'learning', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'The most important single decision a software architect makes is the choice of data structure.', 'Frederick Brooks', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['wisdom', 'discipline', 'focus'], true, 'coding'),
(gen_random_uuid(), 'There is no single development, in either technology or management technique, which by itself promises even one order-of-magnitude improvement within a decade in productivity, in reliability, in simplicity.', 'Frederick Brooks', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['wisdom', 'learning', 'curiosity'], true, 'coding'),
(gen_random_uuid(), 'A program is never less than 90% complete, and never more than 95% complete.', 'Frederick Brooks', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['wisdom', 'discipline', 'learning'], true, 'coding'),
(gen_random_uuid(), 'Plan to throw one away; you will, anyhow.', 'Frederick Brooks', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['wisdom', 'discipline', 'self_improvement'], true, 'coding'),
(gen_random_uuid(), 'Complexity is the enemy of reliability.', 'Frederick Brooks', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['wisdom', 'focus', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'The programmer, like the poet, works only slightly removed from pure thought-stuff. He builds his castles in the air, from air, creating by exertion of the imagination.', 'Frederick Brooks', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['creativity', 'wisdom', 'curiosity'], true, 'coding'),
(gen_random_uuid(), 'The bearing of a child takes nine months, no matter how many women are assigned.', 'Frederick Brooks', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['wisdom', 'discipline', 'learning'], true, 'coding'),
(gen_random_uuid(), 'How does a project get to be a year late? One day at a time.', 'Frederick Brooks', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['wisdom', 'discipline', 'focus'], true, 'coding'),

-- Edsger Dijkstra (61–74)
(gen_random_uuid(), 'Simplicity is a great virtue but it requires hard work to achieve it and education to appreciate it.', 'Edsger Dijkstra', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['wisdom', 'discipline', 'self_improvement'], true, 'coding'),
(gen_random_uuid(), 'Program testing can be used to show the presence of bugs, but never to show their absence.', 'Edsger Dijkstra', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['wisdom', 'learning', 'curiosity'], true, 'coding'),
(gen_random_uuid(), 'The question of whether a computer can think is no more interesting than the question of whether a submarine can swim.', 'Edsger Dijkstra', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['wisdom', 'curiosity', 'learning'], true, 'coding'),
(gen_random_uuid(), 'Competent programmers are fully aware of the strictly limited size of their own skulls; therefore they approach the programming task in full humility.', 'Edsger Dijkstra', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['wisdom', 'self_improvement', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'The computing scientist''s main challenge is not to get confused by the complexities of his own making.', 'Edsger Dijkstra', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['wisdom', 'focus', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'If debugging is the process of removing software bugs, then programming must be the process of putting them in.', 'Edsger Dijkstra', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['wisdom', 'curiosity', 'learning'], true, 'coding'),
(gen_random_uuid(), 'Object-oriented programming is an exceptionally bad idea which could only have originated in California.', 'Edsger Dijkstra', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['wisdom', 'curiosity', 'learning'], true, 'coding'),
(gen_random_uuid(), 'The art of programming is the art of organizing complexity, of mastering multitude and avoiding its bastard chaos as effectively as possible.', 'Edsger Dijkstra', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline', 'wisdom', 'focus'], true, 'coding'),
(gen_random_uuid(), 'A program that has not been tested does not work.', 'Edsger Dijkstra', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline', 'wisdom', 'learning'], true, 'coding'),
(gen_random_uuid(), 'Do not try to solve the general problem before solving a specific instance of it.', 'Edsger Dijkstra', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['wisdom', 'focus', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'The tools we use have a profound and devious influence on our thinking habits and, therefore, on our thinking abilities.', 'Edsger Dijkstra', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['wisdom', 'learning', 'curiosity'], true, 'coding'),
(gen_random_uuid(), 'Elegance is not a dispensable luxury but a quality that decides between success and failure.', 'Edsger Dijkstra', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['wisdom', 'creativity', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'We shall do a much better programming job, provided we approach the task with a full appreciation of its tremendous difficulty.', 'Edsger Dijkstra', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['wisdom', 'discipline', 'self_improvement'], true, 'coding'),
(gen_random_uuid(), 'Separation of concerns is one of the most important principles in software engineering.', 'Edsger Dijkstra', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline', 'wisdom', 'focus'], true, 'coding'),

-- Tony Hoare (75–82)
(gen_random_uuid(), 'There are two ways of constructing a software design: one way is to make it so simple that there are obviously no deficiencies, and the other way is to make it so complicated that there are no obvious deficiencies.', 'Tony Hoare', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['wisdom', 'discipline', 'focus'], true, 'coding'),
(gen_random_uuid(), 'I null reference: that was my billion-dollar mistake.', 'Tony Hoare', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['wisdom', 'learning', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'The price of reliability is the pursuit of the utmost simplicity.', 'Tony Hoare', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['wisdom', 'discipline', 'focus'], true, 'coding'),
(gen_random_uuid(), 'I call it my billion-dollar mistake. It was the invention of the null reference in 1965.', 'Tony Hoare', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['wisdom', 'learning', 'self_improvement'], true, 'coding'),
(gen_random_uuid(), 'Inside every large program is a small program struggling to get out.', 'Tony Hoare', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['wisdom', 'creativity', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'The first rule of software maintenance: if it ain''t broke, don''t fix it; if it is broke, find out why before touching it.', 'Tony Hoare', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['wisdom', 'discipline', 'focus'], true, 'coding'),
(gen_random_uuid(), 'Correctness is clearly the prime quality. If a system does not do what it is supposed to do, then everything else about it matters little.', 'Tony Hoare', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['wisdom', 'discipline', 'focus'], true, 'coding'),
(gen_random_uuid(), 'Software engineering is programming integrated over time.', 'Tony Hoare', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['wisdom', 'discipline', 'learning'], true, 'coding'),

-- Alan Kay (83–92)
(gen_random_uuid(), 'The best way to predict the future is to invent it.', 'Alan Kay', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['creativity', 'wisdom', 'curiosity'], true, 'coding'),
(gen_random_uuid(), 'Simple things should be simple, complex things should be possible.', 'Alan Kay', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['wisdom', 'discipline', 'creativity'], true, 'coding'),
(gen_random_uuid(), 'Most software today is very much like an Egyptian pyramid, with millions of bricks piled on top of each other, with no structural integrity, but just done by brute force and thousands of slaves.', 'Alan Kay', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['wisdom', 'creativity', 'curiosity'], true, 'coding'),
(gen_random_uuid(), 'Technology is anything that wasn''t around when you were born.', 'Alan Kay', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['wisdom', 'curiosity', 'learning'], true, 'coding'),
(gen_random_uuid(), 'A change in perspective is worth 80 IQ points.', 'Alan Kay', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['wisdom', 'creativity', 'self_improvement'], true, 'coding'),
(gen_random_uuid(), 'The computer revolution hasn''t happened yet.', 'Alan Kay', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['curiosity', 'wisdom', 'creativity'], true, 'coding'),
(gen_random_uuid(), 'Perspective is worth 80 IQ points. Seeing the problem from a new angle gives you an immense advantage.', 'Alan Kay', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['wisdom', 'creativity', 'learning'], true, 'coding'),
(gen_random_uuid(), 'Object-oriented programming to me means only messaging, local retention and protection and hiding of state-process, and extreme late-binding of all things.', 'Alan Kay', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['learning', 'wisdom', 'curiosity'], true, 'coding'),
(gen_random_uuid(), 'The real romance is out ahead and yet to come. The computer revolution hasn''t started yet.', 'Alan Kay', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['curiosity', 'creativity', 'wisdom'], true, 'coding'),
(gen_random_uuid(), 'Every programming language is just a way of thinking about computation, not a way of computing.', 'Alan Kay', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['wisdom', 'curiosity', 'learning'], true, 'coding'),

-- Barbara Liskov (93–98)
(gen_random_uuid(), 'Abstraction is the key to managing complexity in software.', 'Barbara Liskov', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['wisdom', 'discipline', 'focus'], true, 'coding'),
(gen_random_uuid(), 'A subtype must be substitutable for its supertype without altering the correctness of the program.', 'Barbara Liskov', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline', 'wisdom', 'learning'], true, 'coding'),
(gen_random_uuid(), 'Good abstractions hide details that don''t matter to the user and expose those that do.', 'Barbara Liskov', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['wisdom', 'discipline', 'focus'], true, 'coding'),
(gen_random_uuid(), 'The notion of a type in programming languages is fundamentally about abstraction.', 'Barbara Liskov', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['learning', 'wisdom', 'curiosity'], true, 'coding'),
(gen_random_uuid(), 'Encapsulation is not a goal but a consequence of good abstraction.', 'Barbara Liskov', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['wisdom', 'discipline', 'learning'], true, 'coding'),
(gen_random_uuid(), 'Data abstraction is the most fundamental tool for managing complexity in programs.', 'Barbara Liskov', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['wisdom', 'focus', 'discipline'], true, 'coding'),

-- Grady Booch (99–106)
(gen_random_uuid(), 'A fool with a tool is still a fool.', 'Grady Booch', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['wisdom', 'learning', 'self_improvement'], true, 'coding'),
(gen_random_uuid(), 'The function of good software is to make the complex appear to be simple.', 'Grady Booch', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['wisdom', 'creativity', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'Clean code is not written by following a set of rules. You don''t become a software craftsman by learning a list of heuristics.', 'Grady Booch', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['wisdom', 'self_improvement', 'learning'], true, 'coding'),
(gen_random_uuid(), 'The object model is an abstraction of reality, not a model of the software system itself.', 'Grady Booch', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['wisdom', 'learning', 'curiosity'], true, 'coding'),
(gen_random_uuid(), 'Software engineering is not computer science; it is not mathematics; it is an engineering discipline.', 'Grady Booch', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['wisdom', 'learning', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'Good architecture matters enormously. Like gravity, it is always operating in the background.', 'Grady Booch', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['wisdom', 'discipline', 'focus'], true, 'coding'),
(gen_random_uuid(), 'The software architect''s job is to make hard things possible, not merely to make easy things easy.', 'Grady Booch', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['wisdom', 'creativity', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'Every complex system that works evolved from a simpler system that worked.', 'Grady Booch', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['wisdom', 'learning', 'curiosity'], true, 'coding'),

-- Ward Cunningham (107–112)
(gen_random_uuid(), 'Debt in software happens when you take shortcuts that make code harder to change in the future.', 'Ward Cunningham', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['wisdom', 'discipline', 'self_improvement'], true, 'coding'),
(gen_random_uuid(), 'The best way to get the right answer on the internet is not to ask a question; it''s to post the wrong answer.', 'Ward Cunningham', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['wisdom', 'curiosity', 'learning'], true, 'coding'),
(gen_random_uuid(), 'Make the code say what you mean and mean what you say.', 'Ward Cunningham', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline', 'wisdom', 'focus'], true, 'coding'),
(gen_random_uuid(), 'Technical debt is a wonderful metaphor because everyone knows what it feels like to be in debt.', 'Ward Cunningham', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['wisdom', 'learning', 'self_improvement'], true, 'coding'),
(gen_random_uuid(), 'I coined the debt metaphor to explain why we sometimes had to refactor our code.', 'Ward Cunningham', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['wisdom', 'learning', 'curiosity'], true, 'coding'),
(gen_random_uuid(), 'Every pattern is a three-part rule, which expresses a relation between a context, a problem, and a solution.', 'Ward Cunningham', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['learning', 'wisdom', 'discipline'], true, 'coding'),

-- Kent Beck (113–122)
(gen_random_uuid(), 'Make it work, make it right, make it fast.', 'Kent Beck', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline', 'wisdom', 'focus'], true, 'coding'),
(gen_random_uuid(), 'I''m not a great programmer; I''m just a good programmer with great habits.', 'Kent Beck', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['self_improvement', 'discipline', 'wisdom'], true, 'coding'),
(gen_random_uuid(), 'The key is not to spend more time on tests, but to spend less time debugging.', 'Kent Beck', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline', 'wisdom', 'focus'], true, 'coding'),
(gen_random_uuid(), 'Test-driven development is a way of managing fear during programming.', 'Kent Beck', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline', 'self_improvement', 'wisdom'], true, 'coding'),
(gen_random_uuid(), 'Whenever you are tempted to type something into a print statement or a debugger expression, write it as a test instead.', 'Kent Beck', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline', 'focus', 'learning'], true, 'coding'),
(gen_random_uuid(), 'Any program feature without an automated test simply doesn''t exist.', 'Kent Beck', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline', 'wisdom', 'focus'], true, 'coding'),
(gen_random_uuid(), 'Small steps are the key to maintaining a feeling of progress.', 'Kent Beck', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline', 'self_improvement', 'focus'], true, 'coding'),
(gen_random_uuid(), 'Pair programming is not for everyone, but it works for a lot of people.', 'Kent Beck', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['learning', 'wisdom', 'creativity'], true, 'coding'),
(gen_random_uuid(), 'The goal of refactoring is to make the code easier to understand and cheaper to modify.', 'Kent Beck', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline', 'wisdom', 'self_improvement'], true, 'coding'),
(gen_random_uuid(), 'Do the simplest thing that could possibly work.', 'Kent Beck', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['wisdom', 'discipline', 'focus'], true, 'coding'),

-- Martin Fowler (123–132)
(gen_random_uuid(), 'Any fool can write code that a computer can understand. Good programmers write code that humans can understand.', 'Martin Fowler', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['wisdom', 'discipline', 'creativity'], true, 'coding'),
(gen_random_uuid(), 'Refactoring is a disciplined technique for restructuring an existing body of code, altering its internal structure without changing its external behavior.', 'Martin Fowler', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline', 'wisdom', 'self_improvement'], true, 'coding'),
(gen_random_uuid(), 'If you have to ask how much technical debt you have, you have a lot.', 'Martin Fowler', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['wisdom', 'learning', 'self_improvement'], true, 'coding'),
(gen_random_uuid(), 'When you feel the need to write a comment, first try to refactor the code so that any comment becomes superfluous.', 'Martin Fowler', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline', 'wisdom', 'focus'], true, 'coding'),
(gen_random_uuid(), 'Continuous integration doesn''t get rid of bugs, but it does make them dramatically easier to find and remove.', 'Martin Fowler', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline', 'learning', 'focus'], true, 'coding'),
(gen_random_uuid(), 'I believe that if you pay attention to design, code structure tends to get better over time.', 'Martin Fowler', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline', 'self_improvement', 'wisdom'], true, 'coding'),
(gen_random_uuid(), 'Patterns are a literary form for capturing the wisdom of experienced practitioners.', 'Martin Fowler', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['wisdom', 'learning', 'creativity'], true, 'coding'),
(gen_random_uuid(), 'Architecture is the decisions that you wish you could get right early in a project, but that you are not necessarily more likely to get them right than any other.', 'Martin Fowler', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['wisdom', 'learning', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'A class has one responsibility: to do whatever the class is named after.', 'Martin Fowler', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline', 'focus', 'wisdom'], true, 'coding'),
(gen_random_uuid(), 'The whole point of objects is that they are a technique to pack data with the functions that use that data.', 'Martin Fowler', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['learning', 'wisdom', 'curiosity'], true, 'coding'),

-- Linus Torvalds (133–141)
(gen_random_uuid(), 'Talk is cheap. Show me the code.', 'Linus Torvalds', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline', 'wisdom', 'focus'], true, 'coding'),
(gen_random_uuid(), 'Most good programmers do programming not because they expect to get paid or get adulation by the public, but because it is fun to program.', 'Linus Torvalds', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['curiosity', 'creativity', 'self_improvement'], true, 'coding'),
(gen_random_uuid(), 'Bad programmers worry about the code. Good programmers worry about data structures and their relationships.', 'Linus Torvalds', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['wisdom', 'discipline', 'learning'], true, 'coding'),
(gen_random_uuid(), 'Intelligence is the ability to avoid doing work, yet getting the work done.', 'Linus Torvalds', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['wisdom', 'creativity', 'curiosity'], true, 'coding'),
(gen_random_uuid(), 'In open source, we feel strongly that to really do something well, you have to get a lot of people involved.', 'Linus Torvalds', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['learning', 'creativity', 'wisdom'], true, 'coding'),
(gen_random_uuid(), 'Given enough eyeballs, all bugs are shallow.', 'Linus Torvalds', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['wisdom', 'learning', 'curiosity'], true, 'coding'),
(gen_random_uuid(), 'Software is like sex: it''s better when it''s free.', 'Linus Torvalds', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['wisdom', 'creativity', 'curiosity'], true, 'coding'),
(gen_random_uuid(), 'I often compare open source to science. To where science took this whole notion of developing ideas in the open and improving on other people''s work and trying to select the best.', 'Linus Torvalds', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['learning', 'curiosity', 'wisdom'], true, 'coding'),
(gen_random_uuid(), 'Portability is for people who cannot write new programs.', 'Linus Torvalds', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['wisdom', 'creativity', 'curiosity'], true, 'coding'),

-- Brian Kernighan & Dennis Ritchie (142–153)
(gen_random_uuid(), 'Debugging is twice as hard as writing the code in the first place. Therefore, if you write the code as cleverly as possible, you are, by definition, not smart enough to debug it.', 'Brian Kernighan', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['wisdom', 'discipline', 'focus'], true, 'coding'),
(gen_random_uuid(), 'The only way to learn a new programming language is by writing programs in it.', 'Brian Kernighan', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['learning', 'discipline', 'self_improvement'], true, 'coding'),
(gen_random_uuid(), 'Controlling complexity is the essence of computer programming.', 'Brian Kernighan', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['wisdom', 'discipline', 'focus'], true, 'coding'),
(gen_random_uuid(), 'Everyone knows that debugging is twice as hard as writing a program in the first place. So if you''re as clever as you can be when you write it, how will you ever debug it?', 'Brian Kernighan', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['wisdom', 'discipline', 'learning'], true, 'coding'),
(gen_random_uuid(), 'The most effective debugging tool is still careful thought, coupled with judiciously placed print statements.', 'Brian Kernighan', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['wisdom', 'discipline', 'focus'], true, 'coding'),
(gen_random_uuid(), 'If in doubt, don''t.', 'Brian Kernighan', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['wisdom', 'discipline', 'focus'], true, 'coding'),
(gen_random_uuid(), 'UNIX is simple. It just takes a genius to understand its simplicity.', 'Dennis Ritchie', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['wisdom', 'creativity', 'curiosity'], true, 'coding'),
(gen_random_uuid(), 'C is quirky, flawed, and an enormous success.', 'Dennis Ritchie', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['wisdom', 'curiosity', 'learning'], true, 'coding'),
(gen_random_uuid(), 'The C programming language — a language which combines the flexibility of assembly language with the power of assembly language.', 'Dennis Ritchie', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['wisdom', 'curiosity', 'creativity'], true, 'coding'),
(gen_random_uuid(), 'I tend to be better at naming things when I write code than when I write prose.', 'Brian Kernighan', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['creativity', 'wisdom', 'learning'], true, 'coding'),
(gen_random_uuid(), 'Good style means the reader never stops to wonder why you wrote something the way you did.', 'Brian Kernighan', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['wisdom', 'creativity', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'Keep it simple. As simple as possible. But no simpler.', 'Brian Kernighan', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['wisdom', 'discipline', 'focus'], true, 'coding'),

-- Jon Bentley (154–160)
(gen_random_uuid(), 'The most important principle of programming is the principle of simplicity.', 'Jon Bentley', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['wisdom', 'discipline', 'focus'], true, 'coding'),
(gen_random_uuid(), 'Efficiency comes from understanding the problem, not just the algorithm.', 'Jon Bentley', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['wisdom', 'learning', 'focus'], true, 'coding'),
(gen_random_uuid(), 'The performance of a program is determined by a small fraction of its code. Find that fraction.', 'Jon Bentley', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['wisdom', 'focus', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'Think before you code. A few minutes of design saves hours of debugging.', 'Jon Bentley', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['wisdom', 'discipline', 'focus'], true, 'coding'),
(gen_random_uuid(), 'The right data structure can make an O(n²) algorithm look like O(n log n).', 'Jon Bentley', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['learning', 'wisdom', 'curiosity'], true, 'coding'),
(gen_random_uuid(), 'Beautiful code is a pleasure to read and easy to reason about.', 'Jon Bentley', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['creativity', 'wisdom', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'In designing algorithms, the time spent planning is rarely wasted.', 'Jon Bentley', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline', 'wisdom', 'focus'], true, 'coding'),

-- Harold Abelson & Gerald Sussman (161–170)
(gen_random_uuid(), 'Programs must be written for people to read, and only incidentally for machines to execute.', 'Harold Abelson', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['wisdom', 'creativity', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'The intellectual content of a procedure is not in the steps but in the relationship between the steps.', 'Harold Abelson', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['wisdom', 'learning', 'curiosity'], true, 'coding'),
(gen_random_uuid(), 'In computer science, there''s a notion that all problems can be solved by adding another level of indirection.', 'Harold Abelson', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['wisdom', 'creativity', 'learning'], true, 'coding'),
(gen_random_uuid(), 'The complexity of software is an essential property, not an accidental one.', 'Gerald Sussman', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['wisdom', 'curiosity', 'learning'], true, 'coding'),
(gen_random_uuid(), 'The power of a language is not merely what it lets you say, but what it makes it natural to think.', 'Gerald Sussman', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['wisdom', 'creativity', 'curiosity'], true, 'coding'),
(gen_random_uuid(), 'Recursion is the key to unlocking many problems that would otherwise be intractable.', 'Gerald Sussman', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['learning', 'wisdom', 'curiosity'], true, 'coding'),
(gen_random_uuid(), 'A language that doesn''t affect the way you think about programming is not worth knowing.', 'Harold Abelson', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['wisdom', 'learning', 'curiosity'], true, 'coding'),
(gen_random_uuid(), 'Iteration lets the programmer say ''do this N times''. Recursion lets the programmer say ''keep doing this until you''re done''.', 'Harold Abelson', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['learning', 'curiosity', 'wisdom'], true, 'coding'),
(gen_random_uuid(), 'The key to understanding recursion is: a recursive solution must reduce the problem toward a base case.', 'Gerald Sussman', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['learning', 'wisdom', 'focus'], true, 'coding'),
(gen_random_uuid(), 'Every powerful technique in computer science was once a radical idea.', 'Harold Abelson', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['curiosity', 'creativity', 'wisdom'], true, 'coding'),

-- Peter Norvig (171–178)
(gen_random_uuid(), 'The best way to accelerate a slow programmer is to give them better algorithms, not a faster computer.', 'Peter Norvig', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['wisdom', 'learning', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'The lesson is: instead of imagining that our main task is to instruct a computer what to do, we should concentrate on explaining to humans what we want.', 'Peter Norvig', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['wisdom', 'creativity', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'Practice is the only path to mastery. Ten thousand hours of deliberate practice.', 'Peter Norvig', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline', 'self_improvement', 'learning'], true, 'coding'),
(gen_random_uuid(), 'Programmers are not to be measured by their ingenuity and their logic but by the completeness of their case analysis.', 'Peter Norvig', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['wisdom', 'discipline', 'focus'], true, 'coding'),
(gen_random_uuid(), 'Understanding Big O notation is the difference between a programmer who guesses performance and one who knows it.', 'Peter Norvig', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['learning', 'wisdom', 'curiosity'], true, 'coding'),
(gen_random_uuid(), 'A good algorithm is a key insight expressed in code.', 'Peter Norvig', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['wisdom', 'creativity', 'learning'], true, 'coding'),
(gen_random_uuid(), 'The purpose of abstraction is not to be vague, but to create a new semantic level in which one can be absolutely precise.', 'Peter Norvig', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['wisdom', 'discipline', 'learning'], true, 'coding'),
(gen_random_uuid(), 'Fifteen years ago I committed to consistently improving my programming knowledge. That commitment still pays dividends every day.', 'Peter Norvig', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['self_improvement', 'discipline', 'learning'], true, 'coding'),

-- Steve McConnell (179–188)
(gen_random_uuid(), 'Good code is its own best documentation.', 'Steve McConnell', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['wisdom', 'discipline', 'creativity'], true, 'coding'),
(gen_random_uuid(), 'The purpose of software development is to reduce complexity, not add to it.', 'Steve McConnell', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['wisdom', 'discipline', 'focus'], true, 'coding'),
(gen_random_uuid(), 'The primary goal of software design is managing accidental complexity.', 'Steve McConnell', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['wisdom', 'discipline', 'focus'], true, 'coding'),
(gen_random_uuid(), 'The most important single aspect of software development is to be clear about what you are trying to build.', 'Steve McConnell', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['wisdom', 'focus', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'Measure twice, cut once. Think twice, code once.', 'Steve McConnell', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline', 'wisdom', 'focus'], true, 'coding'),
(gen_random_uuid(), 'Software projects fail for one of two reasons: bad people or bad management. The two are almost always related.', 'Steve McConnell', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['wisdom', 'learning', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'The single most important thing you can do to improve your programming ability is to read good code.', 'Steve McConnell', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['learning', 'self_improvement', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'Trying to improve software quality by increasing the amount of testing is like trying to lose weight by weighing yourself more often.', 'Steve McConnell', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['wisdom', 'discipline', 'learning'], true, 'coding'),
(gen_random_uuid(), 'Managing software projects is like herding cats, but the cats are invisible and move in directions you don''t expect.', 'Steve McConnell', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['wisdom', 'curiosity', 'learning'], true, 'coding'),
(gen_random_uuid(), 'Of all the ways to fail a project, running out of time is the most common — and the most preventable.', 'Steve McConnell', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline', 'wisdom', 'focus'], true, 'coding'),

-- John Carmack (189–196)
(gen_random_uuid(), 'Focus is a matter of deciding what things you''re not going to do.', 'John Carmack', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['focus', 'wisdom', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'In the information age, the barriers just aren''t there. The barriers are self-imposed.', 'John Carmack', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['self_improvement', 'wisdom', 'creativity'], true, 'coding'),
(gen_random_uuid(), 'If you''re not doing some things that are crazy, then you''re doing the wrong things.', 'John Carmack', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['creativity', 'curiosity', 'wisdom'], true, 'coding'),
(gen_random_uuid(), 'When you understand something at the bit level, the rest is easy.', 'John Carmack', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['learning', 'wisdom', 'curiosity'], true, 'coding'),
(gen_random_uuid(), 'The real performance wins come from algorithmic improvements, not hardware.', 'John Carmack', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['wisdom', 'learning', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'Focused, hard work is the real key to success. Keep your eyes on the goal and just keep taking the next step towards completing it.', 'John Carmack', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline', 'focus', 'self_improvement'], true, 'coding'),
(gen_random_uuid(), 'Sometimes the elegant implementation is just a function. Not a method. Not a class. Not a framework. Just a function.', 'John Carmack', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['wisdom', 'creativity', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'Spending a week writing a fast renderer is much less impressive than spending ten minutes writing one that''s already fast enough.', 'John Carmack', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['wisdom', 'discipline', 'focus'], true, 'coding'),

-- Rich Hickey (197–204)
(gen_random_uuid(), 'Simplicity is the ultimate sophistication — in code as in life.', 'Rich Hickey', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['wisdom', 'discipline', 'creativity'], true, 'coding'),
(gen_random_uuid(), 'Complexity is not inherent in problems; it''s what we add to solutions.', 'Rich Hickey', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['wisdom', 'discipline', 'focus'], true, 'coding'),
(gen_random_uuid(), 'Simplicity is hard work. But the amazing thing is that in the long run, it is also easier.', 'Rich Hickey', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline', 'wisdom', 'self_improvement'], true, 'coding'),
(gen_random_uuid(), 'If you make a general tool and try to sell it, you often fail. If you make a specific tool and try to understand it, you often succeed.', 'Rich Hickey', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['wisdom', 'creativity', 'learning'], true, 'coding'),
(gen_random_uuid(), 'We''re not building things out of atoms; we''re building things out of ideas. And ideas have no weight, and you can move fast.', 'Rich Hickey', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['creativity', 'wisdom', 'curiosity'], true, 'coding'),
(gen_random_uuid(), 'The reason data is simple is that it has no behavior. Data just is.', 'Rich Hickey', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['wisdom', 'learning', 'curiosity'], true, 'coding'),
(gen_random_uuid(), 'Programming is not about typing, it''s about thinking.', 'Rich Hickey', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['wisdom', 'focus', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'Every time you complect two things, you double the amount of thinking required to work with either.', 'Rich Hickey', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['wisdom', 'discipline', 'focus'], true, 'coding'),

-- Paul Graham (205–212)
(gen_random_uuid(), 'The test of a programming language is whether it makes programs shorter, clearer, and more reliable.', 'Paul Graham', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['wisdom', 'creativity', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'Hackers are not usually interested in money because they''re interested in doing interesting work.', 'Paul Graham', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['curiosity', 'creativity', 'wisdom'], true, 'coding'),
(gen_random_uuid(), 'Great software, likewise, requires a fanatical devotion to beauty.', 'Paul Graham', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['creativity', 'discipline', 'wisdom'], true, 'coding'),
(gen_random_uuid(), 'The best hackers tend to have an almost physical sense of how well their code is working.', 'Paul Graham', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['wisdom', 'creativity', 'learning'], true, 'coding'),
(gen_random_uuid(), 'In most fields, the best work is done by those who find their subject fascinating.', 'Paul Graham', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['curiosity', 'creativity', 'self_improvement'], true, 'coding'),
(gen_random_uuid(), 'Brevity is underrated. If you can say something clearly in fewer words, you should.', 'Paul Graham', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['wisdom', 'discipline', 'focus'], true, 'coding'),
(gen_random_uuid(), 'Beautiful code is both an aesthetic pleasure and a practical advantage.', 'Paul Graham', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['creativity', 'wisdom', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'The best way to learn to program is to write programs. There''s no substitute.', 'Paul Graham', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['learning', 'discipline', 'self_improvement'], true, 'coding'),

-- Eric Raymond (213–220)
(gen_random_uuid(), 'Design for the future, because it will be here sooner than you think.', 'Eric Raymond', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['wisdom', 'creativity', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'Every good work of software starts by scratching a developer''s personal itch.', 'Eric Raymond', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['creativity', 'curiosity', 'self_improvement'], true, 'coding'),
(gen_random_uuid(), 'Release early, release often. And listen to your customers.', 'Eric Raymond', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline', 'self_improvement', 'learning'], true, 'coding'),
(gen_random_uuid(), 'Good security comes from a habit of writing code that is obviously correct, not from cleverness.', 'Eric Raymond', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['wisdom', 'discipline', 'focus'], true, 'coding'),
(gen_random_uuid(), 'When you have to solve a problem, the right structure of the solution is often the structure of the problem itself.', 'Eric Raymond', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['wisdom', 'creativity', 'learning'], true, 'coding'),
(gen_random_uuid(), 'Perfection in design is achieved not when there is nothing more to add, but when there is nothing left to take away.', 'Eric Raymond', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['wisdom', 'discipline', 'creativity'], true, 'coding'),
(gen_random_uuid(), 'Rule of Modularity: Write simple parts connected by clean interfaces.', 'Eric Raymond', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline', 'wisdom', 'focus'], true, 'coding'),
(gen_random_uuid(), 'Rule of Clarity: Clarity is better than cleverness.', 'Eric Raymond', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['wisdom', 'discipline', 'creativity'], true, 'coding'),

-- Additional / topic-driven attributed quotes (221–250)
(gen_random_uuid(), 'The goal of computer science education is not to produce programmers, but to produce thinkers who can program.', 'Harold Abelson', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['wisdom', 'learning', 'curiosity'], true, 'coding'),
(gen_random_uuid(), 'A data structure is worth a thousand algorithms.', 'Alan Kay', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['wisdom', 'learning', 'curiosity'], true, 'coding'),
(gen_random_uuid(), 'Big O notation is the language we use to describe the efficiency of algorithms. Learn it until it is second nature.', 'Jon Bentley', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['learning', 'wisdom', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'O(n log n) is the gold standard: fast enough for almost everything, achievable with a good comparison sort.', 'Donald Knuth', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['learning', 'wisdom', 'curiosity'], true, 'coding'),
(gen_random_uuid(), 'A hash table is one of the most powerful data structures ever invented. Understand it deeply.', 'Brian Kernighan', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['learning', 'wisdom', 'curiosity'], true, 'coding'),
(gen_random_uuid(), 'A well-chosen data structure makes an algorithm obvious. A poorly chosen one makes it impossible.', 'Frederick Brooks', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['wisdom', 'discipline', 'learning'], true, 'coding'),
(gen_random_uuid(), 'Binary search is humanity''s greatest algorithmic gift to itself: logarithmic access in a sorted world.', 'Donald Knuth', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['learning', 'wisdom', 'curiosity'], true, 'coding'),
(gen_random_uuid(), 'Sorting is not just about ordering data — it is the foundation upon which binary search, merges, and countless optimizations are built.', 'Jon Bentley', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['learning', 'wisdom', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'Design patterns are reusable solutions to commonly occurring problems in software design. They are not prescriptions, they are vocabularies.', 'Grady Booch', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['learning', 'wisdom', 'creativity'], true, 'coding'),
(gen_random_uuid(), 'The SOLID principles are not laws — they are guidelines. Apply them with judgment, not dogma.', 'Robert C. Martin', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['wisdom', 'discipline', 'self_improvement'], true, 'coding'),
(gen_random_uuid(), 'Open for extension, closed for modification. The open-closed principle is perhaps the most important principle in object-oriented design.', 'Robert C. Martin', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline', 'wisdom', 'focus'], true, 'coding'),
(gen_random_uuid(), 'Computational thinking is a skill as fundamental as reading, writing, and arithmetic.', 'Jeannette Wing', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['learning', 'wisdom', 'self_improvement'], true, 'coding'),
(gen_random_uuid(), 'Computational thinking means thinking recursively, thinking in terms of abstractions, and decomposing large problems into smaller ones.', 'Jeannette Wing', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['learning', 'wisdom', 'curiosity'], true, 'coding'),
(gen_random_uuid(), 'Encapsulation is the art of hiding the complexity that is not your business.', 'Grady Booch', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['wisdom', 'discipline', 'focus'], true, 'coding'),
(gen_random_uuid(), 'Every act of refactoring is an act of professional courage.', 'Martin Fowler', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline', 'self_improvement', 'wisdom'], true, 'coding'),
(gen_random_uuid(), 'The DRY principle is about knowledge, not just code. Every piece of knowledge must have a single authoritative representation.', 'Andrew Hunt', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['wisdom', 'discipline', 'focus'], true, 'coding'),
(gen_random_uuid(), 'KISS: Keep It Simple, Stupid. The simplest solution that works is usually the best.', 'Kelly Johnson', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['wisdom', 'discipline', 'focus'], true, 'coding'),
(gen_random_uuid(), 'When in doubt, don''t add it. You aren''t gonna need it.', 'Kent Beck', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline', 'wisdom', 'focus'], true, 'coding'),
(gen_random_uuid(), 'Software craftsmanship is about two things: writing great software and taking responsibility for your work.', 'Robert C. Martin', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline', 'self_improvement', 'wisdom'], true, 'coding'),
(gen_random_uuid(), 'A craftsman takes pride in quality. A software craftsman takes pride in clean, tested, working code.', 'Andrew Hunt', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline', 'self_improvement', 'wisdom'], true, 'coding'),
(gen_random_uuid(), 'To iterate is human; to recurse, divine.', 'Peter Deutsch', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['wisdom', 'curiosity', 'creativity'], true, 'coding'),
(gen_random_uuid(), 'Recursion is just induction made executable.', 'Gerald Sussman', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['learning', 'wisdom', 'curiosity'], true, 'coding'),
(gen_random_uuid(), 'An interface is a contract between the caller and the implementer. Respect it or suffer the consequences.', 'Barbara Liskov', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline', 'wisdom', 'focus'], true, 'coding'),
(gen_random_uuid(), 'The problem with object-oriented languages is they''ve got all this implicit environment that they carry around with them.', 'Rich Hickey', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['wisdom', 'curiosity', 'learning'], true, 'coding'),
(gen_random_uuid(), 'First, solve the problem. Then, write the code.', 'John Johnson', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['wisdom', 'discipline', 'focus'], true, 'coding'),
(gen_random_uuid(), 'The most disastrous thing that you can ever learn is your first programming language.', 'Alan Kay', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['wisdom', 'learning', 'curiosity'], true, 'coding'),
(gen_random_uuid(), 'Testing shows the presence, not the absence, of bugs. You can never prove software correct — only ever disprove it.', 'Edsger Dijkstra', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['wisdom', 'learning', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'Abstraction is selective ignorance. You choose to ignore some details so you can see the important ones more clearly.', 'Andrew Hunt', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['wisdom', 'focus', 'creativity'], true, 'coding'),
(gen_random_uuid(), 'When you write code without tests, you are not actually done. You are only half done.', 'Kent Beck', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline', 'wisdom', 'self_improvement'], true, 'coding'),
(gen_random_uuid(), 'The craft of programming begins with empathy, not syntax. Empathy for users. Empathy for future maintainers.', 'Kent Beck', 'philosophy', 'en', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['wisdom', 'creativity', 'self_improvement'], true, 'coding')

ON CONFLICT (text, author) DO NOTHING;

COMMIT;
