-- 032_science_general_es.sql
-- MindScrolling — Science Mode: general_science ES (250 quotes)
-- Topics: método científico, descubrimientos, naturaleza, evolución, biología,
--         química, medio ambiente, medicina, neurociencia, genética, ecología,
--         geología, astronomía básica
--
-- All rows:
--   category       = 'philosophy'
--   lang           = 'es'
--   swipe_dir      = 'down'
--   pack_name      = 'free'
--   is_premium     = false
--   content_type   = 'science'
--   sub_category   = 'general_science'
--   is_hidden_mode = true
--   locked_by      = 'science'
-- Run in Supabase SQL Editor

BEGIN;

-- ══════════════════════════════════════════════════════════════════════════════
-- GENERAL SCIENCE — SPANISH (250 quotes)
-- ══════════════════════════════════════════════════════════════════════════════

INSERT INTO quotes (id, text, author, category, lang, swipe_dir, pack_name, is_premium, content_type, sub_category, tags, is_hidden_mode, locked_by) VALUES

-- Carl Sagan (1–16)
(gen_random_uuid(), 'El cosmos es todo lo que es, todo lo que fue y todo lo que será.', 'Carl Sagan', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'En algún lugar, algo increíble espera ser descubierto.', 'Carl Sagan', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'learning', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'La ciencia no es solo compatible con la espiritualidad; es una fuente profunda de espiritualidad.', 'Carl Sagan', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'curiosity', 'learning'], true, 'science'),
(gen_random_uuid(), 'Vivimos en una sociedad profundamente dependiente de la ciencia y la tecnología, en la que nadie sabe nada de estos temas.', 'Carl Sagan', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['learning', 'wisdom', 'self_improvement'], true, 'science'),
(gen_random_uuid(), 'La extinción es la regla. La supervivencia es la excepción.', 'Carl Sagan', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'curiosity', 'learning'], true, 'science'),
(gen_random_uuid(), 'El cerebro humano es el objeto más complejo del universo conocido y es la única herramienta con la que podemos estudiarlo.', 'Carl Sagan', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'learning', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'Cada vez que una tribu ha adoptado el pensamiento científico, la ciencia ha prosperado y la humanidad también.', 'Carl Sagan', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['learning', 'self_improvement', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'La Tierra es el único mundo conocido que alberga vida. No hay otro lugar, al menos en el futuro cercano, al que nuestra especie pudiera migrar.', 'Carl Sagan', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'curiosity', 'learning'], true, 'science'),
(gen_random_uuid(), 'Somos polvo de estrellas que contempla las estrellas.', 'Carl Sagan', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'La ciencia requiere valentía porque a menudo las verdades de la naturaleza son contrarias a nuestros prejuicios.', 'Carl Sagan', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['discipline', 'learning', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'Quien no recuerda el pasado está condenado a repetirlo; la ciencia es la memoria colectiva de la humanidad.', 'Carl Sagan', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['learning', 'wisdom', 'self_improvement'], true, 'science'),
(gen_random_uuid(), 'Un argumento es extraordinario cuando su evidencia también lo es.', 'Carl Sagan', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'learning', 'curiosity'], true, 'science'),
(gen_random_uuid(), 'La naturaleza no miente; somos nosotros quienes la malinterpretamos.', 'Carl Sagan', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'El universo no está obligado a ser comprensible para nosotros; es una maravilla que lo sea.', 'Carl Sagan', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'Conocerse a uno mismo es el comienzo de toda ciencia.', 'Carl Sagan', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['self_improvement', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'Preferir la ilusión a la realidad es el error más costoso que puede cometer una civilización.', 'Carl Sagan', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'learning', 'self_improvement'], true, 'science'),

-- Neil deGrasse Tyson (17–30)
(gen_random_uuid(), 'El universo es bajo ninguna obligación de tener sentido para ti.', 'Neil deGrasse Tyson', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'La exploración es lo que hacemos cuando no sabemos a dónde vamos.', 'Neil deGrasse Tyson', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'learning', 'self_improvement'], true, 'science'),
(gen_random_uuid(), 'El conocimiento científico es un cuerpo de afirmaciones acerca del universo de grado variable de certeza.', 'Neil deGrasse Tyson', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['learning', 'wisdom', 'curiosity'], true, 'science'),
(gen_random_uuid(), 'Todos somos conectados: entre sí biológicamente, con la Tierra químicamente y con el resto del universo atómicamente.', 'Neil deGrasse Tyson', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'La ignorancia es una semilla de la que no puede brotar más que más ignorancia, a menos que la reguemos con curiosidad.', 'Neil deGrasse Tyson', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'learning', 'self_improvement'], true, 'science'),
(gen_random_uuid(), 'La astrofísica no consuela el ego; su propósito es revelar la realidad.', 'Neil deGrasse Tyson', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'curiosity', 'learning'], true, 'science'),
(gen_random_uuid(), 'Si el universo no tuviera belleza no la podríamos percibir; que podamos hacerlo dice algo tanto del universo como de nosotros.', 'Neil deGrasse Tyson', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'La ciencia es una actitud ante el conocimiento, no un conjunto de respuestas definitivas.', 'Neil deGrasse Tyson', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['learning', 'curiosity', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'Cuando los niños miran el cielo nocturno con asombro, en ese momento se vuelven científicos.', 'Neil deGrasse Tyson', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'learning', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'Cuanto más del universo conocemos, más pequeños nos damos cuenta de que somos.', 'Neil deGrasse Tyson', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'wisdom', 'self_improvement'], true, 'science'),
(gen_random_uuid(), 'La razón por la que la ciencia funciona es que rechaza la verdad por autoridad y la acepta por evidencia.', 'Neil deGrasse Tyson', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['learning', 'wisdom', 'discipline'], true, 'science'),
(gen_random_uuid(), 'No hay mayor descubrimiento que aquel que cambia nuestra comprensión de lo que ya creíamos saber.', 'Neil deGrasse Tyson', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'learning', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'La muerte de las estrellas fertiliza las galaxias con los átomos que luego forman planetas y vida.', 'Neil deGrasse Tyson', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'Los datos son los hechos del universo; ignorarlos es elegir la oscuridad sobre la luz.', 'Neil deGrasse Tyson', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['learning', 'wisdom', 'discipline'], true, 'science'),

-- Richard Dawkins (31–44)
(gen_random_uuid(), 'La evolución ha sido observada. Solo que no ha sido observada mientras ocurre.', 'Richard Dawkins', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['learning', 'curiosity', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'El gen egoísta no tiene propósitos; es la selección natural la que crea la ilusión de propósito.', 'Richard Dawkins', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'learning', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'La biología es el estudio de cosas complicadas que parecen diseñadas pero no lo están.', 'Richard Dawkins', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'El universo que observamos tiene precisamente las propiedades que deberíamos esperar si no hay diseño ni propósito.', 'Richard Dawkins', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'curiosity', 'learning'], true, 'science'),
(gen_random_uuid(), 'El ADN es un libro de instrucciones escrito en un alfabeto de cuatro letras que tardó miles de millones de años en escribirse.', 'Richard Dawkins', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'learning', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'La selección natural es el único proceso conocido capaz de producir complejidad organizada a partir de la simplicidad.', 'Richard Dawkins', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['learning', 'wisdom', 'curiosity'], true, 'science'),
(gen_random_uuid(), 'Cada animal que ha existido es una prueba viviente de que todos sus ancestros sobrevivieron.', 'Richard Dawkins', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'La genética ha revelado que todos los seres vivos son primos en algún grado.', 'Richard Dawkins', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'learning', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'La ciencia ofrece una comprensión del mundo que ninguna mitología puede superar en poder explicativo.', 'Richard Dawkins', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['learning', 'wisdom', 'self_improvement'], true, 'science'),
(gen_random_uuid(), 'Ningún descubrimiento ha sido más liberador para la mente humana que la evolución por selección natural.', 'Richard Dawkins', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['learning', 'wisdom', 'curiosity'], true, 'science'),
(gen_random_uuid(), 'La diversidad de la vida es el resultado de cuatro mil millones de años de talla sin artista.', 'Richard Dawkins', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'Entender la evolución no es solo conocer un hecho; es ver el mundo con ojos completamente distintos.', 'Richard Dawkins', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['learning', 'curiosity', 'self_improvement'], true, 'science'),
(gen_random_uuid(), 'La herencia no transmite recuerdos sino instrucciones; ese es el genio del ADN.', 'Richard Dawkins', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'learning', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'Rechazar la evidencia por incomodidad es el mayor obstáculo para el progreso científico.', 'Richard Dawkins', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'discipline', 'learning'], true, 'science'),

-- Jane Goodall (45–57)
(gen_random_uuid(), 'Solo cuando comprendemos podemos proteger; solo cuando protegemos podemos preservar.', 'Jane Goodall', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'learning', 'self_improvement'], true, 'science'),
(gen_random_uuid(), 'Los chimpancés me enseñaron que no existe una brecha tan grande entre el ser humano y el resto del reino animal.', 'Jane Goodall', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['learning', 'curiosity', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'La observación paciente es el instrumento más poderoso del naturalista.', 'Jane Goodall', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['discipline', 'learning', 'focus'], true, 'science'),
(gen_random_uuid(), 'Cada individuo importa, cada individuo tiene un papel que desempeñar y cada individuo marca una diferencia.', 'Jane Goodall', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'self_improvement', 'learning'], true, 'science'),
(gen_random_uuid(), 'La mayor amenaza para nuestro planeta es la creencia de que alguien más lo salvará.', 'Jane Goodall', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['discipline', 'self_improvement', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'Los animales sienten emociones; negar eso no es ciencia, es prejuicio.', 'Jane Goodall', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'learning', 'curiosity'], true, 'science'),
(gen_random_uuid(), 'El campo es el mejor laboratorio; allí la naturaleza escribe sus propias hipótesis.', 'Jane Goodall', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['learning', 'curiosity', 'discipline'], true, 'science'),
(gen_random_uuid(), 'La biodiversidad que perdemos hoy no volverá nunca; esa es la urgencia de la conservación.', 'Jane Goodall', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'self_improvement', 'learning'], true, 'science'),
(gen_random_uuid(), 'Pasé años observando chimpancés y cada día confirmaba que el comportamiento social es mucho más antiguo que la humanidad.', 'Jane Goodall', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'learning', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'La empatía con otras especies es la base de una ecología responsable.', 'Jane Goodall', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'self_improvement', 'learning'], true, 'science'),
(gen_random_uuid(), 'Tenemos el deber de usar la inteligencia que nos dio la evolución para proteger la vida que la misma evolución creó.', 'Jane Goodall', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'discipline', 'self_improvement'], true, 'science'),
(gen_random_uuid(), 'La paciencia del científico de campo es la misma que la del bosque: infinita y silenciosa.', 'Jane Goodall', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['discipline', 'focus', 'learning'], true, 'science'),
(gen_random_uuid(), 'Cada especie que desaparece lleva consigo un capítulo de la historia de la vida en la Tierra.', 'Jane Goodall', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'learning', 'curiosity'], true, 'science'),

-- Rachel Carson (58–69)
(gen_random_uuid(), 'En la naturaleza nada existe solo; todo forma parte de una red de relaciones.', 'Rachel Carson', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'curiosity', 'learning'], true, 'science'),
(gen_random_uuid(), 'El hombre que contempla el mar en la noche oscura se sabe diminuto ante la creación.', 'Rachel Carson', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'La pregunta es si la humanidad se destruirá a sí misma o aprenderá a vivir con la Tierra.', 'Rachel Carson', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'self_improvement', 'learning'], true, 'science'),
(gen_random_uuid(), 'El sentido del asombro es un antídoto contra el aburrimiento y el desencanto.', 'Rachel Carson', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'Los pesticidas no deben llamarse pesticidas; son biocidas, asesinos de la vida en masa.', 'Rachel Carson', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'learning', 'self_improvement'], true, 'science'),
(gen_random_uuid(), 'Aquellos que contemplan la belleza de la Tierra encuentran reservas de fortaleza que durarán toda la vida.', 'Rachel Carson', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'curiosity', 'self_improvement'], true, 'science'),
(gen_random_uuid(), 'La ciencia ambiental no estudia el mundo tal como es, sino como podría dejar de ser.', 'Rachel Carson', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['learning', 'wisdom', 'discipline'], true, 'science'),
(gen_random_uuid(), 'Comprender el océano es comprender el corazón de este planeta.', 'Rachel Carson', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'learning', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'La ecología enseña que alterar un hilo de la red de la vida puede desgarrar toda la tela.', 'Rachel Carson', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'learning', 'curiosity'], true, 'science'),
(gen_random_uuid(), 'Si los hechos son los semillas que más tarde producen conocimiento y sabiduría, las emociones son el suelo fértil.', 'Rachel Carson', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['learning', 'wisdom', 'curiosity'], true, 'science'),
(gen_random_uuid(), 'Los contaminantes no respetan fronteras nacionales; la atmósfera es el bien común de todos.', 'Rachel Carson', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'self_improvement', 'learning'], true, 'science'),
(gen_random_uuid(), 'La primavera silenciosa no es una metáfora; puede ser nuestro futuro si no actuamos.', 'Rachel Carson', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'discipline', 'self_improvement'], true, 'science'),

-- David Attenborough (70–82)
(gen_random_uuid(), 'Esta Tierra maravillosa y magnífica que compartimos con millones de especies no es solo nuestra.', 'David Attenborough', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'curiosity', 'learning'], true, 'science'),
(gen_random_uuid(), 'No hay nada más inspirador en la naturaleza que ver cómo la vida encuentra su camino en los lugares más inhóspitos.', 'David Attenborough', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'La diversidad biológica de la Tierra es nuestro mayor tesoro y el más amenazado.', 'David Attenborough', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'self_improvement', 'learning'], true, 'science'),
(gen_random_uuid(), 'Los animales son mis amigos y no como a mis amigos.', 'David Attenborough', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'learning', 'curiosity'], true, 'science'),
(gen_random_uuid(), 'Cada criatura, por más pequeña que sea, tiene su lugar perfecto en el gran tapiz de la vida.', 'David Attenborough', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'La naturaleza, abandonada a sí misma, siempre encuentra el equilibrio; somos nosotros quienes lo perturbamos.', 'David Attenborough', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'learning', 'self_improvement'], true, 'science'),
(gen_random_uuid(), 'El futuro de la humanidad depende del futuro de la naturaleza; no son asuntos separados.', 'David Attenborough', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'discipline', 'self_improvement'], true, 'science'),
(gen_random_uuid(), 'Observar un ecosistema en funcionamiento es contemplar la inteligencia colectiva de millones de años.', 'David Attenborough', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'La comunicación de la ciencia al público no es un lujo; es una necesidad democrática.', 'David Attenborough', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['learning', 'wisdom', 'self_improvement'], true, 'science'),
(gen_random_uuid(), 'Los arrecifes de coral son las selvas tropicales del mar; su pérdida sería una catástrofe silenciosa.', 'David Attenborough', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'curiosity', 'learning'], true, 'science'),
(gen_random_uuid(), 'Cuando filmamos la naturaleza sin interferir, dejamos que el universo se explique a sí mismo.', 'David Attenborough', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'learning', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'Somos la única especie que puede destruir conscientemente la biosfera y la única que puede salvarla conscientemente.', 'David Attenborough', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'self_improvement', 'discipline'], true, 'science'),
(gen_random_uuid(), 'La selva tropical es el laboratorio más antiguo de la evolución; cada metro cuadrado es un libro de biología.', 'David Attenborough', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'learning', 'wisdom'], true, 'science'),

-- Marie Curie (83–95)
(gen_random_uuid(), 'Nada en la vida debe ser temido; solo debe ser comprendido. Ahora es momento de comprender más para temer menos.', 'Marie Curie', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'wisdom', 'self_improvement'], true, 'science'),
(gen_random_uuid(), 'Sea menos curioso sobre las personas y más sobre las ideas.', 'Marie Curie', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'focus', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'Me enseñaron que el camino del progreso no es ni rápido ni fácil.', 'Marie Curie', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['discipline', 'self_improvement', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'La radioactividad no es un fenómeno atómico sino un fenómeno del núcleo del átomo; esa distinción lo cambió todo.', 'Marie Curie', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['learning', 'curiosity', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'La ciencia tiene una gran belleza. El científico en su laboratorio es también un niño ante fenómenos naturales.', 'Marie Curie', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'Uno nunca debe tener miedo a lo desconocido; el desconocido es precisamente la frontera donde empieza la ciencia.', 'Marie Curie', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'discipline', 'learning'], true, 'science'),
(gen_random_uuid(), 'El laboratorio fue mi hogar; allí encontré la claridad que el mundo exterior rara vez ofrece.', 'Marie Curie', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['focus', 'discipline', 'learning'], true, 'science'),
(gen_random_uuid(), 'La perseverancia científica consiste en seguir cuando todos los experimentos fallan y solo queda la convicción de que hay algo que encontrar.', 'Marie Curie', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['discipline', 'focus', 'self_improvement'], true, 'science'),
(gen_random_uuid(), 'La primera condición de una investigación exitosa es la honestidad con los datos, incluso cuando contradicen tu hipótesis.', 'Marie Curie', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['discipline', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'Fui la primera en muchas cosas no porque fuera excepcional sino porque me negué a creer que había puertas cerradas.', 'Marie Curie', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['self_improvement', 'discipline', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'La curiosidad sin disciplina es fantasía; la disciplina sin curiosidad es rutina. La ciencia es ambas.', 'Marie Curie', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'discipline', 'learning'], true, 'science'),
(gen_random_uuid(), 'Un laboratorio es un lugar donde la naturaleza habla y el científico escucha con cuidado extremo.', 'Marie Curie', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['learning', 'discipline', 'focus'], true, 'science'),
(gen_random_uuid(), 'El descubrimiento del radio no fue un accidente; fue el resultado de años de trabajo sistemático y fe en la hipótesis.', 'Marie Curie', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['discipline', 'learning', 'self_improvement'], true, 'science'),

-- Charles Darwin (96–109)
(gen_random_uuid(), 'No es la especie más fuerte la que sobrevive, ni la más inteligente, sino la que mejor se adapta al cambio.', 'Charles Darwin', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'self_improvement', 'learning'], true, 'science'),
(gen_random_uuid(), 'La ignorancia genera más confianza que el conocimiento; son los que saben poco quienes afirman con certeza.', 'Charles Darwin', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'learning', 'self_improvement'], true, 'science'),
(gen_random_uuid(), 'Un hombre que se atreve a desperdiciar una hora de su tiempo no ha descubierto el valor de la vida.', 'Charles Darwin', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['discipline', 'focus', 'self_improvement'], true, 'science'),
(gen_random_uuid(), 'El libro de la naturaleza está abierto para todo el que tenga la paciencia de leerlo.', 'Charles Darwin', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'learning', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'La selección natural opera sobre la variación; sin diferencia entre individuos no hay evolución posible.', 'Charles Darwin', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['learning', 'curiosity', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'Las formas más bellas de la vida se han originado a partir de un comienzo tan sencillo como un solo organismo.', 'Charles Darwin', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'La geología de la Tierra es su autobiografía; las rocas son páginas escritas en millones de años.', 'Charles Darwin', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'learning', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'Confiar en la observación directa por encima de la autoridad es el principio que guió toda mi investigación.', 'Charles Darwin', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['discipline', 'learning', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'Todo animal es la suma de sus ancestros; la historia de la vida está inscrita en la anatomía.', 'Charles Darwin', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'El instinto de exploración y clasificación está en la base misma de la ciencia natural.', 'Charles Darwin', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'learning', 'discipline'], true, 'science'),
(gen_random_uuid(), 'Así como la geología ha revelado la historia de la Tierra, la biología revela la historia de la vida.', 'Charles Darwin', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['learning', 'curiosity', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'Las Islas Galápagos fueron para mí un microcosmos de la historia natural del planeta entero.', 'Charles Darwin', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'learning', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'La paciencia del naturalista debe igualar la paciencia de la naturaleza; ninguna observación es demasiado pequeña.', 'Charles Darwin', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['discipline', 'focus', 'learning'], true, 'science'),
(gen_random_uuid(), 'En el largo plazo de la historia natural, las pequeñas ventajas acumuladas se convierten en transformaciones radicales.', 'Charles Darwin', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'learning', 'self_improvement'], true, 'science'),

-- Louis Pasteur (110–121)
(gen_random_uuid(), 'En los campos de la observación, la suerte solo favorece a las mentes preparadas.', 'Louis Pasteur', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['discipline', 'learning', 'focus'], true, 'science'),
(gen_random_uuid(), 'La ciencia no tiene fronteras porque el conocimiento pertenece a la humanidad.', 'Louis Pasteur', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'learning', 'self_improvement'], true, 'science'),
(gen_random_uuid(), 'Decidme lo que sabes, lo que haces y te diré lo que eres.', 'Louis Pasteur', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'discipline', 'self_improvement'], true, 'science'),
(gen_random_uuid(), 'La fermentación no es un proceso químico simple; es la obra de seres vivos microscópicos que cambiaron la medicina.', 'Louis Pasteur', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['learning', 'curiosity', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'La teoría germinal no fue aceptada de inmediato; la resistencia al cambio es parte de la historia de la ciencia.', 'Louis Pasteur', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'learning', 'self_improvement'], true, 'science'),
(gen_random_uuid(), 'El microscopio reveló un mundo que existía antes de que lo descubriéramos; así funciona siempre la buena ciencia.', 'Louis Pasteur', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'learning', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'La vacunación es el triunfo de la prevención sobre la curación; pensar antes de que llegue la enfermedad.', 'Louis Pasteur', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'learning', 'discipline'], true, 'science'),
(gen_random_uuid(), 'Trabajar, descubrir, publicar sin miedo: esa es la ética del científico honesto.', 'Louis Pasteur', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['discipline', 'self_improvement', 'learning'], true, 'science'),
(gen_random_uuid(), 'La asepsia salvó más vidas que cualquier medicamento; limpiar las manos fue una revolución médica.', 'Louis Pasteur', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['learning', 'wisdom', 'self_improvement'], true, 'science'),
(gen_random_uuid(), 'El experimento es el juez supremo de toda hipótesis científica; no hay apelación posible.', 'Louis Pasteur', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['discipline', 'learning', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'Los microbios gobiernan el planeta; la mayoría son aliados, no enemigos.', 'Louis Pasteur', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'learning', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'Sin la teoría, la práctica es solo rutina guiada por hábito; la ciencia dignifica el oficio.', 'Louis Pasteur', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['learning', 'discipline', 'wisdom'], true, 'science'),

-- Alexander Fleming (122–132)
(gen_random_uuid(), 'Un buen observador nunca ignora un resultado inesperado; en él puede esconderse el descubrimiento más importante.', 'Alexander Fleming', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'learning', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'La penicilina fue un regalo de la naturaleza; mi único mérito fue no tirarlo a la basura.', 'Alexander Fleming', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'La suerte en la ciencia es la intersección entre la preparación y el momento oportuno.', 'Alexander Fleming', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['discipline', 'learning', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'El mundo entero se puede cambiar con un solo descubrimiento si tienes el coraje de seguirlo hasta sus consecuencias.', 'Alexander Fleming', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'discipline', 'self_improvement'], true, 'science'),
(gen_random_uuid(), 'La biología y la medicina son inseparables; entender la vida es la condición previa para sanarla.', 'Alexander Fleming', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['learning', 'wisdom', 'curiosity'], true, 'science'),
(gen_random_uuid(), 'Los antibióticos revolucionaron la medicina; también nos enseñaron que los microbios se adaptan y que debemos hacerlo nosotros también.', 'Alexander Fleming', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['learning', 'wisdom', 'self_improvement'], true, 'science'),
(gen_random_uuid(), 'Tener un ojo entrenado para lo anómalo es el primer talento del investigador.', 'Alexander Fleming', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'focus', 'learning'], true, 'science'),
(gen_random_uuid(), 'La naturaleza siempre tiene soluciones antes de que los humanos pensemos en los problemas.', 'Alexander Fleming', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'Un cultivo contaminado fue mi maestro más importante; aprendí más del accidente que de todos los experimentos planeados.', 'Alexander Fleming', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'learning', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'La resistencia bacteriana a los antibióticos es una advertencia: la naturaleza no perdona el uso irresponsable de sus dones.', 'Alexander Fleming', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'learning', 'self_improvement'], true, 'science'),
(gen_random_uuid(), 'El que busca con ojos limpios y mente abierta siempre encontrará algo que nadie esperaba encontrar.', 'Alexander Fleming', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'learning', 'wisdom'], true, 'science'),

-- Santiago Ramón y Cajal (133–145)
(gen_random_uuid(), 'Todo hombre puede ser, si se lo propone, escultor de su propio cerebro.', 'Santiago Ramón y Cajal', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['self_improvement', 'discipline', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'El cerebro es el órgano más complejo del universo conocido y el menos comprendido; por eso es el más fascinante.', 'Santiago Ramón y Cajal', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'learning', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'Las neuronas que se activan juntas se conectan juntas; así el aprendizaje remodela literalmente el cerebro.', 'Santiago Ramón y Cajal', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['learning', 'curiosity', 'self_improvement'], true, 'science'),
(gen_random_uuid(), 'El microscopio me reveló que el cerebro no es una red continua sino un universo de células individuales que se comunican.', 'Santiago Ramón y Cajal', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'learning', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'La voluntad es la arquitecta de todo lo grande que el ser humano ha logrado.', 'Santiago Ramón y Cajal', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['discipline', 'self_improvement', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'Sin constancia, el talento es una promesa incumplida; el trabajo sistemático supera al genio perezoso.', 'Santiago Ramón y Cajal', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['discipline', 'focus', 'self_improvement'], true, 'science'),
(gen_random_uuid(), 'La neurociencia nació cuando alguien tuvo la audacia de mirar el cerebro y preguntar cómo funciona, no solo qué es.', 'Santiago Ramón y Cajal', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'learning', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'La plasticidad del cerebro adulto es la mayor esperanza de la neurociencia moderna.', 'Santiago Ramón y Cajal', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['learning', 'self_improvement', 'curiosity'], true, 'science'),
(gen_random_uuid(), 'Trazar el mapa de las células nerviosas fue trazar el mapa del pensamiento mismo.', 'Santiago Ramón y Cajal', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'learning', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'La España científica que soñé necesitaba investigadores que amaran la verdad más que el reconocimiento.', 'Santiago Ramón y Cajal', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['discipline', 'wisdom', 'self_improvement'], true, 'science'),
(gen_random_uuid(), 'El científico debe tener la humildad de cambiar de opinión cuando los datos lo exigen.', 'Santiago Ramón y Cajal', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'learning', 'self_improvement'], true, 'science'),
(gen_random_uuid(), 'Entender cómo una neurona transmite señales fue entender el idioma en que el cerebro piensa.', 'Santiago Ramón y Cajal', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'learning', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'La observación meticulosa no es burocracia científica; es el respeto que la realidad merece.', 'Santiago Ramón y Cajal', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['discipline', 'learning', 'focus'], true, 'science'),

-- Severo Ochoa (146–155)
(gen_random_uuid(), 'La investigación científica es la forma más alta de servicio que puede prestar un ciudadano a su país y a la humanidad.', 'Severo Ochoa', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'discipline', 'self_improvement'], true, 'science'),
(gen_random_uuid(), 'Descifrar cómo se sintetiza el ARN fue comprender cómo la vida se reproduce a sí misma en el nivel más fundamental.', 'Severo Ochoa', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'learning', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'La bioquímica revela que la vida es química con ambición; reacciones que se auto-organizan para persistir.', 'Severo Ochoa', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'El código genético es el lenguaje universal de la vida; ninguna otra lengua ha durado tanto ni se ha hablado tan ampliamente.', 'Severo Ochoa', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'learning', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'La ciencia española tiene tanto talento como cualquier otra; lo que a veces le ha faltado es inversión y confianza.', 'Severo Ochoa', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'discipline', 'self_improvement'], true, 'science'),
(gen_random_uuid(), 'Trabajar en un laboratorio extranjero fue para mí la escuela que España aún no podía darme; no hay fronteras en la ciencia.', 'Severo Ochoa', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['learning', 'self_improvement', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'El Premio Nobel no es el fin del trabajo; es la confirmación de que la dirección era correcta.', 'Severo Ochoa', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['discipline', 'wisdom', 'self_improvement'], true, 'science'),
(gen_random_uuid(), 'Entender la síntesis del ARN fue entender un paso clave en cómo la información biológica fluye desde el gen hasta la proteína.', 'Severo Ochoa', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['learning', 'curiosity', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'La biología molecular es la historia de cómo la vida lee sus propias instrucciones cada vez que una célula se divide.', 'Severo Ochoa', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'learning', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'El científico exiliado lleva consigo su método; el método es más robusto que cualquier frontera política.', 'Severo Ochoa', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'discipline', 'self_improvement'], true, 'science'),

-- Mario Molina (156–165)
(gen_random_uuid(), 'El ozono estratosférico es el escudo invisible que hace posible la vida en tierra firme.', 'Mario Molina', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'Cuando publicamos que los CFC destruían el ozono, no esperaba el escepticismo de la industria; lo esperaba de la ciencia.', 'Mario Molina', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'learning', 'self_improvement'], true, 'science'),
(gen_random_uuid(), 'La química de la atmósfera no es un asunto de especialistas; sus consecuencias son de todos.', 'Mario Molina', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['learning', 'wisdom', 'self_improvement'], true, 'science'),
(gen_random_uuid(), 'El Protocolo de Montreal demuestra que cuando la ciencia habla con claridad, la política puede actuar.', 'Mario Molina', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'discipline', 'self_improvement'], true, 'science'),
(gen_random_uuid(), 'Una molécula sintetizada en un laboratorio puede alterar el equilibrio de toda la atmósfera terrestre; eso es responsabilidad química.', 'Mario Molina', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'learning', 'curiosity'], true, 'science'),
(gen_random_uuid(), 'La ciencia del clima no predice el futuro con certeza; señala riesgos con claridad y eso es suficiente para actuar.', 'Mario Molina', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'learning', 'discipline'], true, 'science'),
(gen_random_uuid(), 'Ser científico latinoamericano y ganar el Nobel fue demostrar que la excelencia no tiene geografía.', 'Mario Molina', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'self_improvement', 'learning'], true, 'science'),
(gen_random_uuid(), 'La química atmosférica conecta una reacción en el laboratorio con el bienestar de millones de personas; esa conexión es poderosa.', 'Mario Molina', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['learning', 'curiosity', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'Ignorar la evidencia del cambio climático no cambia el cambio climático; cambia solo nuestra capacidad de responder.', 'Mario Molina', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'learning', 'self_improvement'], true, 'science'),
(gen_random_uuid(), 'El medioambiente no es un lujo que los países ricos pueden proteger; es la infraestructura sobre la que toda economía descansa.', 'Mario Molina', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'learning', 'self_improvement'], true, 'science'),

-- César Milstein (166–174)
(gen_random_uuid(), 'Los anticuerpos monoclonales son una herramienta que la naturaleza diseñó para defenderse y que nosotros aprendimos a dirigir.', 'César Milstein', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'learning', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'La investigación básica parece inútil hasta que sus aplicaciones salvan millones de vidas.', 'César Milstein', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'learning', 'self_improvement'], true, 'science'),
(gen_random_uuid(), 'La ciencia argentina tiene una tradición de rigor que no tiene nada que envidiar a ningún centro del mundo.', 'César Milstein', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'self_improvement', 'discipline'], true, 'science'),
(gen_random_uuid(), 'Cuando fusionamos células para crear hibridomas, no sabíamos que estábamos fundando la inmunología terapéutica moderna.', 'César Milstein', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'learning', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'La investigación sin aplicación es filosofía; la aplicación sin investigación es artesanía; la unión de ambas es la ciencia.', 'César Milstein', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['learning', 'wisdom', 'discipline'], true, 'science'),
(gen_random_uuid(), 'El sistema inmunitario es la armada más sofisticada que la evolución ha construido; aprender a aliarse con ella es la meta de la medicina.', 'César Milstein', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'learning', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'Un científico exiliado no deja de pensar en su país; trabaja doblemente duro para devolverle algo desde lejos.', 'César Milstein', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['discipline', 'wisdom', 'self_improvement'], true, 'science'),
(gen_random_uuid(), 'La precisión molecular de los anticuerpos monoclonales hizo posible diagnósticos que antes eran imposibles.', 'César Milstein', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['learning', 'curiosity', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'Financiar la ciencia básica es una apuesta a largo plazo que todos los estados inteligentes deben hacer.', 'César Milstein', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'discipline', 'self_improvement'], true, 'science'),

-- Bernardo Houssay (175–183)
(gen_random_uuid(), 'La hipófisis es la directora de la orquesta hormonal del cuerpo; sin ella el metabolismo pierde su compás.', 'Bernardo Houssay', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'learning', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'El primer Nobel iberoamericano de fisiología nació del trabajo meticuloso en un laboratorio de Buenos Aires.', 'Bernardo Houssay', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['discipline', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'Los países que no invierten en ciencia básica están hipotecando su futuro en manos del conocimiento ajeno.', 'Bernardo Houssay', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'self_improvement', 'learning'], true, 'science'),
(gen_random_uuid(), 'La diabetes no es solo una enfermedad; es la ventana por la que la endocrinología moderna asomó al mundo.', 'Bernardo Houssay', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['learning', 'curiosity', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'La fisiología enseña que el cuerpo es un sistema de equilibrios dinámicos, nunca estático.', 'Bernardo Houssay', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'learning', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'Crear instituciones científicas sólidas requiere más valentía política que ganar cualquier guerra.', 'Bernardo Houssay', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['discipline', 'wisdom', 'self_improvement'], true, 'science'),
(gen_random_uuid(), 'El investigador que trabaja sin vocación produce datos; el que trabaja con vocación produce ciencia.', 'Bernardo Houssay', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['discipline', 'wisdom', 'self_improvement'], true, 'science'),
(gen_random_uuid(), 'El rigor experimental no es un fin en sí mismo; es la garantía de que las conclusiones merecen confianza.', 'Bernardo Houssay', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['discipline', 'learning', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'América Latina tiene científicos de primer nivel mundial; lo que necesita son políticas que los retengan y los liberen.', 'Bernardo Houssay', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'discipline', 'self_improvement'], true, 'science'),

-- Albert Einstein (184–198)
(gen_random_uuid(), 'La imaginación es más importante que el conocimiento; el conocimiento tiene límites pero la imaginación los rodea.', 'Albert Einstein', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['creativity', 'wisdom', 'curiosity'], true, 'science'),
(gen_random_uuid(), 'La única fuente de conocimiento es la experiencia.', 'Albert Einstein', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['learning', 'wisdom', 'curiosity'], true, 'science'),
(gen_random_uuid(), 'Si no puedes explicarlo de manera simple, es que no lo entiendes suficientemente bien.', 'Albert Einstein', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'learning', 'self_improvement'], true, 'science'),
(gen_random_uuid(), 'La curiosidad tiene su propia razón de existir; basta con contemplar los misterios de la eternidad.', 'Albert Einstein', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'Dios no juega a los dados con el universo.', 'Albert Einstein', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'curiosity', 'learning'], true, 'science'),
(gen_random_uuid(), 'El tiempo es una ilusión, aunque una muy persistente.', 'Albert Einstein', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'La gravedad no es responsable de que las personas se enamoren, pero sí de que los planetas orbiten.', 'Albert Einstein', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'El pensamiento lógico lleva de A a B; la imaginación lleva a cualquier parte.', 'Albert Einstein', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['creativity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'La mente que se abre a una nueva idea jamás regresa a su tamaño original.', 'Albert Einstein', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['learning', 'curiosity', 'self_improvement'], true, 'science'),
(gen_random_uuid(), 'El universo y la estupidez humana son infinitos; del universo no estoy completamente seguro.', 'Albert Einstein', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'learning', 'self_improvement'], true, 'science'),
(gen_random_uuid(), 'La masa y la energía son manifestaciones diferentes de la misma realidad física.', 'Albert Einstein', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'learning', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'La física teórica es el intento de construir conceptos que reflejen la estructura del mundo real.', 'Albert Einstein', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['learning', 'curiosity', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'El mayor error de la física clásica fue asumir que el tiempo era absoluto; la relatividad liberó al universo de esa prisión.', 'Albert Einstein', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'learning', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'La intuición es el motor secreto de la física teórica; las ecuaciones confirman lo que la intuición ya sospechaba.', 'Albert Einstein', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['creativity', 'wisdom', 'curiosity'], true, 'science'),
(gen_random_uuid(), 'Hacer la misma cosa una y otra vez esperando resultados distintos es la definición de locura.', 'Albert Einstein', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'self_improvement', 'learning'], true, 'science'),

-- Stephen Hawking (199–212)
(gen_random_uuid(), 'Por grande que sea la oscuridad, siempre podemos encender una luz.', 'Stephen Hawking', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'self_improvement', 'curiosity'], true, 'science'),
(gen_random_uuid(), 'El universo no tiene fronteras en el tiempo; el tiempo comenzó con el Big Bang.', 'Stephen Hawking', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'learning', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'La inteligencia es la capacidad de adaptarse al cambio.', 'Stephen Hawking', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'self_improvement', 'learning'], true, 'science'),
(gen_random_uuid(), 'Los agujeros negros no son tan negros como los pintamos; emiten radiación y eventualmente se evaporan.', 'Stephen Hawking', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'learning', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'Recuerda mirar las estrellas, no tus pies; intenta dar sentido a lo que ves.', 'Stephen Hawking', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'wisdom', 'self_improvement'], true, 'science'),
(gen_random_uuid(), 'La vida sería trágica si no fuera divertida; los científicos son las personas más privilegiadas del mundo.', 'Stephen Hawking', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'learning', 'curiosity'], true, 'science'),
(gen_random_uuid(), 'El tiempo no es constante; fluye más lento en campos gravitatorios intensos, lo cual lo convierte en una variable física.', 'Stephen Hawking', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'learning', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'Aunque el universo sea inmensamente hostil a la vida, el hecho de que estemos aquí para observarlo es el mayor misterio.', 'Stephen Hawking', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'La física cuántica describe el nivel más fundamental de la realidad que hemos alcanzado; más abajo, aún no sabemos.', 'Stephen Hawking', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'learning', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'Soy discapacitado, pero no se me ocurre que eso sea una excusa para no intentar todo lo que quiero intentar.', 'Stephen Hawking', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['discipline', 'self_improvement', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'El mayor enemigo del conocimiento no es la ignorancia sino la ilusión de conocimiento.', 'Stephen Hawking', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'learning', 'self_improvement'], true, 'science'),
(gen_random_uuid(), 'Si el universo admite una gran teoría unificada, esa teoría conectará la gravedad con la mecánica cuántica.', 'Stephen Hawking', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'learning', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'La ciencia no solo describe el universo; cambia nuestra posición en él, haciéndonos algo más que espectadores.', 'Stephen Hawking', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'curiosity', 'self_improvement'], true, 'science'),
(gen_random_uuid(), 'Que el universo haya empezado de la nada no es filosóficamente desconcertante; la física lo describe con elegancia.', 'Stephen Hawking', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),

-- Isaac Asimov (213–226)
(gen_random_uuid(), 'La ciencia recopila conocimiento más rápido de lo que la sociedad recopila sabiduría.', 'Isaac Asimov', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'learning', 'self_improvement'], true, 'science'),
(gen_random_uuid(), 'La frase más emocionante en ciencia no es ¡Eureka! sino Qué curioso.', 'Isaac Asimov', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'learning', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'El autoeducación es la única educación que merece llamarse tal.', 'Isaac Asimov', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['self_improvement', 'learning', 'discipline'], true, 'science'),
(gen_random_uuid(), 'En el universo, lo ordinario es lo extraordinario; solo la costumbre nos impide verlo.', 'Isaac Asimov', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'La ciencia ficción imagina el futuro; la ciencia lo construye; ambas necesitan la misma materia prima: la imaginación.', 'Isaac Asimov', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['creativity', 'curiosity', 'learning'], true, 'science'),
(gen_random_uuid(), 'El libro es la invención más importante de la humanidad porque externaliza la memoria y la hace compartible.', 'Isaac Asimov', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['learning', 'wisdom', 'self_improvement'], true, 'science'),
(gen_random_uuid(), 'Los robots no son la amenaza; la amenaza es la falta de criterio con que diseñamos los sistemas que nos gobiernan.', 'Isaac Asimov', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'learning', 'self_improvement'], true, 'science'),
(gen_random_uuid(), 'El universo es vasto y antiguo; la humanidad es nueva y pequeña, pero extraordinariamente curiosa.', 'Isaac Asimov', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'La diferencia entre lo posible y lo imposible se reduce a la medida de nuestra ignorancia.', 'Isaac Asimov', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['learning', 'curiosity', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'Popularizar la ciencia no es simplificarla; es traducirla al idioma en que la humanidad sueña.', 'Isaac Asimov', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['learning', 'wisdom', 'creativity'], true, 'science'),
(gen_random_uuid(), 'La física, la química y la biología son tres ventanas sobre el mismo paisaje; quien las mira juntas ve más.', 'Isaac Asimov', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'learning', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'El tiempo en que vivimos es el más apasionante de la historia porque en ningún otro el conocimiento creció tan rápido.', 'Isaac Asimov', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'La ciencia no es un conjunto de respuestas; es el arte de hacer las preguntas correctas.', 'Isaac Asimov', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'learning', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'Quienes temen la ciencia temen, en realidad, las consecuencias del conocimiento sobre sus propias creencias.', 'Isaac Asimov', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'learning', 'self_improvement'], true, 'science'),

-- Temas transversales: método científico, naturaleza, ecología, geología, astronomía (227–250)
(gen_random_uuid(), 'El método científico es la única herramienta diseñada para corregir sus propios errores.', 'Carl Sagan', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['learning', 'discipline', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'La hipótesis que no puede ser falsificada no es ciencia; es dogma con vocabulario técnico.', 'Richard Dawkins', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'learning', 'discipline'], true, 'science'),
(gen_random_uuid(), 'Los fósiles son cartas del pasado enviadas al futuro; la geología es el servicio postal de la historia de la Tierra.', 'Charles Darwin', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'learning', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'La atmósfera es una película delgadísima alrededor de la Tierra; su fragilidad debería asombrarnos y movilizarnos.', 'Carl Sagan', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'wisdom', 'self_improvement'], true, 'science'),
(gen_random_uuid(), 'La ecología demuestra que el concepto de individuo tiene límites borrosos; somos nodos en redes que nos superan.', 'Jane Goodall', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'Los genes no son el destino; son el punto de partida de una conversación continua con el ambiente.', 'Richard Dawkins', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['learning', 'curiosity', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'La neuroplasticidad confirma lo que los sabios intuían: que el cerebro que aprende se transforma.', 'Santiago Ramón y Cajal', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['learning', 'self_improvement', 'curiosity'], true, 'science'),
(gen_random_uuid(), 'Cada estrella que ves en el cielo nocturno es un sol; muchos tienen planetas; algunos pueden albergar vida.', 'Neil deGrasse Tyson', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'La tabla periódica es el mapa de los átomos; con solo 118 elementos la naturaleza construyó todo lo que existe.', 'Marie Curie', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'learning', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'La deriva continental explica por qué hay fósiles de organismos similares en continentes separados por océanos.', 'Charles Darwin', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'learning', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'El agua es la molécula de la vida; sin ella la química orgánica compleja es imposible.', 'Albert Einstein', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'Los ciclos biogeoquímicos del carbono, nitrógeno y oxígeno son el metabolismo del planeta entero.', 'Rachel Carson', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'learning', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'La extinción masiva del Cretácico no borró la vida; la reinventó, y de sus escombros surgieron los mamíferos.', 'Neil deGrasse Tyson', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'La microbiología enseña que los organismos invisibles gobiernan la química de los océanos, el suelo y nuestros intestinos.', 'Louis Pasteur', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'learning', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'La velocidad de la luz no es solo una constante física; es el límite absoluto de la causalidad en el universo.', 'Albert Einstein', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'learning', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'Los volcanes no son solo catástrofes; son la forma en que la Tierra renueva su corteza y regula su temperatura.', 'David Attenborough', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'La fotosíntesis es el proceso que convierte la energía del sol en materia viva; sin ella la cadena alimentaria no existe.', 'Jane Goodall', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'learning', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'El genoma humano tiene tres mil millones de pares de bases; leerlo fue como descifrar la receta de un ser humano.', 'César Milstein', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'learning', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'La medicina preventiva es más eficiente que la curativa; la salud pública es la aplicación social de la biología.', 'Bernardo Houssay', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'learning', 'self_improvement'], true, 'science'),
(gen_random_uuid(), 'Los ecosistemas de agua dulce son los más vulnerables y los más ignorados de la ecología moderna.', 'Rachel Carson', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['wisdom', 'learning', 'curiosity'], true, 'science'),
(gen_random_uuid(), 'La estratigrafía es el arte de leer el tiempo en las capas de la roca; cada estrato es un capítulo de la historia del planeta.', 'Charles Darwin', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'learning', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'El universo observable tiene noventa y tres mil millones de años luz de diámetro; nuestro papel en él es diminuto y precioso.', 'Stephen Hawking', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'La ciencia ciudadana demuestra que la observación sistemática no requiere laboratorio; requiere rigor y constancia.', 'Isaac Asimov', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['learning', 'discipline', 'self_improvement'], true, 'science'),
(gen_random_uuid(), 'El asombro ante la naturaleza no es prerrogativa del poeta; es el punto de partida obligatorio del científico.', 'Carl Sagan', 'philosophy', 'es', 'down', 'free', false, 'science', 'general_science', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science')

ON CONFLICT (text, author) DO NOTHING;

COMMIT;
