-- 034_coding_frontend_en.sql
-- MindScrolling — Coding Mode: Frontend batch (English)
-- 250 quotes: UI/UX design, responsive design, accessibility, CSS, JavaScript,
--   React, web standards, animations, typography, color theory, mobile-first,
--   progressive web apps, design systems, component architecture, user testing,
--   performance, SEO
--
-- All rows:
--   category       = 'philosophy'
--   lang           = 'en'
--   swipe_dir      = 'down'
--   pack_name      = 'free'
--   is_premium     = false
--   content_type   = 'coding'
--   sub_category   = 'frontend'
--   is_hidden_mode = true
--   locked_by      = 'coding'
-- Run in Supabase SQL Editor

BEGIN;

-- ══════════════════════════════════════════════════════════════════════════════
-- CODING FRONTEND — ENGLISH (250 quotes)
-- ══════════════════════════════════════════════════════════════════════════════

INSERT INTO quotes (id, text, author, category, lang, swipe_dir, pack_name, is_premium, content_type, sub_category, tags, is_hidden_mode, locked_by) VALUES

-- Steve Jobs (1–12)
(gen_random_uuid(), 'Design is not just what it looks like and feels like. Design is how it works.', 'Steve Jobs', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['creativity', 'focus', 'wisdom'], true, 'coding'),
(gen_random_uuid(), 'Simplicity is the ultimate sophistication.', 'Steve Jobs', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['creativity', 'discipline', 'wisdom'], true, 'coding'),
(gen_random_uuid(), 'The computer is the most remarkable tool that we''ve ever come up with. It''s the equivalent of a bicycle for our minds.', 'Steve Jobs', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['creativity', 'learning', 'wisdom'], true, 'coding'),
(gen_random_uuid(), 'You have to start with the customer experience and work backwards to the technology.', 'Steve Jobs', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['creativity', 'focus', 'wisdom'], true, 'coding'),
(gen_random_uuid(), 'Details matter, it''s worth waiting to get it right.', 'Steve Jobs', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['discipline', 'focus', 'wisdom'], true, 'coding'),
(gen_random_uuid(), 'People think focus means saying yes to the thing you''ve got to focus on. But that''s not what it means at all. It means saying no to the hundred other good ideas that there are.', 'Steve Jobs', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['discipline', 'focus', 'wisdom'], true, 'coding'),
(gen_random_uuid(), 'Innovation distinguishes between a leader and a follower.', 'Steve Jobs', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['creativity', 'courage', 'wisdom'], true, 'coding'),
(gen_random_uuid(), 'The only way to do great work is to love what you do.', 'Steve Jobs', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['passion', 'focus', 'wisdom'], true, 'coding'),
(gen_random_uuid(), 'Your time is limited, so don''t waste it living someone else''s life.', 'Steve Jobs', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['courage', 'focus', 'wisdom'], true, 'coding'),
(gen_random_uuid(), 'If you haven''t found it yet, keep looking. Don''t settle.', 'Steve Jobs', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['discipline', 'passion', 'wisdom'], true, 'coding'),
(gen_random_uuid(), 'Be a yardstick of quality. Some people aren''t used to an environment where excellence is expected.', 'Steve Jobs', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['discipline', 'focus', 'wisdom'], true, 'coding'),
(gen_random_uuid(), 'That''s been one of my mantras — focus and simplicity. Simple can be harder than complex.', 'Steve Jobs', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['creativity', 'discipline', 'focus'], true, 'coding'),

-- Tim Berners-Lee (13–24)
(gen_random_uuid(), 'The web does not just connect machines, it connects people.', 'Tim Berners-Lee', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['creativity', 'wisdom', 'curiosity'], true, 'coding'),
(gen_random_uuid(), 'The power of the Web is in its universality. Access by everyone regardless of disability is an essential aspect.', 'Tim Berners-Lee', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'curiosity', 'learning'], true, 'coding'),
(gen_random_uuid(), 'The original idea of the web was that it should be a collaborative space where you can communicate through sharing information.', 'Tim Berners-Lee', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['creativity', 'wisdom', 'curiosity'], true, 'coding'),
(gen_random_uuid(), 'Data is a precious thing and will last longer than the systems themselves.', 'Tim Berners-Lee', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'discipline', 'focus'], true, 'coding'),
(gen_random_uuid(), 'The web is more a social creation than a technical one. I designed it for a social effect — to help people work together.', 'Tim Berners-Lee', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['creativity', 'wisdom', 'curiosity'], true, 'coding'),
(gen_random_uuid(), 'Anyone who has lost track of time when using a computer knows the feeling of being ''present''.', 'Tim Berners-Lee', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['focus', 'wisdom', 'curiosity'], true, 'coding'),
(gen_random_uuid(), 'We need diversity of thought in the world to face the new challenges.', 'Tim Berners-Lee', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['creativity', 'wisdom', 'curiosity'], true, 'coding'),
(gen_random_uuid(), 'The goal of the Web is to serve humanity. We build it now so that those who come to it later will be able to create things we cannot ourselves imagine.', 'Tim Berners-Lee', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['creativity', 'wisdom', 'learning'], true, 'coding'),
(gen_random_uuid(), 'Openness is the most powerful thing we have.', 'Tim Berners-Lee', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['courage', 'wisdom', 'curiosity'], true, 'coding'),
(gen_random_uuid(), 'If we lose the openness of the web, we lose the web itself.', 'Tim Berners-Lee', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['courage', 'wisdom', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'Web design is not about how a site looks; it is about how it works.', 'Tim Berners-Lee', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['creativity', 'focus', 'wisdom'], true, 'coding'),
(gen_random_uuid(), 'Long-term, the web will be a space where machine-readable data and human-readable pages live together.', 'Tim Berners-Lee', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'curiosity', 'learning'], true, 'coding'),

-- Jeffrey Zeldman (25–36)
(gen_random_uuid(), 'Content precedes design. Design in the absence of content is not design, it''s decoration.', 'Jeffrey Zeldman', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['creativity', 'wisdom', 'focus'], true, 'coding'),
(gen_random_uuid(), 'Good design, when it''s done well, becomes invisible.', 'Jeffrey Zeldman', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['creativity', 'wisdom', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'Web standards are not just rules imposed by a committee. They are a foundation of trust between users and makers.', 'Jeffrey Zeldman', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'discipline', 'focus'], true, 'coding'),
(gen_random_uuid(), 'Accessible design is good design.', 'Jeffrey Zeldman', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['creativity', 'wisdom', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'The separation of structure from presentation is the foundation of good web design.', 'Jeffrey Zeldman', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['discipline', 'focus', 'wisdom'], true, 'coding'),
(gen_random_uuid(), 'Progressive enhancement is not a technique, it is a philosophy of building things that work for everyone.', 'Jeffrey Zeldman', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'discipline', 'curiosity'], true, 'coding'),
(gen_random_uuid(), 'Design without content is sculpture. Content without design is a manuscript.', 'Jeffrey Zeldman', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['creativity', 'wisdom', 'focus'], true, 'coding'),
(gen_random_uuid(), 'The most powerful force in web design is the constraint of the medium itself.', 'Jeffrey Zeldman', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['discipline', 'creativity', 'wisdom'], true, 'coding'),
(gen_random_uuid(), 'Web standards exist so that browsers behave consistently, not so that designers lose sleep.', 'Jeffrey Zeldman', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'discipline', 'focus'], true, 'coding'),
(gen_random_uuid(), 'The browser is not your canvas; it is a communication channel between your content and your user.', 'Jeffrey Zeldman', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'creativity', 'focus'], true, 'coding'),
(gen_random_uuid(), 'A list is one of the most powerful structural elements in web design and we constantly under-use it.', 'Jeffrey Zeldman', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'discipline', 'curiosity'], true, 'coding'),
(gen_random_uuid(), 'To master web design is to master the interplay of content, structure, and visual presentation.', 'Jeffrey Zeldman', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['creativity', 'discipline', 'wisdom'], true, 'coding'),

-- Ethan Marcotte (37–48)
(gen_random_uuid(), 'Responsive web design is not about screen sizes, it is about the fluidity of content.', 'Ethan Marcotte', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['creativity', 'wisdom', 'focus'], true, 'coding'),
(gen_random_uuid(), 'The web is a fluid medium; our designs should be too.', 'Ethan Marcotte', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['creativity', 'wisdom', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'Rather than tailoring disconnected designs to each of an ever-increasing number of web devices, we can treat them as facets of the same experience.', 'Ethan Marcotte', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['creativity', 'wisdom', 'focus'], true, 'coding'),
(gen_random_uuid(), 'A responsive design is not a fixed layout broken up by media queries — it is a system of proportional relationships.', 'Ethan Marcotte', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['discipline', 'focus', 'wisdom'], true, 'coding'),
(gen_random_uuid(), 'Fluid grids, flexible images, and media queries are the three technical ingredients of responsive web design.', 'Ethan Marcotte', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['learning', 'discipline', 'focus'], true, 'coding'),
(gen_random_uuid(), 'The control which designers know in the print medium, and often desire in the web medium, is simply a function of the limitation of the printed page.', 'Ethan Marcotte', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['creativity', 'wisdom', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'Responsive design is not a checklist. It is a conversation between your layout and the device that renders it.', 'Ethan Marcotte', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['creativity', 'wisdom', 'focus'], true, 'coding'),
(gen_random_uuid(), 'We are not designing pages, we are designing systems of components.', 'Ethan Marcotte', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['discipline', 'creativity', 'wisdom'], true, 'coding'),
(gen_random_uuid(), 'Our layouts should embrace the flexibility of the web rather than fight it.', 'Ethan Marcotte', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['creativity', 'wisdom', 'curiosity'], true, 'coding'),
(gen_random_uuid(), 'Think modularly. Design for the content, not the container.', 'Ethan Marcotte', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['discipline', 'creativity', 'focus'], true, 'coding'),
(gen_random_uuid(), 'The web''s inherent flexibility is not a bug to be fixed but a feature to be embraced.', 'Ethan Marcotte', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['creativity', 'wisdom', 'courage'], true, 'coding'),
(gen_random_uuid(), 'Proportional relationships in design create harmony. Fixed pixels create brittleness.', 'Ethan Marcotte', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['creativity', 'discipline', 'wisdom'], true, 'coding'),

-- Dan Abramov (49–60)
(gen_random_uuid(), 'Don''t solve the problems you don''t have yet.', 'Dan Abramov', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['discipline', 'wisdom', 'focus'], true, 'coding'),
(gen_random_uuid(), 'UI is a function of state.', 'Dan Abramov', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['discipline', 'focus', 'learning'], true, 'coding'),
(gen_random_uuid(), 'React''s real power is that it makes you think about your UI as a series of state snapshots.', 'Dan Abramov', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['creativity', 'wisdom', 'focus'], true, 'coding'),
(gen_random_uuid(), 'The best component is a component you don''t need to think about.', 'Dan Abramov', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['creativity', 'wisdom', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'Lift state up only when you need to share it. Don''t lift it preemptively.', 'Dan Abramov', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['discipline', 'focus', 'wisdom'], true, 'coding'),
(gen_random_uuid(), 'Components should do one thing and do it well.', 'Dan Abramov', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['discipline', 'focus', 'wisdom'], true, 'coding'),
(gen_random_uuid(), 'Hooks let you use state and other React features without writing a class.', 'Dan Abramov', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['learning', 'creativity', 'focus'], true, 'coding'),
(gen_random_uuid(), 'Write the component you wish you had. Then make it real.', 'Dan Abramov', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['creativity', 'discipline', 'focus'], true, 'coding'),
(gen_random_uuid(), 'Derived state is often the source of subtle bugs. Prefer computing values on the fly.', 'Dan Abramov', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'discipline', 'focus'], true, 'coding'),
(gen_random_uuid(), 'Effects are for synchronizing your component with the outside world.', 'Dan Abramov', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['learning', 'discipline', 'focus'], true, 'coding'),
(gen_random_uuid(), 'Good abstractions delay decisions. Great abstractions make the right decisions obvious.', 'Dan Abramov', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'creativity', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'The component model forces you to think about what data each piece of UI truly needs.', 'Dan Abramov', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['discipline', 'focus', 'wisdom'], true, 'coding'),

-- Brad Frost (61–72)
(gen_random_uuid(), 'Atomic design is not a linear process. It is a mental model that helps us think about our UI in terms of hierarchy.', 'Brad Frost', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['creativity', 'wisdom', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'Pattern libraries are a design system''s single source of truth.', 'Brad Frost', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['discipline', 'focus', 'wisdom'], true, 'coding'),
(gen_random_uuid(), 'Atoms combine into molecules. Molecules combine into organisms. Organisms form templates. Templates become pages.', 'Brad Frost', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['creativity', 'discipline', 'learning'], true, 'coding'),
(gen_random_uuid(), 'We are not designing pages, we are designing systems of components that can be assembled into pages.', 'Brad Frost', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['creativity', 'discipline', 'wisdom'], true, 'coding'),
(gen_random_uuid(), 'Mobile-first thinking forces you to prioritize. That prioritization makes everything better, even on desktop.', 'Brad Frost', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['discipline', 'focus', 'wisdom'], true, 'coding'),
(gen_random_uuid(), 'A design system is not a project. It is a product serving products.', 'Brad Frost', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'discipline', 'focus'], true, 'coding'),
(gen_random_uuid(), 'The best design systems are living documents, not frozen artifacts.', 'Brad Frost', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['creativity', 'wisdom', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'Components without context are like words without sentences — useful individually but meaningful only in combination.', 'Brad Frost', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['creativity', 'wisdom', 'learning'], true, 'coding'),
(gen_random_uuid(), 'Performance is a feature. Treat it as one in your design system.', 'Brad Frost', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['discipline', 'focus', 'wisdom'], true, 'coding'),
(gen_random_uuid(), 'The most reusable components are those with the fewest assumptions about their context.', 'Brad Frost', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['creativity', 'wisdom', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'Progressive disclosure means showing the right information at the right time, not all information all the time.', 'Brad Frost', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'discipline', 'focus'], true, 'coding'),
(gen_random_uuid(), 'Build for the edge cases and the happy path will take care of itself.', 'Brad Frost', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['discipline', 'wisdom', 'focus'], true, 'coding'),

-- Luke Wroblewski (73–84)
(gen_random_uuid(), 'Mobile-first means designing for constraints. Constraints breed clarity.', 'Luke Wroblewski', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['discipline', 'creativity', 'wisdom'], true, 'coding'),
(gen_random_uuid(), 'If you design for the smallest screen first, you are forced to prioritize ruthlessly.', 'Luke Wroblewski', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['discipline', 'focus', 'wisdom'], true, 'coding'),
(gen_random_uuid(), 'Touch targets need to be large enough for human fingers, not mouse cursors.', 'Luke Wroblewski', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'focus', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'Form design is the hardest problem in UX. Get it right and users barely notice. Get it wrong and they leave.', 'Luke Wroblewski', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'discipline', 'focus'], true, 'coding'),
(gen_random_uuid(), 'The best input is no input. Reduce what users must type.', 'Luke Wroblewski', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['creativity', 'wisdom', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'Inline validation is dramatically better than end-of-form validation. Correct errors at the point of creation.', 'Luke Wroblewski', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['discipline', 'wisdom', 'focus'], true, 'coding'),
(gen_random_uuid(), 'Single-column layouts outperform multi-column ones on mobile. Hierarchy, not grids.', 'Luke Wroblewski', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['discipline', 'focus', 'wisdom'], true, 'coding'),
(gen_random_uuid(), 'Context matters more than screen size. Design for the situation, not the device.', 'Luke Wroblewski', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'creativity', 'focus'], true, 'coding'),
(gen_random_uuid(), 'One task per screen. The fewer decisions a user must make, the more likely they complete the task.', 'Luke Wroblewski', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['discipline', 'focus', 'wisdom'], true, 'coding'),
(gen_random_uuid(), 'Progressive disclosure on mobile is not optional — it is survival.', 'Luke Wroblewski', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'discipline', 'focus'], true, 'coding'),
(gen_random_uuid(), 'Speed is the most important feature on a mobile interface.', 'Luke Wroblewski', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['discipline', 'focus', 'wisdom'], true, 'coding'),
(gen_random_uuid(), 'Thumb-friendly navigation puts actions where thumbs naturally rest.', 'Luke Wroblewski', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['creativity', 'wisdom', 'focus'], true, 'coding'),

-- Jared Spool (85–96)
(gen_random_uuid(), 'Good design, when it''s done well, becomes invisible. It''s only when it''s done poorly that we notice it.', 'Jared Spool', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['creativity', 'wisdom', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'If the user can''t find the information they need, the site has failed.', 'Jared Spool', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'discipline', 'focus'], true, 'coding'),
(gen_random_uuid(), 'UX is a conversation between the product and the user. Make sure your side is worth listening to.', 'Jared Spool', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['creativity', 'wisdom', 'focus'], true, 'coding'),
(gen_random_uuid(), 'Every time a user has to think, you have a UX problem.', 'Jared Spool', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'discipline', 'focus'], true, 'coding'),
(gen_random_uuid(), 'Navigation is a tax on content. If users must navigate to find something, they are paying for poor organization.', 'Jared Spool', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'creativity', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'The best test of your design is watching a real person use it for the first time.', 'Jared Spool', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'discipline', 'curiosity'], true, 'coding'),
(gen_random_uuid(), 'Usability testing is not about testing users. It is about testing your design assumptions.', 'Jared Spool', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'discipline', 'learning'], true, 'coding'),
(gen_random_uuid(), 'An interface that requires documentation has already failed.', 'Jared Spool', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'creativity', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'The most dangerous phrase in design is: I assume the user will know how to do this.', 'Jared Spool', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'discipline', 'curiosity'], true, 'coding'),
(gen_random_uuid(), 'Design research is not about proving hypotheses. It is about discovering the unknown.', 'Jared Spool', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['curiosity', 'wisdom', 'learning'], true, 'coding'),
(gen_random_uuid(), 'Users do not read; they scan. Design for the scanner, not the reader.', 'Jared Spool', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'discipline', 'focus'], true, 'coding'),
(gen_random_uuid(), 'Error messages are a UX failure. The best error message is one that never needs to appear.', 'Jared Spool', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'creativity', 'discipline'], true, 'coding'),

-- Don Norman (97–108)
(gen_random_uuid(), 'Good design is actually a lot harder to notice than poor design, in part because good designs fit our needs so well that the design is invisible.', 'Don Norman', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['creativity', 'wisdom', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'The design of everyday things is about communicating, not just aesthetics.', 'Don Norman', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['creativity', 'wisdom', 'focus'], true, 'coding'),
(gen_random_uuid(), 'Affordances define what actions are possible. Signifiers communicate where the action should take place.', 'Don Norman', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['learning', 'wisdom', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'If an error is possible, someone will make it. The designer must assume that all possible errors will occur and design so as to minimize the error and its consequences.', 'Don Norman', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'discipline', 'focus'], true, 'coding'),
(gen_random_uuid(), 'The human mind is exquisitely tuned to understand and interact with the world. A poor design thwarts the talent that is the mind.', 'Don Norman', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['creativity', 'wisdom', 'learning'], true, 'coding'),
(gen_random_uuid(), 'Make it easy to do the right things, harder to do the wrong things, and easier to recover when the wrong things happen anyway.', 'Don Norman', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'discipline', 'creativity'], true, 'coding'),
(gen_random_uuid(), 'Design is really an act of communication, which means having a deep understanding of the person with whom the designer is communicating.', 'Don Norman', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['creativity', 'wisdom', 'curiosity'], true, 'coding'),
(gen_random_uuid(), 'Feedback — sending back to the user information about what action has actually been done — is a critical component of good design.', 'Don Norman', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'discipline', 'focus'], true, 'coding'),
(gen_random_uuid(), 'When something has been done many times, it becomes natural. Change natural patterns only with strong justification.', 'Don Norman', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'discipline', 'focus'], true, 'coding'),
(gen_random_uuid(), 'The best designs take into account not just usability but all of human behavior, cognition, and emotion.', 'Don Norman', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'creativity', 'learning'], true, 'coding'),
(gen_random_uuid(), 'Conceptual models are the mental images we have of how things work. Good design matches the user''s mental model.', 'Don Norman', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'creativity', 'learning'], true, 'coding'),
(gen_random_uuid(), 'Beauty and brains, pleasure and usability — they go hand in hand.', 'Don Norman', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['creativity', 'wisdom', 'discipline'], true, 'coding'),

-- John Maeda (109–120)
(gen_random_uuid(), 'Simplicity is about subtracting the obvious and adding the meaningful.', 'John Maeda', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['creativity', 'wisdom', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'The simplest way to achieve simplicity is through thoughtful reduction.', 'John Maeda', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['creativity', 'discipline', 'wisdom'], true, 'coding'),
(gen_random_uuid(), 'Hiding complexity is not the same as eliminating it. One creates confusion; the other creates clarity.', 'John Maeda', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'creativity', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'The balance between simplicity and complexity is the most important design challenge.', 'John Maeda', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['creativity', 'wisdom', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'Technology is nothing without the human experience at the center.', 'John Maeda', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'creativity', 'focus'], true, 'coding'),
(gen_random_uuid(), 'Design and art are about conveying meaning, not just beauty. Every pixel should carry intent.', 'John Maeda', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['creativity', 'wisdom', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'Organization makes a system of many appear fewer. Group related things.', 'John Maeda', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['discipline', 'wisdom', 'focus'], true, 'coding'),
(gen_random_uuid(), 'Time is a powerful tool in design. Something that appears complex can become simple when experienced over time.', 'John Maeda', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'creativity', 'patience'], true, 'coding'),
(gen_random_uuid(), 'In the digital age, simplicity requires more work than complexity.', 'John Maeda', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['discipline', 'wisdom', 'creativity'], true, 'coding'),
(gen_random_uuid(), 'Emotion in design is not decoration. It is information.', 'John Maeda', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['creativity', 'wisdom', 'curiosity'], true, 'coding'),
(gen_random_uuid(), 'The laws of simplicity apply to all design mediums: web, print, product. Reduce, organize, time, learn.', 'John Maeda', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['discipline', 'wisdom', 'learning'], true, 'coding'),
(gen_random_uuid(), 'Great design is not minimalism. It is the removal of everything that does not serve the purpose.', 'John Maeda', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['creativity', 'discipline', 'wisdom'], true, 'coding'),

-- Jakob Nielsen (121–132)
(gen_random_uuid(), 'Usability is not a luxury. It is a prerequisite.', 'Jakob Nielsen', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'discipline', 'focus'], true, 'coding'),
(gen_random_uuid(), 'Users spend most of their time on other sites. This means that users prefer your site to work the same way as all the other sites they already know.', 'Jakob Nielsen', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'discipline', 'learning'], true, 'coding'),
(gen_random_uuid(), 'The best user interface is one that the user never thinks about.', 'Jakob Nielsen', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['creativity', 'wisdom', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'Testing with five users is enough to find 85% of usability problems.', 'Jakob Nielsen', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'discipline', 'learning'], true, 'coding'),
(gen_random_uuid(), 'Response times: 0.1 seconds feels instant. 1 second keeps the user''s flow. 10 seconds breaks attention.', 'Jakob Nielsen', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'discipline', 'focus'], true, 'coding'),
(gen_random_uuid(), 'Visibility of system status is the most fundamental of all usability heuristics.', 'Jakob Nielsen', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'discipline', 'focus'], true, 'coding'),
(gen_random_uuid(), 'Match between system and the real world: speak the users'' language, not yours.', 'Jakob Nielsen', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'creativity', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'Aesthetic and minimalist design: every extra unit of information competes with relevant information.', 'Jakob Nielsen', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['discipline', 'wisdom', 'focus'], true, 'coding'),
(gen_random_uuid(), 'Help and documentation should be easy to search and focused on the user''s task.', 'Jakob Nielsen', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'discipline', 'learning'], true, 'coding'),
(gen_random_uuid(), 'Error messages should express the problem in plain language, suggest a solution, and avoid blame.', 'Jakob Nielsen', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'creativity', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'Recognition over recall: make objects, actions, and options visible to reduce cognitive load.', 'Jakob Nielsen', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'discipline', 'learning'], true, 'coding'),
(gen_random_uuid(), 'Consistency and standards: users should not have to wonder whether different words, situations, or actions mean the same thing.', 'Jakob Nielsen', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['discipline', 'wisdom', 'focus'], true, 'coding'),

-- Edward Tufte (133–142)
(gen_random_uuid(), 'Clarity and simplicity in presentation of data allow the viewer to think about the substance rather than the methodology.', 'Edward Tufte', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'creativity', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'The purpose of data visualization is to illuminate; decoration is the enemy of clarity.', 'Edward Tufte', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['creativity', 'wisdom', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'Chartjunk is the visual clutter that surrounds data but adds no information. Eliminate it.', 'Edward Tufte', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['discipline', 'wisdom', 'focus'], true, 'coding'),
(gen_random_uuid(), 'Data-ink ratio: maximize the proportion of ink devoted to data, minimize the rest.', 'Edward Tufte', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['discipline', 'wisdom', 'creativity'], true, 'coding'),
(gen_random_uuid(), 'Good design brings order to information without concealing the information itself.', 'Edward Tufte', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['creativity', 'wisdom', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'The enemy of good design is the love of decoration for its own sake.', 'Edward Tufte', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['discipline', 'wisdom', 'focus'], true, 'coding'),
(gen_random_uuid(), 'Presenting data in a matrix grid multiplies the information you can show in a given space.', 'Edward Tufte', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'creativity', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'Typography should be invisible. When you notice the type, the designer has failed.', 'Edward Tufte', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['creativity', 'wisdom', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'Small multiples are the essence of visual thinking. They enforce comparisons.', 'Edward Tufte', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['creativity', 'wisdom', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'What is to be sought in designs for the display of information is the clear portrayal of complexity.', 'Edward Tufte', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['creativity', 'wisdom', 'discipline'], true, 'coding'),

-- Dieter Rams (143–152)
(gen_random_uuid(), 'Good design is as little design as possible.', 'Dieter Rams', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['creativity', 'wisdom', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'Good design is honest. It does not make a product more innovative, powerful or valuable than it really is.', 'Dieter Rams', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'discipline', 'courage'], true, 'coding'),
(gen_random_uuid(), 'Good design is long-lasting. It avoids being fashionable and therefore never appears antiquated.', 'Dieter Rams', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'discipline', 'creativity'], true, 'coding'),
(gen_random_uuid(), 'Good design is thorough down to the last detail. Nothing must be arbitrary or left to chance.', 'Dieter Rams', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['discipline', 'focus', 'wisdom'], true, 'coding'),
(gen_random_uuid(), 'Indifference towards people and the reality in which they live is actually the one and only cardinal sin in design.', 'Dieter Rams', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'courage', 'creativity'], true, 'coding'),
(gen_random_uuid(), 'Good design is environmentally friendly. Design makes an important contribution to the preservation of the environment.', 'Dieter Rams', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'discipline', 'creativity'], true, 'coding'),
(gen_random_uuid(), 'Good design is useful. A product is bought to be used. It must satisfy certain criteria, not only functional but also psychological and aesthetic.', 'Dieter Rams', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'creativity', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'Good design is unobtrusive. Products fulfilling a purpose are like tools. They are neither decorative objects nor works of art.', 'Dieter Rams', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['creativity', 'wisdom', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'Good design makes a product understandable. It clarifies the product''s structure and is self-explanatory.', 'Dieter Rams', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'creativity', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'Less, but better — because it concentrates on the essential aspects, and the products are not burdened with non-essentials.', 'Dieter Rams', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['creativity', 'wisdom', 'discipline'], true, 'coding'),

-- Alan Cooper (153–162)
(gen_random_uuid(), 'No matter how cool your interface is, it would be better if there were less of it.', 'Alan Cooper', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['creativity', 'wisdom', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'The degree to which an interface enables users to accomplish tasks reflects the quality of the design.', 'Alan Cooper', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'discipline', 'focus'], true, 'coding'),
(gen_random_uuid(), 'Personas are a powerful tool because they make the abstract concrete. Designing for a real person, even an imaginary one, changes everything.', 'Alan Cooper', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['creativity', 'wisdom', 'learning'], true, 'coding'),
(gen_random_uuid(), 'Feature-rich software is often interaction-poor. Adding features does not equal adding value.', 'Alan Cooper', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'discipline', 'creativity'], true, 'coding'),
(gen_random_uuid(), 'Users should never have to adapt to software. Software should adapt to users.', 'Alan Cooper', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'creativity', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'The goal-directed design process asks: what does the user want to accomplish? Then it builds backwards from that answer.', 'Alan Cooper', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'discipline', 'focus'], true, 'coding'),
(gen_random_uuid(), 'Interaction design is the practice of designing interactive digital products, environments, systems, and services.', 'Alan Cooper', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['creativity', 'wisdom', 'learning'], true, 'coding'),
(gen_random_uuid(), 'The biggest problem in software design is that designers design for users who are like themselves.', 'Alan Cooper', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'curiosity', 'learning'], true, 'coding'),
(gen_random_uuid(), 'Designing for the edge case means the center takes care of itself.', 'Alan Cooper', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'discipline', 'focus'], true, 'coding'),
(gen_random_uuid(), 'Perpetual intermediates are the majority of users. Design for them, not the power user or the novice.', 'Alan Cooper', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'creativity', 'discipline'], true, 'coding'),

-- Douglas Crockford (163–172)
(gen_random_uuid(), 'JavaScript is the only language that I''m aware of that people feel they don''t need to learn before they start using it.', 'Douglas Crockford', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'discipline', 'learning'], true, 'coding'),
(gen_random_uuid(), 'The good parts of JavaScript are actually really good. The bad parts can be worked around.', 'Douglas Crockford', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'discipline', 'focus'], true, 'coding'),
(gen_random_uuid(), 'Most of the JavaScript features that were removed in strict mode were removed because they are hazardous.', 'Douglas Crockford', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'discipline', 'learning'], true, 'coding'),
(gen_random_uuid(), 'Programming is the most complicated thing that humans do. It is amazing that it works at all.', 'Douglas Crockford', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'curiosity', 'learning'], true, 'coding'),
(gen_random_uuid(), 'JSON is not a document format. JSON is not a markup language. JSON is a data interchange format.', 'Douglas Crockford', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'discipline', 'learning'], true, 'coding'),
(gen_random_uuid(), 'The features of JavaScript that are most despised are actually the features that are most powerful.', 'Douglas Crockford', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'curiosity', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'You cannot stop programming language evolution. The best you can do is channel it.', 'Douglas Crockford', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'discipline', 'creativity'], true, 'coding'),
(gen_random_uuid(), 'Code should be written to be read by humans and only incidentally for machines to execute.', 'Douglas Crockford', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'discipline', 'creativity'], true, 'coding'),
(gen_random_uuid(), 'The browser is the most important runtime environment in the world today.', 'Douglas Crockford', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'curiosity', 'learning'], true, 'coding'),
(gen_random_uuid(), 'Prototype-based object orientation is as powerful as class-based, and more flexible. JavaScript proves it.', 'Douglas Crockford', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'learning', 'curiosity'], true, 'coding'),

-- Brendan Eich (173–182)
(gen_random_uuid(), 'JavaScript was designed in ten days. The wonder is not that it has flaws but that it works at all.', 'Brendan Eich', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'curiosity', 'learning'], true, 'coding'),
(gen_random_uuid(), 'Always bet on JavaScript.', 'Brendan Eich', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['courage', 'wisdom', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'The web''s openness is its most important feature. Never trade openness for convenience.', 'Brendan Eich', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['courage', 'wisdom', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'JavaScript''s event loop model is elegant: simple, non-blocking, and sufficient for most tasks.', 'Brendan Eich', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'discipline', 'learning'], true, 'coding'),
(gen_random_uuid(), 'First-class functions are the most powerful feature in JavaScript. Master them.', 'Brendan Eich', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['learning', 'discipline', 'wisdom'], true, 'coding'),
(gen_random_uuid(), 'Language evolution is inevitable. Good language design anticipates and guides evolution.', 'Brendan Eich', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'creativity', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'The browser is a platform of the people. No single company should own it.', 'Brendan Eich', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['courage', 'wisdom', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'Closures are JavaScript''s most powerful and least understood feature.', 'Brendan Eich', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['learning', 'wisdom', 'curiosity'], true, 'coding'),
(gen_random_uuid(), 'Prototypal inheritance is more fundamental and flexible than classical inheritance.', 'Brendan Eich', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'learning', 'curiosity'], true, 'coding'),
(gen_random_uuid(), 'Moving fast and breaking things works in a lab. On the web, you break users.', 'Brendan Eich', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'discipline', 'courage'], true, 'coding'),

-- Addy Osmani (183–194)
(gen_random_uuid(), 'First, solve the problem. Then, write the code. Then, optimize.', 'Addy Osmani', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['discipline', 'wisdom', 'focus'], true, 'coding'),
(gen_random_uuid(), 'Performance is a feature. Budget for it the same way you budget for other features.', 'Addy Osmani', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['discipline', 'focus', 'wisdom'], true, 'coding'),
(gen_random_uuid(), 'JavaScript has a cost. Parsing, compiling, and executing all take time. Ship less JS.', 'Addy Osmani', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['discipline', 'wisdom', 'focus'], true, 'coding'),
(gen_random_uuid(), 'Code splitting is the practice of only sending the code your users need. Everything else is technical debt.', 'Addy Osmani', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['discipline', 'wisdom', 'focus'], true, 'coding'),
(gen_random_uuid(), 'Lazy loading is not an optimization; it is a principle. Load what is needed, when it is needed.', 'Addy Osmani', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['discipline', 'wisdom', 'focus'], true, 'coding'),
(gen_random_uuid(), 'Critical rendering path optimization is the difference between a fast site and a slow one.', 'Addy Osmani', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['discipline', 'focus', 'learning'], true, 'coding'),
(gen_random_uuid(), 'RAIL: Response, Animation, Idle, Load. These are the four pillars of perceived performance.', 'Addy Osmani', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['discipline', 'learning', 'focus'], true, 'coding'),
(gen_random_uuid(), 'Design patterns solve recurring problems. Using them is engineering literacy.', 'Addy Osmani', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'learning', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'Build, measure, learn. Apply the feedback loop to performance as rigorously as to features.', 'Addy Osmani', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['discipline', 'wisdom', 'learning'], true, 'coding'),
(gen_random_uuid(), 'Service workers unlock offline-first experiences. Progressive web apps start here.', 'Addy Osmani', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['learning', 'creativity', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'Automate what can be automated. Every manual build step is a liability.', 'Addy Osmani', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['discipline', 'focus', 'wisdom'], true, 'coding'),
(gen_random_uuid(), 'Web components bring reusability to the platform level. They are the building blocks of the open web.', 'Addy Osmani', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['creativity', 'wisdom', 'learning'], true, 'coding'),

-- Kyle Simpson (195–204)
(gen_random_uuid(), 'You don''t know JavaScript until you understand the coercion rules.', 'Kyle Simpson', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'discipline', 'learning'], true, 'coding'),
(gen_random_uuid(), 'Scope is not a runtime behavior; it is determined at author time. That''s what lexical scope means.', 'Kyle Simpson', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['learning', 'wisdom', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'The this keyword is one of the most misunderstood features of JavaScript, yet it is also one of the most powerful.', 'Kyle Simpson', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'discipline', 'learning'], true, 'coding'),
(gen_random_uuid(), 'Closures are not a gotcha. They are the language working exactly as designed.', 'Kyle Simpson', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'learning', 'curiosity'], true, 'coding'),
(gen_random_uuid(), 'Async programming is not hard. It is just different from synchronous thinking. Embrace the difference.', 'Kyle Simpson', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'discipline', 'learning'], true, 'coding'),
(gen_random_uuid(), 'Generators and promises together create async/await. Understanding the primitive is understanding the abstraction.', 'Kyle Simpson', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['learning', 'wisdom', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'Prototypes are not a bad pattern to avoid; they are the core of how JavaScript objects work.', 'Kyle Simpson', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'learning', 'curiosity'], true, 'coding'),
(gen_random_uuid(), 'Type coercion in JavaScript follows deterministic rules. Learn the rules and the surprises disappear.', 'Kyle Simpson', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'discipline', 'learning'], true, 'coding'),
(gen_random_uuid(), 'Functional programming is not a paradigm shift for JavaScript; it is JavaScript''s natural state.', 'Kyle Simpson', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'learning', 'creativity'], true, 'coding'),
(gen_random_uuid(), 'Understanding a language means being able to predict its behavior without running the code.', 'Kyle Simpson', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'discipline', 'learning'], true, 'coding'),

-- Lea Verou (205–214)
(gen_random_uuid(), 'CSS is a language of constraints and creativity. The constraints make you a better designer.', 'Lea Verou', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['creativity', 'wisdom', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'Custom properties in CSS are not just variables; they are a dynamic communication channel across your stylesheet.', 'Lea Verou', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['creativity', 'learning', 'wisdom'], true, 'coding'),
(gen_random_uuid(), 'The cascade is not a bug to be fought; it is the C in CSS and a feature to be understood.', 'Lea Verou', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'learning', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'Specificity is not a gotcha. It is a conflict resolution system. Learn its rules.', 'Lea Verou', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'discipline', 'learning'], true, 'coding'),
(gen_random_uuid(), 'CSS animations and transitions are not decoration; they communicate change to the user.', 'Lea Verou', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['creativity', 'wisdom', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'The web is the most accessible application delivery platform ever created. CSS is part of why.', 'Lea Verou', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'creativity', 'curiosity'], true, 'coding'),
(gen_random_uuid(), 'Preprocessors are scaffolding. Eventually the platform catches up and the scaffolding comes down.', 'Lea Verou', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'discipline', 'curiosity'], true, 'coding'),
(gen_random_uuid(), 'Grid and flexbox are not competing tools; they solve different problems and work beautifully together.', 'Lea Verou', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['creativity', 'wisdom', 'learning'], true, 'coding'),
(gen_random_uuid(), 'Color is one of the most powerful tools in a web designer''s arsenal. Use it with intention.', 'Lea Verou', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['creativity', 'wisdom', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'CSS is not a toy language. Its surface simplicity hides surprising depth and power.', 'Lea Verou', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'curiosity', 'learning'], true, 'coding'),

-- Rachel Andrew (215–224)
(gen_random_uuid(), 'CSS Grid changed web layout forever. We no longer need to hack layout with floats and inline blocks.', 'Rachel Andrew', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['creativity', 'wisdom', 'learning'], true, 'coding'),
(gen_random_uuid(), 'Understanding CSS Grid means understanding tracks, lines, and cells as a two-dimensional system.', 'Rachel Andrew', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['learning', 'discipline', 'wisdom'], true, 'coding'),
(gen_random_uuid(), 'Intrinsic web design is about creating layouts that respond to their content, not just their containers.', 'Rachel Andrew', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['creativity', 'wisdom', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'The browser developer tools are the most powerful classroom on the planet for learning CSS.', 'Rachel Andrew', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['learning', 'curiosity', 'wisdom'], true, 'coding'),
(gen_random_uuid(), 'Subgrid solves the last major alignment problem in CSS. Nested grids can now align to the parent.', 'Rachel Andrew', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['learning', 'wisdom', 'creativity'], true, 'coding'),
(gen_random_uuid(), 'The best way to learn CSS Grid is to use it. Start with a simple layout and grow from there.', 'Rachel Andrew', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['learning', 'discipline', 'curiosity'], true, 'coding'),
(gen_random_uuid(), 'Multi-column layout in CSS is underused. It is the right tool for long-form content.', 'Rachel Andrew', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['creativity', 'wisdom', 'learning'], true, 'coding'),
(gen_random_uuid(), 'CSS layout is not about picking a framework. It is about understanding the tools the browser gives you.', 'Rachel Andrew', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'discipline', 'learning'], true, 'coding'),
(gen_random_uuid(), 'Writing mode support in CSS enables truly global typography without JavaScript hacks.', 'Rachel Andrew', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['creativity', 'wisdom', 'learning'], true, 'coding'),
(gen_random_uuid(), 'The new CSS logical properties make bidirectional and multi-language layouts natural and maintainable.', 'Rachel Andrew', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'learning', 'discipline'], true, 'coding'),

-- Jen Simmons (225–234)
(gen_random_uuid(), 'CSS is a design tool, not just a styling language. Use it to express real design intent.', 'Jen Simmons', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['creativity', 'wisdom', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'Intrinsic sizing in CSS lets content determine its own size. Stop fighting the browser.', 'Jen Simmons', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['creativity', 'wisdom', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'The web has never had a real layout system until CSS Grid. We are only beginning to see what is possible.', 'Jen Simmons', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['creativity', 'wisdom', 'curiosity'], true, 'coding'),
(gen_random_uuid(), 'Flexbox is for one-dimensional layout. Grid is for two-dimensional layout. Use each for what it does best.', 'Jen Simmons', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'discipline', 'learning'], true, 'coding'),
(gen_random_uuid(), 'We copied print design into the browser for decades. CSS Grid gives us the chance to invent something new.', 'Jen Simmons', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['creativity', 'wisdom', 'courage'], true, 'coding'),
(gen_random_uuid(), 'The browser does not need to render your design like a print PDF. Let go of control and embrace the medium.', 'Jen Simmons', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['creativity', 'courage', 'wisdom'], true, 'coding'),
(gen_random_uuid(), 'Shapes in CSS — circle, polygon, ellipse — are not decoration. They change how text flows around content.', 'Jen Simmons', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['creativity', 'wisdom', 'learning'], true, 'coding'),
(gen_random_uuid(), 'Variable fonts are one of the biggest advances in web typography in a decade.', 'Jen Simmons', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['creativity', 'wisdom', 'learning'], true, 'coding'),
(gen_random_uuid(), 'The container query changes everything. Now components can respond to their own context, not just the viewport.', 'Jen Simmons', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['creativity', 'learning', 'wisdom'], true, 'coding'),
(gen_random_uuid(), 'Layout should serve communication. When layout calls attention to itself, it has failed.', 'Jen Simmons', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['creativity', 'wisdom', 'discipline'], true, 'coding'),

-- Sara Soueidan (235–244)
(gen_random_uuid(), 'Accessibility is not a checklist. It is a mindset that you bring to every design decision.', 'Sara Soueidan', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'discipline', 'courage'], true, 'coding'),
(gen_random_uuid(), 'SVG is the most powerful and underused format on the web. It is resolution-independent, accessible, and scriptable.', 'Sara Soueidan', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['creativity', 'wisdom', 'learning'], true, 'coding'),
(gen_random_uuid(), 'ARIA roles do not add functionality; they add meaning. Semantic HTML comes first.', 'Sara Soueidan', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'discipline', 'learning'], true, 'coding'),
(gen_random_uuid(), 'Focus management is the invisible accessibility feature that separates good keyboard UX from bad.', 'Sara Soueidan', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'discipline', 'focus'], true, 'coding'),
(gen_random_uuid(), 'Color contrast is not a preference; it is a requirement. 4.5:1 for normal text, 3:1 for large text.', 'Sara Soueidan', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'discipline', 'focus'], true, 'coding'),
(gen_random_uuid(), 'Every interactive element must be keyboard operable. If it cannot be reached by Tab, it does not exist for many users.', 'Sara Soueidan', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'discipline', 'courage'], true, 'coding'),
(gen_random_uuid(), 'Screen readers do not browse websites visually. They consume the accessibility tree. Build it with care.', 'Sara Soueidan', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'discipline', 'learning'], true, 'coding'),
(gen_random_uuid(), 'Motion can cause harm. Respect prefers-reduced-motion and design animations with restraint.', 'Sara Soueidan', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'discipline', 'creativity'], true, 'coding'),
(gen_random_uuid(), 'Inclusive design benefits everyone. High contrast benefits low-vision users and users in bright sunlight alike.', 'Sara Soueidan', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'creativity', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'Alt text is not a description of an image; it is a replacement for an image. Write what the image communicates.', 'Sara Soueidan', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'discipline', 'creativity'], true, 'coding'),

-- Paul Graham (245–250)
(gen_random_uuid(), 'Hackers and painters both make things, and they have a lot in common. The most important: they never stop learning.', 'Paul Graham', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'learning', 'creativity'], true, 'coding'),
(gen_random_uuid(), 'The best way to have good ideas is to notice anomalies: odd things that puzzle you. What is actually going on?', 'Paul Graham', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['curiosity', 'wisdom', 'creativity'], true, 'coding'),
(gen_random_uuid(), 'Taste is developed through exposure to good work. Look at beautiful software, beautiful interfaces, beautiful design.', 'Paul Graham', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['creativity', 'wisdom', 'learning'], true, 'coding'),
(gen_random_uuid(), 'The most important quality in a programmer is curiosity. Everything else follows from that.', 'Paul Graham', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['curiosity', 'wisdom', 'learning'], true, 'coding'),
(gen_random_uuid(), 'Web startups that win on design win completely. Users cannot tell why a well-designed product feels better — they just know it does.', 'Paul Graham', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['creativity', 'wisdom', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'Good design looks effortless. That effortlessness is earned by enormous effort behind the scenes.', 'Paul Graham', 'philosophy', 'en', 'down', 'free', false, 'coding', 'frontend', ARRAY['creativity', 'discipline', 'wisdom'], true, 'coding')

ON CONFLICT (text, author) DO NOTHING;

COMMIT;
