-- 036_coding_backend_en.sql
-- MindScrolling — Coding Mode: Backend batch (English)
-- 250 quotes: API design, databases, microservices, caching, scalability,
--   security, authentication, message queues, load balancing, containerization,
--   serverless, REST, GraphQL, event-driven, SOLID, design patterns,
--   distributed systems, concurrency, networking
--
-- All rows:
--   category       = 'philosophy'
--   lang           = 'en'
--   swipe_dir      = 'down'
--   pack_name      = 'free'
--   is_premium     = false
--   content_type   = 'coding'
--   sub_category   = 'backend'
--   is_hidden_mode = true
--   locked_by      = 'coding'
-- Run in Supabase SQL Editor

BEGIN;

-- ══════════════════════════════════════════════════════════════════════════════
-- CODING BACKEND — ENGLISH (250 quotes)
-- ══════════════════════════════════════════════════════════════════════════════

INSERT INTO quotes (id, text, author, category, lang, swipe_dir, pack_name, is_premium, content_type, sub_category, tags, is_hidden_mode, locked_by) VALUES

-- Martin Fowler (1–18)
(gen_random_uuid(), 'Any fool can write code that a computer can understand. Good programmers write code that humans can understand.', 'Martin Fowler', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'discipline', 'focus'], true, 'coding'),
(gen_random_uuid(), 'The first step to refactoring is making the tests pass. Never refactor without a safety net.', 'Martin Fowler', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline', 'wisdom', 'focus'], true, 'coding'),
(gen_random_uuid(), 'Microservices are not a silver bullet. They trade one set of problems for another. Choose deliberately.', 'Martin Fowler', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'discipline', 'curiosity'], true, 'coding'),
(gen_random_uuid(), 'A service mesh handles the communication concerns that every microservice would otherwise have to solve itself.', 'Martin Fowler', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'discipline', 'learning'], true, 'coding'),
(gen_random_uuid(), 'Event sourcing stores a log of events as the source of truth, not the current state. This changes everything about audit and replay.', 'Martin Fowler', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'learning', 'curiosity'], true, 'coding'),
(gen_random_uuid(), 'CQRS separates the read model from the write model. This asymmetry allows each to be optimized independently.', 'Martin Fowler', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'discipline', 'focus'], true, 'coding'),
(gen_random_uuid(), 'The strangler fig pattern lets you migrate a legacy system incrementally without a risky big-bang rewrite.', 'Martin Fowler', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'discipline', 'courage'], true, 'coding'),
(gen_random_uuid(), 'Feature toggles decouple deployment from release. Ship code continuously and turn features on when ready.', 'Martin Fowler', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline', 'wisdom', 'focus'], true, 'coding'),
(gen_random_uuid(), 'Domain-driven design starts with understanding the business domain. The model lives in the language of the domain experts.', 'Martin Fowler', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'learning', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'A bounded context defines the scope in which a domain model applies. Cross the boundary and the model breaks.', 'Martin Fowler', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'discipline', 'focus'], true, 'coding'),
(gen_random_uuid(), 'The anti-corruption layer protects your clean domain model from the chaos of external systems.', 'Martin Fowler', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline', 'wisdom', 'focus'], true, 'coding'),
(gen_random_uuid(), 'Continuous integration is not just a tool. It is a practice that changes how a team thinks about integration risk.', 'Martin Fowler', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline', 'wisdom', 'courage'], true, 'coding'),
(gen_random_uuid(), 'The repository pattern separates your domain logic from your data access logic. Keep them apart.', 'Martin Fowler', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'discipline', 'focus'], true, 'coding'),
(gen_random_uuid(), 'An aggregate is a cluster of domain objects treated as a single unit. Enforce invariants at the aggregate boundary.', 'Martin Fowler', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'discipline', 'learning'], true, 'coding'),
(gen_random_uuid(), 'Blue-green deployments eliminate downtime by keeping two identical production environments and switching traffic.', 'Martin Fowler', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline', 'wisdom', 'focus'], true, 'coding'),
(gen_random_uuid(), 'Canary releases expose a new version to a small subset of users before rolling it out broadly. Fail small.', 'Martin Fowler', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'discipline', 'courage'], true, 'coding'),
(gen_random_uuid(), 'The saga pattern manages distributed transactions across microservices using compensating transactions.', 'Martin Fowler', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'discipline', 'learning'], true, 'coding'),
(gen_random_uuid(), 'Dark launching lets you run new code in production silently, validating behavior before users ever see it.', 'Martin Fowler', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline', 'wisdom', 'focus'], true, 'coding'),

-- Robert C. Martin (19–34)
(gen_random_uuid(), 'The Single Responsibility Principle: a class should have one, and only one, reason to change.', 'Robert C. Martin', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline', 'wisdom', 'focus'], true, 'coding'),
(gen_random_uuid(), 'The Open-Closed Principle: software entities should be open for extension, closed for modification.', 'Robert C. Martin', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'discipline', 'learning'], true, 'coding'),
(gen_random_uuid(), 'The Liskov Substitution Principle: subtypes must be substitutable for their base types without altering correctness.', 'Robert C. Martin', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'discipline', 'focus'], true, 'coding'),
(gen_random_uuid(), 'The Interface Segregation Principle: clients should not be forced to depend on interfaces they do not use.', 'Robert C. Martin', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline', 'wisdom', 'focus'], true, 'coding'),
(gen_random_uuid(), 'The Dependency Inversion Principle: depend on abstractions, not on concretions.', 'Robert C. Martin', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'discipline', 'learning'], true, 'coding'),
(gen_random_uuid(), 'Clean architecture keeps business rules at the center, isolated from frameworks, databases, and delivery mechanisms.', 'Robert C. Martin', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline', 'wisdom', 'focus'], true, 'coding'),
(gen_random_uuid(), 'The use case layer contains the application-specific business rules. It orchestrates the flow of data.', 'Robert C. Martin', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'discipline', 'focus'], true, 'coding'),
(gen_random_uuid(), 'A database is a detail. Your domain should not know or care which database you are using.', 'Robert C. Martin', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'discipline', 'curiosity'], true, 'coding'),
(gen_random_uuid(), 'The web is a delivery mechanism, not the application. Do not let HTTP leak into your business logic.', 'Robert C. Martin', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline', 'wisdom', 'focus'], true, 'coding'),
(gen_random_uuid(), 'Functions that do one thing do it well and do nothing else. That is the secret of maintainable code.', 'Robert C. Martin', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline', 'wisdom', 'focus'], true, 'coding'),
(gen_random_uuid(), 'Error handling obscures logic. Separate error handling from the happy path whenever possible.', 'Robert C. Martin', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'discipline', 'focus'], true, 'coding'),
(gen_random_uuid(), 'Test-driven development is not about testing. It is about design. Writing tests first shapes better code.', 'Robert C. Martin', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline', 'wisdom', 'learning'], true, 'coding'),
(gen_random_uuid(), 'The Dependency Rule: source code dependencies must point inward toward higher-level policies.', 'Robert C. Martin', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'discipline', 'focus'], true, 'coding'),
(gen_random_uuid(), 'Screaming architecture: the top-level directory of a system should tell you what the system does, not its framework.', 'Robert C. Martin', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'discipline', 'curiosity'], true, 'coding'),
(gen_random_uuid(), 'The right way to fix a bug is to first write a test that fails because of the bug, then fix the bug.', 'Robert C. Martin', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline', 'wisdom', 'focus'], true, 'coding'),
(gen_random_uuid(), 'Coupling is the enemy of change. When things change together, they should be together. Otherwise, keep them apart.', 'Robert C. Martin', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'discipline', 'learning'], true, 'coding'),
(gen_random_uuid(), 'Architecture is about deferring decisions. The longer you can keep options open, the better your design.', 'Robert C. Martin', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'discipline', 'curiosity'], true, 'coding'),

-- Kent Beck (35–46)
(gen_random_uuid(), 'Make it work, make it right, make it fast. In that order, every time.', 'Kent Beck', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline', 'wisdom', 'focus'], true, 'coding'),
(gen_random_uuid(), 'Extreme Programming embraces change. The ability to change cheaply is the most valuable property a codebase can have.', 'Kent Beck', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['courage', 'wisdom', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'The test is not the goal. The goal is clean code that works. Tests are the way to get there safely.', 'Kent Beck', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline', 'wisdom', 'focus'], true, 'coding'),
(gen_random_uuid(), 'Simple design: passes the tests, reveals intention, has no duplication, has the fewest elements. In that priority.', 'Kent Beck', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'discipline', 'focus'], true, 'coding'),
(gen_random_uuid(), 'Pair programming shares knowledge continuously. There is no bus factor on a team that pairs.', 'Kent Beck', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline', 'wisdom', 'learning'], true, 'coding'),
(gen_random_uuid(), 'The three rules of TDD: write no production code without a failing test; write only enough test to fail; write only enough code to pass.', 'Kent Beck', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline', 'wisdom', 'focus'], true, 'coding'),
(gen_random_uuid(), 'Continuous delivery is not a deployment technique. It is a philosophy of small, safe, frequent change.', 'Kent Beck', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline', 'wisdom', 'courage'], true, 'coding'),
(gen_random_uuid(), 'Refactoring and adding features are two different gears. Switch between them, never engage both at once.', 'Kent Beck', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline', 'wisdom', 'focus'], true, 'coding'),
(gen_random_uuid(), 'Feedback is the engine of software development. Short cycles mean fast feedback. Fast feedback means safe bets.', 'Kent Beck', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'discipline', 'learning'], true, 'coding'),
(gen_random_uuid(), 'Courage without feedback is recklessness. Feedback without courage is paralysis. You need both.', 'Kent Beck', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['courage', 'wisdom', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'The system metaphor gives a team a shared story that explains how the system works to everyone, including newcomers.', 'Kent Beck', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'learning', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'Incremental design keeps complexity proportional to solved problems, not anticipated ones. Build what you need now.', 'Kent Beck', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline', 'wisdom', 'focus'], true, 'coding'),

-- Donald Knuth (47–57)
(gen_random_uuid(), 'Beware of bugs in the above code; I have only proved it correct, not tried it.', 'Donald Knuth', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'curiosity', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'The real problem is that programmers have spent far too much time worrying about efficiency in the wrong places.', 'Donald Knuth', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'discipline', 'focus'], true, 'coding'),
(gen_random_uuid(), 'A person does not really understand something until they have taught it to a computer.', 'Donald Knuth', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'learning', 'curiosity'], true, 'coding'),
(gen_random_uuid(), 'Literate programming: instead of imagining our task as instructing a computer, let us concentrate on explaining ideas to human beings.', 'Donald Knuth', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'learning', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'The best programs are written so that computing machines can perform them quickly and so that human beings can understand them clearly.', 'Donald Knuth', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'discipline', 'learning'], true, 'coding'),
(gen_random_uuid(), 'Science is what we understand well enough to explain to a computer. Art is everything else.', 'Donald Knuth', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'curiosity', 'creativity'], true, 'coding'),
(gen_random_uuid(), 'Email has become the bane of my existence. If I responded to every message I would have no time to create anything.', 'Donald Knuth', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline', 'focus', 'wisdom'], true, 'coding'),
(gen_random_uuid(), 'Structured programming with go-to statements is perfectly all right if you follow certain discipline.', 'Donald Knuth', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline', 'wisdom', 'focus'], true, 'coding'),
(gen_random_uuid(), 'I have been on a diet for the last ten years: I try not to eat anything that I haven''t grown or prepared myself.', 'Donald Knuth', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline', 'wisdom', 'focus'], true, 'coding'),
(gen_random_uuid(), 'Random numbers should not be generated with a method chosen at random.', 'Donald Knuth', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'discipline', 'curiosity'], true, 'coding'),
(gen_random_uuid(), 'The computer was born to solve problems that did not exist before.', 'Donald Knuth', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['curiosity', 'wisdom', 'creativity'], true, 'coding'),

-- Edsger Dijkstra (58–68)
(gen_random_uuid(), 'Simplicity is a prerequisite for reliability.', 'Edsger Dijkstra', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline', 'wisdom', 'focus'], true, 'coding'),
(gen_random_uuid(), 'The question of whether a computer can think is no more interesting than the question of whether a submarine can swim.', 'Edsger Dijkstra', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'curiosity', 'learning'], true, 'coding'),
(gen_random_uuid(), 'Testing shows the presence, not the absence, of bugs.', 'Edsger Dijkstra', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'discipline', 'focus'], true, 'coding'),
(gen_random_uuid(), 'The art of programming is the art of organizing complexity.', 'Edsger Dijkstra', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'discipline', 'creativity'], true, 'coding'),
(gen_random_uuid(), 'If debugging is the process of removing software bugs, then programming must be the process of putting them in.', 'Edsger Dijkstra', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'curiosity', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'The use of COBOL cripples the mind; its teaching should, therefore, be regarded as a criminal offence.', 'Edsger Dijkstra', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'courage', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'Program testing can be used to show the presence of bugs, but never to show their absence.', 'Edsger Dijkstra', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'discipline', 'focus'], true, 'coding'),
(gen_random_uuid(), 'Object-oriented programming is an exceptionally bad idea which could only have originated in California.', 'Edsger Dijkstra', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'courage', 'curiosity'], true, 'coding'),
(gen_random_uuid(), 'We should not introduce errors through sloppiness but systematically keep them out.', 'Edsger Dijkstra', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline', 'wisdom', 'focus'], true, 'coding'),
(gen_random_uuid(), 'Elegance is not a dispensable luxury but a quality that decides between success and failure.', 'Edsger Dijkstra', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'discipline', 'creativity'], true, 'coding'),
(gen_random_uuid(), 'Goto considered harmful: the quality of programmers is inversely proportional to the density of goto statements in their code.', 'Edsger Dijkstra', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline', 'wisdom', 'focus'], true, 'coding'),

-- Brian Kernighan (69–78)
(gen_random_uuid(), 'Debugging is twice as hard as writing the code in the first place. Therefore, if you write the code as cleverly as possible, you are not smart enough to debug it.', 'Brian Kernighan', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'discipline', 'focus'], true, 'coding'),
(gen_random_uuid(), 'The Unix philosophy: write programs that do one thing and do it well. Write programs to work together.', 'Brian Kernighan', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline', 'wisdom', 'focus'], true, 'coding'),
(gen_random_uuid(), 'Write programs to handle text streams, because that is a universal interface.', 'Brian Kernighan', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline', 'wisdom', 'learning'], true, 'coding'),
(gen_random_uuid(), 'The most effective debugging tool is still careful thought, coupled with judiciously placed print statements.', 'Brian Kernighan', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'discipline', 'focus'], true, 'coding'),
(gen_random_uuid(), 'Don''t comment bad code — rewrite it. Comments should explain why, not what the code does.', 'Brian Kernighan', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline', 'wisdom', 'focus'], true, 'coding'),
(gen_random_uuid(), 'Controlling complexity is the essence of computer programming. Keep modules simple, their interfaces clean.', 'Brian Kernighan', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline', 'wisdom', 'focus'], true, 'coding'),
(gen_random_uuid(), 'Everyone knows that debugging is twice as hard as writing a program. So if you''re as clever as you can be when you write it, how will you ever debug it?', 'Brian Kernighan', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'discipline', 'curiosity'], true, 'coding'),
(gen_random_uuid(), 'The C programming language is quirky, flawed, and an enormous success. It is honest about what it is.', 'Brian Kernighan', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'courage', 'learning'], true, 'coding'),
(gen_random_uuid(), 'UNIX is simple. It just takes a genius to understand its simplicity.', 'Brian Kernighan', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'curiosity', 'learning'], true, 'coding'),
(gen_random_uuid(), 'A language that doesn''t affect the way you think about programming is not worth knowing.', 'Brian Kernighan', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'learning', 'curiosity'], true, 'coding'),

-- Linus Torvalds (79–89)
(gen_random_uuid(), 'Talk is cheap. Show me the code.', 'Linus Torvalds', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline', 'wisdom', 'courage'], true, 'coding'),
(gen_random_uuid(), 'Software is like sex: it''s better when it''s free.', 'Linus Torvalds', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'courage', 'creativity'], true, 'coding'),
(gen_random_uuid(), 'Bad programmers worry about the code. Good programmers worry about data structures and their relationships.', 'Linus Torvalds', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'discipline', 'focus'], true, 'coding'),
(gen_random_uuid(), 'Most good programmers do programming not because they expect to get paid but because it is fun to program.', 'Linus Torvalds', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'creativity', 'learning'], true, 'coding'),
(gen_random_uuid(), 'Given enough eyeballs, all bugs are shallow. That is the power of open-source peer review.', 'Linus Torvalds', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'learning', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'A computer is like air conditioning — it becomes useless when you open Windows.', 'Linus Torvalds', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'curiosity', 'courage'], true, 'coding'),
(gen_random_uuid(), 'I am not a visionary. I am an engineer. I''m perfectly happy with all the people who are walking around and just staring at the clouds.', 'Linus Torvalds', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'discipline', 'courage'], true, 'coding'),
(gen_random_uuid(), 'The Linux philosophy is laugh in the face of danger. Oops. Wrong one. Do it yourself. That''s the one.', 'Linus Torvalds', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['courage', 'discipline', 'wisdom'], true, 'coding'),
(gen_random_uuid(), 'Portability is for people who cannot write new programs.', 'Linus Torvalds', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['courage', 'wisdom', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'The kernel is the one place where you absolutely do not get to say: let''s use a garbage-collected language.', 'Linus Torvalds', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline', 'wisdom', 'focus'], true, 'coding'),
(gen_random_uuid(), 'When you say: I wrote a program that crashed Windows, people just stare at you blankly and say: yeah, so did I, last Friday.', 'Linus Torvalds', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'courage', 'curiosity'], true, 'coding'),

-- Werner Vogels (90–100)
(gen_random_uuid(), 'Everything fails, all the time. Design for failure from day one.', 'Werner Vogels', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'discipline', 'courage'], true, 'coding'),
(gen_random_uuid(), 'You build it, you run it. Ownership of production makes engineers think differently about quality.', 'Werner Vogels', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline', 'wisdom', 'courage'], true, 'coding'),
(gen_random_uuid(), 'Availability, performance, and security are not features you add at the end. They are properties you build in from the start.', 'Werner Vogels', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline', 'wisdom', 'focus'], true, 'coding'),
(gen_random_uuid(), 'Distributed systems are hard. The network lies to you. Clocks lie to you. Plan for it.', 'Werner Vogels', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'discipline', 'learning'], true, 'coding'),
(gen_random_uuid(), 'Single-digit millisecond latency at any scale is achievable. But it requires building the right primitives.', 'Werner Vogels', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline', 'wisdom', 'focus'], true, 'coding'),
(gen_random_uuid(), 'A serverless world is not one without servers. It is one where you do not manage servers.', 'Werner Vogels', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'learning', 'curiosity'], true, 'coding'),
(gen_random_uuid(), 'Idempotency is not optional in distributed systems. Every operation that can fail must be safe to retry.', 'Werner Vogels', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline', 'wisdom', 'focus'], true, 'coding'),
(gen_random_uuid(), 'The cell-based architecture confines blast radius. When cells fail, they fail independently.', 'Werner Vogels', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'discipline', 'focus'], true, 'coding'),
(gen_random_uuid(), 'Chaos engineering is not about breaking things for fun. It is about building confidence in your system''s resilience.', 'Werner Vogels', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline', 'courage', 'wisdom'], true, 'coding'),
(gen_random_uuid(), 'The best way to test your disaster recovery plan is to invoke it regularly. Simulate the disaster before it happens.', 'Werner Vogels', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline', 'wisdom', 'courage'], true, 'coding'),
(gen_random_uuid(), 'Event-driven architectures decouple producers from consumers. Neither needs to know the other exists.', 'Werner Vogels', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'discipline', 'learning'], true, 'coding'),

-- Leslie Lamport (101–110)
(gen_random_uuid(), 'A distributed system is one in which the failure of a computer you didn''t even know existed can render your own computer unusable.', 'Leslie Lamport', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'curiosity', 'learning'], true, 'coding'),
(gen_random_uuid(), 'If you''re not thinking about failure modes, you''re not thinking about distributed systems.', 'Leslie Lamport', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'discipline', 'focus'], true, 'coding'),
(gen_random_uuid(), 'Consistency, availability, and partition tolerance: you can have at most two. Choose carefully.', 'Leslie Lamport', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'discipline', 'learning'], true, 'coding'),
(gen_random_uuid(), 'Consensus is the fundamental problem of distributed computing. Without agreement, coordination breaks down.', 'Leslie Lamport', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'discipline', 'learning'], true, 'coding'),
(gen_random_uuid(), 'The Paxos algorithm achieves consensus in the presence of failures. But simple it is not.', 'Leslie Lamport', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'learning', 'curiosity'], true, 'coding'),
(gen_random_uuid(), 'Clocks in distributed systems do not agree. Logical clocks provide a consistent ordering of events without requiring synchronization.', 'Leslie Lamport', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'learning', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'A concurrent algorithm is correct if it works under all possible interleavings of operations.', 'Leslie Lamport', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'discipline', 'focus'], true, 'coding'),
(gen_random_uuid(), 'Formal methods let you prove properties about a system before you build it. Bugs found on paper cost nothing.', 'Leslie Lamport', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'discipline', 'learning'], true, 'coding'),
(gen_random_uuid(), 'Writing is how you think, not how you record thought. A specification that is hard to write is a design that is hard to build.', 'Leslie Lamport', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'discipline', 'focus'], true, 'coding'),
(gen_random_uuid(), 'Safety means nothing bad happens. Liveness means something good eventually happens. Both properties matter.', 'Leslie Lamport', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'discipline', 'learning'], true, 'coding'),

-- Joe Armstrong (111–120)
(gen_random_uuid(), 'Make it work, then make it beautiful, then if you really, really have to, make it fast.', 'Joe Armstrong', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'discipline', 'focus'], true, 'coding'),
(gen_random_uuid(), 'Erlang was designed for building fault-tolerant systems. Let it crash is not a bug; it is a philosophy.', 'Joe Armstrong', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'courage', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'The actor model says: processes are isolated, they share nothing, and they communicate only by sending messages.', 'Joe Armstrong', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'discipline', 'learning'], true, 'coding'),
(gen_random_uuid(), 'Concurrency is about dealing with a lot of things at once. Parallelism is about doing a lot of things at once.', 'Joe Armstrong', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'learning', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'Shared-state concurrency is the source of most bugs in concurrent programs. Avoid sharing state.', 'Joe Armstrong', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline', 'wisdom', 'focus'], true, 'coding'),
(gen_random_uuid(), 'A supervisor tree monitors processes and restarts them when they crash. Fault tolerance is structural, not exceptional.', 'Joe Armstrong', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'discipline', 'learning'], true, 'coding'),
(gen_random_uuid(), 'Nine nines of availability is not a goal you achieve with better code alone. It requires a systematic architecture for failure.', 'Joe Armstrong', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline', 'wisdom', 'focus'], true, 'coding'),
(gen_random_uuid(), 'In Erlang, the only way to share data between processes is to send a copy. This is not slow — it is safe.', 'Joe Armstrong', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'discipline', 'learning'], true, 'coding'),
(gen_random_uuid(), 'Hot code reloading means you can update a running system without stopping it. Downtime is optional.', 'Joe Armstrong', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'discipline', 'curiosity'], true, 'coding'),
(gen_random_uuid(), 'Distribution is what makes fault tolerance real. A node that shares no state with others can fail without affecting them.', 'Joe Armstrong', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'discipline', 'focus'], true, 'coding'),

-- Rich Hickey (121–131)
(gen_random_uuid(), 'Simplicity is the ultimate sophistication in software. Complect nothing that need not be complected.', 'Rich Hickey', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'discipline', 'focus'], true, 'coding'),
(gen_random_uuid(), 'Complecting is interleaving concerns that could be separate. Simple systems avoid complecting.', 'Rich Hickey', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'discipline', 'learning'], true, 'coding'),
(gen_random_uuid(), 'Mutable state is the root of complexity in most object-oriented systems. Embrace immutability.', 'Rich Hickey', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'discipline', 'focus'], true, 'coding'),
(gen_random_uuid(), 'Values are immutable. Identity is a succession of values over time. Do not conflate them.', 'Rich Hickey', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'learning', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'The database is a value. Datomic stores facts immutably. Queries can time-travel to any point in history.', 'Rich Hickey', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'curiosity', 'learning'], true, 'coding'),
(gen_random_uuid(), 'Data is the lingua franca of integration. Programs that speak data are more composable than programs that speak objects.', 'Rich Hickey', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'discipline', 'learning'], true, 'coding'),
(gen_random_uuid(), 'Transducers separate transformation from collection traversal. The same logic works on sequences, channels, and streams.', 'Rich Hickey', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'learning', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'Spec your data. A system that validates its inputs and outputs is a system that communicates its contracts clearly.', 'Rich Hickey', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline', 'wisdom', 'focus'], true, 'coding'),
(gen_random_uuid(), 'Polymorphism via protocols gives you open extension without the rigidity of class hierarchies.', 'Rich Hickey', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'learning', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'Core.async brings CSP-style channels to Clojure. Separate the logic of what to do from the machinery of when to do it.', 'Rich Hickey', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'discipline', 'learning'], true, 'coding'),
(gen_random_uuid(), 'Effective programs and effective programmers both need to recognize and eliminate incidental complexity.', 'Rich Hickey', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'discipline', 'focus'], true, 'coding'),

-- Rob Pike (132–141)
(gen_random_uuid(), 'Rule 1: You cannot tell where a program is going to spend its time. Bottlenecks occur in surprising places.', 'Rob Pike', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'discipline', 'focus'], true, 'coding'),
(gen_random_uuid(), 'Fancy algorithms are slow when n is small, and n is usually small. Use simple data structures.', 'Rob Pike', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'discipline', 'focus'], true, 'coding'),
(gen_random_uuid(), 'Data dominates. If you have chosen the right data structures and organized things well, the algorithms will almost always be self-evident.', 'Rob Pike', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'discipline', 'learning'], true, 'coding'),
(gen_random_uuid(), 'Concurrency is not parallelism. Concurrency is a design tool. Parallelism is an execution property.', 'Rob Pike', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'learning', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'Go''s goroutines are cheap. Spin up thousands of them. The scheduler handles the rest.', 'Rob Pike', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'discipline', 'learning'], true, 'coding'),
(gen_random_uuid(), 'Interfaces in Go are satisfied implicitly. Any type that has the methods satisfies the interface. No declaration needed.', 'Rob Pike', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'learning', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'Errors are values in Go. Handle them explicitly. Do not hide them behind exceptions.', 'Rob Pike', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline', 'wisdom', 'focus'], true, 'coding'),
(gen_random_uuid(), 'Channels are the pipes that connect concurrent goroutines. Pass data through channels, not shared memory.', 'Rob Pike', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'discipline', 'learning'], true, 'coding'),
(gen_random_uuid(), 'Do not communicate by sharing memory. Share memory by communicating.', 'Rob Pike', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'discipline', 'focus'], true, 'coding'),
(gen_random_uuid(), 'The gofmt tool formats Go code uniformly. Style debates disappear when a tool decides style for the whole community.', 'Rob Pike', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline', 'wisdom', 'focus'], true, 'coding'),

-- Ken Thompson (142–150)
(gen_random_uuid(), 'When in doubt, use brute force.', 'Ken Thompson', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'courage', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'One of my most productive days was throwing away 1,000 lines of code.', 'Ken Thompson', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline', 'wisdom', 'focus'], true, 'coding'),
(gen_random_uuid(), 'The Unix time-sharing system gave programmers an environment where they could experiment cheaply and share results instantly.', 'Ken Thompson', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'learning', 'creativity'], true, 'coding'),
(gen_random_uuid(), 'Regular expressions are a notation for the set of strings that a pattern matches. They are impossibly powerful.', 'Ken Thompson', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'learning', 'curiosity'], true, 'coding'),
(gen_random_uuid(), 'Trust is built through consistent behavior. A compiler you cannot trust is a compiler you cannot use.', 'Ken Thompson', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'discipline', 'focus'], true, 'coding'),
(gen_random_uuid(), 'The UTF-8 encoding of Unicode is elegant: ASCII is its own subset, and the byte boundaries are self-synchronizing.', 'Ken Thompson', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'learning', 'creativity'], true, 'coding'),
(gen_random_uuid(), 'Everything is a file in Unix. Sockets, pipes, devices — the uniform interface is its greatest design insight.', 'Ken Thompson', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'discipline', 'learning'], true, 'coding'),
(gen_random_uuid(), 'The B language led to C, which led to everything. Every chain of influence starts with one good idea pursued seriously.', 'Ken Thompson', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'curiosity', 'learning'], true, 'coding'),
(gen_random_uuid(), 'Security vulnerabilities are just bugs in unexpected places. You cannot separate security engineering from software engineering.', 'Ken Thompson', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline', 'wisdom', 'focus'], true, 'coding'),

-- Ryan Dahl (151–159)
(gen_random_uuid(), 'Node.js was built on the insight that I/O does not need a thread. Non-blocking I/O changes the cost model entirely.', 'Ryan Dahl', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'learning', 'curiosity'], true, 'coding'),
(gen_random_uuid(), 'Callbacks were a mistake. Promises were better. Async/await makes asynchronous code read like synchronous code.', 'Ryan Dahl', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'learning', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'The event loop processes one event at a time. Never block the event loop with synchronous operations.', 'Ryan Dahl', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline', 'wisdom', 'focus'], true, 'coding'),
(gen_random_uuid(), 'Deno was built to fix the regrets of Node. Security by default, no node_modules, TypeScript first-class.', 'Ryan Dahl', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['courage', 'wisdom', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'Streams are the right abstraction for I/O. Don''t buffer everything in memory when you can process it incrementally.', 'Ryan Dahl', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'discipline', 'focus'], true, 'coding'),
(gen_random_uuid(), 'The V8 engine made JavaScript fast enough for the server. A single language across client and server is a genuine productivity win.', 'Ryan Dahl', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'learning', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'Web servers are fundamentally I/O bound, not CPU bound. Non-blocking I/O is the right fit for most backend work.', 'Ryan Dahl', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'discipline', 'learning'], true, 'coding'),
(gen_random_uuid(), 'Simplicity at the API level hides enormous complexity underneath. That is the right trade-off for a platform.', 'Ryan Dahl', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'discipline', 'focus'], true, 'coding'),
(gen_random_uuid(), 'Regrets are data. Every API decision I got wrong in Node taught me what to get right in Deno.', 'Ryan Dahl', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'learning', 'courage'], true, 'coding'),

-- DHH - David Heinemeier Hansson (160–169)
(gen_random_uuid(), 'Convention over configuration: if you follow the conventions, you get a lot of things for free.', 'David Heinemeier Hansson', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline', 'wisdom', 'focus'], true, 'coding'),
(gen_random_uuid(), 'Rails was extracted from a real application. The framework serves the application, not the other way around.', 'David Heinemeier Hansson', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'discipline', 'learning'], true, 'coding'),
(gen_random_uuid(), 'Programmer happiness is a feature. A language and framework that make you smile produce better software.', 'David Heinemeier Hansson', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'creativity', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'REST is an architectural style, not a protocol. Thinking in resources and representations is a genuine insight.', 'David Heinemeier Hansson', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'discipline', 'learning'], true, 'coding'),
(gen_random_uuid(), 'You are not Google. Stop building for Google-scale until you are Google-scale. Solve today''s problems.', 'David Heinemeier Hansson', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'discipline', 'courage'], true, 'coding'),
(gen_random_uuid(), 'The monolith is not legacy. A majestic monolith is often the right choice for most teams at most scales.', 'David Heinemeier Hansson', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'courage', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'Calm technology: applications that demand the least possible attention while delivering the most possible value.', 'David Heinemeier Hansson', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'discipline', 'focus'], true, 'coding'),
(gen_random_uuid(), 'The database schema is the backbone of your application. Get it right early; changing it later is expensive.', 'David Heinemeier Hansson', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline', 'wisdom', 'focus'], true, 'coding'),
(gen_random_uuid(), 'Active Record is not an anti-pattern. It is a pattern that matches the structure of relational databases perfectly.', 'David Heinemeier Hansson', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'discipline', 'learning'], true, 'coding'),
(gen_random_uuid(), 'Open source is not charity. It is infrastructure. The community of contributors is its own reward.', 'David Heinemeier Hansson', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'courage', 'learning'], true, 'coding'),

-- Jeff Dean (170–179)
(gen_random_uuid(), 'MapReduce was born from the need to process petabytes of data on thousands of unreliable machines. Simplicity at scale.', 'Jeff Dean', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'discipline', 'learning'], true, 'coding'),
(gen_random_uuid(), 'Bigtable stores data across many machines and makes it look like a single consistent table. Abstraction is the engine of scale.', 'Jeff Dean', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'discipline', 'learning'], true, 'coding'),
(gen_random_uuid(), 'Latency numbers every programmer should know: L1 cache 0.5ns, main memory 100ns, SSD 100µs, network 150ms.', 'Jeff Dean', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'discipline', 'learning'], true, 'coding'),
(gen_random_uuid(), 'The tail latency problem: at 1000 servers, the slowest 1% affects every request. Design to reduce tail latencies.', 'Jeff Dean', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'discipline', 'focus'], true, 'coding'),
(gen_random_uuid(), 'Spanner achieves globally distributed transactions with external consistency. TrueTime makes the impossible possible.', 'Jeff Dean', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'learning', 'curiosity'], true, 'coding'),
(gen_random_uuid(), 'The GFS insight: hardware failure is the norm, not the exception. Design systems where hardware failure is routine.', 'Jeff Dean', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'discipline', 'courage'], true, 'coding'),
(gen_random_uuid(), 'Borg was container orchestration before Kubernetes. The ideas are not new; the accessibility of Kubernetes is.', 'Jeff Dean', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'learning', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'Neural architecture search automates what human ML engineers do manually. The future of ML is meta-learning.', 'Jeff Dean', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'curiosity', 'learning'], true, 'coding'),
(gen_random_uuid(), 'Distillation compresses a large model into a small one that retains most of its capability. Efficiency is a first-class concern.', 'Jeff Dean', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'discipline', 'focus'], true, 'coding'),
(gen_random_uuid(), 'Designing for 10x scale usually requires a new architecture, not just more hardware. Anticipate the cliff.', 'Jeff Dean', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'discipline', 'learning'], true, 'coding'),

-- Guido van Rossum (180–188)
(gen_random_uuid(), 'There should be one obvious way to do it. That is the Zen of Python applied to API design.', 'Guido van Rossum', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'discipline', 'focus'], true, 'coding'),
(gen_random_uuid(), 'Explicit is better than implicit. Name things clearly; do not rely on clever inferences.', 'Guido van Rossum', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'discipline', 'learning'], true, 'coding'),
(gen_random_uuid(), 'Readability counts. Code is read far more often than it is written. Optimize for the reader.', 'Guido van Rossum', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'discipline', 'focus'], true, 'coding'),
(gen_random_uuid(), 'Errors should never pass silently unless explicitly silenced. Fail loudly; never swallow exceptions.', 'Guido van Rossum', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline', 'wisdom', 'focus'], true, 'coding'),
(gen_random_uuid(), 'In the face of ambiguity, refuse the temptation to guess. A system that guesses is a system that surprises.', 'Guido van Rossum', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'discipline', 'focus'], true, 'coding'),
(gen_random_uuid(), 'Now is better than never. An imperfect solution that ships beats a perfect solution that doesn''t.', 'Guido van Rossum', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'discipline', 'courage'], true, 'coding'),
(gen_random_uuid(), 'Special cases aren''t special enough to break the rules. Consistency in an API is a form of respect for its users.', 'Guido van Rossum', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'discipline', 'focus'], true, 'coding'),
(gen_random_uuid(), 'Beautiful is better than ugly. A codebase you are proud of is a codebase people want to contribute to.', 'Guido van Rossum', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'creativity', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'The GIL is a trade-off: it simplifies CPython and makes threading safer at the cost of true parallelism. Use multiprocessing for CPU work.', 'Guido van Rossum', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'discipline', 'learning'], true, 'coding'),

-- Bjarne Stroustrup (189–197)
(gen_random_uuid(), 'C makes it easy to shoot yourself in the foot. C++ makes it harder, but when you do, it blows your whole leg off.', 'Bjarne Stroustrup', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'discipline', 'courage'], true, 'coding'),
(gen_random_uuid(), 'There are only two kinds of programming languages: the ones people complain about and the ones nobody uses.', 'Bjarne Stroustrup', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'courage', 'curiosity'], true, 'coding'),
(gen_random_uuid(), 'An abstract machine is not an overhead. It is the foundation on which portable, maintainable software is built.', 'Bjarne Stroustrup', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'learning', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'Resource Acquisition Is Initialization: manage resources through objects whose destructors release them. RAII is the foundation of safe C++.', 'Bjarne Stroustrup', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline', 'wisdom', 'focus'], true, 'coding'),
(gen_random_uuid(), 'The best software is software that solves a problem without being seen. Complexity is the enemy of reliability.', 'Bjarne Stroustrup', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'discipline', 'focus'], true, 'coding'),
(gen_random_uuid(), 'Zero-overhead abstraction: what you don''t use, you don''t pay for. What you do use, you couldn''t hand-code any better.', 'Bjarne Stroustrup', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'discipline', 'focus'], true, 'coding'),
(gen_random_uuid(), 'Type-safety is not a constraint. It is a tool that lets the compiler find entire classes of bugs before runtime.', 'Bjarne Stroustrup', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'discipline', 'learning'], true, 'coding'),
(gen_random_uuid(), 'C++ is designed to allow you to express ideas directly in code. Express the algorithm, not the machine.', 'Bjarne Stroustrup', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'discipline', 'creativity'], true, 'coding'),
(gen_random_uuid(), 'Every feature in a programming language is a trade-off. Understand the trade-off before choosing the feature.', 'Bjarne Stroustrup', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'discipline', 'learning'], true, 'coding'),

-- Anders Hejlsberg (198–206)
(gen_random_uuid(), 'TypeScript''s type system is structural, not nominal. If it has the shape, it fits the type. Duck typing with a safety net.', 'Anders Hejlsberg', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'learning', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'A great type system catches bugs at compile time that would only surface at runtime. Shift errors left.', 'Anders Hejlsberg', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline', 'wisdom', 'focus'], true, 'coding'),
(gen_random_uuid(), 'Language design is library design and library design is language design. They are inseparable.', 'Anders Hejlsberg', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'discipline', 'learning'], true, 'coding'),
(gen_random_uuid(), 'Async and await are syntactic sugar over promises, but that sugar makes asynchronous code dramatically more maintainable.', 'Anders Hejlsberg', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'discipline', 'learning'], true, 'coding'),
(gen_random_uuid(), 'Generics allow you to write algorithms that work on any type while preserving type safety. Write once, use everywhere.', 'Anders Hejlsberg', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'discipline', 'focus'], true, 'coding'),
(gen_random_uuid(), 'LINQ brought query language into the type system. Data access and object manipulation use the same expressive syntax.', 'Anders Hejlsberg', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'creativity', 'learning'], true, 'coding'),
(gen_random_uuid(), 'The Roslyn compiler exposes the full compiler pipeline as an API. Tools that understand code are better than tools that parse text.', 'Anders Hejlsberg', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'learning', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'Nullability annotations in C# make null-safety explicit. Declare your intent; let the compiler enforce it.', 'Anders Hejlsberg', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline', 'wisdom', 'focus'], true, 'coding'),
(gen_random_uuid(), 'Records are immutable data containers. Immutability plus value semantics equals predictable, thread-safe code.', 'Anders Hejlsberg', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'discipline', 'focus'], true, 'coding'),

-- James Gosling (207–214)
(gen_random_uuid(), 'Write once, run anywhere was not a marketing slogan. It was a genuine insight about the cost of platform fragmentation.', 'James Gosling', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'discipline', 'learning'], true, 'coding'),
(gen_random_uuid(), 'The JVM is one of the greatest engineering achievements in software. Decades of optimization make it formidably fast.', 'James Gosling', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'discipline', 'learning'], true, 'coding'),
(gen_random_uuid(), 'Garbage collection eliminated an entire class of bugs at the cost of predictable latency. For most applications, it is the right trade-off.', 'James Gosling', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'discipline', 'focus'], true, 'coding'),
(gen_random_uuid(), 'Java was designed to be familiar. A C++ programmer could read Java code on day one. Adoption depends on familiarity.', 'James Gosling', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'learning', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'Thread safety is not optional in a concurrent system. Every shared mutable state is a potential race condition.', 'James Gosling', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline', 'wisdom', 'focus'], true, 'coding'),
(gen_random_uuid(), 'Java''s checked exceptions force callers to handle errors explicitly. The compiler becomes a reminder of what can go wrong.', 'James Gosling', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline', 'wisdom', 'learning'], true, 'coding'),
(gen_random_uuid(), 'Interfaces define contracts. An API is a promise to its callers, and interfaces make that promise explicit and verifiable.', 'James Gosling', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'discipline', 'focus'], true, 'coding'),
(gen_random_uuid(), 'Spring grew because Java EE was too heavy. The best frameworks reduce friction without hiding what is happening.', 'James Gosling', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'discipline', 'learning'], true, 'coding'),

-- Yukihiro Matsumoto (215–222)
(gen_random_uuid(), 'I wanted a language more powerful than Perl and more object-oriented than Python. That is why I created Ruby.', 'Yukihiro Matsumoto', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['creativity', 'wisdom', 'courage'], true, 'coding'),
(gen_random_uuid(), 'The principle of least surprise: the language should behave in a way that minimizes confusion for experienced programmers.', 'Yukihiro Matsumoto', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'discipline', 'focus'], true, 'coding'),
(gen_random_uuid(), 'Everything in Ruby is an object. Even integers and booleans respond to methods. Uniformity breeds elegance.', 'Yukihiro Matsumoto', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'learning', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'Matz is nice and so we are nice. The Ruby community''s culture reflects the language''s design philosophy.', 'Yukihiro Matsumoto', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'learning', 'courage'], true, 'coding'),
(gen_random_uuid(), 'Duck typing means you do not check what something is; you check what it can do. Behavior over identity.', 'Yukihiro Matsumoto', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'discipline', 'learning'], true, 'coding'),
(gen_random_uuid(), 'Blocks in Ruby are closures that make iteration and resource management elegantly expressible.', 'Yukihiro Matsumoto', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'creativity', 'learning'], true, 'coding'),
(gen_random_uuid(), 'Metaprogramming in Ruby lets the language describe itself. Code that writes code is the ultimate abstraction.', 'Yukihiro Matsumoto', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'creativity', 'learning'], true, 'coding'),
(gen_random_uuid(), 'The goal of Ruby is to make programmers happy. Productivity and joy are not in conflict; they are the same thing.', 'Yukihiro Matsumoto', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'creativity', 'discipline'], true, 'coding'),

-- Brendan Eich (223–228)
(gen_random_uuid(), 'JavaScript was designed in ten days. It is a testament to the power of a good idea that it is still running the web thirty years later.', 'Brendan Eich', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'curiosity', 'learning'], true, 'coding'),
(gen_random_uuid(), 'The prototype chain gives JavaScript a form of inheritance that is more flexible than classical inheritance.', 'Brendan Eich', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'learning', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'Closures are JavaScript''s most powerful feature. They capture the environment where they were created.', 'Brendan Eich', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'learning', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'JavaScript''s event loop and non-blocking I/O were not planned for the server, but Node proved they work there too.', 'Brendan Eich', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'curiosity', 'learning'], true, 'coding'),
(gen_random_uuid(), 'TC39 moves carefully. Breaking the web is not an option when billions of pages depend on your language.', 'Brendan Eich', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline', 'wisdom', 'focus'], true, 'coding'),
(gen_random_uuid(), 'Always bet on JavaScript. It survives because it is the only language that runs natively in every browser.', 'Brendan Eich', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'courage', 'learning'], true, 'coding'),

-- Sanjay Ghemawat (229–234)
(gen_random_uuid(), 'The Google File System assumes failures are normal. Replication and checksums are not optional extras; they are the core design.', 'Sanjay Ghemawat', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline', 'wisdom', 'focus'], true, 'coding'),
(gen_random_uuid(), 'Chubby provides a distributed lock service. Coordination in distributed systems requires a single source of truth.', 'Sanjay Ghemawat', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'discipline', 'learning'], true, 'coding'),
(gen_random_uuid(), 'Colossus improved on GFS by eliminating the single master bottleneck. Every bottleneck you remove reveals the next one.', 'Sanjay Ghemawat', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'discipline', 'focus'], true, 'coding'),
(gen_random_uuid(), 'SSTable is the storage format behind Bigtable. Immutable sorted files make compaction and range scans efficient.', 'Sanjay Ghemawat', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'learning', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'Profiling at scale reveals different bottlenecks than profiling a single machine. Always profile at the target scale.', 'Sanjay Ghemawat', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'discipline', 'focus'], true, 'coding'),
(gen_random_uuid(), 'The best systems papers describe systems that were actually built and run in production. Theory validated by practice.', 'Sanjay Ghemawat', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'discipline', 'learning'], true, 'coding'),

-- Dennis Ritchie (235–241)
(gen_random_uuid(), 'C is quirky, flawed, and an enormous success. It is the closest to the hardware without being assembly.', 'Dennis Ritchie', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'discipline', 'courage'], true, 'coding'),
(gen_random_uuid(), 'Unix was not designed to stop its users from doing stupid things, as that would also stop them from doing clever things.', 'Dennis Ritchie', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'courage', 'creativity'], true, 'coding'),
(gen_random_uuid(), 'The only way to learn a new programming language is by writing programs in it. There is no shortcut.', 'Dennis Ritchie', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline', 'wisdom', 'learning'], true, 'coding'),
(gen_random_uuid(), 'Keeping Unix small and simple was a deliberate choice. You can only control what you can understand.', 'Dennis Ritchie', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'discipline', 'focus'], true, 'coding'),
(gen_random_uuid(), 'The pipe is Unix''s most profound contribution: small programs communicating through a universal interface.', 'Dennis Ritchie', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'creativity', 'learning'], true, 'coding'),
(gen_random_uuid(), 'Pointer arithmetic gives you direct control over memory. That power demands corresponding discipline.', 'Dennis Ritchie', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline', 'wisdom', 'focus'], true, 'coding'),
(gen_random_uuid(), 'Systems programming is the art of building the platform on which everything else runs. It requires understanding the machine fully.', 'Dennis Ritchie', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'learning', 'discipline'], true, 'coding'),

-- General Backend Wisdom — attributed to canonical authors (242–250)
(gen_random_uuid(), 'An API is a contract. Breaking it silently is a betrayal of every caller who trusted it.', 'Martin Fowler', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline', 'wisdom', 'focus'], true, 'coding'),
(gen_random_uuid(), 'Cache invalidation is one of the two hard problems in computer science. Choose your caching strategy with care.', 'Martin Fowler', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'discipline', 'learning'], true, 'coding'),
(gen_random_uuid(), 'Observability is not monitoring. Monitoring asks: is it up? Observability asks: why is it behaving this way?', 'Werner Vogels', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'discipline', 'learning'], true, 'coding'),
(gen_random_uuid(), 'GraphQL gives clients the power to ask for exactly what they need and nothing more. Underfetching and overfetching disappear.', 'Rob Pike', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'discipline', 'focus'], true, 'coding'),
(gen_random_uuid(), 'A load balancer distributes traffic across servers to prevent any single node from becoming a bottleneck or a single point of failure.', 'Leslie Lamport', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'discipline', 'learning'], true, 'coding'),
(gen_random_uuid(), 'Message queues decouple producers from consumers in time. The queue absorbs bursts and smooths out spikes.', 'Joe Armstrong', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'discipline', 'focus'], true, 'coding'),
(gen_random_uuid(), 'Containers bundle an application with its dependencies. What runs in development runs in production. No surprises.', 'Werner Vogels', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline', 'wisdom', 'focus'], true, 'coding'),
(gen_random_uuid(), 'JWT encodes claims that can be verified without a database lookup. Stateless authentication scales horizontally.', 'Robert C. Martin', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'discipline', 'focus'], true, 'coding'),
(gen_random_uuid(), 'The circuit breaker pattern stops cascading failures. When a dependency is down, fail fast instead of waiting and tying up resources.', 'Martin Fowler', 'philosophy', 'en', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom', 'discipline', 'courage'], true, 'coding')

ON CONFLICT (text, author) DO NOTHING;

COMMIT;
