-- 037_coding_devops_en.sql
-- MindScrolling — Coding Mode: DevOps & Tools batch (English)
-- 250 quotes: CI/CD, Docker, Kubernetes, monitoring, logging, infrastructure as code,
--   cloud computing, git, testing pipelines, automation, SRE, incident response,
--   observability, performance, deployment strategies, Terraform, AWS, Linux,
--   shell scripting, open source
--
-- All rows:
--   category       = 'philosophy'
--   lang           = 'en'
--   swipe_dir      = 'down'
--   pack_name      = 'free'
--   is_premium     = false
--   content_type   = 'coding'
--   sub_category   = 'devops_tools'
--   is_hidden_mode = true
--   locked_by      = 'coding'
-- Run in Supabase SQL Editor

BEGIN;

-- ══════════════════════════════════════════════════════════════════════════════
-- CODING DEVOPS & TOOLS — ENGLISH (250 quotes)
-- ══════════════════════════════════════════════════════════════════════════════

INSERT INTO quotes (id, text, author, category, lang, swipe_dir, pack_name, is_premium, content_type, sub_category, tags, is_hidden_mode, locked_by) VALUES

-- Gene Kim (1–16)
(gen_random_uuid(), 'Improving daily work is even more important than doing daily work.', 'Gene Kim', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','focus'], true, 'coding'),
(gen_random_uuid(), 'The First Way emphasizes the performance of the entire system, as opposed to the performance of a specific silo of work or department.', 'Gene Kim', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'The Second Way is about creating the right to left feedback loops. The goal of almost any process improvement initiative is to shorten and amplify feedback loops.', 'Gene Kim', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','focus'], true, 'coding'),
(gen_random_uuid(), 'The Third Way is about creating a culture that fosters two things: continual experimentation and understanding that repetition and practice is the prerequisite to mastery.', 'Gene Kim', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'Unplanned work is always more costly than planned work.', 'Gene Kim', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'Technical debt is like a financial debt. Unless you pay down the principal, you will forever be paying interest.', 'Gene Kim', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'Until code is in production, no value is actually being generated, because it''s merely WIP stuck in the system.', 'Gene Kim', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','focus'], true, 'coding'),
(gen_random_uuid(), 'Every business is a software business. You have to start thinking and acting like a digital company.', 'Gene Kim', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','learning'], true, 'coding'),
(gen_random_uuid(), 'In DevOps, we believe that the biggest risk is not moving quickly enough.', 'Gene Kim', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['courage','discipline'], true, 'coding'),
(gen_random_uuid(), 'Waiting for a perfect solution is itself a form of waste.', 'Gene Kim', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','focus'], true, 'coding'),
(gen_random_uuid(), 'Constraints dictate where to focus improvement efforts. Find the bottleneck and exploit it.', 'Gene Kim', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'Resilience is built by practicing failure before it happens to you.', 'Gene Kim', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','courage'], true, 'coding'),
(gen_random_uuid(), 'The goal is not to eliminate change, but to be able to handle change with grace.', 'Gene Kim', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'Automation is not about replacing people. It is about freeing people to do higher-value work.', 'Gene Kim', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','focus'], true, 'coding'),
(gen_random_uuid(), 'When things go wrong, and they always will, the question is: how fast can you detect and fix the problem?', 'Gene Kim', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'Small batch sizes reduce variability and make problems visible sooner.', 'Gene Kim', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','focus'], true, 'coding'),

-- Jez Humble (17–32)
(gen_random_uuid(), 'The biggest risk in software development is building something that nobody wants.', 'Jez Humble', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'Continuous delivery is the ability to get changes of all types into production safely, quickly, and sustainably.', 'Jez Humble', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','focus'], true, 'coding'),
(gen_random_uuid(), 'Every build should be production-ready. If your software is not deployable at all times, you are accumulating risk.', 'Jez Humble', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'The goal of continuous integration is that software is always in a working state.', 'Jez Humble', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','focus'], true, 'coding'),
(gen_random_uuid(), 'Configuration management is the foundation of everything you do in deployment.', 'Jez Humble', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'Test environments that differ from production are a source of constant pain and bugs.', 'Jez Humble', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','focus'], true, 'coding'),
(gen_random_uuid(), 'A deployment pipeline is your best documentation of how software gets from code to production.', 'Jez Humble', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'Make it easy to do the right thing and hard to do the wrong thing in your deployment process.', 'Jez Humble', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','focus'], true, 'coding'),
(gen_random_uuid(), 'Release frequency and release stability are not opposites; with the right practices, they reinforce each other.', 'Jez Humble', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'Trunk-based development requires discipline, but it enables speed.', 'Jez Humble', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','focus'], true, 'coding'),
(gen_random_uuid(), 'Rolling back is always safer than rolling forward when you do not understand the failure.', 'Jez Humble', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'If it hurts, do it more often and bring the pain forward.', 'Jez Humble', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','courage'], true, 'coding'),
(gen_random_uuid(), 'Infrastructure as code means your infrastructure is reviewable, testable, and versioned just like application code.', 'Jez Humble', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'Lean thinking applied to software delivery means reducing batch size and increasing flow.', 'Jez Humble', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','focus'], true, 'coding'),
(gen_random_uuid(), 'Monitoring is not optional in a continuous delivery pipeline. It is the feedback loop that closes the cycle.', 'Jez Humble', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'Automated testing is the safety net that lets you move fast without breaking things.', 'Jez Humble', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','focus'], true, 'coding'),

-- Patrick Debois (33–44)
(gen_random_uuid(), 'DevOps is not a tool. It is a culture. Tools enable the culture but they cannot replace it.', 'Patrick Debois', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'The wall between development and operations is built from misaligned incentives, not incompatible skills.', 'Patrick Debois', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'When you share responsibility for production, you write better code.', 'Patrick Debois', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'Collaboration across silos is not a nice-to-have. It is the core of DevOps.', 'Patrick Debois', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'Empathy between dev and ops teams is more powerful than any process improvement.', 'Patrick Debois', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','learning'], true, 'coding'),
(gen_random_uuid(), 'Every incident is an opportunity to learn something you did not know about your system.', 'Patrick Debois', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['learning','wisdom'], true, 'coding'),
(gen_random_uuid(), 'Systems thinking means you optimize the whole, not the parts in isolation.', 'Patrick Debois', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'Feedback without action is noise. Action without feedback is blind.', 'Patrick Debois', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'The shortest path to production is a straight line through trust.', 'Patrick Debois', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'Breaking down silos requires vulnerability. You have to admit what you do not know.', 'Patrick Debois', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['courage','wisdom'], true, 'coding'),
(gen_random_uuid(), 'Continuous improvement is not a project. It is a habit embedded in daily work.', 'Patrick Debois', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','focus'], true, 'coding'),
(gen_random_uuid(), 'Start small, automate one thing, and build momentum from there.', 'Patrick Debois', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','focus'], true, 'coding'),

-- Werner Vogels (45–58)
(gen_random_uuid(), 'Everything fails, all the time.', 'Werner Vogels', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'You build it, you run it. That means you own the full lifecycle of your software.', 'Werner Vogels', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','focus'], true, 'coding'),
(gen_random_uuid(), 'Design for failure means designing so that when failure occurs, it is contained, predictable, and recoverable.', 'Werner Vogels', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'Loose coupling allows you to move fast without dragging every other part of the system with you.', 'Werner Vogels', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'Scalability is not about handling peak load. It is about recovering predictably after peak load.', 'Werner Vogels', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'The cloud is not just hosting. It is a platform for building systems that could not exist before.', 'Werner Vogels', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','learning'], true, 'coding'),
(gen_random_uuid(), 'Undifferentiated heavy lifting is the enemy of innovation. Outsource what does not distinguish you.', 'Werner Vogels', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'Availability is not a feature you add later. It is an architectural decision you make first.', 'Werner Vogels', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'Operational excellence is the competitive advantage you cannot buy and cannot copy overnight.', 'Werner Vogels', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'Chaos engineering is institutionalized humility. You assume your system will fail.', 'Werner Vogels', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'In distributed systems, the network is never reliable. Build as if it is always lying to you.', 'Werner Vogels', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'Two-pizza teams stay focused because they cannot afford to diffuse their attention.', 'Werner Vogels', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','focus'], true, 'coding'),
(gen_random_uuid(), 'Idempotency in operations means you can retry safely without fear of side effects.', 'Werner Vogels', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'Working backwards from the customer is not a slogan. It is a design methodology.', 'Werner Vogels', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','focus'], true, 'coding'),

-- Charity Majors (59–72)
(gen_random_uuid(), 'Observability is not about collecting more data. It is about being able to ask new questions of your system.', 'Charity Majors', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'If you cannot debug your system in production, you do not understand your system.', 'Charity Majors', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'Shipping is the heartbeat of a healthy engineering team.', 'Charity Majors', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','focus'], true, 'coding'),
(gen_random_uuid(), 'Tests tell you what you already know your code should do. Observability tells you what you do not know yet.', 'Charity Majors', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','learning'], true, 'coding'),
(gen_random_uuid(), 'High cardinality is what separates observability from monitoring. You need to slice data by any dimension.', 'Charity Majors', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'Production is the only place where you discover what your system actually does.', 'Charity Majors', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','learning'], true, 'coding'),
(gen_random_uuid(), 'Alerting on symptoms rather than causes is the difference between a good on-call and a miserable one.', 'Charity Majors', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'Software engineers who never go on-call write software that is unpleasant to operate.', 'Charity Majors', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'Structured events are the atomic unit of observability. Everything else is derived from them.', 'Charity Majors', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'Distributed tracing is how you understand cause and effect in systems too complex to reason about locally.', 'Charity Majors', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','learning'], true, 'coding'),
(gen_random_uuid(), 'The on-call experience is the feedback mechanism that makes your architecture honest.', 'Charity Majors', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'Sociotechnical systems fail at the seams between teams. That is where you instrument first.', 'Charity Majors', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'Fast deploys make incidents smaller. Small incidents make deploys less scary.', 'Charity Majors', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','focus'], true, 'coding'),
(gen_random_uuid(), 'You can have fast deploys or slow deploys. Fast deploys give you faster recovery.', 'Charity Majors', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','wisdom'], true, 'coding'),

-- Kelsey Hightower (73–86)
(gen_random_uuid(), 'Kubernetes is a platform for building platforms. If you are using it directly, you are doing too much work.', 'Kelsey Hightower', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'The best container orchestration is the one your team understands and operates confidently.', 'Kelsey Hightower', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'Simplicity in infrastructure is a competitive advantage that compounds over time.', 'Kelsey Hightower', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'No one gets credit for fixing problems that were never caused. Boring infrastructure is successful infrastructure.', 'Kelsey Hightower', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'Running Kubernetes in production is not the goal. Serving customers reliably is the goal.', 'Kelsey Hightower', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','focus'], true, 'coding'),
(gen_random_uuid(), 'Infrastructure automation is not about removing humans. It is about removing toil so humans can think.', 'Kelsey Hightower', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'Containers enforce the discipline of stateless services. If your app cannot run in a container, fix your app.', 'Kelsey Hightower', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','focus'], true, 'coding'),
(gen_random_uuid(), 'Cloud native does not mean cloud-hosted. It means designed to exploit the properties of the cloud.', 'Kelsey Hightower', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','learning'], true, 'coding'),
(gen_random_uuid(), 'Service meshes are an answer to a question you should first ask: do I have the problem they solve?', 'Kelsey Hightower', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'The goal of platform engineering is to make the right path the easiest path for developers.', 'Kelsey Hightower', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'Declarative configuration means you describe what you want, not how to get there. Machines figure out the how.', 'Kelsey Hightower', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'Health checks are the simplest form of observability. Never deploy a service without them.', 'Kelsey Hightower', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','focus'], true, 'coding'),
(gen_random_uuid(), 'Immutable infrastructure means you never patch in place. You replace. This eliminates an entire class of drift.', 'Kelsey Hightower', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'You do not need Kubernetes. You need to ship software reliably. Sometimes those are the same answer.', 'Kelsey Hightower', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','focus'], true, 'coding'),

-- John Allspaw (87–98)
(gen_random_uuid(), 'Blameless postmortems are not just a practice. They are a statement about what kind of organization you are.', 'John Allspaw', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'The goal of a postmortem is not to find who was at fault. It is to understand how the system failed.', 'John Allspaw', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','learning'], true, 'coding'),
(gen_random_uuid(), 'Resilience engineering is the study of how complex systems succeed, not just how they fail.', 'John Allspaw', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','learning'], true, 'coding'),
(gen_random_uuid(), 'Engineers are not the last line of defense. Defenses need to be layered across the whole system.', 'John Allspaw', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'Incidents reveal the distance between how you think your system works and how it actually works.', 'John Allspaw', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','learning'], true, 'coding'),
(gen_random_uuid(), 'Safety is not the absence of incidents. It is the presence of adaptive capacity.', 'John Allspaw', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'Feature flags are operational controls. Treat them with the same rigor as configuration management.', 'John Allspaw', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'Debugging in production requires courage and the observability tools to support that courage.', 'John Allspaw', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['courage','discipline'], true, 'coding'),
(gen_random_uuid(), 'Cognitive work during incidents is not a problem to eliminate. It is a capacity to develop.', 'John Allspaw', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','learning'], true, 'coding'),
(gen_random_uuid(), 'Change management that prevents change is not risk management. It is organizational self-harm.', 'John Allspaw', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'The best incident commanders know when to delegate and when to intervene.', 'John Allspaw', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'Automation does not remove human judgment. It changes the domain in which human judgment is applied.', 'John Allspaw', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),

-- Martin Fowler (99–112)
(gen_random_uuid(), 'Continuous integration is a practice, not a tool. The tool supports the practice but cannot replace it.', 'Martin Fowler', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'Feature branching is a poor man''s modular architecture with high merge costs.', 'Martin Fowler', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'Any fool can write code that a computer can understand. Good engineers write code that humans can understand.', 'Martin Fowler', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'Microservices are a form of modular decomposition. But modular decomposition requires modular thinking first.', 'Martin Fowler', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'Before you adopt microservices, make sure you have mastered the monolith.', 'Martin Fowler', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'The most important sign of a good test suite is that it gives you confidence to change code.', 'Martin Fowler', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','focus'], true, 'coding'),
(gen_random_uuid(), 'Deployments should be boring events. If they are exciting, you have a process problem.', 'Martin Fowler', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'Infrastructure code should be held to the same standards as application code.', 'Martin Fowler', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'Database migrations are not a deployment step. They are a database evolution strategy.', 'Martin Fowler', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'A good deployment pipeline is the best kind of documentation: it shows exactly what happens, in order.', 'Martin Fowler', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'Technical debt is not a metaphor. It has real interest payments measured in slower delivery.', 'Martin Fowler', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'Canary releases let you validate changes in production before committing to full rollout.', 'Martin Fowler', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'Blue-green deployments make rollback a two-step switch, not a multi-hour recovery operation.', 'Martin Fowler', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'Refactoring without tests is just moving technical debt around.', 'Martin Fowler', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','focus'], true, 'coding'),

-- Linus Torvalds (113–126)
(gen_random_uuid(), 'In open source, we feel strongly that to really do something well, you have to get a lot of people involved.', 'Linus Torvalds', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','learning'], true, 'coding'),
(gen_random_uuid(), 'Git is designed to be a content-addressable filesystem. Everything follows from that.', 'Linus Torvalds', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'Talk is cheap. Show me the code.', 'Linus Torvalds', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','focus'], true, 'coding'),
(gen_random_uuid(), 'The Linux philosophy is ''Laugh in the face of danger''. Oops. Wrong one. ''Do it yourself''. Yes, that''s it.', 'Linus Torvalds', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['courage','discipline'], true, 'coding'),
(gen_random_uuid(), 'Bad programmers worry about the code. Good programmers worry about data structures and their relationships.', 'Linus Torvalds', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'Most good programmers do programming not because they expect to get paid, but because it is fun to program.', 'Linus Torvalds', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','passion'], true, 'coding'),
(gen_random_uuid(), 'Intelligence is the ability to avoid doing work, yet getting the work done.', 'Linus Torvalds', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'Software is like sex: it''s better when it''s free.', 'Linus Torvalds', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','courage'], true, 'coding'),
(gen_random_uuid(), 'If you think your users are idiots, only idiots will use it.', 'Linus Torvalds', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'The single most important thing in open source is transparent development with public patches.', 'Linus Torvalds', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'Security holes are not a feature. They are bugs that happen to be security-relevant.', 'Linus Torvalds', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'Given enough eyeballs, all bugs are shallow. That is the whole point of open source.', 'Linus Torvalds', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','learning'], true, 'coding'),
(gen_random_uuid(), 'Portability is for people who cannot write new programs.', 'Linus Torvalds', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','courage'], true, 'coding'),
(gen_random_uuid(), 'A filesystem is not just a storage mechanism. It is a contract between the OS and the applications.', 'Linus Torvalds', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),

-- Dennis Ritchie & Ken Thompson (127–138)
(gen_random_uuid(), 'UNIX is basically a simple operating system, but you have to be a genius to understand the simplicity.', 'Dennis Ritchie', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'The only way to learn a new programming language is by writing programs in it.', 'Dennis Ritchie', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'C is quirky, flawed, and an enormous success.', 'Dennis Ritchie', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','courage'], true, 'coding'),
(gen_random_uuid(), 'The tools we build shape the kind of thinking we do. Choose tools that make hard things possible.', 'Dennis Ritchie', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'The Unix philosophy: write programs that do one thing well, and work together through clean interfaces.', 'Ken Thompson', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'One of the best programming skills you can have is knowing when to walk away and come back later.', 'Ken Thompson', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'Rule one of systems design: if a system works, do not redesign it until you understand why it works.', 'Ken Thompson', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'When in doubt, use brute force. Clever solutions have more places to hide bugs.', 'Ken Thompson', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'Pipes are the original composable abstraction. Everything that followed owes a debt to that idea.', 'Ken Thompson', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','learning'], true, 'coding'),
(gen_random_uuid(), 'The shell is both a command interpreter and a programming language. That duality is its greatest strength.', 'Ken Thompson', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'A small system that solves its problem exactly is worth more than a large system that solves it approximately.', 'Dennis Ritchie', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'Text streams are the universal interface of Unix. Any tool that reads text can work with any tool that writes it.', 'Dennis Ritchie', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),

-- Rob Pike & Brian Kernighan (139–152)
(gen_random_uuid(), 'Rule 1: You can''t tell where a program is going to spend its time. Bottlenecks surprise you.', 'Rob Pike', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'Fancy algorithms are slow when N is small, and N is usually small.', 'Rob Pike', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'Data dominates. If you have chosen the right data structures and organized things well, the algorithms are self-evident.', 'Rob Pike', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'Concurrency is not parallelism. Concurrency is the composition of independently executing processes.', 'Rob Pike', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','learning'], true, 'coding'),
(gen_random_uuid(), 'Don''t communicate by sharing memory; share memory by communicating.', 'Rob Pike', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'Simplicity is the prerequisite for reliability.', 'Rob Pike', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'Good programs are programs that are simple to understand and therefore correct.', 'Brian Kernighan', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'Debugging is twice as hard as writing the code in the first place. Therefore, if you write the code as cleverly as possible, you are, by definition, not smart enough to debug it.', 'Brian Kernighan', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'Everyone knows that debugging is twice as hard as writing a program in the first place.', 'Brian Kernighan', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'The most effective debugging tool is still careful thought, coupled with judiciously placed print statements.', 'Brian Kernighan', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'Controlling complexity is the essence of computer programming.', 'Brian Kernighan', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'Write clearly: don''t sacrifice clarity for small gains in efficiency.', 'Brian Kernighan', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'Let your data be the boss. The structure of your data shapes the structure of your code.', 'Rob Pike', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'When in doubt, enumerate explicitly. Implicit assumptions are where bugs live.', 'Brian Kernighan', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),

-- Eric Raymond (153–162)
(gen_random_uuid(), 'Every good work of software starts by scratching a developer''s personal itch.', 'Eric Raymond', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['passion','wisdom'], true, 'coding'),
(gen_random_uuid(), 'Release early, release often, and listen to your customers.', 'Eric Raymond', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','focus'], true, 'coding'),
(gen_random_uuid(), 'Good open source is not about giving code away. It is about building a community around a shared problem.', 'Eric Raymond', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'The cathedral model builds quality through centralized control. The bazaar builds it through distributed review.', 'Eric Raymond', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','learning'], true, 'coding'),
(gen_random_uuid(), 'Smart questions get smart answers. The way you frame your question determines the quality of the help you receive.', 'Eric Raymond', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','learning'], true, 'coding'),
(gen_random_uuid(), 'Hacker culture values competence over credentials. Show your work and let it speak for itself.', 'Eric Raymond', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'The right tool for the job is usually the simplest one that actually solves the problem.', 'Eric Raymond', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'Transparency in development is not just a moral value. It is a practical advantage.', 'Eric Raymond', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'Open source works because code does not lie. The behavior is in the binary, not in the marketing.', 'Eric Raymond', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'Reputation in the hacker community is built by shipping working code, not by talking about it.', 'Eric Raymond', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','wisdom'], true, 'coding'),

-- Mitchell Hashimoto (163–174)
(gen_random_uuid(), 'Infrastructure as code is not about automating what you do manually. It is about expressing intent.', 'Mitchell Hashimoto', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'Terraform''s power is in its state. Understanding state is understanding Terraform.', 'Mitchell Hashimoto', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'Idempotent infrastructure means you can apply it a hundred times and get the same result.', 'Mitchell Hashimoto', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'Secrets management is the hardest part of infrastructure automation. Treat it as a first-class problem.', 'Mitchell Hashimoto', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'Vagrant was built because environment parity was the hidden cost destroying developer productivity.', 'Mitchell Hashimoto', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'Good tools create habits. Bad tools create workarounds. Design your tools with the desired behavior in mind.', 'Mitchell Hashimoto', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'Multi-cloud is not a goal. Vendor independence is. Know the difference before you architect.', 'Mitchell Hashimoto', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'Open source sustainability requires more than great code. It requires community, governance, and trust.', 'Mitchell Hashimoto', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'Zero-downtime deployments are possible with the right abstractions at every layer of the stack.', 'Mitchell Hashimoto', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'Configuration drift is the silent killer of infrastructure reliability.', 'Mitchell Hashimoto', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'Plan before you apply. The Terraform plan output is your change contract.', 'Mitchell Hashimoto', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','focus'], true, 'coding'),
(gen_random_uuid(), 'Modules are how you encode institutional knowledge about infrastructure patterns.', 'Mitchell Hashimoto', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),

-- Solomon Hykes (175–184)
(gen_random_uuid(), 'Docker was built on the insight that shipping the environment with the code solves the ''works on my machine'' problem.', 'Solomon Hykes', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'Containers are not virtual machines. Understanding the difference is the first step to using them correctly.', 'Solomon Hykes', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','learning'], true, 'coding'),
(gen_random_uuid(), 'Portability means your application behaves the same wherever it runs. That is a promise, not a feature.', 'Solomon Hykes', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'The best developer experience is one where the developer does not have to think about infrastructure.', 'Solomon Hykes', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','focus'], true, 'coding'),
(gen_random_uuid(), 'Open standards in containerization mean no single vendor owns the runtime layer of your stack.', 'Solomon Hykes', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'Layered images are a lesson in caching: structure your Dockerfile so the stable layers come first.', 'Solomon Hykes', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'The Dockerfile is the recipe for your environment. Version it, review it, test it like any other code.', 'Solomon Hykes', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','focus'], true, 'coding'),
(gen_random_uuid(), 'Build once, run anywhere was not a new idea. Docker made it true for the first time at scale.', 'Solomon Hykes', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'The ecosystem around a tool is as important as the tool itself. Open source creates network effects.', 'Solomon Hykes', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','learning'], true, 'coding'),
(gen_random_uuid(), 'Isolation without portability is a jail. Portability without isolation is chaos. You need both.', 'Solomon Hykes', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),

-- Adrian Cockcroft (185–196)
(gen_random_uuid(), 'Cloud native is about more than technology. It is a new way of thinking about operational responsibility.', 'Adrian Cockcroft', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'Microservices at Netflix were not planned. They emerged from the need to deploy independently.', 'Adrian Cockcroft', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','learning'], true, 'coding'),
(gen_random_uuid(), 'Chaos engineering means you inject failure before failure injects itself on you.', 'Adrian Cockcroft', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','courage'], true, 'coding'),
(gen_random_uuid(), 'The hardest part of scaling is not the technology. It is the organizational change that enables the technology.', 'Adrian Cockcroft', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'Speed of deployment is the metric that forces everything else to be disciplined.', 'Adrian Cockcroft', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','focus'], true, 'coding'),
(gen_random_uuid(), 'Loosely coupled teams build loosely coupled architectures. Conway''s Law is not a metaphor.', 'Adrian Cockcroft', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'Service discovery is the infrastructure problem that microservices create and that you cannot ignore.', 'Adrian Cockcroft', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'Resilience patterns like circuit breakers are not features. They are survival mechanisms.', 'Adrian Cockcroft', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'Auto-scaling is not magic. It is policy expressed as code, and policy can be wrong.', 'Adrian Cockcroft', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'Serverless removes the server from the developer''s concern, not from the world.', 'Adrian Cockcroft', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','learning'], true, 'coding'),
(gen_random_uuid(), 'Platform teams exist to absorb complexity so product teams can move fast.', 'Adrian Cockcroft', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'Observability is the property of a system that tells you how well you understand it.', 'Adrian Cockcroft', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),

-- Richard Stallman & Larry Wall (197–206)
(gen_random_uuid(), 'Free software is a matter of liberty, not price. Think of free as in free speech, not free beer.', 'Richard Stallman', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['courage','wisdom'], true, 'coding'),
(gen_random_uuid(), 'Proprietary software keeps users divided and helpless. Free software lets them cooperate and control their computing.', 'Richard Stallman', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','courage'], true, 'coding'),
(gen_random_uuid(), 'The GPL ensures that every user of the software has the same freedom to study, modify, and distribute.', 'Richard Stallman', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'Copyleft is a way of using copyright to ensure software freedom is preserved as code passes between hands.', 'Richard Stallman', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'The three great virtues of a programmer are laziness, impatience, and hubris.', 'Larry Wall', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'Easy things should be easy, and hard things should be possible.', 'Larry Wall', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'Real laziness means writing a tool to do repetitive work so you never have to do it manually again.', 'Larry Wall', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'There is more than one way to do it. The right way depends on the context.', 'Larry Wall', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'Scripting languages exist because not every problem deserves a compiled solution.', 'Larry Wall', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'The computer should be doing the hard work. That is what it is paid to do.', 'Larry Wall', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','wisdom'], true, 'coding'),

-- Guido van Rossum (207–216)
(gen_random_uuid(), 'Python''s readability is not an accident. It was a deliberate design principle from the beginning.', 'Guido van Rossum', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'There should be one — and preferably only one — obvious way to do it.', 'Guido van Rossum', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'Explicit is better than implicit. Readability is not an afterthought; it is the point.', 'Guido van Rossum', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'Code is read far more often than it is written. Design for the reader, not the writer.', 'Guido van Rossum', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'Automation scripts written in Python are as maintainable as any application code, if you treat them that way.', 'Guido van Rossum', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','focus'], true, 'coding'),
(gen_random_uuid(), 'The battery-included philosophy means you should not reinvent wheels for common operational tasks.', 'Guido van Rossum', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'Errors should never pass silently. Unless explicitly silenced. This is the right stance for operational code.', 'Guido van Rossum', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'In the face of ambiguity, refuse the temptation to guess. Programs should fail clearly, not silently.', 'Guido van Rossum', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'Now is better than never. Although never is often better than right now. Ship with quality.', 'Guido van Rossum', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','focus'], true, 'coding'),
(gen_random_uuid(), 'If the implementation is hard to explain, it is a bad idea. Complexity is not sophistication.', 'Guido van Rossum', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),

-- James Hamilton, Pat Helland, Jeff Dean (217–232)
(gen_random_uuid(), 'At scale, hardware failures are not edge cases. They are the normal operating condition.', 'James Hamilton', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'Predictable performance is more valuable than peak performance. Tail latencies kill user experience.', 'James Hamilton', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'Power efficiency at scale is not just a cost concern. It is an engineering discipline.', 'James Hamilton', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'Network topology is destiny in large-scale distributed systems. Design around it, not against it.', 'James Hamilton', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'Hyperscale requires that every architectural decision be justifiable at a million times the current load.', 'James Hamilton', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'Life beyond distributed transactions is possible. Embrace eventual consistency where strong consistency is too expensive.', 'Pat Helland', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'Immutable data is the foundation of append-only systems, event sourcing, and audit trails.', 'Pat Helland', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'Data on the outside is the shared reality that services communicate through. Design it carefully.', 'Pat Helland', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'Idempotence and commutativity in distributed operations are not academic properties. They are survival traits.', 'Pat Helland', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'At Google scale, the bottleneck is never where you first think it is. Profile before you optimize.', 'Jeff Dean', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'MapReduce made distributed computation accessible by hiding the complexity of fault tolerance.', 'Jeff Dean', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','learning'], true, 'coding'),
(gen_random_uuid(), 'The numbers everyone should know: L1 cache 0.5ns, memory 100ns, disk 10ms, cross-datacenter 150ms.', 'Jeff Dean', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','learning'], true, 'coding'),
(gen_random_uuid(), 'Bigtable showed that a simple data model consistently applied can out-perform a complex one inconsistently applied.', 'Jeff Dean', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'Checkpointing lets you restart expensive computations from the last safe state, not from zero.', 'Jeff Dean', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'Sharding distributes both load and failure. Design your shard key so that load and failure are distributed evenly.', 'Jeff Dean', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'Spanner proved that external consistency at global scale is achievable if you are willing to invest in the clock.', 'Jeff Dean', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','learning'], true, 'coding'),

-- General DevOps & SRE principles (233–250)
(gen_random_uuid(), 'An SLO is a promise to your users expressed as a number. Break it and you break trust.', 'SRE Practice', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'Error budgets turn reliability into a negotiation between velocity and stability.', 'SRE Practice', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'Toil is repetitive, automatable, tactical work with no enduring value. Eliminate it deliberately.', 'SRE Practice', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','focus'], true, 'coding'),
(gen_random_uuid(), 'The first rule of on-call is: if you are paged for something that could have been automated, automate it.', 'SRE Practice', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'Runbooks are operational memory. Keep them current or they become worse than useless.', 'SRE Practice', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'A good git commit message answers why, not what. The diff already shows what.', 'Git Practice', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'Rebase for clean history before merging. The future maintainer will thank you.', 'Git Practice', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','focus'], true, 'coding'),
(gen_random_uuid(), 'git bisect is the most underused debugging tool in every developer''s arsenal.', 'Git Practice', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'Branches are cheap in git. Use them freely. Merge them promptly.', 'Git Practice', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','focus'], true, 'coding'),
(gen_random_uuid(), 'Never force-push to main. The history you rewrite may be the history someone else is building on.', 'Git Practice', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'Shell scripts are infrastructure. They deserve version control, error handling, and tests.', 'Linux Practice', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'Set -euo pipefail at the top of every shell script. Fail fast and fail loudly.', 'Linux Practice', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','focus'], true, 'coding'),
(gen_random_uuid(), 'The /proc filesystem is the kernel speaking to you in real time. Learn to read it.', 'Linux Practice', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','learning'], true, 'coding'),
(gen_random_uuid(), 'cgroups and namespaces are the Linux primitives that make containers possible. Know your foundations.', 'Linux Practice', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','learning'], true, 'coding'),
(gen_random_uuid(), 'Every log line is a gift from your past self to your future self during an incident.', 'Observability Practice', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'Structured logging is not about format. It is about making your logs queryable at 3am when things are broken.', 'Observability Practice', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'The four golden signals are latency, traffic, errors, and saturation. Monitor these before anything else.', 'Observability Practice', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'A metric without context is trivia. A metric with historical baseline and alert threshold is operational intelligence.', 'Observability Practice', 'philosophy', 'en', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding')

ON CONFLICT (text, author) DO NOTHING;

COMMIT;
