-- 038_science_physics_es.sql
-- MindScrolling — Science Mode: Physics ES (250 quotes)
-- Topics: mecánica cuántica, relatividad, termodinámica, electromagnetismo,
--         física de partículas, cosmología, astrofísica, agujeros negros,
--         materia oscura, entropía, gravedad, física nuclear, teoría de cuerdas,
--         espacio-tiempo
--
-- All rows:
--   category       = 'philosophy'
--   lang           = 'es'
--   swipe_dir      = 'down'
--   pack_name      = 'free'
--   is_premium     = false
--   content_type   = 'science'
--   sub_category   = 'physics'
--   is_hidden_mode = true
--   locked_by      = 'science'
-- Run in Supabase SQL Editor

BEGIN;

-- ══════════════════════════════════════════════════════════════════════════════
-- PHYSICS — SPANISH (250 quotes)
-- ══════════════════════════════════════════════════════════════════════════════

INSERT INTO quotes (id, text, author, category, lang, swipe_dir, pack_name, is_premium, content_type, sub_category, tags, is_hidden_mode, locked_by) VALUES

-- Albert Einstein (1–22)
(gen_random_uuid(), 'El tiempo es relativo: depende de dónde estés y a qué velocidad te muevas respecto a otro observador.', 'Albert Einstein', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'La relatividad nos enseña que el espacio y el tiempo son una sola tela que la materia curva a su alrededor.', 'Albert Einstein', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['curiosity', 'learning', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'La energía y la masa son dos caras de la misma moneda; esa equivalencia cambió nuestra visión del universo.', 'Albert Einstein', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['learning', 'curiosity', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'La gravedad no es una fuerza; es la curvatura del espacio-tiempo provocada por la presencia de masa.', 'Albert Einstein', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'Lo más incomprensible del universo es precisamente que podamos comprenderlo con ecuaciones.', 'Albert Einstein', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['wisdom', 'curiosity', 'learning'], true, 'science'),
(gen_random_uuid(), 'Un campo unificado que describa gravedad y electromagnetismo sería la sinfonía final de la física.', 'Albert Einstein', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['curiosity', 'learning', 'creativity'], true, 'science'),
(gen_random_uuid(), 'El universo no juega a los dados, pero la mecánica cuántica insiste en que sí lo hace.', 'Albert Einstein', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'Nada puede viajar más rápido que la luz en el vacío; ese límite es absoluto e irrompible.', 'Albert Einstein', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['learning', 'curiosity', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'La dilatación del tiempo no es una ilusión; los relojes atómicos en órbita lo confirman con precisión.', 'Albert Einstein', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'La contracción de la longitud a velocidades relativistas es tan real como cualquier otro fenómeno físico.', 'Albert Einstein', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['learning', 'curiosity', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'El efecto fotoeléctrico mostró que la luz viaja en paquetes discretos de energía llamados fotones.', 'Albert Einstein', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['curiosity', 'learning', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'El espacio sin materia es impensable; la materia sin espacio-tiempo tampoco tiene sentido.', 'Albert Einstein', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['wisdom', 'curiosity', 'learning'], true, 'science'),
(gen_random_uuid(), 'Las ondas gravitacionales son riples en el tejido del espacio-tiempo, predichas antes de ser detectadas.', 'Albert Einstein', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'La física teórica es el arte de construir modelos matemáticos que describen la realidad con elegancia.', 'Albert Einstein', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['creativity', 'learning', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'La simultaneidad es relativa: dos eventos simultáneos para un observador no lo son para otro en movimiento.', 'Albert Einstein', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['curiosity', 'learning', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'El universo tiene un pasado finito; la idea de que siempre existió no es sostenible físicamente.', 'Albert Einstein', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'La física nos revela que el tiempo fluye diferente según la intensidad del campo gravitacional local.', 'Albert Einstein', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['curiosity', 'learning', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'La intuición matemática más profunda a menudo anticipa los experimentos por décadas.', 'Albert Einstein', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['creativity', 'curiosity', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'El principio de equivalencia afirma que la aceleración y la gravedad son físicamente indistinguibles.', 'Albert Einstein', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['learning', 'curiosity', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'La cosmología relativista predice un universo dinámico, no estático, que se expande o contrae.', 'Albert Einstein', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'Cada fórmula física condensa siglos de observación en unas pocas letras y símbolos esenciales.', 'Albert Einstein', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['wisdom', 'learning', 'creativity'], true, 'science'),
(gen_random_uuid(), 'La física no describe el universo tal como es; describe el universo tal como podemos medirlo.', 'Albert Einstein', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['wisdom', 'curiosity', 'learning'], true, 'science'),

-- Richard Feynman (23–44)
(gen_random_uuid(), 'Si crees que entiendes la mecánica cuántica, es que no la has entendido del todo.', 'Richard Feynman', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'La naturaleza usa solo los hilos más largos para tejer sus patrones, y cada trozo revela la tela entera.', 'Richard Feynman', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'El placer de descubrir cosas nuevas es la recompensa más grande que ofrece la física.', 'Richard Feynman', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['curiosity', 'learning', 'self_improvement'], true, 'science'),
(gen_random_uuid(), 'Las partículas subatómicas no tienen trayectorias definidas; toman todos los caminos posibles a la vez.', 'Richard Feynman', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['curiosity', 'learning', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'El electrón no es una bola de billar; es una entidad cuántica sin análogo en el mundo cotidiano.', 'Richard Feynman', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'La electrodinámica cuántica predice el momento magnético del electrón con una precisión asombrosa.', 'Richard Feynman', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['learning', 'curiosity', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'La ciencia es la creencia en la ignorancia de los expertos; cuestionar es su método esencial.', 'Richard Feynman', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'El universo no está obligado a ser comprensible para nosotros, pero resulta que sí lo es.', 'Richard Feynman', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'Las integrales de camino suman todas las historias posibles de una partícula para obtener su comportamiento.', 'Richard Feynman', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['learning', 'curiosity', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'La física teórica avanza cuando alguien se atreve a imaginar algo que contradice la intuición común.', 'Richard Feynman', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['creativity', 'curiosity', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'Un diagrama de Feynman no es solo un dibujo; es una receta exacta para calcular probabilidades cuánticas.', 'Richard Feynman', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['learning', 'curiosity', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'La incertidumbre cuántica no es ignorancia; es una propiedad fundamental de la naturaleza misma.', 'Richard Feynman', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'Los físicos no hacemos el universo; simplemente intentamos leer las reglas con las que ya viene escrito.', 'Richard Feynman', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['wisdom', 'curiosity', 'learning'], true, 'science'),
(gen_random_uuid(), 'La superposición cuántica permite que un sistema exista en múltiples estados hasta que se mide.', 'Richard Feynman', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['curiosity', 'learning', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'La física de partículas revela que la materia ordinaria es casi todo espacio vacío con fuerzas.', 'Richard Feynman', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'El entrelazamiento cuántico conecta partículas separadas de manera que Einstein llamó acción fantasmal.', 'Richard Feynman', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['curiosity', 'learning', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'La renormalización es una técnica matemática extraña, pero funciona, y eso es lo que importa en física.', 'Richard Feynman', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['learning', 'curiosity', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'Cuando un experimento contradice una teoría, la teoría pierde sin importar quién la formuló.', 'Richard Feynman', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['wisdom', 'learning', 'curiosity'], true, 'science'),
(gen_random_uuid(), 'La física es como el sexo: a veces produce algo útil, pero esa no es la razón por la que la hacemos.', 'Richard Feynman', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'Las leyes de la física son las mismas en cualquier rincón del universo observable.', 'Richard Feynman', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'El universo es tan extraño que incluso nuestros mejores modelos son solo aproximaciones útiles.', 'Richard Feynman', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['wisdom', 'curiosity', 'learning'], true, 'science'),
(gen_random_uuid(), 'Estudiar física es aprender a maravillarse con rigor, sin perder la capacidad de asombro.', 'Richard Feynman', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['curiosity', 'learning', 'self_improvement'], true, 'science'),

-- Stephen Hawking (45–63)
(gen_random_uuid(), 'Un agujero negro no es tan negro como lo pintan; emite radiación térmica de manera muy lenta.', 'Stephen Hawking', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'El universo comenzó en una singularidad de densidad y temperatura infinitas hace unos trece mil millones de años.', 'Stephen Hawking', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['curiosity', 'learning', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'El tiempo imaginario es una dimensión matemática que permite eliminar la singularidad del Big Bang.', 'Stephen Hawking', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'La radiación de Hawking implica que los agujeros negros eventualmente se evaporan con el tiempo.', 'Stephen Hawking', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['learning', 'curiosity', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'La entropía de un agujero negro es proporcional al área de su horizonte de eventos, no a su volumen.', 'Stephen Hawking', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'El universo no tiene bordes en el tiempo; la condición de no frontera lo hace completo en sí mismo.', 'Stephen Hawking', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['curiosity', 'learning', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'La teoría M podría ser la teoría del todo que unifica las cinco versiones de la teoría de cuerdas.', 'Stephen Hawking', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['learning', 'curiosity', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'La gravedad cuántica es el Santo Grial de la física moderna: unir relatividad y mecánica cuántica.', 'Stephen Hawking', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'Mientras haya vida, habrá esperanza de entender por qué el universo existe en lugar de nada.', 'Stephen Hawking', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'El universo no necesitó un creador externo; las leyes de la física son suficientes para explicar su origen.', 'Stephen Hawking', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['wisdom', 'curiosity', 'learning'], true, 'science'),
(gen_random_uuid(), 'La singularidad desnuda, sin horizonte de eventos, violaría la censura cósmica de Penrose.', 'Stephen Hawking', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['learning', 'curiosity', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'Colonizar otros planetas es el seguro de vida de la humanidad frente a los peligros cósmicos.', 'Stephen Hawking', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['curiosity', 'wisdom', 'self_improvement'], true, 'science'),
(gen_random_uuid(), 'La física cuántica de campo en espacio-tiempo curvo produce efectos como la creación de partículas.', 'Stephen Hawking', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['curiosity', 'learning', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'Las estrellas de neutrones son laboratorios naturales donde la materia alcanza densidades nucleares extremas.', 'Stephen Hawking', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'Un universo con constante cosmológica positiva se expande aceleradamente hacia un futuro frío.', 'Stephen Hawking', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['curiosity', 'learning', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'La información no puede destruirse; incluso en un agujero negro debe preservarse de alguna forma.', 'Stephen Hawking', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['wisdom', 'curiosity', 'learning'], true, 'science'),
(gen_random_uuid(), 'Comprender el universo es el mayor logro de la mente humana, más allá de cualquier conquista material.', 'Stephen Hawking', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['wisdom', 'curiosity', 'learning'], true, 'science'),
(gen_random_uuid(), 'La cosmología cuántica estudia el universo entero como un sistema regido por las leyes de lo muy pequeño.', 'Stephen Hawking', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['curiosity', 'learning', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'La flecha del tiempo apunta hacia donde la entropía aumenta; esa es la razón por la que recordamos el pasado.', 'Stephen Hawking', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),

-- Niels Bohr (64–79)
(gen_random_uuid(), 'Todo lo que llamamos real está hecho de cosas que no podemos considerar reales en el sentido clásico.', 'Niels Bohr', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'En física cuántica, la observación no es pasiva; el acto de medir altera aquello que se mide.', 'Niels Bohr', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['curiosity', 'learning', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'El principio de complementariedad afirma que onda y partícula son descripciones mutuamente excluyentes.', 'Niels Bohr', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'Un átomo en reposo no es algo que la mecánica cuántica pueda describir con coordenadas precisas.', 'Niels Bohr', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['learning', 'curiosity', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'La correspondencia entre mecánica clásica y cuántica se recupera en el límite de números cuánticos altos.', 'Niels Bohr', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['learning', 'wisdom', 'curiosity'], true, 'science'),
(gen_random_uuid(), 'El colapso de la función de onda al medir es uno de los misterios más profundos de la física.', 'Niels Bohr', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'Los niveles de energía discretos del átomo de hidrógeno fueron la primera huella de lo cuántico.', 'Niels Bohr', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['curiosity', 'learning', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'La realidad cuántica no existe independientemente del instrumento que usamos para observarla.', 'Niels Bohr', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['wisdom', 'curiosity', 'learning'], true, 'science'),
(gen_random_uuid(), 'La dualidad onda-partícula no es una contradicción; es una característica fundamental de la naturaleza.', 'Niels Bohr', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'La interpretación de Copenhague sitúa al observador en el corazón mismo de la descripción cuántica.', 'Niels Bohr', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['learning', 'curiosity', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'La física cuántica obliga a revisar conceptos filosóficos como causalidad, realidad y conocimiento.', 'Niels Bohr', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['wisdom', 'curiosity', 'learning'], true, 'science'),
(gen_random_uuid(), 'Los fotones individuales producen un patrón de interferencia estadístico que revela su naturaleza ondulatoria.', 'Niels Bohr', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['curiosity', 'learning', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'La mecánica cuántica es una teoría completa, aunque su interpretación filosófica sigue debatiéndose.', 'Niels Bohr', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['learning', 'wisdom', 'curiosity'], true, 'science'),
(gen_random_uuid(), 'Sin la extrañeza cuántica no habría transistores, láseres ni ninguna de las tecnologías modernas.', 'Niels Bohr', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'La física cuántica revela que la certeza absoluta es imposible a nivel subatómico por principio.', 'Niels Bohr', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['wisdom', 'curiosity', 'learning'], true, 'science'),
(gen_random_uuid(), 'Preguntarse qué es el electrón entre mediciones no tiene respuesta física válida según la teoría cuántica.', 'Niels Bohr', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),

-- Werner Heisenberg (80–92)
(gen_random_uuid(), 'El principio de incertidumbre no es un límite tecnológico; es una ley fundamental de la naturaleza.', 'Werner Heisenberg', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['wisdom', 'curiosity', 'learning'], true, 'science'),
(gen_random_uuid(), 'Cuanto más precisamente conocemos la posición de un electrón, menos sabemos de su momento y viceversa.', 'Werner Heisenberg', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['curiosity', 'learning', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'La mecánica de matrices fue la primera formulación matemática rigurosa de la mecánica cuántica.', 'Werner Heisenberg', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['learning', 'curiosity', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'La física cuántica disuelve la idea de una trayectoria objetiva del electrón; solo quedan probabilidades.', 'Werner Heisenberg', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'Las fluctuaciones cuánticas del vacío crean y destruyen pares de partículas sin violar la energía.', 'Werner Heisenberg', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['curiosity', 'learning', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'La naturaleza nos prohíbe conocer simultáneamente todos los atributos de un sistema cuántico.', 'Werner Heisenberg', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['wisdom', 'curiosity', 'learning'], true, 'science'),
(gen_random_uuid(), 'El observador no puede separarse del sistema observado en la mecánica cuántica; ambos interactúan.', 'Werner Heisenberg', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'La física atómica obliga a reconocer que la realidad no es lo que percibimos con los sentidos.', 'Werner Heisenberg', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['wisdom', 'curiosity', 'learning'], true, 'science'),
(gen_random_uuid(), 'Las relaciones de conmutación entre posición y momento son el corazón algebraico de la cuántica.', 'Werner Heisenberg', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['learning', 'curiosity', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'La física cuántica surgió de la necesidad de explicar el espectro del cuerpo negro sin divergencias.', 'Werner Heisenberg', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['curiosity', 'learning', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'El concepto clásico de trayectoria carece de significado en el mundo subatómico cuántico.', 'Werner Heisenberg', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'La incertidumbre energía-tiempo permite fluctuaciones breves que alimentan procesos virtuales cuánticos.', 'Werner Heisenberg', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['curiosity', 'learning', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'El avance de la física exige estar dispuesto a abandonar conceptos que parecían absolutos y eternos.', 'Werner Heisenberg', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['wisdom', 'curiosity', 'self_improvement'], true, 'science'),

-- Isaac Newton (93–107)
(gen_random_uuid(), 'La fuerza que atrae una manzana al suelo es la misma que mantiene la Luna en su órbita.', 'Isaac Newton', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'La gravedad universal actúa a distancia de forma instantánea, algo que a mí mismo me inquietaba.', 'Isaac Newton', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['curiosity', 'learning', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'La segunda ley del movimiento relaciona la fuerza con el cambio de cantidad de movimiento por unidad de tiempo.', 'Isaac Newton', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['learning', 'curiosity', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'A toda acción le corresponde una reacción igual y opuesta; esa es la base de la mecánica clásica.', 'Isaac Newton', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['wisdom', 'learning', 'curiosity'], true, 'science'),
(gen_random_uuid(), 'La luz blanca es una mezcla de todos los colores del espectro; el prisma los separa según su refracción.', 'Isaac Newton', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['curiosity', 'learning', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'El cálculo infinitesimal fue la herramienta matemática que necesitaba la física para progresar.', 'Isaac Newton', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['learning', 'creativity', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'Si he visto más lejos, es porque me he apoyado en hombros de gigantes del conocimiento previo.', 'Isaac Newton', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['wisdom', 'learning', 'self_improvement'], true, 'science'),
(gen_random_uuid(), 'La inercia mantiene un cuerpo en reposo o en movimiento rectilíneo uniforme salvo fuerza externa.', 'Isaac Newton', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['learning', 'curiosity', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'El espacio absoluto newtoniano es el escenario fijo en el que se desarrolla el drama del universo.', 'Isaac Newton', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'Las mareas oceánicas son el resultado de la diferencia en la atracción gravitacional de la Luna.', 'Isaac Newton', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['curiosity', 'learning', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'La órbita elíptica de los planetas se deduce directamente de la ley del inverso del cuadrado.', 'Isaac Newton', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['learning', 'curiosity', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'La física newtoniana domina a escalas cotidianas; solo falla en lo muy rápido, pequeño o masivo.', 'Isaac Newton', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['wisdom', 'curiosity', 'learning'], true, 'science'),
(gen_random_uuid(), 'La constante de gravitación universal G es tan pequeña que solo planetas la hacen perceptible.', 'Isaac Newton', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['curiosity', 'learning', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'Para cada problema hay una solución; la matemática es el lenguaje en que la naturaleza la escribe.', 'Isaac Newton', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['learning', 'wisdom', 'creativity'], true, 'science'),
(gen_random_uuid(), 'Me considero un niño que juega en la orilla, y el océano de la verdad se extiende ante mí sin explorar.', 'Isaac Newton', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['curiosity', 'wisdom', 'self_improvement'], true, 'science'),

-- Max Planck (108–119)
(gen_random_uuid(), 'La energía no fluye de forma continua; se emite y absorbe en paquetes discretos llamados cuantos.', 'Max Planck', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['curiosity', 'learning', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'La constante de Planck es tan pequeña que sus efectos solo se notan a escalas subatómicas.', 'Max Planck', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['learning', 'curiosity', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'El espectro del cuerpo negro fue el primer problema que exigió una explicación cuántica de la radiación.', 'Max Planck', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'La termodinámica estadística conecta el comportamiento microscópico con las propiedades macroscópicas.', 'Max Planck', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['learning', 'curiosity', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'La acción es la cantidad física central que la mecánica cuántica cuantiza en unidades de h-barra.', 'Max Planck', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['curiosity', 'learning', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'Una nueva verdad científica no triunfa convenciendo a sus oponentes, sino porque ellos mueren.', 'Max Planck', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['wisdom', 'curiosity', 'learning'], true, 'science'),
(gen_random_uuid(), 'La revolución cuántica no fue planeada; surgió de la necesidad de resolver una ecuación inconveniente.', 'Max Planck', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'La temperatura absoluta cero es el estado de mínima energía posible, nunca alcanzable completamente.', 'Max Planck', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['learning', 'curiosity', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'La física avanza cuando alguien tiene el coraje de tomar en serio una idea matemáticamente necesaria.', 'Max Planck', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['curiosity', 'self_improvement', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'El segundo principio de la termodinámica es una ley estadística, no absoluta, pero su violación es infinitamente improbable.', 'Max Planck', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['learning', 'wisdom', 'curiosity'], true, 'science'),
(gen_random_uuid(), 'La radiación no es solo una onda continua; tiene una estructura granular que el experimento confirmó.', 'Max Planck', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['curiosity', 'learning', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'El físico debe ser fiel a los datos experimentales aunque contradigan sus convicciones teóricas previas.', 'Max Planck', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['wisdom', 'learning', 'self_improvement'], true, 'science'),

-- Erwin Schrödinger (120–131)
(gen_random_uuid(), 'La función de onda no describe la partícula; describe nuestro conocimiento probabilístico de ella.', 'Erwin Schrödinger', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'Un gato puede estar vivo y muerto simultáneamente según la mecánica cuántica hasta ser observado.', 'Erwin Schrödinger', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['curiosity', 'learning', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'La ecuación de onda proporciona la herramienta matemática para predecir la evolución de sistemas cuánticos.', 'Erwin Schrödinger', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['learning', 'curiosity', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'La materia viva evita el equilibrio termodinámico alimentándose de entropía negativa del entorno.', 'Erwin Schrödinger', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'La mecánica ondulatoria y la mecánica de matrices son matemáticamente equivalentes aunque conceptualmente distintas.', 'Erwin Schrödinger', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['learning', 'curiosity', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'El entrelazamiento cuántico es la característica más peculiar de la mecánica cuántica, no solo una rareza.', 'Erwin Schrödinger', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['curiosity', 'learning', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'La conciencia no puede separarse de la física; tal vez sea la mecánica cuántica quien la explique.', 'Erwin Schrödinger', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['wisdom', 'curiosity', 'learning'], true, 'science'),
(gen_random_uuid(), 'Los orbitales atómicos son soluciones de la ecuación de onda con condiciones de frontera definidas.', 'Erwin Schrödinger', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['learning', 'curiosity', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'La física cuántica predice con exactitud los espectros atómicos que el ojo humano no puede resolver.', 'Erwin Schrödinger', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'La idea de continuidad en la naturaleza es una aproximación; a escala cuántica todo es discreto.', 'Erwin Schrödinger', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['curiosity', 'learning', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'El problema de la medición cuántica divide a los físicos hoy tanto como dividió a Bohr y Einstein.', 'Erwin Schrödinger', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['wisdom', 'curiosity', 'learning'], true, 'science'),
(gen_random_uuid(), 'La biofísica cuántica podría revelar que la vida explota efectos de coherencia para procesos vitales.', 'Erwin Schrödinger', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['curiosity', 'learning', 'wisdom'], true, 'science'),

-- Paul Dirac (132–141)
(gen_random_uuid(), 'La ecuación relativista del electrón predijo la existencia del positrón antes de que fuera descubierto.', 'Paul Dirac', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['curiosity', 'learning', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'La belleza matemática es una guía más fiable hacia la verdad física que cualquier intuición experimental.', 'Paul Dirac', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['creativity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'La antimateria existe porque las ecuaciones relativistas cuánticas admiten soluciones de energía negativa.', 'Paul Dirac', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'La transformación canónica es el puente entre la mecánica clásica y la cuántica en su formulación algebraica.', 'Paul Dirac', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['learning', 'curiosity', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'El mar de Dirac conceptualizó el vacío cuántico como un mar lleno de electrones de energía negativa.', 'Paul Dirac', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'La estadística de Fermi-Dirac gobierna el comportamiento de partículas con espín semientero como los electrones.', 'Paul Dirac', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['learning', 'curiosity', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'El lagrangiano y el hamiltoniano son dos lenguajes igualmente válidos para describir la dinámica física.', 'Paul Dirac', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['learning', 'wisdom', 'curiosity'], true, 'science'),
(gen_random_uuid(), 'La simetría CPT es una ley fundamental que ningún proceso físico conocido viola.', 'Paul Dirac', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'Una teoría física elegante tiende a ser más verdadera que una que se ajusta a los datos con torpeza.', 'Paul Dirac', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['wisdom', 'creativity', 'learning'], true, 'science'),
(gen_random_uuid(), 'La notación bra-ket de Dirac es el lenguaje universal de la mecánica cuántica en su forma abstracta.', 'Paul Dirac', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['learning', 'curiosity', 'wisdom'], true, 'science'),

-- Nikola Tesla (142–152)
(gen_random_uuid(), 'La corriente alterna es más eficiente que la continua para transportar electricidad a grandes distancias.', 'Nikola Tesla', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['curiosity', 'learning', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'El campo electromagnético rotante fue la intuición que hizo posible el motor de inducción moderno.', 'Nikola Tesla', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['creativity', 'curiosity', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'La resonancia electromagnética puede transferir energía sin cables entre un emisor y un receptor sintonizado.', 'Nikola Tesla', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['curiosity', 'learning', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'La Tierra entera puede funcionar como un conductor resonante para transmitir señales eléctricas globalmente.', 'Nikola Tesla', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'El transformador permite cambiar tensiones con pérdidas mínimas gracias a la inducción electromagnética.', 'Nikola Tesla', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['learning', 'curiosity', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'La electrónica moderna depende de la comprensión profunda del electromagnetismo que Maxwell formuló.', 'Nikola Tesla', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['learning', 'wisdom', 'curiosity'], true, 'science'),
(gen_random_uuid(), 'La frecuencia es la clave para entender la naturaleza; todo vibra a su propia resonancia característica.', 'Nikola Tesla', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'La bobina de Tesla demuestra que altas frecuencias y altas tensiones permiten efectos electromagnéticos extremos.', 'Nikola Tesla', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['curiosity', 'learning', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'El presente es suyo; el futuro por el que trabajo es mío, gracias a la electricidad que liberaré.', 'Nikola Tesla', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['self_improvement', 'discipline', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'Un inventor no trabaja para el dinero; trabaja para convertir una idea en realidad física tangible.', 'Nikola Tesla', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['discipline', 'curiosity', 'self_improvement'], true, 'science'),
(gen_random_uuid(), 'El plasma es el cuarto estado de la materia y el más abundante en el universo visible.', 'Nikola Tesla', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['curiosity', 'learning', 'wisdom'], true, 'science'),

-- Michael Faraday (153–162)
(gen_random_uuid(), 'Las líneas de fuerza magnética no son solo un recurso visual; representan una realidad física del campo.', 'Michael Faraday', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'La inducción electromagnética demuestra que un campo magnético variable genera una corriente eléctrica.', 'Michael Faraday', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['learning', 'curiosity', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'El concepto de campo fue la mayor contribución de Faraday a la física; Maxwell lo formalizó con ecuaciones.', 'Michael Faraday', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'La ley de electrólisis reveló que la materia tiene una estructura discreta mucho antes de la teoría atómica.', 'Michael Faraday', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['learning', 'curiosity', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'El generador eléctrico convierte energía mecánica en eléctrica mediante la inducción de Faraday.', 'Michael Faraday', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['curiosity', 'learning', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'La rotación de Faraday demostró que la luz y el electromagnetismo están profundamente conectados.', 'Michael Faraday', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'La jaula de Faraday protege su interior de campos eléctricos externos distribuyendo cargas en la superficie.', 'Michael Faraday', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['learning', 'curiosity', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'Un hombre que parte de la nada y llega al campo electromagnético prueba que la curiosidad es el motor del progreso.', 'Michael Faraday', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['curiosity', 'self_improvement', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'La electricidad y el magnetismo son dos aspectos de una sola fuerza unificada por las ecuaciones de Maxwell.', 'Michael Faraday', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['wisdom', 'curiosity', 'learning'], true, 'science'),
(gen_random_uuid(), 'La ley de Lenz establece que la corriente inducida siempre se opone al cambio que la produjo.', 'Michael Faraday', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['learning', 'curiosity', 'wisdom'], true, 'science'),

-- Carl Sagan (163–174)
(gen_random_uuid(), 'Los agujeros negros son regiones donde la gravedad vence a cualquier otra fuerza conocida en la naturaleza.', 'Carl Sagan', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'La expansión del universo significa que galaxias lejanas se alejan a velocidades proporcionales a su distancia.', 'Carl Sagan', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['curiosity', 'learning', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'El fondo cósmico de microondas es el eco del Big Bang, una fotografía de cuando el universo tenía 380.000 años.', 'Carl Sagan', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'La materia oscura es invisible pero su influencia gravitacional moldea la estructura a gran escala del cosmos.', 'Carl Sagan', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['curiosity', 'learning', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'La energía oscura acelera la expansión del universo y constituye la mayor parte de su contenido energético.', 'Carl Sagan', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['learning', 'curiosity', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'Los púlsares son relojes cósmicos de precisión extraordinaria que confirmaron la relatividad general.', 'Carl Sagan', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'Las supernovas forjan los elementos pesados que forman los planetas y los seres vivos del universo.', 'Carl Sagan', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'El principio cosmológico afirma que el universo es homogéneo e isótropo a grandes escalas de distancia.', 'Carl Sagan', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['learning', 'curiosity', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'La escala del cosmos pone en perspectiva nuestra existencia; somos microbios en un universo inconmensurable.', 'Carl Sagan', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['wisdom', 'curiosity', 'learning'], true, 'science'),
(gen_random_uuid(), 'Las lentes gravitacionales doblan la luz de galaxias lejanas, confirmando la relatividad general de Einstein.', 'Carl Sagan', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['curiosity', 'learning', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'El universo tiene una edad, una geometría y una composición que la cosmología ha medido con precisión notable.', 'Carl Sagan', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['learning', 'wisdom', 'curiosity'], true, 'science'),
(gen_random_uuid(), 'Contemplar el cielo nocturno es ver el pasado; la luz de las estrellas viaja miles de años hasta nosotros.', 'Carl Sagan', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),

-- Neil deGrasse Tyson (175–186)
(gen_random_uuid(), 'El universo no tiene obligación de parecernos bello ni comprensible; la física lo es de todas formas.', 'Neil deGrasse Tyson', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['wisdom', 'curiosity', 'learning'], true, 'science'),
(gen_random_uuid(), 'Los átomos de tu cuerpo fueron forjados en estrellas que murieron antes de que naciera el Sol.', 'Neil deGrasse Tyson', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'La física de partículas encontró el bosón de Higgs, que da masa a las partículas elementales del modelo estándar.', 'Neil deGrasse Tyson', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['curiosity', 'learning', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'La antimateria es real; los tomógrafos de positrones usan positrones médicamente cada día.', 'Neil deGrasse Tyson', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'Un agujero negro supermasivo duerme en el centro de casi cada galaxia grande, incluyendo la nuestra.', 'Neil deGrasse Tyson', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['curiosity', 'learning', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'La gravedad cuántica sigue siendo el gran problema sin resolver que une lo más grande con lo más pequeño.', 'Neil deGrasse Tyson', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'Los quásares son los objetos más luminosos del universo: agujeros negros que devoran materia a gran velocidad.', 'Neil deGrasse Tyson', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['curiosity', 'learning', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'La física relativista predice que el tiempo pasa más lento cerca de un objeto masivo como la Tierra.', 'Neil deGrasse Tyson', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'El universo no se expande en nada; el espacio mismo se estira llevando a las galaxias consigo.', 'Neil deGrasse Tyson', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['curiosity', 'learning', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'La física no distingue pasado de futuro en sus ecuaciones fundamentales; la flecha del tiempo es emergente.', 'Neil deGrasse Tyson', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['wisdom', 'curiosity', 'learning'], true, 'science'),
(gen_random_uuid(), 'La detección de ondas gravitacionales abrió una nueva ventana al universo que complementa la observación óptica.', 'Neil deGrasse Tyson', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'El universo es 13.800 millones de años más antiguo que cualquier dios que haya creído en él.', 'Neil deGrasse Tyson', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),

-- Michio Kaku (187–198)
(gen_random_uuid(), 'La teoría de cuerdas postula que las partículas elementales son modos de vibración de cuerdas unidimensionales.', 'Michio Kaku', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['curiosity', 'learning', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'Las dimensiones extras compactas de la teoría de cuerdas son demasiado pequeñas para detectarse con aceleradores actuales.', 'Michio Kaku', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'El multiverso podría ser la consecuencia natural de la inflación cósmica que ocurrió tras el Big Bang.', 'Michio Kaku', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['curiosity', 'learning', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'La gravedad cuántica de lazos comparte el escenario con la teoría de cuerdas como candidata a teoría final.', 'Michio Kaku', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['learning', 'curiosity', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'Una civilización de tipo I controla la energía de su planeta; la humanidad aún no ha llegado a ese nivel.', 'Michio Kaku', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['curiosity', 'wisdom', 'self_improvement'], true, 'science'),
(gen_random_uuid(), 'Los gusanos de espacio-tiempo son soluciones matemáticas válidas de la relatividad, aunque físicamente cuestionables.', 'Michio Kaku', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['curiosity', 'learning', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'La física del futuro fusionará computación cuántica, inteligencia artificial y medicina personalizada.', 'Michio Kaku', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'El modelo estándar de partículas es el mapa más detallado de los bloques fundamentales de la materia.', 'Michio Kaku', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['learning', 'curiosity', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'La supersimetría predice que cada partícula del modelo estándar tiene un compañero superpartner aún no detectado.', 'Michio Kaku', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'El espacio-tiempo de once dimensiones es el escenario de la teoría M que unifica todas las supercuerdas.', 'Michio Kaku', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['curiosity', 'learning', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'La física fundamental estudia la naturaleza de la realidad a su nivel más profundo y elemental posible.', 'Michio Kaku', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['wisdom', 'curiosity', 'learning'], true, 'science'),
(gen_random_uuid(), 'El universo cuántico es infinitamente más rico y extraño que cualquier ciencia ficción imaginada.', 'Michio Kaku', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),

-- Roger Penrose (199–209)
(gen_random_uuid(), 'La singularidad del Big Bang y la de los agujeros negros son consecuencias inevitables de la relatividad general.', 'Roger Penrose', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'La conjetura de censura cósmica prohíbe que singularidades desnudas sean visibles desde el exterior.', 'Roger Penrose', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['learning', 'curiosity', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'La entropía del universo primitivo era extraordinariamente baja; eso es lo que hace posible el tiempo.', 'Roger Penrose', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'La geometría no es solo un lenguaje matemático; describe la estructura real del espacio-tiempo físico.', 'Roger Penrose', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['curiosity', 'learning', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'Los twistores son objetos matemáticos que describen el espacio-tiempo de forma diferente a las coordenadas usuales.', 'Roger Penrose', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['learning', 'curiosity', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'La conciencia podría involucrar procesos cuánticos en los microtúbulos de las neuronas cerebrales.', 'Roger Penrose', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'La cosmología conforme cíclica propone que el Big Bang fue el final de un universo anterior.', 'Roger Penrose', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['curiosity', 'learning', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'Los espinores son el objeto matemático fundamental para describir fermiones en el espacio-tiempo relativista.', 'Roger Penrose', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['learning', 'curiosity', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'La física no puede ser puramente algorítmica; hay un elemento no computable en la comprensión matemática.', 'Roger Penrose', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['wisdom', 'curiosity', 'learning'], true, 'science'),
(gen_random_uuid(), 'El triángulo de Penrose ilustra cómo la geometría local puede ser consistente y la global imposible.', 'Roger Penrose', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'La relatividad y la cuántica son incompatibles en su forma actual; su unificación es la tarea pendiente mayor.', 'Roger Penrose', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['curiosity', 'learning', 'wisdom'], true, 'science'),

-- J. Robert Oppenheimer (210–218)
(gen_random_uuid(), 'La fisión nuclear libera la energía almacenada en el núcleo atómico con una eficiencia aterradora.', 'J. Robert Oppenheimer', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'La física nuclear reveló que el sol brilla gracias a la fusión de hidrógeno en helio en su núcleo.', 'J. Robert Oppenheimer', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['curiosity', 'learning', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'El físico tiene la obligación moral de comprender las consecuencias de su trabajo más allá del laboratorio.', 'J. Robert Oppenheimer', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['wisdom', 'self_improvement', 'curiosity'], true, 'science'),
(gen_random_uuid(), 'La masa crítica es la cantidad mínima de material fisionable necesaria para que una reacción en cadena sea autosostenida.', 'J. Robert Oppenheimer', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['learning', 'curiosity', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'La física atómica cambió la guerra, la medicina y la energía en un solo siglo de descubrimientos.', 'J. Robert Oppenheimer', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['wisdom', 'learning', 'curiosity'], true, 'science'),
(gen_random_uuid(), 'La ciencia no puede frenar su propio avance; pero la sabiduría humana puede dirigir sus aplicaciones.', 'J. Robert Oppenheimer', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['wisdom', 'self_improvement', 'learning'], true, 'science'),
(gen_random_uuid(), 'La reacción de fusión termonuclear es la fuente de energía de las estrellas y la promesa de la energía limpia.', 'J. Robert Oppenheimer', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['curiosity', 'learning', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'El plutonio-239 y el uranio-235 son los dos isótopos fisionables que hicieron posible la era nuclear.', 'J. Robert Oppenheimer', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['learning', 'curiosity', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'Ahora me he convertido en la muerte, el destructor de mundos; la física puede ser tanto creación como ruina.', 'J. Robert Oppenheimer', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['wisdom', 'curiosity', 'self_improvement'], true, 'science'),

-- Ernest Rutherford (219–227)
(gen_random_uuid(), 'El núcleo atómico es increíblemente pequeño respecto al átomo, como una mosca en una catedral vacía.', 'Ernest Rutherford', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'El experimento de la lámina de oro reveló que la masa atómica está concentrada en un núcleo central.', 'Ernest Rutherford', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['curiosity', 'learning', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'La radiactividad es la desintegración espontánea del núcleo atómico, que emite partículas y radiación.', 'Ernest Rutherford', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['learning', 'curiosity', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'La vida media de un isótopo radiactivo es constante e independiente de condiciones externas como temperatura.', 'Ernest Rutherford', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['learning', 'wisdom', 'curiosity'], true, 'science'),
(gen_random_uuid(), 'La transmutación de elementos ocurre de forma natural en la radiactividad; la alquimia era intuición prematura.', 'Ernest Rutherford', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'El protón fue identificado como el componente positivo del núcleo gracias a experimentos de bombardeo.', 'Ernest Rutherford', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['learning', 'curiosity', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'La física nuclear nació cuando observé que las partículas alfa rebotaban en láminas de oro inesperadamente.', 'Ernest Rutherford', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'Toda ciencia es física o colección de estampillas; las demás disciplinas esperan su reducción a física.', 'Ernest Rutherford', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['wisdom', 'curiosity', 'learning'], true, 'science'),
(gen_random_uuid(), 'La energía de enlace nuclear es lo que mantiene unidos los protones y neutrones contra la repulsión eléctrica.', 'Ernest Rutherford', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['curiosity', 'learning', 'wisdom'], true, 'science'),

-- Enrico Fermi (228–236)
(gen_random_uuid(), 'Si no hay civilizaciones extraterrestres avanzadas, ¿dónde están? Esa paradoja me inquieta profundamente.', 'Enrico Fermi', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'El primer reactor nuclear Chicago Pile-1 demostró que la fisión en cadena controlada era posible.', 'Enrico Fermi', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['curiosity', 'learning', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'La estadística de Fermi-Dirac explica por qué los metales conducen electricidad a temperatura ambiente.', 'Enrico Fermi', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['learning', 'curiosity', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'Los neutrinos atraviesan la Tierra como si no existiera; su masa casi nula los hace imposibles de detener.', 'Enrico Fermi', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'La interacción débil es responsable de la desintegración beta que convierte neutrones en protones.', 'Enrico Fermi', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['learning', 'curiosity', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'Un físico experimental no espera una teoría perfecta; construye un experimento y deja que la naturaleza hable.', 'Enrico Fermi', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['wisdom', 'discipline', 'learning'], true, 'science'),
(gen_random_uuid(), 'Las estimaciones de Fermi usan órdenes de magnitud para llegar a respuestas razonables sin datos exactos.', 'Enrico Fermi', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['learning', 'wisdom', 'curiosity'], true, 'science'),
(gen_random_uuid(), 'La captura neutrónica crea isótopos radiactivos con aplicaciones médicas e industriales invaluables.', 'Enrico Fermi', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['learning', 'curiosity', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'La moderación de neutrones con agua pesada o grafito permite controlar la velocidad de la fisión nuclear.', 'Enrico Fermi', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['curiosity', 'learning', 'wisdom'], true, 'science'),

-- Marie Curie (237–250)
(gen_random_uuid(), 'La radiactividad no es una propiedad química; es una propiedad del núcleo atómico mismo del elemento.', 'Marie Curie', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'El radio y el polonio son elementos que descubrí midiendo pacientemente la ionización del aire circundante.', 'Marie Curie', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['discipline', 'curiosity', 'learning'], true, 'science'),
(gen_random_uuid(), 'La ionización producida por la radiactividad puede medirse con precisión usando un electrómetro sensible.', 'Marie Curie', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['learning', 'curiosity', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'La pechblenda emite más radiación que el uranio puro; eso indicó la presencia de elementos desconocidos.', 'Marie Curie', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['curiosity', 'wisdom', 'learning'], true, 'science'),
(gen_random_uuid(), 'Nada en la vida debe temerse; todo debe ser comprendido, incluida la radiación que tantos misterios guarda.', 'Marie Curie', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['curiosity', 'self_improvement', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'La física y la química son inseparables cuando se estudia la naturaleza del átomo y sus transformaciones.', 'Marie Curie', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['learning', 'curiosity', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'La perseverancia en el laboratorio es la virtud más importante de un científico experimental riguroso.', 'Marie Curie', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['discipline', 'self_improvement', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'Los rayos X, descubiertos por Röntgen, y la radiactividad revelaron que la materia esconde energía enorme.', 'Marie Curie', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['curiosity', 'learning', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'La ciencia no conoce fronteras nacionales; pertenece a la humanidad entera y la humanidad es su linterna.', 'Marie Curie', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['wisdom', 'curiosity', 'self_improvement'], true, 'science'),
(gen_random_uuid(), 'El aislamiento de un gramo de radio requirió toneladas de pechblenda y años de trabajo incesante.', 'Marie Curie', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['discipline', 'self_improvement', 'learning'], true, 'science'),
(gen_random_uuid(), 'La radiación gamma penetra la materia con mayor facilidad que los rayos alfa o beta por su naturaleza fotónica.', 'Marie Curie', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['learning', 'curiosity', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'Una mujer en física debe trabajar el doble para demostrar la mitad; esa injusticia no detendrá la ciencia.', 'Marie Curie', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['self_improvement', 'discipline', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'Los isótopos del mismo elemento tienen propiedades químicas idénticas pero masas nucleares diferentes.', 'Marie Curie', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['learning', 'curiosity', 'wisdom'], true, 'science'),
(gen_random_uuid(), 'La ciencia experimental exige honestidad absoluta con los datos, sin importar si contradicen la hipótesis.', 'Marie Curie', 'philosophy', 'es', 'down', 'free', false, 'science', 'physics', ARRAY['wisdom', 'discipline', 'self_improvement'], true, 'science')

ON CONFLICT (text, author) DO NOTHING;

COMMIT;
