-- 040_science_tech_es.sql
-- MindScrolling — Science Mode: Technology batch (Spanish)
-- 250 quotes: computación, IA, internet, robótica, tecnología espacial, biotecnología,
--   energía renovable, revolución digital, innovación, automatización,
--   ciberseguridad, realidad virtual
--
-- All rows:
--   category       = 'philosophy'
--   lang           = 'es'
--   swipe_dir      = 'down'
--   pack_name      = 'free'
--   is_premium     = false
--   content_type   = 'science'
--   sub_category   = 'technology'
--   is_hidden_mode = true
--   locked_by      = 'science'
-- Run in Supabase SQL Editor

BEGIN;

-- ══════════════════════════════════════════════════════════════════════════════
-- TECHNOLOGY — SPANISH (250 quotes)
-- ══════════════════════════════════════════════════════════════════════════════

INSERT INTO quotes (id, text, author, category, lang, swipe_dir, pack_name, is_premium, content_type, sub_category, tags, is_hidden_mode, locked_by) VALUES

-- Alan Turing (1–16)
(gen_random_uuid(), 'Solo podemos ver poco hacia adelante, pero podemos ver mucho de lo que necesita hacerse.', 'Alan Turing', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['curiosity','learning'], true, 'science'),
(gen_random_uuid(), 'Una máquina merecería llamarse inteligente si pudiera engañar a un humano haciéndole creer que es humano.', 'Alan Turing', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['curiosity','logic'], true, 'science'),
(gen_random_uuid(), 'A veces son las personas de las que nadie espera nada quienes hacen las cosas que nadie puede imaginar.', 'Alan Turing', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['curiosity','perseverance'], true, 'science'),
(gen_random_uuid(), 'Quienes pueden imaginar cualquier cosa pueden crear lo imposible.', 'Alan Turing', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['creativity','curiosity'], true, 'science'),
(gen_random_uuid(), 'La pregunta no es si las máquinas pueden pensar, sino si los hombres lo hacen.', 'Alan Turing', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['curiosity','wisdom'], true, 'science'),
(gen_random_uuid(), 'La ciencia es una ecuación diferencial; la religión es una condición de frontera.', 'Alan Turing', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['curiosity','logic'], true, 'science'),
(gen_random_uuid(), 'El razonamiento matemático puede considerarse como el ejercicio de una combinación de ingenio y paciencia.', 'Alan Turing', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['curiosity','learning'], true, 'science'),
(gen_random_uuid(), 'Si se espera que una máquina sea infalible, no puede ser también inteligente.', 'Alan Turing', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['curiosity','wisdom'], true, 'science'),
(gen_random_uuid(), 'La pregunta original de si las máquinas pueden pensar es demasiado imprecisa para merecer discusión.', 'Alan Turing', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['curiosity','logic'], true, 'science'),
(gen_random_uuid(), 'Las máquinas me sorprenden con mucha frecuencia.', 'Alan Turing', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['curiosity','learning'], true, 'science'),
(gen_random_uuid(), 'No estamos interesados en el hecho de que el cerebro tenga la consistencia de la papilla fría.', 'Alan Turing', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['curiosity','logic'], true, 'science'),
(gen_random_uuid(), 'Una computadora no es inteligente a menos que pueda imitar el pensamiento humano.', 'Alan Turing', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['curiosity','logic'], true, 'science'),
(gen_random_uuid(), 'Podemos llamar inteligencia a todo aquello que un algoritmo puede aprender a hacer mejor que un humano.', 'Alan Turing', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['learning','curiosity'], true, 'science'),
(gen_random_uuid(), 'El aprendizaje automático es la ciencia de hacer que las computadoras actúen sin ser programadas explícitamente.', 'Alan Turing', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['learning','logic'], true, 'science'),
(gen_random_uuid(), 'El código es poesía ejecutable; cada línea es una decisión que moldea la realidad digital.', 'Alan Turing', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['creativity','logic'], true, 'science'),
(gen_random_uuid(), 'La inteligencia artificial comenzará donde termina la rigidez de nuestras propias suposiciones.', 'Alan Turing', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['curiosity','wisdom'], true, 'science'),

-- Ada Lovelace (17–30)
(gen_random_uuid(), 'La imaginación es la facultad del descubrimiento por excelencia. Es lo que penetra en los mundos invisibles que nos rodean.', 'Ada Lovelace', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['creativity','curiosity'], true, 'science'),
(gen_random_uuid(), 'El motor analítico no tiene pretensiones de originar nada. Puede hacer lo que sabemos ordenarle que haga.', 'Ada Lovelace', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['logic','curiosity'], true, 'science'),
(gen_random_uuid(), 'La ciencia de las operaciones, tal como surge de las matemáticas, es la ciencia de sí misma.', 'Ada Lovelace', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['learning','logic'], true, 'science'),
(gen_random_uuid(), 'Nunca paro hasta que logro lo que quiero; no hay límites para lo que yo puedo hacer.', 'Ada Lovelace', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['perseverance','focus'], true, 'science'),
(gen_random_uuid(), 'El número es el único lenguaje universal que las máquinas y los humanos comparten.', 'Ada Lovelace', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['logic','learning'], true, 'science'),
(gen_random_uuid(), 'Las matemáticas son el lenguaje con el que el universo escribe sus leyes más profundas.', 'Ada Lovelace', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['curiosity','logic'], true, 'science'),
(gen_random_uuid(), 'Toda máquina comienza como un sueño en la mente de quien se atreve a imaginar lo imposible.', 'Ada Lovelace', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['creativity','perseverance'], true, 'science'),
(gen_random_uuid(), 'Mi cerebro es más que meramente mortal; de eso estoy bastante segura.', 'Ada Lovelace', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['courage','perseverance'], true, 'science'),
(gen_random_uuid(), 'La poesía científica y la poesía literaria no son tan distintas como la gente supone.', 'Ada Lovelace', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['creativity','curiosity'], true, 'science'),
(gen_random_uuid(), 'Aquella que puede abstraer las relaciones más complejas tiene la clave del progreso técnico.', 'Ada Lovelace', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['logic','learning'], true, 'science'),
(gen_random_uuid(), 'La computación no es solo aritmética; es el arte de transformar problemas en soluciones paso a paso.', 'Ada Lovelace', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['logic','creativity'], true, 'science'),
(gen_random_uuid(), 'El futuro pertenece a quienes entienden que los números son la nueva escritura del mundo.', 'Ada Lovelace', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['learning','curiosity'], true, 'science'),
(gen_random_uuid(), 'Una mente analítica ve patrones donde otros solo ven caos.', 'Ada Lovelace', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['logic','wisdom'], true, 'science'),
(gen_random_uuid(), 'Para programar el futuro hay que entender primero el presente con absoluta claridad.', 'Ada Lovelace', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['logic','learning'], true, 'science'),

-- Nikola Tesla (31–44)
(gen_random_uuid(), 'El presente es suyo; el futuro, por el cual realmente he trabajado, es mío.', 'Nikola Tesla', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['perseverance','wisdom'], true, 'science'),
(gen_random_uuid(), 'Si quieres encontrar los secretos del universo, piensa en términos de energía, frecuencia y vibración.', 'Nikola Tesla', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['curiosity','wisdom'], true, 'science'),
(gen_random_uuid(), 'Nuestra mayor ignorancia es la ignorancia de lo que ignoramos.', 'Nikola Tesla', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['curiosity','wisdom'], true, 'science'),
(gen_random_uuid(), 'La mente es como un paracaídas: solo funciona cuando está abierta.', 'Nikola Tesla', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['curiosity','learning'], true, 'science'),
(gen_random_uuid(), 'El día en que captemos la ciencia detrás del relámpago lo habremos dominado todo.', 'Nikola Tesla', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['curiosity','perseverance'], true, 'science'),
(gen_random_uuid(), 'No me preocupo por el dinero; me preocupa el trabajo que no he podido terminar.', 'Nikola Tesla', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['focus','perseverance'], true, 'science'),
(gen_random_uuid(), 'Seré recordado por haber dotado de electricidad al mundo; aún no he empezado.', 'Nikola Tesla', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['perseverance','courage'], true, 'science'),
(gen_random_uuid(), 'La electricidad no es solo una fuente de luz; es el lenguaje del cosmos hecho visible.', 'Nikola Tesla', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['curiosity','wisdom'], true, 'science'),
(gen_random_uuid(), 'La soledad es la fuente de toda verdadera creatividad y de todo gran descubrimiento.', 'Nikola Tesla', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['creativity','reflection'], true, 'science'),
(gen_random_uuid(), 'He construido, inventado y descubierto para dar a la humanidad una vida más fácil y digna.', 'Nikola Tesla', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['perseverance','wisdom'], true, 'science'),
(gen_random_uuid(), 'La energía del futuro no vendrá del petróleo; vendrá del sol, el viento y la tierra misma.', 'Nikola Tesla', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['curiosity','learning'], true, 'science'),
(gen_random_uuid(), 'Un inventor es el que ve lo que todos han visto y piensa lo que nadie ha pensado.', 'Nikola Tesla', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['creativity','curiosity'], true, 'science'),
(gen_random_uuid(), 'Lo que hoy parece ciencia ficción mañana será simplemente ciencia.', 'Nikola Tesla', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['curiosity','wisdom'], true, 'science'),
(gen_random_uuid(), 'El cerebro no es más que una computadora hecha de carne; tarde o temprano haremos máquinas que lo superen.', 'Nikola Tesla', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['curiosity','logic'], true, 'science'),

-- Steve Jobs (45–60)
(gen_random_uuid(), 'La innovación distingue a los líderes de los seguidores.', 'Steve Jobs', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['creativity','leadership'], true, 'science'),
(gen_random_uuid(), 'La tecnología no tiene sentido por sí sola. Es la fe en la humanidad, el arte, la poesía y el amor lo que hace que la tecnología valga la pena.', 'Steve Jobs', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['creativity','wisdom'], true, 'science'),
(gen_random_uuid(), 'Sé hambriento, sé ingenuo.', 'Steve Jobs', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['curiosity','perseverance'], true, 'science'),
(gen_random_uuid(), 'La creatividad consiste en conectar cosas. Cuando preguntas a personas creativas cómo hicieron algo, se sienten un poco culpables porque no lo hicieron realmente.', 'Steve Jobs', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['creativity','curiosity'], true, 'science'),
(gen_random_uuid(), 'El diseño no es solo cómo se ve; diseño es cómo funciona.', 'Steve Jobs', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['creativity','focus'], true, 'science'),
(gen_random_uuid(), 'Tu tiempo es limitado, así que no lo malgastes viviendo la vida de otra persona.', 'Steve Jobs', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['wisdom','focus'], true, 'science'),
(gen_random_uuid(), 'Los mejores publicistas son quienes toman algo complicado y lo hacen simple.', 'Steve Jobs', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['creativity','focus'], true, 'science'),
(gen_random_uuid(), 'Estoy convencido de que la mitad de lo que separa a los emprendedores exitosos de los que no lo son es pura perseverancia.', 'Steve Jobs', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['perseverance','courage'], true, 'science'),
(gen_random_uuid(), 'Tenemos que tener mucho cuidado de no ahogar la chispa de la curiosidad con demasiada estructura.', 'Steve Jobs', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['curiosity','creativity'], true, 'science'),
(gen_random_uuid(), 'La calidad es más importante que la cantidad. Un jonrón es mejor que dos dobles.', 'Steve Jobs', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['focus','wisdom'], true, 'science'),
(gen_random_uuid(), 'No puedes unir los puntos mirando hacia adelante; solo puedes hacerlo mirando hacia atrás.', 'Steve Jobs', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['wisdom','reflection'], true, 'science'),
(gen_random_uuid(), 'Poner en el mercado ideas brillantes no significa nada si no se ejecutan.', 'Steve Jobs', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['focus','perseverance'], true, 'science'),
(gen_random_uuid(), 'El ordenador personal es la bicicleta para la mente humana.', 'Steve Jobs', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['creativity','curiosity'], true, 'science'),
(gen_random_uuid(), 'En un mundo conectado, la diferencia entre un mediocre y un genio es solo la calidad de su curiosidad.', 'Steve Jobs', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['curiosity','wisdom'], true, 'science'),
(gen_random_uuid(), 'Cuando los buenos artistas copian, los grandes artistas roban. Y nosotros siempre hemos sido descarados al robar grandes ideas.', 'Steve Jobs', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['creativity','learning'], true, 'science'),
(gen_random_uuid(), 'Simplicity is the ultimate sophistication — la simplicidad es la máxima sofisticación.', 'Steve Jobs', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['focus','creativity'], true, 'science'),

-- Bill Gates (61–74)
(gen_random_uuid(), 'La tecnología solo es una herramienta. En cuanto a motivar a los niños y hacer el trabajo con ellos, el profesor es lo más importante.', 'Bill Gates', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['learning','wisdom'], true, 'science'),
(gen_random_uuid(), 'Siempre sobrestimamos el cambio que ocurrirá en los próximos dos años y subestimamos el que ocurrirá en los próximos diez.', 'Bill Gates', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['curiosity','wisdom'], true, 'science'),
(gen_random_uuid(), 'El éxito es un mal profesor. Seduce a las personas inteligentes para que piensen que no pueden perder.', 'Bill Gates', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['wisdom','reflection'], true, 'science'),
(gen_random_uuid(), 'Si no puede medirse, no puede mejorarse.', 'Bill Gates', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['logic','focus'], true, 'science'),
(gen_random_uuid(), 'La automatización aplicada a una operación ineficiente ampliará la ineficiencia.', 'Bill Gates', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['logic','wisdom'], true, 'science'),
(gen_random_uuid(), 'En esta era digital, la educación no puede quedarse atrás. Aprender a programar es tan fundamental como leer.', 'Bill Gates', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['learning','curiosity'], true, 'science'),
(gen_random_uuid(), 'Los robots no nos quitarán los empleos; cambiarán los empleos que hacemos. Nuestra tarea es adaptarnos.', 'Bill Gates', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['wisdom','learning'], true, 'science'),
(gen_random_uuid(), 'La inteligencia artificial es la frontera más emocionante de la humanidad desde la revolución industrial.', 'Bill Gates', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['curiosity','learning'], true, 'science'),
(gen_random_uuid(), 'El software es una gran combinación entre arte y tecnología.', 'Bill Gates', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['creativity','curiosity'], true, 'science'),
(gen_random_uuid(), 'Sé amable con los nerds. Existen probabilidades de que acabes trabajando para uno de ellos.', 'Bill Gates', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['wisdom','learning'], true, 'science'),
(gen_random_uuid(), 'Internet es el primer gran avance de la humanidad desde el libro impreso.', 'Bill Gates', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['curiosity','learning'], true, 'science'),
(gen_random_uuid(), 'El ciberespacio no tiene fronteras geográficas, pero sí consecuencias muy reales.', 'Bill Gates', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['wisdom','curiosity'], true, 'science'),
(gen_random_uuid(), 'El mundo no te debe nada. Existía primero.', 'Bill Gates', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['wisdom','reflection'], true, 'science'),
(gen_random_uuid(), 'Elegir un trabajo que te apasione es la mejor manera de transformar el mundo desde adentro.', 'Bill Gates', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['focus','perseverance'], true, 'science'),

-- Tim Berners-Lee (75–86)
(gen_random_uuid(), 'La web es más una creación social que técnica. La diseñé para un efecto social, no como un juguete tecnológico.', 'Tim Berners-Lee', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['curiosity','wisdom'], true, 'science'),
(gen_random_uuid(), 'Los datos son el petróleo del siglo XXI, pero a diferencia del petróleo, pueden compartirse sin agotarse.', 'Tim Berners-Lee', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['curiosity','learning'], true, 'science'),
(gen_random_uuid(), 'La web debe ser para todos, sin barreras de lengua, cultura o capacidad.', 'Tim Berners-Lee', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['wisdom','learning'], true, 'science'),
(gen_random_uuid(), 'Internet es un espacio público global; protegerlo es proteger la democracia misma.', 'Tim Berners-Lee', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['courage','wisdom'], true, 'science'),
(gen_random_uuid(), 'Cualquier persona cuyas ideas puedan conectar con las tuyas a través de una red transforma tu capacidad de pensar.', 'Tim Berners-Lee', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['curiosity','learning'], true, 'science'),
(gen_random_uuid(), 'El objetivo de la web es servir a la humanidad; cuando lo olvidamos, nos perdemos.', 'Tim Berners-Lee', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['wisdom','reflection'], true, 'science'),
(gen_random_uuid(), 'El hipertexto fue la clave: conectar documentos para conectar personas.', 'Tim Berners-Lee', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['curiosity','creativity'], true, 'science'),
(gen_random_uuid(), 'La privacidad es un derecho humano fundamental que la tecnología debe proteger, no erosionar.', 'Tim Berners-Lee', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['courage','wisdom'], true, 'science'),
(gen_random_uuid(), 'Un internet abierto es una oportunidad para cada persona en el planeta de aprender, crear e innovar.', 'Tim Berners-Lee', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['learning','curiosity'], true, 'science'),
(gen_random_uuid(), 'Diseñé la web para que fuera una herramienta de paz y comprensión; aún creo que puede serlo.', 'Tim Berners-Lee', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['wisdom','perseverance'], true, 'science'),
(gen_random_uuid(), 'El código abierto es la filosofía más poderosa que ha producido la era digital.', 'Tim Berners-Lee', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['curiosity','creativity'], true, 'science'),
(gen_random_uuid(), 'Cuando compartimos conocimiento libremente en la red, todos nos volvemos más inteligentes.', 'Tim Berners-Lee', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['learning','wisdom'], true, 'science'),

-- Grace Hopper (87–98)
(gen_random_uuid(), 'La frase más peligrosa en el idioma es: siempre lo hemos hecho así.', 'Grace Hopper', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['courage','wisdom'], true, 'science'),
(gen_random_uuid(), 'Va a la cama cuando quieras; aprende cuando quieras; sé curioso cuando quieras. Pero hazlo.', 'Grace Hopper', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['curiosity','perseverance'], true, 'science'),
(gen_random_uuid(), 'Si tienes una buena idea, ponla en marcha. Es mucho más fácil pedir perdón que pedir permiso.', 'Grace Hopper', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['courage','perseverance'], true, 'science'),
(gen_random_uuid(), 'Los humanos son alérgicos al cambio; les gusta decir que siempre lo han hecho así. Yo intento combatir eso.', 'Grace Hopper', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['courage','wisdom'], true, 'science'),
(gen_random_uuid(), 'El liderazgo es comprensión de personas.', 'Grace Hopper', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['wisdom','leadership'], true, 'science'),
(gen_random_uuid(), 'Uno de los errores más dañinos que puedes cometer en un equipo es creer que la idea del otro siempre vale menos.', 'Grace Hopper', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['wisdom','learning'], true, 'science'),
(gen_random_uuid(), 'En ciencias de la computación, los barcos en el puerto están seguros, pero no es para eso para lo que se construyen los barcos.', 'Grace Hopper', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['courage','perseverance'], true, 'science'),
(gen_random_uuid(), 'Los mejores programadores no son los que más saben; son los que mejor preguntan.', 'Grace Hopper', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['curiosity','learning'], true, 'science'),
(gen_random_uuid(), 'Una máquina solo puede hacer lo que le digamos; su inteligencia es el reflejo de la nuestra.', 'Grace Hopper', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['logic','wisdom'], true, 'science'),
(gen_random_uuid(), 'El aprendizaje es una aventura continua; quien deja de aprender deja de crecer.', 'Grace Hopper', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['learning','perseverance'], true, 'science'),
(gen_random_uuid(), 'El software sin documentación es como una ciudad sin señales de tráfico: funciona hasta que falla.', 'Grace Hopper', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['logic','wisdom'], true, 'science'),
(gen_random_uuid(), 'La computación es más que calcular; es una manera de pensar sobre el mundo.', 'Grace Hopper', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['curiosity','logic'], true, 'science'),

-- Arthur C. Clarke (99–110)
(gen_random_uuid(), 'Cualquier tecnología suficientemente avanzada es indistinguible de la magia.', 'Arthur C. Clarke', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['curiosity','wisdom'], true, 'science'),
(gen_random_uuid(), 'La única forma de descubrir los límites de lo posible es aventurarse en lo imposible.', 'Arthur C. Clarke', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['courage','curiosity'], true, 'science'),
(gen_random_uuid(), 'Si un anciano y distinguido científico dice que algo es posible, probablemente tiene razón; si dice que es imposible, casi con seguridad está equivocado.', 'Arthur C. Clarke', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['curiosity','wisdom'], true, 'science'),
(gen_random_uuid(), 'El vuelo espacial es la segunda mayor aventura de la humanidad; la primera es la de la mente.', 'Arthur C. Clarke', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['curiosity','perseverance'], true, 'science'),
(gen_random_uuid(), 'No podemos predecir el futuro, pero sí podemos inventarlo.', 'Arthur C. Clarke', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['creativity','courage'], true, 'science'),
(gen_random_uuid(), 'Los satélites artificiales cambiarán el mundo más que ningún otro invento desde la imprenta.', 'Arthur C. Clarke', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['curiosity','wisdom'], true, 'science'),
(gen_random_uuid(), 'Las comunicaciones mundiales instantáneas crearán una aldea global; la pregunta es si esa aldea será civilizada.', 'Arthur C. Clarke', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['curiosity','wisdom'], true, 'science'),
(gen_random_uuid(), 'El universo es no solo más extraño de lo que suponemos, sino más extraño de lo que podemos suponer.', 'Arthur C. Clarke', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['curiosity','wonder'], true, 'science'),
(gen_random_uuid(), 'La exploración espacial no es un lujo; es la única garantía de supervivencia a largo plazo de nuestra especie.', 'Arthur C. Clarke', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['courage','perseverance'], true, 'science'),
(gen_random_uuid(), 'La robótica llevará a cabo las tareas monótonas; la humanidad se dedicará a crear.', 'Arthur C. Clarke', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['creativity','wisdom'], true, 'science'),
(gen_random_uuid(), 'Cuando la tecnología supere el arte de construir máquinas que piensen, la humanidad entrará en una nueva era.', 'Arthur C. Clarke', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['curiosity','logic'], true, 'science'),
(gen_random_uuid(), 'Las estrellas no son el destino final; son el primer paso de un viaje sin fin.', 'Arthur C. Clarke', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['curiosity','perseverance'], true, 'science'),

-- Isaac Asimov (111–124)
(gen_random_uuid(), 'El autoeducado es quien sabe que la ignorancia lo rodea por todos lados.', 'Isaac Asimov', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['learning','curiosity'], true, 'science'),
(gen_random_uuid(), 'La ciencia recopila conocimiento más rápido de lo que la sociedad recopila sabiduría.', 'Isaac Asimov', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['wisdom','curiosity'], true, 'science'),
(gen_random_uuid(), 'Los robots son la proyección de nuestras aspiraciones más nobles y de nuestros miedos más profundos.', 'Isaac Asimov', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['curiosity','reflection'], true, 'science'),
(gen_random_uuid(), 'Las tres leyes de la robótica existen porque los humanos son demasiado falibles para confiarles el poder sin restricciones.', 'Isaac Asimov', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['wisdom','logic'], true, 'science'),
(gen_random_uuid(), 'En la ciencia, la satisfacción de entender supera la incomodidad de descubrir que estabas equivocado.', 'Isaac Asimov', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['curiosity','learning'], true, 'science'),
(gen_random_uuid(), 'Cuanto más se expande el conocimiento, más crecen los bordes de la ignorancia.', 'Isaac Asimov', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['curiosity','wisdom'], true, 'science'),
(gen_random_uuid(), 'Una inteligencia artificial que aprende de sus errores es más valiosa que una que nunca los comete.', 'Isaac Asimov', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['learning','logic'], true, 'science'),
(gen_random_uuid(), 'La ciencia ficción de hoy es la tecnología de mañana; no hay mejor laboratorio que la imaginación.', 'Isaac Asimov', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['creativity','curiosity'], true, 'science'),
(gen_random_uuid(), 'Las computadoras no son mágicas; son el resultado de millones de decisiones lógicas tomadas en secuencia.', 'Isaac Asimov', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['logic','learning'], true, 'science'),
(gen_random_uuid(), 'La automatización convierte tareas rutinarias en procesos invisibles y libera la mente para lo esencial.', 'Isaac Asimov', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['wisdom','learning'], true, 'science'),
(gen_random_uuid(), 'Si el conocimiento puede crear problemas, no es la ignorancia la solución.', 'Isaac Asimov', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['wisdom','curiosity'], true, 'science'),
(gen_random_uuid(), 'La humanidad siempre ha tenido miedo de sus propias creaciones; eso no ha impedido crearlas.', 'Isaac Asimov', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['courage','curiosity'], true, 'science'),
(gen_random_uuid(), 'La inteligencia es la capacidad de adaptarse al cambio.', 'Isaac Asimov', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['wisdom','learning'], true, 'science'),
(gen_random_uuid(), 'El futuro de la robótica no está en reemplazar humanos, sino en amplificar lo mejor de ellos.', 'Isaac Asimov', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['wisdom','curiosity'], true, 'science'),

-- Ray Kurzweil (125–136)
(gen_random_uuid(), 'La singularidad está cerca. La fusión entre humanos y máquinas ya ha comenzado.', 'Ray Kurzweil', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['curiosity','wisdom'], true, 'science'),
(gen_random_uuid(), 'El ritmo del cambio tecnológico es exponencial, no lineal; nuestros cerebros no están diseñados para comprenderlo.', 'Ray Kurzweil', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['curiosity','learning'], true, 'science'),
(gen_random_uuid(), 'En treinta años la inteligencia artificial superará a la humana en cada dominio intelectual.', 'Ray Kurzweil', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['curiosity','wisdom'], true, 'science'),
(gen_random_uuid(), 'La nanotecnología reparará nuestros cuerpos desde dentro; la biología es solo la primera versión.', 'Ray Kurzweil', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['curiosity','learning'], true, 'science'),
(gen_random_uuid(), 'El cerebro humano no es el pináculo de la inteligencia posible; es el punto de partida.', 'Ray Kurzweil', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['curiosity','wisdom'], true, 'science'),
(gen_random_uuid(), 'Las tecnologías exponenciales derriban barreras que parecían eternas en solo una generación.', 'Ray Kurzweil', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['curiosity','learning'], true, 'science'),
(gen_random_uuid(), 'El aprendizaje profundo no es solo un algoritmo; es el primer destello de inteligencia emergente.', 'Ray Kurzweil', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['curiosity','logic'], true, 'science'),
(gen_random_uuid(), 'Digitalizar el conocimiento humano es el proyecto más ambicioso de nuestra civilización.', 'Ray Kurzweil', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['learning','curiosity'], true, 'science'),
(gen_random_uuid(), 'Las interfaces cerebro-computadora nos permitirán expandir la conciencia más allá del cráneo.', 'Ray Kurzweil', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['curiosity','wonder'], true, 'science'),
(gen_random_uuid(), 'La biotecnología reprogramará la vida como si fuera software; el código genético es solo el inicio.', 'Ray Kurzweil', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['curiosity','learning'], true, 'science'),
(gen_random_uuid(), 'Cada avance tecnológico es una victoria de la razón humana sobre las limitaciones de la materia.', 'Ray Kurzweil', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['wisdom','perseverance'], true, 'science'),
(gen_random_uuid(), 'La inteligencia artificial no tiene emociones, pero puede aprender a simularlas tan bien que la diferencia se vuelve filosófica.', 'Ray Kurzweil', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['curiosity','wisdom'], true, 'science'),

-- Marshall McLuhan (137–148)
(gen_random_uuid(), 'El medio es el mensaje.', 'Marshall McLuhan', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['wisdom','curiosity'], true, 'science'),
(gen_random_uuid(), 'Hemos hecho extensiones de nosotros mismos con todos los materiales tecnológicos.', 'Marshall McLuhan', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['curiosity','reflection'], true, 'science'),
(gen_random_uuid(), 'La aldea global ya existe; y en ella cada mensaje es un estallido simultáneo para toda la humanidad.', 'Marshall McLuhan', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['wisdom','curiosity'], true, 'science'),
(gen_random_uuid(), 'El libro impreso creó la nación; internet creará la aldea global. El efecto es siempre mayor que la causa.', 'Marshall McLuhan', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['curiosity','wisdom'], true, 'science'),
(gen_random_uuid(), 'Quien controla los medios controla las mentes; es la ecuación más poderosa de la historia.', 'Marshall McLuhan', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['wisdom','reflection'], true, 'science'),
(gen_random_uuid(), 'La tecnología es una extensión del cuerpo humano; moldeamos las herramientas y luego las herramientas nos moldean.', 'Marshall McLuhan', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['wisdom','reflection'], true, 'science'),
(gen_random_uuid(), 'La electricidad no introdujo simplemente la luz; introdujo un nuevo modo de vivir simultáneamente en el tiempo y el espacio.', 'Marshall McLuhan', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['curiosity','wisdom'], true, 'science'),
(gen_random_uuid(), 'La era digital es la era del mosaico: todo está relacionado con todo al mismo tiempo.', 'Marshall McLuhan', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['curiosity','learning'], true, 'science'),
(gen_random_uuid(), 'El mundo se ha convertido en una computadora y la computadora en una extensión del cerebro humano.', 'Marshall McLuhan', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['curiosity','wisdom'], true, 'science'),
(gen_random_uuid(), 'Vivimos en una edad definida por la velocidad de la información, no por la profundidad del pensamiento.', 'Marshall McLuhan', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['wisdom','reflection'], true, 'science'),
(gen_random_uuid(), 'Los medios de comunicación no son ventanas al mundo; son ventanas a nuestras propias mentes.', 'Marshall McLuhan', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['reflection','wisdom'], true, 'science'),
(gen_random_uuid(), 'Internet es el primer entorno creado por los humanos que no tiene centro ni periferia.', 'Marshall McLuhan', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['curiosity','wisdom'], true, 'science'),

-- Elon Musk (149–162)
(gen_random_uuid(), 'Cuando algo es suficientemente importante, lo haces incluso si las probabilidades no están a tu favor.', 'Elon Musk', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['courage','perseverance'], true, 'science'),
(gen_random_uuid(), 'Si algo es importante para el futuro de la humanidad, debería hacerse aunque la probabilidad de éxito sea baja.', 'Elon Musk', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['courage','wisdom'], true, 'science'),
(gen_random_uuid(), 'La primera regla de cualquier tecnología usada en un negocio es que la automatización aplicada a una operación eficiente multiplicará la eficiencia.', 'Elon Musk', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['logic','focus'], true, 'science'),
(gen_random_uuid(), 'La humanidad debe convertirse en una especie multiplanetaria; no es un lujo, es una necesidad de supervivencia.', 'Elon Musk', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['courage','perseverance'], true, 'science'),
(gen_random_uuid(), 'Los vehículos eléctricos no son el futuro; son el presente que el mundo aún no ha aceptado.', 'Elon Musk', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['curiosity','perseverance'], true, 'science'),
(gen_random_uuid(), 'La IA es la tecnología más transformadora y potencialmente peligrosa que la humanidad ha creado.', 'Elon Musk', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['wisdom','curiosity'], true, 'science'),
(gen_random_uuid(), 'Los cohetes reutilizables cambiarán el acceso al espacio tanto como los aviones cambiaron el acceso al cielo.', 'Elon Musk', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['curiosity','perseverance'], true, 'science'),
(gen_random_uuid(), 'Trabaja como si el trabajo que amas dependiera de ello, porque probablemente así sea.', 'Elon Musk', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['focus','perseverance'], true, 'science'),
(gen_random_uuid(), 'La energía solar es la única fuente que puede satisfacer la demanda energética global sin destruir el planeta.', 'Elon Musk', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['curiosity','wisdom'], true, 'science'),
(gen_random_uuid(), 'La ciberseguridad es tan importante como la seguridad física; ninguna sociedad digital puede ignorarla.', 'Elon Musk', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['wisdom','courage'], true, 'science'),
(gen_random_uuid(), 'Los humanos somos criaturas digitales atrapadas en cuerpos analógicos; la fusión es inevitable.', 'Elon Musk', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['curiosity','reflection'], true, 'science'),
(gen_random_uuid(), 'Perseverancia es la diferencia entre los que sueñan y los que construyen.', 'Elon Musk', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['perseverance','focus'], true, 'science'),
(gen_random_uuid(), 'La realidad virtual creará mundos tan ricos como el real; la pregunta es qué haremos con esa libertad.', 'Elon Musk', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['curiosity','wonder'], true, 'science'),
(gen_random_uuid(), 'El fracaso es una opción aquí. Si las cosas no están fallando, no estás innovando lo suficiente.', 'Elon Musk', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['courage','perseverance'], true, 'science'),

-- Marc Andreessen (163–172)
(gen_random_uuid(), 'El software está devorando al mundo. Cada industria está siendo redefinida por la tecnología.', 'Marc Andreessen', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['curiosity','wisdom'], true, 'science'),
(gen_random_uuid(), 'Las grandes ideas tecnológicas son rechazadas por la mayoría antes de que se vuelvan obvias para todos.', 'Marc Andreessen', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['courage','wisdom'], true, 'science'),
(gen_random_uuid(), 'Internet democratizó la distribución del conocimiento; nadie vuelve a controlar lo que la gente puede saber.', 'Marc Andreessen', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['wisdom','learning'], true, 'science'),
(gen_random_uuid(), 'El mayor riesgo en tecnología es no correr riesgos. Los mercados premian la audacia, no la prudencia.', 'Marc Andreessen', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['courage','wisdom'], true, 'science'),
(gen_random_uuid(), 'La inteligencia artificial ampliará la capacidad humana tanto como el microscopio amplió nuestra visión del mundo.', 'Marc Andreessen', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['curiosity','learning'], true, 'science'),
(gen_random_uuid(), 'En veinte años toda empresa será una empresa tecnológica o dejará de existir.', 'Marc Andreessen', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['wisdom','curiosity'], true, 'science'),
(gen_random_uuid(), 'Las plataformas de código abierto son los cimientos invisibles sobre los que descansa la economía digital.', 'Marc Andreessen', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['learning','wisdom'], true, 'science'),
(gen_random_uuid(), 'El dinero no es la restricción más importante para las startups tecnológicas; lo es el talento.', 'Marc Andreessen', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['wisdom','focus'], true, 'science'),
(gen_random_uuid(), 'La computación en la nube es la infraestructura invisible que hace posible el mundo digital moderno.', 'Marc Andreessen', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['curiosity','learning'], true, 'science'),
(gen_random_uuid(), 'Cuando la tecnología es lo suficientemente poderosa, se vuelve política. Toda revolución digital es también social.', 'Marc Andreessen', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['wisdom','curiosity'], true, 'science'),

-- Vint Cerf (173–182)
(gen_random_uuid(), 'Internet es una conversación global que nunca termina; su poder radica en la participación, no en la infraestructura.', 'Vint Cerf', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['wisdom','curiosity'], true, 'science'),
(gen_random_uuid(), 'Diseñamos internet para que fuera resistente a los fallos; no anticipamos que los humanos podrían convertirse en el punto débil.', 'Vint Cerf', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['wisdom','reflection'], true, 'science'),
(gen_random_uuid(), 'La interoperabilidad es el valor más subestimado en la historia de la tecnología.', 'Vint Cerf', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['logic','wisdom'], true, 'science'),
(gen_random_uuid(), 'Los protocolos de red son los tratados diplomáticos del mundo digital; sin ellos, el caos es inevitable.', 'Vint Cerf', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['logic','wisdom'], true, 'science'),
(gen_random_uuid(), 'La ciberseguridad no es un producto; es un proceso continuo que nunca termina.', 'Vint Cerf', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['wisdom','perseverance'], true, 'science'),
(gen_random_uuid(), 'Cada dispositivo conectado es una puerta; la seguridad de toda la red depende de la más débil de ellas.', 'Vint Cerf', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['wisdom','logic'], true, 'science'),
(gen_random_uuid(), 'El acceso a internet no debería ser un privilegio; debería ser tan universal como el agua potable.', 'Vint Cerf', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['wisdom','courage'], true, 'science'),
(gen_random_uuid(), 'La arquitectura abierta de internet es lo que hizo posible la innovación que nadie había planeado.', 'Vint Cerf', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['curiosity','creativity'], true, 'science'),
(gen_random_uuid(), 'En la era digital, la identidad es tan valiosa como la propiedad; protegerla exige la misma diligencia.', 'Vint Cerf', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['wisdom','courage'], true, 'science'),
(gen_random_uuid(), 'Las redes de comunicación son el sistema nervioso de la civilización moderna; su salud es nuestra salud.', 'Vint Cerf', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['wisdom','curiosity'], true, 'science'),

-- Albert Einstein (183–196)
(gen_random_uuid(), 'La imaginación es más importante que el conocimiento. El conocimiento es limitado; la imaginación rodea al mundo.', 'Albert Einstein', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['creativity','curiosity'], true, 'science'),
(gen_random_uuid(), 'La tecnología es maravillosa cuando sirve al ser humano; se convierte en amenaza cuando el ser humano la sirve.', 'Albert Einstein', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['wisdom','reflection'], true, 'science'),
(gen_random_uuid(), 'No podemos resolver los problemas de hoy con el mismo tipo de pensamiento que usamos cuando los creamos.', 'Albert Einstein', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['curiosity','wisdom'], true, 'science'),
(gen_random_uuid(), 'Si buscas resultados distintos, no hagas siempre lo mismo.', 'Albert Einstein', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['wisdom','courage'], true, 'science'),
(gen_random_uuid(), 'Lo más incomprensible del universo es que sea comprensible.', 'Albert Einstein', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['curiosity','wonder'], true, 'science'),
(gen_random_uuid(), 'Toda nuestra ciencia, medida en comparación con la realidad, es primitiva e infantil; y sin embargo es lo más precioso que tenemos.', 'Albert Einstein', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['curiosity','wisdom'], true, 'science'),
(gen_random_uuid(), 'La diferencia entre genialidad y estupidez es que la genialidad tiene sus límites.', 'Albert Einstein', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['wisdom','curiosity'], true, 'science'),
(gen_random_uuid(), 'La ciencia sin religión está coja; la religión sin ciencia está ciega.', 'Albert Einstein', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['wisdom','reflection'], true, 'science'),
(gen_random_uuid(), 'La creatividad es la inteligencia divirtiéndose.', 'Albert Einstein', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['creativity','curiosity'], true, 'science'),
(gen_random_uuid(), 'La física cuántica demuestra que la realidad es mucho más extraña de lo que nuestro sentido común puede aceptar.', 'Albert Einstein', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['curiosity','wonder'], true, 'science'),
(gen_random_uuid(), 'Una persona que nunca cometió un error nunca intentó nada nuevo.', 'Albert Einstein', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['courage','learning'], true, 'science'),
(gen_random_uuid(), 'El pensamiento puro puede captar la realidad, como los antiguos soñaban.', 'Albert Einstein', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['curiosity','wisdom'], true, 'science'),
(gen_random_uuid(), 'La revolución digital es, ante todo, una revolución del pensamiento; cambia cómo concebimos el mundo.', 'Albert Einstein', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['curiosity','wisdom'], true, 'science'),
(gen_random_uuid(), 'La energía no se crea ni se destruye; solo se transforma. La misma ley gobierna la información en la era digital.', 'Albert Einstein', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['curiosity','logic'], true, 'science'),

-- Stephen Hawking (197–210)
(gen_random_uuid(), 'La inteligencia es la capacidad de adaptarse al cambio.', 'Stephen Hawking', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['wisdom','learning'], true, 'science'),
(gen_random_uuid(), 'El mayor enemigo del conocimiento no es la ignorancia; es la ilusión del conocimiento.', 'Stephen Hawking', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['wisdom','curiosity'], true, 'science'),
(gen_random_uuid(), 'La IA podría ser el mayor logro de la humanidad o su último. Todo depende de cómo la controlemos.', 'Stephen Hawking', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['wisdom','courage'], true, 'science'),
(gen_random_uuid(), 'Por complicada que sea la vida, siempre hay algo que puedes hacer y en lo que puedes tener éxito.', 'Stephen Hawking', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['perseverance','courage'], true, 'science'),
(gen_random_uuid(), 'El universo no necesita a Dios para existir; pero nosotros necesitamos ciencia para comprenderlo.', 'Stephen Hawking', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['curiosity','wisdom'], true, 'science'),
(gen_random_uuid(), 'Recuerda mirar las estrellas y no tus pies. Intenta dar sentido a lo que ves.', 'Stephen Hawking', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['curiosity','wonder'], true, 'science'),
(gen_random_uuid(), 'La tecnología es neutral; lo que la convierte en herramienta o en arma es la intención humana.', 'Stephen Hawking', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['wisdom','reflection'], true, 'science'),
(gen_random_uuid(), 'Los agujeros negros no son prisiones eternas; la información siempre encuentra la manera de escapar.', 'Stephen Hawking', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['curiosity','wisdom'], true, 'science'),
(gen_random_uuid(), 'La colonización espacial no es opcional si queremos que la humanidad sobreviva más allá de este planeta.', 'Stephen Hawking', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['courage','wisdom'], true, 'science'),
(gen_random_uuid(), 'Las computadoras cuánticas procesarán información de maneras que escapan completamente a nuestra intuición clásica.', 'Stephen Hawking', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['curiosity','logic'], true, 'science'),
(gen_random_uuid(), 'Sin imperfección ni tú ni yo existiríamos; la vida misma es un error afortunado de la naturaleza.', 'Stephen Hawking', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['wisdom','curiosity'], true, 'science'),
(gen_random_uuid(), 'El universo comenzó con el Big Bang; la era digital comenzó con el primer bit. Ambos son puntos de no retorno.', 'Stephen Hawking', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['curiosity','wonder'], true, 'science'),
(gen_random_uuid(), 'La IA generativa es la herramienta más disruptiva desde la imprenta; su impacto tardará décadas en comprenderse.', 'Stephen Hawking', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['wisdom','curiosity'], true, 'science'),
(gen_random_uuid(), 'La humanidad sobrevivirá a sus propias tecnologías si aprende a usarlas con sabiduría y no solo con ambición.', 'Stephen Hawking', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['wisdom','courage'], true, 'science'),

-- Temáticos: IA y aprendizaje automático (211–220)
(gen_random_uuid(), 'La inteligencia artificial no reemplaza la creatividad humana; la amplifica y la libera de lo rutinario.', 'Alan Turing', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['creativity','wisdom'], true, 'science'),
(gen_random_uuid(), 'El aprendizaje automático es la ciencia de enseñar a las máquinas a aprender de la experiencia.', 'Arthur C. Clarke', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['learning','logic'], true, 'science'),
(gen_random_uuid(), 'Los algoritmos de IA son tan éticos como los datos con los que los entrenamos.', 'Grace Hopper', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['wisdom','logic'], true, 'science'),
(gen_random_uuid(), 'La IA generativa es el pincel más poderoso que la humanidad haya tenido; depende de nosotros lo que pintamos.', 'Ray Kurzweil', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['creativity','wisdom'], true, 'science'),
(gen_random_uuid(), 'Una red neuronal aprende patrones, no verdades; la diferencia importa más de lo que creemos.', 'Isaac Asimov', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['logic','wisdom'], true, 'science'),
(gen_random_uuid(), 'El deep learning ha demostrado que la inteligencia puede emerger de la estadística pura.', 'Alan Turing', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['curiosity','logic'], true, 'science'),
(gen_random_uuid(), 'Los modelos de lenguaje grande son la primera demostración práctica de inteligencia lingüística no humana.', 'Ray Kurzweil', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['curiosity','learning'], true, 'science'),
(gen_random_uuid(), 'La IA aprende de nuestros datos; si nuestros datos reflejan sesgos, la IA amplificará esos sesgos.', 'Tim Berners-Lee', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['wisdom','reflection'], true, 'science'),
(gen_random_uuid(), 'El aprendizaje por refuerzo enseña a las máquinas a través del fracaso repetido; hay mucho que los humanos podemos aprender de ese proceso.', 'Isaac Asimov', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['learning','perseverance'], true, 'science'),
(gen_random_uuid(), 'La computación cuántica y la IA juntas serán la mayor transformación tecnológica de la historia humana.', 'Stephen Hawking', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['curiosity','wisdom'], true, 'science'),

-- Temáticos: Internet y conectividad (221–230)
(gen_random_uuid(), 'Internet conectó las mentes del planeta; ahora la IA las amplificará. Nadie puede predecir el resultado.', 'Vint Cerf', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['curiosity','wisdom'], true, 'science'),
(gen_random_uuid(), 'La revolución de internet no fue tecnológica sino social: cambió cómo nos relacionamos, pensamos y creamos.', 'Tim Berners-Lee', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['wisdom','reflection'], true, 'science'),
(gen_random_uuid(), 'El WiFi es el nuevo oxígeno urbano; su ausencia se siente como una privación física.', 'Marshall McLuhan', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['curiosity','reflection'], true, 'science'),
(gen_random_uuid(), 'Las redes sociales son el espejo más honesto de la sociedad: muestran lo mejor y lo peor de nosotros simultáneamente.', 'Marc Andreessen', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['wisdom','reflection'], true, 'science'),
(gen_random_uuid(), 'El internet de las cosas convertirá cada objeto en un sensor inteligente; el mundo físico y digital serán uno.', 'Arthur C. Clarke', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['curiosity','learning'], true, 'science'),
(gen_random_uuid(), 'La brecha digital no es solo tecnológica; es una brecha de oportunidades que amenaza la equidad global.', 'Vint Cerf', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['wisdom','courage'], true, 'science'),
(gen_random_uuid(), 'El 5G no es solo velocidad; es la infraestructura sobre la que se construirá la próxima civilización digital.', 'Ray Kurzweil', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['curiosity','learning'], true, 'science'),
(gen_random_uuid(), 'Los datos masivos son la nueva geología: capas de información que revelan la historia del comportamiento humano.', 'Bill Gates', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['curiosity','wisdom'], true, 'science'),
(gen_random_uuid(), 'La computación en la nube democratizó el acceso a infraestructura que antes solo tenían los grandes.', 'Marc Andreessen', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['wisdom','learning'], true, 'science'),
(gen_random_uuid(), 'La velocidad de internet duplica capacidades humanas; lo que tomaba una vida ahora toma una tarde.', 'Bill Gates', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['learning','curiosity'], true, 'science'),

-- Temáticos: Robótica y automatización (231–238)
(gen_random_uuid(), 'Un robot bien diseñado no imita al humano; lo complementa haciendo lo que el humano no puede o no quiere hacer.', 'Isaac Asimov', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['wisdom','logic'], true, 'science'),
(gen_random_uuid(), 'La automatización no destruye empleos; destruye tareas. Los empleos del futuro aún no tienen nombre.', 'Bill Gates', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['wisdom','learning'], true, 'science'),
(gen_random_uuid(), 'Los cobots, robots colaborativos, son la prueba de que la relación entre humanos y máquinas puede ser simbiótica.', 'Arthur C. Clarke', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['curiosity','wisdom'], true, 'science'),
(gen_random_uuid(), 'La robótica quirúrgica ha hecho posible operaciones que ninguna mano humana, por hábil que sea, podría realizar.', 'Stephen Hawking', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['curiosity','perseverance'], true, 'science'),
(gen_random_uuid(), 'Automatizar la manufactura no es el fin del trabajo humano; es el comienzo del trabajo creativo masivo.', 'Elon Musk', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['wisdom','creativity'], true, 'science'),
(gen_random_uuid(), 'Los vehículos autónomos no solo cambiarán el transporte; cambiarán el urbanismo, la vivienda y el tiempo libre.', 'Elon Musk', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['curiosity','wisdom'], true, 'science'),
(gen_random_uuid(), 'La robótica de enjambre imita a la naturaleza: la inteligencia colectiva supera siempre a la individual.', 'Isaac Asimov', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['curiosity','logic'], true, 'science'),
(gen_random_uuid(), 'El exoesqueleto robótico es la primera prótesis que amplifica en vez de solo reemplazar; es el inicio del humano aumentado.', 'Ray Kurzweil', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['curiosity','wonder'], true, 'science'),

-- Temáticos: Tecnología espacial (239–244)
(gen_random_uuid(), 'La carrera espacial no terminó en la Luna; apenas comenzó. El sistema solar es el nuevo océano por explorar.', 'Elon Musk', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['curiosity','courage'], true, 'science'),
(gen_random_uuid(), 'Los telescopios espaciales son los ojos de la civilización mirando hacia su propio origen.', 'Stephen Hawking', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['curiosity','wonder'], true, 'science'),
(gen_random_uuid(), 'La propulsión iónica llevará a la humanidad a las estrellas; no con explosiones, sino con paciencia y física.', 'Arthur C. Clarke', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['curiosity','perseverance'], true, 'science'),
(gen_random_uuid(), 'Los satélites de observación terrestre son los centinelas que vigilan la salud de nuestro planeta en tiempo real.', 'Nikola Tesla', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['curiosity','wisdom'], true, 'science'),
(gen_random_uuid(), 'La minería de asteroides transformará la escasez de recursos en un problema del pasado si nos atrevemos a intentarlo.', 'Elon Musk', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['courage','curiosity'], true, 'science'),
(gen_random_uuid(), 'Terraformar Marte es el proyecto de ingeniería más ambicioso concebido por la mente humana; y es posible.', 'Arthur C. Clarke', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['courage','perseverance'], true, 'science'),

-- Temáticos: Energía renovable, biotecnología, ciberseguridad, RV (245–250)
(gen_random_uuid(), 'La energía solar es la democracia energética: el sol brilla para todos sin cobrar facturas.', 'Nikola Tesla', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['wisdom','curiosity'], true, 'science'),
(gen_random_uuid(), 'La biotecnología es la próxima revolución industrial: en lugar de moldeamos metales, moldeamos vida.', 'Ray Kurzweil', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['curiosity','wonder'], true, 'science'),
(gen_random_uuid(), 'La ciberseguridad es la higiene de la era digital; descuidarla es tan irresponsable como no lavarse las manos.', 'Vint Cerf', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['wisdom','logic'], true, 'science'),
(gen_random_uuid(), 'La realidad virtual no es un escape de la realidad; es una extensión de ella hacia territorios imposibles.', 'Arthur C. Clarke', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['creativity','wonder'], true, 'science'),
(gen_random_uuid(), 'La revolución digital es la mayor redistribución del poder cognitivo en la historia de la humanidad.', 'Marshall McLuhan', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['wisdom','curiosity'], true, 'science'),
(gen_random_uuid(), 'Innovar no es solo crear lo nuevo; es atreverse a destruir lo que funciona para construir lo que funciona mejor.', 'Steve Jobs', 'philosophy', 'es', 'down', 'free', false, 'science', 'technology', ARRAY['courage','creativity'], true, 'science')

ON CONFLICT (text, author) DO NOTHING;

COMMIT;
