-- 041_coding_frontend_es.sql
-- MindScrolling — Coding Mode: Frontend batch (Spanish)
-- 250 citas: diseño UI/UX, diseño responsivo, accesibilidad, CSS, JavaScript,
--   estándares web, animaciones, tipografía, sistemas de diseño,
--   arquitectura de componentes, mobile-first, experiencia de usuario
--
-- All rows:
--   category       = 'philosophy'
--   lang           = 'es'
--   swipe_dir      = 'down'
--   pack_name      = 'free'
--   is_premium     = false
--   content_type   = 'coding'
--   sub_category   = 'frontend'
--   is_hidden_mode = true
--   locked_by      = 'coding'
-- Run in Supabase SQL Editor

BEGIN;

-- ══════════════════════════════════════════════════════════════════════════════
-- CODING FRONTEND — SPANISH (250 citas)
-- ══════════════════════════════════════════════════════════════════════════════

INSERT INTO quotes (id, text, author, category, lang, swipe_dir, pack_name, is_premium, content_type, sub_category, tags, is_hidden_mode, locked_by) VALUES

-- Steve Jobs (1–14)
(gen_random_uuid(), 'El diseño no es solo cómo se ve y cómo se siente. El diseño es cómo funciona.', 'Steve Jobs', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['creativity', 'focus'], true, 'coding'),
(gen_random_uuid(), 'La simplicidad es la máxima sofisticación.', 'Steve Jobs', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['creativity', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'Las personas que están suficientemente locas como para creer que pueden cambiar el mundo son quienes lo cambian.', 'Steve Jobs', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['courage', 'creativity'], true, 'coding'),
(gen_random_uuid(), 'La creatividad es simplemente conectar cosas. Los creativos son capaces de sintetizar experiencias que otros no han tenido.', 'Steve Jobs', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['creativity', 'wisdom'], true, 'coding'),
(gen_random_uuid(), 'El enfoque consiste en decir no a cien buenas ideas para poder concentrarse en la que realmente importa.', 'Steve Jobs', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['focus', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'Tu tiempo es limitado. No lo desperdicies viviendo la vida de otra persona.', 'Steve Jobs', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['courage', 'wisdom'], true, 'coding'),
(gen_random_uuid(), 'La innovación distingue a un líder de un seguidor.', 'Steve Jobs', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['creativity', 'courage'], true, 'coding'),
(gen_random_uuid(), 'Los detalles importan. Vale la pena esperar hasta hacerlos bien.', 'Steve Jobs', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['discipline', 'focus'], true, 'coding'),
(gen_random_uuid(), 'El buen diseño es en realidad mucho más difícil de notar que el mal diseño, en parte porque el buen diseño se adapta a nuestras necesidades.', 'Steve Jobs', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['creativity', 'wisdom'], true, 'coding'),
(gen_random_uuid(), 'Cuando empezas a diseñar algo, tienes que conocer al usuario como a ti mismo.', 'Steve Jobs', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['focus', 'wisdom'], true, 'coding'),
(gen_random_uuid(), 'La calidad es más importante que la cantidad. Un home run es mejor que dos dobles.', 'Steve Jobs', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['discipline', 'wisdom'], true, 'coding'),
(gen_random_uuid(), 'Diseñar es la expresión fundamental del alma humana que emerge a través del artesano.', 'Steve Jobs', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['creativity', 'wisdom'], true, 'coding'),
(gen_random_uuid(), 'El arte más grande es hacer que algo complicado sea increíblemente simple.', 'Steve Jobs', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['creativity', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'No se puede conectar los puntos mirando hacia adelante, solo se pueden conectar mirando hacia atrás.', 'Steve Jobs', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'courage'], true, 'coding'),

-- Tim Berners-Lee (15–26)
(gen_random_uuid(), 'La web no es para mí. La web es para todo el mundo.', 'Tim Berners-Lee', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'creativity'], true, 'coding'),
(gen_random_uuid(), 'El poder de la web está en su universalidad. El acceso para todos, independientemente de la discapacidad, es un aspecto esencial.', 'Tim Berners-Lee', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'Los datos son una cosa preciosa y durarán más que los sistemas en sí mismos.', 'Tim Berners-Lee', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'focus'], true, 'coding'),
(gen_random_uuid(), 'La web tal como la conocemos es solo un estado embrionario de lo que será.', 'Tim Berners-Lee', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['curiosity', 'wisdom'], true, 'coding'),
(gen_random_uuid(), 'Cuando uno diseña para la web, diseña para todos: ciegos, sordos, con movilidad reducida. La accesibilidad no es opcional.', 'Tim Berners-Lee', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'HTTP no es una tecnología de una sola dirección. Es un protocolo de diálogo entre cliente y servidor.', 'Tim Berners-Lee', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['learning', 'wisdom'], true, 'coding'),
(gen_random_uuid(), 'Los estándares abiertos son la base de una web libre. Sin ellos, la web se fragmenta en jardines vallados.', 'Tim Berners-Lee', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'La semántica en HTML no es burocracia. Es el contrato entre el autor y la máquina.', 'Tim Berners-Lee', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['discipline', 'wisdom'], true, 'coding'),
(gen_random_uuid(), 'Una URL bien formada es la promesa de que un recurso existirá en ese lugar. Rómpela y pierdes confianza.', 'Tim Berners-Lee', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['discipline', 'wisdom'], true, 'coding'),
(gen_random_uuid(), 'Vincular no es robar. Vincular es el corazón mismo de la web.', 'Tim Berners-Lee', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'creativity'], true, 'coding'),
(gen_random_uuid(), 'Diseñar la web es diseñar para la humanidad entera, con toda su diversidad de capacidades y contextos.', 'Tim Berners-Lee', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'creativity'], true, 'coding'),
(gen_random_uuid(), 'El HTML es el lienzo de la web. Su estructura define lo que la experiencia puede llegar a ser.', 'Tim Berners-Lee', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['creativity', 'discipline'], true, 'coding'),

-- Jeffrey Zeldman (27–38)
(gen_random_uuid(), 'El contenido precede al diseño. El diseño en ausencia de contenido no es diseño, es decoración.', 'Jeffrey Zeldman', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'Los estándares web no son reglas del gobierno. Son acuerdos que permiten que la web funcione para todos.', 'Jeffrey Zeldman', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'El diseño web no es sobre imponer tu visión al mundo. Es sobre servir a tu audiencia.', 'Jeffrey Zeldman', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'focus'], true, 'coding'),
(gen_random_uuid(), 'La separación entre estructura, presentación y comportamiento no es una regla arbitraria. Es la arquitectura de la web.', 'Jeffrey Zeldman', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['discipline', 'wisdom'], true, 'coding'),
(gen_random_uuid(), 'Un sitio web mal codificado puede funcionar hoy. Un sitio web bien codificado funcionará durante años.', 'Jeffrey Zeldman', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['discipline', 'wisdom'], true, 'coding'),
(gen_random_uuid(), 'El HTML semántico es legible por humanos y por máquinas. Esa dualidad es su poder.', 'Jeffrey Zeldman', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'learning'], true, 'coding'),
(gen_random_uuid(), 'Cuando el código es la interfaz, la claridad del código es la claridad de la experiencia.', 'Jeffrey Zeldman', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['discipline', 'focus'], true, 'coding'),
(gen_random_uuid(), 'Diseñar con estándares no limita la creatividad. La libera al establecer una base confiable.', 'Jeffrey Zeldman', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['creativity', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'La tipografía en la web ha madurado. Ya no hay excusa para usar texto sin considerar la jerarquía visual.', 'Jeffrey Zeldman', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['creativity', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'Cada capa de la web —HTML, CSS, JavaScript— tiene su responsabilidad. Respétala y el sistema escala.', 'Jeffrey Zeldman', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['discipline', 'wisdom'], true, 'coding'),
(gen_random_uuid(), 'El mejor diseño web es invisible. El usuario alcanza su objetivo sin pensar en la interfaz.', 'Jeffrey Zeldman', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'focus'], true, 'coding'),
(gen_random_uuid(), 'Construir para la web es construir para el público más diverso que existe. Esa responsabilidad es enorme.', 'Jeffrey Zeldman', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'courage'], true, 'coding'),

-- Dan Abramov (39–51)
(gen_random_uuid(), 'Los componentes son la unidad de reutilización en la UI. Cuando están bien diseñados, el sistema se escala solo.', 'Dan Abramov', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['discipline', 'wisdom'], true, 'coding'),
(gen_random_uuid(), 'El estado local es poderoso, pero el estado global es peligroso. Usa solo el estado que necesitas donde lo necesitas.', 'Dan Abramov', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['discipline', 'focus'], true, 'coding'),
(gen_random_uuid(), 'Los efectos secundarios son la principal fuente de complejidad en las interfaces. Aislarlos es la mitad de la batalla.', 'Dan Abramov', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['discipline', 'wisdom'], true, 'coding'),
(gen_random_uuid(), 'El modelo mental correcto de los hooks es que describen sincronización, no ciclos de vida.', 'Dan Abramov', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['learning', 'wisdom'], true, 'coding'),
(gen_random_uuid(), 'Los componentes controlados dan al desarrollador el control total del flujo de datos. Úsalos cuando necesites predecibilidad.', 'Dan Abramov', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['discipline', 'focus'], true, 'coding'),
(gen_random_uuid(), 'Un componente bien diseñado hace una sola cosa y la hace perfectamente. El principio de responsabilidad única aplica al frontend.', 'Dan Abramov', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['discipline', 'wisdom'], true, 'coding'),
(gen_random_uuid(), 'Renderizar es barato. El problema es cuando renderizas de más. Mide antes de optimizar.', 'Dan Abramov', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['discipline', 'wisdom'], true, 'coding'),
(gen_random_uuid(), 'La composición es más flexible que la herencia para construir interfaces de usuario. Compón en lugar de extender.', 'Dan Abramov', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['creativity', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'Si necesitas leer el estado justo antes de un efecto, ese estado debería ser una dependencia del efecto.', 'Dan Abramov', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['learning', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'Las abstracciones prematuras en UI son peores que el código repetido. Espera ver el patrón tres veces antes de abstraer.', 'Dan Abramov', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'El flujo de datos en una sola dirección hace que el comportamiento de la UI sea predecible y fácil de depurar.', 'Dan Abramov', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['discipline', 'focus'], true, 'coding'),
(gen_random_uuid(), 'Separar la lógica de la presentación no es una sugerencia de estilo. Es la diferencia entre código mantenible y código frágil.', 'Dan Abramov', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['discipline', 'wisdom'], true, 'coding'),
(gen_random_uuid(), 'Los errores en producción son costosos. Escribir pruebas para comportamientos de UI es inversión, no gasto.', 'Dan Abramov', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['discipline', 'wisdom'], true, 'coding'),

-- Don Norman (52–63)
(gen_random_uuid(), 'El diseño centrado en el ser humano comienza con entender a las personas, no con imaginar soluciones.', 'Don Norman', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'focus'], true, 'coding'),
(gen_random_uuid(), 'Cuando algo sale mal, la culpa es del diseño, no del usuario. Los errores del usuario son errores del diseñador.', 'Don Norman', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'La affordance es la relación entre un objeto y quien lo usa. Un botón debe verse como algo que se presiona.', 'Don Norman', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'creativity'], true, 'coding'),
(gen_random_uuid(), 'El feedback inmediato es fundamental. Sin retroalimentación, el usuario no sabe si su acción fue registrada.', 'Don Norman', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'focus'], true, 'coding'),
(gen_random_uuid(), 'La visibilidad de las acciones posibles reduce la carga cognitiva. Muestra lo que se puede hacer, no lo que se hizo.', 'Don Norman', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'Los modelos conceptuales malos generan confusión. El diseñador debe alinear el modelo del sistema con el modelo del usuario.', 'Don Norman', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'learning'], true, 'coding'),
(gen_random_uuid(), 'La emoción en el diseño no es opcional. El diseño emocional crea apego y fidelidad que el diseño funcional no puede lograr solo.', 'Don Norman', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['creativity', 'wisdom'], true, 'coding'),
(gen_random_uuid(), 'Dos errores de diseño son peores que uno: el primero confunde, el segundo convence al usuario de que es torpe.', 'Don Norman', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'El buen diseño hace que las cosas complejas parezcan simples sin esconder la complejidad que el usuario necesita controlar.', 'Don Norman', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'creativity'], true, 'coding'),
(gen_random_uuid(), 'Observa cómo las personas usan realmente tu producto. Sus acciones son más honestas que sus palabras.', 'Don Norman', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'curiosity'], true, 'coding'),
(gen_random_uuid(), 'La consistencia en el diseño crea expectativas. Romper esas expectativas tiene un costo cognitivo que el usuario paga.', 'Don Norman', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['discipline', 'wisdom'], true, 'coding'),
(gen_random_uuid(), 'El diseño es resolver problemas de personas. No es decorar superficies.', 'Don Norman', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'focus'], true, 'coding'),

-- Jared Spool (64–74)
(gen_random_uuid(), 'El diseño es la intención detrás del resultado. Sin intención clara, el resultado es accidente.', 'Jared Spool', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'Buenos diseñadores investigan. Grandes diseñadores investigan continuamente y nunca asumen que ya conocen al usuario.', 'Jared Spool', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['curiosity', 'wisdom'], true, 'coding'),
(gen_random_uuid(), 'Las pruebas de usabilidad con cinco usuarios revelan el 85% de los problemas de diseño. No necesitas más datos, necesitas actuar.', 'Jared Spool', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'Un diseño que necesita instrucciones es un diseño que ha fallado. La interfaz debe ser su propio manual.', 'Jared Spool', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'focus'], true, 'coding'),
(gen_random_uuid(), 'La experiencia de usuario no es solo la pantalla que el usuario ve. Es todo lo que el usuario siente antes, durante y después.', 'Jared Spool', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'creativity'], true, 'coding'),
(gen_random_uuid(), 'El error más costoso en UX es construir la solución correcta para el problema equivocado.', 'Jared Spool', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'La empatía no es ponerse en los zapatos del usuario. Es entender el camino que el usuario recorre con esos zapatos.', 'Jared Spool', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'curiosity'], true, 'coding'),
(gen_random_uuid(), 'Cuando el diseño falla, los usuarios se culpan a sí mismos. Cuando el diseño funciona, los usuarios se sienten inteligentes.', 'Jared Spool', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'creativity'], true, 'coding'),
(gen_random_uuid(), 'Los microtextos importan tanto como el diseño visual. Las palabras en una interfaz son diseño.', 'Jared Spool', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['discipline', 'wisdom'], true, 'coding'),
(gen_random_uuid(), 'No puedes diseñar para la experiencia del usuario sin salir de la oficina y observar al usuario.', 'Jared Spool', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['curiosity', 'wisdom'], true, 'coding'),
(gen_random_uuid(), 'El diseño centrado en datos y el diseño centrado en el usuario no son opuestos. Son complementarios.', 'Jared Spool', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'discipline'], true, 'coding'),

-- Alan Cooper (75–85)
(gen_random_uuid(), 'Las personas como nosotros son los mejores aprendices sobre las personas como nosotros. El diseñador debe salir de sí mismo.', 'Alan Cooper', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'curiosity'], true, 'coding'),
(gen_random_uuid(), 'Las personas-persona no son datos demográficos. Son arquetipos comportamentales que guían decisiones de diseño concretas.', 'Alan Cooper', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'learning'], true, 'coding'),
(gen_random_uuid(), 'El diseño de interacción existe para servir objetivos humanos, no para demostrar poder tecnológico.', 'Alan Cooper', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'focus'], true, 'coding'),
(gen_random_uuid(), 'La mayoría del software está diseñado para complacer al programador, no al usuario. Esa es la raíz del problema.', 'Alan Cooper', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'El software debería comportarse como un asistente inteligente que entiende el contexto, no como una máquina estúpida.', 'Alan Cooper', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'creativity'], true, 'coding'),
(gen_random_uuid(), 'Diseñar primero, codificar después. El orden importa. La implementación no debería guiar el diseño.', 'Alan Cooper', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['discipline', 'wisdom'], true, 'coding'),
(gen_random_uuid(), 'La danza entre el usuario y el sistema es la interacción. El diseñador coreografía esa danza.', 'Alan Cooper', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['creativity', 'wisdom'], true, 'coding'),
(gen_random_uuid(), 'Un sistema que obliga al usuario a pensar en su funcionamiento interno ha fracasado como herramienta.', 'Alan Cooper', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'focus'], true, 'coding'),
(gen_random_uuid(), 'Los usuarios no cometen errores. Los sistemas cometen errores al no anticipar el comportamiento del usuario.', 'Alan Cooper', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'El diseño de interacción bien hecho es invisible. Los usuarios están ocupados logrando sus objetivos, no admirando tu trabajo.', 'Alan Cooper', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'focus'], true, 'coding'),
(gen_random_uuid(), 'La funcionalidad excesiva sin estructura de navegación coherente abruma al usuario. Menos opciones, mejor diseño.', 'Alan Cooper', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['discipline', 'wisdom'], true, 'coding'),

-- Edward Tufte (86–96)
(gen_random_uuid(), 'La excelencia en la visualización estadística consiste en mostrar los datos. Por encima de todo, comunica los datos.', 'Edward Tufte', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['discipline', 'wisdom'], true, 'coding'),
(gen_random_uuid(), 'La tinta de datos es la tinta que vale. El resto es ruido visual que debe eliminarse.', 'Edward Tufte', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['discipline', 'focus'], true, 'coding'),
(gen_random_uuid(), 'Chartjunk no solo es feo, es mentiroso. Distorsiona los datos que pretende representar.', 'Edward Tufte', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['discipline', 'wisdom'], true, 'coding'),
(gen_random_uuid(), 'La densidad de información no equivale a complejidad. Mucha información bien organizada es más clara que poca información mal presentada.', 'Edward Tufte', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'Las interfaces de pantalla pequeña no deben simplificar la información. Deben densificarla con mayor precisión.', 'Edward Tufte', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['discipline', 'focus'], true, 'coding'),
(gen_random_uuid(), 'El espacio en blanco no es espacio vacío. Es el silencio que hace que la información pueda ser escuchada.', 'Edward Tufte', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['creativity', 'wisdom'], true, 'coding'),
(gen_random_uuid(), 'La tipografía pequeña y densa, bien diseñada, transmite más información con menos distracciones que la tipografía grande y vaga.', 'Edward Tufte', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['discipline', 'wisdom'], true, 'coding'),
(gen_random_uuid(), 'Presentar evidencia visual es siempre un acto de persuasión. Diseña con honestidad o no diseñes.', 'Edward Tufte', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'courage'], true, 'coding'),
(gen_random_uuid(), 'El diseño de interfaz debe revelar la estructura de los datos, no ocultarla detrás de ornamentos.', 'Edward Tufte', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['discipline', 'wisdom'], true, 'coding'),
(gen_random_uuid(), 'Comparar es la operación cognitiva más poderosa. Diseña interfaces que faciliten la comparación.', 'Edward Tufte', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'Las buenas visualizaciones no solo muestran datos. Provocan preguntas sobre los datos.', 'Edward Tufte', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['curiosity', 'wisdom'], true, 'coding'),

-- Dieter Rams (97–107)
(gen_random_uuid(), 'El buen diseño es tan poco diseño como sea posible. Menos pero mejor.', 'Dieter Rams', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['discipline', 'wisdom'], true, 'coding'),
(gen_random_uuid(), 'El buen diseño es innovador. Nunca lo hace todo por sí solo, pero siempre está ligado al desarrollo tecnológico.', 'Dieter Rams', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['creativity', 'wisdom'], true, 'coding'),
(gen_random_uuid(), 'El buen diseño hace útil a un producto. El buen diseño hace valioso a un producto. No son lo mismo.', 'Dieter Rams', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'focus'], true, 'coding'),
(gen_random_uuid(), 'El buen diseño es honesto. No hace al producto parecer más innovador, poderoso o valioso de lo que realmente es.', 'Dieter Rams', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'El buen diseño es discreto. Los productos que cumplen un propósito son como herramientas. No son objetos decorativos ni obras de arte.', 'Dieter Rams', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['discipline', 'wisdom'], true, 'coding'),
(gen_random_uuid(), 'El buen diseño es duradero. Evita estar a la moda y por ello nunca parece anticuado.', 'Dieter Rams', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'El buen diseño es meticuloso hasta el último detalle. Nada debe ser arbitrario o dejado al azar.', 'Dieter Rams', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['discipline', 'focus'], true, 'coding'),
(gen_random_uuid(), 'El buen diseño es respetuoso con el medio ambiente. Contribuye a la preservación del entorno.', 'Dieter Rams', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'Pregúntate si el diseño que estás viendo es realmente necesario. Indiferencia hacia el desorden es una virtud de diseñador.', 'Dieter Rams', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['discipline', 'wisdom'], true, 'coding'),
(gen_random_uuid(), 'Los buenos diseñadores deben ser eternamente insatisfechos. La perfección no existe, pero la búsqueda de ella refina el trabajo.', 'Dieter Rams', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['discipline', 'courage'], true, 'coding'),
(gen_random_uuid(), 'Los colores, formas y materiales en el diseño no deben afirmarse a sí mismos. Deben servir a la función.', 'Dieter Rams', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['discipline', 'wisdom'], true, 'coding'),

-- Jakob Nielsen (108–119)
(gen_random_uuid(), 'La usabilidad no es un lujo de grandes empresas. Es la condición mínima para que un producto digital tenga sentido.', 'Jakob Nielsen', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'Cero distracciones, cero ambigüedad, cero fricción. Esos son los tres pilares de una experiencia de usuario excelente.', 'Jakob Nielsen', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['discipline', 'focus'], true, 'coding'),
(gen_random_uuid(), 'La visibilidad del estado del sistema es la primera heurística del diseño. El usuario siempre debe saber qué está pasando.', 'Jakob Nielsen', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'El lenguaje del sistema debe coincidir con el lenguaje del usuario. Los términos técnicos internos no pertenecen a la interfaz.', 'Jakob Nielsen', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'focus'], true, 'coding'),
(gen_random_uuid(), 'Los usuarios deben poder deshacer y rehacer. Sin esa posibilidad, cada acción tiene un costo de ansiedad.', 'Jakob Nielsen', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'La consistencia y los estándares reducen la carga de aprendizaje. Los usuarios no deberían preguntarse si diferentes palabras significan lo mismo.', 'Jakob Nielsen', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['discipline', 'wisdom'], true, 'coding'),
(gen_random_uuid(), 'Prevenir errores es mejor que diseñar buenos mensajes de error. La mejor interfaz de error es la que nunca aparece.', 'Jakob Nielsen', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'El reconocimiento siempre supera al recuerdo en diseño de interfaces. Muestra las opciones, no obligues a memorizar.', 'Jakob Nielsen', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'focus'], true, 'coding'),
(gen_random_uuid(), 'La eficiencia de uso para usuarios expertos puede diferir de la facilidad de aprendizaje. Diseña para ambos niveles.', 'Jakob Nielsen', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'Los mensajes de error deben expresar el problema en lenguaje claro, indicar el problema con precisión y sugerir una solución.', 'Jakob Nielsen', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['discipline', 'focus'], true, 'coding'),
(gen_random_uuid(), 'La ayuda y la documentación no deberían ser necesarias, pero cuando lo son, deben ser fáciles de encontrar y orientadas a la tarea.', 'Jakob Nielsen', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'Un diseño con demasiada información compite consigo mismo. La densidad sin jerarquía no es información, es ruido.', 'Jakob Nielsen', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['discipline', 'wisdom'], true, 'coding'),

-- Douglas Crockford (120–130)
(gen_random_uuid(), 'JavaScript tiene partes buenas y partes malas. Un buen programador solo usa las partes buenas.', 'Douglas Crockford', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['discipline', 'wisdom'], true, 'coding'),
(gen_random_uuid(), 'El código que no entiendes es código que no puedes mantener. La claridad supera a la astucia siempre.', 'Douglas Crockford', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'JSON no fue inventado. Fue descubierto. Siempre estuvo en JavaScript, esperando ser usado correctamente.', 'Douglas Crockford', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'curiosity'], true, 'coding'),
(gen_random_uuid(), 'El ámbito de función en JavaScript no es un defecto. Es una característica poderosa que los buenos programadores dominan.', 'Douglas Crockford', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['learning', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'Los cierres en JavaScript son la característica más poderosa del lenguaje. También la más malentendida.', 'Douglas Crockford', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['learning', 'wisdom'], true, 'coding'),
(gen_random_uuid(), 'Un lenguaje que no cambia la forma en que piensas sobre la programación no vale la pena aprenderlo.', 'Douglas Crockford', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['learning', 'curiosity'], true, 'coding'),
(gen_random_uuid(), 'La herencia prototipal de JavaScript es más poderosa que la herencia clásica. Solo requiere comprenderla correctamente.', 'Douglas Crockford', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['learning', 'wisdom'], true, 'coding'),
(gen_random_uuid(), 'Evita la coerción implícita en JavaScript. Cuando el lenguaje convierte tipos por ti, el resultado puede sorprenderte.', 'Douglas Crockford', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['discipline', 'wisdom'], true, 'coding'),
(gen_random_uuid(), 'El código debe ser escrito para que lo lean los humanos, y solo incidentalmente para que lo ejecuten las máquinas.', 'Douglas Crockford', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'La seguridad en JavaScript comienza por entender el modelo de seguridad del navegador. No construyas sobre suposiciones falsas.', 'Douglas Crockford', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['discipline', 'wisdom'], true, 'coding'),
(gen_random_uuid(), 'La mayoría de los errores en programación son errores de comprensión, no errores de escritura. Lee más código del que escribes.', 'Douglas Crockford', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'learning'], true, 'coding'),

-- Brendan Eich (131–141)
(gen_random_uuid(), 'JavaScript fue diseñado en diez días, pero ha evolucionado durante décadas. La evolución supera al diseño original.', 'Brendan Eich', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'curiosity'], true, 'coding'),
(gen_random_uuid(), 'Siempre aposté por la web. Incluso cuando todos decían que los plugins nativos ganarían. La web fue más resistente.', 'Brendan Eich', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['courage', 'wisdom'], true, 'coding'),
(gen_random_uuid(), 'Los lenguajes de programación son herramientas. Una herramienta bien afilada puede construir cosas hermosas aunque tenga una historia complicada.', 'Brendan Eich', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'La semántica de JavaScript se puede aprender. Lo que no tiene solución es no tomarse el tiempo para aprenderla.', 'Brendan Eich', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['learning', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'WebAssembly no reemplaza a JavaScript. Le da a JavaScript compañía para los casos en que el rendimiento nativo importa.', 'Brendan Eich', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['learning', 'wisdom'], true, 'coding'),
(gen_random_uuid(), 'El estándar ECMAScript es una promesa pública. Cada versión es un compromiso de compatibilidad que no puede romperse.', 'Brendan Eich', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['discipline', 'wisdom'], true, 'coding'),
(gen_random_uuid(), 'Mover rápido y romper cosas funciona en un laboratorio. En la web, rompes a los usuarios.', 'Brendan Eich', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'La retrocompatibilidad en la web es sagrada. Millones de páginas dependen de que el comportamiento de ayer funcione mañana.', 'Brendan Eich', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['discipline', 'wisdom'], true, 'coding'),
(gen_random_uuid(), 'JavaScript es funcional y orientado a objetos al mismo tiempo. Esa dualidad es una fortaleza, no una contradicción.', 'Brendan Eich', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'learning'], true, 'coding'),
(gen_random_uuid(), 'El DOM es la interfaz entre JavaScript y el HTML. Manipularlo con eficiencia es el primer paso hacia el rendimiento en el navegador.', 'Brendan Eich', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['learning', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'Las promesas en JavaScript transformaron la programación asíncrona. Antes había callbacks. Ahora hay composición.', 'Brendan Eich', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['learning', 'wisdom'], true, 'coding'),

-- Paul Graham (142–152)
(gen_random_uuid(), 'Los hackers y los pintores tienen mucho en común. Lo más importante: nunca dejan de aprender.', 'Paul Graham', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'learning'], true, 'coding'),
(gen_random_uuid(), 'El gusto se desarrolla exponiéndose a buen trabajo. Observa interfaces hermosas y aprende a distinguirlas de las mediocres.', 'Paul Graham', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['creativity', 'wisdom'], true, 'coding'),
(gen_random_uuid(), 'Las startups que ganan en diseño ganan por completo. Los usuarios no saben por qué un buen diseño se siente mejor, simplemente lo saben.', 'Paul Graham', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['creativity', 'wisdom'], true, 'coding'),
(gen_random_uuid(), 'El buen diseño parece sin esfuerzo. Ese esfuerzo aparente es ganado con un enorme trabajo detrás de escena.', 'Paul Graham', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['creativity', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'Los mejores programadores piensan como diseñadores. Quieren que su código sea no solo correcto, sino elegante.', 'Paul Graham', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['creativity', 'wisdom'], true, 'coding'),
(gen_random_uuid(), 'Construir algo que la gente quiere es el primer principio del diseño de producto. Todo lo demás viene después.', 'Paul Graham', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['focus', 'wisdom'], true, 'coding'),
(gen_random_uuid(), 'La ambigüedad es el enemigo del diseño. Cuando una interfaz puede interpretarse de dos maneras, los usuarios elegirán la equivocada.', 'Paul Graham', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'La característica más importante en un programador no es el conocimiento técnico, sino la curiosidad.', 'Paul Graham', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['curiosity', 'wisdom'], true, 'coding'),
(gen_random_uuid(), 'Las mejores ideas nacen de notar anomalías: cosas extrañas que te hacen preguntarte qué está pasando realmente.', 'Paul Graham', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['curiosity', 'creativity'], true, 'coding'),
(gen_random_uuid(), 'Escribe código que puedas entender seis meses después. Si no puedes, ya has fallado a tu yo futuro.', 'Paul Graham', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['discipline', 'wisdom'], true, 'coding'),
(gen_random_uuid(), 'El prototipo feo que resuelve el problema real vale más que el diseño hermoso que resuelve el problema equivocado.', 'Paul Graham', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'focus'], true, 'coding'),

-- Kent Beck (153–162)
(gen_random_uuid(), 'Haz que funcione. Haz que sea correcto. Haz que sea rápido. En ese orden, sin excepciones.', 'Kent Beck', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['discipline', 'wisdom'], true, 'coding'),
(gen_random_uuid(), 'El código limpio no es código sin comentarios. Es código que no necesita comentarios para ser entendido.', 'Kent Beck', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['discipline', 'wisdom'], true, 'coding'),
(gen_random_uuid(), 'Las pruebas no son una red de seguridad. Son una especificación ejecutable de lo que el sistema debe hacer.', 'Kent Beck', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['discipline', 'focus'], true, 'coding'),
(gen_random_uuid(), 'Refactorizar sin pruebas es como arreglar un avión en vuelo sin cinturón de seguridad. Puede salir bien, pero no lo recomiendo.', 'Kent Beck', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['discipline', 'courage'], true, 'coding'),
(gen_random_uuid(), 'La simplicidad del diseño no es falta de ambición. Es la máxima ambición: hacer lo complejo parecer obvio.', 'Kent Beck', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'creativity'], true, 'coding'),
(gen_random_uuid(), 'La deuda técnica tiene intereses. Si no la pagas, algún día el interés supera al capital y el sistema colapsa.', 'Kent Beck', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['discipline', 'wisdom'], true, 'coding'),
(gen_random_uuid(), 'Los patrones de diseño son el vocabulario compartido de los ingenieros. Hablar en patrones acelera la comunicación.', 'Kent Beck', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'learning'], true, 'coding'),
(gen_random_uuid(), 'El feedback rápido es el principio central del desarrollo ágil. Si no sabes pronto si algo funciona, corriges tarde.', 'Kent Beck', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['discipline', 'wisdom'], true, 'coding'),
(gen_random_uuid(), 'Pequeños pasos seguros llevan más lejos que grandes saltos peligrosos. En código, en diseño, en vida.', 'Kent Beck', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['discipline', 'wisdom'], true, 'coding'),
(gen_random_uuid(), 'El código duplicado es la raíz de casi todos los males. Duplícalo una vez si debes, pero abstrae a la segunda repetición.', 'Kent Beck', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['discipline', 'wisdom'], true, 'coding'),

-- Martin Fowler (163–172)
(gen_random_uuid(), 'Cualquier tonto puede escribir código que entiende una computadora. Los buenos programadores escriben código que entienden los humanos.', 'Martin Fowler', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'La refactorización es el proceso de mejorar el diseño del código existente sin cambiar su comportamiento externo.', 'Martin Fowler', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['discipline', 'learning'], true, 'coding'),
(gen_random_uuid(), 'El código mal estructurado no es un problema de rendimiento. Es un problema de comunicación. Comunica mal la intención.', 'Martin Fowler', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['discipline', 'wisdom'], true, 'coding'),
(gen_random_uuid(), 'La arquitectura no es sobre los diagramas. Es sobre las decisiones que hacen que algunos cambios sean fáciles y otros difíciles.', 'Martin Fowler', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'Si algo duele, hazlo con más frecuencia. Si los despliegues son dolorosos, despliega más seguido hasta que no duelan.', 'Martin Fowler', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['courage', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'Los microservicios no son la respuesta a todos los problemas. A veces un monolito bien estructurado es la solución correcta.', 'Martin Fowler', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'Una interfaz bien diseñada oculta la complejidad de su implementación. Una interfaz mal diseñada la expone.', 'Martin Fowler', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['discipline', 'wisdom'], true, 'coding'),
(gen_random_uuid(), 'El testing de componentes de UI verifica el contrato entre el componente y el sistema. Sin ese contrato, la integración es frágil.', 'Martin Fowler', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['discipline', 'focus'], true, 'coding'),
(gen_random_uuid(), 'Los cambios frecuentes a pequeña escala reducen el riesgo. Los cambios grandes e infrecuentes lo concentran.', 'Martin Fowler', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['discipline', 'wisdom'], true, 'coding'),
(gen_random_uuid(), 'El diseño emergente surge de refactorizar continuamente con buen criterio. No planifiques la arquitectura; cultívala.', 'Martin Fowler', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'creativity'], true, 'coding'),

-- Addy Osmani (173–184)
(gen_random_uuid(), 'Primero resuelve el problema. Luego escribe el código. Luego optimiza. El orden importa.', 'Addy Osmani', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['discipline', 'wisdom'], true, 'coding'),
(gen_random_uuid(), 'El rendimiento es una funcionalidad. Presiupuesta para él igual que para cualquier otra funcionalidad.', 'Addy Osmani', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['discipline', 'focus'], true, 'coding'),
(gen_random_uuid(), 'JavaScript tiene un costo. Parsear, compilar y ejecutar llevan tiempo. Envía menos JavaScript.', 'Addy Osmani', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['discipline', 'wisdom'], true, 'coding'),
(gen_random_uuid(), 'La carga diferida no es una optimización. Es un principio. Carga lo que se necesita, cuando se necesita.', 'Addy Osmani', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['discipline', 'focus'], true, 'coding'),
(gen_random_uuid(), 'RAIL: Respuesta, Animación, Inactivo, Carga. Esos son los cuatro pilares del rendimiento percibido.', 'Addy Osmani', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['discipline', 'learning'], true, 'coding'),
(gen_random_uuid(), 'Los patrones de diseño resuelven problemas recurrentes. Usarlos es alfabetismo de ingeniería de software.', 'Addy Osmani', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'learning'], true, 'coding'),
(gen_random_uuid(), 'Construye, mide, aprende. Aplica ese ciclo de retroalimentación al rendimiento con el mismo rigor que a las funcionalidades.', 'Addy Osmani', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['discipline', 'wisdom'], true, 'coding'),
(gen_random_uuid(), 'Los service workers desbloquean experiencias offline-first. Las aplicaciones web progresivas comienzan aquí.', 'Addy Osmani', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['learning', 'creativity'], true, 'coding'),
(gen_random_uuid(), 'Automatiza lo que pueda ser automatizado. Cada paso de compilación manual es una deuda operacional.', 'Addy Osmani', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['discipline', 'focus'], true, 'coding'),
(gen_random_uuid(), 'Los web components llevan la reutilización al nivel de la plataforma. Son los bloques de construcción de la web abierta.', 'Addy Osmani', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['creativity', 'wisdom'], true, 'coding'),
(gen_random_uuid(), 'La división de código es la práctica de enviar solo el código que el usuario necesita en ese momento. Todo lo demás es deuda.', 'Addy Osmani', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['discipline', 'wisdom'], true, 'coding'),
(gen_random_uuid(), 'La optimización de la ruta crítica de renderizado es la diferencia entre un sitio rápido y uno lento.', 'Addy Osmani', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['discipline', 'focus'], true, 'coding'),

-- Brad Frost (185–195)
(gen_random_uuid(), 'El diseño atómico no es una metodología de CSS. Es una forma de pensar sobre las interfaces como sistemas.', 'Brad Frost', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['creativity', 'wisdom'], true, 'coding'),
(gen_random_uuid(), 'Los átomos forman moléculas, las moléculas forman organismos, los organismos forman plantillas y las plantillas forman páginas.', 'Brad Frost', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['creativity', 'learning'], true, 'coding'),
(gen_random_uuid(), 'Un sistema de diseño no es un kit de componentes. Es la fuente de verdad compartida entre diseño e ingeniería.', 'Brad Frost', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['discipline', 'wisdom'], true, 'coding'),
(gen_random_uuid(), 'Mobile-first no es solo una técnica CSS. Es una filosofía de diseño que te obliga a priorizar lo esencial.', 'Brad Frost', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['discipline', 'focus'], true, 'coding'),
(gen_random_uuid(), 'El diseño responsivo no es opcional. Es la descripción técnica de cómo debe comportarse la web por defecto.', 'Brad Frost', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['discipline', 'wisdom'], true, 'coding'),
(gen_random_uuid(), 'Los patrones en un sistema de diseño son decisiones de diseño codificadas. Cambia el patrón y cambias la decisión en todas partes.', 'Brad Frost', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'La coherencia visual no surge de tener buenas intenciones. Surge de tener un sistema de diseño bien mantenido.', 'Brad Frost', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['discipline', 'wisdom'], true, 'coding'),
(gen_random_uuid(), 'Los componentes deben ser agnósticos al contexto. Si un componente asume dónde vive, no es realmente reutilizable.', 'Brad Frost', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['discipline', 'creativity'], true, 'coding'),
(gen_random_uuid(), 'Documenta tus componentes con ejemplos vivos. La documentación estática siempre queda desincronizada.', 'Brad Frost', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['discipline', 'wisdom'], true, 'coding'),
(gen_random_uuid(), 'El vocabulario compartido entre diseñadores e ingenieros reduce los malentendidos y acelera el trabajo.', 'Brad Frost', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'focus'], true, 'coding'),
(gen_random_uuid(), 'Un sistema de diseño maduro permite moverse rápido sin romper cosas porque las decisiones comunes ya están tomadas.', 'Brad Frost', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['discipline', 'focus'], true, 'coding'),

-- John Maeda (196–207)
(gen_random_uuid(), 'La simplicidad consiste en eliminar lo obvio y añadir lo significativo.', 'John Maeda', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['creativity', 'wisdom'], true, 'coding'),
(gen_random_uuid(), 'La tecnología y el arte son dos formas de hacer preguntas sobre el mundo. El mejor diseño es la intersección de ambas.', 'John Maeda', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['creativity', 'wisdom'], true, 'coding'),
(gen_random_uuid(), 'La ley de la reducción dice: cuando en duda, elimina. Si no es esencial, sobra.', 'John Maeda', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['discipline', 'focus'], true, 'coding'),
(gen_random_uuid(), 'El tiempo es el recurso más valioso que puede dar un diseño. Ahórralo al usuario y habrás creado algo excepcional.', 'John Maeda', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'focus'], true, 'coding'),
(gen_random_uuid(), 'La organización hace que un sistema de muchos parezca un sistema de pocos. Eso es diseño de información.', 'John Maeda', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['creativity', 'wisdom'], true, 'coding'),
(gen_random_uuid(), 'El contexto importa más que la regla. Una buena tipografía depende del mensaje, no solo de la fuente.', 'John Maeda', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['creativity', 'wisdom'], true, 'coding'),
(gen_random_uuid(), 'Las emociones no son un accidente del diseño. Son el objetivo. El diseñador que ignora las emociones ignora al usuario.', 'John Maeda', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['creativity', 'wisdom'], true, 'coding'),
(gen_random_uuid(), 'La confianza es el recurso más escaso en el diseño digital. Gánala lentamente, piérdela rápido.', 'John Maeda', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'Un sistema complejo que funciona sin fallas ha evolucionado desde un sistema simple que funcionaba. Empieza simple.', 'John Maeda', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'El lenguaje visual es tan poderoso como el lenguaje verbal. Los diseñadores que lo dominan pueden comunicar sin palabras.', 'John Maeda', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['creativity', 'wisdom'], true, 'coding'),
(gen_random_uuid(), 'La modularidad en el diseño permite el crecimiento ordenado. Un sistema modular escala; uno monolítico colapsa.', 'John Maeda', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['discipline', 'wisdom'], true, 'coding'),
(gen_random_uuid(), 'El buen diseño no grita. Habla con claridad, en el tono correcto, en el momento correcto.', 'John Maeda', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['creativity', 'wisdom'], true, 'coding'),

-- Luke Wroblewski (208–218)
(gen_random_uuid(), 'Mobile-first significa diseñar para las restricciones más severas primero. Lo que funciona en móvil funciona en todas partes.', 'Luke Wroblewski', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['discipline', 'focus'], true, 'coding'),
(gen_random_uuid(), 'Los formularios son la parte más crítica de cualquier aplicación. Son donde el negocio sucede.', 'Luke Wroblewski', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['focus', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'El diseño de formularios no es glamoroso, pero es donde la mayoría de las conversiones se ganan o se pierden.', 'Luke Wroblewski', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['discipline', 'wisdom'], true, 'coding'),
(gen_random_uuid(), 'Los controles de entrada mal diseñados en dispositivos táctiles son la principal fuente de frustración en móvil.', 'Luke Wroblewski', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['discipline', 'wisdom'], true, 'coding'),
(gen_random_uuid(), 'Las pantallas pequeñas exigen jerarquía de información clara. Lo que cabe en una pantalla grande debe priorizado para la pequeña.', 'Luke Wroblewski', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['discipline', 'focus'], true, 'coding'),
(gen_random_uuid(), 'Los patrones de navegación en móvil no son simplificaciones de la navegación de escritorio. Son soluciones propias del medio.', 'Luke Wroblewski', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['creativity', 'wisdom'], true, 'coding'),
(gen_random_uuid(), 'El tamaño de los objetivos táctiles no es negociable. Menos de 44x44 puntos y el usuario comete errores que culpa a tu app.', 'Luke Wroblewski', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['discipline', 'wisdom'], true, 'coding'),
(gen_random_uuid(), 'La validación inline de formularios reduce el tiempo de completado y los errores. Retroalimenta al usuario mientras escribe.', 'Luke Wroblewski', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['discipline', 'focus'], true, 'coding'),
(gen_random_uuid(), 'Los datos de uso móvil superaron al escritorio hace años. Diseñar primero para escritorio es diseñar para la minoría.', 'Luke Wroblewski', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'La densidad de información en móvil debe ser alta, no baja. Los usuarios de móvil no tienen menos inteligencia.', 'Luke Wroblewski', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'El teclado virtual en móvil cambia todo el diseño. Anticipa cuándo aparece y diseña el layout en consecuencia.', 'Luke Wroblewski', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['discipline', 'focus'], true, 'coding'),

-- Citas adicionales de autores del listado — conceptos específicos de frontend (219–250)
(gen_random_uuid(), 'CSS Grid y Flexbox no son competidores. Resuelven problemas diferentes y trabajan hermosamente juntos.', 'Jeffrey Zeldman', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['creativity', 'learning'], true, 'coding'),
(gen_random_uuid(), 'La accesibilidad no es una lista de verificación. Es una mentalidad que llevas a cada decisión de diseño.', 'Tim Berners-Lee', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'Los sistemas de diseño que no evolucionan se convierten en deuda de diseño. Deben ser organismos vivos.', 'Brad Frost', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['discipline', 'creativity'], true, 'coding'),
(gen_random_uuid(), 'La jerarquía visual guía el ojo del usuario. Sin jerarquía, todo compite y nada gana.', 'John Maeda', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['creativity', 'wisdom'], true, 'coding'),
(gen_random_uuid(), 'Una animación que no comunica nada es una animación que molesta. El movimiento debe tener significado.', 'Don Norman', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['creativity', 'wisdom'], true, 'coding'),
(gen_random_uuid(), 'El contraste de color no es estética. Es accesibilidad. Texto ilegible excluye a millones de usuarios.', 'Jakob Nielsen', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['discipline', 'wisdom'], true, 'coding'),
(gen_random_uuid(), 'Los estados de carga, error y vacío son parte del diseño. Ignorarlos produce interfaces que confunden en el peor momento.', 'Dan Abramov', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['discipline', 'focus'], true, 'coding'),
(gen_random_uuid(), 'El HTML semántico no es solo para motores de búsqueda. Es para lectores de pantalla, para herramientas de accesibilidad, para el futuro.', 'Jeffrey Zeldman', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'Un botón que parece un enlace y un enlace que parece un botón no son problemas de estilo. Son problemas de comunicación.', 'Jared Spool', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'La tipografía es la voz visual del texto. Elige fuentes que hablen con el tono correcto para el mensaje correcto.', 'John Maeda', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['creativity', 'wisdom'], true, 'coding'),
(gen_random_uuid(), 'Los tokens de diseño son el ADN del sistema de diseño. Cambia el token y cambia el sistema entero de forma consistente.', 'Brad Frost', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['discipline', 'wisdom'], true, 'coding'),
(gen_random_uuid(), 'La rejilla en diseño web no es una camisa de fuerza. Es el ritmo invisible que hace que el layout se sienta armónico.', 'Dieter Rams', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['creativity', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'Los componentes reutilizables son la promesa de la eficiencia. Se cumplen solo cuando su API es simple e intuitiva.', 'Dan Abramov', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['discipline', 'wisdom'], true, 'coding'),
(gen_random_uuid(), 'El rendimiento percibido es más importante que el rendimiento real. Un skeleton screen puede sentirse más rápido que una pantalla en blanco.', 'Addy Osmani', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['creativity', 'wisdom'], true, 'coding'),
(gen_random_uuid(), 'La accesibilidad es la calidad de un sistema que permite que cualquier persona lo use, independientemente de sus capacidades.', 'Tim Berners-Lee', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'Las variables CSS son más que variables. Son canales de comunicación entre partes del sistema que de otro modo no se conocerían.', 'Jeffrey Zeldman', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['creativity', 'learning'], true, 'coding'),
(gen_random_uuid(), 'El diseño responsivo no se trata de hacer que las cosas quepan en pantallas pequeñas. Se trata de diseñar para todos los contextos.', 'Luke Wroblewski', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['discipline', 'wisdom'], true, 'coding'),
(gen_random_uuid(), 'El usuario escanea, no lee. Diseña párrafos cortos, encabezados descriptivos y puntos clave visibles de inmediato.', 'Jakob Nielsen', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'focus'], true, 'coding'),
(gen_random_uuid(), 'La documentación de componentes que no tiene ejemplos ejecutables no es documentación. Es ficción.', 'Martin Fowler', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['discipline', 'wisdom'], true, 'coding'),
(gen_random_uuid(), 'La carga cognitiva es el enemigo silencioso de la experiencia de usuario. Cada decisión que el usuario no tiene que tomar es un regalo.', 'Don Norman', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'focus'], true, 'coding'),
(gen_random_uuid(), 'Los breakpoints en diseño responsivo no deben basarse en dispositivos. Deben basarse en el contenido.', 'Brad Frost', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['creativity', 'wisdom'], true, 'coding'),
(gen_random_uuid(), 'El scroll infinito puede parecer conveniente. Para el usuario que busca el pie de página, es una pesadilla.', 'Jared Spool', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['wisdom', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'La paleta de colores de una interfaz no es decoración. Define la jerarquía, el estado y la emoción del sistema.', 'Dieter Rams', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['creativity', 'wisdom'], true, 'coding'),
(gen_random_uuid(), 'El tamaño de texto base en web debe ser al menos 16px. Cualquier cosa menor no respeta la visión del usuario promedio.', 'Luke Wroblewski', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['discipline', 'wisdom'], true, 'coding'),
(gen_random_uuid(), 'Los errores de validación deben aparecer cuando el usuario termina de escribir un campo, no cuando envía el formulario completo.', 'Jakob Nielsen', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['discipline', 'focus'], true, 'coding'),
(gen_random_uuid(), 'El interlineado adecuado no es un detalle tipográfico. Es la diferencia entre texto legible y texto que cansa los ojos.', 'John Maeda', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['creativity', 'discipline'], true, 'coding'),
(gen_random_uuid(), 'Una interfaz que funciona en modo oscuro y modo claro con el mismo nivel de calidad demuestra madurez en el sistema de diseño.', 'Brad Frost', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['discipline', 'wisdom'], true, 'coding'),
(gen_random_uuid(), 'Los storybooks y catálogos de componentes no son lujos de equipos grandes. Son la documentación viva que todo equipo necesita.', 'Dan Abramov', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['discipline', 'learning'], true, 'coding'),
(gen_random_uuid(), 'El diseño web no es impresión digital. Es un medio propio con sus propias restricciones y posibilidades.', 'Jeffrey Zeldman', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['creativity', 'wisdom'], true, 'coding'),
(gen_random_uuid(), 'La consistencia en los espacios, colores y tipografía no es obsesión. Es respeto por la atención del usuario.', 'Dieter Rams', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['discipline', 'wisdom'], true, 'coding'),
(gen_random_uuid(), 'El microcopiado — los textos pequeños en botones, etiquetas y mensajes — es donde el diseño de producto se vuelve literario.', 'Jared Spool', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['creativity', 'wisdom'], true, 'coding'),
(gen_random_uuid(), 'Las animaciones CSS que se ejecutan solo en el compositor son suaves. Las que tocan el layout bloquean el hilo principal.', 'Addy Osmani', 'philosophy', 'es', 'down', 'free', false, 'coding', 'frontend', ARRAY['discipline', 'focus'], true, 'coding')

ON CONFLICT (text, author) DO NOTHING;

COMMIT;
