-- 042_coding_backend_es.sql
-- MindScrolling — Coding Mode: Backend batch (Spanish)
-- 250 quotes: diseño de APIs, bases de datos, microservicios, caché, escalabilidad,
--   seguridad, autenticación, colas de mensajes, contenedores, serverless,
--   REST, GraphQL, patrones de diseño, SOLID, sistemas distribuidos, concurrencia
--
-- All rows:
--   category       = 'philosophy'
--   lang           = 'es'
--   swipe_dir      = 'down'
--   pack_name      = 'free'
--   is_premium     = false
--   content_type   = 'coding'
--   sub_category   = 'backend'
--   is_hidden_mode = true
--   locked_by      = 'coding'
-- Run in Supabase SQL Editor

BEGIN;

-- ══════════════════════════════════════════════════════════════════════════════
-- CODING BACKEND — ESPAÑOL (250 quotes)
-- ══════════════════════════════════════════════════════════════════════════════

INSERT INTO quotes (id, text, author, category, lang, swipe_dir, pack_name, is_premium, content_type, sub_category, tags, is_hidden_mode, locked_by) VALUES

-- Martin Fowler (1–18)
(gen_random_uuid(), 'Cualquier tonto puede escribir código que una máquina entiende. Los buenos programadores escriben código que los humanos entienden.', 'Martin Fowler', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'Refactorizar sin pruebas es como operar sin anestesia: técnicamente posible, pero brutal para todos.', 'Martin Fowler', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'Un microservicio que hace demasiado ya no es un microservicio: es un monolito disfrazado.', 'Martin Fowler', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'La base de datos es el corazón del sistema; trátala con el mismo cuidado que tratarías un órgano vital.', 'Martin Fowler', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'Los límites entre servicios deben reflejar los límites del dominio de negocio, no los límites de los equipos.', 'Martin Fowler', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'Una API es un contrato. Romperlo sin avisar es traicionar a todos los que confiaron en ti.', 'Martin Fowler', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'El acoplamiento oculto es el enemigo invisible de los sistemas distribuidos.', 'Martin Fowler', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'Diseña pensando en el fallo. En producción, todo lo que puede fallar eventualmente fallará.', 'Martin Fowler', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'La integración continua no es una herramienta: es una disciplina de equipo que exige compromiso diario.', 'Martin Fowler', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'Un buen esquema de base de datos es documentación ejecutable de las reglas de negocio.', 'Martin Fowler', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'La consistencia eventual no es un defecto del sistema: es una decisión de diseño consciente con consecuencias reales.', 'Martin Fowler', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'Versionar una API es admitir que el cambio es inevitable; ignorarlo es pretender que el tiempo no pasa.', 'Martin Fowler', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'El patrón Strangler Fig te permite matar un monolito sin detener el negocio: migra una pieza a la vez.', 'Martin Fowler', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'La deuda técnica acumulada en la capa de datos es la más costosa de pagar: los esquemas no mienten.', 'Martin Fowler', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'Cuando los microservicios se comunican de forma síncrona en cadena, has recreado el monolito con más latencia.', 'Martin Fowler', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'El evento de dominio es la unidad mínima de verdad en un sistema orientado a eventos.', 'Martin Fowler', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'Migrar esquemas de base de datos en producción requiere el mismo respeto que una cirugía en un paciente despierto.', 'Martin Fowler', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'El código limpio no es un lujo: es la única forma sostenible de mantener la velocidad de desarrollo a largo plazo.', 'Martin Fowler', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline','wisdom'], true, 'coding'),

-- Robert C. Martin (19–36)
(gen_random_uuid(), 'Una función debe hacer una sola cosa, hacerla bien y hacerla solamente.', 'Robert C. Martin', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'El principio de responsabilidad única aplicado a servicios: un servicio, una razón para cambiar.', 'Robert C. Martin', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'Abre tu software a la extensión y ciérralo a la modificación; ese es el secreto de la longevidad del código.', 'Robert C. Martin', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'Depende de abstracciones, nunca de implementaciones concretas: esa es la inversión de dependencias.', 'Robert C. Martin', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'El código profesional es aquel que el autor no se avergüenza de mostrar a las tres de la mañana.', 'Robert C. Martin', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'TDD no es escribir pruebas primero: es diseñar el comportamiento antes de implementar la solución.', 'Robert C. Martin', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'Deja el código más limpio de lo que lo encontraste; esa es la regla del boy scout aplicada al software.', 'Robert C. Martin', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'Los nombres importan. Un nombre correcto elimina la necesidad de un comentario explicativo.', 'Robert C. Martin', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'La arquitectura limpia pone las reglas de negocio en el centro y los detalles técnicos en los bordes.', 'Robert C. Martin', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'Un sistema bien diseñado puede cambiar de base de datos sin que el dominio se entere.', 'Robert C. Martin', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'Los comentarios que explican el qué indican que el código no es lo suficientemente claro.', 'Robert C. Martin', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'Las pruebas unitarias son la documentación más honesta que existe: no pueden mentir porque se ejecutan.', 'Robert C. Martin', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'Una buena arquitectura retrasa las decisiones hasta que tienes la información suficiente para tomarlas bien.', 'Robert C. Martin', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'El principio de segregación de interfaces dice: no obligues a nadie a depender de lo que no usa.', 'Robert C. Martin', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'El software que no puede probarse de forma aislada tiene un problema de diseño, no de pruebas.', 'Robert C. Martin', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'La verdadera profesionalidad en software es decir no cuando la solución rápida compromete la integridad del sistema.', 'Robert C. Martin', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'Cada capa de abstracción debe tener una razón de ser clara; las capas sin propósito solo añaden ruido.', 'Robert C. Martin', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'El código es poesía técnica: cada línea innecesaria disminuye la belleza del conjunto.', 'Robert C. Martin', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline','wisdom'], true, 'coding'),

-- Kent Beck (37–52)
(gen_random_uuid(), 'Haz que funcione, haz que sea correcto, haz que sea rápido: en ese orden, nunca al revés.', 'Kent Beck', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'La prueba que falla es información valiosa: te dice exactamente qué parte del contrato rompiste.', 'Kent Beck', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'El diseño simple no es el más fácil de construir, sino el más difícil de descubrir.', 'Kent Beck', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'Integra con frecuencia para que los conflictos sean pequeños; integra raramente para que sean dolorosos.', 'Kent Beck', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'Las pruebas de integración verifican que las piezas hablan el idioma correcto entre sí.', 'Kent Beck', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'Duplicar conocimiento en el código es la raíz de casi todos los problemas de mantenimiento.', 'Kent Beck', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'La refactorización continua no es perfeccionismo: es higiene mínima de ingeniería.', 'Kent Beck', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'Un sistema diseñado para el cambio tiene más valor que uno optimizado para el estado actual.', 'Kent Beck', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'La comunicación entre programador y código debe ser tan fluida como entre dos personas que se entienden.', 'Kent Beck', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'El feedback rápido es el motor del aprendizaje; un ciclo de prueba lento es un freno al progreso.', 'Kent Beck', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'La simplicidad en arquitectura no se logra omitiendo cosas necesarias, sino eliminando las innecesarias.', 'Kent Beck', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'Cada historia de usuario que no puede probarse automáticamente es una promesa sin garantía.', 'Kent Beck', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'La deuda técnica pagada hoy cuesta menos que la misma deuda pagada mañana con intereses.', 'Kent Beck', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'Los cambios pequeños y frecuentes reducen el riesgo más que los grandes cambios poco frecuentes.', 'Kent Beck', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'Cuando el código duele al cambiar, te está diciendo que hay un diseño que merece ser descubierto.', 'Kent Beck', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'Un equipo con buenas prácticas de integración convierte los conflictos en conversaciones productivas.', 'Kent Beck', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline','wisdom'], true, 'coding'),

-- Donald Knuth (53–66)
(gen_random_uuid(), 'La optimización prematura es la raíz de todos los males en programación.', 'Donald Knuth', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'Mide antes de optimizar. La intuición sobre rendimiento casi siempre está equivocada.', 'Donald Knuth', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'El arte de programar es el arte de organizar y dominar la complejidad.', 'Donald Knuth', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'Un algoritmo correcto implementado de forma oscura no tiene ningún valor práctico duradero.', 'Donald Knuth', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'Las estructuras de datos son el corazón de los sistemas eficientes; los algoritmos son la sangre.', 'Donald Knuth', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'Comprender profundamente un problema es el noventa por ciento de la solución.', 'Donald Knuth', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'El código es literatura técnica; debe poder leerse con la misma fluidez que un buen texto.', 'Donald Knuth', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'La elegancia en software no es decorativa: es señal de que se entendió el problema correctamente.', 'Donald Knuth', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'Documentar el porqué de una decisión es tan importante como documentar el cómo.', 'Donald Knuth', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'Los números de rendimiento sin contexto de carga son estadísticas sin significado.', 'Donald Knuth', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'La precisión en la especificación de un sistema es la única forma de evitar sorpresas desagradables.', 'Donald Knuth', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'Un programa que funciona por accidente es un programa a punto de fallar por razones desconocidas.', 'Donald Knuth', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'La correctitud debe demostrarse, no suponerse; los sistemas críticos no admiten corazonadas.', 'Donald Knuth', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'Cambiar un sistema sin entenderlo completamente es como operar en la oscuridad con herramientas afiladas.', 'Donald Knuth', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom','discipline'], true, 'coding'),

-- Edsger Dijkstra (67–80)
(gen_random_uuid(), 'La prueba de programas puede mostrar la presencia de errores, pero nunca su ausencia.', 'Edsger Dijkstra', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'La simplicidad es condición previa para la fiabilidad; los sistemas complejos fallan de formas complejas.', 'Edsger Dijkstra', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'El software que no puede razonarse formalmente no puede confiarse para tareas críticas.', 'Edsger Dijkstra', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'Dominar la complejidad es la esencia de la programación; todo lo demás es detalle técnico.', 'Edsger Dijkstra', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'La depuración es dos veces más difícil que la programación; si escribes código al límite de tu inteligencia, ¿cómo lo depurarás?', 'Edsger Dijkstra', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'Los buenos sistemas son los que fracasan de forma predecible y comprensible.', 'Edsger Dijkstra', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'Un sistema distribuido falla en partes que nadie anticipó; diseña para la sorpresa.', 'Edsger Dijkstra', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'La concurrencia sin disciplina produce errores que solo se manifiestan en producción bajo carga real.', 'Edsger Dijkstra', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'El programador que no puede explicar su código en lenguaje natural no lo entiende del todo.', 'Edsger Dijkstra', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'La separación de responsabilidades no es una recomendación: es la ley fundamental del diseño correcto.', 'Edsger Dijkstra', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'La abstracción correcta oculta la complejidad sin ocultar la información relevante.', 'Edsger Dijkstra', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'Probar con datos reales en producción no es una estrategia de calidad: es una apuesta con usuarios reales.', 'Edsger Dijkstra', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'La corrección de un sistema no puede verificarse mediante la observación externa exclusivamente.', 'Edsger Dijkstra', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'El estado mutable compartido es la fuente de los errores más difíciles de reproducir en sistemas concurrentes.', 'Edsger Dijkstra', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom','discipline'], true, 'coding'),

-- Brian Kernighan (81–92)
(gen_random_uuid(), 'Depurar es más difícil que programar; si eres tan listo como puedes ser al programar, no serás lo suficientemente listo para depurar.', 'Brian Kernighan', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'El código que no puede leerse en voz alta con claridad probablemente tampoco puede mantenerse con claridad.', 'Brian Kernighan', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'Las interfaces claras son más valiosas que las implementaciones brillantes.', 'Brian Kernighan', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'Un protocolo de red bien diseñado sobrevive décadas; uno mal diseñado se convierte en legado doloroso.', 'Brian Kernighan', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'Escribe primero el código más simple posible; la optimización es un problema del futuro.', 'Brian Kernighan', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'La herramienta correcta para el trabajo correcto: no uses un martillo cuando necesitas un bisturí.', 'Brian Kernighan', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'Los sistemas que perduran son los que tienen límites claros y responsabilidades bien definidas.', 'Brian Kernighan', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'La portabilidad del software depende de la calidad de sus abstracciones, no de sus implementaciones.', 'Brian Kernighan', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'El código minimalista no es código perezoso: es código que ha sido pensado profundamente.', 'Brian Kernighan', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'La claridad en los mensajes de error es tan importante como la claridad en el código mismo.', 'Brian Kernighan', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'Un sistema de ficheros bien diseñado es una lección de abstracción aplicada al almacenamiento.', 'Brian Kernighan', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'La modularidad bien aplicada permite cambiar el interior sin romper el exterior.', 'Brian Kernighan', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline','wisdom'], true, 'coding'),

-- Linus Torvalds (93–104)
(gen_random_uuid(), 'El código que no puede revisarse no puede mejorarse; la revisión abierta es la mayor garantía de calidad.', 'Linus Torvalds', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'Los sistemas operativos son la evidencia más clara de que el diseño importa tanto como la implementación.', 'Linus Torvalds', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'Un kernel sin fallas de seguridad es un ideal; minimizar la superficie de ataque es una realidad alcanzable.', 'Linus Torvalds', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'El control de versiones no es opcional: es la memoria institucional de cualquier proyecto serio.', 'Linus Torvalds', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'La concurrencia a nivel de kernel requiere un nivel de disciplina que la mayoría de los desarrolladores subestima.', 'Linus Torvalds', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'El software libre es libre como en libertad: da al código la capacidad de evolucionar sin ataduras.', 'Linus Torvalds', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'Hacer que algo funcione en todos los hardware posibles es el reto más humilde y más brutal del software.', 'Linus Torvalds', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'La estabilidad de una API de sistema operativo es la promesa más costosa que puede hacer un equipo.', 'Linus Torvalds', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'Los parches de seguridad mal escritos crean vulnerabilidades nuevas mientras cierran las antiguas.', 'Linus Torvalds', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'El rendimiento de un sistema no es una característica: es la consecuencia de miles de decisiones correctas.', 'Linus Torvalds', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'El historial de commits de un proyecto bien gestionado cuenta la historia de cómo se resolvieron los problemas.', 'Linus Torvalds', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'La gestión de memoria es el arte de saber exactamente a quién pertenece cada byte en cada momento.', 'Linus Torvalds', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline','wisdom'], true, 'coding'),

-- Rob Pike (105–116)
(gen_random_uuid(), 'Los datos dominan. Si tienes las estructuras de datos correctas, los algoritmos se escriben solos.', 'Rob Pike', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'La concurrencia no es el paralelismo; una es sobre la estructura del programa, el otro sobre la ejecución.', 'Rob Pike', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'No comuniques compartiendo memoria; comparte memoria comunicando. Esa es la filosofía de los canales.', 'Rob Pike', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'La simplicidad es la característica más difícil de lograr y la más fácil de destruir con el tiempo.', 'Rob Pike', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'Un lenguaje de programación que no cambia la forma en que piensas no merece aprenderse.', 'Rob Pike', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'El manejo explícito de errores no es verbosidad: es honestidad sobre lo que puede salir mal.', 'Rob Pike', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'Las goroutines son baratas; el bloqueo innecesario es caro. Diseña para la concurrencia desde el principio.', 'Rob Pike', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'Un servidor que no puede manejar miles de conexiones concurrentes no está listo para el mundo real.', 'Rob Pike', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'Las interfaces pequeñas y bien definidas son la clave de la composabilidad en cualquier sistema.', 'Rob Pike', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'La legibilidad del código es más importante que la originalidad; el equipo debe poder leerlo mañana.', 'Rob Pike', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'Los errores ignorados se convierten en fallos silenciosos; cada error merece una respuesta explícita.', 'Rob Pike', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'Menos características con mayor calidad supera a más características con mayor complejidad.', 'Rob Pike', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline','wisdom'], true, 'coding'),

-- Leslie Lamport (117–128)
(gen_random_uuid(), 'Un sistema distribuido es uno donde el fallo de un computador que ni siquiera sabías que existía puede detener tu trabajo.', 'Leslie Lamport', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'El consenso distribuido es el problema más profundo de la informática: simple de enunciar, brutal de resolver.', 'Leslie Lamport', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'Los relojes lógicos permiten ordenar eventos sin necesidad de sincronización de relojes físicos.', 'Leslie Lamport', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'La especificación formal de un sistema es el único antídoto real contra los malentendidos de diseño.', 'Leslie Lamport', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'Paxos es difícil no porque el algoritmo sea oscuro, sino porque el problema que resuelve es genuinamente difícil.', 'Leslie Lamport', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'La tolerancia a fallos no se diseña una vez: se verifica continuamente bajo condiciones adversas reales.', 'Leslie Lamport', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'Un sistema que puede probarse en estado de fallo parcial es más confiable que uno que solo funciona en condiciones ideales.', 'Leslie Lamport', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'La seguridad y la vivacidad son las dos propiedades fundamentales de cualquier sistema concurrente correcto.', 'Leslie Lamport', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'El orden causal de los eventos en un sistema distribuido es la verdad más objetiva disponible.', 'Leslie Lamport', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'Escribir código correcto es difícil; escribir código concurrente correcto es un orden de magnitud más difícil.', 'Leslie Lamport', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'La replicación aumenta la disponibilidad pero introduce el problema de la consistencia; no hay ganancia gratuita.', 'Leslie Lamport', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'Un modelo formal incorrecto produce garantías incorrectas; mejor ningún modelo que uno que engaña.', 'Leslie Lamport', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline','wisdom'], true, 'coding'),

-- Werner Vogels (129–140)
(gen_random_uuid(), 'Todo fallará eventualmente. Diseña para la recuperación, no solo para la prevención.', 'Werner Vogels', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'La disponibilidad es el producto de decisiones de diseño tomadas bajo incertidumbre real, no en papel.', 'Werner Vogels', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'Los sistemas a escala de internet exigen que aceptes el fallo como estado normal, no como excepción.', 'Werner Vogels', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'La elasticidad real significa crecer y decrecer automáticamente según la demanda, sin intervención humana.', 'Werner Vogels', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'Los equipos que poseen el servicio de extremo a extremo producen sistemas más confiables que los que lo dividen.', 'Werner Vogels', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'La observabilidad de un sistema distribuido no es opcional: sin ella, operas en la oscuridad total.', 'Werner Vogels', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'Los servicios desacoplados permiten que los fallos sean locales; el acoplamiento convierte los fallos en cascadas.', 'Werner Vogels', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'La velocidad de despliegue es una ventaja competitiva; un pipeline lento es un handicap estratégico.', 'Werner Vogels', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'Los SLO no son métricas de monitoreo: son compromisos de confianza con los usuarios del sistema.', 'Werner Vogels', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'La durabilidad de los datos en la nube requiere múltiples copias en múltiples zonas; una sola copia es una ilusión.', 'Werner Vogels', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'Automatizar las operaciones no es pereza: es la única forma de operar sistemas a escala sin errores humanos.', 'Werner Vogels', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'El caos controlado en producción te enseña más sobre tu sistema que cualquier prueba en entorno de staging.', 'Werner Vogels', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom','discipline'], true, 'coding'),

-- Jeff Dean (141–152)
(gen_random_uuid(), 'Los números de latencia que no conoces de memoria son puntos ciegos en el diseño de tu sistema.', 'Jeff Dean', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'La caché es el primer recurso del ingeniero de sistemas; usarla bien requiere entender los patrones de acceso.', 'Jeff Dean', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'A escala de millones de peticiones, los errores raros se vuelven frecuentes y los fallos ocasionales se hacen constantes.', 'Jeff Dean', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'La sharding de bases de datos resuelve el problema de volumen pero crea el problema de las consultas cruzadas.', 'Jeff Dean', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'Los sistemas de almacenamiento distribuido son tan confiables como el componente más débil de su cadena de escritura.', 'Jeff Dean', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'El procesamiento por lotes y el procesamiento en tiempo real no son mutuamente excluyentes: se complementan.', 'Jeff Dean', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'La infraestructura de bajo nivel mal diseñada se convierte en el techo de rendimiento de todo lo que construyes encima.', 'Jeff Dean', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'Diseñar para diez veces más carga de la actual no es paranoia: es ingeniería preventiva responsable.', 'Jeff Dean', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'Un índice bien elegido convierte una consulta de minutos en una de milisegundos; el índice incorrecto lo hace al revés.', 'Jeff Dean', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'La compresión de datos no solo ahorra espacio: reduce la latencia de red y el coste de almacenamiento simultáneamente.', 'Jeff Dean', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'Los sistemas de colas permiten absorber picos de tráfico sin degradar la experiencia del usuario final.', 'Jeff Dean', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'MapReduce democratizó el procesamiento masivo de datos; la abstracción correcta cambia lo que es posible.', 'Jeff Dean', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom','discipline'], true, 'coding'),

-- Rich Hickey (153–164)
(gen_random_uuid(), 'La simplicidad no es facilidad. Lo simple tiene una sola responsabilidad; lo fácil puede estar tejido con complejidad oculta.', 'Rich Hickey', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'El estado mutable es el mayor enemigo de los sistemas concurrentes; la inmutabilidad es una solución, no una restricción.', 'Rich Hickey', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'Los valores son simples por naturaleza: no cambian, no tienen efectos secundarios, son seguros de compartir.', 'Rich Hickey', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'El tiempo es una dimensión fundamental del modelado de datos; ignorarlo produce sistemas que olvidan su propia historia.', 'Rich Hickey', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'La programación orientada a objetos mezcla estado, identidad y valor; separarlos clarifica el diseño enormemente.', 'Rich Hickey', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'Las colas de mensajes no son solo buffers: son los puntos de desacoplamiento más poderosos de una arquitectura.', 'Rich Hickey', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'Un sistema que no puede razonarse localmente sin contexto global es un sistema que ha acumulado demasiada complejidad.', 'Rich Hickey', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'La composición de funciones puras produce sistemas predecibles; la composición de objetos con estado produce sorpresas.', 'Rich Hickey', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'El polimorfismo basado en datos es más flexible que el basado en tipos; los datos no cambian de forma, los tipos sí.', 'Rich Hickey', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'Accidental es lo que no se requiere por el problema; esencial es lo que no se puede evitar. Minimiza lo accidental.', 'Rich Hickey', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'El diseño orientado a datos permite que los sistemas evolucionen sin reescribirse desde cero.', 'Rich Hickey', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'La especificidad de los tipos en una API es la documentación más útil que puedes proporcionar a un consumidor.', 'Rich Hickey', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom','discipline'], true, 'coding'),

-- Joe Armstrong (165–174)
(gen_random_uuid(), 'Los procesos ligeros que fallan de forma aislada son la base de los sistemas tolerantes a fallos.', 'Joe Armstrong', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'Deja que falle. Recuperarse del fallo es más confiable que prevenir cada posible fallo imaginable.', 'Joe Armstrong', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'El paso de mensajes entre procesos aislados elimina las condiciones de carrera por construcción.', 'Joe Armstrong', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'La concurrencia masiva es natural cuando cada proceso tiene su propia memoria y no la comparte.', 'Joe Armstrong', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'Un supervisor que reinicia procesos fallidos es más robusto que código defensivo que intenta prevenir todo.', 'Joe Armstrong', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'La distribución en Erlang no es una característica avanzada: es el modo natural de pensar sobre el sistema.', 'Joe Armstrong', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'Los sistemas de telecomunicaciones requieren nueve nueves de disponibilidad; eso solo se logra con fallo como primer ciudadano.', 'Joe Armstrong', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'El código que no puede actualizarse sin parar el sistema no está listo para el mundo real de producción continua.', 'Joe Armstrong', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'Los mensajes asíncronos desacoplan el tiempo de los procesos; ninguno espera al otro para continuar.', 'Joe Armstrong', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'La programación funcional en sistemas distribuidos no es académica: es la forma más natural de modelar la realidad.', 'Joe Armstrong', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom','discipline'], true, 'coding'),

-- James Gosling (175–182)
(gen_random_uuid(), 'Escribir una vez, ejecutar en cualquier lugar no es magia: es el resultado de abstraer la plataforma correctamente.', 'James Gosling', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'La gestión automática de memoria elimina una clase completa de errores a cambio de perder algo de control fino.', 'James Gosling', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'El tipado fuerte en tiempo de compilación es una red de seguridad que atrapa errores antes de que lleguen a producción.', 'James Gosling', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'Los servidores de aplicaciones existen porque el código de negocio no debería ocuparse de gestionar conexiones de red.', 'James Gosling', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'La interoperabilidad entre sistemas requiere estándares compartidos; los protocolos propietarios son barreras disfrazadas.', 'James Gosling', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'La seguridad de tipos no garantiza la corrección del programa, pero elimina una categoría completa de bugs runtime.', 'James Gosling', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'La retrocompatibilidad es una promesa costosa pero necesaria para cualquier plataforma con ecosistema maduro.', 'James Gosling', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'El modelo de hilos en Java mostró que la concurrencia accesible tiene un coste en complejidad de razonamiento.', 'James Gosling', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom','discipline'], true, 'coding'),

-- Bjarne Stroustrup (183–190)
(gen_random_uuid(), 'El lenguaje de programación debe facilitar las buenas prácticas y dificultar las malas, no al revés.', 'Bjarne Stroustrup', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'Los recursos adquiridos en la construcción deben liberarse en la destrucción; esa es la esencia de RAII.', 'Bjarne Stroustrup', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'La abstracción sin coste de tiempo de ejecución es el objetivo supremo de un lenguaje de sistemas.', 'Bjarne Stroustrup', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'El código que no se puede depurar fácilmente es código que no debería haber sido escrito tan inteligentemente.', 'Bjarne Stroustrup', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'Los genéricos bien usados producen código reutilizable sin sacrificar la seguridad de tipos.', 'Bjarne Stroustrup', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'La sobrecarga innecesaria de abstracción hace que el código sea más difícil de entender y más lento de ejecutar.', 'Bjarne Stroustrup', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'El diseño de sistemas de bajo nivel requiere entender exactamente qué hace la máquina con cada instrucción.', 'Bjarne Stroustrup', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'La compatibilidad con C fue una decisión estratégica que determinó el ecosistema de C++ por décadas.', 'Bjarne Stroustrup', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom','discipline'], true, 'coding'),

-- Ryan Dahl (191–198)
(gen_random_uuid(), 'El modelo de I/O no bloqueante permite manejar miles de conexiones concurrentes con un único hilo de ejecución.', 'Ryan Dahl', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'JavaScript en el servidor unifica el lenguaje de frontend y backend, reduciendo la fricción del cambio de contexto.', 'Ryan Dahl', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'El bucle de eventos es simple pero poderoso: una arquitectura que escaló para servir millones de conexiones.', 'Ryan Dahl', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'Los módulos con permisos explícitos son más seguros que los módulos con acceso total al sistema por defecto.', 'Ryan Dahl', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'Un runtime que respeta los estándares web permite reutilizar código entre el navegador y el servidor.', 'Ryan Dahl', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'Las promesas son más manejables que los callbacks anidados, pero las funciones asíncronas son la solución natural.', 'Ryan Dahl', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'El servidor HTTP más simple posible sigue siendo el mejor punto de partida para entender cómo funciona la web.', 'Ryan Dahl', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'La seguridad por defecto es más valiosa que la comodidad por defecto en cualquier entorno de ejecución moderno.', 'Ryan Dahl', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline','wisdom'], true, 'coding'),

-- DHH (199–206)
(gen_random_uuid(), 'La convención sobre la configuración elimina decisiones triviales y libera energía mental para lo que importa.', 'DHH', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'Un framework con buenas convenciones permite que un programador nuevo sea productivo en horas, no semanas.', 'DHH', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'La API REST bien diseñada es autoexplicativa; el consumidor entiende las capacidades sin leer documentación externa.', 'DHH', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'El monolito bien estructurado es más fácil de operar que un sistema de microservicios prematuro y mal dividido.', 'DHH', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'La productividad del programador es el primer factor de rendimiento en cualquier empresa de software.', 'DHH', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'Optimizar para la felicidad del desarrollador no es sentimentalismo: produce código mejor mantenido a largo plazo.', 'DHH', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'El ORM correcto elimina el SQL repetitivo sin robar al programador la capacidad de escribir consultas eficientes.', 'DHH', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'La autenticación integrada en el framework elimina una clase de vulnerabilidades antes de que el programador las cometa.', 'DHH', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline','wisdom'], true, 'coding'),

-- Guido van Rossum (207–214)
(gen_random_uuid(), 'El código se lee muchas más veces de las que se escribe; la legibilidad no es estética, es funcionalidad.', 'Guido van Rossum', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'Debería haber una, y preferiblemente solo una, forma obvia de hacer algo; la ambigüedad engendra errores.', 'Guido van Rossum', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'Lo explícito es mejor que lo implícito; los sistemas que esconden su comportamiento son difíciles de depurar.', 'Guido van Rossum', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'Los errores no deben silenciarse a menos que sean explícitamente ignorados; el silencio en software es peligroso.', 'Guido van Rossum', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'Lo simple es mejor que lo complejo; lo complejo es mejor que lo complicado. Conoce la diferencia.', 'Guido van Rossum', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'El espacio de nombres es una gran idea; úsalos tanto como sea posible para organizar el código de backend.', 'Guido van Rossum', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'La practicidad supera a la pureza cuando el objetivo final es resolver problemas reales en producción.', 'Guido van Rossum', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'Las anotaciones de tipo en Python no son obligatorias, pero son cortesía hacia el próximo desarrollador que lea el código.', 'Guido van Rossum', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline','wisdom'], true, 'coding'),

-- Dennis Ritchie (215–220)
(gen_random_uuid(), 'C es un lenguaje que asume que el programador sabe lo que hace; esa libertad tiene un precio en responsabilidad.', 'Dennis Ritchie', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'Unix enseñó que los programas pequeños que hacen una sola cosa, combinados, son más poderosos que los monolitos.', 'Dennis Ritchie', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'La interfaz de llamada al sistema es el contrato más estable de cualquier sistema operativo moderno.', 'Dennis Ritchie', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'Los punteros son la abstracción más cercana a la realidad de la máquina; usarlos bien requiere disciplina absoluta.', 'Dennis Ritchie', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'Todo en Unix es un fichero; esa abstracción unifica la interfaz de acceso a recursos completamente distintos.', 'Dennis Ritchie', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'La elegancia de C radica en que hace exactamente lo que dices, ni más ni menos; el programador manda.', 'Dennis Ritchie', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom','discipline'], true, 'coding'),

-- Temáticos — API Design (221–228)
(gen_random_uuid(), 'Una API REST idempotente permite reintentos seguros sin efectos secundarios acumulados en el servidor.', 'Martin Fowler', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'GraphQL transfiere el control de la forma de los datos del servidor al cliente; úsalo cuando los clientes son heterogéneos.', 'Robert C. Martin', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'La paginación es obligatoria en cualquier endpoint que devuelva colecciones; las listas sin límite no escalan.', 'Werner Vogels', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'Los códigos de estado HTTP son el lenguaje común entre cliente y servidor; usarlos correctamente es respeto al estándar.', 'Brian Kernighan', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'El rate limiting en una API pública no es opresión: es la defensa mínima contra el abuso no intencionado.', 'Jeff Dean', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'La documentación de la API generada desde el código nunca está desactualizada; la documentación manual siempre lo está.', 'Kent Beck', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'El versionado semántico en una API comunica el impacto del cambio; sin él, cada nueva versión es una apuesta para el consumidor.', 'Martin Fowler', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'Los tokens de autenticación de vida corta son más seguros que los de vida larga; el tiempo es un control de acceso.', 'Robert C. Martin', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline','wisdom'], true, 'coding'),

-- Temáticos — Bases de Datos (229–236)
(gen_random_uuid(), 'Una transacción ACID garantiza que el sistema pasa de un estado válido a otro estado válido, nunca a uno corrupto.', 'Donald Knuth', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'El índice incorrecto puede ser peor que ningún índice; los índices selectivos son los que cambian el rendimiento.', 'Jeff Dean', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'La normalización excesiva de la base de datos produce consultas tan complejas que nadie puede mantenerlas.', 'Martin Fowler', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'Las migraciones de esquema sin retroceso posible son bombas de tiempo en sistemas de alta disponibilidad.', 'Werner Vogels', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'El log de transacciones es la fuente de verdad más confiable de cualquier base de datos relacional bien gestionada.', 'Leslie Lamport', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'Las bases de datos NoSQL no son mejores ni peores que las relacionales: son apropiadas para modelos de acceso diferentes.', 'Rich Hickey', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'El connection pooling es obligatorio en cualquier aplicación web de producción que acceda a una base de datos relacional.', 'DHH', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'Las consultas lentas en producción son más peligrosas que los errores explícitos; degradan sin avisar claramente.', 'Jeff Dean', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline','wisdom'], true, 'coding'),

-- Temáticos — Seguridad / Auth (237–244)
(gen_random_uuid(), 'Nunca almacenes contraseñas en texto plano; el hash con sal es el mínimo estándar aceptable de seguridad.', 'Linus Torvalds', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'El principio de mínimo privilegio aplicado a microservicios significa que cada servicio solo puede hacer lo que necesita.', 'Edsger Dijkstra', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'OAuth delega la autenticación sin exponer las credenciales; separar autenticación de autorización es diseño correcto.', 'Brian Kernighan', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'La inyección SQL en el código moderno es negligencia imperdonable; los parámetros preparados existen desde hace décadas.', 'Robert C. Martin', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'Cifrar en reposo y en tránsito no es paranoia: es el precio mínimo de manejar datos de usuarios responsablemente.', 'Werner Vogels', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'La rotación regular de secretos es más importante que tener secretos complejos que nunca se rotan.', 'Jeff Dean', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'Validar la entrada en el servidor, independientemente de la validación en el cliente, es una ley no negociable.', 'Guido van Rossum', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'Los logs de auditoría son la memoria forense del sistema; sin ellos, un incidente de seguridad es irreconstruible.', 'Leslie Lamport', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom','discipline'], true, 'coding'),

-- Temáticos — Escalabilidad / Colas / Caché (245–250)
(gen_random_uuid(), 'La caché es una apuesta: asumes que los datos no cambiarán antes de que expiren. Gestiona esa apuesta conscientemente.', 'Martin Fowler', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'El escalado horizontal requiere que los servicios sean sin estado; el estado compartido es el enemigo de la elasticidad.', 'Werner Vogels', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'Una cola de mensajes entre productores y consumidores convierte el acoplamiento temporal en desacoplamiento real.', 'Joe Armstrong', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'El circuit breaker detiene la cascada de fallos antes de que un servicio lento destruya todo el sistema.', 'Martin Fowler', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'Serverless desplaza la responsabilidad de la infraestructura al proveedor; lo que ganas en simplicidad, lo pierdes en control.', 'Ryan Dahl', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'Los contenedores garantizan paridad entre el entorno de desarrollo y el de producción; esa paridad elimina la clase de bugs más frustrante.', 'Linus Torvalds', 'philosophy', 'es', 'down', 'free', false, 'coding', 'backend', ARRAY['discipline','wisdom'], true, 'coding')

ON CONFLICT (text, author) DO NOTHING;

COMMIT;
