-- 043_coding_fundamentals_es.sql
-- MindScrolling — Coding Mode: Fundamentals batch (Spanish)
-- 250 quotes: algoritmos, estructuras de datos, código limpio, refactoring,
--   testing, depuración, resolución de problemas, pensamiento computacional,
--   abstracción, recursión, Big O, patrones de diseño, SOLID, DRY, KISS
--
-- All rows:
--   category       = 'philosophy'
--   lang           = 'es'
--   swipe_dir      = 'down'
--   pack_name      = 'free'
--   is_premium     = false
--   content_type   = 'coding'
--   sub_category   = 'fundamentals'
--   is_hidden_mode = true
--   locked_by      = 'coding'
-- Run in Supabase SQL Editor

BEGIN;

-- ══════════════════════════════════════════════════════════════════════════════
-- CODING FUNDAMENTALS — SPANISH (250 quotes)
-- ══════════════════════════════════════════════════════════════════════════════

INSERT INTO quotes (id, text, author, category, lang, swipe_dir, pack_name, is_premium, content_type, sub_category, tags, is_hidden_mode, locked_by) VALUES

-- Donald Knuth (1–18)
(gen_random_uuid(), 'Un algoritmo debe verse para ser creído.', 'Donald Knuth', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'La optimización prematura es la raíz de todos los males.', 'Donald Knuth', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'El arte de programar es el arte de organizar la complejidad.', 'Donald Knuth', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'Los mejores programas están escritos para que las máquinas los ejecuten rápido y los humanos los entiendan con claridad.', 'Donald Knuth', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'La ciencia es lo que entendemos lo suficiente como para explicárselo a una computadora. El arte es todo lo demás que hacemos.', 'Donald Knuth', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'Si encuentras que pasas casi todo tu tiempo en teoría, empieza a prestar atención a las cosas prácticas; mejorarás tus teorías.', 'Donald Knuth', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'Los números aleatorios no deben generarse con un método elegido al azar.', 'Donald Knuth', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'Programar es la actividad de enseñarle a una computadora lo que quieres que haga de la forma más precisa posible.', 'Donald Knuth', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'La elegancia no es un lujo; en programación, la elegancia es la señal de que entendiste el problema correctamente.', 'Donald Knuth', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'Un algoritmo ineficiente en una computadora rápida es derrotar el propósito de ambos.', 'Donald Knuth', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'El análisis de algoritmos es la gramática del razonamiento computacional.', 'Donald Knuth', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'Dominar las estructuras de datos es dominar la forma en que el pensamiento toma forma dentro de la máquina.', 'Donald Knuth', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'La recursión es la forma en que la naturaleza resuelve problemas: divídelos hasta que sean triviales.', 'Donald Knuth', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'Quien no mide la complejidad de su solución no controla realmente lo que ha construido.', 'Donald Knuth', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'El pensamiento computacional no es pensar como una máquina; es pensar con la precisión que las máquinas exigen.', 'Donald Knuth', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'Leer código ajeno es tan importante como escribir el propio; ambos forman al programador completo.', 'Donald Knuth', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'La abstracción es el instrumento más poderoso de la informática teórica y práctica.', 'Donald Knuth', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'Un programa correcto que tarda en ejecutarse sigue siendo correcto; un programa rápido que falla no sirve de nada.', 'Donald Knuth', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),

-- Robert C. Martin (19–36)
(gen_random_uuid(), 'El código limpio hace una cosa bien. El código sucio intenta hacer muchas cosas a la vez.', 'Robert C. Martin', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'La verdadera medida de un buen programador es cuánto cuida el código que escribe.', 'Robert C. Martin', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'Siempre deja el código un poco más limpio de lo que lo encontraste.', 'Robert C. Martin', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'Los nombres de las variables son la primera documentación de tu código; elige con cuidado.', 'Robert C. Martin', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'Una función debe hacer una sola cosa, hacerla bien y no hacer nada más.', 'Robert C. Martin', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'El código duplicado es la fuente más común de defectos en el software.', 'Robert C. Martin', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'Los comentarios que explican lo que hace el código son un olor; el código debe explicarse solo.', 'Robert C. Martin', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'El refactoring no es arreglar bugs; es mejorar la estructura del código sin cambiar su comportamiento.', 'Robert C. Martin', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'Las pruebas automatizadas son la red de seguridad que permite refactorizar con confianza.', 'Robert C. Martin', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'El principio de responsabilidad única dice: una clase debe tener una única razón para cambiar.', 'Robert C. Martin', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'El código abierto para extensión y cerrado para modificación es la madurez arquitectónica del software.', 'Robert C. Martin', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'Depender de abstracciones en lugar de concreciones es el camino hacia el software flexible.', 'Robert C. Martin', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'El código profesional no es solo código que funciona; es código que otros puedan leer, mantener y extender.', 'Robert C. Martin', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'TDD no es escribir pruebas primero; es diseñar pensando en la verificabilidad desde el inicio.', 'Robert C. Martin', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'Un buen arquitecto maximiza el número de decisiones que no se toman.', 'Robert C. Martin', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'La deuda técnica, como la financiera, genera intereses; págala pronto o te ahogará.', 'Robert C. Martin', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'El principio DRY no es solo evitar copiar y pegar; es que cada pieza de conocimiento tenga una sola representación.', 'Robert C. Martin', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'Escribir código simple es más difícil que escribir código complicado; requiere más pensamiento.', 'Robert C. Martin', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),

-- Andrew Hunt & David Thomas (37–52)
(gen_random_uuid(), 'El programador pragmático piensa más allá del problema inmediato y siempre coloca el trabajo en su contexto más amplio.', 'Andrew Hunt', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'No te repitas: todo conocimiento debe tener una representación única, no ambigua y autoritativa en un sistema.', 'Andrew Hunt', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'Arregla los problemas pequeños antes de que se conviertan en grandes; la ventana rota no reparada invita al caos.', 'Andrew Hunt', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'Usa el poder de la línea de comandos; las interfaces gráficas son convenientes, pero no reemplazan la precisión del terminal.', 'David Thomas', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'El mejor lenguaje de programación es el que mejor se adapta al problema que intentas resolver.', 'David Thomas', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'Invierte regularmente en tu cartera de conocimiento; el mundo tecnológico no espera a los que se detienen.', 'Andrew Hunt', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'Piensa en el código como comunicación; primero lo escribe el programador, luego lo lee la máquina, luego otros programadores.', 'David Thomas', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'Las estimaciones son compromisos; si no puedes estimar con confianza, di que no sabes.', 'Andrew Hunt', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'El debugging es el arte de eliminar lo que no puede estar mal hasta descubrir lo que debe estar mal.', 'David Thomas', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'Un diseño ortogonal garantiza que cambiar un componente no afecte a otros; esa independencia es libertad.', 'Andrew Hunt', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'El prototipo descartable sirve para aprender; nunca entregues un prototipo como si fuera código de producción.', 'David Thomas', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'Usa versiones de control desde el primer commit; no hay excusa para trabajar sin red de seguridad histórica.', 'Andrew Hunt', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'Domina al menos un editor de texto profundamente; tu editor es la extensión de tus dedos en el código.', 'David Thomas', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'Los requisitos no se descubren; se inventan en colaboración entre el cliente y el desarrollador.', 'Andrew Hunt', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'Haz que las cosas difíciles sean fáciles de hacer bien y difíciles de hacer mal; eso es diseño de API excelente.', 'David Thomas', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'Aprende al menos un nuevo lenguaje de programación cada año; cada lenguaje te enseña a pensar de forma diferente.', 'Andrew Hunt', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),

-- Frederick Brooks (53–68)
(gen_random_uuid(), 'No hay bala de plata que elimine la complejidad esencial del software.', 'Frederick Brooks', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'Añadir personas a un proyecto tardío lo retrasa aún más.', 'Frederick Brooks', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'La complejidad del software es una propiedad esencial, no accidental; no puede diseñarse.', 'Frederick Brooks', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'Planea desechar uno; de todos modos lo harás.', 'Frederick Brooks', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'El programador, como el poeta, trabaja solo con la mente pura; construye castillos en el aire.', 'Frederick Brooks', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'Las herramientas afiladas multiplican la eficiencia del artesano; un programador sin sus herramientas es mediocre.', 'Frederick Brooks', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'El diseño del sistema debe reflejarse en la estructura del equipo que lo construye.', 'Frederick Brooks', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'La segunda versión de un sistema siempre es la más peligrosa; el diseñador quiere corregir todo y termina comprometiendo la coherencia.', 'Frederick Brooks', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'La integridad conceptual es la cualidad más importante de un diseño de sistema.', 'Frederick Brooks', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'Una especificación que no pueda ser leída por el cliente no puede ser verificada por el programador.', 'Frederick Brooks', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'El software bien diseñado es más fácil de cambiar; esa capacidad de cambio es su mayor valor a largo plazo.', 'Frederick Brooks', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'La depuración es el momento de mayor aprendizaje en la vida de un programador; no la evites, domínala.', 'Frederick Brooks', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'El buen juicio viene de la experiencia; la experiencia viene del mal juicio en proyectos anteriores.', 'Frederick Brooks', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'Mostrar el progreso del software es más difícil que mostrar el de la construcción; el software no tiene masa visible.', 'Frederick Brooks', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'El costo de mantener software mal escrito supera con creces el costo de escribirlo bien desde el principio.', 'Frederick Brooks', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'Los grandes sistemas de software son obras colectivas; la humildad técnica no es opcional, es arquitectónica.', 'Frederick Brooks', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),

-- Edsger Dijkstra (69–84)
(gen_random_uuid(), 'La prueba de que un programa es correcto sólo puede demostrar la presencia de errores, nunca su ausencia.', 'Edsger Dijkstra', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'La simplicidad es condición previa de la fiabilidad.', 'Edsger Dijkstra', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'Programar bien no es una habilidad técnica; es una forma disciplinada de pensar.', 'Edsger Dijkstra', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'El uso del goto hace que el código sea ilegible y el flujo de control inmanejable.', 'Edsger Dijkstra', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'Si la depuración es el arte de eliminar bugs, entonces programar debe ser el arte de no introducirlos.', 'Edsger Dijkstra', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'La informática no trata sobre computadoras más de lo que la astronomía trata sobre telescopios.', 'Edsger Dijkstra', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'Un programa bien estructurado es aquel que puede ser entendido en partes sin necesidad de entender el todo.', 'Edsger Dijkstra', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'La abstracción no es un lujo; es la única herramienta con la que podemos manejar la complejidad del mundo real.', 'Edsger Dijkstra', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'Las computadoras son extraordinariamente rápidas haciendo cosas extremadamente estúpidas; el programador les da inteligencia.', 'Edsger Dijkstra', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'Escribir código correcto es más difícil que parece; la única forma de hacerlo bien es pensar rigurosamente antes de escribir.', 'Edsger Dijkstra', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'El problema con los lenguajes de programación no es el lenguaje; es que los programadores no piensan antes de programar.', 'Edsger Dijkstra', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'Separar lo que cambia de lo que no cambia es la primera lección de diseño de software duradero.', 'Edsger Dijkstra', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'El código que no puede ser probado formalmente no debería considerarse correcto por defecto.', 'Edsger Dijkstra', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'La programación estructurada no es una restricción; es la liberación del caos del flujo arbitrario.', 'Edsger Dijkstra', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'Un invariante de bucle bien definido hace que la correctitud del algoritmo sea obvia, no una esperanza.', 'Edsger Dijkstra', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'La elegancia no es cosmética; en algoritmos, la elegancia es eficiencia y claridad al mismo tiempo.', 'Edsger Dijkstra', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),

-- Tony Hoare (85–97)
(gen_random_uuid(), 'Hay dos maneras de construir software: hacerlo tan simple que obviamente no haya errores, o tan complejo que no haya errores obvios.', 'Tony Hoare', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'La referencia nula fue mi error de mil millones de dólares; introducirla fue la decisión más fácil y más costosa de mi carrera.', 'Tony Hoare', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'La corrección del software no es negociable; un sistema que falla aleatoriamente no es un sistema.', 'Tony Hoare', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'La verificación formal es el único camino hacia la certeza en software crítico; la intuición no basta.', 'Tony Hoare', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'Un tipo de dato bien definido es un contrato entre el diseñador y el usuario de ese dato.', 'Tony Hoare', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'La concurrencia bien diseñada no es complicada; la concurrencia mal diseñada es imposible de depurar.', 'Tony Hoare', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'Primero haz que funcione, luego haz que sea correcto, luego haz que sea rápido; en ese orden y no en otro.', 'Tony Hoare', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'La especificación algebraica de tipos de datos abstractos es más precisa que cualquier documentación en prosa.', 'Tony Hoare', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'El debugging más efectivo es el que se hace antes de ejecutar: razonar sobre el código antes de correrlo.', 'Tony Hoare', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'La modularidad es la forma más poderosa de gestionar la complejidad en sistemas grandes.', 'Tony Hoare', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'El software seguro no accidentalmente es seguro; la seguridad debe ser diseñada desde el inicio.', 'Tony Hoare', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'Los invariantes de clase son la columna vertebral del diseño orientado a objetos correcto.', 'Tony Hoare', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'Confiar en la lógica del programa sin probarlo formalmente es como confiar en un puente sin calcularlo.', 'Tony Hoare', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),

-- Alan Kay (98–110)
(gen_random_uuid(), 'El mejor camino para predecir el futuro es inventarlo.', 'Alan Kay', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'La perspectiva vale ochenta puntos de cociente intelectual.', 'Alan Kay', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'La orientación a objetos trata los objetos como entidades que se comunican mediante mensajes, no como colecciones de datos.', 'Alan Kay', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'El software bien diseñado envejece como el buen vino; el mal software se agría como la leche.', 'Alan Kay', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'La mayoría del software de hoy es como la pirámide del antiguo Egipto: miles de trabajadores empujando bloques pero sin arquitectura real.', 'Alan Kay', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'El cambio de paradigma no es incremental; es una ruptura con la forma de pensar anterior.', 'Alan Kay', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'Smalltalk demostró que un lenguaje puede ser tan simple que cabe en una tarjeta y tan poderoso que construye sistemas completos.', 'Alan Kay', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'Las interfaces de usuario deben ser tan intuitivas que hasta un niño las use; si no, el problema es el diseño, no el usuario.', 'Alan Kay', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'La computadora personal fue concebida como un instrumento musical para la mente humana, no como una calculadora glorificada.', 'Alan Kay', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'Pensar en objetos que se envían mensajes es más natural que pensar en procedimientos que manipulan datos.', 'Alan Kay', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'La abstracción nos permite ignorar los detalles sin perder el control; esa es su magia.', 'Alan Kay', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'Un lenguaje de programación que no cambia tu forma de pensar no vale la pena aprenderlo.', 'Alan Kay', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'Las ideas realmente buenas en computación se pueden expresar en muy pocas palabras; si necesitas muchas, probablemente no estás en lo correcto.', 'Alan Kay', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),

-- Kent Beck (111–124)
(gen_random_uuid(), 'Haz que funcione, luego hazlo correcto, luego hazlo rápido.', 'Kent Beck', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'El desarrollo guiado por pruebas es un método de diseño más que de testing.', 'Kent Beck', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'Escribe la prueba más simple posible que podría fallar, luego escribe el código más simple que la haga pasar.', 'Kent Beck', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'El refactoring continuo mantiene el sistema saludable; sin él, el código se deteriora inevitablemente.', 'Kent Beck', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'La programación en parejas no reduce la velocidad; duplica la revisión y reduce los errores costosos.', 'Kent Beck', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'Integra con frecuencia; cada hora sin integración es una hora de deuda de integración acumulándose.', 'Kent Beck', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'Los smells de código son señales de que algo está mal en el diseño, no en la funcionalidad.', 'Kent Beck', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'El código más flexible no es el más genérico; es el más simple que puede ser extendido cuando sea necesario.', 'Kent Beck', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'La comunicación entre desarrolladores es tan importante como la comunicación entre módulos del sistema.', 'Kent Beck', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'Un test que tarda mucho en ejecutarse no se ejecuta; los tests deben ser rápidos para ser útiles.', 'Kent Beck', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'La confianza en el código sin tests es una ilusión; el sistema puede estar funcionando hoy y roto mañana.', 'Kent Beck', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'Un diseño simple tiene todos los tests pasando y no tiene duplicación ni oscuridad innecesaria.', 'Kent Beck', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'La valía de una suite de tests se mide por su capacidad de capturar regresiones, no por su cobertura numérica.', 'Kent Beck', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'XP no es un conjunto de prácticas; es una forma de trabajar basada en el respeto, la comunicación y la retroalimentación continua.', 'Kent Beck', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),

-- Martin Fowler (125–138)
(gen_random_uuid(), 'El refactoring es el proceso de cambiar el código de tal manera que no altere el comportamiento externo pero mejore la estructura interna.', 'Martin Fowler', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'Cualquier tonto puede escribir código que una computadora entienda; los buenos programadores escriben código que los humanos entiendan.', 'Martin Fowler', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'Si tu código necesita un comentario para entenderse, primero intenta reescribirlo para que sea autoexplicativo.', 'Martin Fowler', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'Los patrones de diseño no son recetas; son vocabulario compartido para describir soluciones a problemas recurrentes.', 'Martin Fowler', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'La arquitectura es el conjunto de decisiones de diseño que desearías haber tomado correctamente desde el principio.', 'Martin Fowler', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'La entrega continua es la capacidad de llevar cambios de software a producción de forma segura y rápida en cualquier momento.', 'Martin Fowler', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'Un microservicio bien definido puede ser reemplazado completamente sin afectar al resto del sistema.', 'Martin Fowler', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'La indirección es la herramienta del diseñador; permite cambiar implementaciones sin romper contratos.', 'Martin Fowler', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'Una buena suite de tests permite que cualquier miembro del equipo refactorice sin miedo.', 'Martin Fowler', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'El código es comunicación; cada función y variable es una declaración de intención.', 'Martin Fowler', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'La separación entre lógica de dominio e infraestructura es la diferencia entre software adaptable y software frágil.', 'Martin Fowler', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'Un modelo de dominio bien diseñado habla el idioma del negocio y lo traduce al idioma del código sin pérdida de significado.', 'Martin Fowler', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'Los patrones empresariales de arquitectura son la gramática del software a escala.', 'Martin Fowler', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'Sin disciplina de integración continua, el trabajo en paralelo genera conflictos que crecen exponencialmente con el tiempo.', 'Martin Fowler', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),

-- Linus Torvalds (139–151)
(gen_random_uuid(), 'El código que habla por sí mismo es el mejor código que existe.', 'Linus Torvalds', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'El software libre no es gratis porque no cuesta dinero; es libre porque respeta tu libertad.', 'Linus Torvalds', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'Hablar es barato. Muéstrame el código.', 'Linus Torvalds', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'El buen gusto en programación es saber cuándo un enfoque simple es mejor que uno ingenioso.', 'Linus Torvalds', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'Los sistemas operativos bien diseñados se componen de capas de abstracción cada una resolviendo un nivel de complejidad diferente.', 'Linus Torvalds', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'El código que funciona en mi máquina no es suficiente; debe funcionar en todas las máquinas del mundo.', 'Linus Torvalds', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'El control de versiones no es opcional; es tan fundamental como guardar el trabajo.', 'Linus Torvalds', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'La colaboración distribuida a escala global es posible cuando el modelo de trabajo está bien diseñado desde el inicio.', 'Linus Torvalds', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'Los bugs que no puedes reproducir son los más peligrosos; la reproducibilidad es el primer paso del debugging.', 'Linus Torvalds', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'La optimización a nivel del kernel requiere entender el hardware; sin ese conocimiento, la optimización es ciega.', 'Linus Torvalds', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'Mantener compatibilidad hacia atrás no es cobardía; es respeto por los usuarios que dependen de tu software.', 'Linus Torvalds', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'El diseño de sistemas distribuidos require pensar en los fallos como el caso normal, no como la excepción.', 'Linus Torvalds', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'Un commit pequeño y enfocado cuenta una historia clara; un commit grande y mezclado no cuenta nada.', 'Linus Torvalds', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),

-- Brian Kernighan (152–163)
(gen_random_uuid(), 'Controla la complejidad del software dividiéndola: cada parte debe ser comprensible de forma aislada.', 'Brian Kernighan', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'La depuración es dos veces más difícil que escribir el código; si escribes el código más inteligente que puedes, no podrás depurarlo.', 'Brian Kernighan', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'El lenguaje C te da la suficiente cuerda para colgarte; también para construir puentes.', 'Brian Kernighan', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'Un programa bien estructurado es más fácil de probar, mantener y extender que uno escrito sin diseño previo.', 'Brian Kernighan', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'El arte de programar incluye el arte de nombrar; los nombres reveladores son mitad del trabajo de documentación.', 'Brian Kernighan', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'Las herramientas de línea de comandos componen; los programas pequeños que hacen una cosa bien son más valiosos que los monolitos.', 'Brian Kernighan', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'El texto plano es el formato más duradero; mientras exista computación, el texto plano será legible.', 'Brian Kernighan', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'Escribe código que sea difícil de usar incorrectamente; eso vale más que cualquier documentación.', 'Brian Kernighan', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'Probar con casos extremos revela más bugs que probar con casos normales; busca los límites de tu lógica.', 'Brian Kernighan', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'La filosofía Unix de hacer una cosa bien ha demostrado ser más duradera que cualquier arquitectura monolítica.', 'Brian Kernighan', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'El código portable es código bien escrito; las suposiciones sobre el entorno son deuda oculta.', 'Brian Kernighan', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'Un buen tutorial enseña a pensar, no solo a ejecutar; los mejores tutoriales te hacen entender el por qué.', 'Brian Kernighan', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),

-- Harold Abelson (164–175)
(gen_random_uuid(), 'Los programas deben ser escritos para que la gente los lea y solo incidentalmente para que las máquinas los ejecuten.', 'Harold Abelson', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'La complejidad no es una propiedad del problema; es una propiedad del nivel de abstracción que elegimos.', 'Harold Abelson', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'La recursión es la forma más natural de describir problemas que tienen estructura autosimilar.', 'Harold Abelson', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'El lenguaje de programación es un medio de expresión del pensamiento computacional, no solo una herramienta de instrucción.', 'Harold Abelson', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'Las funciones de orden superior expresan patrones de computación que no pueden nombrarse de otra manera.', 'Harold Abelson', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'El intérprete metacircular demuestra que un lenguaje puede describirse completamente en sí mismo; esa es su mayor profundidad.', 'Harold Abelson', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'La programación funcional hace explícitas las dependencias entre datos; eso la hace más fácil de razonar.', 'Harold Abelson', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'Entender la diferencia entre procedimiento e iteración es entender la naturaleza del cálculo computacional.', 'Harold Abelson', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'La abstracción de datos separa el uso de una estructura de datos de su implementación; esa separación es poder.', 'Harold Abelson', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'El pensamiento computacional no es exclusivo de los informáticos; es una forma general de resolver problemas con precisión.', 'Harold Abelson', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'La evaluación diferida permite trabajar con estructuras de datos infinitas; es la abstracción del tiempo de computación.', 'Harold Abelson', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'Separar la descripción de un proceso de la implementación del proceso es el corazón del diseño de software.', 'Harold Abelson', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),

-- Peter Norvig (176–187)
(gen_random_uuid(), 'La IA no trata sobre simular la inteligencia humana; trata sobre resolver problemas que requieren inteligencia para resolverlos.', 'Peter Norvig', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'Programar no se aprende leyendo; se aprende escribiendo código, cometiendo errores y corrigiéndolos.', 'Peter Norvig', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'Un buen algoritmo de búsqueda define explícitamente el espacio de estados, las acciones y la función de costo.', 'Peter Norvig', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'La heurística es una estimación informada; sin ella, la búsqueda ciega en espacios grandes es inviable.', 'Peter Norvig', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'Dominar la programación requiere diez años de práctica deliberada; no hay atajos para la maestría.', 'Peter Norvig', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'La probabilidad y la estadística son las matemáticas del razonamiento bajo incertidumbre; todo programador debería conocerlas.', 'Peter Norvig', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'Los datos limpios son más valiosos que los algoritmos sofisticados; la basura entra y la basura sale.', 'Peter Norvig', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'La representación del conocimiento es la mitad del problema en inteligencia artificial; la otra mitad es el razonamiento sobre esa representación.', 'Peter Norvig', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'Entender los fundamentos matemáticos de los algoritmos permite adaptarlos a nuevos dominios; sin esa base, solo puedes copiarlos.', 'Peter Norvig', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'La complejidad computacional define los límites de lo que es posible resolver eficientemente; respétala.', 'Peter Norvig', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'Python es el idioma franco de la computación moderna; su claridad reduce la distancia entre la idea y su implementación.', 'Peter Norvig', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'Aprender a leer código de otros es tan importante como aprender a escribirlo; la comprensión de código es una habilidad separada.', 'Peter Norvig', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),

-- Steve McConnell (188–200)
(gen_random_uuid(), 'La construcción de software es el proceso más complejo y cognitivamente exigente que la humanidad ha emprendido sistemáticamente.', 'Steve McConnell', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'El código es leído diez veces más de lo que se escribe; optimiza para la lectura, no para la escritura.', 'Steve McConnell', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'Los buenos desarrolladores producen diez veces más que los mediocres no por escribir más rápido sino por tomar mejores decisiones.', 'Steve McConnell', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'La revisión de código es la práctica de calidad con mejor relación costo-beneficio en el desarrollo de software.', 'Steve McConnell', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'Un buen nombre de variable reduce el número de comentarios necesarios en al menos un cincuenta por ciento.', 'Steve McConnell', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'La gestión del alcance es la habilidad de ingeniería más valiosa y menos enseñada en las universidades.', 'Steve McConnell', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'Probar antes de codificar obliga a pensar en el comportamiento esperado; eso mejora el diseño más que cualquier patrón.', 'Steve McConnell', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'El código defensivo anticipa los usos incorrectos; cada suposición no verificada es una bomba de tiempo latente.', 'Steve McConnell', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'La pseudocodificación antes de implementar reduce los errores de lógica y clarifica el pensamiento sobre el algoritmo.', 'Steve McConnell', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'El costo de corregir un defecto crece exponencialmente cuanto más tarde se encuentra en el ciclo de desarrollo.', 'Steve McConnell', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'La complejidad ciclomática mide el número de caminos de ejecución; valores altos predicen la probabilidad de defectos.', 'Steve McConnell', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'Un buen programador es aquel que mira en ambas direcciones antes de cruzar una calle de sentido único.', 'Steve McConnell', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'Documentar las decisiones de diseño y sus razones es más valioso que documentar el código en sí.', 'Steve McConnell', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),

-- Rich Hickey (201–211)
(gen_random_uuid(), 'La simplicidad no es lo mismo que la facilidad; lo simple no está entrelazado, lo fácil es solo familiar.', 'Rich Hickey', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'El estado mutable es la fuente de la mayoría de los bugs concurrentes; la inmutabilidad los elimina por diseño.', 'Rich Hickey', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'Entrelazar conceptos en el código crea complejidad accidental que no existe en el problema original.', 'Rich Hickey', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'Los valores inmutables son más fáciles de razonar, compartir y cachear; el estado mutable tiene un costo cognitivo enorme.', 'Rich Hickey', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'El polimorfismo basado en tipos viola la separación de datos y comportamiento que hace al código realmente flexible.', 'Rich Hickey', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'Las abstracciones leaky no mienten; simplemente revelan que la abstracción es insuficiente para el problema.', 'Rich Hickey', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'La composición de funciones puras es la forma más segura de construir sistemas grandes y predecibles.', 'Rich Hickey', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'El problema con la orientación a objetos es que mezcla identidad, estado y comportamiento cuando a menudo solo necesitas uno de los tres.', 'Rich Hickey', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'Clojure no es un lenguaje de programación; es una forma de pensar sobre la información y su transformación.', 'Rich Hickey', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'El tiempo es una dimensión frecuentemente ignorada en el diseño de software; los datos cambian y el sistema debe saberlo.', 'Rich Hickey', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'Un buen diseño comienza por hacer preguntas difíciles sobre qué necesita cambiar y qué debe permanecer estable.', 'Rich Hickey', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),

-- Paul Graham (212–223)
(gen_random_uuid(), 'Los hackers son artistas; el buen código es arte funcional que deleita tanto al que lo usa como al que lo lee.', 'Paul Graham', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'La brevedad es la almendía del alma; en código, la concisión reduce los lugares donde pueden esconderse los bugs.', 'Paul Graham', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'Lisp no es solo un lenguaje; es una notación para describir algoritmos que resulta ser ejecutable.', 'Paul Graham', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'El software exitoso se construye en capas; cada capa es un lenguaje de dominio específico para la capa superior.', 'Paul Graham', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'Hacer las cosas simples que importan primero es la única forma de llegar a la complejidad que vale la pena.', 'Paul Graham', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'El prototipado rápido revela las suposiciones incorrectas antes de que se conviertan en arquitectura permanente.', 'Paul Graham', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'La elegancia del código es una señal de que el programador entendió el problema lo suficientemente bien como para resolverlo limpiamente.', 'Paul Graham', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'Los mejores programadores no son los que conocen más lenguajes; son los que conocen cuándo usar cada herramienta.', 'Paul Graham', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'La recursión no asusta a quien entiende que un problema complejo es simplemente un problema pequeño más sus variaciones.', 'Paul Graham', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'Resolver problemas difíciles hace mejores programadores; los problemas triviales producen programadores triviales.', 'Paul Graham', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'El software no envejece como el hardware; envejece como el conocimiento, que se vuelve obsoleto cuando el mundo cambia.', 'Paul Graham', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'Pensar en el usuario final mientras escribes código es la diferencia entre software que se usa y software que se tolera.', 'Paul Graham', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),

-- Eric Raymond (224–232)
(gen_random_uuid(), 'Dados suficientes ojos, todos los bugs son superficiales.', 'Eric Raymond', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'El bazar es más eficiente que la catedral para encontrar y corregir errores en software complejo.', 'Eric Raymond', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'Cada programa que usas tiene código escrito por alguien que también aprendió; ningún código nace perfecto.', 'Eric Raymond', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'La cultura hacker valora la elegancia, la ingeniosidad y la solución mínima que resuelve el problema máximo.', 'Eric Raymond', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'El principio KISS dice que los sistemas simples son más robustos que los complejos en condiciones del mundo real.', 'Eric Raymond', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'Publicar pronto, publicar frecuentemente; cada versión es retroalimentación y cada retroalimentación mejora el software.', 'Eric Raymond', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'Los programadores brillantes que resuelven solos hacen sistemas que nadie más puede mantener; la colaboración produce sistemas que todos pueden mejorar.', 'Eric Raymond', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'La filosofía Unix es acumular pequeñas herramientas que hacen una cosa bien y componer soluciones con ellas.', 'Eric Raymond', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'El código abierto no es una metodología; es una epistemología: el conocimiento mejora cuando es examinado por muchos.', 'Eric Raymond', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),

-- Jon Bentley (233–241)
(gen_random_uuid(), 'Antes de optimizar, mide; sin datos reales, la optimización es solo superstición con código.', 'Jon Bentley', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'Los problemas de programación más elegantes son aquellos donde la solución correcta es también la más simple.', 'Jon Bentley', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'El algoritmo correcto es frecuentemente mil veces más rápido que la optimización de un algoritmo incorrecto.', 'Jon Bentley', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'La estructura de datos correcta puede reducir un algoritmo de complejidad cuadrática a lineal; elige primero la estructura.', 'Jon Bentley', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'Programar perlas son soluciones elegantes a problemas difíciles; encontrarlas requiere pensamiento profundo, no código rápido.', 'Jon Bentley', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'Escribir el programa más simple que resuelve el problema es más difícil que escribir el más complicado.', 'Jon Bentley', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'Entender el problema antes de escribir una sola línea de código multiplica la calidad del resultado final.', 'Jon Bentley', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'La búsqueda binaria es la demostración más pura de que dividir el problema a la mitad resuelve exponencialmente más rápido.', 'Jon Bentley', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'El software de calidad no es aquel que no tiene bugs; es aquel donde los bugs no pueden sobrevivir mucho tiempo.', 'Jon Bentley', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),

-- John Carmack (242–250)
(gen_random_uuid(), 'El rendimiento es una característica; si no mides, no puedes mejorar lo que no ves.', 'John Carmack', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'La programación de bajo nivel revela verdades que la abstracción oculta; conocer el hardware es conocer los límites reales.', 'John Carmack', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'Iterar rápidamente sobre ideas es la única forma de descubrir cuáles son realmente buenas y cuáles solo parecen buenas.', 'John Carmack', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'El código legible no es solo un estándar de cortesía; es una estrategia de mantenimiento a largo plazo.', 'John Carmack', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'La optimización de sistemas de tiempo real requiere entender no solo el algoritmo sino el modelo de memoria del hardware.', 'John Carmack', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'Los mejores programas de videojuegos son arte de ingeniería: cada ciclo de CPU contado, cada byte de memoria justificado.', 'John Carmack', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'La determinación de resolver un problema difícil, combinada con el rigor de no aceptar soluciones a medias, produce código excelente.', 'John Carmack', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'El profiler es el instrumento del programador que busca la verdad sobre el rendimiento; sin él, todo es especulación.', 'John Carmack', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'Construir sistemas en tiempo real enseña que cada decisión de diseño tiene un costo medible; esa disciplina mejora todo el código que escribes después.', 'John Carmack', 'philosophy', 'es', 'down', 'free', false, 'coding', 'fundamentals', ARRAY['discipline','learning'], true, 'coding')

ON CONFLICT (text, author) DO NOTHING;

COMMIT;
