-- 044_coding_devops_es.sql
-- MindScrolling — Coding Mode: DevOps & Tools batch (Spanish)
-- 250 quotes: CI/CD, Docker, Kubernetes, monitoreo, logging, infraestructura como código,
--   cloud computing, git, pipelines de testing, automatización, SRE, respuesta a incidentes,
--   observabilidad, rendimiento, estrategias de despliegue
--
-- All rows:
--   category       = 'philosophy'
--   lang           = 'es'
--   swipe_dir      = 'down'
--   pack_name      = 'free'
--   is_premium     = false
--   content_type   = 'coding'
--   sub_category   = 'devops_tools'
--   is_hidden_mode = true
--   locked_by      = 'coding'
-- Run in Supabase SQL Editor

BEGIN;

-- ══════════════════════════════════════════════════════════════════════════════
-- CODING DEVOPS & TOOLS — SPANISH (250 quotes)
-- ══════════════════════════════════════════════════════════════════════════════

INSERT INTO quotes (id, text, author, category, lang, swipe_dir, pack_name, is_premium, content_type, sub_category, tags, is_hidden_mode, locked_by) VALUES

-- Gene Kim (1–14)
(gen_random_uuid(), 'Mejorar el trabajo diario es incluso más importante que hacer el trabajo diario.', 'Gene Kim', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','focus'], true, 'coding'),
(gen_random_uuid(), 'El trabajo no planificado siempre cuesta más que el trabajo planificado.', 'Gene Kim', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'La deuda técnica es como la deuda financiera. Si no pagas el capital, pagarás intereses para siempre.', 'Gene Kim', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'Hasta que el código no está en producción, no se genera valor real. Solo es trabajo en progreso atascado en el sistema.', 'Gene Kim', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','focus'], true, 'coding'),
(gen_random_uuid(), 'El mayor riesgo en DevOps es no moverse con suficiente rapidez.', 'Gene Kim', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['courage','discipline'], true, 'coding'),
(gen_random_uuid(), 'Esperar la solución perfecta es en sí misma una forma de desperdicio.', 'Gene Kim', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','focus'], true, 'coding'),
(gen_random_uuid(), 'Las restricciones dictan dónde enfocar los esfuerzos de mejora. Encuentra el cuello de botella y explótalo.', 'Gene Kim', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'La resiliencia se construye practicando el fallo antes de que te ocurra.', 'Gene Kim', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','courage'], true, 'coding'),
(gen_random_uuid(), 'El objetivo no es eliminar el cambio, sino poder gestionarlo con elegancia.', 'Gene Kim', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'La automatización no consiste en reemplazar personas. Consiste en liberar a las personas para trabajo de mayor valor.', 'Gene Kim', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','focus'], true, 'coding'),
(gen_random_uuid(), 'Los lotes pequeños reducen la variabilidad y hacen visibles los problemas antes.', 'Gene Kim', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','focus'], true, 'coding'),
(gen_random_uuid(), 'Todo negocio es un negocio de software. Debes empezar a pensar y actuar como una empresa digital.', 'Gene Kim', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','learning'], true, 'coding'),
(gen_random_uuid(), 'Cuando las cosas salen mal, y siempre lo harán, la pregunta es: ¿con qué rapidez puedes detectar y solucionar el problema?', 'Gene Kim', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'El primer camino enfatiza el rendimiento del sistema completo, no el rendimiento de un silo de trabajo específico.', 'Gene Kim', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','wisdom'], true, 'coding'),

-- Jez Humble (15–28)
(gen_random_uuid(), 'El mayor riesgo en el desarrollo de software es construir algo que nadie quiere.', 'Jez Humble', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'La entrega continua es la capacidad de llevar cambios de todo tipo a producción de forma segura, rápida y sostenible.', 'Jez Humble', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','focus'], true, 'coding'),
(gen_random_uuid(), 'Cada construcción debe estar lista para producción. Si tu software no es desplegable en todo momento, acumulas riesgo.', 'Jez Humble', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'La integración continua no es una herramienta, es una disciplina.', 'Jez Humble', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','focus'], true, 'coding'),
(gen_random_uuid(), 'Integrar menos frecuentemente no reduce el riesgo, lo aumenta enormemente.', 'Jez Humble', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'Las pruebas automatizadas son el fundamento de la entrega continua. Sin ellas, nada más funciona.', 'Jez Humble', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','focus'], true, 'coding'),
(gen_random_uuid(), 'El despliegue debe ser un evento aburrido y rutinario, no un momento de terror.', 'Jez Humble', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'Si duele, hazlo más frecuentemente. El dolor desaparece cuando lo practicas constantemente.', 'Jez Humble', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','courage'], true, 'coding'),
(gen_random_uuid(), 'La calidad no se puede inspeccionar a posteriori. Debe construirse desde el inicio.', 'Jez Humble', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'Un pipeline de despliegue convierte cada commit en un candidato para producción.', 'Jez Humble', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','focus'], true, 'coding'),
(gen_random_uuid(), 'La verdadera agilidad requiere que puedas liberar software en cualquier momento.', 'Jez Humble', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'Reducir el tamaño de los lotes reduce el riesgo y acelera el feedback.', 'Jez Humble', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','focus'], true, 'coding'),
(gen_random_uuid(), 'El trabajo en progreso es inventario. El inventario es riesgo. Minimiza ambos.', 'Jez Humble', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'La infraestructura como código permite aplicar las mismas prácticas de ingeniería al aprovisionamiento que al software.', 'Jez Humble', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','learning'], true, 'coding'),

-- Patrick Debois (29–41)
(gen_random_uuid(), 'DevOps no es un rol, es una mentalidad de colaboración entre desarrollo y operaciones.', 'Patrick Debois', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'La cultura es el ingrediente más difícil de cambiar en cualquier transformación DevOps.', 'Patrick Debois', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','learning'], true, 'coding'),
(gen_random_uuid(), 'Los silos entre dev y ops son la raíz de la mayoría de los problemas de entrega de software.', 'Patrick Debois', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'La empatía entre equipos de desarrollo y operaciones es más valiosa que cualquier herramienta.', 'Patrick Debois', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'Automatizar el despliegue es el primer paso para recuperar el control del proceso de entrega.', 'Patrick Debois', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','focus'], true, 'coding'),
(gen_random_uuid(), 'DevOps es el resultado lógico de aplicar pensamiento Agile a las operaciones de TI.', 'Patrick Debois', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','learning'], true, 'coding'),
(gen_random_uuid(), 'La confianza entre equipos se construye con transparencia, no con promesas.', 'Patrick Debois', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'El monitoreo no es opcional. Es la diferencia entre reaccionar y anticipar.', 'Patrick Debois', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'Cada incidente es una oportunidad de aprendizaje. Culpar a las personas destruye ese aprendizaje.', 'Patrick Debois', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','learning'], true, 'coding'),
(gen_random_uuid(), 'El flujo de valor del software va desde la idea hasta el usuario. DevOps optimiza ese flujo completo.', 'Patrick Debois', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'Compartir el dolor del despliegue entre dev y ops es el primer paso hacia la responsabilidad compartida.', 'Patrick Debois', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','courage'], true, 'coding'),
(gen_random_uuid(), 'Las retrospectivas sin acción son solo terapia de grupo. La mejora requiere cambios concretos.', 'Patrick Debois', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','focus'], true, 'coding'),
(gen_random_uuid(), 'No existe una transformación DevOps sin cambiar la forma en que los equipos se comunican.', 'Patrick Debois', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','learning'], true, 'coding'),

-- Werner Vogels (42–55)
(gen_random_uuid(), 'Todo falla, todo el tiempo. Diseña sistemas que lo asuman.', 'Werner Vogels', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'La disponibilidad es el resultado de disciplina de ingeniería, no de suerte.', 'Werner Vogels', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'Los microservicios te dan independencia de despliegue. Esa independencia tiene un precio en complejidad.', 'Werner Vogels', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','learning'], true, 'coding'),
(gen_random_uuid(), 'La escalabilidad no es solo un problema técnico. Es también un problema organizacional.', 'Werner Vogels', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'Operar a escala significa que los problemas que antes eran hipotéticos se vuelven cotidianos.', 'Werner Vogels', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','learning'], true, 'coding'),
(gen_random_uuid(), 'La nube no elimina los problemas de infraestructura. Los transforma.', 'Werner Vogels', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'Construir para el fallo no es pesimismo. Es ingeniería responsable.', 'Werner Vogels', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'La consistencia eventual es una concesión consciente a la disponibilidad y la partición.', 'Werner Vogels', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','learning'], true, 'coding'),
(gen_random_uuid(), 'Si no puedes medir el rendimiento, no puedes mejorarlo. Instrumenta todo.', 'Werner Vogels', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','focus'], true, 'coding'),
(gen_random_uuid(), 'Los equipos que poseen sus servicios de extremo a extremo despliegan con más confianza.', 'Werner Vogels', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'La resiliencia del sistema se prueba bajo condiciones reales, no en reuniones de planificación.', 'Werner Vogels', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','courage'], true, 'coding'),
(gen_random_uuid(), 'El aislamiento de fallos es una característica de diseño, no una corrección posterior.', 'Werner Vogels', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'Los disyuntores en software hacen lo mismo que en electricidad: evitan que un fallo destruya todo el sistema.', 'Werner Vogels', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','learning'], true, 'coding'),
(gen_random_uuid(), 'La arquitectura distribuida requiere pensar de forma diferente sobre el estado, el tiempo y el fallo.', 'Werner Vogels', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),

-- Charity Majors (56–69)
(gen_random_uuid(), 'La observabilidad es la capacidad de hacer preguntas que nunca habías previsto sobre tus sistemas en producción.', 'Charity Majors', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','learning'], true, 'coding'),
(gen_random_uuid(), 'El monitoreo te dice que algo está mal. La observabilidad te dice por qué.', 'Charity Majors', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'Los ingenieros deberían poseer sus sistemas en producción. Esa propiedad genera responsabilidad real.', 'Charity Majors', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','courage'], true, 'coding'),
(gen_random_uuid(), 'La producción es la única fuente de verdad. Todo lo demás es suposición.', 'Charity Majors', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'Los tests son necesarios pero no suficientes. La confianza real viene de observar el comportamiento en producción.', 'Charity Majors', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'Un sistema opaco es un sistema que falla sin aviso. La instrumentación convierte lo opaco en transparente.', 'Charity Majors', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','focus'], true, 'coding'),
(gen_random_uuid(), 'Los eventos estructurados de alta cardinalidad son la base de la observabilidad real.', 'Charity Majors', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'Depurar en producción no es un pecado. Es una habilidad que todo ingeniero debe dominar.', 'Charity Majors', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['courage','learning'], true, 'coding'),
(gen_random_uuid(), 'El tiempo medio de detección es tan importante como el tiempo medio de resolución. Detectar rápido es la mitad de la batalla.', 'Charity Majors', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','focus'], true, 'coding'),
(gen_random_uuid(), 'Los sistemas sociotécnicos fallan de formas sociotécnicas. Las herramientas solas no resuelven problemas culturales.', 'Charity Majors', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','learning'], true, 'coding'),
(gen_random_uuid(), 'Los despliegues frecuentes y pequeños son más seguros que los despliegues grandes e infrecuentes.', 'Charity Majors', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','focus'], true, 'coding'),
(gen_random_uuid(), 'La cultura de no culpar no significa ignorar los fallos. Significa aprender de ellos sin destruir a las personas.', 'Charity Majors', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','courage'], true, 'coding'),
(gen_random_uuid(), 'Las alertas que nadie responde son ruido. Las alertas accionables son las únicas que importan.', 'Charity Majors', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','focus'], true, 'coding'),
(gen_random_uuid(), 'La experiencia del desarrollador en producción define la calidad del software que produce.', 'Charity Majors', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),

-- Kelsey Hightower (70–83)
(gen_random_uuid(), 'Kubernetes no es la solución a todos tus problemas. Pero te da las herramientas para construir soluciones.', 'Kelsey Hightower', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','learning'], true, 'coding'),
(gen_random_uuid(), 'La abstracción correcta en la nube es aquella que oculta la complejidad sin ocultar el control.', 'Kelsey Hightower', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'Los contenedores son la unidad de despliegue del futuro. Estandarizan el empaquetado de aplicaciones.', 'Kelsey Hightower', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'La orquestación de contenedores existe para gestionar la complejidad que los contenedores introducen a escala.', 'Kelsey Hightower', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'Antes de adoptar Kubernetes, pregúntate si realmente necesitas lo que ofrece. La simplicidad tiene valor.', 'Kelsey Hightower', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'La infraestructura inmutable elimina la categoría entera de problemas de deriva de configuración.', 'Kelsey Hightower', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'El operador de Kubernetes extiende la API para automatizar el conocimiento operacional específico del dominio.', 'Kelsey Hightower', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'Los límites de recursos en Kubernetes no son opcionales. Son la diferencia entre un clúster estable y el caos.', 'Kelsey Hightower', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','focus'], true, 'coding'),
(gen_random_uuid(), 'GitOps convierte el repositorio de código en la fuente única de verdad para el estado del sistema.', 'Kelsey Hightower', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'La computación sin servidor no elimina los servidores. Los abstrae para que no tengas que gestionarlos.', 'Kelsey Hightower', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','learning'], true, 'coding'),
(gen_random_uuid(), 'La red en sistemas distribuidos es el componente más impredecible. Diseña asumiendo que fallará.', 'Kelsey Hightower', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'La declaración del estado deseado es más poderosa que la instrucción imperativa del estado alcanzado.', 'Kelsey Hightower', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'Los namespaces de Kubernetes son fronteras de organización, no fronteras de seguridad fuertes.', 'Kelsey Hightower', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'Aprender las bases de Linux y redes es prerequisito para dominar cualquier plataforma de contenedores.', 'Kelsey Hightower', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','learning'], true, 'coding'),

-- John Allspaw (84–96)
(gen_random_uuid(), 'Las revisiones post-incidente sin culpa producen más aprendizaje que las investigaciones punitivas.', 'John Allspaw', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','learning'], true, 'coding'),
(gen_random_uuid(), 'La ingeniería de operaciones es una disciplina técnica seria, no el trabajo de los que no saben programar.', 'John Allspaw', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'Los sistemas complejos no fallan por una sola causa. Fallan por la convergencia de múltiples factores latentes.', 'John Allspaw', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','learning'], true, 'coding'),
(gen_random_uuid(), 'La capacidad de adaptación es más valiosa que la robustez. Los sistemas adaptativos sobreviven a los fallos inesperados.', 'John Allspaw', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','courage'], true, 'coding'),
(gen_random_uuid(), 'El conocimiento de cómo funciona el sistema en producción vive en las mentes de los ingenieros, no en la documentación.', 'John Allspaw', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','learning'], true, 'coding'),
(gen_random_uuid(), 'La capacidad de despliegue y la capacidad de reversión son dos caras de la misma moneda.', 'John Allspaw', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'Operar a alta velocidad requiere construir confianza a través de la consistencia repetida, no de la certeza absoluta.', 'John Allspaw', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'Los ingenieros que comprenden las limitaciones del sistema toman mejores decisiones bajo presión.', 'John Allspaw', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'El aprendizaje organizacional después de un incidente requiere entender qué funcionó, no solo qué falló.', 'John Allspaw', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','learning'], true, 'coding'),
(gen_random_uuid(), 'La resiliencia no es la ausencia de fallos. Es la capacidad de recuperarse de ellos con gracia.', 'John Allspaw', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','courage'], true, 'coding'),
(gen_random_uuid(), 'Los runbooks son valiosos cuando están desactualizados porque muestran cómo el sistema ha cambiado.', 'John Allspaw', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','learning'], true, 'coding'),
(gen_random_uuid(), 'La comunicación durante un incidente es tan importante como las acciones técnicas tomadas.', 'John Allspaw', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'Los sistemas distribuidos tienen propiedades emergentes que no se pueden predecir solo con pruebas unitarias.', 'John Allspaw', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','learning'], true, 'coding'),

-- Martin Fowler (97–111)
(gen_random_uuid(), 'Cualquier tonto puede escribir código que un computador entiende. Los buenos programadores escriben código que los humanos pueden entender.', 'Martin Fowler', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'La refactorización continua es el mantenimiento preventivo del software. Ignorarla genera deuda técnica acumulada.', 'Martin Fowler', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','focus'], true, 'coding'),
(gen_random_uuid(), 'La entrega continua requiere que tu rama principal siempre esté en estado desplegable.', 'Martin Fowler', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'Los microservicios son una opción de arquitectura con beneficios y costos reales. No son una solución universal.', 'Martin Fowler', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'Una buena arquitectura maximiza las decisiones que no necesitas tomar hoy.', 'Martin Fowler', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'Las pruebas de integración son más valiosas que las unitarias cuando el contrato entre sistemas es la fuente de bugs.', 'Martin Fowler', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'El trunk-based development reduce la carga cognitiva de gestionar ramas de larga duración.', 'Martin Fowler', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','focus'], true, 'coding'),
(gen_random_uuid(), 'Los feature flags permiten separar el despliegue del lanzamiento. Son una herramienta poderosa de gestión de riesgo.', 'Martin Fowler', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'Un monolito bien estructurado es preferible a un conjunto de microservicios mal diseñados.', 'Martin Fowler', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'El código es el único documento que refleja con exactitud lo que el sistema hace realmente.', 'Martin Fowler', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'Los patrones de diseño son vocabulario compartido para discutir soluciones a problemas recurrentes de arquitectura.', 'Martin Fowler', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','learning'], true, 'coding'),
(gen_random_uuid(), 'La integración continua es una práctica, no una herramienta. Las herramientas solo la facilitan.', 'Martin Fowler', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','focus'], true, 'coding'),
(gen_random_uuid(), 'Los contratos entre microservicios son tan importantes como los contratos en el código orientado a objetos.', 'Martin Fowler', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'La arquitectura evolutiva acepta que los requisitos cambiarán y diseña para facilitar ese cambio.', 'Martin Fowler', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','learning'], true, 'coding'),
(gen_random_uuid(), 'Un pipeline de CI que tarda más de diez minutos deja de ser una red de seguridad y se convierte en un obstáculo.', 'Martin Fowler', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','focus'], true, 'coding'),

-- Eric Raymond (112–122)
(gen_random_uuid(), 'Con suficientes ojos, todos los bugs son superficiales. La revisión abierta es el mejor sistema de control de calidad.', 'Eric Raymond', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','learning'], true, 'coding'),
(gen_random_uuid(), 'Lanza pronto, lanza frecuentemente. Escucha a tus usuarios y desarrolla en abierto.', 'Eric Raymond', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','courage'], true, 'coding'),
(gen_random_uuid(), 'Cuando ya no tienes nada que perder, el código abierto se convierte en la estrategia más racional.', 'Eric Raymond', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','courage'], true, 'coding'),
(gen_random_uuid(), 'Diseña cada programa para que haga una cosa y la haga bien. Combínalos para hacer tareas complejas.', 'Eric Raymond', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'La cultura hacker es fundamentalmente una cultura meritocrática. Lo que importa es lo que produces.', 'Eric Raymond', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'Repara lo que está roto. El pragmatismo es la virtud central del buen programador de sistemas.', 'Eric Raymond', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','courage'], true, 'coding'),
(gen_random_uuid(), 'Los datos buenos dominan sobre los algoritmos inteligentes. Conoce tus datos antes de optimizar el código.', 'Eric Raymond', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'La transparencia del código fuente es el fundamento de la confianza en el software que ejecuta infraestructura crítica.', 'Eric Raymond', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'Documenta el por qué, no el qué. El código ya explica el qué. El comentario debe explicar la intención.', 'Eric Raymond', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'Los mejores programas crecen desde necesidades reales, no desde especificaciones abstractas.', 'Eric Raymond', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','learning'], true, 'coding'),
(gen_random_uuid(), 'La modularidad reduce la complejidad. Cada módulo debe tener una responsabilidad clara y una interfaz pequeña.', 'Eric Raymond', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','wisdom'], true, 'coding'),

-- Linus Torvalds (123–134)
(gen_random_uuid(), 'El software es como el sexo: es mejor cuando es libre.', 'Linus Torvalds', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','courage'], true, 'coding'),
(gen_random_uuid(), 'Git no es solo control de versiones. Es la manera en que coordinamos el trabajo distribuido a escala global.', 'Linus Torvalds', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'La única forma de hacer un buen trabajo es comprometerte completamente con la excelencia técnica.', 'Linus Torvalds', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','focus'], true, 'coding'),
(gen_random_uuid(), 'El kernel de Linux prueba que la colaboración masiva distribuida puede producir software de calidad superior.', 'Linus Torvalds', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','learning'], true, 'coding'),
(gen_random_uuid(), 'Los mensajes de commit son cartas al futuro. Escríbelos como si importaran, porque importarán.', 'Linus Torvalds', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'La correctitud es más importante que el rendimiento. Optimiza después de que funcione correctamente.', 'Linus Torvalds', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'Los parches son la moneda de confianza en el desarrollo de software abierto. Envía parches buenos, gana reputación.', 'Linus Torvalds', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'La compatibilidad hacia atrás no es una limitación. Es una promesa a todos los que dependen de ti.', 'Linus Torvalds', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'El peor código que he visto siempre viene de personas que tratan de demostrar cuán inteligentes son.', 'Linus Torvalds', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'La ramificación en git es barata. Úsala con generosidad para aislar experimentos del trabajo estable.', 'Linus Torvalds', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','focus'], true, 'coding'),
(gen_random_uuid(), 'Un sistema operativo no es grande. Es una colección de pequeños programas bien diseñados que trabajan juntos.', 'Linus Torvalds', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'El código abierto prospera porque la reputación es más valiosa que el dinero en las comunidades técnicas.', 'Linus Torvalds', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','learning'], true, 'coding'),

-- Dennis Ritchie & Ken Thompson (135–144)
(gen_random_uuid(), 'UNIX es básicamente un sistema operativo simple, pero tienes que ser un genio para entender su simplicidad.', 'Dennis Ritchie', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'El lenguaje C fue diseñado para dar al programador el control total del hardware sin sacrificar la portabilidad.', 'Dennis Ritchie', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','learning'], true, 'coding'),
(gen_random_uuid(), 'La elegancia de UNIX proviene de su filosofía: herramientas pequeñas, bien definidas, combinables entre sí.', 'Dennis Ritchie', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'La verdadera portabilidad proviene de principios de diseño sólidos, no de capas de abstracción superficiales.', 'Dennis Ritchie', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'Los sistemas que sobreviven décadas lo hacen porque sus creadores tuvieron la humildad de diseñarlos para el cambio.', 'Ken Thompson', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'Cuando tienes dudas entre dos diseños, elige el más simple. La simplicidad es difícil de lograr y fácil de destruir.', 'Ken Thompson', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'El shell de UNIX fue la primera interfaz de programación de alto nivel. Su poder reside en la composición.', 'Ken Thompson', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','learning'], true, 'coding'),
(gen_random_uuid(), 'Los pipes de UNIX son la implementación más elegante del principio de composición en sistemas operativos.', 'Ken Thompson', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'Un lenguaje de programación que no te hace pensar diferente sobre el mundo no vale la pena aprenderlo.', 'Ken Thompson', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','learning'], true, 'coding'),
(gen_random_uuid(), 'La abstracción de archivos de UNIX unifica el acceso a dispositivos, redes y datos bajo una sola interfaz.', 'Ken Thompson', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),

-- Rob Pike (145–155)
(gen_random_uuid(), 'La claridad es un objetivo de diseño. Un código claro no necesita comentarios extensos para ser entendido.', 'Rob Pike', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'La concurrencia no es paralelismo. Entender la diferencia es fundamental para diseñar sistemas correctos.', 'Rob Pike', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','learning'], true, 'coding'),
(gen_random_uuid(), 'No te comuniques compartiendo memoria. Comparte memoria comunicándote. Los canales son más seguros que los mutex.', 'Rob Pike', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'Los errores en Go son valores. Tratarlos como excepciones oculta la lógica del flujo de control.', 'Rob Pike', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'La complejidad que no se puede eliminar debe ser gestionada. Nunca ignorada.', 'Rob Pike', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'El diseño de interfaces es más importante que el diseño de implementaciones. Las interfaces son promesas.', 'Rob Pike', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'La legibilidad del código es una propiedad del equipo, no del individuo. Escribe para quien venga después.', 'Rob Pike', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'Go fue diseñado para que la escala humana del desarrollo fuera tan importante como la escala técnica del sistema.', 'Rob Pike', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','learning'], true, 'coding'),
(gen_random_uuid(), 'Los goroutines son baratos de crear pero costosos de no sincronizar. Usa los canales con disciplina.', 'Rob Pike', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','focus'], true, 'coding'),
(gen_random_uuid(), 'La herramienta correcta para el trabajo correcto. No apliques la misma solución a todos los problemas.', 'Rob Pike', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'La depuración es difícil. Escribe código que haga la depuración innecesaria con claridad y contratos explícitos.', 'Rob Pike', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','wisdom'], true, 'coding'),

-- Brian Kernighan (156–165)
(gen_random_uuid(), 'El control de la complejidad es la esencia de la programación informática.', 'Brian Kernighan', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'La depuración es el doble de difícil que escribir el código. Si escribes el código más inteligente que puedes, no puedes depurarlo.', 'Brian Kernighan', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'Escribe código para que funcione primero. Luego mídelo. Optimiza solo lo que la medición señala.', 'Brian Kernighan', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'Un programa que funciona incorrectamente de forma silenciosa es más peligroso que uno que falla con ruido.', 'Brian Kernighan', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'La notación influye en el pensamiento. Un buen lenguaje te permite expresar ideas que de otro modo serían inexpresables.', 'Brian Kernighan', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','learning'], true, 'coding'),
(gen_random_uuid(), 'Cada programa tiene al menos un bug. Cada programa se puede acortar al menos un carácter. Por inducción, todo programa se puede reducir a un carácter que no funciona.', 'Brian Kernighan', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'Usa herramientas para amplificar tu inteligencia. Los buenos ingenieros construyen y usan herramientas con fervor.', 'Brian Kernighan', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'Las expresiones regulares son una herramienta de procesamiento de texto poderosa. Dominarlas multiplica tu productividad.', 'Brian Kernighan', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'El estilo de programación uniforme dentro de un proyecto es más importante que el estilo personalmente preferido.', 'Brian Kernighan', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'Aprende a usar la línea de comandos con fluidez. La automatización de tareas repetitivas es una inversión que siempre rentabiliza.', 'Brian Kernighan', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','focus'], true, 'coding'),

-- Mitchell Hashimoto (166–177)
(gen_random_uuid(), 'La infraestructura como código permite aplicar revisión de pares, control de versiones y pruebas al aprovisionamiento.', 'Mitchell Hashimoto', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'Terraform hace que el estado deseado de la infraestructura sea explícito, versionable y reproducible.', 'Mitchell Hashimoto', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','focus'], true, 'coding'),
(gen_random_uuid(), 'Vagrant eliminó la excusa de "funciona en mi máquina" al estandarizar los entornos de desarrollo.', 'Mitchell Hashimoto', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'El plan de Terraform antes del apply es la diferencia entre cambiar infraestructura con confianza e improvisación.', 'Mitchell Hashimoto', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','focus'], true, 'coding'),
(gen_random_uuid(), 'Vault resuelve el problema de los secretos de forma sistémica. No escondas credenciales en archivos de configuración.', 'Mitchell Hashimoto', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'Los módulos de Terraform promueven la reutilización y los estándares de infraestructura en toda la organización.', 'Mitchell Hashimoto', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','focus'], true, 'coding'),
(gen_random_uuid(), 'La destrucción y recreación de infraestructura debe ser un proceso rutinario, no un evento traumático.', 'Mitchell Hashimoto', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','courage'], true, 'coding'),
(gen_random_uuid(), 'Packer permite crear imágenes de máquina idénticas para múltiples plataformas desde una sola configuración fuente.', 'Mitchell Hashimoto', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'El state de Terraform es el mapa de la realidad. Gestionarlo con cuidado es tan importante como el código mismo.', 'Mitchell Hashimoto', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'La detección de cambios en infraestructura debe ser continua, no solo en el momento del despliegue.', 'Mitchell Hashimoto', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','focus'], true, 'coding'),
(gen_random_uuid(), 'Los proveedores de Terraform son la interfaz entre tu código declarativo y las APIs del mundo real.', 'Mitchell Hashimoto', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'El principio de mínimo privilegio debe aplicarse a toda infraestructura. No solo a usuarios, también a servicios.', 'Mitchell Hashimoto', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','wisdom'], true, 'coding'),

-- Solomon Hykes (178–188)
(gen_random_uuid(), 'Docker democratizó el empaquetado de aplicaciones al hacer que los contenedores fueran accesibles para todos.', 'Solomon Hykes', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','learning'], true, 'coding'),
(gen_random_uuid(), 'El problema de "funciona en mi máquina" desaparece cuando empaquetas la aplicación con todas sus dependencias.', 'Solomon Hykes', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'Los contenedores son la unidad estándar de software que puede ejecutarse de forma confiable en cualquier entorno.', 'Solomon Hykes', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','focus'], true, 'coding'),
(gen_random_uuid(), 'Docker Compose permite describir aplicaciones multi-contenedor como código versionable y reproducible.', 'Solomon Hykes', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'Los registros de contenedores son la infraestructura de distribución de software del siglo XXI.', 'Solomon Hykes', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','learning'], true, 'coding'),
(gen_random_uuid(), 'El aislamiento de procesos en contenedores no es solo seguridad. Es también claridad arquitectural.', 'Solomon Hykes', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'Un Dockerfile es la receta reproducible para construir un entorno de ejecución controlado y versionado.', 'Solomon Hykes', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','focus'], true, 'coding'),
(gen_random_uuid(), 'Las capas de imagen de Docker son la implementación del principio DRY aplicado a la distribución de software.', 'Solomon Hykes', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'La estandarización del contenedor fue lo que hizo posible el ecosistema de orquestación que vino después.', 'Solomon Hykes', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','learning'], true, 'coding'),
(gen_random_uuid(), 'Las imágenes de contenedores inmutables son la base de los despliegues reproducibles y reversibles.', 'Solomon Hykes', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'La portabilidad real del software requiere empaquetar no solo el código sino también el entorno de ejecución.', 'Solomon Hykes', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','wisdom'], true, 'coding'),

-- Adrian Cockcroft (189–200)
(gen_random_uuid(), 'Netflix demostró que los microservicios a escala masiva son viables con la arquitectura correcta.', 'Adrian Cockcroft', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','learning'], true, 'coding'),
(gen_random_uuid(), 'La ingeniería del caos no es sabotaje. Es la práctica de descubrir debilidades antes de que el caos real las encuentre.', 'Adrian Cockcroft', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','courage'], true, 'coding'),
(gen_random_uuid(), 'La arquitectura de microservicios requiere madurez operacional que los equipos pequeños a menudo subestiman.', 'Adrian Cockcroft', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'Los servicios bien diseñados tienen límites claros que mapean con precisión a las capacidades del negocio.', 'Adrian Cockcroft', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'La nube no es solo infraestructura. Es una plataforma que cambia la forma en que construyes y operas software.', 'Adrian Cockcroft', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','learning'], true, 'coding'),
(gen_random_uuid(), 'Los equipos de dos pizzas de Amazon son la expresión organizacional del principio de responsabilidad única.', 'Adrian Cockcroft', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'La degradación elegante es más valiosa que la disponibilidad total. Decide qué puede fallar sin destruir la experiencia.', 'Adrian Cockcroft', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'Los patrones de resiliencia como bulkheads y circuit breakers son la arquitectura de la tolerancia a fallos.', 'Adrian Cockcroft', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'La velocidad de despliegue es una métrica de salud organizacional, no solo técnica.', 'Adrian Cockcroft', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'El monitoreo distribuido requiere correlacionar eventos de múltiples fuentes. El trazado distribuido hace esto posible.', 'Adrian Cockcroft', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'Las organizaciones que adoptan la nube solo para ahorrar costos pierden sus beneficios más importantes.', 'Adrian Cockcroft', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'La agilidad en la nube proviene de la capacidad de experimentar rápidamente con nuevas arquitecturas sin inversión masiva.', 'Adrian Cockcroft', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','courage'], true, 'coding'),

-- Richard Stallman (201–208)
(gen_random_uuid(), 'El software libre no significa que no cueste dinero. Significa que el usuario tiene libertad sobre él.', 'Richard Stallman', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','courage'], true, 'coding'),
(gen_random_uuid(), 'Copyleft es la forma de usar el copyright para garantizar que el software libre permanezca libre.', 'Richard Stallman', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'La libertad de estudiar cómo funciona un programa y adaptarlo es fundamental para el conocimiento técnico.', 'Richard Stallman', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','learning'], true, 'coding'),
(gen_random_uuid(), 'La infraestructura crítica construida sobre software propietario crea dependencias que vulneran la soberanía tecnológica.', 'Richard Stallman', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','courage'], true, 'coding'),
(gen_random_uuid(), 'Compartir el código es el acto más natural de cooperación entre programadores. Las restricciones artificiales son el problema.', 'Richard Stallman', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'GNU fue una demostración de que un sistema completo puede construirse por cooperación voluntaria sin jerarquía corporativa.', 'Richard Stallman', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','courage'], true, 'coding'),
(gen_random_uuid(), 'Las cuatro libertades del software libre son las bases de una infraestructura tecnológica soberana y auditable.', 'Richard Stallman', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'El derecho a modificar el software que usas es tan fundamental como el derecho a reparar los objetos que posees.', 'Richard Stallman', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','courage'], true, 'coding'),

-- Larry Wall (209–215)
(gen_random_uuid(), 'Las tres virtudes del programador son la pereza, la impaciencia y la arrogancia. En ese orden preciso.', 'Larry Wall', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'Hay más de una forma de hacerlo. La flexibilidad en el diseño de lenguajes permite expresividad real.', 'Larry Wall', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','learning'], true, 'coding'),
(gen_random_uuid(), 'Perl fue diseñado para hacer fácil las cosas fáciles y posible las cosas difíciles, no para hacer todo igual de difícil.', 'Larry Wall', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'La automatización de tareas repetitivas es la primera aplicación de la pereza productiva del programador.', 'Larry Wall', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','focus'], true, 'coding'),
(gen_random_uuid(), 'Los scripts de shell son el pegamento que une las herramientas de UNIX en flujos de trabajo automatizados.', 'Larry Wall', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'El procesamiento de texto es el trabajo central del sistema operativo. Dominarlo es dominar la automatización.', 'Larry Wall', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'Un lenguaje de scripting es el martillo del administrador de sistemas. Úsalo para clavar automatización en todas partes.', 'Larry Wall', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','focus'], true, 'coding'),

-- Guido van Rossum (216–223)
(gen_random_uuid(), 'El código es leído con mucha más frecuencia de lo que es escrito. Optimiza para la lectura, no para la escritura.', 'Guido van Rossum', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'Debería haber una y, preferiblemente solo una, forma obvia de hacerlo. La claridad tiene valor práctico.', 'Guido van Rossum', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'Explícito es mejor que implícito. En infraestructura como en código, la claridad previene errores costosos.', 'Guido van Rossum', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'Los errores nunca deben pasar silenciosamente. A menos que sean silenciados explícitamente. La opacidad mata.', 'Guido van Rossum', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'Si la implementación es difícil de explicar, es una mala idea. La complejidad oculta cobra facturas altas.', 'Guido van Rossum', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'Python fue diseñado con la legibilidad como objetivo primario porque los programas son comunicación entre humanos.', 'Guido van Rossum', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','learning'], true, 'coding'),
(gen_random_uuid(), 'La automatización con Python en DevOps demostró que la legibilidad y la utilidad práctica no son opuestos.', 'Guido van Rossum', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'Frente a la ambigüedad, rechaza la tentación de adivinar. Pregunta explícitamente o falla con claridad.', 'Guido van Rossum', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),

-- General DevOps / CI-CD topics — attributed as community wisdom (224–250)
(gen_random_uuid(), 'Un pipeline roto es una señal de alarma, no un inconveniente. Detente, corrígelo, no lo ignores.', 'Gene Kim', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','focus'], true, 'coding'),
(gen_random_uuid(), 'El despliegue azul-verde elimina el tiempo de inactividad al tener dos entornos de producción idénticos intercambiables.', 'Jez Humble', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'El despliegue canario reduce el riesgo exponiendo el cambio a una fracción pequeña de usuarios antes del rollout completo.', 'Martin Fowler', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'Los logs estructurados son más valiosos que los logs de texto libre. Formatea para que las máquinas puedan leerlos.', 'Charity Majors', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','focus'], true, 'coding'),
(gen_random_uuid(), 'El trazado distribuido es la herramienta que hace comprensibles los sistemas de microservicios en producción.', 'Adrian Cockcroft', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'Los objetivos de nivel de servicio son contratos con los usuarios. Defínelos antes de construir, no después de fallar.', 'Werner Vogels', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'El presupuesto de error es la cantidad de tiempo de inactividad aceptable que queda antes de violar el SLO.', 'John Allspaw', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'La automatización de pruebas de seguridad en el pipeline convierte la seguridad en una propiedad continua del sistema.', 'Kelsey Hightower', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','focus'], true, 'coding'),
(gen_random_uuid(), 'La gestión de secretos es el problema de seguridad más subestimado en la infraestructura moderna de software.', 'Mitchell Hashimoto', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'El análisis de causa raíz que termina en "error humano" es un análisis incompleto. El sistema permitió ese error.', 'Patrick Debois', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','learning'], true, 'coding'),
(gen_random_uuid(), 'La revisión de arquitectura no es un proceso burocrático. Es la forma en que los equipos maduros evitan errores costosos.', 'Martin Fowler', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'El reintento con backoff exponencial es el patrón básico para construir resiliencia en llamadas a servicios remotos.', 'Werner Vogels', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'Las pruebas de contrato entre servicios garantizan que los cambios en un servicio no rompan silenciosamente a sus consumidores.', 'Jez Humble', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','focus'], true, 'coding'),
(gen_random_uuid(), 'La idempotencia de las operaciones de infraestructura permite ejecutarlas múltiples veces con el mismo resultado seguro.', 'Mitchell Hashimoto', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'El monorepo y el repositorio múltiple son estrategias con tradeoffs reales. Elige según la estructura del equipo.', 'Linus Torvalds', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'Las migraciones de base de datos son despliegues. Trátales con el mismo rigor que el código de aplicación.', 'Gene Kim', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'El escaneo de vulnerabilidades en imágenes de contenedores debe ocurrir en el pipeline, no en producción.', 'Solomon Hykes', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','focus'], true, 'coding'),
(gen_random_uuid(), 'La política de retención de logs no es un detalle técnico menor. Es un requisito de cumplimiento y diagnóstico.', 'Charity Majors', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'El auto-escalado reactivo responde al pasado. El auto-escalado predictivo se adelanta al futuro. Ambos tienen su lugar.', 'Adrian Cockcroft', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'Las pruebas de carga revelan los límites del sistema antes de que los usuarios reales los descubran por ti.', 'John Allspaw', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','focus'], true, 'coding'),
(gen_random_uuid(), 'DevSecOps es la integración de la seguridad como práctica continua, no como auditoría de último momento.', 'Patrick Debois', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'La documentación de arquitectura como código, con diagramas generados automáticamente, nunca queda desactualizada.', 'Martin Fowler', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','learning'], true, 'coding'),
(gen_random_uuid(), 'El registro de cambios de infraestructura debe ser tan detallado como el historial de commits del código de aplicación.', 'Kelsey Hightower', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','focus'], true, 'coding'),
(gen_random_uuid(), 'La observabilidad de costos en la nube es tan importante como la observabilidad técnica. Instrumenta el gasto.', 'Werner Vogels', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','wisdom'], true, 'coding'),
(gen_random_uuid(), 'Los dashboards que nadie mira son ruido visual. Construye paneles que respondan preguntas operacionales reales.', 'Charity Majors', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','focus'], true, 'coding'),
(gen_random_uuid(), 'La cultura DevOps no se compra con herramientas. Se cultiva con prácticas repetidas y responsabilidad compartida.', 'Gene Kim', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['wisdom','discipline'], true, 'coding'),
(gen_random_uuid(), 'El tiempo de recuperación de un fallo es la métrica más honesta de la madurez operacional de un equipo.', 'Jez Humble', 'philosophy', 'es', 'down', 'free', false, 'coding', 'devops_tools', ARRAY['discipline','courage'], true, 'coding')

ON CONFLICT (text, author) DO NOTHING;

COMMIT;
