-- 046_exercises_python.sql
-- 100 Python exercises, bilingual EN+ES
-- Distribution: diff1=25, diff2=25, diff3=25, diff4=15, diff5=10
-- Points: 10/20/30/50/100 | Penalty: 3/3/5/10/10

BEGIN;

INSERT INTO exercises (
  id, title_en, title_es,
  description_en, description_es,
  language, difficulty, category,
  starter_code, solution, expected_output,
  hint_count,
  hint_1_en, hint_1_es,
  hint_2_en, hint_2_es,
  hint_3_en, hint_3_es,
  points, hints_used_penalty,
  created_at
) VALUES

-- ============================================================
-- DIFFICULTY 1 — 25 exercises (points=10, penalty=3)
-- ============================================================

-- 1. basics
(gen_random_uuid(),
 'Hello World', 'Hola Mundo',
 'Print the text "Hello, World!" to the console.',
 'Imprime el texto "Hello, World!" en la consola.',
 'python', 1, 'basics',
 'print("___")',
 'print("Hello, World!")',
 'Hello, World!',
 3,
 'Use the print() function.', 'Usa la función print().',
 'The text goes inside the parentheses in quotes.', 'El texto va dentro del paréntesis entre comillas.',
 'print("Hello, World!")', 'print("Hello, World!")',
 10, 3, now()),

-- 2. basics
(gen_random_uuid(),
 'Print Your Name', 'Imprime Tu Nombre',
 'Store your name in a variable called name and print it.',
 'Guarda tu nombre en una variable llamada name e imprímela.',
 'python', 1, 'basics',
 'name = "___"\nprint(name)',
 'name = "Alice"\nprint(name)',
 'Alice',
 3,
 'Assign a string value to the variable.', 'Asigna un valor de cadena a la variable.',
 'Use double or single quotes around text.', 'Usa comillas dobles o simples alrededor del texto.',
 'name = "Alice" then print(name)', 'name = "Alice" luego print(name)',
 10, 3, now()),

-- 3. math
(gen_random_uuid(),
 'Add Two Numbers', 'Suma Dos Números',
 'Add 7 and 3 and print the result.',
 'Suma 7 y 3 e imprime el resultado.',
 'python', 1, 'math',
 'result = ___ + ___\nprint(result)',
 'result = 7 + 3\nprint(result)',
 '10',
 3,
 'Use the + operator between two numbers.', 'Usa el operador + entre dos números.',
 'Assign the sum to a variable then print it.', 'Asigna la suma a una variable y luego imprímela.',
 'result = 7 + 3', 'result = 7 + 3',
 10, 3, now()),

-- 4. math
(gen_random_uuid(),
 'Multiply Numbers', 'Multiplicar Números',
 'Multiply 6 by 4 and print the result.',
 'Multiplica 6 por 4 e imprime el resultado.',
 'python', 1, 'math',
 'result = ___ * ___\nprint(result)',
 'result = 6 * 4\nprint(result)',
 '24',
 3,
 'Use the * operator for multiplication.', 'Usa el operador * para multiplicar.',
 '6 * 4 gives 24.', '6 * 4 da 24.',
 'result = 6 * 4', 'result = 6 * 4',
 10, 3, now()),

-- 5. strings
(gen_random_uuid(),
 'String Length', 'Longitud de Cadena',
 'Print the length of the string "Python".',
 'Imprime la longitud de la cadena "Python".',
 'python', 1, 'strings',
 'word = "Python"\nprint(___)',
 'word = "Python"\nprint(len(word))',
 '6',
 3,
 'There is a built-in function that counts characters.', 'Hay una función integrada que cuenta caracteres.',
 'The function is called len().', 'La función se llama len().',
 'print(len(word))', 'print(len(word))',
 10, 3, now()),

-- 6. strings
(gen_random_uuid(),
 'Uppercase String', 'Cadena en Mayúsculas',
 'Convert the string "hello" to uppercase and print it.',
 'Convierte la cadena "hello" a mayúsculas e imprímela.',
 'python', 1, 'strings',
 'text = "hello"\nprint(text.___())',
 'text = "hello"\nprint(text.upper())',
 'HELLO',
 3,
 'Strings have methods you can call with a dot.', 'Las cadenas tienen métodos que puedes llamar con un punto.',
 'The method name is related to "upper".', 'El nombre del método está relacionado con "upper".',
 'text.upper()', 'text.upper()',
 10, 3, now()),

-- 7. strings
(gen_random_uuid(),
 'Lowercase String', 'Cadena en Minúsculas',
 'Convert the string "WORLD" to lowercase and print it.',
 'Convierte la cadena "WORLD" a minúsculas e imprímela.',
 'python', 1, 'strings',
 'text = "WORLD"\nprint(text.___())',
 'text = "WORLD"\nprint(text.lower())',
 'world',
 3,
 'Strings have methods you can call with a dot.', 'Las cadenas tienen métodos que puedes llamar con un punto.',
 'The method name is related to "lower".', 'El nombre del método está relacionado con "lower".',
 'text.lower()', 'text.lower()',
 10, 3, now()),

-- 8. basics
(gen_random_uuid(),
 'Boolean Values', 'Valores Booleanos',
 'Print the boolean value True.',
 'Imprime el valor booleano True.',
 'python', 1, 'basics',
 'print(___)',
 'print(True)',
 'True',
 3,
 'Python has two boolean values.', 'Python tiene dos valores booleanos.',
 'Boolean values start with a capital letter in Python.', 'Los valores booleanos empiezan con mayúscula en Python.',
 'print(True)', 'print(True)',
 10, 3, now()),

-- 9. math
(gen_random_uuid(),
 'Division', 'División',
 'Divide 10 by 2 and print the result.',
 'Divide 10 entre 2 e imprime el resultado.',
 'python', 1, 'math',
 'result = ___ / ___\nprint(result)',
 'result = 10 / 2\nprint(result)',
 '5.0',
 3,
 'Use the / operator for division.', 'Usa el operador / para dividir.',
 'Division in Python 3 always returns a float.', 'La división en Python 3 siempre devuelve un flotante.',
 'result = 10 / 2 → 5.0', 'result = 10 / 2 → 5.0',
 10, 3, now()),

-- 10. math
(gen_random_uuid(),
 'Integer Division', 'División Entera',
 'Use floor division to divide 17 by 5 and print the result.',
 'Usa la división entera para dividir 17 entre 5 e imprime el resultado.',
 'python', 1, 'math',
 'result = 17 ___ 5\nprint(result)',
 'result = 17 // 5\nprint(result)',
 '3',
 3,
 'There is a special operator for floor division.', 'Hay un operador especial para la división entera.',
 'Use two forward slashes: //', 'Usa dos barras inclinadas: //',
 'result = 17 // 5', 'result = 17 // 5',
 10, 3, now()),

-- 11. basics
(gen_random_uuid(),
 'Type Check', 'Verificar Tipo',
 'Print the type of the value 42.',
 'Imprime el tipo del valor 42.',
 'python', 1, 'basics',
 'print(type(___))',
 'print(type(42))',
 '<class ''int''>',
 3,
 'Use a built-in function that returns the type.', 'Usa una función integrada que devuelve el tipo.',
 'The function is called type().', 'La función se llama type().',
 'print(type(42))', 'print(type(42))',
 10, 3, now()),

-- 12. arrays
(gen_random_uuid(),
 'Create a List', 'Crear una Lista',
 'Create a list with the numbers 1, 2, 3 and print it.',
 'Crea una lista con los números 1, 2, 3 e imprímela.',
 'python', 1, 'arrays',
 'numbers = [___]\nprint(numbers)',
 'numbers = [1, 2, 3]\nprint(numbers)',
 '[1, 2, 3]',
 3,
 'Lists use square brackets.', 'Las listas usan corchetes.',
 'Separate items with commas inside the brackets.', 'Separa los elementos con comas dentro de los corchetes.',
 'numbers = [1, 2, 3]', 'numbers = [1, 2, 3]',
 10, 3, now()),

-- 13. arrays
(gen_random_uuid(),
 'List Length', 'Longitud de Lista',
 'Print the number of elements in the list [10, 20, 30, 40].',
 'Imprime el número de elementos en la lista [10, 20, 30, 40].',
 'python', 1, 'arrays',
 'nums = [10, 20, 30, 40]\nprint(___)',
 'nums = [10, 20, 30, 40]\nprint(len(nums))',
 '4',
 3,
 'Use the same function used to measure strings.', 'Usa la misma función que se usa para medir cadenas.',
 'The function is len().', 'La función es len().',
 'print(len(nums))', 'print(len(nums))',
 10, 3, now()),

-- 14. arrays
(gen_random_uuid(),
 'Access List Element', 'Acceder a Elemento de Lista',
 'Print the first element of the list ["a", "b", "c"].',
 'Imprime el primer elemento de la lista ["a", "b", "c"].',
 'python', 1, 'arrays',
 'letters = ["a", "b", "c"]\nprint(letters[___])',
 'letters = ["a", "b", "c"]\nprint(letters[0])',
 'a',
 3,
 'Python uses zero-based indexing.', 'Python usa índices base cero.',
 'The first element is at index 0.', 'El primer elemento está en el índice 0.',
 'letters[0]', 'letters[0]',
 10, 3, now()),

-- 15. strings
(gen_random_uuid(),
 'String Concatenation', 'Concatenación de Cadenas',
 'Concatenate "Hello" and " World" and print the result.',
 'Concatena "Hello" y " World" e imprime el resultado.',
 'python', 1, 'strings',
 'result = "Hello" ___ " World"\nprint(result)',
 'result = "Hello" + " World"\nprint(result)',
 'Hello World',
 3,
 'You can join strings with an operator.', 'Puedes unir cadenas con un operador.',
 'Use the + operator to concatenate strings.', 'Usa el operador + para concatenar cadenas.',
 '"Hello" + " World"', '"Hello" + " World"',
 10, 3, now()),

-- 16. basics
(gen_random_uuid(),
 'Variable Swap', 'Intercambio de Variables',
 'Swap the values of a=5 and b=10, then print a and b.',
 'Intercambia los valores de a=5 y b=10, luego imprime a y b.',
 'python', 1, 'basics',
 'a = 5\nb = 10\n___, ___ = ___, ___\nprint(a, b)',
 'a = 5\nb = 10\na, b = b, a\nprint(a, b)',
 '10 5',
 3,
 'Python supports tuple unpacking for swaps.', 'Python admite desempaquetado de tuplas para intercambios.',
 'You can swap without a temp variable: a, b = b, a', 'Puedes intercambiar sin variable temporal: a, b = b, a',
 'a, b = b, a', 'a, b = b, a',
 10, 3, now()),

-- 17. math
(gen_random_uuid(),
 'Modulo Operator', 'Operador Módulo',
 'Print the remainder of 17 divided by 5.',
 'Imprime el resto de dividir 17 entre 5.',
 'python', 1, 'math',
 'print(17 ___ 5)',
 'print(17 % 5)',
 '2',
 3,
 'There is a special operator for the remainder.', 'Hay un operador especial para el resto.',
 'The modulo operator is the percent sign %.', 'El operador módulo es el signo de porcentaje %.',
 'print(17 % 5)', 'print(17 % 5)',
 10, 3, now()),

-- 18. strings
(gen_random_uuid(),
 'String Repetition', 'Repetición de Cadenas',
 'Print the string "ha" repeated 3 times.',
 'Imprime la cadena "ha" repetida 3 veces.',
 'python', 1, 'strings',
 'print("ha" ___ 3)',
 'print("ha" * 3)',
 'hahaha',
 3,
 'You can repeat strings with an operator.', 'Puedes repetir cadenas con un operador.',
 'Use the * operator to repeat a string.', 'Usa el operador * para repetir una cadena.',
 '"ha" * 3', '"ha" * 3',
 10, 3, now()),

-- 19. basics
(gen_random_uuid(),
 'Check Even Number', 'Verificar Número Par',
 'Print True if 8 is even, otherwise print False.',
 'Imprime True si 8 es par, de lo contrario imprime False.',
 'python', 1, 'basics',
 'print(8 % 2 ___ 0)',
 'print(8 % 2 == 0)',
 'True',
 3,
 'Use the modulo operator to check divisibility.', 'Usa el operador módulo para verificar la divisibilidad.',
 'A number is even if its remainder divided by 2 equals 0.', 'Un número es par si su resto al dividir por 2 es 0.',
 '8 % 2 == 0', '8 % 2 == 0',
 10, 3, now()),

-- 20. strings
(gen_random_uuid(),
 'String Slice', 'Rebanada de Cadena',
 'Print the first 3 characters of the string "Python".',
 'Imprime los primeros 3 caracteres de la cadena "Python".',
 'python', 1, 'strings',
 'word = "Python"\nprint(word[___])',
 'word = "Python"\nprint(word[0:3])',
 'Pyt',
 3,
 'You can extract parts of a string using slicing.', 'Puedes extraer partes de una cadena usando rebanado.',
 'Slice syntax is [start:end] where end is exclusive.', 'La sintaxis de rebanado es [inicio:fin] donde fin es exclusivo.',
 'word[0:3]', 'word[0:3]',
 10, 3, now()),

-- 21. arrays
(gen_random_uuid(),
 'Append to List', 'Agregar a Lista',
 'Append the number 4 to the list [1, 2, 3] and print it.',
 'Agrega el número 4 a la lista [1, 2, 3] e imprímela.',
 'python', 1, 'arrays',
 'nums = [1, 2, 3]\nnums.___(4)\nprint(nums)',
 'nums = [1, 2, 3]\nnums.append(4)\nprint(nums)',
 '[1, 2, 3, 4]',
 3,
 'Lists have a method to add elements at the end.', 'Las listas tienen un método para añadir elementos al final.',
 'The method is called append().', 'El método se llama append().',
 'nums.append(4)', 'nums.append(4)',
 10, 3, now()),

-- 22. basics
(gen_random_uuid(),
 'Conditional Print', 'Imprimir Condicionalmente',
 'If x is greater than 5, print "big". x = 10.',
 'Si x es mayor que 5, imprime "big". x = 10.',
 'python', 1, 'basics',
 'x = 10\nif x ___ 5:\n    print("big")',
 'x = 10\nif x > 5:\n    print("big")',
 'big',
 3,
 'Use a comparison operator to check the condition.', 'Usa un operador de comparación para verificar la condición.',
 'The greater-than operator is >.', 'El operador mayor que es >.',
 'if x > 5:', 'if x > 5:',
 10, 3, now()),

-- 23. math
(gen_random_uuid(),
 'Power Operator', 'Operador Potencia',
 'Print 2 raised to the power of 8.',
 'Imprime 2 elevado a la potencia de 8.',
 'python', 1, 'math',
 'print(2 ___ 8)',
 'print(2 ** 8)',
 '256',
 3,
 'Python has a built-in power operator.', 'Python tiene un operador de potencia integrado.',
 'Use ** for exponentiation.', 'Usa ** para la exponenciación.',
 'print(2 ** 8)', 'print(2 ** 8)',
 10, 3, now()),

-- 24. strings
(gen_random_uuid(),
 'String Contains', 'Cadena Contiene',
 'Check if "cat" is in the string "concatenate" and print the result.',
 'Verifica si "cat" está en la cadena "concatenate" e imprime el resultado.',
 'python', 1, 'strings',
 'print("cat" ___ "concatenate")',
 'print("cat" in "concatenate")',
 'True',
 3,
 'Python has a keyword to check membership.', 'Python tiene una palabra clave para verificar membresía.',
 'Use the "in" keyword.', 'Usa la palabra clave "in".',
 '"cat" in "concatenate"', '"cat" in "concatenate"',
 10, 3, now()),

-- 25. basics
(gen_random_uuid(),
 'Print Multiple Values', 'Imprimir Múltiples Valores',
 'Print the values 1, 2, 3 on the same line separated by spaces.',
 'Imprime los valores 1, 2, 3 en la misma línea separados por espacios.',
 'python', 1, 'basics',
 'print(___, ___, ___)',
 'print(1, 2, 3)',
 '1 2 3',
 3,
 'print() can accept multiple arguments.', 'print() puede aceptar múltiples argumentos.',
 'Separate each value with a comma.', 'Separa cada valor con una coma.',
 'print(1, 2, 3)', 'print(1, 2, 3)',
 10, 3, now()),

-- ============================================================
-- DIFFICULTY 2 — 25 exercises (points=20, penalty=3)
-- ============================================================

-- 26. functions
(gen_random_uuid(),
 'Define a Function', 'Definir una Función',
 'Define a function called greet that prints "Hello, friend!" and call it.',
 'Define una función llamada greet que imprima "Hello, friend!" y llámala.',
 'python', 2, 'functions',
 'def ___():\n    print("Hello, friend!")\n\ngreet()',
 'def greet():\n    print("Hello, friend!")\n\ngreet()',
 'Hello, friend!',
 3,
 'Use the def keyword to define a function.', 'Usa la palabra clave def para definir una función.',
 'The function name goes after def, followed by parentheses and a colon.', 'El nombre de la función va después de def, seguido de paréntesis y dos puntos.',
 'def greet():', 'def greet():',
 20, 3, now()),

-- 27. functions
(gen_random_uuid(),
 'Function with Parameter', 'Función con Parámetro',
 'Define a function square(n) that returns n squared. Print square(5).',
 'Define una función square(n) que devuelva n al cuadrado. Imprime square(5).',
 'python', 2, 'functions',
 'def square(n):\n    return ___\n\nprint(square(5))',
 'def square(n):\n    return n ** 2\n\nprint(square(5))',
 '25',
 3,
 'Use the return keyword to give back a value.', 'Usa la palabra clave return para devolver un valor.',
 'Use the ** operator to calculate the power.', 'Usa el operador ** para calcular la potencia.',
 'return n ** 2', 'return n ** 2',
 20, 3, now()),

-- 28. arrays
(gen_random_uuid(),
 'List Sum', 'Suma de Lista',
 'Print the sum of all numbers in [3, 7, 2, 8, 1].',
 'Imprime la suma de todos los números en [3, 7, 2, 8, 1].',
 'python', 2, 'arrays',
 'nums = [3, 7, 2, 8, 1]\nprint(___)',
 'nums = [3, 7, 2, 8, 1]\nprint(sum(nums))',
 '21',
 3,
 'There is a built-in function that adds all elements of a list.', 'Hay una función integrada que suma todos los elementos de una lista.',
 'The function is called sum().', 'La función se llama sum().',
 'print(sum(nums))', 'print(sum(nums))',
 20, 3, now()),

-- 29. arrays
(gen_random_uuid(),
 'List Maximum', 'Máximo de Lista',
 'Print the largest number in [4, 9, 2, 7, 1].',
 'Imprime el número más grande en [4, 9, 2, 7, 1].',
 'python', 2, 'arrays',
 'nums = [4, 9, 2, 7, 1]\nprint(___)',
 'nums = [4, 9, 2, 7, 1]\nprint(max(nums))',
 '9',
 3,
 'There is a built-in function for finding the maximum.', 'Hay una función integrada para encontrar el máximo.',
 'The function is called max().', 'La función se llama max().',
 'print(max(nums))', 'print(max(nums))',
 20, 3, now()),

-- 30. strings
(gen_random_uuid(),
 'Split String', 'Dividir Cadena',
 'Split the string "apple,banana,cherry" by comma and print the result.',
 'Divide la cadena "apple,banana,cherry" por coma e imprime el resultado.',
 'python', 2, 'strings',
 'text = "apple,banana,cherry"\nprint(text.___(","))',
 'text = "apple,banana,cherry"\nprint(text.split(","))',
 '[''apple'', ''banana'', ''cherry'']',
 3,
 'Strings have a method to split them into a list.', 'Las cadenas tienen un método para dividirlas en una lista.',
 'The method is called split() and takes a delimiter.', 'El método se llama split() y toma un delimitador.',
 'text.split(",")', 'text.split(",")',
 20, 3, now()),

-- 31. strings
(gen_random_uuid(),
 'Strip Whitespace', 'Eliminar Espacios',
 'Remove leading and trailing whitespace from "  hello  " and print it.',
 'Elimina los espacios al inicio y final de "  hello  " e imprímelo.',
 'python', 2, 'strings',
 'text = "  hello  "\nprint(text.___())',
 'text = "  hello  "\nprint(text.strip())',
 'hello',
 3,
 'Strings have a method to remove surrounding whitespace.', 'Las cadenas tienen un método para eliminar espacios circundantes.',
 'The method is called strip().', 'El método se llama strip().',
 'text.strip()', 'text.strip()',
 20, 3, now()),

-- 32. patterns
(gen_random_uuid(),
 'For Loop Range', 'Bucle For con Range',
 'Print numbers from 1 to 5 using a for loop.',
 'Imprime números del 1 al 5 usando un bucle for.',
 'python', 2, 'patterns',
 'for i in range(___, ___):\n    print(i)',
 'for i in range(1, 6):\n    print(i)',
 '1\n2\n3\n4\n5',
 3,
 'Use range() with start and stop values.', 'Usa range() con valores de inicio y fin.',
 'range(1, 6) gives 1, 2, 3, 4, 5 — the stop is exclusive.', 'range(1, 6) da 1, 2, 3, 4, 5 — el fin es exclusivo.',
 'for i in range(1, 6):', 'for i in range(1, 6):',
 20, 3, now()),

-- 33. patterns
(gen_random_uuid(),
 'While Loop', 'Bucle While',
 'Print numbers from 1 to 3 using a while loop.',
 'Imprime números del 1 al 3 usando un bucle while.',
 'python', 2, 'patterns',
 'n = 1\nwhile n ___ 4:\n    print(n)\n    n += 1',
 'n = 1\nwhile n < 4:\n    print(n)\n    n += 1',
 '1\n2\n3',
 3,
 'The while loop runs as long as the condition is true.', 'El bucle while se ejecuta mientras la condición sea verdadera.',
 'Use n < 4 so the loop stops before printing 4.', 'Usa n < 4 para que el bucle se detenga antes de imprimir 4.',
 'while n < 4:', 'while n < 4:',
 20, 3, now()),

-- 34. objects
(gen_random_uuid(),
 'Create a Dictionary', 'Crear un Diccionario',
 'Create a dictionary with keys "name" and "age" set to "Alice" and 30. Print it.',
 'Crea un diccionario con claves "name" y "age" con valores "Alice" y 30. Imprímelo.',
 'python', 2, 'objects',
 'person = {___}\nprint(person)',
 'person = {"name": "Alice", "age": 30}\nprint(person)',
 '{''name'': ''Alice'', ''age'': 30}',
 3,
 'Dictionaries use curly braces and key-value pairs.', 'Los diccionarios usan llaves y pares clave-valor.',
 'Format: {"key": value, "key2": value2}', 'Formato: {"clave": valor, "clave2": valor2}',
 'person = {"name": "Alice", "age": 30}', 'person = {"name": "Alice", "age": 30}',
 20, 3, now()),

-- 35. objects
(gen_random_uuid(),
 'Access Dictionary Value', 'Acceder a Valor de Diccionario',
 'Print the value of the "age" key from {"name": "Bob", "age": 25}.',
 'Imprime el valor de la clave "age" de {"name": "Bob", "age": 25}.',
 'python', 2, 'objects',
 'person = {"name": "Bob", "age": 25}\nprint(person[___])',
 'person = {"name": "Bob", "age": 25}\nprint(person["age"])',
 '25',
 3,
 'Access dictionary values using bracket notation.', 'Accede a los valores del diccionario usando notación de corchetes.',
 'Use the key name in quotes inside square brackets.', 'Usa el nombre de la clave entre comillas dentro de corchetes.',
 'person["age"]', 'person["age"]',
 20, 3, now()),

-- 36. functions
(gen_random_uuid(),
 'Default Parameter', 'Parámetro Predeterminado',
 'Define greet(name="World") that prints "Hello, {name}!". Call greet().',
 'Define greet(name="World") que imprima "Hello, {name}!". Llama greet().',
 'python', 2, 'functions',
 'def greet(name="___"):\n    print(f"Hello, {name}!")\n\ngreet()',
 'def greet(name="World"):\n    print(f"Hello, {name}!")\n\ngreet()',
 'Hello, World!',
 3,
 'Default parameter values go in the function signature.', 'Los valores de parámetros predeterminados van en la firma de la función.',
 'Use = in the parameter to set a default: name="World"', 'Usa = en el parámetro para establecer un valor predeterminado: name="World"',
 'def greet(name="World"):', 'def greet(name="World"):',
 20, 3, now()),

-- 37. strings
(gen_random_uuid(),
 'String Replace', 'Reemplazar en Cadena',
 'Replace "bad" with "good" in "This is bad" and print it.',
 'Reemplaza "bad" con "good" en "This is bad" e imprímelo.',
 'python', 2, 'strings',
 'text = "This is bad"\nprint(text.___("bad", "good"))',
 'text = "This is bad"\nprint(text.replace("bad", "good"))',
 'This is good',
 3,
 'Strings have a method to replace substrings.', 'Las cadenas tienen un método para reemplazar subcadenas.',
 'The method is replace(old, new).', 'El método es replace(viejo, nuevo).',
 'text.replace("bad", "good")', 'text.replace("bad", "good")',
 20, 3, now()),

-- 38. arrays
(gen_random_uuid(),
 'Sort a List', 'Ordenar una Lista',
 'Sort the list [3, 1, 4, 1, 5, 9, 2] and print it.',
 'Ordena la lista [3, 1, 4, 1, 5, 9, 2] e imprímela.',
 'python', 2, 'arrays',
 'nums = [3, 1, 4, 1, 5, 9, 2]\nnums.sort()\nprint(___)',
 'nums = [3, 1, 4, 1, 5, 9, 2]\nnums.sort()\nprint(nums)',
 '[1, 1, 2, 3, 4, 5, 9]',
 3,
 'Lists have a method to sort in place.', 'Las listas tienen un método para ordenar en su lugar.',
 'After calling sort(), print the list.', 'Después de llamar a sort(), imprime la lista.',
 'nums.sort() then print(nums)', 'nums.sort() luego print(nums)',
 20, 3, now()),

-- 39. arrays
(gen_random_uuid(),
 'List Comprehension Basics', 'Comprensión de Lista Básica',
 'Create a list of squares [1, 4, 9, 16, 25] using a list comprehension.',
 'Crea una lista de cuadrados [1, 4, 9, 16, 25] usando comprensión de lista.',
 'python', 2, 'arrays',
 'squares = [___ for x in range(1, 6)]\nprint(squares)',
 'squares = [x**2 for x in range(1, 6)]\nprint(squares)',
 '[1, 4, 9, 16, 25]',
 3,
 'List comprehensions let you build lists in one line.', 'Las comprensiones de lista te permiten construir listas en una línea.',
 'The expression before "for" defines each element.', 'La expresión antes de "for" define cada elemento.',
 '[x**2 for x in range(1, 6)]', '[x**2 for x in range(1, 6)]',
 20, 3, now()),

-- 40. math
(gen_random_uuid(),
 'Absolute Value', 'Valor Absoluto',
 'Print the absolute value of -42.',
 'Imprime el valor absoluto de -42.',
 'python', 2, 'math',
 'print(___(-42))',
 'print(abs(-42))',
 '42',
 3,
 'Python has a built-in function for absolute value.', 'Python tiene una función integrada para el valor absoluto.',
 'The function is called abs().', 'La función se llama abs().',
 'print(abs(-42))', 'print(abs(-42))',
 20, 3, now()),

-- 41. patterns
(gen_random_uuid(),
 'FizzBuzz One', 'FizzBuzz Uno',
 'Print "Fizz" if 9 is divisible by 3, else print the number.',
 'Imprime "Fizz" si 9 es divisible entre 3, si no imprime el número.',
 'python', 2, 'patterns',
 'n = 9\nif n % 3 == ___:\n    print("Fizz")\nelse:\n    print(n)',
 'n = 9\nif n % 3 == 0:\n    print("Fizz")\nelse:\n    print(n)',
 'Fizz',
 3,
 'Use modulo to check divisibility.', 'Usa el módulo para verificar la divisibilidad.',
 'If n % 3 equals 0, the number is divisible by 3.', 'Si n % 3 es igual a 0, el número es divisible entre 3.',
 'if n % 3 == 0:', 'if n % 3 == 0:',
 20, 3, now()),

-- 42. strings
(gen_random_uuid(),
 'f-string Formatting', 'Formato con f-string',
 'Use an f-string to print "My name is Alice and I am 30 years old."',
 'Usa un f-string para imprimir "My name is Alice and I am 30 years old."',
 'python', 2, 'strings',
 'name = "Alice"\nage = 30\nprint(f"My name is ___ and I am ___ years old.")',
 'name = "Alice"\nage = 30\nprint(f"My name is {name} and I am {age} years old.")',
 'My name is Alice and I am 30 years old.',
 3,
 'f-strings embed variables inside curly braces.', 'Los f-strings insertan variables dentro de llaves.',
 'Prefix the string with f and use {variable} inside.', 'Prefija la cadena con f y usa {variable} dentro.',
 'f"...{name}...{age}..."', 'f"...{name}...{age}..."',
 20, 3, now()),

-- 43. objects
(gen_random_uuid(),
 'Dictionary Keys', 'Claves de Diccionario',
 'Print all keys of {"x": 1, "y": 2, "z": 3}.',
 'Imprime todas las claves de {"x": 1, "y": 2, "z": 3}.',
 'python', 2, 'objects',
 'd = {"x": 1, "y": 2, "z": 3}\nprint(list(d.___()))',
 'd = {"x": 1, "y": 2, "z": 3}\nprint(list(d.keys()))',
 '[''x'', ''y'', ''z'']',
 3,
 'Dictionaries have a method to get all keys.', 'Los diccionarios tienen un método para obtener todas las claves.',
 'The method is called keys().', 'El método se llama keys().',
 'd.keys()', 'd.keys()',
 20, 3, now()),

-- 44. arrays
(gen_random_uuid(),
 'Remove from List', 'Eliminar de Lista',
 'Remove the value 3 from [1, 2, 3, 4, 5] and print it.',
 'Elimina el valor 3 de [1, 2, 3, 4, 5] e imprímela.',
 'python', 2, 'arrays',
 'nums = [1, 2, 3, 4, 5]\nnums.___(3)\nprint(nums)',
 'nums = [1, 2, 3, 4, 5]\nnums.remove(3)\nprint(nums)',
 '[1, 2, 4, 5]',
 3,
 'Lists have a method to remove a specific value.', 'Las listas tienen un método para eliminar un valor específico.',
 'The method is called remove() and takes the value to remove.', 'El método se llama remove() y toma el valor a eliminar.',
 'nums.remove(3)', 'nums.remove(3)',
 20, 3, now()),

-- 45. functions
(gen_random_uuid(),
 'Return Multiple Values', 'Retornar Múltiples Valores',
 'Write a function min_max(lst) that returns the min and max of a list. Test with [3, 1, 4, 1, 5].',
 'Escribe una función min_max(lst) que devuelva el mínimo y máximo de una lista. Prueba con [3, 1, 4, 1, 5].',
 'python', 2, 'functions',
 'def min_max(lst):\n    return ___, ___\n\nlo, hi = min_max([3, 1, 4, 1, 5])\nprint(lo, hi)',
 'def min_max(lst):\n    return min(lst), max(lst)\n\nlo, hi = min_max([3, 1, 4, 1, 5])\nprint(lo, hi)',
 '1 5',
 3,
 'A function can return multiple values separated by commas.', 'Una función puede devolver múltiples valores separados por comas.',
 'Use min() and max() built-in functions.', 'Usa las funciones integradas min() y max().',
 'return min(lst), max(lst)', 'return min(lst), max(lst)',
 20, 3, now()),

-- 46. patterns
(gen_random_uuid(),
 'List Iteration', 'Iteración de Lista',
 'Print each fruit in ["apple", "banana", "cherry"] on its own line.',
 'Imprime cada fruta en ["apple", "banana", "cherry"] en su propia línea.',
 'python', 2, 'patterns',
 'fruits = ["apple", "banana", "cherry"]\nfor ___ in fruits:\n    print(___)',
 'fruits = ["apple", "banana", "cherry"]\nfor fruit in fruits:\n    print(fruit)',
 'apple\nbanana\ncherry',
 3,
 'Use a for loop to iterate over a list.', 'Usa un bucle for para iterar sobre una lista.',
 'Choose a variable name for each element: for fruit in fruits', 'Elige un nombre de variable para cada elemento: for fruit in fruits',
 'for fruit in fruits: print(fruit)', 'for fruit in fruits: print(fruit)',
 20, 3, now()),

-- 47. math
(gen_random_uuid(),
 'Round a Number', 'Redondear un Número',
 'Round 3.14159 to 2 decimal places and print it.',
 'Redondea 3.14159 a 2 decimales e imprímelo.',
 'python', 2, 'math',
 'print(round(3.14159, ___))',
 'print(round(3.14159, 2))',
 '3.14',
 3,
 'Python has a built-in round() function.', 'Python tiene una función integrada round().',
 'The second argument is the number of decimal places.', 'El segundo argumento es el número de decimales.',
 'round(3.14159, 2)', 'round(3.14159, 2)',
 20, 3, now()),

-- 48. objects
(gen_random_uuid(),
 'Dictionary Update', 'Actualizar Diccionario',
 'Add key "city" with value "Paris" to {"name": "Alice"} and print it.',
 'Agrega la clave "city" con valor "Paris" a {"name": "Alice"} e imprímelo.',
 'python', 2, 'objects',
 'person = {"name": "Alice"}\nperson[___] = ___\nprint(person)',
 'person = {"name": "Alice"}\nperson["city"] = "Paris"\nprint(person)',
 '{''name'': ''Alice'', ''city'': ''Paris''}',
 3,
 'Add a new key-value pair using bracket notation.', 'Agrega un nuevo par clave-valor usando notación de corchetes.',
 'person["city"] = "Paris" adds the key.', 'person["city"] = "Paris" agrega la clave.',
 'person["city"] = "Paris"', 'person["city"] = "Paris"',
 20, 3, now()),

-- 49. arrays
(gen_random_uuid(),
 'Reverse a List', 'Invertir una Lista',
 'Reverse the list [1, 2, 3, 4, 5] and print it.',
 'Invierte la lista [1, 2, 3, 4, 5] e imprímela.',
 'python', 2, 'arrays',
 'nums = [1, 2, 3, 4, 5]\nprint(nums[___])',
 'nums = [1, 2, 3, 4, 5]\nprint(nums[::-1])',
 '[5, 4, 3, 2, 1]',
 3,
 'You can reverse a list using slicing.', 'Puedes invertir una lista usando rebanado.',
 'Use slice notation with a step of -1: [::-1]', 'Usa notación de rebanado con paso -1: [::-1]',
 'nums[::-1]', 'nums[::-1]',
 20, 3, now()),

-- 50. strings
(gen_random_uuid(),
 'Count Occurrences', 'Contar Ocurrencias',
 'Count how many times "l" appears in "hello world" and print it.',
 'Cuenta cuántas veces aparece "l" en "hello world" e imprímelo.',
 'python', 2, 'strings',
 'text = "hello world"\nprint(text.___("l"))',
 'text = "hello world"\nprint(text.count("l"))',
 '3',
 3,
 'Strings have a method to count substring occurrences.', 'Las cadenas tienen un método para contar ocurrencias de subcadenas.',
 'The method is called count().', 'El método se llama count().',
 'text.count("l")', 'text.count("l")',
 20, 3, now()),

-- ============================================================
-- DIFFICULTY 3 — 25 exercises (points=30, penalty=5)
-- ============================================================

-- 51. functions
(gen_random_uuid(),
 'Recursive Factorial', 'Factorial Recursivo',
 'Write a recursive function factorial(n) that returns n!. Print factorial(5).',
 'Escribe una función recursiva factorial(n) que devuelva n!. Imprime factorial(5).',
 'python', 3, 'functions',
 'def factorial(n):\n    if n == ___:\n        return 1\n    return n * factorial(___)\n\nprint(factorial(5))',
 'def factorial(n):\n    if n == 0:\n        return 1\n    return n * factorial(n - 1)\n\nprint(factorial(5))',
 '120',
 3,
 'A recursive function calls itself with a smaller input.', 'Una función recursiva se llama a sí misma con una entrada menor.',
 'The base case is when n equals 0, returning 1.', 'El caso base es cuando n es igual a 0, devolviendo 1.',
 'if n == 0: return 1; return n * factorial(n-1)', 'if n == 0: return 1; return n * factorial(n-1)',
 30, 5, now()),

-- 52. algorithms
(gen_random_uuid(),
 'Linear Search', 'Búsqueda Lineal',
 'Write a function find(lst, target) that returns the index of target in lst, or -1. Test with find([4,2,7,1], 7).',
 'Escribe una función find(lst, target) que devuelva el índice de target en lst, o -1. Prueba con find([4,2,7,1], 7).',
 'python', 3, 'algorithms',
 'def find(lst, target):\n    for i, val in enumerate(lst):\n        if val == target:\n            return ___\n    return -1\n\nprint(find([4, 2, 7, 1], 7))',
 'def find(lst, target):\n    for i, val in enumerate(lst):\n        if val == target:\n            return i\n    return -1\n\nprint(find([4, 2, 7, 1], 7))',
 '2',
 3,
 'Use enumerate() to get both index and value.', 'Usa enumerate() para obtener tanto el índice como el valor.',
 'When the value matches the target, return the current index i.', 'Cuando el valor coincide con el objetivo, devuelve el índice actual i.',
 'return i', 'return i',
 30, 5, now()),

-- 53. data_structures
(gen_random_uuid(),
 'Stack with List', 'Pila con Lista',
 'Implement push and pop using a list. Push 1, 2, 3 then pop once. Print the popped value.',
 'Implementa push y pop usando una lista. Añade 1, 2, 3 y luego elimina uno. Imprime el valor eliminado.',
 'python', 3, 'data_structures',
 'stack = []\nstack.append(1)\nstack.append(2)\nstack.append(3)\npopped = stack.___() \nprint(popped)',
 'stack = []\nstack.append(1)\nstack.append(2)\nstack.append(3)\npopped = stack.pop()\nprint(popped)',
 '3',
 3,
 'A stack is LIFO: last in, first out.', 'Una pila es LIFO: el último en entrar es el primero en salir.',
 'Lists have a method that removes and returns the last element.', 'Las listas tienen un método que elimina y devuelve el último elemento.',
 'stack.pop()', 'stack.pop()',
 30, 5, now()),

-- 54. objects
(gen_random_uuid(),
 'Class Definition', 'Definición de Clase',
 'Define a class Dog with attribute name. Create an instance with name "Rex" and print its name.',
 'Define una clase Dog con atributo name. Crea una instancia con nombre "Rex" e imprime su nombre.',
 'python', 3, 'objects',
 'class Dog:\n    def __init__(self, name):\n        self.___ = name\n\ndog = Dog("Rex")\nprint(dog.name)',
 'class Dog:\n    def __init__(self, name):\n        self.name = name\n\ndog = Dog("Rex")\nprint(dog.name)',
 'Rex',
 3,
 'Use self.attribute to store instance data.', 'Usa self.atributo para almacenar datos de instancia.',
 'Inside __init__, assign self.name = name.', 'Dentro de __init__, asigna self.name = name.',
 'self.name = name', 'self.name = name',
 30, 5, now()),

-- 55. algorithms
(gen_random_uuid(),
 'Count Words', 'Contar Palabras',
 'Count the frequency of each word in "the cat sat on the mat the cat". Print the dictionary.',
 'Cuenta la frecuencia de cada palabra en "the cat sat on the mat the cat". Imprime el diccionario.',
 'python', 3, 'algorithms',
 'text = "the cat sat on the mat the cat"\nwords = text.split()\ncounts = {}\nfor word in words:\n    counts[word] = counts.___(word, 0) + 1\nprint(counts)',
 'text = "the cat sat on the mat the cat"\nwords = text.split()\ncounts = {}\nfor word in words:\n    counts[word] = counts.get(word, 0) + 1\nprint(counts)',
 '{''the'': 3, ''cat'': 2, ''sat'': 1, ''on'': 1, ''mat'': 1}',
 3,
 'Use dict.get() to retrieve a value with a default.', 'Usa dict.get() para recuperar un valor con un predeterminado.',
 'counts.get(word, 0) returns 0 if the word is not yet in the dict.', 'counts.get(word, 0) devuelve 0 si la palabra aún no está en el dict.',
 'counts.get(word, 0) + 1', 'counts.get(word, 0) + 1',
 30, 5, now()),

-- 56. math
(gen_random_uuid(),
 'Fibonacci Sequence', 'Secuencia de Fibonacci',
 'Print the first 8 Fibonacci numbers: 0 1 1 2 3 5 8 13.',
 'Imprime los primeros 8 números de Fibonacci: 0 1 1 2 3 5 8 13.',
 'python', 3, 'math',
 'a, b = 0, 1\nfor _ in range(8):\n    print(a, end=" ")\n    a, b = ___, ___',
 'a, b = 0, 1\nfor _ in range(8):\n    print(a, end=" ")\n    a, b = b, a + b',
 '0 1 1 2 3 5 8 13',
 3,
 'Each Fibonacci number is the sum of the two before it.', 'Cada número de Fibonacci es la suma de los dos anteriores.',
 'Update a and b simultaneously: a becomes b, b becomes a+b.', 'Actualiza a y b simultáneamente: a se convierte en b, b en a+b.',
 'a, b = b, a + b', 'a, b = b, a + b',
 30, 5, now()),

-- 57. data_structures
(gen_random_uuid(),
 'Set Operations', 'Operaciones con Conjuntos',
 'Find the intersection of {1, 2, 3, 4} and {3, 4, 5, 6} and print it.',
 'Encuentra la intersección de {1, 2, 3, 4} y {3, 4, 5, 6} e imprímela.',
 'python', 3, 'data_structures',
 'a = {1, 2, 3, 4}\nb = {3, 4, 5, 6}\nprint(a ___ b)',
 'a = {1, 2, 3, 4}\nb = {3, 4, 5, 6}\nprint(a & b)',
 '{3, 4}',
 3,
 'Sets support mathematical set operations.', 'Los conjuntos admiten operaciones matemáticas de conjuntos.',
 'Use & for intersection between two sets.', 'Usa & para la intersección entre dos conjuntos.',
 'a & b', 'a & b',
 30, 5, now()),

-- 58. functions
(gen_random_uuid(),
 'Lambda Function', 'Función Lambda',
 'Create a lambda that doubles a number. Print the result of doubling 7.',
 'Crea una lambda que doble un número. Imprime el resultado de doblar 7.',
 'python', 3, 'functions',
 'double = lambda x: ___\nprint(double(7))',
 'double = lambda x: x * 2\nprint(double(7))',
 '14',
 3,
 'Lambda functions are anonymous one-line functions.', 'Las funciones lambda son funciones anónimas de una línea.',
 'Syntax: lambda parameter: expression', 'Sintaxis: lambda parámetro: expresión',
 'lambda x: x * 2', 'lambda x: x * 2',
 30, 5, now()),

-- 59. algorithms
(gen_random_uuid(),
 'Palindrome Check', 'Verificar Palíndromo',
 'Write is_palindrome(s) that returns True if s is a palindrome. Test with "racecar".',
 'Escribe is_palindrome(s) que devuelva True si s es un palíndromo. Prueba con "racecar".',
 'python', 3, 'algorithms',
 'def is_palindrome(s):\n    return s == ___\n\nprint(is_palindrome("racecar"))',
 'def is_palindrome(s):\n    return s == s[::-1]\n\nprint(is_palindrome("racecar"))',
 'True',
 3,
 'A palindrome reads the same forwards and backwards.', 'Un palíndromo se lee igual hacia adelante que hacia atrás.',
 'Compare the string to its reverse.', 'Compara la cadena con su reverso.',
 's == s[::-1]', 's == s[::-1]',
 30, 5, now()),

-- 60. patterns
(gen_random_uuid(),
 'List Comprehension Filter', 'Filtro con Comprensión de Lista',
 'Create a list of even numbers from 1 to 20 using a list comprehension.',
 'Crea una lista de números pares del 1 al 20 usando comprensión de lista.',
 'python', 3, 'patterns',
 'evens = [x for x in range(1, 21) if ___]\nprint(evens)',
 'evens = [x for x in range(1, 21) if x % 2 == 0]\nprint(evens)',
 '[2, 4, 6, 8, 10, 12, 14, 16, 18, 20]',
 3,
 'Add a condition after the "for" clause in a list comprehension.', 'Agrega una condición después de la cláusula "for" en la comprensión de lista.',
 'Use if x % 2 == 0 to filter even numbers.', 'Usa if x % 2 == 0 para filtrar números pares.',
 'if x % 2 == 0', 'if x % 2 == 0',
 30, 5, now()),

-- 61. objects
(gen_random_uuid(),
 'Class Method', 'Método de Clase',
 'Add a method speak() to Dog that returns "Woof!". Call it on Dog("Rex").',
 'Agrega un método speak() a Dog que devuelva "Woof!". Llámalo en Dog("Rex").',
 'python', 3, 'objects',
 'class Dog:\n    def __init__(self, name):\n        self.name = name\n    def speak(self):\n        return ___\n\nprint(Dog("Rex").speak())',
 'class Dog:\n    def __init__(self, name):\n        self.name = name\n    def speak(self):\n        return "Woof!"\n\nprint(Dog("Rex").speak())',
 'Woof!',
 3,
 'Methods are functions defined inside a class.', 'Los métodos son funciones definidas dentro de una clase.',
 'Return the string "Woof!" from the speak method.', 'Devuelve la cadena "Woof!" desde el método speak.',
 'return "Woof!"', 'return "Woof!"',
 30, 5, now()),

-- 62. data_structures
(gen_random_uuid(),
 'Queue with Deque', 'Cola con Deque',
 'Use collections.deque to enqueue 1, 2, 3 then dequeue one. Print the result.',
 'Usa collections.deque para agregar 1, 2, 3 a la cola y luego quitar uno. Imprime el resultado.',
 'python', 3, 'data_structures',
 'from collections import deque\nq = deque()\nq.append(1)\nq.append(2)\nq.append(3)\nprint(q.___())',
 'from collections import deque\nq = deque()\nq.append(1)\nq.append(2)\nq.append(3)\nprint(q.popleft())',
 '1',
 3,
 'A queue is FIFO: first in, first out.', 'Una cola es FIFO: el primero en entrar es el primero en salir.',
 'Use popleft() to remove from the front of the deque.', 'Usa popleft() para eliminar del frente del deque.',
 'q.popleft()', 'q.popleft()',
 30, 5, now()),

-- 63. algorithms
(gen_random_uuid(),
 'Anagram Check', 'Verificar Anagrama',
 'Write is_anagram(a, b) that returns True if a and b are anagrams. Test with ("listen", "silent").',
 'Escribe is_anagram(a, b) que devuelva True si a y b son anagramas. Prueba con ("listen", "silent").',
 'python', 3, 'algorithms',
 'def is_anagram(a, b):\n    return sorted(___) == sorted(___)\n\nprint(is_anagram("listen", "silent"))',
 'def is_anagram(a, b):\n    return sorted(a) == sorted(b)\n\nprint(is_anagram("listen", "silent"))',
 'True',
 3,
 'Anagrams contain the same characters in different order.', 'Los anagramas contienen los mismos caracteres en diferente orden.',
 'Sorting both strings and comparing them is an elegant solution.', 'Ordenar ambas cadenas y compararlas es una solución elegante.',
 'sorted(a) == sorted(b)', 'sorted(a) == sorted(b)',
 30, 5, now()),

-- 64. strings
(gen_random_uuid(),
 'Count Vowels', 'Contar Vocales',
 'Count the number of vowels in "programming" and print it.',
 'Cuenta el número de vocales en "programming" e imprímelo.',
 'python', 3, 'strings',
 'text = "programming"\ncount = sum(1 for c in text if c in ___)\nprint(count)',
 'text = "programming"\ncount = sum(1 for c in text if c in "aeiou")\nprint(count)',
 '3',
 3,
 'Iterate over each character and check if it is a vowel.', 'Itera sobre cada carácter y verifica si es una vocal.',
 'Check if the character is in the string "aeiou".', 'Verifica si el carácter está en la cadena "aeiou".',
 'c in "aeiou"', 'c in "aeiou"',
 30, 5, now()),

-- 65. math
(gen_random_uuid(),
 'Prime Check', 'Verificar Primo',
 'Write is_prime(n) that returns True if n is prime. Test with is_prime(17).',
 'Escribe is_prime(n) que devuelva True si n es primo. Prueba con is_prime(17).',
 'python', 3, 'math',
 'def is_prime(n):\n    if n < 2:\n        return False\n    for i in range(2, int(n**0.5) + 1):\n        if n % i == ___:\n            return False\n    return True\n\nprint(is_prime(17))',
 'def is_prime(n):\n    if n < 2:\n        return False\n    for i in range(2, int(n**0.5) + 1):\n        if n % i == 0:\n            return False\n    return True\n\nprint(is_prime(17))',
 'True',
 3,
 'A prime number has no divisors other than 1 and itself.', 'Un número primo no tiene divisores aparte de 1 y él mismo.',
 'If any i divides n evenly (n % i == 0), n is not prime.', 'Si algún i divide n exactamente (n % i == 0), n no es primo.',
 'if n % i == 0: return False', 'if n % i == 0: return False',
 30, 5, now()),

-- 66. patterns
(gen_random_uuid(),
 'Nested Loop Star Triangle', 'Triángulo de Asteriscos con Bucle Anidado',
 'Print a right triangle of stars with 4 rows: row 1 has 1 star, row 4 has 4 stars.',
 'Imprime un triángulo rectángulo de estrellas con 4 filas: fila 1 tiene 1, fila 4 tiene 4.',
 'python', 3, 'patterns',
 'for i in range(1, ___):\n    print("*" * i)',
 'for i in range(1, 5):\n    print("*" * i)',
 '*\n**\n***\n****',
 3,
 'Multiply the star string by the row number.', 'Multiplica la cadena de estrellas por el número de fila.',
 'range(1, 5) gives 1, 2, 3, 4 — use that as the count.', 'range(1, 5) da 1, 2, 3, 4 — úsalo como el conteo.',
 'for i in range(1, 5): print("*" * i)', 'for i in range(1, 5): print("*" * i)',
 30, 5, now()),

-- 67. functions
(gen_random_uuid(),
 'Map Function', 'Función Map',
 'Use map() to square each number in [1, 2, 3, 4]. Print as a list.',
 'Usa map() para elevar al cuadrado cada número en [1, 2, 3, 4]. Imprime como lista.',
 'python', 3, 'functions',
 'nums = [1, 2, 3, 4]\nresult = list(map(___, nums))\nprint(result)',
 'nums = [1, 2, 3, 4]\nresult = list(map(lambda x: x**2, nums))\nprint(result)',
 '[1, 4, 9, 16]',
 3,
 'map() applies a function to every element of an iterable.', 'map() aplica una función a cada elemento de un iterable.',
 'Pass a lambda as the first argument to map().', 'Pasa una lambda como primer argumento a map().',
 'map(lambda x: x**2, nums)', 'map(lambda x: x**2, nums)',
 30, 5, now()),

-- 68. objects
(gen_random_uuid(),
 'Inheritance', 'Herencia',
 'Create class Animal with speak() returning "...". Create Dog(Animal) overriding speak() to return "Woof". Print Dog().speak().',
 'Crea clase Animal con speak() que devuelva "...". Crea Dog(Animal) sobreescribiendo speak() para devolver "Woof". Imprime Dog().speak().',
 'python', 3, 'objects',
 'class Animal:\n    def speak(self):\n        return "..."\n\nclass Dog(___):\n    def speak(self):\n        return "Woof"\n\nprint(Dog().speak())',
 'class Animal:\n    def speak(self):\n        return "..."\n\nclass Dog(Animal):\n    def speak(self):\n        return "Woof"\n\nprint(Dog().speak())',
 'Woof',
 3,
 'Put the parent class name in parentheses when defining a subclass.', 'Pon el nombre de la clase padre en paréntesis al definir una subclase.',
 'class Dog(Animal): inherits from Animal.', 'class Dog(Animal): hereda de Animal.',
 'class Dog(Animal):', 'class Dog(Animal):',
 30, 5, now()),

-- 69. algorithms
(gen_random_uuid(),
 'Flatten Nested List', 'Aplanar Lista Anidada',
 'Flatten [[1, 2], [3, 4], [5]] into a single list and print it.',
 'Aplana [[1, 2], [3, 4], [5]] en una sola lista e imprímela.',
 'python', 3, 'algorithms',
 'nested = [[1, 2], [3, 4], [5]]\nflat = [x for ___ in nested for x in ___]\nprint(flat)',
 'nested = [[1, 2], [3, 4], [5]]\nflat = [x for sub in nested for x in sub]\nprint(flat)',
 '[1, 2, 3, 4, 5]',
 3,
 'Use a nested list comprehension to flatten.', 'Usa una comprensión de lista anidada para aplanar.',
 'Outer loop: for sub in nested. Inner: for x in sub.', 'Bucle externo: for sub in nested. Interior: for x in sub.',
 '[x for sub in nested for x in sub]', '[x for sub in nested for x in sub]',
 30, 5, now()),

-- 70. data_structures
(gen_random_uuid(),
 'Counter Most Common', 'Counter Más Común',
 'Use Counter to find the 2 most common letters in "mississippi". Print them.',
 'Usa Counter para encontrar las 2 letras más comunes en "mississippi". Imprímelas.',
 'python', 3, 'data_structures',
 'from collections import Counter\nc = Counter("mississippi")\nprint(c.most_common(___))',
 'from collections import Counter\nc = Counter("mississippi")\nprint(c.most_common(2))',
 '[(''s'', 4), (''i'', 4)]',
 3,
 'Counter has a method to get the most frequent elements.', 'Counter tiene un método para obtener los elementos más frecuentes.',
 'most_common(n) returns the n most common elements.', 'most_common(n) devuelve los n elementos más comunes.',
 'c.most_common(2)', 'c.most_common(2)',
 30, 5, now()),

-- 71. arrays
(gen_random_uuid(),
 'Zip Two Lists', 'Combinar Dos Listas',
 'Pair up ["a","b","c"] with [1,2,3] using zip and print each pair.',
 'Empareja ["a","b","c"] con [1,2,3] usando zip e imprime cada par.',
 'python', 3, 'arrays',
 'keys = ["a", "b", "c"]\nvals = [1, 2, 3]\nfor k, v in ___(keys, vals):\n    print(k, v)',
 'keys = ["a", "b", "c"]\nvals = [1, 2, 3]\nfor k, v in zip(keys, vals):\n    print(k, v)',
 'a 1\nb 2\nc 3',
 3,
 'zip() pairs elements from two iterables.', 'zip() empareja elementos de dos iterables.',
 'Use zip(keys, vals) and unpack each pair as k, v.', 'Usa zip(keys, vals) y desempaqueta cada par como k, v.',
 'for k, v in zip(keys, vals):', 'for k, v in zip(keys, vals):',
 30, 5, now()),

-- 72. strings
(gen_random_uuid(),
 'Join List to String', 'Unir Lista en Cadena',
 'Join ["Hello", "World", "Python"] into a single string with spaces and print it.',
 'Une ["Hello", "World", "Python"] en una sola cadena con espacios e imprímela.',
 'python', 3, 'strings',
 'words = ["Hello", "World", "Python"]\nprint(___.join(words))',
 'words = ["Hello", "World", "Python"]\nprint(" ".join(words))',
 'Hello World Python',
 3,
 'Strings have a method to join a list of strings.', 'Las cadenas tienen un método para unir una lista de cadenas.',
 'Use separator.join(list) — the separator goes before .join.', 'Usa separador.join(lista) — el separador va antes de .join.',
 '" ".join(words)', '" ".join(words)',
 30, 5, now()),

-- 73. algorithms
(gen_random_uuid(),
 'Binary Search', 'Búsqueda Binaria',
 'Implement binary search on a sorted list. Find 7 in [1,3,5,7,9,11]. Return index.',
 'Implementa búsqueda binaria en una lista ordenada. Encuentra 7 en [1,3,5,7,9,11]. Devuelve el índice.',
 'python', 3, 'algorithms',
 'def binary_search(lst, target):\n    lo, hi = 0, len(lst) - 1\n    while lo <= hi:\n        mid = (lo + hi) // 2\n        if lst[mid] == target:\n            return mid\n        elif lst[mid] < target:\n            lo = ___ + 1\n        else:\n            hi = ___ - 1\n    return -1\n\nprint(binary_search([1,3,5,7,9,11], 7))',
 'def binary_search(lst, target):\n    lo, hi = 0, len(lst) - 1\n    while lo <= hi:\n        mid = (lo + hi) // 2\n        if lst[mid] == target:\n            return mid\n        elif lst[mid] < target:\n            lo = mid + 1\n        else:\n            hi = mid - 1\n    return -1\n\nprint(binary_search([1,3,5,7,9,11], 7))',
 '3',
 3,
 'Binary search halves the search space each iteration.', 'La búsqueda binaria reduce a la mitad el espacio de búsqueda cada iteración.',
 'If target > mid element, search right half: lo = mid + 1.', 'Si target > elemento mid, busca en la mitad derecha: lo = mid + 1.',
 'lo = mid + 1 / hi = mid - 1', 'lo = mid + 1 / hi = mid - 1',
 30, 5, now()),

-- 74. math
(gen_random_uuid(),
 'GCD Calculation', 'Cálculo del MCD',
 'Use the math module to print the GCD of 48 and 18.',
 'Usa el módulo math para imprimir el MCD de 48 y 18.',
 'python', 3, 'math',
 'import math\nprint(math.___(48, 18))',
 'import math\nprint(math.gcd(48, 18))',
 '6',
 3,
 'The math module has many mathematical functions.', 'El módulo math tiene muchas funciones matemáticas.',
 'The function for greatest common divisor is math.gcd().', 'La función para el máximo común divisor es math.gcd().',
 'math.gcd(48, 18)', 'math.gcd(48, 18)',
 30, 5, now()),

-- 75. patterns
(gen_random_uuid(),
 'Generator Expression', 'Expresión Generadora',
 'Use a generator expression to sum squares of 1 to 100. Print the result.',
 'Usa una expresión generadora para sumar los cuadrados del 1 al 100. Imprime el resultado.',
 'python', 3, 'patterns',
 'total = sum(___ for x in range(1, 101))\nprint(total)',
 'total = sum(x**2 for x in range(1, 101))\nprint(total)',
 '338350',
 3,
 'Generator expressions look like list comprehensions but use parentheses.', 'Las expresiones generadoras parecen comprensiones de lista pero usan paréntesis.',
 'Inside sum(), write x**2 for x in range(1, 101).', 'Dentro de sum(), escribe x**2 for x in range(1, 101).',
 'sum(x**2 for x in range(1, 101))', 'sum(x**2 for x in range(1, 101))',
 30, 5, now()),

-- ============================================================
-- DIFFICULTY 4 — 15 exercises (points=50, penalty=10)
-- ============================================================

-- 76. algorithms
(gen_random_uuid(),
 'Merge Sort', 'Ordenamiento por Mezcla',
 'Implement merge sort and sort [38, 27, 43, 3, 9, 82, 10]. Print the sorted list.',
 'Implementa merge sort y ordena [38, 27, 43, 3, 9, 82, 10]. Imprime la lista ordenada.',
 'python', 4, 'algorithms',
 'def merge_sort(lst):\n    if len(lst) <= 1:\n        return lst\n    mid = len(lst) // 2\n    left = merge_sort(lst[:mid])\n    right = merge_sort(lst[mid:])\n    return merge(left, right)\n\ndef merge(l, r):\n    result = []\n    i = j = 0\n    while i < len(l) and j < len(r):\n        if l[i] <= r[j]:\n            result.append(l[___])\n            i += 1\n        else:\n            result.append(r[___])\n            j += 1\n    return result + l[i:] + r[j:]\n\nprint(merge_sort([38, 27, 43, 3, 9, 82, 10]))',
 'def merge_sort(lst):\n    if len(lst) <= 1:\n        return lst\n    mid = len(lst) // 2\n    left = merge_sort(lst[:mid])\n    right = merge_sort(lst[mid:])\n    return merge(left, right)\n\ndef merge(l, r):\n    result = []\n    i = j = 0\n    while i < len(l) and j < len(r):\n        if l[i] <= r[j]:\n            result.append(l[i])\n            i += 1\n        else:\n            result.append(r[j])\n            j += 1\n    return result + l[i:] + r[j:]\n\nprint(merge_sort([38, 27, 43, 3, 9, 82, 10]))',
 '[3, 9, 10, 27, 38, 43, 82]',
 3,
 'Merge sort divides the list in half recursively then merges.', 'Merge sort divide la lista a la mitad recursivamente y luego combina.',
 'The merge function picks the smaller element from l[i] or r[j].', 'La función merge elige el elemento menor de l[i] o r[j].',
 'result.append(l[i]) / result.append(r[j])', 'result.append(l[i]) / result.append(r[j])',
 50, 10, now()),

-- 77. data_structures
(gen_random_uuid(),
 'Linked List Node', 'Nodo de Lista Enlazada',
 'Create a Node class and build a linked list 1->2->3. Traverse and print each value.',
 'Crea una clase Node y construye una lista enlazada 1->2->3. Recorre e imprime cada valor.',
 'python', 4, 'data_structures',
 'class Node:\n    def __init__(self, val):\n        self.val = val\n        self.next = None\n\nhead = Node(1)\nhead.next = Node(2)\nhead.next.next = Node(3)\n\ncurrent = head\nwhile current:\n    print(current.___)\n    current = current.___',
 'class Node:\n    def __init__(self, val):\n        self.val = val\n        self.next = None\n\nhead = Node(1)\nhead.next = Node(2)\nhead.next.next = Node(3)\n\ncurrent = head\nwhile current:\n    print(current.val)\n    current = current.next',
 '1\n2\n3',
 3,
 'A linked list node has a value and a pointer to the next node.', 'Un nodo de lista enlazada tiene un valor y un puntero al siguiente nodo.',
 'Print current.val and advance with current = current.next.', 'Imprime current.val y avanza con current = current.next.',
 'print(current.val); current = current.next', 'print(current.val); current = current.next',
 50, 10, now()),

-- 78. objects
(gen_random_uuid(),
 'Dunder Methods', 'Métodos Dunder',
 'Create a Vector class with __add__ so Vector(1,2) + Vector(3,4) prints Vector(4,6).',
 'Crea una clase Vector con __add__ para que Vector(1,2) + Vector(3,4) imprima Vector(4,6).',
 'python', 4, 'objects',
 'class Vector:\n    def __init__(self, x, y):\n        self.x = x\n        self.y = y\n    def __add__(self, other):\n        return Vector(self.x + other.___, self.y + other.___)\n    def __repr__(self):\n        return f"Vector({self.x},{self.y})"\n\nprint(Vector(1,2) + Vector(3,4))',
 'class Vector:\n    def __init__(self, x, y):\n        self.x = x\n        self.y = y\n    def __add__(self, other):\n        return Vector(self.x + other.x, self.y + other.y)\n    def __repr__(self):\n        return f"Vector({self.x},{self.y})"\n\nprint(Vector(1,2) + Vector(3,4))',
 'Vector(4,6)',
 3,
 'Dunder methods let you define behavior for operators.', 'Los métodos dunder te permiten definir el comportamiento de los operadores.',
 '__add__ receives self and other — access other.x and other.y.', '__add__ recibe self y other — accede a other.x y other.y.',
 'other.x, other.y', 'other.x, other.y',
 50, 10, now()),

-- 79. algorithms
(gen_random_uuid(),
 'Two Sum Problem', 'Problema Two Sum',
 'Find two indices in [2, 7, 11, 15] that sum to 9. Print the indices.',
 'Encuentra dos índices en [2, 7, 11, 15] que sumen 9. Imprime los índices.',
 'python', 4, 'algorithms',
 'def two_sum(nums, target):\n    seen = {}\n    for i, n in enumerate(nums):\n        diff = target - n\n        if diff in seen:\n            return [seen[diff], i]\n        seen[___] = i\n    return []\n\nprint(two_sum([2, 7, 11, 15], 9))',
 'def two_sum(nums, target):\n    seen = {}\n    for i, n in enumerate(nums):\n        diff = target - n\n        if diff in seen:\n            return [seen[diff], i]\n        seen[n] = i\n    return []\n\nprint(two_sum([2, 7, 11, 15], 9))',
 '[0, 1]',
 3,
 'Use a hash map to store numbers you''ve already seen.', 'Usa un mapa hash para almacenar los números que ya has visto.',
 'Store the current number n as the key: seen[n] = i.', 'Almacena el número actual n como clave: seen[n] = i.',
 'seen[n] = i', 'seen[n] = i',
 50, 10, now()),

-- 80. functions
(gen_random_uuid(),
 'Decorator Function', 'Función Decoradora',
 'Write a timer decorator that prints "Running..." before a function executes. Apply it to hello().',
 'Escribe un decorador timer que imprima "Running..." antes de que una función se ejecute. Aplícalo a hello().',
 'python', 4, 'functions',
 'def timer(func):\n    def wrapper():\n        print("Running...")\n        return func()\n    return ___\n\n@timer\ndef hello():\n    print("Hello!")\n\nhello()',
 'def timer(func):\n    def wrapper():\n        print("Running...")\n        return func()\n    return wrapper\n\n@timer\ndef hello():\n    print("Hello!")\n\nhello()',
 'Running...\nHello!',
 3,
 'A decorator wraps a function to add behavior.', 'Un decorador envuelve una función para agregar comportamiento.',
 'The decorator must return the inner wrapper function.', 'El decorador debe devolver la función wrapper interna.',
 'return wrapper', 'return wrapper',
 50, 10, now()),

-- 81. data_structures
(gen_random_uuid(),
 'Binary Tree Traversal', 'Recorrido de Árbol Binario',
 'Build a BST with values 4,2,6,1,3. Do inorder traversal and print values.',
 'Construye un BST con valores 4,2,6,1,3. Haz un recorrido inorden e imprime los valores.',
 'python', 4, 'data_structures',
 'class Node:\n    def __init__(self, val):\n        self.val = val\n        self.left = self.right = None\n\ndef inorder(node):\n    if node:\n        inorder(node.___)\n        print(node.val, end=" ")\n        inorder(node.___)\n\nroot = Node(4)\nroot.left = Node(2)\nroot.right = Node(6)\nroot.left.left = Node(1)\nroot.left.right = Node(3)\ninorder(root)',
 'class Node:\n    def __init__(self, val):\n        self.val = val\n        self.left = self.right = None\n\ndef inorder(node):\n    if node:\n        inorder(node.left)\n        print(node.val, end=" ")\n        inorder(node.right)\n\nroot = Node(4)\nroot.left = Node(2)\nroot.right = Node(6)\nroot.left.left = Node(1)\nroot.left.right = Node(3)\ninorder(root)',
 '1 2 3 4 6',
 3,
 'Inorder traversal visits: left, root, right.', 'El recorrido inorden visita: izquierdo, raíz, derecho.',
 'Recurse into node.left first, then print, then node.right.', 'Recursa en node.left primero, luego imprime, luego node.right.',
 'inorder(node.left) / inorder(node.right)', 'inorder(node.left) / inorder(node.right)',
 50, 10, now()),

-- 82. algorithms
(gen_random_uuid(),
 'Longest Common Prefix', 'Prefijo Común Más Largo',
 'Find the longest common prefix of ["flower","flow","flight"]. Print it.',
 'Encuentra el prefijo común más largo de ["flower","flow","flight"]. Imprímelo.',
 'python', 4, 'algorithms',
 'def lcp(strs):\n    if not strs:\n        return ""\n    prefix = strs[0]\n    for s in strs[1:]:\n        while not s.startswith(___):\n            prefix = prefix[:-1]\n    return prefix\n\nprint(lcp(["flower","flow","flight"]))',
 'def lcp(strs):\n    if not strs:\n        return ""\n    prefix = strs[0]\n    for s in strs[1:]:\n        while not s.startswith(prefix):\n            prefix = prefix[:-1]\n    return prefix\n\nprint(lcp(["flower","flow","flight"]))',
 'fl',
 3,
 'Start with the first string as the prefix and trim from the end.', 'Comienza con la primera cadena como prefijo y recorta desde el final.',
 'Check s.startswith(prefix) — if not, remove the last character.', 'Verifica s.startswith(prefix) — si no, elimina el último carácter.',
 's.startswith(prefix)', 's.startswith(prefix)',
 50, 10, now()),

-- 83. patterns
(gen_random_uuid(),
 'Memoization with Cache', 'Memoización con Caché',
 'Use functools.lru_cache to memoize a slow fib(n). Print fib(35).',
 'Usa functools.lru_cache para memoizar un fib(n) lento. Imprime fib(35).',
 'python', 4, 'patterns',
 'from functools import lru_cache\n\n@lru_cache(maxsize=___)\ndef fib(n):\n    if n < 2:\n        return n\n    return fib(n-1) + fib(n-2)\n\nprint(fib(35))',
 'from functools import lru_cache\n\n@lru_cache(maxsize=None)\ndef fib(n):\n    if n < 2:\n        return n\n    return fib(n-1) + fib(n-2)\n\nprint(fib(35))',
 '9227465',
 3,
 'lru_cache caches function results to avoid recomputation.', 'lru_cache almacena en caché los resultados de funciones para evitar recomputación.',
 'Use maxsize=None to allow unlimited cache entries.', 'Usa maxsize=None para permitir entradas de caché ilimitadas.',
 '@lru_cache(maxsize=None)', '@lru_cache(maxsize=None)',
 50, 10, now()),

-- 84. objects
(gen_random_uuid(),
 'Context Manager', 'Gestor de Contexto',
 'Create a Timer context manager using __enter__/__exit__ that prints "start" and "end". Use it with a with block.',
 'Crea un gestor de contexto Timer usando __enter__/__exit__ que imprima "start" y "end". Úsalo con un bloque with.',
 'python', 4, 'objects',
 'class Timer:\n    def __enter__(self):\n        print("start")\n        return self\n    def __exit__(self, *args):\n        print("end")\n\nwith ___():\n    pass',
 'class Timer:\n    def __enter__(self):\n        print("start")\n        return self\n    def __exit__(self, *args):\n        print("end")\n\nwith Timer():\n    pass',
 'start\nend',
 3,
 '__enter__ runs when entering the with block, __exit__ on leaving.', '__enter__ se ejecuta al entrar al bloque with, __exit__ al salir.',
 'Use with Timer(): to invoke the context manager.', 'Usa with Timer(): para invocar el gestor de contexto.',
 'with Timer():', 'with Timer():',
 50, 10, now()),

-- 85. algorithms
(gen_random_uuid(),
 'Valid Parentheses', 'Paréntesis Válidos',
 'Write is_valid(s) that returns True if brackets in s are balanced. Test "({[]})".',
 'Escribe is_valid(s) que devuelva True si los corchetes en s están balanceados. Prueba "({[]})".',
 'python', 4, 'algorithms',
 'def is_valid(s):\n    stack = []\n    pairs = {")": "(", "}": "{", "]": "["}\n    for c in s:\n        if c in "([{":\n            stack.append(c)\n        elif c in pairs:\n            if not stack or stack[-1] != pairs[c]:\n                return False\n            stack.___() \n    return len(stack) == ___\n\nprint(is_valid("({[]})"))',
 'def is_valid(s):\n    stack = []\n    pairs = {")": "(", "}": "{", "]": "["}\n    for c in s:\n        if c in "([{":\n            stack.append(c)\n        elif c in pairs:\n            if not stack or stack[-1] != pairs[c]:\n                return False\n            stack.pop()\n    return len(stack) == 0\n\nprint(is_valid("({[]})"))',
 'True',
 3,
 'Use a stack to track opening brackets.', 'Usa una pila para rastrear los corchetes de apertura.',
 'Pop when a closing bracket matches; return True if stack is empty.', 'Elimina cuando un corchete de cierre coincide; devuelve True si la pila está vacía.',
 'stack.pop() / len(stack) == 0', 'stack.pop() / len(stack) == 0',
 50, 10, now()),

-- 86. math
(gen_random_uuid(),
 'Matrix Multiplication', 'Multiplicación de Matrices',
 'Multiply 2x2 matrices A=[[1,2],[3,4]] and B=[[5,6],[7,8]]. Print the result.',
 'Multiplica las matrices 2x2 A=[[1,2],[3,4]] y B=[[5,6],[7,8]]. Imprime el resultado.',
 'python', 4, 'math',
 'A = [[1,2],[3,4]]\nB = [[5,6],[7,8]]\nC = [[sum(A[i][k]*B[k][j] for k in range(2)) for j in range(2)] for i in range(2)]\nprint(___)',
 'A = [[1,2],[3,4]]\nB = [[5,6],[7,8]]\nC = [[sum(A[i][k]*B[k][j] for k in range(2)) for j in range(2)] for i in range(2)]\nprint(C)',
 '[[19, 22], [43, 50]]',
 3,
 'Each element C[i][j] is the dot product of row i of A and column j of B.', 'Cada elemento C[i][j] es el producto punto de la fila i de A y la columna j de B.',
 'Use a nested list comprehension with sum().', 'Usa una comprensión de lista anidada con sum().',
 'print(C)', 'print(C)',
 50, 10, now()),

-- 87. functions
(gen_random_uuid(),
 'Currying', 'Currificación',
 'Write a curried add(a)(b) function. Print add(3)(4).',
 'Escribe una función currificada add(a)(b). Imprime add(3)(4).',
 'python', 4, 'functions',
 'def add(a):\n    def inner(b):\n        return ___ + ___\n    return inner\n\nprint(add(3)(4))',
 'def add(a):\n    def inner(b):\n        return a + b\n    return inner\n\nprint(add(3)(4))',
 '7',
 3,
 'Currying transforms a function with multiple args into nested functions.', 'La currificación transforma una función con múltiples argumentos en funciones anidadas.',
 'The inner function captures a from the outer scope: return a + b.', 'La función interna captura a del ámbito externo: return a + b.',
 'return a + b', 'return a + b',
 50, 10, now()),

-- 88. data_structures
(gen_random_uuid(),
 'Graph BFS', 'BFS en Grafo',
 'Do BFS on graph {1:[2,3],2:[4],3:[4],4:[]} starting from 1. Print visit order.',
 'Haz BFS en el grafo {1:[2,3],2:[4],3:[4],4:[]} desde 1. Imprime el orden de visita.',
 'python', 4, 'data_structures',
 'from collections import deque\ngraph = {1:[2,3],2:[4],3:[4],4:[]}\ndef bfs(start):\n    visited = []\n    q = deque([start])\n    seen = {start}\n    while q:\n        node = q.popleft()\n        visited.append(node)\n        for nb in graph[node]:\n            if nb not in seen:\n                seen.add(nb)\n                q.___(nb)\n    return visited\nprint(bfs(1))',
 'from collections import deque\ngraph = {1:[2,3],2:[4],3:[4],4:[]}\ndef bfs(start):\n    visited = []\n    q = deque([start])\n    seen = {start}\n    while q:\n        node = q.popleft()\n        visited.append(node)\n        for nb in graph[node]:\n            if nb not in seen:\n                seen.add(nb)\n                q.append(nb)\n    return visited\nprint(bfs(1))',
 '[1, 2, 3, 4]',
 3,
 'BFS uses a queue to visit nodes level by level.', 'BFS usa una cola para visitar nodos nivel por nivel.',
 'Add unvisited neighbors to the queue with q.append(nb).', 'Agrega vecinos no visitados a la cola con q.append(nb).',
 'q.append(nb)', 'q.append(nb)',
 50, 10, now()),

-- 89. algorithms
(gen_random_uuid(),
 'Group Anagrams', 'Agrupar Anagramas',
 'Group ["eat","tea","tan","ate","nat","bat"] into anagram clusters. Print sorted groups.',
 'Agrupa ["eat","tea","tan","ate","nat","bat"] en grupos de anagramas. Imprime los grupos ordenados.',
 'python', 4, 'algorithms',
 'from collections import defaultdict\ndef group_anagrams(words):\n    groups = defaultdict(list)\n    for w in words:\n        key = tuple(sorted(___))\n        groups[key].append(w)\n    return sorted([sorted(g) for g in groups.values()])\n\nprint(group_anagrams(["eat","tea","tan","ate","nat","bat"]))',
 'from collections import defaultdict\ndef group_anagrams(words):\n    groups = defaultdict(list)\n    for w in words:\n        key = tuple(sorted(w))\n        groups[key].append(w)\n    return sorted([sorted(g) for g in groups.values()])\n\nprint(group_anagrams(["eat","tea","tan","ate","nat","bat"]))',
 '[[''ate'', ''eat'', ''tea''], [''bat''], [''nat'', ''tan'']]',
 3,
 'Sort each word''s letters to create a canonical key.', 'Ordena las letras de cada palabra para crear una clave canónica.',
 'key = tuple(sorted(w)) groups anagrams together.', 'key = tuple(sorted(w)) agrupa los anagramas juntos.',
 'key = tuple(sorted(w))', 'key = tuple(sorted(w))',
 50, 10, now()),

-- 90. patterns
(gen_random_uuid(),
 'Iterator Protocol', 'Protocolo Iterador',
 'Create a Countdown class that iterates from n down to 1 using __iter__ and __next__.',
 'Crea una clase Countdown que itere desde n hasta 1 usando __iter__ y __next__.',
 'python', 4, 'patterns',
 'class Countdown:\n    def __init__(self, n):\n        self.n = n\n    def __iter__(self):\n        return self\n    def __next__(self):\n        if self.n <= 0:\n            raise ___\n        val = self.n\n        self.n -= 1\n        return val\n\nfor x in Countdown(3):\n    print(x)',
 'class Countdown:\n    def __init__(self, n):\n        self.n = n\n    def __iter__(self):\n        return self\n    def __next__(self):\n        if self.n <= 0:\n            raise StopIteration\n        val = self.n\n        self.n -= 1\n        return val\n\nfor x in Countdown(3):\n    print(x)',
 '3\n2\n1',
 3,
 'Raise StopIteration to signal the end of iteration.', 'Lanza StopIteration para señalar el fin de la iteración.',
 'When n reaches 0, raise StopIteration inside __next__.', 'Cuando n llega a 0, lanza StopIteration dentro de __next__.',
 'raise StopIteration', 'raise StopIteration',
 50, 10, now()),

-- ============================================================
-- DIFFICULTY 5 — 10 exercises (points=100, penalty=10)
-- ============================================================

-- 91. algorithms
(gen_random_uuid(),
 'LRU Cache Implementation', 'Implementación de Caché LRU',
 'Implement an LRU cache with capacity 2 supporting get(key) and put(key,val). Test: put(1,1), put(2,2), get(1) → 1, put(3,3), get(2) → -1.',
 'Implementa una caché LRU con capacidad 2 con get(clave) y put(clave,val). Prueba: put(1,1), put(2,2), get(1) → 1, put(3,3), get(2) → -1.',
 'python', 5, 'algorithms',
 'from collections import OrderedDict\nclass LRUCache:\n    def __init__(self, cap):\n        self.cap = cap\n        self.cache = OrderedDict()\n    def get(self, key):\n        if key not in self.cache:\n            return -1\n        self.cache.move_to_end(___)\n        return self.cache[key]\n    def put(self, key, val):\n        self.cache[key] = val\n        self.cache.move_to_end(key)\n        if len(self.cache) > self.cap:\n            self.cache.popitem(last=___)\n\nc = LRUCache(2)\nc.put(1,1); c.put(2,2)\nprint(c.get(1))\nc.put(3,3)\nprint(c.get(2))',
 'from collections import OrderedDict\nclass LRUCache:\n    def __init__(self, cap):\n        self.cap = cap\n        self.cache = OrderedDict()\n    def get(self, key):\n        if key not in self.cache:\n            return -1\n        self.cache.move_to_end(key)\n        return self.cache[key]\n    def put(self, key, val):\n        self.cache[key] = val\n        self.cache.move_to_end(key)\n        if len(self.cache) > self.cap:\n            self.cache.popitem(last=False)\n\nc = LRUCache(2)\nc.put(1,1); c.put(2,2)\nprint(c.get(1))\nc.put(3,3)\nprint(c.get(2))',
 '1\n-1',
 3,
 'OrderedDict preserves insertion order and supports move_to_end.', 'OrderedDict preserva el orden de inserción y admite move_to_end.',
 'move_to_end(key) marks a key as recently used. popitem(last=False) removes oldest.',
 'move_to_end(key) marca una clave como usada recientemente. popitem(last=False) elimina la más antigua.',
 'move_to_end(key) / popitem(last=False)', 'move_to_end(key) / popitem(last=False)',
 100, 10, now()),

-- 92. algorithms
(gen_random_uuid(),
 'Longest Increasing Subsequence', 'Subsecuencia Creciente Más Larga',
 'Find the length of the longest increasing subsequence in [10, 9, 2, 5, 3, 7, 101, 18]. Print it.',
 'Encuentra la longitud de la subsecuencia creciente más larga en [10, 9, 2, 5, 3, 7, 101, 18]. Imprímela.',
 'python', 5, 'algorithms',
 'def lis(nums):\n    dp = [1] * len(nums)\n    for i in range(1, len(nums)):\n        for j in range(i):\n            if nums[j] < nums[i]:\n                dp[i] = max(dp[i], dp[j] + ___)\n    return max(dp)\n\nprint(lis([10, 9, 2, 5, 3, 7, 101, 18]))',
 'def lis(nums):\n    dp = [1] * len(nums)\n    for i in range(1, len(nums)):\n        for j in range(i):\n            if nums[j] < nums[i]:\n                dp[i] = max(dp[i], dp[j] + 1)\n    return max(dp)\n\nprint(lis([10, 9, 2, 5, 3, 7, 101, 18]))',
 '4',
 3,
 'Use dynamic programming where dp[i] = length of LIS ending at index i.', 'Usa programación dinámica donde dp[i] = longitud del LIS que termina en el índice i.',
 'If nums[j] < nums[i], then dp[i] = max(dp[i], dp[j] + 1).', 'Si nums[j] < nums[i], entonces dp[i] = max(dp[i], dp[j] + 1).',
 'dp[j] + 1', 'dp[j] + 1',
 100, 10, now()),

-- 93. data_structures
(gen_random_uuid(),
 'Trie Implementation', 'Implementación de Trie',
 'Implement a Trie with insert and search. Insert "apple", search "apple" → True, search "app" → False.',
 'Implementa un Trie con insert y search. Inserta "apple", busca "apple" → True, busca "app" → False.',
 'python', 5, 'data_structures',
 'class Trie:\n    def __init__(self):\n        self.children = {}\n        self.end = False\n    def insert(self, word):\n        node = self\n        for c in word:\n            if c not in node.children:\n                node.children[c] = Trie()\n            node = node.children[c]\n        node.___ = True\n    def search(self, word):\n        node = self\n        for c in word:\n            if c not in node.children:\n                return False\n            node = node.children[c]\n        return node.___\n\nt = Trie()\nt.insert("apple")\nprint(t.search("apple"))\nprint(t.search("app"))',
 'class Trie:\n    def __init__(self):\n        self.children = {}\n        self.end = False\n    def insert(self, word):\n        node = self\n        for c in word:\n            if c not in node.children:\n                node.children[c] = Trie()\n            node = node.children[c]\n        node.end = True\n    def search(self, word):\n        node = self\n        for c in word:\n            if c not in node.children:\n                return False\n            node = node.children[c]\n        return node.end\n\nt = Trie()\nt.insert("apple")\nprint(t.search("apple"))\nprint(t.search("app"))',
 'True\nFalse',
 3,
 'A Trie stores characters as nodes; mark the last node of a word.', 'Un Trie almacena caracteres como nodos; marca el último nodo de una palabra.',
 'Set node.end = True after inserting all characters. search returns node.end.', 'Establece node.end = True después de insertar todos los caracteres. search devuelve node.end.',
 'node.end = True / return node.end', 'node.end = True / return node.end',
 100, 10, now()),

-- 94. algorithms
(gen_random_uuid(),
 'Coin Change DP', 'Cambio de Monedas DP',
 'Find minimum coins to make amount=11 with coins [1,5,6,9]. Print the count.',
 'Encuentra el mínimo de monedas para hacer amount=11 con monedas [1,5,6,9]. Imprime el conteo.',
 'python', 5, 'algorithms',
 'def coin_change(coins, amount):\n    dp = [float("inf")] * (amount + 1)\n    dp[0] = 0\n    for i in range(1, amount + 1):\n        for c in coins:\n            if c <= i:\n                dp[i] = min(dp[i], dp[i - c] + ___)\n    return dp[amount] if dp[amount] != float("inf") else -1\n\nprint(coin_change([1, 5, 6, 9], 11))',
 'def coin_change(coins, amount):\n    dp = [float("inf")] * (amount + 1)\n    dp[0] = 0\n    for i in range(1, amount + 1):\n        for c in coins:\n            if c <= i:\n                dp[i] = min(dp[i], dp[i - c] + 1)\n    return dp[amount] if dp[amount] != float("inf") else -1\n\nprint(coin_change([1, 5, 6, 9], 11))',
 '2',
 3,
 'dp[i] = minimum coins needed to make amount i.', 'dp[i] = mínimo de monedas necesarias para hacer el monto i.',
 'dp[i] = min(dp[i], dp[i - coin] + 1) for each valid coin.', 'dp[i] = min(dp[i], dp[i - moneda] + 1) para cada moneda válida.',
 'dp[i - c] + 1', 'dp[i - c] + 1',
 100, 10, now()),

-- 95. objects
(gen_random_uuid(),
 'Metaclass', 'Metaclase',
 'Create a metaclass SingletonMeta that ensures only one instance of a class is created. Verify with two instantiations.',
 'Crea una metaclase SingletonMeta que garantice que solo se cree una instancia de una clase. Verifica con dos instanciaciones.',
 'python', 5, 'objects',
 'class SingletonMeta(type):\n    _instances = {}\n    def __call__(cls, *args, **kwargs):\n        if cls not in cls._instances:\n            cls._instances[cls] = super().__call__(*args, **kwargs)\n        return cls.___[cls]\n\nclass DB(metaclass=SingletonMeta):\n    pass\n\na = DB()\nb = DB()\nprint(a is b)',
 'class SingletonMeta(type):\n    _instances = {}\n    def __call__(cls, *args, **kwargs):\n        if cls not in cls._instances:\n            cls._instances[cls] = super().__call__(*args, **kwargs)\n        return cls._instances[cls]\n\nclass DB(metaclass=SingletonMeta):\n    pass\n\na = DB()\nb = DB()\nprint(a is b)',
 'True',
 3,
 'A metaclass controls class creation and instantiation.', 'Una metaclase controla la creación e instanciación de clases.',
 'Return the cached instance: cls._instances[cls].', 'Devuelve la instancia en caché: cls._instances[cls].',
 'cls._instances[cls]', 'cls._instances[cls]',
 100, 10, now()),

-- 96. algorithms
(gen_random_uuid(),
 'Word Ladder Length', 'Longitud de Escalera de Palabras',
 'Find shortest transformation steps from "hit" to "cog" using ["hot","dot","dog","lot","log","cog"]. Print steps.',
 'Encuentra los pasos mínimos de transformación de "hit" a "cog" usando ["hot","dot","dog","lot","log","cog"]. Imprime pasos.',
 'python', 5, 'algorithms',
 'from collections import deque\ndef word_ladder(begin, end, word_list):\n    word_set = set(word_list)\n    q = deque([(begin, 1)])\n    while q:\n        word, steps = q.popleft()\n        for i in range(len(word)):\n            for c in "abcdefghijklmnopqrstuvwxyz":\n                new_word = word[:i] + c + word[i+1:]\n                if new_word == end:\n                    return steps + ___\n                if new_word in word_set:\n                    word_set.remove(new_word)\n                    q.append((new_word, steps + 1))\n    return 0\nprint(word_ladder("hit","cog",["hot","dot","dog","lot","log","cog"]))',
 'from collections import deque\ndef word_ladder(begin, end, word_list):\n    word_set = set(word_list)\n    q = deque([(begin, 1)])\n    while q:\n        word, steps = q.popleft()\n        for i in range(len(word)):\n            for c in "abcdefghijklmnopqrstuvwxyz":\n                new_word = word[:i] + c + word[i+1:]\n                if new_word == end:\n                    return steps + 1\n                if new_word in word_set:\n                    word_set.remove(new_word)\n                    q.append((new_word, steps + 1))\n    return 0\nprint(word_ladder("hit","cog",["hot","dot","dog","lot","log","cog"]))',
 '5',
 3,
 'Use BFS to find the shortest path; change one letter at a time.', 'Usa BFS para encontrar el camino más corto; cambia una letra a la vez.',
 'When new_word == end, return steps + 1 (count the final step).', 'Cuando new_word == end, devuelve steps + 1 (cuenta el paso final).',
 'return steps + 1', 'return steps + 1',
 100, 10, now()),

-- 97. data_structures
(gen_random_uuid(),
 'Min Heap Operations', 'Operaciones con Min Heap',
 'Use heapq to push 5,3,8,1,9 onto a heap then pop the 3 smallest. Print them.',
 'Usa heapq para agregar 5,3,8,1,9 a un heap y luego extraer los 3 menores. Imprímelos.',
 'python', 5, 'data_structures',
 'import heapq\nheap = []\nfor n in [5, 3, 8, 1, 9]:\n    heapq.___(heap, n)\nfor _ in range(3):\n    print(heapq.___(heap))',
 'import heapq\nheap = []\nfor n in [5, 3, 8, 1, 9]:\n    heapq.heappush(heap, n)\nfor _ in range(3):\n    print(heapq.heappop(heap))',
 '1\n3\n5',
 3,
 'heapq provides a min-heap implementation.', 'heapq proporciona una implementación de min-heap.',
 'Use heapq.heappush() to add and heapq.heappop() to remove the minimum.', 'Usa heapq.heappush() para agregar y heapq.heappop() para eliminar el mínimo.',
 'heapq.heappush / heapq.heappop', 'heapq.heappush / heapq.heappop',
 100, 10, now()),

-- 98. functions
(gen_random_uuid(),
 'Async Coroutine', 'Corrutina Asíncrona',
 'Write an async function fetch(url) that returns "data from {url}". Run it with asyncio for "http://api.example.com".',
 'Escribe una función async fetch(url) que devuelva "data from {url}". Ejecútala con asyncio para "http://api.example.com".',
 'python', 5, 'functions',
 'import asyncio\n\nasync def fetch(url):\n    return f"data from {___}"\n\nresult = asyncio.run(fetch("http://api.example.com"))\nprint(result)',
 'import asyncio\n\nasync def fetch(url):\n    return f"data from {url}"\n\nresult = asyncio.run(fetch("http://api.example.com"))\nprint(result)',
 'data from http://api.example.com',
 3,
 'async functions are defined with the async keyword and return coroutines.', 'Las funciones async se definen con la palabra clave async y devuelven corrutinas.',
 'Use the url parameter inside the f-string: f"data from {url}".', 'Usa el parámetro url dentro del f-string: f"data from {url}".',
 'f"data from {url}"', 'f"data from {url}"',
 100, 10, now()),

-- 99. patterns
(gen_random_uuid(),
 'Observer Pattern', 'Patrón Observador',
 'Implement the Observer pattern: EventEmitter with subscribe/emit. Subscribe a listener that prints the event. Emit "click".',
 'Implementa el patrón Observador: EventEmitter con subscribe/emit. Suscribe un listener que imprima el evento. Emite "click".',
 'python', 5, 'patterns',
 'class EventEmitter:\n    def __init__(self):\n        self._listeners = []\n    def subscribe(self, fn):\n        self._listeners.___(fn)\n    def emit(self, event):\n        for fn in self._listeners:\n            fn(___)\n\nem = EventEmitter()\nem.subscribe(lambda e: print(f"event: {e}"))\nem.emit("click")',
 'class EventEmitter:\n    def __init__(self):\n        self._listeners = []\n    def subscribe(self, fn):\n        self._listeners.append(fn)\n    def emit(self, event):\n        for fn in self._listeners:\n            fn(event)\n\nem = EventEmitter()\nem.subscribe(lambda e: print(f"event: {e}"))\nem.emit("click")',
 'event: click',
 3,
 'The Observer pattern decouples event producers from consumers.', 'El patrón Observador desacopla los productores de eventos de los consumidores.',
 'append the listener in subscribe; call fn(event) in emit.', 'agrega el listener en subscribe; llama fn(event) en emit.',
 'self._listeners.append(fn) / fn(event)', 'self._listeners.append(fn) / fn(event)',
 100, 10, now()),

-- 100. challenges
(gen_random_uuid(),
 'Mini Interpreter', 'Mini Intérprete',
 'Write eval_expr(s) that evaluates a string like "3 + 5 * 2 - 4" using Python eval safely. Print the result.',
 'Escribe eval_expr(s) que evalúe una cadena como "3 + 5 * 2 - 4" usando eval de Python de forma segura. Imprime el resultado.',
 'python', 5, 'challenges',
 'def eval_expr(s):\n    allowed = set("0123456789 +-*/()")\n    if any(c not in allowed for c in s):\n        raise ValueError("Invalid expression")\n    return ___(s)\n\nprint(eval_expr("3 + 5 * 2 - 4"))',
 'def eval_expr(s):\n    allowed = set("0123456789 +-*/()")\n    if any(c not in allowed for c in s):\n        raise ValueError("Invalid expression")\n    return eval(s)\n\nprint(eval_expr("3 + 5 * 2 - 4"))',
 '9',
 3,
 'Python''s eval() executes a string as Python code.', 'El eval() de Python ejecuta una cadena como código Python.',
 'Whitelist the allowed characters first, then call eval(s).', 'Primero crea una lista blanca de caracteres permitidos, luego llama eval(s).',
 'return eval(s)', 'return eval(s)',
 100, 10, now())

ON CONFLICT DO NOTHING;

COMMIT;
