-- 049_exercises_cpp.sql
-- 100 C++ programming exercises, bilingual EN+ES
-- Distribution: diff1:25, diff2:25, diff3:25, diff4:15, diff5:10

BEGIN;

INSERT INTO exercises (
  id, title_en, title_es, description_en, description_es,
  language, difficulty, category,
  starter_code, expected_output,
  hint_count, hint_1_en, hint_1_es, hint_2_en, hint_2_es, hint_3_en, hint_3_es,
  points, hints_used_penalty, created_at
) VALUES

-- ============================================================
-- DIFFICULTY 1 — 25 exercises (points: 10, penalty: 3)
-- ============================================================

(gen_random_uuid(),
 'Hello World', 'Hola Mundo',
 'Write a C++ program that prints "Hello, World!" to the console.',
 'Escribe un programa en C++ que imprima "Hello, World!" en la consola.',
 'cpp', 1, 'basics',
 '#include <iostream>\nusing namespace std;\n\nint main() {\n    // your code\n    return 0;\n}',
 'Hello, World!',
 3,
 'Use cout to print output in C++.', 'Usa cout para imprimir en C++.',
 'The << operator sends data to cout.', 'El operador << envía datos a cout.',
 'cout << "Hello, World!" << endl;', 'cout << "Hello, World!" << endl;',
 10, 3, now()),

(gen_random_uuid(),
 'Print Your Name', 'Imprimir Tu Nombre',
 'Declare a string variable with your name and print it.',
 'Declara una variable string con tu nombre e imprímela.',
 'cpp', 1, 'basics',
 '#include <iostream>\nusing namespace std;\n\nint main() {\n    // your code\n    return 0;\n}',
 'Alice',
 3,
 'Include <string> or use the string type from <iostream>.', 'Incluye <string> o usa el tipo string de <iostream>.',
 'Declare: string name = "Alice";', 'Declara: string name = "Alice";',
 'cout << name << endl;', 'cout << name << endl;',
 10, 3, now()),

(gen_random_uuid(),
 'Integer Addition', 'Suma de Enteros',
 'Declare two integer variables, assign them values 7 and 3, print their sum.',
 'Declara dos variables enteras, asígnales los valores 7 y 3, imprime su suma.',
 'cpp', 1, 'math',
 '#include <iostream>\nusing namespace std;\n\nint main() {\n    // your code\n    return 0;\n}',
 '10',
 3,
 'Use the int type to declare integer variables.', 'Usa el tipo int para declarar variables enteras.',
 'Use the + operator to add two numbers.', 'Usa el operador + para sumar dos números.',
 'cout << a + b << endl;', 'cout << a + b << endl;',
 10, 3, now()),

(gen_random_uuid(),
 'Multiply Two Numbers', 'Multiplicar Dos Números',
 'Declare two integers with values 4 and 5, then print their product.',
 'Declara dos enteros con valores 4 y 5, luego imprime su producto.',
 'cpp', 1, 'math',
 '#include <iostream>\nusing namespace std;\n\nint main() {\n    // your code\n    return 0;\n}',
 '20',
 3,
 'Use the * operator for multiplication.', 'Usa el operador * para la multiplicación.',
 'Store the result in a third variable or print directly.', 'Guarda el resultado en una tercera variable o imprímelo directamente.',
 'cout << a * b << endl;', 'cout << a * b << endl;',
 10, 3, now()),

(gen_random_uuid(),
 'Float Division', 'División de Flotantes',
 'Divide 7.0 by 2.0 and print the result as a float.',
 'Divide 7.0 entre 2.0 e imprime el resultado como flotante.',
 'cpp', 1, 'math',
 '#include <iostream>\nusing namespace std;\n\nint main() {\n    // your code\n    return 0;\n}',
 '3.5',
 3,
 'Use float or double to hold decimal values.', 'Usa float o double para almacenar valores decimales.',
 'Assigning 7.0 instead of 7 ensures floating-point division.', 'Asignar 7.0 en lugar de 7 asegura la división en punto flotante.',
 'cout << 7.0 / 2.0 << endl;', 'cout << 7.0 / 2.0 << endl;',
 10, 3, now()),

(gen_random_uuid(),
 'Boolean Variable', 'Variable Booleana',
 'Declare a bool variable set to true and print it.',
 'Declara una variable bool con valor true e imprímela.',
 'cpp', 1, 'basics',
 '#include <iostream>\nusing namespace std;\n\nint main() {\n    // your code\n    return 0;\n}',
 '1',
 3,
 'Use the bool type. True prints as 1 by default.', 'Usa el tipo bool. True se imprime como 1 por defecto.',
 'bool flag = true;', 'bool flag = true;',
 'cout << flag << endl;', 'cout << flag << endl;',
 10, 3, now()),

(gen_random_uuid(),
 'Character Variable', 'Variable de Carácter',
 'Declare a char variable with the value ''A'' and print it.',
 'Declara una variable char con el valor ''A'' e imprímela.',
 'cpp', 1, 'basics',
 '#include <iostream>\nusing namespace std;\n\nint main() {\n    // your code\n    return 0;\n}',
 'A',
 3,
 'Use single quotes for char literals: ''A''.', 'Usa comillas simples para literales char: ''A''.',
 'char c = ''A'';', 'char c = ''A'';',
 'cout << c << endl;', 'cout << c << endl;',
 10, 3, now()),

(gen_random_uuid(),
 'if-else Statement', 'Sentencia if-else',
 'Write a program that checks if 10 is greater than 5. Print "Yes" if true, "No" if false.',
 'Escribe un programa que compruebe si 10 es mayor que 5. Imprime "Yes" si es verdadero, "No" si es falso.',
 'cpp', 1, 'basics',
 '#include <iostream>\nusing namespace std;\n\nint main() {\n    // your code\n    return 0;\n}',
 'Yes',
 3,
 'Use an if statement with a condition in parentheses.', 'Usa una sentencia if con una condición entre paréntesis.',
 'if (10 > 5) prints the true branch.', 'if (10 > 5) imprime la rama verdadera.',
 'if (10 > 5) { cout << "Yes"; } else { cout << "No"; }', 'if (10 > 5) { cout << "Yes"; } else { cout << "No"; }',
 10, 3, now()),

(gen_random_uuid(),
 'for Loop', 'Bucle for',
 'Use a for loop to print numbers 1 through 5, each on a new line.',
 'Usa un bucle for para imprimir los números del 1 al 5, cada uno en una línea nueva.',
 'cpp', 1, 'basics',
 '#include <iostream>\nusing namespace std;\n\nint main() {\n    // your code\n    return 0;\n}',
 '1\n2\n3\n4\n5',
 3,
 'A for loop has init; condition; increment.', 'Un bucle for tiene inicio; condición; incremento.',
 'for (int i = 1; i <= 5; i++)', 'for (int i = 1; i <= 5; i++)',
 'cout << i << endl; inside the loop body.', 'cout << i << endl; dentro del cuerpo del bucle.',
 10, 3, now()),

(gen_random_uuid(),
 'while Loop', 'Bucle while',
 'Use a while loop to print numbers 1 through 3.',
 'Usa un bucle while para imprimir los números del 1 al 3.',
 'cpp', 1, 'basics',
 '#include <iostream>\nusing namespace std;\n\nint main() {\n    // your code\n    return 0;\n}',
 '1\n2\n3',
 3,
 'Initialize a counter before the while loop.', 'Inicializa un contador antes del bucle while.',
 'The condition is checked before each iteration.', 'La condición se verifica antes de cada iteración.',
 'int i = 1; while (i <= 3) { cout << i << endl; i++; }', 'int i = 1; while (i <= 3) { cout << i << endl; i++; }',
 10, 3, now()),

(gen_random_uuid(),
 'String Length', 'Longitud de Cadena',
 'Declare a string "Hello" and print its length.',
 'Declara la cadena "Hello" e imprime su longitud.',
 'cpp', 1, 'strings',
 '#include <iostream>\n#include <string>\nusing namespace std;\n\nint main() {\n    // your code\n    return 0;\n}',
 '5',
 3,
 'The string class has a .length() method.', 'La clase string tiene un método .length().',
 'string s = "Hello"; then call s.length().', 'string s = "Hello"; luego llama a s.length().',
 'cout << s.length() << endl;', 'cout << s.length() << endl;',
 10, 3, now()),

(gen_random_uuid(),
 'Array Declaration', 'Declaración de Arreglo',
 'Declare an integer array of 3 elements {1, 2, 3} and print the second element.',
 'Declara un arreglo entero de 3 elementos {1, 2, 3} e imprime el segundo elemento.',
 'cpp', 1, 'arrays',
 '#include <iostream>\nusing namespace std;\n\nint main() {\n    // your code\n    return 0;\n}',
 '2',
 3,
 'Arrays in C++ are zero-indexed.', 'Los arreglos en C++ están indexados desde cero.',
 'int arr[] = {1, 2, 3};', 'int arr[] = {1, 2, 3};',
 'The second element is at index 1: arr[1].', 'El segundo elemento está en el índice 1: arr[1].',
 10, 3, now()),

(gen_random_uuid(),
 'Modulo Operator', 'Operador Módulo',
 'Print the remainder when 17 is divided by 5.',
 'Imprime el residuo cuando 17 se divide entre 5.',
 'cpp', 1, 'math',
 '#include <iostream>\nusing namespace std;\n\nint main() {\n    // your code\n    return 0;\n}',
 '2',
 3,
 'The % operator gives the remainder.', 'El operador % da el residuo.',
 '17 % 5 equals 2.', '17 % 5 es igual a 2.',
 'cout << 17 % 5 << endl;', 'cout << 17 % 5 << endl;',
 10, 3, now()),

(gen_random_uuid(),
 'Increment Operator', 'Operador de Incremento',
 'Declare an integer x = 5, increment it by 1, and print the result.',
 'Declara un entero x = 5, increméntalo en 1 e imprime el resultado.',
 'cpp', 1, 'basics',
 '#include <iostream>\nusing namespace std;\n\nint main() {\n    // your code\n    return 0;\n}',
 '6',
 3,
 'Use the ++ operator to increment.', 'Usa el operador ++ para incrementar.',
 'x++ increments x by 1.', 'x++ incrementa x en 1.',
 'int x = 5; x++; cout << x << endl;', 'int x = 5; x++; cout << x << endl;',
 10, 3, now()),

(gen_random_uuid(),
 'String Concatenation', 'Concatenación de Cadenas',
 'Concatenate "Hello, " and "World!" and print the result.',
 'Concatena "Hello, " y "World!" e imprime el resultado.',
 'cpp', 1, 'strings',
 '#include <iostream>\n#include <string>\nusing namespace std;\n\nint main() {\n    // your code\n    return 0;\n}',
 'Hello, World!',
 3,
 'Use the + operator to join two strings.', 'Usa el operador + para unir dos cadenas.',
 'string a = "Hello, "; string b = "World!";', 'string a = "Hello, "; string b = "World!";',
 'cout << a + b << endl;', 'cout << a + b << endl;',
 10, 3, now()),

(gen_random_uuid(),
 'Swap Two Variables', 'Intercambiar Dos Variables',
 'Swap the values of two integers a=3 and b=7, then print a and b.',
 'Intercambia los valores de dos enteros a=3 y b=7, luego imprime a y b.',
 'cpp', 1, 'basics',
 '#include <iostream>\nusing namespace std;\n\nint main() {\n    // your code\n    return 0;\n}',
 '7\n3',
 3,
 'Use a temporary variable to hold one value during the swap.', 'Usa una variable temporal para mantener un valor durante el intercambio.',
 'int temp = a; a = b; b = temp;', 'int temp = a; a = b; b = temp;',
 'cout << a << endl << b << endl;', 'cout << a << endl << b << endl;',
 10, 3, now()),

(gen_random_uuid(),
 'Even or Odd', 'Par o Impar',
 'Check if the number 8 is even or odd. Print "Even" or "Odd".',
 'Comprueba si el número 8 es par o impar. Imprime "Even" u "Odd".',
 'cpp', 1, 'math',
 '#include <iostream>\nusing namespace std;\n\nint main() {\n    // your code\n    return 0;\n}',
 'Even',
 3,
 'Use the modulo operator %.', 'Usa el operador módulo %.',
 'A number is even if n % 2 == 0.', 'Un número es par si n % 2 == 0.',
 'if (8 % 2 == 0) cout << "Even"; else cout << "Odd";', 'if (8 % 2 == 0) cout << "Even"; else cout << "Odd";',
 10, 3, now()),

(gen_random_uuid(),
 'Absolute Value', 'Valor Absoluto',
 'Print the absolute value of -15 using the abs() function.',
 'Imprime el valor absoluto de -15 usando la función abs().',
 'cpp', 1, 'math',
 '#include <iostream>\n#include <cmath>\nusing namespace std;\n\nint main() {\n    // your code\n    return 0;\n}',
 '15',
 3,
 'Include <cmath> for math functions.', 'Incluye <cmath> para funciones matemáticas.',
 'abs() returns the absolute value.', 'abs() retorna el valor absoluto.',
 'cout << abs(-15) << endl;', 'cout << abs(-15) << endl;',
 10, 3, now()),

(gen_random_uuid(),
 'Max of Two Numbers', 'Máximo de Dos Números',
 'Print the larger of two numbers: 12 and 9.',
 'Imprime el mayor de dos números: 12 y 9.',
 'cpp', 1, 'math',
 '#include <iostream>\n#include <algorithm>\nusing namespace std;\n\nint main() {\n    // your code\n    return 0;\n}',
 '12',
 3,
 'Include <algorithm> for std::max.', 'Incluye <algorithm> para std::max.',
 'max(a, b) returns the larger value.', 'max(a, b) retorna el valor mayor.',
 'cout << max(12, 9) << endl;', 'cout << max(12, 9) << endl;',
 10, 3, now()),

(gen_random_uuid(),
 'Print Star Pattern', 'Imprimir Patrón de Estrellas',
 'Print a row of 5 asterisks: *****',
 'Imprime una fila de 5 asteriscos: *****',
 'cpp', 1, 'patterns',
 '#include <iostream>\nusing namespace std;\n\nint main() {\n    // your code\n    return 0;\n}',
 '*****',
 3,
 'Use a loop that runs 5 times.', 'Usa un bucle que se ejecute 5 veces.',
 'Print * without endl inside the loop, then endl after.', 'Imprime * sin endl dentro del bucle, luego endl después.',
 'for (int i=0;i<5;i++) cout<<"*"; cout<<endl;', 'for (int i=0;i<5;i++) cout<<"*"; cout<<endl;',
 10, 3, now()),

(gen_random_uuid(),
 'Type Casting', 'Conversión de Tipo',
 'Cast the integer 7 to a double and divide by 2. Print the result.',
 'Convierte el entero 7 a double y divídelo entre 2. Imprime el resultado.',
 'cpp', 1, 'basics',
 '#include <iostream>\nusing namespace std;\n\nint main() {\n    // your code\n    return 0;\n}',
 '3.5',
 3,
 'Use (double) to cast an integer to double.', 'Usa (double) para convertir un entero a double.',
 '(double)7 / 2 performs floating-point division.', '(double)7 / 2 realiza división en punto flotante.',
 'cout << (double)7 / 2 << endl;', 'cout << (double)7 / 2 << endl;',
 10, 3, now()),

(gen_random_uuid(),
 'Nested if', 'if Anidado',
 'Given x=15, print "Big" if x>10, "Medium" if x>5, else "Small".',
 'Dado x=15, imprime "Big" si x>10, "Medium" si x>5, o "Small" en caso contrario.',
 'cpp', 1, 'basics',
 '#include <iostream>\nusing namespace std;\n\nint main() {\n    // your code\n    return 0;\n}',
 'Big',
 3,
 'Use if / else if / else for multiple conditions.', 'Usa if / else if / else para múltiples condiciones.',
 'Check the largest condition first.', 'Verifica la condición más grande primero.',
 'if (x>10) cout<<"Big"; else if (x>5) cout<<"Medium"; else cout<<"Small";', 'if (x>10) cout<<"Big"; else if (x>5) cout<<"Medium"; else cout<<"Small";',
 10, 3, now()),

(gen_random_uuid(),
 'Sum Array Elements', 'Sumar Elementos de Arreglo',
 'Declare int arr[] = {2, 4, 6, 8}. Print the sum of all elements.',
 'Declara int arr[] = {2, 4, 6, 8}. Imprime la suma de todos los elementos.',
 'cpp', 1, 'arrays',
 '#include <iostream>\nusing namespace std;\n\nint main() {\n    // your code\n    return 0;\n}',
 '20',
 3,
 'Use a loop to iterate through the array.', 'Usa un bucle para iterar por el arreglo.',
 'Accumulate the sum in a variable initialized to 0.', 'Acumula la suma en una variable inicializada en 0.',
 'int sum=0; for (int i=0;i<4;i++) sum+=arr[i]; cout<<sum;', 'int sum=0; for (int i=0;i<4;i++) sum+=arr[i]; cout<<sum;',
 10, 3, now()),

(gen_random_uuid(),
 'String Comparison', 'Comparación de Cadenas',
 'Compare strings "apple" and "apple". Print "Equal" if they match.',
 'Compara las cadenas "apple" y "apple". Imprime "Equal" si coinciden.',
 'cpp', 1, 'strings',
 '#include <iostream>\n#include <string>\nusing namespace std;\n\nint main() {\n    // your code\n    return 0;\n}',
 'Equal',
 3,
 'Use == to compare two std::string objects.', 'Usa == para comparar dos objetos std::string.',
 'string a = "apple"; string b = "apple";', 'string a = "apple"; string b = "apple";',
 'if (a == b) cout << "Equal";', 'if (a == b) cout << "Equal";',
 10, 3, now()),

(gen_random_uuid(),
 'Power of 2', 'Potencia de 2',
 'Print 2 raised to the power 8 using pow().',
 'Imprime 2 elevado a la potencia 8 usando pow().',
 'cpp', 1, 'math',
 '#include <iostream>\n#include <cmath>\nusing namespace std;\n\nint main() {\n    // your code\n    return 0;\n}',
 '256',
 3,
 'Include <cmath> for the pow function.', 'Incluye <cmath> para la función pow.',
 'pow(base, exponent) returns base^exponent.', 'pow(base, exponent) retorna base^exponent.',
 'cout << (int)pow(2, 8) << endl;', 'cout << (int)pow(2, 8) << endl;',
 10, 3, now()),

-- ============================================================
-- DIFFICULTY 2 — 25 exercises (points: 20, penalty: 3)
-- ============================================================

(gen_random_uuid(),
 'Function: Add Two Numbers', 'Función: Sumar Dos Números',
 'Write a function add(int a, int b) that returns their sum. Call it with 4 and 6 and print the result.',
 'Escribe una función add(int a, int b) que retorne su suma. Llámala con 4 y 6 e imprime el resultado.',
 'cpp', 2, 'functions',
 '#include <iostream>\nusing namespace std;\n\n// write your function here\n\nint main() {\n    // your code\n    return 0;\n}',
 '10',
 3,
 'Define the function before main().', 'Define la función antes de main().',
 'int add(int a, int b) { return a + b; }', 'int add(int a, int b) { return a + b; }',
 'cout << add(4, 6) << endl;', 'cout << add(4, 6) << endl;',
 20, 3, now()),

(gen_random_uuid(),
 'Function: Factorial', 'Función: Factorial',
 'Write a function factorial(int n) that returns n!. Print factorial(5).',
 'Escribe una función factorial(int n) que retorne n!. Imprime factorial(5).',
 'cpp', 2, 'functions',
 '#include <iostream>\nusing namespace std;\n\n// write your function here\n\nint main() {\n    // your code\n    return 0;\n}',
 '120',
 3,
 'Use a loop or recursion to compute the factorial.', 'Usa un bucle o recursión para calcular el factorial.',
 'Multiply all integers from 1 to n.', 'Multiplica todos los enteros del 1 al n.',
 'int result=1; for(int i=1;i<=n;i++) result*=i;', 'int result=1; for(int i=1;i<=n;i++) result*=i;',
 20, 3, now()),

(gen_random_uuid(),
 'Reverse a String', 'Invertir una Cadena',
 'Reverse the string "hello" and print it.',
 'Invierte la cadena "hello" e imprímela.',
 'cpp', 2, 'strings',
 '#include <iostream>\n#include <string>\n#include <algorithm>\nusing namespace std;\n\nint main() {\n    // your code\n    return 0;\n}',
 'olleh',
 3,
 'Include <algorithm> for std::reverse.', 'Incluye <algorithm> para std::reverse.',
 'reverse() works on iterators: s.begin(), s.end().', 'reverse() trabaja con iteradores: s.begin(), s.end().',
 'string s="hello"; reverse(s.begin(),s.end()); cout<<s;', 'string s="hello"; reverse(s.begin(),s.end()); cout<<s;',
 20, 3, now()),

(gen_random_uuid(),
 'Count Vowels', 'Contar Vocales',
 'Count and print the number of vowels in the string "programming".',
 'Cuenta e imprime el número de vocales en la cadena "programming".',
 'cpp', 2, 'strings',
 '#include <iostream>\n#include <string>\nusing namespace std;\n\nint main() {\n    // your code\n    return 0;\n}',
 '3',
 3,
 'Iterate through each character with a for loop.', 'Itera por cada carácter con un bucle for.',
 'Check if each char is in "aeiou".', 'Verifica si cada carácter está en "aeiou".',
 'if (c==''a''||c==''e''||c==''i''||c==''o''||c==''u'') count++;', 'if (c==''a''||c==''e''||c==''i''||c==''o''||c==''u'') count++;',
 20, 3, now()),

(gen_random_uuid(),
 'Find Max in Array', 'Encontrar Máximo en Arreglo',
 'Find and print the maximum value in int arr[] = {3, 7, 1, 9, 4}.',
 'Encuentra e imprime el valor máximo en int arr[] = {3, 7, 1, 9, 4}.',
 'cpp', 2, 'arrays',
 '#include <iostream>\nusing namespace std;\n\nint main() {\n    // your code\n    return 0;\n}',
 '9',
 3,
 'Initialize max with the first array element.', 'Inicializa max con el primer elemento del arreglo.',
 'Loop through and update max when a larger value is found.', 'Itera y actualiza max cuando encuentres un valor mayor.',
 'int mx=arr[0]; for(int i=1;i<5;i++) if(arr[i]>mx) mx=arr[i];', 'int mx=arr[0]; for(int i=1;i<5;i++) if(arr[i]>mx) mx=arr[i];',
 20, 3, now()),

(gen_random_uuid(),
 'FizzBuzz', 'FizzBuzz',
 'Print numbers 1 to 15. Print "Fizz" for multiples of 3, "Buzz" for multiples of 5, "FizzBuzz" for both.',
 'Imprime números del 1 al 15. Imprime "Fizz" para múltiplos de 3, "Buzz" para múltiplos de 5, "FizzBuzz" para ambos.',
 'cpp', 2, 'basics',
 '#include <iostream>\nusing namespace std;\n\nint main() {\n    // your code\n    return 0;\n}',
 '1\n2\nFizz\n4\nBuzz\nFizz\n7\n8\nFizz\nBuzz\n11\nFizz\n13\n14\nFizzBuzz',
 3,
 'Check divisibility with the % operator.', 'Verifica la divisibilidad con el operador %.',
 'Check FizzBuzz condition (% 15) first to avoid shadowing.', 'Verifica la condición FizzBuzz (% 15) primero para evitar solapamiento.',
 'if(i%15==0) else if(i%3==0) else if(i%5==0) else cout<<i;', 'if(i%15==0) else if(i%3==0) else if(i%5==0) else cout<<i;',
 20, 3, now()),

(gen_random_uuid(),
 'Fibonacci Sequence', 'Secuencia de Fibonacci',
 'Print the first 8 Fibonacci numbers separated by spaces.',
 'Imprime los primeros 8 números de Fibonacci separados por espacios.',
 'cpp', 2, 'math',
 '#include <iostream>\nusing namespace std;\n\nint main() {\n    // your code\n    return 0;\n}',
 '0 1 1 2 3 5 8 13',
 3,
 'Each Fibonacci number is the sum of the previous two.', 'Cada número de Fibonacci es la suma de los dos anteriores.',
 'Start with a=0, b=1 and iterate.', 'Comienza con a=0, b=1 e itera.',
 'int a=0,b=1,c; print a,b then c=a+b; a=b; b=c;', 'int a=0,b=1,c; imprime a,b luego c=a+b; a=b; b=c;',
 20, 3, now()),

(gen_random_uuid(),
 'Uppercase String', 'Cadena en Mayúsculas',
 'Convert the string "hello world" to uppercase and print it.',
 'Convierte la cadena "hello world" a mayúsculas e imprímela.',
 'cpp', 2, 'strings',
 '#include <iostream>\n#include <string>\n#include <algorithm>\nusing namespace std;\n\nint main() {\n    // your code\n    return 0;\n}',
 'HELLO WORLD',
 3,
 'Use transform() with toupper.', 'Usa transform() con toupper.',
 'transform(s.begin(), s.end(), s.begin(), ::toupper);', 'transform(s.begin(), s.end(), s.begin(), ::toupper);',
 'cout << s << endl;', 'cout << s << endl;',
 20, 3, now()),

(gen_random_uuid(),
 'Linear Search', 'Búsqueda Lineal',
 'Search for value 7 in int arr[] = {3, 5, 7, 9, 1}. Print its index.',
 'Busca el valor 7 en int arr[] = {3, 5, 7, 9, 1}. Imprime su índice.',
 'cpp', 2, 'arrays',
 '#include <iostream>\nusing namespace std;\n\nint main() {\n    // your code\n    return 0;\n}',
 '2',
 3,
 'Iterate through the array and compare each element.', 'Itera por el arreglo y compara cada elemento.',
 'When arr[i] == target, print i.', 'Cuando arr[i] == target, imprime i.',
 'for(int i=0;i<5;i++) if(arr[i]==7) cout<<i;', 'for(int i=0;i<5;i++) if(arr[i]==7) cout<<i;',
 20, 3, now()),

(gen_random_uuid(),
 '2D Array Diagonal', 'Diagonal de Arreglo 2D',
 'Declare a 3x3 matrix and print its main diagonal elements {1,5,9}.',
 'Declara una matriz 3x3 e imprime sus elementos de la diagonal principal {1,5,9}.',
 'cpp', 2, 'arrays',
 '#include <iostream>\nusing namespace std;\n\nint main() {\n    int m[3][3]={{1,2,3},{4,5,6},{7,8,9}};\n    // print diagonal\n    return 0;\n}',
 '1\n5\n9',
 3,
 'The main diagonal has row index == column index.', 'La diagonal principal tiene índice de fila == índice de columna.',
 'Loop i from 0 to 2 and print m[i][i].', 'Itera i de 0 a 2 e imprime m[i][i].',
 'for(int i=0;i<3;i++) cout<<m[i][i]<<endl;', 'for(int i=0;i<3;i++) cout<<m[i][i]<<endl;',
 20, 3, now()),

(gen_random_uuid(),
 'Switch Statement', 'Sentencia Switch',
 'Use a switch on integer day=3. Print the day name (1=Mon ... 7=Sun).',
 'Usa un switch sobre el entero day=3. Imprime el nombre del día (1=Lun ... 7=Dom).',
 'cpp', 2, 'basics',
 '#include <iostream>\nusing namespace std;\n\nint main() {\n    int day = 3;\n    // your code\n    return 0;\n}',
 'Wednesday',
 3,
 'Use switch(day) with case labels.', 'Usa switch(day) con etiquetas case.',
 'Each case needs a break statement.', 'Cada case necesita una sentencia break.',
 'case 3: cout<<"Wednesday"; break;', 'case 3: cout<<"Wednesday"; break;',
 20, 3, now()),

(gen_random_uuid(),
 'Pointer Basics', 'Fundamentos de Punteros',
 'Declare int x = 42. Create a pointer to x and print the value through the pointer.',
 'Declara int x = 42. Crea un puntero a x e imprime el valor a través del puntero.',
 'cpp', 2, 'basics',
 '#include <iostream>\nusing namespace std;\n\nint main() {\n    // your code\n    return 0;\n}',
 '42',
 3,
 'A pointer stores the address of a variable.', 'Un puntero almacena la dirección de una variable.',
 'int* ptr = &x; declares a pointer to x.', 'int* ptr = &x; declara un puntero a x.',
 'cout << *ptr << endl; dereferences the pointer.', 'cout << *ptr << endl; desreferencia el puntero.',
 20, 3, now()),

(gen_random_uuid(),
 'Reference Parameter', 'Parámetro de Referencia',
 'Write a function doubleIt(int& n) that doubles n in-place. Call it with x=5 and print x.',
 'Escribe una función doubleIt(int& n) que duplique n en su lugar. Llámala con x=5 e imprime x.',
 'cpp', 2, 'functions',
 '#include <iostream>\nusing namespace std;\n\n// write your function here\n\nint main() {\n    // your code\n    return 0;\n}',
 '10',
 3,
 'Use & in the parameter to pass by reference.', 'Usa & en el parámetro para pasar por referencia.',
 'void doubleIt(int& n) { n *= 2; }', 'void doubleIt(int& n) { n *= 2; }',
 'int x=5; doubleIt(x); cout<<x;', 'int x=5; doubleIt(x); cout<<x;',
 20, 3, now()),

(gen_random_uuid(),
 'String Substring', 'Subcadena',
 'Extract and print the substring "World" from "Hello, World!".',
 'Extrae e imprime la subcadena "World" de "Hello, World!".',
 'cpp', 2, 'strings',
 '#include <iostream>\n#include <string>\nusing namespace std;\n\nint main() {\n    // your code\n    return 0;\n}',
 'World',
 3,
 'Use the substr() method of std::string.', 'Usa el método substr() de std::string.',
 'substr(start, length) extracts a portion.', 'substr(inicio, longitud) extrae una porción.',
 '"Hello, World!".substr(7, 5) gives "World".', '"Hello, World!".substr(7, 5) da "World".',
 20, 3, now()),

(gen_random_uuid(),
 'Count Array Elements > N', 'Contar Elementos > N',
 'Count and print how many elements in {5, 3, 8, 1, 9, 2} are greater than 4.',
 'Cuenta e imprime cuántos elementos en {5, 3, 8, 1, 9, 2} son mayores que 4.',
 'cpp', 2, 'arrays',
 '#include <iostream>\nusing namespace std;\n\nint main() {\n    // your code\n    return 0;\n}',
 '3',
 3,
 'Use a loop to check each element.', 'Usa un bucle para verificar cada elemento.',
 'Maintain a counter and increment when arr[i] > 4.', 'Mantén un contador e increméntalo cuando arr[i] > 4.',
 'int count=0; for each element if(arr[i]>4) count++;', 'int count=0; para cada elemento if(arr[i]>4) count++;',
 20, 3, now()),

(gen_random_uuid(),
 'Triangle Pattern', 'Patrón Triángulo',
 'Print a right triangle of stars with 4 rows.',
 'Imprime un triángulo rectángulo de estrellas con 4 filas.',
 'cpp', 2, 'patterns',
 '#include <iostream>\nusing namespace std;\n\nint main() {\n    // your code\n    return 0;\n}',
 '*\n**\n***\n****',
 3,
 'Use nested loops: outer for rows, inner for stars.', 'Usa bucles anidados: el externo para filas, el interno para estrellas.',
 'The inner loop runs i times for row i.', 'El bucle interno se ejecuta i veces para la fila i.',
 'for(int i=1;i<=4;i++){for(int j=0;j<i;j++) cout<<"*"; cout<<endl;}', 'for(int i=1;i<=4;i++){for(int j=0;j<i;j++) cout<<"*"; cout<<endl;}',
 20, 3, now()),

(gen_random_uuid(),
 'String to Integer', 'Cadena a Entero',
 'Convert the string "42" to an integer and add 8. Print the result.',
 'Convierte la cadena "42" a un entero y súmale 8. Imprime el resultado.',
 'cpp', 2, 'strings',
 '#include <iostream>\n#include <string>\nusing namespace std;\n\nint main() {\n    // your code\n    return 0;\n}',
 '50',
 3,
 'Use stoi() to convert a string to int.', 'Usa stoi() para convertir una cadena a int.',
 'int n = stoi("42");', 'int n = stoi("42");',
 'cout << n + 8 << endl;', 'cout << n + 8 << endl;',
 20, 3, now()),

(gen_random_uuid(),
 'do-while Loop', 'Bucle do-while',
 'Use a do-while loop to print numbers 1 to 4.',
 'Usa un bucle do-while para imprimir los números del 1 al 4.',
 'cpp', 2, 'basics',
 '#include <iostream>\nusing namespace std;\n\nint main() {\n    // your code\n    return 0;\n}',
 '1\n2\n3\n4',
 3,
 'A do-while loop executes the body at least once.', 'Un bucle do-while ejecuta el cuerpo al menos una vez.',
 'Syntax: do { ... } while (condition);', 'Sintaxis: do { ... } while (condicion);',
 'int i=1; do { cout<<i<<endl; i++; } while(i<=4);', 'int i=1; do { cout<<i<<endl; i++; } while(i<=4);',
 20, 3, now()),

(gen_random_uuid(),
 'GCD of Two Numbers', 'MCD de Dos Números',
 'Print the GCD of 48 and 18 using the Euclidean algorithm.',
 'Imprime el MCD de 48 y 18 usando el algoritmo euclidiano.',
 'cpp', 2, 'math',
 '#include <iostream>\nusing namespace std;\n\nint main() {\n    // your code\n    return 0;\n}',
 '6',
 3,
 'The Euclidean algorithm: gcd(a,b) = gcd(b, a%b).', 'El algoritmo euclidiano: mcd(a,b) = mcd(b, a%b).',
 'Loop until b becomes 0, then a is the GCD.', 'Itera hasta que b sea 0, entonces a es el MCD.',
 'while(b){int t=b;b=a%b;a=t;} cout<<a;', 'while(b){int t=b;b=a%b;a=t;} cout<<a;',
 20, 3, now()),

(gen_random_uuid(),
 'Function Default Parameter', 'Parámetro por Defecto',
 'Write greet(string name="World") that prints "Hello, <name>!". Call it with no argument.',
 'Escribe greet(string name="World") que imprima "Hello, <nombre>!". Llámala sin argumento.',
 'cpp', 2, 'functions',
 '#include <iostream>\n#include <string>\nusing namespace std;\n\n// write your function here\n\nint main() {\n    // your code\n    return 0;\n}',
 'Hello, World!',
 3,
 'Default parameter values are set in the function signature.', 'Los valores por defecto se establecen en la firma de la función.',
 'void greet(string name="World") { cout<<"Hello, "<<name<<"!"; }', 'void greet(string name="World") { cout<<"Hello, "<<name<<"!"; }',
 'greet(); uses the default value.', 'greet(); usa el valor por defecto.',
 20, 3, now()),

(gen_random_uuid(),
 'Bubble Sort', 'Ordenamiento Burbuja',
 'Sort int arr[] = {5, 2, 8, 1, 3} using bubble sort and print the sorted array.',
 'Ordena int arr[] = {5, 2, 8, 1, 3} usando burbuja e imprime el arreglo ordenado.',
 'cpp', 2, 'algorithms',
 '#include <iostream>\nusing namespace std;\n\nint main() {\n    // your code\n    return 0;\n}',
 '1 2 3 5 8',
 3,
 'Compare adjacent elements and swap if out of order.', 'Compara elementos adyacentes e intercámbialos si están desordenados.',
 'Use nested loops: outer for passes, inner for comparisons.', 'Usa bucles anidados: el externo para pasadas, el interno para comparaciones.',
 'for(int i=0;i<n-1;i++) for(int j=0;j<n-i-1;j++) if(arr[j]>arr[j+1]) swap(arr[j],arr[j+1]);', 'for(int i=0;i<n-1;i++) for(int j=0;j<n-i-1;j++) if(arr[j]>arr[j+1]) swap(arr[j],arr[j+1]);',
 20, 3, now()),

(gen_random_uuid(),
 'Integer to String', 'Entero a Cadena',
 'Convert the integer 2024 to a string and print its length.',
 'Convierte el entero 2024 a una cadena e imprime su longitud.',
 'cpp', 2, 'strings',
 '#include <iostream>\n#include <string>\nusing namespace std;\n\nint main() {\n    // your code\n    return 0;\n}',
 '4',
 3,
 'Use to_string() to convert int to string.', 'Usa to_string() para convertir int a string.',
 'string s = to_string(2024);', 'string s = to_string(2024);',
 'cout << s.length() << endl;', 'cout << s.length() << endl;',
 20, 3, now()),

(gen_random_uuid(),
 'Palindrome Check', 'Verificar Palíndromo',
 'Check if the string "racecar" is a palindrome. Print "Yes" or "No".',
 'Verifica si la cadena "racecar" es un palíndromo. Imprime "Yes" o "No".',
 'cpp', 2, 'strings',
 '#include <iostream>\n#include <string>\n#include <algorithm>\nusing namespace std;\n\nint main() {\n    // your code\n    return 0;\n}',
 'Yes',
 3,
 'A palindrome reads the same forwards and backwards.', 'Un palíndromo se lee igual de adelante hacia atrás y viceversa.',
 'Compare the string to its reverse.', 'Compara la cadena con su inversa.',
 'string r=s; reverse(r.begin(),r.end()); if(s==r) cout<<"Yes";', 'string r=s; reverse(r.begin(),r.end()); if(s==r) cout<<"Yes";',
 20, 3, now()),

(gen_random_uuid(),
 'Average of Array', 'Promedio de Arreglo',
 'Compute and print the average of {10, 20, 30, 40, 50} as a double.',
 'Calcula e imprime el promedio de {10, 20, 30, 40, 50} como double.',
 'cpp', 2, 'arrays',
 '#include <iostream>\nusing namespace std;\n\nint main() {\n    // your code\n    return 0;\n}',
 '30',
 3,
 'Sum all elements, then divide by the count.', 'Suma todos los elementos, luego divide entre la cantidad.',
 'Cast the sum to double before dividing to avoid integer division.', 'Convierte la suma a double antes de dividir para evitar división entera.',
 'cout << (double)sum / 5 << endl;', 'cout << (double)sum / 5 << endl;',
 20, 3, now()),

(gen_random_uuid(),
 'Number Pyramid', 'Pirámide de Números',
 'Print a pyramid of numbers with 4 rows: row i contains i repeated i times.',
 'Imprime una pirámide de números con 4 filas: la fila i contiene i repetido i veces.',
 'cpp', 2, 'patterns',
 '#include <iostream>\nusing namespace std;\n\nint main() {\n    // your code\n    return 0;\n}',
 '1\n22\n333\n4444',
 3,
 'Use nested loops.', 'Usa bucles anidados.',
 'Outer loop: rows 1 to 4. Inner loop: print i exactly i times.', 'Bucle externo: filas 1 a 4. Bucle interno: imprime i exactamente i veces.',
 'for(int i=1;i<=4;i++){for(int j=0;j<i;j++) cout<<i; cout<<endl;}', 'for(int i=1;i<=4;i++){for(int j=0;j<i;j++) cout<<i; cout<<endl;}',
 20, 3, now()),

-- ============================================================
-- DIFFICULTY 3 — 25 exercises (points: 30, penalty: 5)
-- ============================================================

(gen_random_uuid(),
 'Class: Rectangle', 'Clase: Rectángulo',
 'Create a Rectangle class with width and height. Add an area() method. Print area of 5x3 rectangle.',
 'Crea una clase Rectangle con ancho y alto. Agrega un método area(). Imprime el área de un rectángulo 5x3.',
 'cpp', 3, 'objects',
 '#include <iostream>\nusing namespace std;\n\n// define your class here\n\nint main() {\n    // your code\n    return 0;\n}',
 '15',
 3,
 'Define a class with public member variables and a method.', 'Define una clase con variables miembro públicas y un método.',
 'int area() { return width * height; }', 'int area() { return width * height; }',
 'Rectangle r; r.width=5; r.height=3; cout<<r.area();', 'Rectangle r; r.width=5; r.height=3; cout<<r.area();',
 30, 5, now()),

(gen_random_uuid(),
 'Constructor and Destructor', 'Constructor y Destructor',
 'Create a class Counter with a constructor that prints "Created" and destructor that prints "Destroyed". Instantiate it.',
 'Crea una clase Counter con constructor que imprima "Created" y destructor que imprima "Destroyed". Instánciala.',
 'cpp', 3, 'objects',
 '#include <iostream>\nusing namespace std;\n\n// define your class here\n\nint main() {\n    // your code\n    return 0;\n}',
 'Created\nDestroyed',
 3,
 'The constructor has the same name as the class.', 'El constructor tiene el mismo nombre que la clase.',
 'The destructor is prefixed with ~.', 'El destructor lleva el prefijo ~.',
 'Counter() { cout<<"Created"<<endl; } ~Counter() { cout<<"Destroyed"<<endl; }', 'Counter() { cout<<"Created"<<endl; } ~Counter() { cout<<"Destroyed"<<endl; }',
 30, 5, now()),

(gen_random_uuid(),
 'Recursive Fibonacci', 'Fibonacci Recursivo',
 'Write a recursive function fib(n) and print fib(10).',
 'Escribe una función recursiva fib(n) e imprime fib(10).',
 'cpp', 3, 'functions',
 '#include <iostream>\nusing namespace std;\n\n// write your function here\n\nint main() {\n    // your code\n    return 0;\n}',
 '55',
 3,
 'Base cases: fib(0)=0, fib(1)=1.', 'Casos base: fib(0)=0, fib(1)=1.',
 'Recursive case: fib(n) = fib(n-1) + fib(n-2).', 'Caso recursivo: fib(n) = fib(n-1) + fib(n-2).',
 'return fib(n-1) + fib(n-2);', 'return fib(n-1) + fib(n-2);',
 30, 5, now()),

(gen_random_uuid(),
 'Template Function', 'Función Template',
 'Write a template function maxOf<T>(T a, T b) that returns the larger value. Test with ints 3 and 7.',
 'Escribe una función template maxOf<T>(T a, T b) que retorne el valor mayor. Pruébala con los enteros 3 y 7.',
 'cpp', 3, 'functions',
 '#include <iostream>\nusing namespace std;\n\n// write your template function here\n\nint main() {\n    // your code\n    return 0;\n}',
 '7',
 3,
 'Use template<typename T> before the function.', 'Usa template<typename T> antes de la función.',
 'T maxOf(T a, T b) { return (a > b) ? a : b; }', 'T maxOf(T a, T b) { return (a > b) ? a : b; }',
 'cout << maxOf(3, 7) << endl;', 'cout << maxOf(3, 7) << endl;',
 30, 5, now()),

(gen_random_uuid(),
 'Singly Linked List Node', 'Nodo de Lista Enlazada',
 'Create a struct Node with int data and Node* next. Build a 3-node list (1->2->3) and print each value.',
 'Crea un struct Node con int data y Node* next. Construye una lista de 3 nodos (1->2->3) e imprime cada valor.',
 'cpp', 3, 'data_structures',
 '#include <iostream>\nusing namespace std;\n\n// define your struct here\n\nint main() {\n    // your code\n    return 0;\n}',
 '1\n2\n3',
 3,
 'A Node holds data and a pointer to the next node.', 'Un Node almacena datos y un puntero al siguiente nodo.',
 'Node* head = new Node{1, nullptr}; then chain more nodes.', 'Node* head = new Node{1, nullptr}; luego encadena más nodos.',
 'while(cur) { cout<<cur->data<<endl; cur=cur->next; }', 'while(cur) { cout<<cur->data<<endl; cur=cur->next; }',
 30, 5, now()),

(gen_random_uuid(),
 'Stack Using Array', 'Pila con Arreglo',
 'Implement a stack (push/pop) using an array. Push 10, 20, 30, then pop and print the top element.',
 'Implementa una pila (push/pop) con un arreglo. Empuja 10, 20, 30, luego desapila e imprime el elemento superior.',
 'cpp', 3, 'data_structures',
 '#include <iostream>\nusing namespace std;\n\nint main() {\n    int stk[100];\n    int top = -1;\n    // your code\n    return 0;\n}',
 '30',
 3,
 'Push increments top then assigns: stk[++top] = val.', 'Push incrementa top y asigna: stk[++top] = val.',
 'Pop returns stk[top--].', 'Pop retorna stk[top--].',
 'Push 10,20,30; cout << stk[top--]; gives 30.', 'Push 10,20,30; cout << stk[top--]; da 30.',
 30, 5, now()),

(gen_random_uuid(),
 'Binary Search', 'Búsqueda Binaria',
 'Implement binary search to find value 14 in sorted array {2,5,8,12,14,18,22}. Print its index.',
 'Implementa búsqueda binaria para encontrar 14 en el arreglo ordenado {2,5,8,12,14,18,22}. Imprime su índice.',
 'cpp', 3, 'algorithms',
 '#include <iostream>\nusing namespace std;\n\nint main() {\n    // your code\n    return 0;\n}',
 '4',
 3,
 'Maintain low and high pointers. Check the middle element.', 'Mantén punteros low y high. Verifica el elemento del medio.',
 'If arr[mid] < target, move low = mid+1; else high = mid-1.', 'Si arr[mid] < target, mueve low = mid+1; si no high = mid-1.',
 'int mid=(low+high)/2; if(arr[mid]==target) return mid;', 'int mid=(low+high)/2; if(arr[mid]==target) return mid;',
 30, 5, now()),

(gen_random_uuid(),
 'std::vector Basics', 'Fundamentos de std::vector',
 'Create a vector of ints, push_back values 1-5, then print them in reverse order.',
 'Crea un vector de enteros, usa push_back con valores 1-5, luego imprímelos en orden inverso.',
 'cpp', 3, 'data_structures',
 '#include <iostream>\n#include <vector>\nusing namespace std;\n\nint main() {\n    // your code\n    return 0;\n}',
 '5 4 3 2 1',
 3,
 'Use vector<int> v; and v.push_back(n);', 'Usa vector<int> v; y v.push_back(n);',
 'Iterate in reverse using a reverse loop or rbegin/rend.', 'Itera en reversa usando un bucle inverso o rbegin/rend.',
 'for(int i=v.size()-1;i>=0;i--) cout<<v[i]<<" ";', 'for(int i=v.size()-1;i>=0;i--) cout<<v[i]<<" ";',
 30, 5, now()),

(gen_random_uuid(),
 'std::map Word Count', 'Conteo de Palabras con std::map',
 'Count occurrences of each word in {"apple","banana","apple","cherry","banana","apple"} using a map.',
 'Cuenta las ocurrencias de cada palabra en {"apple","banana","apple","cherry","banana","apple"} con un mapa.',
 'cpp', 3, 'data_structures',
 '#include <iostream>\n#include <map>\n#include <vector>\n#include <string>\nusing namespace std;\n\nint main() {\n    // your code\n    return 0;\n}',
 'apple: 3\nbanana: 2\ncherry: 1',
 3,
 'Use map<string,int> to count word frequencies.', 'Usa map<string,int> para contar frecuencias de palabras.',
 'wordCount[word]++ increments the count.', 'wordCount[word]++ incrementa el conteo.',
 'for(auto& p : wordCount) cout<<p.first<<": "<<p.second<<endl;', 'for(auto& p : wordCount) cout<<p.first<<": "<<p.second<<endl;',
 30, 5, now()),

(gen_random_uuid(),
 'Inheritance', 'Herencia',
 'Create base class Animal with speak(). Derive Dog that overrides speak() to print "Woof". Call speak() on a Dog.',
 'Crea la clase base Animal con speak(). Deriva Dog que sobreescriba speak() para imprimir "Woof". Llama speak() en un Dog.',
 'cpp', 3, 'objects',
 '#include <iostream>\nusing namespace std;\n\n// define your classes here\n\nint main() {\n    // your code\n    return 0;\n}',
 'Woof',
 3,
 'Use class Dog : public Animal to inherit.', 'Usa class Dog : public Animal para heredar.',
 'Override speak() in Dog with the same signature.', 'Sobreescribe speak() en Dog con la misma firma.',
 'Dog d; d.speak(); prints "Woof".', 'Dog d; d.speak(); imprime "Woof".',
 30, 5, now()),

(gen_random_uuid(),
 'Operator Overloading', 'Sobrecarga de Operadores',
 'Create a Vector2D class with x,y. Overload + to add two vectors. Print (1,2)+(3,4).',
 'Crea la clase Vector2D con x,y. Sobrecarga + para sumar dos vectores. Imprime (1,2)+(3,4).',
 'cpp', 3, 'objects',
 '#include <iostream>\nusing namespace std;\n\n// define your class here\n\nint main() {\n    // your code\n    return 0;\n}',
 '4 6',
 3,
 'Use Vector2D operator+(const Vector2D& other) const.', 'Usa Vector2D operator+(const Vector2D& other) const.',
 'Return a new Vector2D with summed components.', 'Retorna un nuevo Vector2D con componentes sumadas.',
 'return Vector2D{x+other.x, y+other.y};', 'return Vector2D{x+other.x, y+other.y};',
 30, 5, now()),

(gen_random_uuid(),
 'Exception Handling', 'Manejo de Excepciones',
 'Write code that throws a runtime_error when dividing by zero. Catch it and print the error message.',
 'Escribe código que lance un runtime_error al dividir entre cero. Captúralo e imprime el mensaje de error.',
 'cpp', 3, 'basics',
 '#include <iostream>\n#include <stdexcept>\nusing namespace std;\n\nint main() {\n    // your code\n    return 0;\n}',
 'Division by zero',
 3,
 'Use try { ... } catch (exception& e) { ... }.', 'Usa try { ... } catch (exception& e) { ... }.',
 'throw runtime_error("Division by zero"); inside the try block.', 'throw runtime_error("Division by zero"); dentro del bloque try.',
 'cout << e.what() << endl; prints the message.', 'cout << e.what() << endl; imprime el mensaje.',
 30, 5, now()),

(gen_random_uuid(),
 'Selection Sort', 'Ordenamiento por Selección',
 'Sort {64, 25, 12, 22, 11} using selection sort and print the result.',
 'Ordena {64, 25, 12, 22, 11} con ordenamiento por selección e imprime el resultado.',
 'cpp', 3, 'algorithms',
 '#include <iostream>\nusing namespace std;\n\nint main() {\n    // your code\n    return 0;\n}',
 '11 12 22 25 64',
 3,
 'Find the minimum in the unsorted portion and swap it to front.', 'Encuentra el mínimo en la porción no ordenada e intercámbialo al frente.',
 'Use two nested loops: outer selects position, inner finds minimum.', 'Usa dos bucles anidados: el externo selecciona posición, el interno encuentra el mínimo.',
 'swap(arr[i], arr[minIdx]);', 'swap(arr[i], arr[minIdx]);',
 30, 5, now()),

(gen_random_uuid(),
 'File Write and Read', 'Escribir y Leer Archivo',
 'Write "Hello File" to a file, then read and print it back.',
 'Escribe "Hello File" en un archivo, luego léelo e imprímelo.',
 'cpp', 3, 'basics',
 '#include <iostream>\n#include <fstream>\n#include <string>\nusing namespace std;\n\nint main() {\n    // your code\n    return 0;\n}',
 'Hello File',
 3,
 'Use ofstream to write, ifstream to read.', 'Usa ofstream para escribir, ifstream para leer.',
 'ofstream out("test.txt"); out << "Hello File"; out.close();', 'ofstream out("test.txt"); out << "Hello File"; out.close();',
 'ifstream in("test.txt"); getline(in, line); cout << line;', 'ifstream in("test.txt"); getline(in, line); cout << line;',
 30, 5, now()),

(gen_random_uuid(),
 'Lambda Function', 'Función Lambda',
 'Use a lambda to square a number. Store it in auto sq and print sq(7).',
 'Usa una lambda para elevar al cuadrado un número. Guárdala en auto sq e imprime sq(7).',
 'cpp', 3, 'functions',
 '#include <iostream>\nusing namespace std;\n\nint main() {\n    // your code\n    return 0;\n}',
 '49',
 3,
 'A lambda: auto fn = [](params) { return ...; };', 'Una lambda: auto fn = [](params) { return ...; };',
 'auto sq = [](int x) { return x * x; };', 'auto sq = [](int x) { return x * x; };',
 'cout << sq(7) << endl;', 'cout << sq(7) << endl;',
 30, 5, now()),

(gen_random_uuid(),
 'std::sort with Lambda', 'std::sort con Lambda',
 'Sort vector {5,3,8,1,9} in descending order using std::sort and a lambda comparator.',
 'Ordena el vector {5,3,8,1,9} en orden descendente usando std::sort y una lambda comparadora.',
 'cpp', 3, 'algorithms',
 '#include <iostream>\n#include <vector>\n#include <algorithm>\nusing namespace std;\n\nint main() {\n    // your code\n    return 0;\n}',
 '9 8 5 3 1',
 3,
 'Pass a lambda as the third argument to std::sort.', 'Pasa una lambda como tercer argumento a std::sort.',
 'sort(v.begin(), v.end(), [](int a, int b){ return a > b; });', 'sort(v.begin(), v.end(), [](int a, int b){ return a > b; });',
 'Print elements separated by spaces.', 'Imprime elementos separados por espacios.',
 30, 5, now()),

(gen_random_uuid(),
 'Struct with Methods', 'Struct con Métodos',
 'Create a struct Circle with double radius and method area() returning pi*r*r. Print area of r=5.',
 'Crea un struct Circle con double radius y método area() que retorne pi*r*r. Imprime el área con r=5.',
 'cpp', 3, 'objects',
 '#include <iostream>\n#include <cmath>\nusing namespace std;\n\n// define your struct here\n\nint main() {\n    // your code\n    return 0;\n}',
 '78.5398',
 3,
 'Structs can have methods just like classes.', 'Los structs pueden tener métodos igual que las clases.',
 'Use M_PI or 3.14159265 for pi.', 'Usa M_PI o 3.14159265 para pi.',
 'double area() { return M_PI * radius * radius; }', 'double area() { return M_PI * radius * radius; }',
 30, 5, now()),

(gen_random_uuid(),
 'Queue Using STL', 'Cola con STL',
 'Use std::queue to enqueue 10, 20, 30, then dequeue and print the front element.',
 'Usa std::queue para encolar 10, 20, 30, luego desencola e imprime el elemento frontal.',
 'cpp', 3, 'data_structures',
 '#include <iostream>\n#include <queue>\nusing namespace std;\n\nint main() {\n    // your code\n    return 0;\n}',
 '10',
 3,
 'Include <queue> for std::queue.', 'Incluye <queue> para std::queue.',
 'Use q.push(val) to enqueue and q.front() to see front.', 'Usa q.push(val) para encolar y q.front() para ver el frente.',
 'q.pop() removes the front; q.front() shows it.', 'q.pop() elimina el frente; q.front() lo muestra.',
 30, 5, now()),

(gen_random_uuid(),
 'String Split by Delimiter', 'Dividir Cadena por Delimitador',
 'Split "one,two,three" by comma and print each token on a new line.',
 'Divide "one,two,three" por coma e imprime cada token en una línea nueva.',
 'cpp', 3, 'strings',
 '#include <iostream>\n#include <sstream>\n#include <string>\nusing namespace std;\n\nint main() {\n    // your code\n    return 0;\n}',
 'one\ntwo\nthree',
 3,
 'Use stringstream to parse tokens.', 'Usa stringstream para analizar tokens.',
 'Replace commas with spaces first, or use getline(ss, token, '','').', 'Reemplaza comas con espacios primero, o usa getline(ss, token, '','').',
 'while(getline(ss,token,'','')) cout<<token<<endl;', 'while(getline(ss,token,'','')) cout<<token<<endl;',
 30, 5, now()),

(gen_random_uuid(),
 'Dynamic Array with new', 'Arreglo Dinámico con new',
 'Allocate an int array of size 5 using new, fill it 1-5, print sum, then delete[].',
 'Asigna un arreglo de int de tamaño 5 con new, llénalo del 1 al 5, imprime la suma, luego delete[].',
 'cpp', 3, 'basics',
 '#include <iostream>\nusing namespace std;\n\nint main() {\n    // your code\n    return 0;\n}',
 '15',
 3,
 'int* arr = new int[5]; allocates heap memory.', 'int* arr = new int[5]; asigna memoria en el heap.',
 'Use a loop to fill and another to sum.', 'Usa un bucle para llenar y otro para sumar.',
 'delete[] arr; frees the memory.', 'delete[] arr; libera la memoria.',
 30, 5, now()),

(gen_random_uuid(),
 'Prime Number Check', 'Verificar Número Primo',
 'Write isPrime(int n) and print whether 37 is prime.',
 'Escribe isPrime(int n) e imprime si 37 es primo.',
 'cpp', 3, 'math',
 '#include <iostream>\n#include <cmath>\nusing namespace std;\n\n// write your function here\n\nint main() {\n    // your code\n    return 0;\n}',
 'Prime',
 3,
 'Check divisibility from 2 to sqrt(n).', 'Verifica divisibilidad desde 2 hasta sqrt(n).',
 'If any divisor found, it''s not prime.', 'Si se encuentra algún divisor, no es primo.',
 'for(int i=2;i<=sqrt(n);i++) if(n%i==0) return false;', 'for(int i=2;i<=sqrt(n);i++) if(n%i==0) return false;',
 30, 5, now()),

(gen_random_uuid(),
 'Insertion Sort', 'Ordenamiento por Inserción',
 'Sort {12, 11, 13, 5, 6} using insertion sort and print the result.',
 'Ordena {12, 11, 13, 5, 6} con ordenamiento por inserción e imprime el resultado.',
 'cpp', 3, 'algorithms',
 '#include <iostream>\nusing namespace std;\n\nint main() {\n    // your code\n    return 0;\n}',
 '5 6 11 12 13',
 3,
 'Take each element and insert it in its correct position.', 'Toma cada elemento e insértalo en su posición correcta.',
 'Shift elements right while arr[j] > key.', 'Desplaza elementos a la derecha mientras arr[j] > key.',
 'int key=arr[i]; while(j>=0&&arr[j]>key){arr[j+1]=arr[j];j--;}', 'int key=arr[i]; while(j>=0&&arr[j]>key){arr[j+1]=arr[j];j--;}',
 30, 5, now()),

(gen_random_uuid(),
 'Static Class Member', 'Miembro Estático de Clase',
 'Create class Counter with a static int count. Increment in constructor. Create 3 objects and print count.',
 'Crea la clase Counter con un static int count. Incrementa en el constructor. Crea 3 objetos e imprime count.',
 'cpp', 3, 'objects',
 '#include <iostream>\nusing namespace std;\n\n// define your class here\n\nint main() {\n    // your code\n    return 0;\n}',
 '3',
 3,
 'Static members are shared across all instances.', 'Los miembros estáticos se comparten entre todas las instancias.',
 'Declare: static int count; and define outside: int Counter::count = 0;', 'Declara: static int count; y define afuera: int Counter::count = 0;',
 'Counter::count++ in the constructor.', 'Counter::count++ en el constructor.',
 30, 5, now()),

(gen_random_uuid(),
 'Merge Two Sorted Arrays', 'Fusionar Dos Arreglos Ordenados',
 'Merge {1,3,5} and {2,4,6} into a sorted array and print the result.',
 'Fusiona {1,3,5} y {2,4,6} en un arreglo ordenado e imprime el resultado.',
 'cpp', 3, 'algorithms',
 '#include <iostream>\nusing namespace std;\n\nint main() {\n    // your code\n    return 0;\n}',
 '1 2 3 4 5 6',
 3,
 'Use two pointers, one for each array.', 'Usa dos punteros, uno para cada arreglo.',
 'Compare elements at both pointers and copy the smaller one.', 'Compara elementos en ambos punteros y copia el menor.',
 'while(i<n1 && j<n2) result[k++] = (a[i]<b[j]) ? a[i++] : b[j++];', 'while(i<n1 && j<n2) result[k++] = (a[i]<b[j]) ? a[i++] : b[j++];',
 30, 5, now()),

(gen_random_uuid(),
 'Diamond Pattern', 'Patrón Diamante',
 'Print a diamond pattern of stars with max width 5 (5 rows top half, 4 rows bottom).',
 'Imprime un patrón diamante de estrellas con ancho máximo 5 (5 filas mitad superior, 4 inferior).',
 'cpp', 3, 'patterns',
 '#include <iostream>\nusing namespace std;\n\nint main() {\n    // your code\n    return 0;\n}',
 '  *\n ***\n*****\n ***\n  *',
 3,
 'Print spaces then stars for each row.', 'Imprime espacios luego estrellas para cada fila.',
 'Stars in row i = 2*i-1 for upper half (i from 1 to n).', 'Estrellas en fila i = 2*i-1 para la mitad superior (i de 1 a n).',
 'Mirror the upper half for the lower half.', 'Refleja la mitad superior para la mitad inferior.',
 30, 5, now()),

-- ============================================================
-- DIFFICULTY 4 — 15 exercises (points: 50, penalty: 10)
-- ============================================================

(gen_random_uuid(),
 'Binary Tree Insert and Inorder', 'Árbol Binario: Inserción e Inorden',
 'Implement a BST with insert and inorder traversal. Insert {5,3,7,1,4} and print inorder.',
 'Implementa un BST con inserción y recorrido inorden. Inserta {5,3,7,1,4} e imprime inorden.',
 'cpp', 4, 'data_structures',
 '#include <iostream>\nusing namespace std;\n\n// define Node struct and BST here\n\nint main() {\n    // your code\n    return 0;\n}',
 '1 3 4 5 7',
 3,
 'BST: left < root < right.', 'BST: izquierda < raíz < derecha.',
 'Recursive insert: go left if val<root, right if val>root.', 'Inserción recursiva: ir a la izquierda si val<raíz, a la derecha si val>raíz.',
 'Inorder: traverse left, print root, traverse right.', 'Inorden: recorrer izquierda, imprimir raíz, recorrer derecha.',
 50, 10, now()),

(gen_random_uuid(),
 'Smart Pointer: unique_ptr', 'Puntero Inteligente: unique_ptr',
 'Create a unique_ptr<int> pointing to 42. Print its value and demonstrate auto-cleanup.',
 'Crea un unique_ptr<int> apuntando a 42. Imprime su valor y demuestra la limpieza automática.',
 'cpp', 4, 'objects',
 '#include <iostream>\n#include <memory>\nusing namespace std;\n\nint main() {\n    // your code\n    return 0;\n}',
 '42',
 3,
 'Include <memory> for smart pointers.', 'Incluye <memory> para punteros inteligentes.',
 'auto p = make_unique<int>(42);', 'auto p = make_unique<int>(42);',
 'Dereference with *p to get the value.', 'Desreferencia con *p para obtener el valor.',
 50, 10, now()),

(gen_random_uuid(),
 'Merge Sort', 'Ordenamiento por Mezcla',
 'Implement merge sort and sort {38, 27, 43, 3, 9, 82, 10}. Print the result.',
 'Implementa merge sort y ordena {38, 27, 43, 3, 9, 82, 10}. Imprime el resultado.',
 'cpp', 4, 'algorithms',
 '#include <iostream>\nusing namespace std;\n\n// implement merge sort here\n\nint main() {\n    // your code\n    return 0;\n}',
 '3 9 10 27 38 43 82',
 3,
 'Divide the array in half recursively.', 'Divide el arreglo a la mitad recursivamente.',
 'Merge two sorted halves using a temporary array.', 'Fusiona dos mitades ordenadas usando un arreglo temporal.',
 'mergeSort(arr, l, mid); mergeSort(arr, mid+1, r); merge(...);', 'mergeSort(arr, l, mid); mergeSort(arr, mid+1, r); merge(...);',
 50, 10, now()),

(gen_random_uuid(),
 'Virtual Functions and Polymorphism', 'Funciones Virtuales y Polimorfismo',
 'Create Animal base with virtual sound(). Cat prints "Meow", Dog prints "Woof". Use base pointer array to call each.',
 'Crea la base Animal con virtual sound(). Cat imprime "Meow", Dog "Woof". Usa arreglo de punteros base para llamar cada uno.',
 'cpp', 4, 'objects',
 '#include <iostream>\nusing namespace std;\n\n// define classes here\n\nint main() {\n    // your code\n    return 0;\n}',
 'Meow\nWoof',
 3,
 'Mark the base method as virtual.', 'Marca el método base como virtual.',
 'Animal* animals[] = {new Cat(), new Dog()};', 'Animal* animals[] = {new Cat(), new Dog()};',
 'Loop and call animals[i]->sound(); for polymorphism.', 'Itera y llama animals[i]->sound(); para polimorfismo.',
 50, 10, now()),

(gen_random_uuid(),
 'Quick Sort', 'Ordenamiento Rápido',
 'Implement quicksort and sort {10, 7, 8, 9, 1, 5}. Print the result.',
 'Implementa quicksort y ordena {10, 7, 8, 9, 1, 5}. Imprime el resultado.',
 'cpp', 4, 'algorithms',
 '#include <iostream>\nusing namespace std;\n\n// implement quicksort here\n\nint main() {\n    // your code\n    return 0;\n}',
 '1 5 7 8 9 10',
 3,
 'Choose a pivot and partition elements around it.', 'Elige un pivote y particiona los elementos alrededor de él.',
 'Elements < pivot go left, elements > pivot go right.', 'Elementos < pivote van a la izquierda, > pivote a la derecha.',
 'Recursively quicksort left and right partitions.', 'Recursivamente aplica quicksort en las particiones izquierda y derecha.',
 50, 10, now()),

(gen_random_uuid(),
 'Abstract Class Interface', 'Interfaz con Clase Abstracta',
 'Create abstract class Shape with pure virtual area(). Derive Triangle (base=6, height=4). Print area.',
 'Crea la clase abstracta Shape con virtual area() puro. Deriva Triangle (base=6, altura=4). Imprime área.',
 'cpp', 4, 'objects',
 '#include <iostream>\nusing namespace std;\n\n// define classes here\n\nint main() {\n    // your code\n    return 0;\n}',
 '12',
 3,
 'A pure virtual function: virtual double area() = 0;', 'Una función virtual pura: virtual double area() = 0;',
 'Triangle area = 0.5 * base * height.', 'Área del triángulo = 0.5 * base * altura.',
 'Shape* s = new Triangle(6,4); cout << s->area();', 'Shape* s = new Triangle(6,4); cout << s->area();',
 50, 10, now()),

(gen_random_uuid(),
 'Graph BFS', 'BFS en Grafo',
 'Implement BFS on an undirected graph with 5 nodes (edges: 0-1,0-2,1-3,2-4). Print BFS from node 0.',
 'Implementa BFS en un grafo no dirigido de 5 nodos (aristas: 0-1,0-2,1-3,2-4). Imprime BFS desde nodo 0.',
 'cpp', 4, 'algorithms',
 '#include <iostream>\n#include <vector>\n#include <queue>\nusing namespace std;\n\nint main() {\n    // your code\n    return 0;\n}',
 '0 1 2 3 4',
 3,
 'Use an adjacency list: vector<vector<int>> adj(5).', 'Usa lista de adyacencia: vector<vector<int>> adj(5).',
 'Use a queue and a visited[] boolean array.', 'Usa una cola y un arreglo booleano visited[].',
 'While queue not empty: dequeue, print, enqueue unvisited neighbors.', 'Mientras la cola no esté vacía: desencola, imprime, encola vecinos no visitados.',
 50, 10, now()),

(gen_random_uuid(),
 'Variadic Template', 'Template Variádico',
 'Write a variadic template sum() that sums any number of ints. Print sum(1,2,3,4,5).',
 'Escribe un template variádico sum() que sume cualquier cantidad de enteros. Imprime sum(1,2,3,4,5).',
 'cpp', 4, 'functions',
 '#include <iostream>\nusing namespace std;\n\n// implement variadic template here\n\nint main() {\n    // your code\n    return 0;\n}',
 '15',
 3,
 'Use template<typename T, typename... Args>.', 'Usa template<typename T, typename... Args>.',
 'Base case: sum(T v) { return v; }', 'Caso base: sum(T v) { return v; }',
 'Recursive: return v + sum(args...);', 'Recursivo: return v + sum(args...);',
 50, 10, now()),

(gen_random_uuid(),
 'Move Semantics', 'Semántica de Movimiento',
 'Create class Buffer with a move constructor. Move a Buffer and print "Moved" from the move constructor.',
 'Crea la clase Buffer con constructor de movimiento. Mueve un Buffer e imprime "Moved" desde el constructor de movimiento.',
 'cpp', 4, 'objects',
 '#include <iostream>\n#include <utility>\nusing namespace std;\n\n// define Buffer class here\n\nint main() {\n    // your code\n    return 0;\n}',
 'Moved',
 3,
 'A move constructor takes an rvalue reference: Buffer(Buffer&& other).', 'Un constructor de movimiento toma una referencia rvalue: Buffer(Buffer&& other).',
 'Use std::move() to cast to rvalue: Buffer b2 = std::move(b1);', 'Usa std::move() para convertir a rvalue: Buffer b2 = std::move(b1);',
 'Print "Moved" inside the move constructor body.', 'Imprime "Moved" dentro del cuerpo del constructor de movimiento.',
 50, 10, now()),

(gen_random_uuid(),
 'std::unordered_map Frequency', 'Frecuencia con std::unordered_map',
 'Find the most frequent element in {1,3,2,1,4,1,3,2,1}. Print the element and its count.',
 'Encuentra el elemento más frecuente en {1,3,2,1,4,1,3,2,1}. Imprime el elemento y su conteo.',
 'cpp', 4, 'data_structures',
 '#include <iostream>\n#include <unordered_map>\n#include <vector>\nusing namespace std;\n\nint main() {\n    // your code\n    return 0;\n}',
 '1 4',
 3,
 'Use unordered_map<int,int> to count frequencies.', 'Usa unordered_map<int,int> para contar frecuencias.',
 'Iterate over the map to find the key with the max value.', 'Itera sobre el mapa para encontrar la clave con el valor máximo.',
 'if(freq[x] > maxCount) { maxCount=freq[x]; maxElem=x; }', 'if(freq[x] > maxCount) { maxCount=freq[x]; maxElem=x; }',
 50, 10, now()),

(gen_random_uuid(),
 'Doubly Linked List', 'Lista Doblemente Enlazada',
 'Build a doubly linked list with nodes 1,2,3. Print it forward then backward.',
 'Construye una lista doblemente enlazada con nodos 1,2,3. Imprímela hacia adelante y luego hacia atrás.',
 'cpp', 4, 'data_structures',
 '#include <iostream>\nusing namespace std;\n\n// define Node struct here\n\nint main() {\n    // your code\n    return 0;\n}',
 '1 2 3\n3 2 1',
 3,
 'Each node has next and prev pointers.', 'Cada nodo tiene punteros next y prev.',
 'Traverse forward using next; traverse backward using prev from tail.', 'Recorre hacia adelante con next; hacia atrás con prev desde la cola.',
 'Keep a tail pointer to start the backward traversal.', 'Mantén un puntero tail para iniciar el recorrido inverso.',
 50, 10, now()),

(gen_random_uuid(),
 'RAII Resource Management', 'Gestión de Recursos RAII',
 'Create a FileHandle class that opens a file in constructor and closes in destructor. Write "RAII" and read it back.',
 'Crea la clase FileHandle que abre un archivo en el constructor y lo cierra en el destructor. Escribe "RAII" y léelo de vuelta.',
 'cpp', 4, 'objects',
 '#include <iostream>\n#include <fstream>\n#include <string>\nusing namespace std;\n\n// define FileHandle class here\n\nint main() {\n    // your code\n    return 0;\n}',
 'RAII',
 3,
 'RAII: Resource Acquisition Is Initialization.', 'RAII: La Adquisición de Recursos es Inicialización.',
 'Open file in constructor, close in destructor.', 'Abre el archivo en el constructor, ciérralo en el destructor.',
 'Scope the FileHandle object so destructor runs at end of block.', 'Delimita el objeto FileHandle para que el destructor se ejecute al final del bloque.',
 50, 10, now()),

(gen_random_uuid(),
 'Depth-First Search', 'Búsqueda en Profundidad',
 'Implement recursive DFS on a graph with 4 nodes (edges 0-1,0-2,1-3). Print DFS from node 0.',
 'Implementa DFS recursivo en un grafo de 4 nodos (aristas 0-1,0-2,1-3). Imprime DFS desde nodo 0.',
 'cpp', 4, 'algorithms',
 '#include <iostream>\n#include <vector>\nusing namespace std;\n\n// implement DFS here\n\nint main() {\n    // your code\n    return 0;\n}',
 '0 1 3 2',
 3,
 'Use a visited[] array to avoid revisiting nodes.', 'Usa un arreglo visited[] para evitar revisitar nodos.',
 'DFS: mark visited, print, then recurse on each neighbor.', 'DFS: marca como visitado, imprime, luego recurre en cada vecino.',
 'void dfs(int v, vector<bool>& vis, vector<vector<int>>& adj)', 'void dfs(int v, vector<bool>& vis, vector<vector<int>>& adj)',
 50, 10, now()),

(gen_random_uuid(),
 'Custom Iterator', 'Iterador Personalizado',
 'Create a Range class that supports range-based for loop over integers [1,5]. Print each value.',
 'Crea una clase Range que soporte bucle for basado en rango sobre enteros [1,5]. Imprime cada valor.',
 'cpp', 4, 'objects',
 '#include <iostream>\nusing namespace std;\n\n// define Range and Iterator here\n\nint main() {\n    // your code\n    return 0;\n}',
 '1\n2\n3\n4\n5',
 3,
 'Provide begin() and end() methods returning iterators.', 'Provee métodos begin() y end() que retornen iteradores.',
 'The iterator needs operator++, operator*, and operator!=.', 'El iterador necesita operator++, operator*, y operator!=.',
 'for (int x : Range(1, 5)) cout << x << endl;', 'for (int x : Range(1, 5)) cout << x << endl;',
 50, 10, now()),

(gen_random_uuid(),
 'Matrix Multiplication', 'Multiplicación de Matrices',
 'Multiply 2x2 matrices A={{1,2},{3,4}} and B={{5,6},{7,8}}. Print the result matrix.',
 'Multiplica las matrices 2x2 A={{1,2},{3,4}} y B={{5,6},{7,8}}. Imprime la matriz resultado.',
 'cpp', 4, 'math',
 '#include <iostream>\nusing namespace std;\n\nint main() {\n    // your code\n    return 0;\n}',
 '19 22\n43 50',
 3,
 'C[i][j] = sum of A[i][k]*B[k][j] for all k.', 'C[i][j] = suma de A[i][k]*B[k][j] para todo k.',
 'Use three nested loops: i, j, k.', 'Usa tres bucles anidados: i, j, k.',
 'for(int k=0;k<2;k++) C[i][j] += A[i][k]*B[k][j];', 'for(int k=0;k<2;k++) C[i][j] += A[i][k]*B[k][j];',
 50, 10, now()),

-- ============================================================
-- DIFFICULTY 5 — 10 exercises (points: 100, penalty: 10)
-- ============================================================

(gen_random_uuid(),
 'LRU Cache', 'Caché LRU',
 'Implement an LRU cache with capacity 2. Put(1,1), Put(2,2), Get(1)=1, Put(3,3) evicts 2, Get(2)=-1. Print Get results.',
 'Implementa una caché LRU con capacidad 2. Put(1,1), Put(2,2), Get(1)=1, Put(3,3) desaloja 2, Get(2)=-1. Imprime resultados.',
 'cpp', 5, 'data_structures',
 '#include <iostream>\n#include <list>\n#include <unordered_map>\nusing namespace std;\n\n// implement LRUCache here\n\nint main() {\n    // your code\n    return 0;\n}',
 '1\n-1',
 3,
 'Use a doubly linked list for O(1) eviction + unordered_map for O(1) lookup.', 'Usa una lista doblemente enlazada para desalojo O(1) + unordered_map para búsqueda O(1).',
 'The map stores key -> list iterator for fast access.', 'El mapa almacena key -> iterador de lista para acceso rápido.',
 'On Get: move accessed node to front. On Put overflow: remove back node.', 'En Get: mueve el nodo accedido al frente. En Put si excede: elimina el nodo trasero.',
 100, 10, now()),

(gen_random_uuid(),
 'Trie Data Structure', 'Estructura de Datos Trie',
 'Implement a Trie with insert and search. Insert "apple" and "app". Search "app"=true, "apt"=false.',
 'Implementa un Trie con inserción y búsqueda. Inserta "apple" y "app". Busca "app"=true, "apt"=false.',
 'cpp', 5, 'data_structures',
 '#include <iostream>\n#include <unordered_map>\nusing namespace std;\n\n// implement TrieNode and Trie here\n\nint main() {\n    // your code\n    return 0;\n}',
 '1\n0',
 3,
 'Each TrieNode has a map of children and a bool isEnd.', 'Cada TrieNode tiene un mapa de hijos y un bool isEnd.',
 'Insert: traverse/create nodes for each char; mark isEnd at last.', 'Insertar: recorre/crea nodos para cada char; marca isEnd al final.',
 'Search: traverse nodes; return isEnd of last node.', 'Buscar: recorre nodos; retorna isEnd del último nodo.',
 100, 10, now()),

(gen_random_uuid(),
 'Dijkstra''s Algorithm', 'Algoritmo de Dijkstra',
 'Find the shortest path from node 0 in a 5-node weighted graph. Print distances from 0.',
 'Encuentra el camino más corto desde el nodo 0 en un grafo ponderado de 5 nodos. Imprime distancias desde 0.',
 'cpp', 5, 'algorithms',
 '#include <iostream>\n#include <vector>\n#include <queue>\n#include <climits>\nusing namespace std;\n\nint main() {\n    // edges: {0,1,10},{0,2,3},{1,3,2},{2,1,4},{2,3,8},{3,4,5},{4,3,1}\n    return 0;\n}',
 '0 7 3 9 14',
 3,
 'Use a min-heap priority_queue of {distance, node}.', 'Usa una priority_queue min-heap de {distancia, nodo}.',
 'Initialize dist[] = INT_MAX; dist[src] = 0.', 'Inicializa dist[] = INT_MAX; dist[src] = 0.',
 'Relax edges: if dist[u]+w < dist[v], update dist[v].', 'Relaja aristas: si dist[u]+w < dist[v], actualiza dist[v].',
 100, 10, now()),

(gen_random_uuid(),
 'Thread-Safe Singleton', 'Singleton con Seguridad de Hilos',
 'Implement a thread-safe Singleton using call_once. Print the instance address twice and verify they match.',
 'Implementa un Singleton seguro para hilos usando call_once. Imprime la dirección de instancia dos veces y verifica que coincidan.',
 'cpp', 5, 'objects',
 '#include <iostream>\n#include <mutex>\nusing namespace std;\n\n// implement Singleton here\n\nint main() {\n    // your code\n    return 0;\n}',
 'Same instance',
 3,
 'Use static Singleton* instance and std::once_flag.', 'Usa static Singleton* instance y std::once_flag.',
 'std::call_once(flag, []{ instance = new Singleton(); });', 'std::call_once(flag, []{ instance = new Singleton(); });',
 'Compare pointers: if(a==b) cout<<"Same instance";', 'Compara punteros: if(a==b) cout<<"Same instance";',
 100, 10, now()),

(gen_random_uuid(),
 'Expression Tree Evaluator', 'Evaluador de Árbol de Expresión',
 'Build an expression tree for (3+4)*2 using nodes. Evaluate and print the result.',
 'Construye un árbol de expresión para (3+4)*2 usando nodos. Evalúa e imprime el resultado.',
 'cpp', 5, 'data_structures',
 '#include <iostream>\nusing namespace std;\n\n// define ExprNode and evaluate() here\n\nint main() {\n    // your code\n    return 0;\n}',
 '14',
 3,
 'Each node is either an operator (+,-,*,/) or a number leaf.', 'Cada nodo es un operador (+,-,*,/) o una hoja numérica.',
 'Recursive evaluate: return left->eval() op right->eval() for operators.', 'Evaluación recursiva: retorna left->eval() op right->eval() para operadores.',
 'Build tree manually: multiply node with children (add node(3,4)) and 2.', 'Construye el árbol manualmente: nodo multiplicar con hijos (nodo sumar(3,4)) y 2.',
 100, 10, now()),

(gen_random_uuid(),
 'CRTP Static Polymorphism', 'Polimorfismo Estático con CRTP',
 'Use CRTP: Base<Derived> calls Derived::impl(). Create Square that prints "Square". Call through Base.',
 'Usa CRTP: Base<Derived> llama a Derived::impl(). Crea Square que imprima "Square". Llama a través de Base.',
 'cpp', 5, 'objects',
 '#include <iostream>\nusing namespace std;\n\n// implement CRTP here\n\nint main() {\n    // your code\n    return 0;\n}',
 'Square',
 3,
 'CRTP: template<typename T> class Base { void execute(){ static_cast<T*>(this)->impl(); } };', 'CRTP: template<typename T> class Base { void execute(){ static_cast<T*>(this)->impl(); } };',
 'Derived inherits from Base<Derived> and provides impl().', 'Derived hereda de Base<Derived> y provee impl().',
 'No virtual dispatch — resolved at compile time.', 'Sin despacho virtual — resuelto en tiempo de compilación.',
 100, 10, now()),

(gen_random_uuid(),
 'Memory Pool Allocator', 'Asignador de Memoria Pool',
 'Implement a simple memory pool that pre-allocates 1024 bytes. Allocate and print two int values from it.',
 'Implementa un memory pool simple que pre-asigna 1024 bytes. Asigna e imprime dos valores int de él.',
 'cpp', 5, 'challenges',
 '#include <iostream>\nusing namespace std;\n\n// implement MemoryPool here\n\nint main() {\n    // your code\n    return 0;\n}',
 '42\n99',
 3,
 'Pre-allocate a char buffer[1024] as the pool.', 'Pre-asigna un char buffer[1024] como el pool.',
 'Keep an offset pointer; allocate by advancing it.', 'Mantén un puntero de desplazamiento; asigna avanzándolo.',
 'Use placement new: new(pool.alloc(sizeof(int))) int(42);', 'Usa placement new: new(pool.alloc(sizeof(int))) int(42);',
 100, 10, now()),

(gen_random_uuid(),
 'Compile-Time Fibonacci', 'Fibonacci en Tiempo de Compilación',
 'Use template metaprogramming to compute Fibonacci at compile time. Print Fib<12>::value.',
 'Usa metaprogramación de plantillas para calcular Fibonacci en tiempo de compilación. Imprime Fib<12>::value.',
 'cpp', 5, 'challenges',
 '#include <iostream>\nusing namespace std;\n\n// implement Fib template here\n\nint main() {\n    // your code\n    return 0;\n}',
 '144',
 3,
 'Use template<int N> struct Fib { enum { value = Fib<N-1>::value + Fib<N-2>::value }; };', 'Usa template<int N> struct Fib { enum { value = Fib<N-1>::value + Fib<N-2>::value }; };',
 'Base cases: template<> struct Fib<0> and Fib<1> with value=0 and 1.', 'Casos base: template<> struct Fib<0> y Fib<1> con value=0 y 1.',
 'cout << Fib<12>::value; is evaluated entirely at compile time.', 'cout << Fib<12>::value; se evalúa completamente en tiempo de compilación.',
 100, 10, now()),

(gen_random_uuid(),
 'Coroutine Generator (C++20)', 'Generador Corrutina (C++20)',
 'Implement a coroutine generator that yields integers 1 to 5 using C++20 coroutines. Print each yielded value.',
 'Implementa un generador corrutina que produzca enteros del 1 al 5 usando corrutinas C++20. Imprime cada valor producido.',
 'cpp', 5, 'challenges',
 '#include <iostream>\n#include <coroutine>\nusing namespace std;\n\n// implement Generator here\n\nint main() {\n    // your code\n    return 0;\n}',
 '1\n2\n3\n4\n5',
 3,
 'A coroutine returns a Generator type with promise_type.', 'Una corrutina retorna un tipo Generator con promise_type.',
 'Use co_yield to suspend and yield a value.', 'Usa co_yield para suspender y producir un valor.',
 'promise_type needs yield_value, get_return_object, initial/final_suspend.', 'promise_type necesita yield_value, get_return_object, initial/final_suspend.',
 100, 10, now()),

(gen_random_uuid(),
 'Lock-Free Stack', 'Pila Sin Bloqueo',
 'Implement a lock-free stack using std::atomic and CAS (compare_exchange_weak). Push 1,2,3 and pop all, printing values.',
 'Implementa una pila sin bloqueo usando std::atomic y CAS (compare_exchange_weak). Empuja 1,2,3 y desapila todos, imprimiendo valores.',
 'cpp', 5, 'challenges',
 '#include <iostream>\n#include <atomic>\nusing namespace std;\n\n// implement LockFreeStack here\n\nint main() {\n    // your code\n    return 0;\n}',
 '3\n2\n1',
 3,
 'Use atomic<Node*> head with CAS for thread-safe push/pop.', 'Usa atomic<Node*> head con CAS para push/pop seguro entre hilos.',
 'Push: create node, set node->next=head, CAS(head, node->next, node).', 'Push: crea nodo, establece node->next=head, CAS(head, node->next, node).',
 'Pop: old_head=head, CAS(head, old_head, old_head->next).', 'Pop: old_head=head, CAS(head, old_head, old_head->next).',
 100, 10, now())

ON CONFLICT DO NOTHING;

COMMIT;
