-- 050_exercises_typescript.sql
-- 100 TypeScript exercises, bilingual EN+ES
-- Distribution: diff1=25, diff2=25, diff3=25, diff4=15, diff5=10
-- Points: 10/20/30/50/100 | Penalty: 3/3/5/10/10
-- Focus: types, interfaces, generics, enums, union types, type guards,
--        utility types, mapped types, conditional types, decorators

BEGIN;

INSERT INTO exercises (
  id, title_en, title_es,
  description_en, description_es,
  language, difficulty, category,
  starter_code, expected_output,
  hint_count,
  hint_1_en, hint_1_es,
  hint_2_en, hint_2_es,
  hint_3_en, hint_3_es,
  points, hints_used_penalty,
  created_at
) VALUES

-- ============================================================
-- DIFFICULTY 1 — 25 exercises (points=10, penalty=3)
-- ============================================================

-- 1. basics
(gen_random_uuid(),
 'Hello TypeScript', 'Hola TypeScript',
 'Declare a string variable named greeting with the value "Hello, TypeScript!" and print it.',
 'Declara una variable string llamada greeting con el valor "Hello, TypeScript!" e imprímela.',
 'typescript', 1, 'basics',
 'const greeting: string = ___;\nconsole.log(greeting);',
 'Hello, TypeScript!',
 3,
 'Use the string type annotation after the variable name.', 'Usa la anotación de tipo string después del nombre de la variable.',
 'Assign a string literal with double quotes.', 'Asigna un literal de cadena con comillas dobles.',
 'const greeting: string = "Hello, TypeScript!";', 'const greeting: string = "Hello, TypeScript!";',
 10, 3, now()),

-- 2. basics
(gen_random_uuid(),
 'Number Type', 'Tipo Número',
 'Declare a number variable named age with the value 25 and print it.',
 'Declara una variable number llamada age con el valor 25 e imprímela.',
 'typescript', 1, 'basics',
 'const age: ___ = 25;\nconsole.log(age);',
 '25',
 3,
 'Use the number type annotation.', 'Usa la anotación de tipo number.',
 'TypeScript uses "number" for all numeric values.', 'TypeScript usa "number" para todos los valores numéricos.',
 'const age: number = 25;', 'const age: number = 25;',
 10, 3, now()),

-- 3. basics
(gen_random_uuid(),
 'Boolean Type', 'Tipo Booleano',
 'Declare a boolean variable named isActive with the value true and print it.',
 'Declara una variable boolean llamada isActive con el valor true e imprímela.',
 'typescript', 1, 'basics',
 'const isActive: ___ = true;\nconsole.log(isActive);',
 'true',
 3,
 'Use the boolean type annotation.', 'Usa la anotación de tipo boolean.',
 'Boolean values are true or false without quotes.', 'Los valores booleanos son true o false sin comillas.',
 'const isActive: boolean = true;', 'const isActive: boolean = true;',
 10, 3, now()),

-- 4. basics
(gen_random_uuid(),
 'Type Inference', 'Inferencia de Tipos',
 'Let TypeScript infer the type: declare a variable score assigned 100, then print it.',
 'Deja que TypeScript infiera el tipo: declara una variable score asignada a 100 e imprímela.',
 'typescript', 1, 'basics',
 'const score = ___;\nconsole.log(score);',
 '100',
 3,
 'TypeScript infers the type from the assigned value.', 'TypeScript infiere el tipo a partir del valor asignado.',
 'No need to write ": number" — TypeScript figures it out.', 'No es necesario escribir ": number" — TypeScript lo deduce.',
 'const score = 100;', 'const score = 100;',
 10, 3, now()),

-- 5. basics
(gen_random_uuid(),
 'Array of Numbers', 'Array de Números',
 'Declare a typed array of numbers named scores containing [10, 20, 30] and print its length.',
 'Declara un array tipado de números llamado scores con [10, 20, 30] e imprime su longitud.',
 'typescript', 1, 'arrays',
 'const scores: number[] = [10, 20, 30];\nconsole.log(scores.___);',
 '3',
 3,
 'Access the length property of the array.', 'Accede a la propiedad length del array.',
 'number[] declares a typed array of numbers.', 'number[] declara un array tipado de números.',
 'console.log(scores.length);', 'console.log(scores.length);',
 10, 3, now()),

-- 6. arrays
(gen_random_uuid(),
 'Array of Strings', 'Array de Cadenas',
 'Declare a string array named fruits with ["apple", "banana", "cherry"] and print the first element.',
 'Declara un array de strings llamado fruits con ["apple", "banana", "cherry"] e imprime el primer elemento.',
 'typescript', 1, 'arrays',
 'const fruits: string[] = ["apple", "banana", "cherry"];\nconsole.log(fruits[___]);',
 'apple',
 3,
 'Arrays are zero-indexed in TypeScript.', 'Los arrays son de índice cero en TypeScript.',
 'The first element is at index 0.', 'El primer elemento está en el índice 0.',
 'console.log(fruits[0]);', 'console.log(fruits[0]);',
 10, 3, now()),

-- 7. strings
(gen_random_uuid(),
 'String Concatenation', 'Concatenación de Strings',
 'Declare firstName = "John" and lastName = "Doe" as typed strings, then print the full name separated by a space.',
 'Declara firstName = "John" y lastName = "Doe" como strings tipados, luego imprime el nombre completo separado por un espacio.',
 'typescript', 1, 'strings',
 'const firstName: string = "John";\nconst lastName: string = "Doe";\nconsole.log(___ + " " + ___);',
 'John Doe',
 3,
 'Use + to concatenate strings.', 'Usa + para concatenar strings.',
 'Put a space string " " between the two names.', 'Pon un espacio " " entre los dos nombres.',
 'console.log(firstName + " " + lastName);', 'console.log(firstName + " " + lastName);',
 10, 3, now()),

-- 8. strings
(gen_random_uuid(),
 'Template Literal', 'Template Literal',
 'Use a template literal to print "My name is Alice and I am 30 years old." using variables name and age.',
 'Usa un template literal para imprimir "My name is Alice and I am 30 years old." usando variables name y age.',
 'typescript', 1, 'strings',
 'const name: string = "Alice";\nconst age: number = 30;\nconsole.log(`___`);',
 'My name is Alice and I am 30 years old.',
 3,
 'Template literals use backticks ` instead of quotes.', 'Los template literals usan comillas invertidas ` en lugar de comillas.',
 'Embed variables with ${variableName} syntax.', 'Incrusta variables con la sintaxis ${variableName}.',
 '`My name is ${name} and I am ${age} years old.`', '`My name is ${name} and I am ${age} years old.`',
 10, 3, now()),

-- 9. functions
(gen_random_uuid(),
 'Typed Function', 'Función Tipada',
 'Write a function add that takes two number parameters and returns their sum. Print add(3, 4).',
 'Escribe una función add que tome dos parámetros number y devuelva su suma. Imprime add(3, 4).',
 'typescript', 1, 'functions',
 'function add(a: number, b: ___): number {\n  return a + b;\n}\nconsole.log(add(3, 4));',
 '7',
 3,
 'Both parameters need the number type annotation.', 'Ambos parámetros necesitan la anotación de tipo number.',
 'The return type number goes after the closing parenthesis.', 'El tipo de retorno number va después del paréntesis de cierre.',
 'function add(a: number, b: number): number { return a + b; }', 'function add(a: number, b: number): number { return a + b; }',
 10, 3, now()),

-- 10. functions
(gen_random_uuid(),
 'Void Return Type', 'Tipo de Retorno Void',
 'Write a function greet that takes a string name parameter, returns void, and prints "Hello, <name>!".',
 'Escribe una función greet que tome un parámetro string name, devuelva void e imprima "Hello, <name>!".',
 'typescript', 1, 'functions',
 'function greet(name: string): ___ {\n  console.log(`Hello, ${name}!`);\n}\ngreet("World");',
 'Hello, World!',
 3,
 'Functions that do not return a value use the void return type.', 'Las funciones que no devuelven un valor usan el tipo de retorno void.',
 'void means the function performs an action but returns nothing.', 'void significa que la función realiza una acción pero no devuelve nada.',
 'function greet(name: string): void { ... }', 'function greet(name: string): void { ... }',
 10, 3, now()),

-- 11. objects
(gen_random_uuid(),
 'Object Type Annotation', 'Anotación de Tipo de Objeto',
 'Declare a variable person with an inline object type containing name: string and age: number. Print person.name.',
 'Declara una variable person con un tipo de objeto en línea que contenga name: string y age: number. Imprime person.name.',
 'typescript', 1, 'objects',
 'const person: { name: string; age: number } = { name: "Bob", age: 25 };\nconsole.log(person.___);',
 'Bob',
 3,
 'Access object properties with dot notation.', 'Accede a las propiedades del objeto con notación de punto.',
 'person.name retrieves the name property.', 'person.name recupera la propiedad name.',
 'console.log(person.name);', 'console.log(person.name);',
 10, 3, now()),

-- 12. basics
(gen_random_uuid(),
 'Any Type', 'Tipo Any',
 'Declare a variable data with type any, assign it the number 42, then reassign it to the string "hello" and print it.',
 'Declara una variable data con tipo any, asígnale el número 42, luego reasígnala al string "hello" e imprímela.',
 'typescript', 1, 'basics',
 'let data: any = 42;\ndata = "hello";\nconsole.log(data);',
 'hello',
 3,
 'The any type disables type checking for that variable.', 'El tipo any deshabilita la verificación de tipos para esa variable.',
 'any allows reassigning to values of different types.', 'any permite reasignar a valores de diferentes tipos.',
 'let data: any = 42; data = "hello";', 'let data: any = 42; data = "hello";',
 10, 3, now()),

-- 13. basics
(gen_random_uuid(),
 'Const vs Let Types', 'Tipos Const vs Let',
 'Declare a const PI: number = 3.14 and a let counter: number = 0. Increment counter by 1 and print both.',
 'Declara un const PI: number = 3.14 y un let counter: number = 0. Incrementa counter en 1 e imprime ambos.',
 'typescript', 1, 'basics',
 'const PI: number = 3.14;\nlet counter: number = 0;\ncounter___;\nconsole.log(PI);\nconsole.log(counter);',
 '3.14\n1',
 3,
 'Use ++ to increment a number variable by 1.', 'Usa ++ para incrementar una variable numérica en 1.',
 'counter++ increments counter from 0 to 1.', 'counter++ incrementa counter de 0 a 1.',
 'counter++;', 'counter++;',
 10, 3, now()),

-- 14. math
(gen_random_uuid(),
 'Math Operations', 'Operaciones Matemáticas',
 'Declare x: number = 10 and y: number = 3. Print the result of integer division (Math.floor(x / y)).',
 'Declara x: number = 10 e y: number = 3. Imprime el resultado de la división entera (Math.floor(x / y)).',
 'typescript', 1, 'math',
 'const x: number = 10;\nconst y: number = 3;\nconsole.log(Math.floor(___ / ___));',
 '3',
 3,
 'Math.floor rounds down to the nearest integer.', 'Math.floor redondea hacia abajo al entero más cercano.',
 'Pass the division x / y inside Math.floor().', 'Pasa la división x / y dentro de Math.floor().',
 'Math.floor(x / y)', 'Math.floor(x / y)',
 10, 3, now()),

-- 15. strings
(gen_random_uuid(),
 'String Length', 'Longitud de String',
 'Declare a string message = "TypeScript" and print its character count.',
 'Declara un string message = "TypeScript" e imprime su cantidad de caracteres.',
 'typescript', 1, 'strings',
 'const message: string = "TypeScript";\nconsole.log(message.___);',
 '10',
 3,
 'Use the .length property to get the character count.', 'Usa la propiedad .length para obtener el conteo de caracteres.',
 '"TypeScript" has 10 characters.', '"TypeScript" tiene 10 caracteres.',
 'message.length', 'message.length',
 10, 3, now()),

-- 16. arrays
(gen_random_uuid(),
 'Push to Array', 'Agregar al Array',
 'Declare a number array nums = [1, 2, 3]. Push the value 4 and print the array.',
 'Declara un array de números nums = [1, 2, 3]. Agrega el valor 4 e imprime el array.',
 'typescript', 1, 'arrays',
 'const nums: number[] = [1, 2, 3];\nnums.___(4);\nconsole.log(nums);',
 '[ 1, 2, 3, 4 ]',
 3,
 'Use the .push() method to add an element to the end.', 'Usa el método .push() para agregar un elemento al final.',
 'nums.push(4) adds 4 at the end of the array.', 'nums.push(4) agrega el 4 al final del array.',
 'nums.push(4);', 'nums.push(4);',
 10, 3, now()),

-- 17. functions
(gen_random_uuid(),
 'Arrow Function', 'Función Flecha',
 'Write a typed arrow function double that takes a number n and returns n * 2. Print double(5).',
 'Escribe una función flecha tipada double que tome un número n y devuelva n * 2. Imprime double(5).',
 'typescript', 1, 'functions',
 'const double = (n: ___): number => n * 2;\nconsole.log(double(5));',
 '10',
 3,
 'Arrow functions use => instead of the function keyword.', 'Las funciones flecha usan => en lugar de la palabra clave function.',
 'The parameter n needs a number type annotation.', 'El parámetro n necesita una anotación de tipo number.',
 'const double = (n: number): number => n * 2;', 'const double = (n: number): number => n * 2;',
 10, 3, now()),

-- 18. objects
(gen_random_uuid(),
 'Optional Property', 'Propiedad Opcional',
 'Declare an object car with type { brand: string; year?: number }. Set brand to "Toyota" with no year. Print car.brand.',
 'Declara un objeto car con tipo { brand: string; year?: number }. Establece brand a "Toyota" sin year. Imprime car.brand.',
 'typescript', 1, 'objects',
 'const car: { brand: string; year?: number } = { brand: "Toyota" };\nconsole.log(car.___);',
 'Toyota',
 3,
 'The ? makes the property optional — it can be omitted.', 'El ? hace que la propiedad sea opcional — puede omitirse.',
 'Access brand with car.brand.', 'Accede a brand con car.brand.',
 'console.log(car.brand);', 'console.log(car.brand);',
 10, 3, now()),

-- 19. basics
(gen_random_uuid(),
 'Null and Undefined', 'Null y Undefined',
 'Declare a variable value with type string | null and assign it null. Print the result of value === null.',
 'Declara una variable value con tipo string | null y asígnale null. Imprime el resultado de value === null.',
 'typescript', 1, 'basics',
 'const value: string | null = null;\nconsole.log(value === ___);',
 'true',
 3,
 'null is a valid value for a string | null type.', 'null es un valor válido para un tipo string | null.',
 'Comparing null === null returns true.', 'Comparar null === null devuelve true.',
 'console.log(value === null);', 'console.log(value === null);',
 10, 3, now()),

-- 20. math
(gen_random_uuid(),
 'Modulo Operator', 'Operador Módulo',
 'Print whether 17 is odd by computing 17 % 2 and checking if it equals 1.',
 'Imprime si 17 es impar calculando 17 % 2 y verificando si es igual a 1.',
 'typescript', 1, 'math',
 'const n: number = 17;\nconsole.log(n % 2 === ___);',
 'true',
 3,
 'The % operator gives the remainder of division.', 'El operador % da el resto de la división.',
 '17 divided by 2 has remainder 1, so it is odd.', '17 dividido por 2 tiene resto 1, por lo que es impar.',
 'n % 2 === 1', 'n % 2 === 1',
 10, 3, now()),

-- 21. strings
(gen_random_uuid(),
 'String toUpperCase', 'String toUpperCase',
 'Declare word = "typescript" and print it converted to uppercase.',
 'Declara word = "typescript" e imprímela convertida a mayúsculas.',
 'typescript', 1, 'strings',
 'const word: string = "typescript";\nconsole.log(word.___());',
 'TYPESCRIPT',
 3,
 'Strings have a built-in method to convert to uppercase.', 'Los strings tienen un método integrado para convertir a mayúsculas.',
 'Use .toUpperCase() method.', 'Usa el método .toUpperCase().',
 'word.toUpperCase()', 'word.toUpperCase()',
 10, 3, now()),

-- 22. arrays
(gen_random_uuid(),
 'Array includes', 'Array includes',
 'Declare colors: string[] = ["red", "green", "blue"]. Print whether "green" is in the array.',
 'Declara colors: string[] = ["red", "green", "blue"]. Imprime si "green" está en el array.',
 'typescript', 1, 'arrays',
 'const colors: string[] = ["red", "green", "blue"];\nconsole.log(colors.___("green"));',
 'true',
 3,
 'Use the .includes() method to check for membership.', 'Usa el método .includes() para verificar la membresía.',
 'includes returns true if the value is found.', 'includes devuelve true si se encuentra el valor.',
 'colors.includes("green")', 'colors.includes("green")',
 10, 3, now()),

-- 23. functions
(gen_random_uuid(),
 'Default Parameter', 'Parámetro por Defecto',
 'Write a function greetUser with parameter name: string = "Guest" that prints "Welcome, <name>!". Call it with no argument.',
 'Escribe una función greetUser con parámetro name: string = "Guest" que imprima "Welcome, <name>!". Llámala sin argumento.',
 'typescript', 1, 'functions',
 'function greetUser(name: string = ___): void {\n  console.log(`Welcome, ${name}!`);\n}\ngreetUser();',
 'Welcome, Guest!',
 3,
 'Default parameters use = after the type annotation.', 'Los parámetros por defecto usan = después de la anotación de tipo.',
 'When called with no argument, the default "Guest" is used.', 'Cuando se llama sin argumento, se usa el valor por defecto "Guest".',
 'name: string = "Guest"', 'name: string = "Guest"',
 10, 3, now()),

-- 24. basics
(gen_random_uuid(),
 'Type Assertion', 'Aserción de Tipo',
 'Declare a variable val: any = "Hello". Use a type assertion to treat it as a string and print its .length.',
 'Declara una variable val: any = "Hello". Usa una aserción de tipo para tratarla como string e imprime su .length.',
 'typescript', 1, 'basics',
 'const val: any = "Hello";\nconsole.log((val as ___).length);',
 '5',
 3,
 'Use the "as" keyword for type assertions.', 'Usa la palabra clave "as" para las aserciones de tipo.',
 '(val as string) tells TypeScript to treat val as a string.', '(val as string) le dice a TypeScript que trate val como un string.',
 '(val as string).length', '(val as string).length',
 10, 3, now()),

-- 25. math
(gen_random_uuid(),
 'Power of Two', 'Potencia de Dos',
 'Use Math.pow to calculate 2 to the power of 8 and print the result.',
 'Usa Math.pow para calcular 2 elevado a la potencia de 8 e imprime el resultado.',
 'typescript', 1, 'math',
 'console.log(Math.pow(___, ___));',
 '256',
 3,
 'Math.pow(base, exponent) computes the power.', 'Math.pow(base, exponente) calcula la potencia.',
 'Math.pow(2, 8) = 256.', 'Math.pow(2, 8) = 256.',
 'Math.pow(2, 8)', 'Math.pow(2, 8)',
 10, 3, now()),

-- ============================================================
-- DIFFICULTY 2 — 25 exercises (points=20, penalty=3)
-- ============================================================

-- 26. basics (interfaces)
(gen_random_uuid(),
 'Basic Interface', 'Interfaz Básica',
 'Define an interface User with properties name: string and age: number. Create a variable u of type User and print u.name.',
 'Define una interfaz User con propiedades name: string y age: number. Crea una variable u de tipo User e imprime u.name.',
 'typescript', 2, 'objects',
 'interface User {\n  name: string;\n  age: ___;\n}\nconst u: User = { name: "Alice", age: 30 };\nconsole.log(u.name);',
 'Alice',
 3,
 'Interfaces define the shape of an object.', 'Las interfaces definen la forma de un objeto.',
 'Each property needs a type annotation inside the interface body.', 'Cada propiedad necesita una anotación de tipo dentro del cuerpo de la interfaz.',
 'age: number;', 'age: number;',
 20, 3, now()),

-- 27. objects (interfaces)
(gen_random_uuid(),
 'Interface with Optional Property', 'Interfaz con Propiedad Opcional',
 'Define an interface Product with name: string, price: number, and optional description?: string. Create a product without description and print its price.',
 'Define una interfaz Product con name: string, price: number y description?: string opcional. Crea un producto sin description e imprime su price.',
 'typescript', 2, 'objects',
 'interface Product {\n  name: string;\n  price: number;\n  description?: string;\n}\nconst p: Product = { name: "Book", price: 15 };\nconsole.log(p.___);',
 '15',
 3,
 'The ? after a property name makes it optional.', 'El ? después del nombre de una propiedad la hace opcional.',
 'You can omit optional properties when creating the object.', 'Puedes omitir las propiedades opcionales al crear el objeto.',
 'console.log(p.price);', 'console.log(p.price);',
 20, 3, now()),

-- 28. basics (enums)
(gen_random_uuid(),
 'Basic Enum', 'Enum Básico',
 'Define a numeric enum Direction with values Up, Down, Left, Right. Print the value of Direction.Up.',
 'Define un enum numérico Direction con valores Up, Down, Left, Right. Imprime el valor de Direction.Up.',
 'typescript', 2, 'basics',
 'enum Direction {\n  Up,\n  Down,\n  Left,\n  Right\n}\nconsole.log(Direction.___);',
 '0',
 3,
 'Numeric enums start at 0 by default.', 'Los enums numéricos comienzan en 0 por defecto.',
 'Direction.Up has the value 0, Direction.Down = 1, etc.', 'Direction.Up tiene el valor 0, Direction.Down = 1, etc.',
 'Direction.Up', 'Direction.Up',
 20, 3, now()),

-- 29. basics (enums)
(gen_random_uuid(),
 'String Enum', 'Enum de String',
 'Define a string enum Status with values Active = "ACTIVE" and Inactive = "INACTIVE". Print Status.Active.',
 'Define un enum de string Status con valores Active = "ACTIVE" e Inactive = "INACTIVE". Imprime Status.Active.',
 'typescript', 2, 'basics',
 'enum Status {\n  Active = "ACTIVE",\n  Inactive = ___\n}\nconsole.log(Status.Active);',
 'ACTIVE',
 3,
 'String enums require explicit string values for each member.', 'Los enums de string requieren valores de string explícitos para cada miembro.',
 'Set Inactive = "INACTIVE" as the string value.', 'Establece Inactive = "INACTIVE" como valor de string.',
 'Inactive = "INACTIVE"', 'Inactive = "INACTIVE"',
 20, 3, now()),

-- 30. basics (union types)
(gen_random_uuid(),
 'Union Type', 'Tipo Unión',
 'Declare a function printId that accepts id: number | string and prints it. Call with printId(101) and printId("E202").',
 'Declara una función printId que acepte id: number | string e imprímela. Llama con printId(101) y printId("E202").',
 'typescript', 2, 'functions',
 'function printId(id: number | ___): void {\n  console.log(id);\n}\nprintId(101);\nprintId("E202");',
 '101\nE202',
 3,
 'Use the | operator to create a union type.', 'Usa el operador | para crear un tipo unión.',
 'number | string means the parameter can be either type.', 'number | string significa que el parámetro puede ser de cualquiera de los dos tipos.',
 'id: number | string', 'id: number | string',
 20, 3, now()),

-- 31. functions (generics)
(gen_random_uuid(),
 'Generic Identity Function', 'Función Genérica de Identidad',
 'Write a generic function identity<T> that takes a value of type T and returns it unchanged. Print identity<string>("hello") and identity<number>(42).',
 'Escribe una función genérica identity<T> que tome un valor de tipo T y lo devuelva sin cambios. Imprime identity<string>("hello") e identity<number>(42).',
 'typescript', 2, 'functions',
 'function identity<T>(value: ___): T {\n  return value;\n}\nconsole.log(identity<string>("hello"));\nconsole.log(identity<number>(42));',
 'hello\n42',
 3,
 'Generic functions use a type parameter <T> declared after the function name.', 'Las funciones genéricas usan un parámetro de tipo <T> declarado después del nombre de la función.',
 'The parameter type and return type both use T.', 'El tipo del parámetro y el tipo de retorno usan T.',
 'function identity<T>(value: T): T', 'function identity<T>(value: T): T',
 20, 3, now()),

-- 32. arrays (generics)
(gen_random_uuid(),
 'Generic Array Type', 'Tipo Array Genérico',
 'Declare a variable list using the generic Array<number> syntax with values [5, 10, 15]. Print list[1].',
 'Declara una variable list usando la sintaxis genérica Array<number> con valores [5, 10, 15]. Imprime list[1].',
 'typescript', 2, 'arrays',
 'const list: Array<___> = [5, 10, 15];\nconsole.log(list[1]);',
 '10',
 3,
 'Array<number> is equivalent to number[].', 'Array<number> es equivalente a number[].',
 'list[1] accesses the element at index 1 (zero-based).', 'list[1] accede al elemento en el índice 1 (base cero).',
 'Array<number>', 'Array<number>',
 20, 3, now()),

-- 33. strings
(gen_random_uuid(),
 'String Split and Join', 'Split y Join de String',
 'Split "a,b,c,d" by comma into an array, then join the array with " - " and print the result.',
 'Divide "a,b,c,d" por coma en un array, luego une el array con " - " e imprime el resultado.',
 'typescript', 2, 'strings',
 'const parts: string[] = "a,b,c,d".split(",");\nconsole.log(parts.join("___"));',
 'a - b - c - d',
 3,
 'split() breaks a string into an array; join() combines an array into a string.', 'split() divide un string en un array; join() combina un array en un string.',
 'Pass " - " as the separator to join().', 'Pasa " - " como separador a join().',
 'parts.join(" - ")', 'parts.join(" - ")',
 20, 3, now()),

-- 34. arrays
(gen_random_uuid(),
 'Array map', 'Array map',
 'Given nums: number[] = [1, 2, 3, 4], use .map() to create a new array where each value is squared. Print the result.',
 'Dado nums: number[] = [1, 2, 3, 4], usa .map() para crear un nuevo array donde cada valor esté al cuadrado. Imprime el resultado.',
 'typescript', 2, 'arrays',
 'const nums: number[] = [1, 2, 3, 4];\nconst squared = nums.map(n => n ___ n);\nconsole.log(squared);',
 '[ 1, 4, 9, 16 ]',
 3,
 'Use * to multiply a number by itself.', 'Usa * para multiplicar un número por sí mismo.',
 'n * n gives the square of n.', 'n * n da el cuadrado de n.',
 'n => n * n', 'n => n * n',
 20, 3, now()),

-- 35. arrays
(gen_random_uuid(),
 'Array filter', 'Array filter',
 'Given numbers: number[] = [1,2,3,4,5,6], use .filter() to keep only even numbers and print the result.',
 'Dado numbers: number[] = [1,2,3,4,5,6], usa .filter() para mantener solo los números pares e imprime el resultado.',
 'typescript', 2, 'arrays',
 'const numbers: number[] = [1,2,3,4,5,6];\nconst evens = numbers.filter(n => n % 2 === ___);\nconsole.log(evens);',
 '[ 2, 4, 6 ]',
 3,
 'A number is even if n % 2 equals 0.', 'Un número es par si n % 2 es igual a 0.',
 'filter() keeps elements for which the callback returns true.', 'filter() mantiene los elementos para los cuales el callback devuelve true.',
 'n % 2 === 0', 'n % 2 === 0',
 20, 3, now()),

-- 36. functions
(gen_random_uuid(),
 'Rest Parameters', 'Parámetros Rest',
 'Write a function sum(...nums: number[]): number that returns the total of all arguments. Print sum(1, 2, 3, 4, 5).',
 'Escribe una función sum(...nums: number[]): number que devuelva el total de todos los argumentos. Imprime sum(1, 2, 3, 4, 5).',
 'typescript', 2, 'functions',
 'function sum(___nums: number[]): number {\n  return nums.reduce((acc, n) => acc + n, 0);\n}\nconsole.log(sum(1, 2, 3, 4, 5));',
 '15',
 3,
 'Rest parameters use ... before the parameter name.', 'Los parámetros rest usan ... antes del nombre del parámetro.',
 '...nums collects all passed arguments into a number array.', '...nums recopila todos los argumentos pasados en un array de números.',
 'function sum(...nums: number[]): number', 'function sum(...nums: number[]): number',
 20, 3, now()),

-- 37. objects
(gen_random_uuid(),
 'Interface Extends', 'Interfaz Extends',
 'Define interface Animal with name: string. Define interface Dog extending Animal with breed: string. Create a Dog and print its name.',
 'Define la interfaz Animal con name: string. Define la interfaz Dog extendiendo Animal con breed: string. Crea un Dog e imprime su name.',
 'typescript', 2, 'objects',
 'interface Animal { name: string; }\ninterface Dog ___ Animal { breed: string; }\nconst d: Dog = { name: "Rex", breed: "Labrador" };\nconsole.log(d.name);',
 'Rex',
 3,
 'Use the extends keyword to inherit from another interface.', 'Usa la palabra clave extends para heredar de otra interfaz.',
 'Dog extends Animal means Dog has all Animal properties plus its own.', 'Dog extends Animal significa que Dog tiene todas las propiedades de Animal más las propias.',
 'interface Dog extends Animal', 'interface Dog extends Animal',
 20, 3, now()),

-- 38. patterns (type alias)
(gen_random_uuid(),
 'Type Alias', 'Alias de Tipo',
 'Create a type alias Point for { x: number; y: number }. Declare a variable p: Point = { x: 3, y: 4 } and print p.x.',
 'Crea un alias de tipo Point para { x: number; y: number }. Declara una variable p: Point = { x: 3, y: 4 } e imprime p.x.',
 'typescript', 2, 'patterns',
 'type Point = { x: number; y: ___; };\nconst p: Point = { x: 3, y: 4 };\nconsole.log(p.x);',
 '3',
 3,
 'Use the type keyword to create a type alias.', 'Usa la palabra clave type para crear un alias de tipo.',
 'type Point = { ... } names the object shape for reuse.', 'type Point = { ... } nombra la forma del objeto para reutilizarla.',
 'type Point = { x: number; y: number; }', 'type Point = { x: number; y: number; }',
 20, 3, now()),

-- 39. algorithms
(gen_random_uuid(),
 'FizzBuzz Typed', 'FizzBuzz Tipado',
 'Write a typed function fizzBuzz(n: number): string that returns "Fizz" if divisible by 3, "Buzz" if by 5, "FizzBuzz" if both, else the number as string. Print fizzBuzz(15).',
 'Escribe una función tipada fizzBuzz(n: number): string que devuelva "Fizz" si es divisible por 3, "Buzz" si lo es por 5, "FizzBuzz" si ambos, o el número como string. Imprime fizzBuzz(15).',
 'typescript', 2, 'algorithms',
 'function fizzBuzz(n: number): string {\n  if (n % 15 === 0) return "FizzBuzz";\n  if (n % 3 === 0) return "Fizz";\n  if (n % 5 === 0) return "Buzz";\n  return ___;\n}\nconsole.log(fizzBuzz(15));',
 'FizzBuzz',
 3,
 'Check divisibility by 15 first to catch FizzBuzz cases.', 'Verifica la divisibilidad por 15 primero para capturar los casos FizzBuzz.',
 'Return the number converted to a string with String(n) or n.toString().', 'Devuelve el número convertido a string con String(n) o n.toString().',
 'return String(n);', 'return String(n);',
 20, 3, now()),

-- 40. algorithms
(gen_random_uuid(),
 'Factorial Typed', 'Factorial Tipado',
 'Write a recursive typed function factorial(n: number): number. Print factorial(5).',
 'Escribe una función tipada recursiva factorial(n: number): number. Imprime factorial(5).',
 'typescript', 2, 'algorithms',
 'function factorial(n: number): number {\n  if (n <= 1) return 1;\n  return n * factorial(n - ___);\n}\nconsole.log(factorial(5));',
 '120',
 3,
 'The base case returns 1 when n <= 1.', 'El caso base devuelve 1 cuando n <= 1.',
 'Each recursive call reduces n by 1.', 'Cada llamada recursiva reduce n en 1.',
 'factorial(n - 1)', 'factorial(n - 1)',
 20, 3, now()),

-- 41. objects
(gen_random_uuid(),
 'Readonly Property', 'Propiedad Readonly',
 'Define an interface Config with a readonly property apiUrl: string. Create a config object and print apiUrl.',
 'Define una interfaz Config con una propiedad readonly apiUrl: string. Crea un objeto config e imprime apiUrl.',
 'typescript', 2, 'objects',
 'interface Config {\n  readonly apiUrl: string;\n}\nconst config: Config = { apiUrl: "https://api.example.com" };\nconsole.log(config.___);',
 'https://api.example.com',
 3,
 'readonly prevents reassignment of that property after initialization.', 'readonly evita la reasignación de esa propiedad después de la inicialización.',
 'Access readonly properties normally with dot notation.', 'Accede a las propiedades readonly normalmente con notación de punto.',
 'config.apiUrl', 'config.apiUrl',
 20, 3, now()),

-- 42. strings
(gen_random_uuid(),
 'String Slice', 'String Slice',
 'Given text = "Hello, World!", use .slice() to extract "World" (characters 7-12) and print it.',
 'Dado text = "Hello, World!", usa .slice() para extraer "World" (caracteres 7-12) e imprímelo.',
 'typescript', 2, 'strings',
 'const text: string = "Hello, World!";\nconsole.log(text.slice(___, ___));',
 'World',
 3,
 'slice(start, end) extracts characters from index start up to (not including) end.', 'slice(start, end) extrae caracteres desde el índice start hasta (sin incluir) end.',
 '"World" starts at index 7 and ends before index 12.', '"World" comienza en el índice 7 y termina antes del índice 12.',
 'text.slice(7, 12)', 'text.slice(7, 12)',
 20, 3, now()),

-- 43. math
(gen_random_uuid(),
 'Min and Max', 'Mínimo y Máximo',
 'Print the minimum and maximum of [3, 1, 4, 1, 5, 9, 2, 6] using Math.min and Math.max with the spread operator.',
 'Imprime el mínimo y máximo de [3, 1, 4, 1, 5, 9, 2, 6] usando Math.min y Math.max con el operador spread.',
 'typescript', 2, 'math',
 'const vals: number[] = [3, 1, 4, 1, 5, 9, 2, 6];\nconsole.log(Math.min(___vals));\nconsole.log(Math.max(...vals));',
 '1\n9',
 3,
 'Use the spread operator ... to expand the array into individual arguments.', 'Usa el operador spread ... para expandir el array en argumentos individuales.',
 'Math.min(...vals) passes all array elements as separate arguments.', 'Math.min(...vals) pasa todos los elementos del array como argumentos separados.',
 'Math.min(...vals)', 'Math.min(...vals)',
 20, 3, now()),

-- 44. patterns (destructuring)
(gen_random_uuid(),
 'Object Destructuring', 'Desestructuración de Objeto',
 'Destructure name and age from a typed object { name: "Eve", age: 28 } and print them on separate lines.',
 'Desestructura name y age de un objeto tipado { name: "Eve", age: 28 } e imprímelos en líneas separadas.',
 'typescript', 2, 'patterns',
 'const { ___, ___ }: { name: string; age: number } = { name: "Eve", age: 28 };\nconsole.log(name);\nconsole.log(age);',
 'Eve\n28',
 3,
 'Destructuring pulls named properties into local variables.', 'La desestructuración extrae propiedades con nombre en variables locales.',
 'const { name, age } = object; creates two variables.', 'const { name, age } = objeto; crea dos variables.',
 'const { name, age } = ...', 'const { name, age } = ...',
 20, 3, now()),

-- 45. patterns (spread)
(gen_random_uuid(),
 'Array Spread', 'Spread de Array',
 'Merge arrays [1, 2, 3] and [4, 5, 6] into one array using the spread operator and print it.',
 'Une los arrays [1, 2, 3] y [4, 5, 6] en un solo array usando el operador spread e imprímelo.',
 'typescript', 2, 'patterns',
 'const a: number[] = [1, 2, 3];\nconst b: number[] = [4, 5, 6];\nconst merged = [___a, ...b];\nconsole.log(merged);',
 '[ 1, 2, 3, 4, 5, 6 ]',
 3,
 'The spread operator ... expands an array in-place.', 'El operador spread ... expande un array en su lugar.',
 '[...a, ...b] creates a new array with all elements from both arrays.', '[...a, ...b] crea un nuevo array con todos los elementos de ambos arrays.',
 '[...a, ...b]', '[...a, ...b]',
 20, 3, now()),

-- 46. data_structures
(gen_random_uuid(),
 'Typed Tuple', 'Tupla Tipada',
 'Declare a tuple person: [string, number] = ["Alice", 30] and print the second element.',
 'Declara una tupla person: [string, number] = ["Alice", 30] e imprime el segundo elemento.',
 'typescript', 2, 'data_structures',
 'const person: [string, ___] = ["Alice", 30];\nconsole.log(person[1]);',
 '30',
 3,
 'Tuples are fixed-length arrays where each position has a specific type.', 'Las tuplas son arrays de longitud fija donde cada posición tiene un tipo específico.',
 '[string, number] means index 0 is a string, index 1 is a number.', '[string, number] significa que el índice 0 es un string y el índice 1 es un número.',
 '[string, number]', '[string, number]',
 20, 3, now()),

-- 47. patterns
(gen_random_uuid(),
 'Nullish Coalescing', 'Coalescencia Nula',
 'Use the nullish coalescing operator ?? to print "default" when the value is null.',
 'Usa el operador de coalescencia nula ?? para imprimir "default" cuando el valor es null.',
 'typescript', 2, 'patterns',
 'const value: string | null = null;\nconsole.log(value ___ "default");',
 'default',
 3,
 'The ?? operator returns the right side when the left side is null or undefined.', 'El operador ?? devuelve el lado derecho cuando el lado izquierdo es null o undefined.',
 'value ?? "default" evaluates to "default" because value is null.', 'value ?? "default" evalúa a "default" porque value es null.',
 'value ?? "default"', 'value ?? "default"',
 20, 3, now()),

-- 48. patterns
(gen_random_uuid(),
 'Optional Chaining', 'Encadenamiento Opcional',
 'Given user: { address?: { city: string } } = {}, safely access user.address.city using optional chaining and print it.',
 'Dado user: { address?: { city: string } } = {}, accede de forma segura a user.address.city usando encadenamiento opcional e imprímelo.',
 'typescript', 2, 'patterns',
 'const user: { address?: { city: string } } = {};\nconsole.log(user___address___city);',
 'undefined',
 3,
 'Use ?. for optional chaining to safely access nested properties.', 'Usa ?. para el encadenamiento opcional y acceder de forma segura a propiedades anidadas.',
 'If address is undefined, user?.address?.city returns undefined instead of throwing.', 'Si address es undefined, user?.address?.city devuelve undefined en lugar de lanzar un error.',
 'user?.address?.city', 'user?.address?.city',
 20, 3, now()),

-- 49. arrays
(gen_random_uuid(),
 'Array reduce', 'Array reduce',
 'Use .reduce() on [1, 2, 3, 4, 5] to compute the sum and print it.',
 'Usa .reduce() en [1, 2, 3, 4, 5] para calcular la suma e imprímela.',
 'typescript', 2, 'arrays',
 'const nums: number[] = [1, 2, 3, 4, 5];\nconst total = nums.reduce((acc, n) => acc ___ n, 0);\nconsole.log(total);',
 '15',
 3,
 'reduce() accumulates a value by applying a function to each element.', 'reduce() acumula un valor aplicando una función a cada elemento.',
 'acc + n adds each element to the accumulator; start with 0.', 'acc + n suma cada elemento al acumulador; comienza con 0.',
 'acc + n', 'acc + n',
 20, 3, now()),

-- 50. objects
(gen_random_uuid(),
 'Index Signature', 'Firma de Índice',
 'Define an interface StringMap with an index signature [key: string]: string. Create an instance and print a value.',
 'Define una interfaz StringMap con una firma de índice [key: string]: string. Crea una instancia e imprime un valor.',
 'typescript', 2, 'objects',
 'interface StringMap {\n  [key: string]: string;\n}\nconst map: StringMap = { color: "red", size: "large" };\nconsole.log(map["___"]);',
 'red',
 3,
 'An index signature allows any string key with a specified value type.', 'Una firma de índice permite cualquier clave string con un tipo de valor especificado.',
 'Access values with map["key"] or map.key notation.', 'Accede a los valores con map["key"] o notación map.key.',
 'map["color"]', 'map["color"]',
 20, 3, now()),

-- ============================================================
-- DIFFICULTY 3 — 25 exercises (points=30, penalty=5)
-- ============================================================

-- 51. patterns (type guards)
(gen_random_uuid(),
 'typeof Type Guard', 'Type Guard con typeof',
 'Write a function describe(val: string | number): string that returns "string: <val>" or "number: <val>" using a typeof guard. Print describe("hi") and describe(5).',
 'Escribe una función describe(val: string | number): string que devuelva "string: <val>" o "number: <val>" usando un typeof guard. Imprime describe("hi") y describe(5).',
 'typescript', 3, 'patterns',
 'function describe(val: string | number): string {\n  if (typeof val === "___") return `string: ${val}`;\n  return `number: ${val}`;\n}\nconsole.log(describe("hi"));\nconsole.log(describe(5));',
 'string: hi\nnumber: 5',
 3,
 'typeof returns "string" or "number" at runtime.', 'typeof devuelve "string" o "number" en tiempo de ejecución.',
 'Inside the if block TypeScript narrows val to string.', 'Dentro del bloque if TypeScript estrecha val a string.',
 'typeof val === "string"', 'typeof val === "string"',
 30, 5, now()),

-- 52. patterns (type guards)
(gen_random_uuid(),
 'instanceof Type Guard', 'Type Guard con instanceof',
 'Create classes Cat and Dog each with a speak() method. Write a function makeSound(animal: Cat | Dog) that calls the right speak() using instanceof. Print makeSound(new Cat()).',
 'Crea las clases Cat y Dog cada una con un método speak(). Escribe una función makeSound(animal: Cat | Dog) que llame al speak() correcto usando instanceof. Imprime makeSound(new Cat()).',
 'typescript', 3, 'patterns',
 'class Cat { speak(): string { return "Meow"; } }\nclass Dog { speak(): string { return "Woof"; } }\nfunction makeSound(animal: Cat | Dog): void {\n  if (animal ___ Cat) console.log(animal.speak());\n  else console.log(animal.speak());\n}\nmakeSound(new Cat());',
 'Meow',
 3,
 'instanceof checks if an object is an instance of a particular class.', 'instanceof verifica si un objeto es una instancia de una clase particular.',
 'Use "instanceof Cat" to narrow the type to Cat inside the if branch.', 'Usa "instanceof Cat" para estrechar el tipo a Cat dentro de la rama if.',
 'animal instanceof Cat', 'animal instanceof Cat',
 30, 5, now()),

-- 53. generics
(gen_random_uuid(),
 'Generic Stack', 'Pila Genérica',
 'Implement a generic class Stack<T> with push(item: T): void and pop(): T | undefined methods. Push 1 and 2, then pop and print the result.',
 'Implementa una clase genérica Stack<T> con métodos push(item: T): void y pop(): T | undefined. Empuja 1 y 2, luego saca e imprime el resultado.',
 'typescript', 3, 'data_structures',
 'class Stack<T> {\n  private items: T[] = [];\n  push(item: T): void { this.items.push(item); }\n  pop(): T | undefined { return this.items.___(); }\n}\nconst s = new Stack<number>();\ns.push(1); s.push(2);\nconsole.log(s.pop());',
 '2',
 3,
 'pop() removes and returns the last element of an array.', 'pop() elimina y devuelve el último elemento de un array.',
 'this.items.pop() removes the last pushed item.', 'this.items.pop() elimina el último elemento introducido.',
 'this.items.pop()', 'this.items.pop()',
 30, 5, now()),

-- 54. utility types
(gen_random_uuid(),
 'Partial Utility Type', 'Tipo Utilitario Partial',
 'Define interface User { name: string; email: string; age: number }. Write a function updateUser(user: User, updates: Partial<User>): User that merges updates. Print the name after updating email.',
 'Define la interfaz User { name: string; email: string; age: number }. Escribe una función updateUser(user: User, updates: Partial<User>): User que combine updates. Imprime el nombre después de actualizar el email.',
 'typescript', 3, 'objects',
 'interface User { name: string; email: string; age: number; }\nfunction updateUser(user: User, updates: ___<User>): User {\n  return { ...user, ...updates };\n}\nconst u = updateUser({ name: "Alice", email: "a@b.com", age: 25 }, { email: "new@b.com" });\nconsole.log(u.name);',
 'Alice',
 3,
 'Partial<T> makes all properties of T optional.', 'Partial<T> hace que todas las propiedades de T sean opcionales.',
 'This allows passing only the fields you want to update.', 'Esto permite pasar solo los campos que deseas actualizar.',
 'Partial<User>', 'Partial<User>',
 30, 5, now()),

-- 55. utility types
(gen_random_uuid(),
 'Readonly Utility Type', 'Tipo Utilitario Readonly',
 'Define interface Config { host: string; port: number }. Create a Readonly<Config> variable and print its host.',
 'Define la interfaz Config { host: string; port: number }. Crea una variable Readonly<Config> e imprime su host.',
 'typescript', 3, 'objects',
 'interface Config { host: string; port: number; }\nconst cfg: ___<Config> = { host: "localhost", port: 3000 };\nconsole.log(cfg.host);',
 'localhost',
 3,
 'Readonly<T> makes all properties of T immutable.', 'Readonly<T> hace que todas las propiedades de T sean inmutables.',
 'Any attempt to reassign a Readonly property causes a compile error.', 'Cualquier intento de reasignar una propiedad Readonly causa un error de compilación.',
 'Readonly<Config>', 'Readonly<Config>',
 30, 5, now()),

-- 56. utility types
(gen_random_uuid(),
 'Pick Utility Type', 'Tipo Utilitario Pick',
 'Define interface Person { name: string; age: number; email: string }. Use Pick<Person, "name" | "email"> to declare a contact variable and print its email.',
 'Define la interfaz Person { name: string; age: number; email: string }. Usa Pick<Person, "name" | "email"> para declarar una variable contact e imprime su email.',
 'typescript', 3, 'objects',
 'interface Person { name: string; age: number; email: string; }\nconst contact: ___<Person, "name" | "email"> = { name: "Bob", email: "bob@x.com" };\nconsole.log(contact.email);',
 'bob@x.com',
 3,
 'Pick<T, K> creates a type with only the specified properties K from T.', 'Pick<T, K> crea un tipo con solo las propiedades especificadas K de T.',
 'The second argument is a union of property name strings.', 'El segundo argumento es una unión de strings de nombres de propiedades.',
 'Pick<Person, "name" | "email">', 'Pick<Person, "name" | "email">',
 30, 5, now()),

-- 57. utility types
(gen_random_uuid(),
 'Omit Utility Type', 'Tipo Utilitario Omit',
 'Define interface Employee { id: number; name: string; salary: number }. Use Omit to create a type without salary. Print the id of an instance.',
 'Define la interfaz Employee { id: number; name: string; salary: number }. Usa Omit para crear un tipo sin salary. Imprime el id de una instancia.',
 'typescript', 3, 'objects',
 'interface Employee { id: number; name: string; salary: number; }\nconst e: ___<Employee, "salary"> = { id: 1, name: "Carol" };\nconsole.log(e.id);',
 '1',
 3,
 'Omit<T, K> creates a type by removing property K from T.', 'Omit<T, K> crea un tipo eliminando la propiedad K de T.',
 'The second argument is the property name to exclude.', 'El segundo argumento es el nombre de la propiedad a excluir.',
 'Omit<Employee, "salary">', 'Omit<Employee, "salary">',
 30, 5, now()),

-- 58. mapped types
(gen_random_uuid(),
 'Record Utility Type', 'Tipo Utilitario Record',
 'Use Record<string, number> to declare a scores map with { math: 90, science: 85 }. Print scores.math.',
 'Usa Record<string, number> para declarar un mapa scores con { math: 90, science: 85 }. Imprime scores.math.',
 'typescript', 3, 'patterns',
 'const scores: ___<string, number> = { math: 90, science: 85 };\nconsole.log(scores.math);',
 '90',
 3,
 'Record<K, V> creates an object type with keys K and values V.', 'Record<K, V> crea un tipo de objeto con claves K y valores V.',
 'Record<string, number> is like { [key: string]: number }.', 'Record<string, number> es como { [key: string]: number }.',
 'Record<string, number>', 'Record<string, number>',
 30, 5, now()),

-- 59. mapped types
(gen_random_uuid(),
 'Custom Mapped Type', 'Tipo Mapeado Personalizado',
 'Create a mapped type Nullable<T> that makes all properties of T nullable (T[K] | null). Apply it to { a: number; b: string } and print a value.',
 'Crea un tipo mapeado Nullable<T> que haga que todas las propiedades de T sean anulables (T[K] | null). Aplícalo a { a: number; b: string } e imprime un valor.',
 'typescript', 3, 'patterns',
 'type Nullable<T> = { [K in keyof T]: T[K] | ___ };\nconst obj: Nullable<{ a: number; b: string }> = { a: null, b: "hi" };\nconsole.log(obj.b);',
 'hi',
 3,
 'keyof T iterates over all property names of T.', 'keyof T itera sobre todos los nombres de propiedades de T.',
 'T[K] | null adds null as an allowed value for each property.', 'T[K] | null agrega null como valor permitido para cada propiedad.',
 'T[K] | null', 'T[K] | null',
 30, 5, now()),

-- 60. functions
(gen_random_uuid(),
 'Function Overloads', 'Sobrecarga de Funciones',
 'Write a function combine with overloads: (a: string, b: string) => string and (a: number, b: number) => number. Print combine("Hello, ", "World!") and combine(3, 4).',
 'Escribe una función combine con sobrecargas: (a: string, b: string) => string y (a: number, b: number) => number. Imprime combine("Hello, ", "World!") y combine(3, 4).',
 'typescript', 3, 'functions',
 'function combine(a: string, b: string): string;\nfunction combine(a: number, b: number): number;\nfunction combine(a: any, b: any): any {\n  return a + b;\n}\nconsole.log(combine("Hello, ", "World!"));\nconsole.log(combine(___, ___));',
 'Hello, World!\n7',
 3,
 'Function overloads define multiple call signatures before the implementation.', 'Las sobrecargas de funciones definen múltiples firmas de llamada antes de la implementación.',
 'The implementation uses any to handle both cases; callers see the typed overloads.', 'La implementación usa any para manejar ambos casos; los llamadores ven las sobrecargas tipadas.',
 'combine(3, 4)', 'combine(3, 4)',
 30, 5, now()),

-- 61. algorithms
(gen_random_uuid(),
 'Binary Search Typed', 'Búsqueda Binaria Tipada',
 'Write a typed function binarySearch(arr: number[], target: number): number that returns the index of target or -1. Print binarySearch([1,3,5,7,9], 7).',
 'Escribe una función tipada binarySearch(arr: number[], target: number): number que devuelva el índice del objetivo o -1. Imprime binarySearch([1,3,5,7,9], 7).',
 'typescript', 3, 'algorithms',
 'function binarySearch(arr: number[], target: number): number {\n  let lo = 0, hi = arr.length - 1;\n  while (lo <= hi) {\n    const mid = Math.floor((lo + hi) / 2);\n    if (arr[mid] === target) return ___;\n    else if (arr[mid] < target) lo = mid + 1;\n    else hi = mid - 1;\n  }\n  return -1;\n}\nconsole.log(binarySearch([1,3,5,7,9], 7));',
 '3',
 3,
 'When arr[mid] === target you have found the element.', 'Cuando arr[mid] === target has encontrado el elemento.',
 'Return mid as the found index.', 'Devuelve mid como el índice encontrado.',
 'return mid;', 'return mid;',
 30, 5, now()),

-- 62. data_structures
(gen_random_uuid(),
 'Generic Queue', 'Cola Genérica',
 'Implement a generic class Queue<T> with enqueue(item: T): void and dequeue(): T | undefined. Enqueue "a" and "b", dequeue and print.',
 'Implementa una clase genérica Queue<T> con enqueue(item: T): void y dequeue(): T | undefined. Encola "a" y "b", desencola e imprime.',
 'typescript', 3, 'data_structures',
 'class Queue<T> {\n  private items: T[] = [];\n  enqueue(item: T): void { this.items.push(item); }\n  dequeue(): T | undefined { return this.items.___(); }\n}\nconst q = new Queue<string>();\nq.enqueue("a"); q.enqueue("b");\nconsole.log(q.dequeue());',
 'a',
 3,
 'A queue is FIFO — first in, first out.', 'Una cola es FIFO — primero en entrar, primero en salir.',
 'shift() removes and returns the first element of an array.', 'shift() elimina y devuelve el primer elemento de un array.',
 'this.items.shift()', 'this.items.shift()',
 30, 5, now()),

-- 63. generics
(gen_random_uuid(),
 'Generic Constraint', 'Restricción Genérica',
 'Write a function getLength<T extends { length: number }>(val: T): number that returns val.length. Print getLength("hello") and getLength([1,2,3]).',
 'Escribe una función getLength<T extends { length: number }>(val: T): number que devuelva val.length. Imprime getLength("hello") y getLength([1,2,3]).',
 'typescript', 3, 'functions',
 'function getLength<T extends { length: ___ }>(val: T): number {\n  return val.length;\n}\nconsole.log(getLength("hello"));\nconsole.log(getLength([1,2,3]));',
 '5\n3',
 3,
 'extends { length: number } constrains T to types that have a length property.', 'extends { length: number } restringe T a tipos que tienen una propiedad length.',
 'Both strings and arrays have a .length property.', 'Tanto los strings como los arrays tienen una propiedad .length.',
 'length: number', 'length: number',
 30, 5, now()),

-- 64. patterns (discriminated union)
(gen_random_uuid(),
 'Discriminated Union', 'Unión Discriminada',
 'Define types Circle { kind: "circle"; radius: number } and Square { kind: "square"; side: number }. Write function area(shape: Circle | Square): number. Print area({ kind: "circle", radius: 5 }) rounded to 2 decimals.',
 'Define los tipos Circle { kind: "circle"; radius: number } y Square { kind: "square"; side: number }. Escribe la función area(shape: Circle | Square): number. Imprime area({ kind: "circle", radius: 5 }) redondeado a 2 decimales.',
 'typescript', 3, 'patterns',
 'type Circle = { kind: "circle"; radius: number };\ntype Square = { kind: "square"; side: number };\nfunction area(shape: Circle | Square): number {\n  if (shape.kind === "circle") return Math.PI * shape.radius ** 2;\n  return shape.___ ** 2;\n}\nconsole.log(area({ kind: "circle", radius: 5 }).toFixed(2));',
 '78.54',
 3,
 'The kind property acts as a discriminant to narrow the union.', 'La propiedad kind actúa como discriminante para estrechar la unión.',
 'When kind is "square", shape is narrowed to Square with a side property.', 'Cuando kind es "square", shape se estrecha a Square con una propiedad side.',
 'shape.side', 'shape.side',
 30, 5, now()),

-- 65. algorithms
(gen_random_uuid(),
 'Typed Bubble Sort', 'Bubble Sort Tipado',
 'Write a typed function bubbleSort(arr: number[]): number[] that returns a sorted copy. Print bubbleSort([5,3,8,1,2]).',
 'Escribe una función tipada bubbleSort(arr: number[]): number[] que devuelva una copia ordenada. Imprime bubbleSort([5,3,8,1,2]).',
 'typescript', 3, 'algorithms',
 'function bubbleSort(arr: number[]): number[] {\n  const a = [...arr];\n  for (let i = 0; i < a.length; i++)\n    for (let j = 0; j < a.length - i - 1; j++)\n      if (a[j] > a[j+1]) [a[j], a[j+1]] = [a[___], a[___]];\n  return a;\n}\nconsole.log(bubbleSort([5,3,8,1,2]));',
 '[ 1, 2, 3, 5, 8 ]',
 3,
 'Swap adjacent elements using destructuring assignment.', 'Intercambia elementos adyacentes usando asignación de desestructuración.',
 '[a[j], a[j+1]] = [a[j+1], a[j]] swaps the two elements.', '[a[j], a[j+1]] = [a[j+1], a[j]] intercambia los dos elementos.',
 'j+1, j', 'j+1, j',
 30, 5, now()),

-- 66. strings
(gen_random_uuid(),
 'String Regex Match', 'Regex Match en String',
 'Given email = "user@example.com", use a regex to validate the format and print true or false.',
 'Dado email = "user@example.com", usa una regex para validar el formato e imprime true o false.',
 'typescript', 3, 'strings',
 'const email: string = "user@example.com";\nconst valid: boolean = /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(___);\nconsole.log(valid);',
 'true',
 3,
 'RegExp.test() returns true if the string matches the pattern.', 'RegExp.test() devuelve true si el string coincide con el patrón.',
 'Pass the email variable to .test().', 'Pasa la variable email a .test().',
 '/regex/.test(email)', '/regex/.test(email)',
 30, 5, now()),

-- 67. objects
(gen_random_uuid(),
 'Class with Interface', 'Clase con Interfaz',
 'Define interface Shape { area(): number }. Create class Rectangle implementing Shape with width and height constructor params. Print new Rectangle(4, 5).area().',
 'Define la interfaz Shape { area(): number }. Crea la clase Rectangle implementando Shape con parámetros de constructor width y height. Imprime new Rectangle(4, 5).area().',
 'typescript', 3, 'objects',
 'interface Shape { area(): number; }\nclass Rectangle implements Shape {\n  constructor(private width: number, private height: number) {}\n  area(): number { return this.___ * this.___; }\n}\nconsole.log(new Rectangle(4, 5).area());',
 '20',
 3,
 'implements enforces that the class provides the interface methods.', 'implements exige que la clase proporcione los métodos de la interfaz.',
 'area() should return width times height.', 'area() debe devolver width multiplicado por height.',
 'this.width * this.height', 'this.width * this.height',
 30, 5, now()),

-- 68. algorithms
(gen_random_uuid(),
 'Two Sum', 'Dos Suma',
 'Write a typed function twoSum(nums: number[], target: number): [number, number] | null that returns indices of two numbers summing to target. Print twoSum([2,7,11,15], 9).',
 'Escribe una función tipada twoSum(nums: number[], target: number): [number, number] | null que devuelva los índices de dos números que sumen target. Imprime twoSum([2,7,11,15], 9).',
 'typescript', 3, 'algorithms',
 'function twoSum(nums: number[], target: number): [number, number] | null {\n  const map = new Map<number, number>();\n  for (let i = 0; i < nums.length; i++) {\n    const complement = target - nums[i];\n    if (map.has(complement)) return [map.get(complement)!, ___];\n    map.set(nums[i], i);\n  }\n  return null;\n}\nconsole.log(twoSum([2,7,11,15], 9));',
 '[ 0, 1 ]',
 3,
 'Use a Map to store each number and its index as you iterate.', 'Usa un Map para almacenar cada número y su índice mientras iteras.',
 'Return [map.get(complement)!, i] when the complement is found.', 'Devuelve [map.get(complement)!, i] cuando se encuentra el complemento.',
 'i', 'i',
 30, 5, now()),

-- 69. data_structures
(gen_random_uuid(),
 'Map and Set Types', 'Tipos Map y Set',
 'Create a Map<string, number> named scores, add ("Alice", 95) and ("Bob", 87), then print the size and Alice''s score.',
 'Crea un Map<string, number> llamado scores, agrega ("Alice", 95) y ("Bob", 87), luego imprime el tamaño y la puntuación de Alice.',
 'typescript', 3, 'data_structures',
 'const scores = new Map<string, number>();\nscores.set("Alice", 95);\nscores.set("Bob", 87);\nconsole.log(scores.size);\nconsole.log(scores.get("___"));',
 '2\n95',
 3,
 'Map<K, V> stores key-value pairs with typed keys and values.', 'Map<K, V> almacena pares clave-valor con claves y valores tipados.',
 'Use .get("Alice") to retrieve Alice''s score.', 'Usa .get("Alice") para obtener la puntuación de Alice.',
 'scores.get("Alice")', 'scores.get("Alice")',
 30, 5, now()),

-- 70. patterns
(gen_random_uuid(),
 'Intersection Types', 'Tipos Intersección',
 'Define types Named { name: string } and Aged { age: number }. Create type Person = Named & Aged. Declare a Person and print their name and age.',
 'Define los tipos Named { name: string } y Aged { age: number }. Crea el tipo Person = Named & Aged. Declara una Person e imprime su name y age.',
 'typescript', 3, 'patterns',
 'type Named = { name: string };\ntype Aged = { age: number };\ntype Person = Named ___ Aged;\nconst p: Person = { name: "Dana", age: 22 };\nconsole.log(p.name, p.age);',
 'Dana 22',
 3,
 'Use the & operator to create an intersection type.', 'Usa el operador & para crear un tipo intersección.',
 'An intersection type combines all properties from both types.', 'Un tipo intersección combina todas las propiedades de ambos tipos.',
 'Named & Aged', 'Named & Aged',
 30, 5, now()),

-- 71. math
(gen_random_uuid(),
 'GCD Algorithm Typed', 'Algoritmo MCD Tipado',
 'Write a typed function gcd(a: number, b: number): number using the Euclidean algorithm. Print gcd(48, 18).',
 'Escribe una función tipada gcd(a: number, b: number): number usando el algoritmo de Euclides. Imprime gcd(48, 18).',
 'typescript', 3, 'math',
 'function gcd(a: number, b: number): number {\n  while (b !== 0) {\n    [a, b] = [b, a ___ b];\n  }\n  return a;\n}\nconsole.log(gcd(48, 18));',
 '6',
 3,
 'The Euclidean algorithm repeatedly replaces (a, b) with (b, a % b).', 'El algoritmo de Euclides reemplaza repetidamente (a, b) con (b, a % b).',
 'Use the % modulo operator.', 'Usa el operador módulo %.',
 'a % b', 'a % b',
 30, 5, now()),

-- 72. patterns (conditional types)
(gen_random_uuid(),
 'Conditional Type', 'Tipo Condicional',
 'Create a conditional type IsString<T> that equals "yes" if T is string, "no" otherwise. Print a value of type IsString<string> and IsString<number>.',
 'Crea un tipo condicional IsString<T> que sea igual a "yes" si T es string, "no" de lo contrario. Imprime un valor de tipo IsString<string> e IsString<number>.',
 'typescript', 3, 'patterns',
 'type IsString<T> = T extends string ? "___" : "no";\nconst a: IsString<string> = "yes";\nconst b: IsString<number> = "no";\nconsole.log(a);\nconsole.log(b);',
 'yes\nno',
 3,
 'Conditional types use the T extends X ? Y : Z syntax.', 'Los tipos condicionales usan la sintaxis T extends X ? Y : Z.',
 'If T extends string the type resolves to "yes", otherwise "no".', 'Si T extends string el tipo se resuelve a "yes", de lo contrario "no".',
 '"yes"', '"yes"',
 30, 5, now()),

-- 73. objects
(gen_random_uuid(),
 'Abstract Class', 'Clase Abstracta',
 'Define abstract class Vehicle with abstract method fuelType(): string and a method describe() that prints "This vehicle uses <fuelType()>". Create class Car extending it. Call new Car().describe().',
 'Define la clase abstracta Vehicle con el método abstracto fuelType(): string y un método describe() que imprima "This vehicle uses <fuelType()>". Crea la clase Car extendiéndola. Llama a new Car().describe().',
 'typescript', 3, 'objects',
 'abstract class Vehicle {\n  abstract fuelType(): string;\n  describe(): void { console.log(`This vehicle uses ${this.fuelType()}`); }\n}\nclass Car extends Vehicle {\n  fuelType(): string { return "___"; }\n}\nnew Car().describe();',
 'This vehicle uses gasoline',
 3,
 'Abstract classes cannot be instantiated directly.', 'Las clases abstractas no pueden instanciarse directamente.',
 'Car must implement the fuelType() method.', 'Car debe implementar el método fuelType().',
 'return "gasoline";', 'return "gasoline";',
 30, 5, now()),

-- 74. functions
(gen_random_uuid(),
 'Higher-Order Typed Function', 'Función de Orden Superior Tipada',
 'Write a typed function applyTwice<T>(fn: (x: T) => T, val: T): T that applies fn twice. Print applyTwice((n: number) => n * 2, 3).',
 'Escribe una función tipada applyTwice<T>(fn: (x: T) => T, val: T): T que aplique fn dos veces. Imprime applyTwice((n: number) => n * 2, 3).',
 'typescript', 3, 'functions',
 'function applyTwice<T>(fn: (x: T) => T, val: T): T {\n  return fn(fn(___));\n}\nconsole.log(applyTwice((n: number) => n * 2, 3));',
 '12',
 3,
 'Apply the inner call first: fn(val), then wrap it: fn(fn(val)).', 'Aplica primero la llamada interna: fn(val), luego envuélvela: fn(fn(val)).',
 'fn(fn(val)) applies fn to val, then applies fn to the result.', 'fn(fn(val)) aplica fn a val, luego aplica fn al resultado.',
 'fn(val)', 'fn(val)',
 30, 5, now()),

-- 75. strings
(gen_random_uuid(),
 'Palindrome Check Typed', 'Verificación de Palíndromo Tipada',
 'Write a typed function isPalindrome(s: string): boolean that checks if s equals its reverse. Print isPalindrome("racecar") and isPalindrome("hello").',
 'Escribe una función tipada isPalindrome(s: string): boolean que verifique si s es igual a su inverso. Imprime isPalindrome("racecar") e isPalindrome("hello").',
 'typescript', 3, 'strings',
 'function isPalindrome(s: string): boolean {\n  return s === s.split("").___().join("");\n}\nconsole.log(isPalindrome("racecar"));\nconsole.log(isPalindrome("hello"));',
 'true\nfalse',
 3,
 'Split into characters, reverse the array, then join back.', 'Divide en caracteres, invierte el array, luego une de nuevo.',
 '.reverse() reverses an array in place.', '.reverse() invierte un array en su lugar.',
 '.reverse()', '.reverse()',
 30, 5, now()),

-- ============================================================
-- DIFFICULTY 4 — 15 exercises (points=50, penalty=10)
-- ============================================================

-- 76. mapped types
(gen_random_uuid(),
 'Mapped Type with Modifiers', 'Tipo Mapeado con Modificadores',
 'Create a mapped type Mutable<T> that removes the readonly modifier from all properties of T. Apply it to { readonly x: number; readonly y: number } and mutate a property.',
 'Crea un tipo mapeado Mutable<T> que elimine el modificador readonly de todas las propiedades de T. Aplícalo a { readonly x: number; readonly y: number } y muta una propiedad.',
 'typescript', 4, 'patterns',
 'type Mutable<T> = { -readonly [K in keyof T]: T[K] };\nconst p: Mutable<{ readonly x: number; readonly y: number }> = { x: 1, y: 2 };\np.x = ___;\nconsole.log(p.x);',
 '10',
 3,
 'The -readonly prefix removes the readonly modifier in a mapped type.', 'El prefijo -readonly elimina el modificador readonly en un tipo mapeado.',
 'After Mutable<T> is applied, properties can be reassigned.', 'Después de aplicar Mutable<T>, las propiedades pueden reasignarse.',
 'p.x = 10;', 'p.x = 10;',
 50, 10, now()),

-- 77. patterns (decorators concept)
(gen_random_uuid(),
 'Property Decorator Pattern', 'Patrón Decorador de Propiedad',
 'Without decorator syntax, simulate a logged property by wrapping a class method: create class Counter with a count property. Wrap the increment method to log "increment called" before incrementing. Call increment() and print count.',
 'Sin sintaxis de decoradores, simula una propiedad registrada envolviendo un método de clase: crea la clase Counter con una propiedad count. Envuelve el método increment para registrar "increment called" antes de incrementar. Llama a increment() e imprime count.',
 'typescript', 4, 'patterns',
 'class Counter {\n  count: number = 0;\n  increment(): void { this.count++; }\n}\nconst c = new Counter();\nconst originalIncrement = c.increment.bind(c);\nc.increment = () => {\n  console.log("increment called");\n  ___();\n};\nc.increment();\nconsole.log(c.count);',
 'increment called\n1',
 3,
 'Store the original method and call it inside the wrapper.', 'Almacena el método original y llámalo dentro del envoltorio.',
 'originalIncrement() calls the stored original method.', 'originalIncrement() llama al método original almacenado.',
 'originalIncrement', 'originalIncrement',
 50, 10, now()),

-- 78. generics
(gen_random_uuid(),
 'Generic Pair and Swap', 'Par Genérico y Swap',
 'Define a generic type Pair<A, B> = [A, B] and a function swap<A, B>(pair: Pair<A, B>): Pair<B, A>. Print swap(["hello", 42]).',
 'Define un tipo genérico Pair<A, B> = [A, B] y una función swap<A, B>(pair: Pair<A, B>): Pair<B, A>. Imprime swap(["hello", 42]).',
 'typescript', 4, 'functions',
 'type Pair<A, B> = [A, B];\nfunction swap<A, B>(pair: Pair<A, B>): Pair<B, A> {\n  return [pair[___], pair[___]];\n}\nconsole.log(swap(["hello", 42]));',
 '[ 42, ''hello'' ]',
 3,
 'To swap, the new first element comes from index 1 and the new second from index 0.', 'Para intercambiar, el nuevo primer elemento viene del índice 1 y el nuevo segundo del índice 0.',
 'Return [pair[1], pair[0]] to reverse the pair.', 'Devuelve [pair[1], pair[0]] para invertir el par.',
 '1, 0', '1, 0',
 50, 10, now()),

-- 79. algorithms
(gen_random_uuid(),
 'Memoize Generic', 'Memoize Genérico',
 'Write a generic function memoize<T extends unknown[], R>(fn: (...args: T) => R): (...args: T) => R that caches results. Use it to memoize a slow factorial. Print memoized(5).',
 'Escribe una función genérica memoize<T extends unknown[], R>(fn: (...args: T) => R): (...args: T) => R que almacene en caché los resultados. Úsala para memoizar un factorial lento. Imprime memoized(5).',
 'typescript', 4, 'algorithms',
 'function memoize<T extends unknown[], R>(fn: (...args: T) => R): (...args: T) => R {\n  const cache = new Map<string, R>();\n  return (...args: T): R => {\n    const key = JSON.stringify(args);\n    if (cache.has(key)) return cache.get(key)!;\n    const result = fn(___args);\n    cache.set(key, result);\n    return result;\n  };\n}\nconst memoized = memoize((n: number): number => n <= 1 ? 1 : n * memoized(n - 1));\nconsole.log(memoized(5));',
 '120',
 3,
 'Use the spread operator to forward all arguments to fn.', 'Usa el operador spread para reenviar todos los argumentos a fn.',
 'fn(...args) calls the original function with the spread arguments.', 'fn(...args) llama a la función original con los argumentos expandidos.',
 '...', '...',
 50, 10, now()),

-- 80. patterns (conditional types)
(gen_random_uuid(),
 'Infer in Conditional Types', 'Infer en Tipos Condicionales',
 'Create a type ReturnType<T> using conditional types and infer to extract the return type of a function. Apply it to () => number and print a value of that type.',
 'Crea un tipo ReturnType<T> usando tipos condicionales e infer para extraer el tipo de retorno de una función. Aplícalo a () => number e imprime un valor de ese tipo.',
 'typescript', 4, 'patterns',
 'type MyReturnType<T> = T extends (...args: any[]) => ___ R ? R : never;\ntype Num = MyReturnType<() => number>;\nconst x: Num = 42;\nconsole.log(x);',
 '42',
 3,
 'The infer keyword captures a type within a conditional type expression.', 'La palabra clave infer captura un tipo dentro de una expresión de tipo condicional.',
 'infer R is placed where you want to capture the return type.', 'infer R se coloca donde deseas capturar el tipo de retorno.',
 'infer', 'infer',
 50, 10, now()),

-- 81. data_structures
(gen_random_uuid(),
 'Generic Linked List', 'Lista Enlazada Genérica',
 'Implement a generic singly-linked list with Node<T> and LinkedList<T> classes. Add push and toArray methods. Push 1, 2, 3 and print the array.',
 'Implementa una lista enlazada simple genérica con las clases Node<T> y LinkedList<T>. Agrega los métodos push y toArray. Empuja 1, 2, 3 e imprime el array.',
 'typescript', 4, 'data_structures',
 'class Node<T> { constructor(public val: T, public next: Node<T> | null = null) {} }\nclass LinkedList<T> {\n  private head: Node<T> | null = null;\n  push(val: T): void {\n    const node = new Node(val);\n    if (!this.head) { this.head = node; return; }\n    let cur = this.head;\n    while (cur.next) cur = cur.next;\n    cur.next = ___;\n  }\n  toArray(): T[] {\n    const res: T[] = [];\n    let cur = this.head;\n    while (cur) { res.push(cur.val); cur = cur.next; }\n    return res;\n  }\n}\nconst list = new LinkedList<number>();\nlist.push(1); list.push(2); list.push(3);\nconsole.log(list.toArray());',
 '[ 1, 2, 3 ]',
 3,
 'Traverse to the last node (where cur.next is null) and attach the new node.', 'Recorre hasta el último nodo (donde cur.next es null) y adjunta el nuevo nodo.',
 'cur.next = node sets the new node as the tail.', 'cur.next = node establece el nuevo nodo como la cola.',
 'node', 'node',
 50, 10, now()),

-- 82. algorithms
(gen_random_uuid(),
 'Deep Clone Generic', 'Clon Profundo Genérico',
 'Write a typed function deepClone<T>(obj: T): T that deep clones a plain object using JSON parse/stringify. Clone { a: 1, b: { c: 2 } }, mutate the clone, and print original.b.c.',
 'Escribe una función tipada deepClone<T>(obj: T): T que clone profundamente un objeto plano usando JSON parse/stringify. Clona { a: 1, b: { c: 2 } }, muta el clon e imprime original.b.c.',
 'typescript', 4, 'algorithms',
 'function deepClone<T>(obj: T): T {\n  return JSON.___(JSON.stringify(obj));\n}\nconst original = { a: 1, b: { c: 2 } };\nconst clone = deepClone(original);\nclone.b.c = 99;\nconsole.log(original.b.c);',
 '2',
 3,
 'JSON.parse converts a JSON string back into an object.', 'JSON.parse convierte un string JSON de vuelta en un objeto.',
 'JSON.parse(JSON.stringify(obj)) creates a fully independent deep copy.', 'JSON.parse(JSON.stringify(obj)) crea una copia profunda completamente independiente.',
 'parse', 'parse',
 50, 10, now()),

-- 83. objects
(gen_random_uuid(),
 'Builder Pattern Typed', 'Patrón Builder Tipado',
 'Implement a QueryBuilder class with select(fields: string[]): this, from(table: string): this, and build(): string methods. Chain them and print the result.',
 'Implementa una clase QueryBuilder con métodos select(fields: string[]): this, from(table: string): this y build(): string. Encadénalos e imprime el resultado.',
 'typescript', 4, 'patterns',
 'class QueryBuilder {\n  private _fields: string[] = [];\n  private _table: string = "";\n  select(fields: string[]): ___ { this._fields = fields; return this; }\n  from(table: string): this { this._table = table; return this; }\n  build(): string { return `SELECT ${this._fields.join(", ")} FROM ${this._table}`; }\n}\nconsole.log(new QueryBuilder().select(["id","name"]).from("users").build());',
 'SELECT id, name FROM users',
 3,
 'Returning "this" from each method enables method chaining.', 'Devolver "this" de cada método habilita el encadenamiento de métodos.',
 'The return type this refers to the current class instance.', 'El tipo de retorno this se refiere a la instancia de clase actual.',
 'this', 'this',
 50, 10, now()),

-- 84. generics
(gen_random_uuid(),
 'KeyOf and Lookup Types', 'KeyOf y Tipos de Búsqueda',
 'Write a typed function getProperty<T, K extends keyof T>(obj: T, key: K): T[K]. Use it to get the "name" property of { name: "Tom", age: 20 } and print it.',
 'Escribe una función tipada getProperty<T, K extends keyof T>(obj: T, key: K): T[K]. Úsala para obtener la propiedad "name" de { name: "Tom", age: 20 } e imprímela.',
 'typescript', 4, 'functions',
 'function getProperty<T, K extends keyof T>(obj: T, key: K): T[K] {\n  return obj[___];\n}\nconsole.log(getProperty({ name: "Tom", age: 20 }, "name"));',
 'Tom',
 3,
 'K extends keyof T constrains K to be a key of T.', 'K extends keyof T restringe K a ser una clave de T.',
 'obj[key] uses the lookup type T[K] for type-safe property access.', 'obj[key] usa el tipo de búsqueda T[K] para un acceso seguro a propiedades.',
 'key', 'key',
 50, 10, now()),

-- 85. patterns
(gen_random_uuid(),
 'Template Literal Types', 'Tipos Template Literal',
 'Create a type EventName<T extends string> = `on${Capitalize<T>}`. Print a value of type EventName<"click"> and EventName<"change">.',
 'Crea un tipo EventName<T extends string> = `on${Capitalize<T>}`. Imprime un valor de tipo EventName<"click"> y EventName<"change">.',
 'typescript', 4, 'patterns',
 'type EventName<T extends string> = `on${___<T>}`;\nconst e1: EventName<"click"> = "onClick";\nconst e2: EventName<"change"> = "onChange";\nconsole.log(e1);\nconsole.log(e2);',
 'onClick\nonChange',
 3,
 'Capitalize<T> is a built-in TypeScript utility type that uppercases the first letter.', 'Capitalize<T> es un tipo utilitario integrado de TypeScript que convierte en mayúscula la primera letra.',
 'Template literal types can embed utility types like Capitalize<T>.', 'Los tipos template literal pueden incrustar tipos utilitarios como Capitalize<T>.',
 'Capitalize', 'Capitalize',
 50, 10, now()),

-- 86. algorithms
(gen_random_uuid(),
 'Flatten Nested Array', 'Aplanar Array Anidado',
 'Write a typed recursive function flatten(arr: (number | number[])[]): number[] that flattens one level of nesting. Print flatten([1, [2, 3], [4, 5], 6]).',
 'Escribe una función tipada recursiva flatten(arr: (number | number[])[]): number[] que aplane un nivel de anidamiento. Imprime flatten([1, [2, 3], [4, 5], 6]).',
 'typescript', 4, 'algorithms',
 'function flatten(arr: (number | number[])[]): number[] {\n  return arr.reduce<number[]>((acc, item) => {\n    if (Array.isArray(item)) return acc.concat(___);\n    return acc.concat(item);\n  }, []);\n}\nconsole.log(flatten([1, [2, 3], [4, 5], 6]));',
 '[ 1, 2, 3, 4, 5, 6 ]',
 3,
 'When item is an array, concat its elements into the accumulator.', 'Cuando item es un array, concatena sus elementos en el acumulador.',
 'acc.concat(item) spreads the nested array into the flat result.', 'acc.concat(item) expande el array anidado en el resultado plano.',
 'item', 'item',
 50, 10, now()),

-- 87. data_structures
(gen_random_uuid(),
 'Typed Binary Tree', 'Árbol Binario Tipado',
 'Implement a generic BinaryTree<T> with insert(val: T) using BST rules (assuming numbers) and inOrder(): T[] traversal. Insert 5, 3, 7 and print inOrder result.',
 'Implementa un árbol binario genérico BinaryTree<T> con insert(val: T) usando reglas BST (asumiendo números) y recorrido inOrder(): T[]. Inserta 5, 3, 7 e imprime el resultado inOrder.',
 'typescript', 4, 'data_structures',
 'class TNode<T> { constructor(public val: T, public left: TNode<T>|null=null, public right: TNode<T>|null=null){} }\nclass BinaryTree<T> {\n  root: TNode<T>|null = null;\n  insert(val: T): void {\n    const node = new TNode(val);\n    if (!this.root) { this.root = node; return; }\n    let cur: TNode<T>|null = this.root;\n    while(cur) {\n      if ((val as any) < (cur.val as any)) {\n        if (!cur.left) { cur.left = node; return; } else cur = cur.left;\n      } else {\n        if (!cur.right) { cur.right = node; return; } else cur = cur.right;\n      }\n    }\n  }\n  inOrder(node: TNode<T>|null = this.root, res: T[] = []): T[] {\n    if (!node) return res;\n    this.inOrder(node.___, res);\n    res.push(node.val);\n    this.inOrder(node.right, res);\n    return res;\n  }\n}\nconst t = new BinaryTree<number>();\n[5,3,7].forEach(v => t.insert(v));\nconsole.log(t.inOrder());',
 '[ 3, 5, 7 ]',
 3,
 'In-order traversal visits left subtree, then root, then right subtree.', 'El recorrido en orden visita el subárbol izquierdo, luego la raíz, luego el subárbol derecho.',
 'Recurse into node.left before pushing node.val.', 'Recurre en node.left antes de hacer push de node.val.',
 'left', 'left',
 50, 10, now()),

-- 88. patterns
(gen_random_uuid(),
 'Exhaustive Switch with never', 'Switch Exhaustivo con never',
 'Define type Color = "red" | "green" | "blue". Write function colorCode(c: Color): number using a switch that returns hex codes. Use a never assertion in the default case. Print colorCode("green").',
 'Define el tipo Color = "red" | "green" | "blue". Escribe la función colorCode(c: Color): number usando un switch que devuelva códigos hex. Usa una aserción never en el caso default. Imprime colorCode("green").',
 'typescript', 4, 'patterns',
 'type Color = "red" | "green" | "blue";\nfunction colorCode(c: Color): number {\n  switch(c) {\n    case "red": return 0xFF0000;\n    case "green": return 0x00FF00;\n    case "blue": return 0x0000FF;\n    default: const _exhaustive: ___ = c; throw new Error(_exhaustive);\n  }\n}\nconsole.log(colorCode("green"));',
 '65280',
 3,
 'Assigning to type never in the default case catches unhandled union members at compile time.', 'Asignar al tipo never en el caso default detecta miembros de la unión no manejados en tiempo de compilación.',
 'const _exhaustive: never = c; throws if c somehow has an unhandled value.', 'const _exhaustive: never = c; lanza un error si c tiene algún valor no manejado.',
 'never', 'never',
 50, 10, now()),

-- 89. algorithms
(gen_random_uuid(),
 'Flatten Object Keys', 'Aplanar Claves de Objeto',
 'Write a typed function flattenKeys(obj: Record<string, Record<string, number>>): Record<string, number> that merges all nested keys into a single-level object. Print flattenKeys({ a: { x: 1 }, b: { y: 2, z: 3 } }).',
 'Escribe una función tipada flattenKeys(obj: Record<string, Record<string, number>>): Record<string, number> que fusione todas las claves anidadas en un objeto de un solo nivel. Imprime flattenKeys({ a: { x: 1 }, b: { y: 2, z: 3 } }).',
 'typescript', 4, 'algorithms',
 'function flattenKeys(obj: Record<string, Record<string, number>>): Record<string, number> {\n  const result: Record<string, number> = {};\n  for (const outerKey of Object.keys(obj)) {\n    for (const [innerKey, val] of Object.entries(obj[outerKey])) {\n      result[___] = val;\n    }\n  }\n  return result;\n}\nconsole.log(flattenKeys({ a: { x: 1 }, b: { y: 2, z: 3 } }));',
 '{ x: 1, y: 2, z: 3 }',
 3,
 'Use the inner key directly as the result key.', 'Usa la clave interna directamente como clave del resultado.',
 'result[innerKey] = val stores the value under the flattened key.', 'result[innerKey] = val almacena el valor bajo la clave aplanada.',
 'innerKey', 'innerKey',
 50, 10, now()),

-- 90. algorithms
(gen_random_uuid(),
 'Debounce Typed', 'Debounce Tipado',
 'Write a typed function debounce<T extends unknown[]>(fn: (...args: T) => void, delay: number): (...args: T) => void that delays execution. Create a debounced logger and call it — the test verifies the function compiles correctly, print "debounce ready".',
 'Escribe una función tipada debounce<T extends unknown[]>(fn: (...args: T) => void, delay: number): (...args: T) => void que retrase la ejecución. Crea un logger con debounce y llámalo — el test verifica que la función compile correctamente, imprime "debounce ready".',
 'typescript', 4, 'challenges',
 'function debounce<T extends unknown[]>(fn: (...args: T) => void, delay: number): (...args: T) => void {\n  let timer: ReturnType<typeof setTimeout>;\n  return (...args: T): void => {\n    clearTimeout(timer);\n    timer = setTimeout(() => fn(___args), delay);\n  };\n}\nconst log = debounce((msg: string) => console.log(msg), 100);\nlog("debounce ready");',
 'debounce ready',
 3,
 'Use the spread operator to forward all arguments to the original function.', 'Usa el operador spread para reenviar todos los argumentos a la función original.',
 'fn(...args) calls the original with the collected arguments.', 'fn(...args) llama al original con los argumentos recopilados.',
 '...', '...',
 50, 10, now()),

-- ============================================================
-- DIFFICULTY 5 — 10 exercises (points=100, penalty=10)
-- ============================================================

-- 91. patterns (advanced generics)
(gen_random_uuid(),
 'Deep Readonly Type', 'Tipo Deep Readonly',
 'Create a recursive type DeepReadonly<T> that makes all nested properties readonly. Apply it to a nested object and verify immutability at compile time by reading a deep property.',
 'Crea un tipo recursivo DeepReadonly<T> que haga que todas las propiedades anidadas sean readonly. Aplícalo a un objeto anidado y verifica la inmutabilidad en tiempo de compilación leyendo una propiedad profunda.',
 'typescript', 5, 'patterns',
 'type DeepReadonly<T> = T extends object\n  ? { readonly [K in keyof T]: DeepReadonly<T[K]> }\n  : ___;\ntype Config = { db: { host: string; port: number }; debug: boolean };\nconst cfg: DeepReadonly<Config> = { db: { host: "localhost", port: 5432 }, debug: false };\nconsole.log(cfg.db.host);',
 'localhost',
 3,
 'The base case of the recursion is the type T itself (a primitive).', 'El caso base de la recursión es el tipo T mismo (un primitivo).',
 'When T is not an object, return T unchanged.', 'Cuando T no es un objeto, devuelve T sin cambios.',
 'T', 'T',
 100, 10, now()),

-- 92. algorithms (advanced)
(gen_random_uuid(),
 'Typed Event Emitter', 'Emisor de Eventos Tipado',
 'Implement a type-safe EventEmitter<Events> class where Events is a record of event names to payload types. Implement on<K>(event: K, listener: (payload: Events[K]) => void): void and emit<K>(event: K, payload: Events[K]): void. Test with a typed "data" event.',
 'Implementa una clase EventEmitter<Events> type-safe donde Events es un registro de nombres de eventos a tipos de payload. Implementa on<K>(event: K, listener: (payload: Events[K]) => void): void y emit<K>(event: K, payload: Events[K]): void. Prueba con un evento "data" tipado.',
 'typescript', 5, 'patterns',
 'class EventEmitter<Events extends Record<string, unknown>> {\n  private listeners: { [K in keyof Events]?: Array<(p: Events[K]) => void> } = {};\n  on<K extends keyof Events>(event: K, listener: (payload: Events[K]) => void): void {\n    if (!this.listeners[event]) this.listeners[event] = [];\n    this.listeners[event]!.push(___);\n  }\n  emit<K extends keyof Events>(event: K, payload: Events[K]): void {\n    this.listeners[event]?.forEach(fn => fn(payload));\n  }\n}\ntype MyEvents = { data: string; count: number };\nconst emitter = new EventEmitter<MyEvents>();\nemitter.on("data", msg => console.log(msg));\nemitter.emit("data", "hello events");',
 'hello events',
 3,
 'Push the listener function into the array for that event.', 'Haz push de la función listener en el array para ese evento.',
 'this.listeners[event]!.push(listener) stores the callback.', 'this.listeners[event]!.push(listener) almacena el callback.',
 'listener', 'listener',
 100, 10, now()),

-- 93. generics (advanced)
(gen_random_uuid(),
 'Variadic Tuple Types', 'Tipos Tupla Variádicos',
 'Write a typed function zip<A extends unknown[], B extends unknown[]>(a: A, b: B): { [K in keyof A]: [A[K], B[K & keyof B]] }. Zip ["a","b"] and [1,2] and print the result.',
 'Escribe una función tipada zip que una dos arrays en pares. Haz zip de ["a","b"] y [1,2] e imprime el resultado como array de pares.',
 'typescript', 5, 'algorithms',
 'function zip<A, B>(a: A[], b: B[]): [A, B][] {\n  return a.map((val, i) => [val, b[___]] as [A, B]);\n}\nconsole.log(zip(["a", "b"], [1, 2]));',
 '[ [ ''a'', 1 ], [ ''b'', 2 ] ]',
 3,
 'Use the index i from .map() to pair each element with its counterpart.', 'Usa el índice i de .map() para emparejar cada elemento con su contraparte.',
 'b[i] retrieves the element from b at the same position as a.', 'b[i] recupera el elemento de b en la misma posición que a.',
 'i', 'i',
 100, 10, now()),

-- 94. challenges
(gen_random_uuid(),
 'Pipe Function Typed', 'Función Pipe Tipada',
 'Implement a typed pipe function that composes two unary functions left-to-right: pipe<A, B, C>(f: (a: A) => B, g: (b: B) => C): (a: A) => C. Use it to compose n => n * 2 and n => n + 1. Print pipe(double, inc)(5).',
 'Implementa una función pipe tipada que componga dos funciones unarias de izquierda a derecha: pipe<A, B, C>(f: (a: A) => B, g: (b: B) => C): (a: A) => C. Úsala para componer n => n * 2 y n => n + 1. Imprime pipe(double, inc)(5).',
 'typescript', 5, 'functions',
 'function pipe<A, B, C>(f: (a: A) => B, g: (b: B) => C): (a: A) => C {\n  return (a: A): C => g(f(___));\n}\nconst double = (n: number) => n * 2;\nconst inc = (n: number) => n + 1;\nconsole.log(pipe(double, inc)(5));',
 '11',
 3,
 'Apply f first, then pass the result to g.', 'Aplica f primero, luego pasa el resultado a g.',
 'g(f(a)) computes f(a) first, then passes it to g.', 'g(f(a)) calcula f(a) primero, luego lo pasa a g.',
 'a', 'a',
 100, 10, now()),

-- 95. challenges
(gen_random_uuid(),
 'Observable Pattern Typed', 'Patrón Observable Tipado',
 'Implement a minimal typed Observable<T> class with subscribe(observer: (val: T) => void): void and a static from<T>(values: T[]): Observable<T> factory. Print each value from Observable.from([1,2,3]).',
 'Implementa una clase Observable<T> tipada mínima con subscribe(observer: (val: T) => void): void y un factory estático from<T>(values: T[]): Observable<T>. Imprime cada valor de Observable.from([1,2,3]).',
 'typescript', 5, 'patterns',
 'class Observable<T> {\n  constructor(private producer: (observer: (val: T) => void) => void) {}\n  subscribe(observer: (val: T) => void): void {\n    this.___(observer);\n  }\n  static from<T>(values: T[]): Observable<T> {\n    return new Observable<T>(observer => values.forEach(v => observer(v)));\n  }\n}\nObservable.from([1,2,3]).subscribe(v => console.log(v));',
 '1\n2\n3',
 3,
 'The producer function is stored and called in subscribe.', 'La función producer se almacena y se llama en subscribe.',
 'this.producer(observer) triggers the data emission.', 'this.producer(observer) desencadena la emisión de datos.',
 'producer', 'producer',
 100, 10, now()),

-- 96. challenges
(gen_random_uuid(),
 'Result Type (Either)', 'Tipo Result (Either)',
 'Implement discriminated union type Result<T, E> = { ok: true; value: T } | { ok: false; error: E }. Write tryDivide(a: number, b: number): Result<number, string> that returns error when b is 0. Print both outcomes.',
 'Implementa el tipo de unión discriminada Result<T, E> = { ok: true; value: T } | { ok: false; error: E }. Escribe tryDivide(a: number, b: number): Result<number, string> que devuelva error cuando b es 0. Imprime ambos resultados.',
 'typescript', 5, 'patterns',
 'type Result<T, E> = { ok: true; value: T } | { ok: false; error: E };\nfunction tryDivide(a: number, b: number): Result<number, string> {\n  if (b === 0) return { ok: ___, error: "Division by zero" };\n  return { ok: true, value: a / b };\n}\nconst r1 = tryDivide(10, 2);\nconst r2 = tryDivide(10, 0);\nif (r1.ok) console.log(r1.value);\nif (!r2.ok) console.log(r2.error);',
 '5\nDivision by zero',
 3,
 'When b is 0, return the error variant with ok: false.', 'Cuando b es 0, devuelve la variante de error con ok: false.',
 '{ ok: false, error: "..." } is the error branch of the Result type.', '{ ok: false, error: "..." } es la rama de error del tipo Result.',
 'false', 'false',
 100, 10, now()),

-- 97. challenges (mapped + conditional)
(gen_random_uuid(),
 'Required Deep Type', 'Tipo Deep Required',
 'Create a recursive type DeepRequired<T> that makes all nested optional properties required. Apply it to { a?: { b?: number } } and construct a fully required value.',
 'Crea un tipo recursivo DeepRequired<T> que haga que todas las propiedades opcionales anidadas sean requeridas. Aplícalo a { a?: { b?: number } } y construye un valor completamente requerido.',
 'typescript', 5, 'patterns',
 'type DeepRequired<T> = T extends object\n  ? { [K in keyof T]-?: DeepRequired<T[K]> }\n  : T;\ntype Nested = { a?: { b?: number } };\nconst obj: ___<Nested> = { a: { b: 42 } };\nconsole.log(obj.a.b);',
 '42',
 3,
 '-? removes the optional modifier from all properties in the mapped type.', '-? elimina el modificador opcional de todas las propiedades en el tipo mapeado.',
 'Apply DeepRequired to Nested to make all properties required.', 'Aplica DeepRequired a Nested para hacer que todas las propiedades sean requeridas.',
 'DeepRequired', 'DeepRequired',
 100, 10, now()),

-- 98. challenges
(gen_random_uuid(),
 'Curry Function Typed', 'Función Curry Tipada',
 'Write a typed curry function for binary functions: curry<A, B, C>(fn: (a: A, b: B) => C): (a: A) => (b: B) => C. Use it to create an addCurried function. Print addCurried(3)(4).',
 'Escribe una función curry tipada para funciones binarias: curry<A, B, C>(fn: (a: A, b: B) => C): (a: A) => (b: B) => C. Úsala para crear una función addCurried. Imprime addCurried(3)(4).',
 'typescript', 5, 'functions',
 'function curry<A, B, C>(fn: (a: A, b: B) => C): (a: A) => (b: B) => C {\n  return (a: A) => (___: B) => fn(a, b);\n}\nconst add = (a: number, b: number): number => a + b;\nconst addCurried = curry(add);\nconsole.log(addCurried(3)(4));',
 '7',
 3,
 'The curried function returns a function that takes b and calls fn(a, b).', 'La función curry devuelve una función que toma b y llama a fn(a, b).',
 'return (a: A) => (b: B) => fn(a, b); is the full implementation.', 'return (a: A) => (b: B) => fn(a, b); es la implementación completa.',
 'b', 'b',
 100, 10, now()),

-- 99. challenges
(gen_random_uuid(),
 'Type-Safe State Machine', 'Máquina de Estado Type-Safe',
 'Model a traffic light state machine with typed states ("red"|"yellow"|"green") and transitions. Implement next(state): State that cycles red->green->yellow->red. Print 4 transitions starting from "red".',
 'Modela una máquina de estado de semáforo con estados tipados ("red"|"yellow"|"green") y transiciones. Implementa next(state): State que cicle red->green->yellow->red. Imprime 4 transiciones comenzando desde "red".',
 'typescript', 5, 'patterns',
 'type State = "red" | "yellow" | "green";\nconst transitions: Record<State, State> = {\n  red: "green",\n  green: "yellow",\n  yellow: ___\n};\nfunction next(state: State): State { return transitions[state]; }\nlet s: State = "red";\nfor (let i = 0; i < 4; i++) { s = next(s); console.log(s); }',
 'green\nyellow\nred\ngreen',
 3,
 'Define transitions as a Record mapping each state to the next state.', 'Define las transiciones como un Record que mapea cada estado al siguiente.',
 'yellow transitions back to red to complete the cycle.', 'yellow transiciona de vuelta a red para completar el ciclo.',
 '"red"', '"red"',
 100, 10, now()),

-- 100. challenges
(gen_random_uuid(),
 'Typed Middleware Pipeline', 'Pipeline de Middleware Tipado',
 'Implement a typed middleware pipeline: type Middleware<T> = (ctx: T, next: () => void) => void. Write compose<T>(...middlewares: Middleware<T>[]): Middleware<T> that chains them. Run a pipeline that transforms a context object and print its final value.',
 'Implementa un pipeline de middleware tipado: type Middleware<T> = (ctx: T, next: () => void) => void. Escribe compose<T>(...middlewares: Middleware<T>[]): Middleware<T> que los encadene. Ejecuta un pipeline que transforme un objeto de contexto e imprime su valor final.',
 'typescript', 5, 'challenges',
 'type Middleware<T> = (ctx: T, next: () => void) => void;\nfunction compose<T>(...mws: Middleware<T>[]): Middleware<T> {\n  return (ctx: T, next: () => void): void => {\n    let i = 0;\n    function dispatch(): void {\n      if (i >= mws.length) { next(); return; }\n      const mw = mws[i++];\n      mw(ctx, ___);\n    }\n    dispatch();\n  };\n}\nconst ctx = { value: 0 };\nconst pipeline = compose<typeof ctx>(\n  (c, n) => { c.value += 1; n(); },\n  (c, n) => { c.value *= 3; n(); }\n);\npipeline(ctx, () => {});\nconsole.log(ctx.value);',
 '3',
 3,
 'Each middleware calls next() to advance to the following middleware.', 'Cada middleware llama a next() para avanzar al siguiente middleware.',
 'Pass the dispatch function as the next() callback so the chain continues.', 'Pasa la función dispatch como el callback next() para que la cadena continúe.',
 'dispatch', 'dispatch',
 100, 10, now())

ON CONFLICT DO NOTHING;

COMMIT;
