-- 051_exercises_go.sql
-- 50 Go programming exercises, bilingual EN+ES
-- Distribution: diff1=12, diff2=12, diff3=13, diff4=8, diff5=5
-- Points: 10/20/30/50/100 | Penalty: 3/3/5/10/10
-- Focus: goroutines, channels, slices, maps, structs, interfaces,
--        error handling, defer, pointers, fmt, concurrency

BEGIN;

INSERT INTO exercises (
  id, title_en, title_es, description_en, description_es,
  language, difficulty, category,
  starter_code, expected_output,
  hint_count, hint_1_en, hint_1_es, hint_2_en, hint_2_es, hint_3_en, hint_3_es,
  points, hints_used_penalty, created_at
) VALUES

-- ============================================================
-- DIFFICULTY 1 — 12 exercises (points: 10, penalty: 3)
-- ============================================================

-- 1. basics
(gen_random_uuid(),
 'Hello Go', 'Hola Go',
 'Print "Hello, Go!" to the console.',
 'Imprime "Hello, Go!" en la consola.',
 'go', 1, 'basics',
 'package main\n\nimport "fmt"\n\nfunc main() {\n    // your code\n}',
 'Hello, Go!',
 3,
 'Use fmt.Println to print a line.', 'Usa fmt.Println para imprimir una línea.',
 'Pass the string as an argument to fmt.Println.', 'Pasa la cadena como argumento a fmt.Println.',
 'fmt.Println("Hello, Go!")', 'fmt.Println("Hello, Go!")',
 10, 3, now()),

-- 2. basics
(gen_random_uuid(),
 'Declare a Variable', 'Declarar una Variable',
 'Declare an integer variable named age with value 30 and print it.',
 'Declara una variable entera llamada age con valor 30 e imprímela.',
 'go', 1, 'basics',
 'package main\n\nimport "fmt"\n\nfunc main() {\n    // your code\n}',
 '30',
 3,
 'Use var or the := short declaration.', 'Usa var o la declaración corta :=.',
 'age := 30 declares and assigns in one step.', 'age := 30 declara y asigna en un solo paso.',
 'age := 30\nfmt.Println(age)', 'age := 30\nfmt.Println(age)',
 10, 3, now()),

-- 3. basics
(gen_random_uuid(),
 'String Concatenation', 'Concatenación de Cadenas',
 'Declare two strings "Hello" and "World", concatenate them with a space and print.',
 'Declara dos cadenas "Hello" y "World", concaténalas con un espacio e imprime.',
 'go', 1, 'basics',
 'package main\n\nimport "fmt"\n\nfunc main() {\n    // your code\n}',
 'Hello World',
 3,
 'Use the + operator to join strings.', 'Usa el operador + para unir cadenas.',
 'Add a space between the two strings.', 'Agrega un espacio entre las dos cadenas.',
 'fmt.Println(a + " " + b)', 'fmt.Println(a + " " + b)',
 10, 3, now()),

-- 4. basics
(gen_random_uuid(),
 'Simple Addition', 'Suma Simple',
 'Declare two integers 7 and 3, print their sum.',
 'Declara dos enteros 7 y 3, imprime su suma.',
 'go', 1, 'math',
 'package main\n\nimport "fmt"\n\nfunc main() {\n    // your code\n}',
 '10',
 3,
 'Declare a and b with :=.', 'Declara a y b con :=.',
 'Use the + operator.', 'Usa el operador +.',
 'fmt.Println(a + b)', 'fmt.Println(a + b)',
 10, 3, now()),

-- 5. basics
(gen_random_uuid(),
 'Boolean Variable', 'Variable Booleana',
 'Declare a boolean variable isReady with value true and print it.',
 'Declara una variable booleana isReady con valor true e imprímela.',
 'go', 1, 'basics',
 'package main\n\nimport "fmt"\n\nfunc main() {\n    // your code\n}',
 'true',
 3,
 'Use bool as the type or := for inference.', 'Usa bool como tipo o := para inferencia.',
 'isReady := true assigns a boolean.', 'isReady := true asigna un booleano.',
 'isReady := true\nfmt.Println(isReady)', 'isReady := true\nfmt.Println(isReady)',
 10, 3, now()),

-- 6. fmt
(gen_random_uuid(),
 'Formatted Print', 'Impresión Formateada',
 'Use fmt.Printf to print "Name: Alice, Age: 25" using format verbs.',
 'Usa fmt.Printf para imprimir "Name: Alice, Age: 25" con verbos de formato.',
 'go', 1, 'fmt',
 'package main\n\nimport "fmt"\n\nfunc main() {\n    // your code\n}',
 'Name: Alice, Age: 25',
 3,
 'fmt.Printf uses %s for strings and %d for integers.', 'fmt.Printf usa %s para cadenas y %d para enteros.',
 'Pass name and age as extra arguments after the format string.', 'Pasa name y age como argumentos adicionales tras la cadena de formato.',
 'fmt.Printf("Name: %s, Age: %d", "Alice", 25)', 'fmt.Printf("Name: %s, Age: %d", "Alice", 25)',
 10, 3, now()),

-- 7. basics
(gen_random_uuid(),
 'For Loop', 'Bucle For',
 'Print numbers 1 through 5, each on its own line.',
 'Imprime los números del 1 al 5, cada uno en su propia línea.',
 'go', 1, 'control-flow',
 'package main\n\nimport "fmt"\n\nfunc main() {\n    // your code\n}',
 '1\n2\n3\n4\n5',
 3,
 'Go only has one loop keyword: for.', 'Go solo tiene una palabra clave de bucle: for.',
 'Use for i := 1; i <= 5; i++.', 'Usa for i := 1; i <= 5; i++.',
 'fmt.Println(i) inside the loop body.', 'fmt.Println(i) dentro del cuerpo del bucle.',
 10, 3, now()),

-- 8. basics
(gen_random_uuid(),
 'If / Else', 'If / Else',
 'Declare x = 10. If x > 5 print "big", else print "small".',
 'Declara x = 10. Si x > 5 imprime "big", si no imprime "small".',
 'go', 1, 'control-flow',
 'package main\n\nimport "fmt"\n\nfunc main() {\n    // your code\n}',
 'big',
 3,
 'Use if/else without parentheses around the condition.', 'Usa if/else sin paréntesis alrededor de la condición.',
 'x := 10, then compare with >.', 'x := 10, luego compara con >.',
 'if x > 5 { fmt.Println("big") } else { fmt.Println("small") }', 'if x > 5 { fmt.Println("big") } else { fmt.Println("small") }',
 10, 3, now()),

-- 9. functions
(gen_random_uuid(),
 'Simple Function', 'Función Simple',
 'Write a function add(a, b int) int that returns the sum. Call it with 4 and 6 and print the result.',
 'Escribe una función add(a, b int) int que retorne la suma. Llámala con 4 y 6 e imprime el resultado.',
 'go', 1, 'functions',
 'package main\n\nimport "fmt"\n\nfunc main() {\n    // your code\n}',
 '10',
 3,
 'Define the function above main or below it.', 'Define la función arriba o abajo de main.',
 'func add(a, b int) int { return a + b }', 'func add(a, b int) int { return a + b }',
 'fmt.Println(add(4, 6))', 'fmt.Println(add(4, 6))',
 10, 3, now()),

-- 10. slices
(gen_random_uuid(),
 'Create a Slice', 'Crear un Slice',
 'Create a slice of integers [1, 2, 3, 4, 5] and print it.',
 'Crea un slice de enteros [1, 2, 3, 4, 5] e imprímelo.',
 'go', 1, 'slices',
 'package main\n\nimport "fmt"\n\nfunc main() {\n    // your code\n}',
 '[1 2 3 4 5]',
 3,
 'Use a slice literal: []int{1, 2, 3, 4, 5}.', 'Usa un literal de slice: []int{1, 2, 3, 4, 5}.',
 'Assign to a variable and print with fmt.Println.', 'Asigna a una variable e imprime con fmt.Println.',
 'nums := []int{1, 2, 3, 4, 5}\nfmt.Println(nums)', 'nums := []int{1, 2, 3, 4, 5}\nfmt.Println(nums)',
 10, 3, now()),

-- 11. maps
(gen_random_uuid(),
 'Create a Map', 'Crear un Mapa',
 'Create a map with key "name" and value "Alice", then print the value.',
 'Crea un mapa con clave "name" y valor "Alice", luego imprime el valor.',
 'go', 1, 'maps',
 'package main\n\nimport "fmt"\n\nfunc main() {\n    // your code\n}',
 'Alice',
 3,
 'Use map[string]string{"name": "Alice"}.', 'Usa map[string]string{"name": "Alice"}.',
 'Access a map value with m["key"].', 'Accede al valor del mapa con m["key"].',
 'fmt.Println(m["name"])', 'fmt.Println(m["name"])',
 10, 3, now()),

-- 12. defer
(gen_random_uuid(),
 'Defer Basics', 'Bases de Defer',
 'Use defer to print "world" so the output is "hello\nworld".',
 'Usa defer para imprimir "world" de modo que la salida sea "hello\nworld".',
 'go', 1, 'defer',
 'package main\n\nimport "fmt"\n\nfunc main() {\n    // your code\n}',
 'hello\nworld',
 3,
 'defer delays execution until the surrounding function returns.', 'defer retrasa la ejecución hasta que la función que lo contiene retorna.',
 'Place defer fmt.Println("world") before fmt.Println("hello").', 'Coloca defer fmt.Println("world") antes de fmt.Println("hello").',
 'defer fmt.Println("world")\nfmt.Println("hello")', 'defer fmt.Println("world")\nfmt.Println("hello")',
 10, 3, now()),

-- ============================================================
-- DIFFICULTY 2 — 12 exercises (points: 20, penalty: 3)
-- ============================================================

-- 13. slices
(gen_random_uuid(),
 'Append to Slice', 'Agregar a un Slice',
 'Start with []int{1, 2, 3}, append 4 and 5, then print the result.',
 'Comienza con []int{1, 2, 3}, agrega 4 y 5, luego imprime el resultado.',
 'go', 2, 'slices',
 'package main\n\nimport "fmt"\n\nfunc main() {\n    // your code\n}',
 '[1 2 3 4 5]',
 3,
 'Use the built-in append function.', 'Usa la función built-in append.',
 'append returns a new slice; reassign the variable.', 'append retorna un nuevo slice; reasigna la variable.',
 'nums = append(nums, 4, 5)', 'nums = append(nums, 4, 5)',
 20, 3, now()),

-- 14. slices
(gen_random_uuid(),
 'Slice Range Loop', 'Bucle Range sobre Slice',
 'Iterate over []string{"a", "b", "c"} with range and print each element.',
 'Itera sobre []string{"a", "b", "c"} con range e imprime cada elemento.',
 'go', 2, 'slices',
 'package main\n\nimport "fmt"\n\nfunc main() {\n    // your code\n}',
 'a\nb\nc',
 3,
 'Use for _, v := range slice.', 'Usa for _, v := range slice.',
 'Use _ to discard the index if you only need the value.', 'Usa _ para descartar el índice si solo necesitas el valor.',
 'for _, v := range items { fmt.Println(v) }', 'for _, v := range items { fmt.Println(v) }',
 20, 3, now()),

-- 15. maps
(gen_random_uuid(),
 'Map Iteration', 'Iteración de Mapa',
 'Create a map scores with keys "Alice":90 and "Bob":85. Print the sum of all values.',
 'Crea un mapa scores con claves "Alice":90 y "Bob":85. Imprime la suma de todos los valores.',
 'go', 2, 'maps',
 'package main\n\nimport "fmt"\n\nfunc main() {\n    // your code\n}',
 '175',
 3,
 'Use for k, v := range m to iterate a map.', 'Usa for k, v := range m para iterar un mapa.',
 'Accumulate the sum in a variable initialized to 0.', 'Acumula la suma en una variable inicializada en 0.',
 'sum += v inside the range loop.', 'sum += v dentro del bucle range.',
 20, 3, now()),

-- 16. structs
(gen_random_uuid(),
 'Define a Struct', 'Definir un Struct',
 'Define a struct Person with fields Name string and Age int. Create one instance and print Name and Age.',
 'Define un struct Person con campos Name string y Age int. Crea una instancia e imprime Name y Age.',
 'go', 2, 'structs',
 'package main\n\nimport "fmt"\n\nfunc main() {\n    // your code\n}',
 'Alice 30',
 3,
 'Declare the struct type outside main with type Person struct {...}.', 'Declara el tipo struct fuera de main con type Person struct {...}.',
 'Create an instance: p := Person{Name: "Alice", Age: 30}.', 'Crea una instancia: p := Person{Name: "Alice", Age: 30}.',
 'fmt.Println(p.Name, p.Age)', 'fmt.Println(p.Name, p.Age)',
 20, 3, now()),

-- 17. pointers
(gen_random_uuid(),
 'Pointer Basics', 'Bases de Punteros',
 'Declare an integer x = 42. Create a pointer to it and print the dereferenced value.',
 'Declara un entero x = 42. Crea un puntero a él e imprime el valor desreferenciado.',
 'go', 2, 'pointers',
 'package main\n\nimport "fmt"\n\nfunc main() {\n    // your code\n}',
 '42',
 3,
 'Use & to get the address of a variable.', 'Usa & para obtener la dirección de una variable.',
 'Use * to dereference a pointer and read its value.', 'Usa * para desreferenciar un puntero y leer su valor.',
 'p := &x\nfmt.Println(*p)', 'p := &x\nfmt.Println(*p)',
 20, 3, now()),

-- 18. functions
(gen_random_uuid(),
 'Multiple Return Values', 'Múltiples Valores de Retorno',
 'Write a function divide(a, b float64) that returns the quotient and a bool indicating success. Print 10/2 result.',
 'Escribe una función divide(a, b float64) que retorne el cociente y un bool de éxito. Imprime el resultado de 10/2.',
 'go', 2, 'functions',
 'package main\n\nimport "fmt"\n\nfunc main() {\n    // your code\n}',
 '5 true',
 3,
 'Go functions can return multiple values: func f() (float64, bool).', 'Las funciones Go pueden retornar múltiples valores: func f() (float64, bool).',
 'Return b != 0 as the success boolean.', 'Retorna b != 0 como el booleano de éxito.',
 'result, ok := divide(10, 2)\nfmt.Println(result, ok)', 'result, ok := divide(10, 2)\nfmt.Println(result, ok)',
 20, 3, now()),

-- 19. error handling
(gen_random_uuid(),
 'Return an Error', 'Retornar un Error',
 'Write a function sqrt(x float64) that returns an error if x < 0, otherwise the square root.',
 'Escribe una función sqrt(x float64) que retorne un error si x < 0, de lo contrario la raíz cuadrada.',
 'go', 2, 'error-handling',
 'package main\n\nimport "fmt"\n\nfunc main() {\n    // your code\n}',
 'cannot sqrt negative number',
 3,
 'Import "errors" and use errors.New("message").', 'Importa "errors" y usa errors.New("message").',
 'Return (0, errors.New(...)) for invalid input.', 'Retorna (0, errors.New(...)) para entrada inválida.',
 'if err != nil { fmt.Println(err) }', 'if err != nil { fmt.Println(err) }',
 20, 3, now()),

-- 20. defer
(gen_random_uuid(),
 'Defer Stack', 'Pila de Defer',
 'Use three defer statements to print "c", "b", "a" in order (defers run LIFO).',
 'Usa tres sentencias defer para imprimir "c", "b", "a" en orden (los defers corren LIFO).',
 'go', 2, 'defer',
 'package main\n\nimport "fmt"\n\nfunc main() {\n    // your code\n}',
 'c\nb\na',
 3,
 'defer statements execute in last-in, first-out order.', 'Las sentencias defer se ejecutan en orden último en entrar, primero en salir.',
 'Declare them in the order a, b, c — they will print c, b, a.', 'Declára los en el orden a, b, c — imprimirán c, b, a.',
 'defer fmt.Println("a")\ndefer fmt.Println("b")\ndefer fmt.Println("c")', 'defer fmt.Println("a")\ndefer fmt.Println("b")\ndefer fmt.Println("c")',
 20, 3, now()),

-- 21. slices
(gen_random_uuid(),
 'Slice Length and Capacity', 'Longitud y Capacidad de Slice',
 'Create a slice with make([]int, 3, 5). Print its length and capacity.',
 'Crea un slice con make([]int, 3, 5). Imprime su longitud y capacidad.',
 'go', 2, 'slices',
 'package main\n\nimport "fmt"\n\nfunc main() {\n    // your code\n}',
 '3 5',
 3,
 'Use make([]T, len, cap) to create a slice with given length and capacity.', 'Usa make([]T, len, cap) para crear un slice con longitud y capacidad dadas.',
 'len() returns length; cap() returns capacity.', 'len() retorna la longitud; cap() retorna la capacidad.',
 'fmt.Println(len(s), cap(s))', 'fmt.Println(len(s), cap(s))',
 20, 3, now()),

-- 22. maps
(gen_random_uuid(),
 'Map Existence Check', 'Verificar Existencia en Mapa',
 'Check if key "cat" exists in map{"dog": 1, "bird": 2}. Print "found" or "not found".',
 'Verifica si la clave "cat" existe en map{"dog": 1, "bird": 2}. Imprime "found" o "not found".',
 'go', 2, 'maps',
 'package main\n\nimport "fmt"\n\nfunc main() {\n    // your code\n}',
 'not found',
 3,
 'A map lookup returns two values: value and a bool ok.', 'Una búsqueda en mapa retorna dos valores: el valor y un bool ok.',
 'Use _, ok := m["cat"] to check existence.', 'Usa _, ok := m["cat"] para verificar existencia.',
 'if ok { fmt.Println("found") } else { fmt.Println("not found") }', 'if ok { fmt.Println("found") } else { fmt.Println("not found") }',
 20, 3, now()),

-- 23. structs
(gen_random_uuid(),
 'Struct Method', 'Método de Struct',
 'Add a method Greet() to Person that prints "Hello, I am <Name>". Call it on an instance.',
 'Agrega un método Greet() a Person que imprima "Hello, I am <Name>". Llámalo en una instancia.',
 'go', 2, 'structs',
 'package main\n\nimport "fmt"\n\nfunc main() {\n    // your code\n}',
 'Hello, I am Alice',
 3,
 'Define the method with a value receiver: func (p Person) Greet().', 'Define el método con un receptor de valor: func (p Person) Greet().',
 'Inside Greet, use p.Name to access the field.', 'Dentro de Greet, usa p.Name para acceder al campo.',
 'fmt.Println("Hello, I am", p.Name)', 'fmt.Println("Hello, I am", p.Name)',
 20, 3, now()),

-- 24. pointers
(gen_random_uuid(),
 'Modify via Pointer', 'Modificar con Puntero',
 'Write a function double(n *int) that multiplies the value at n by 2. Apply it to x=5 and print x.',
 'Escribe una función double(n *int) que multiplique por 2 el valor en n. Aplícala a x=5 e imprime x.',
 'go', 2, 'pointers',
 'package main\n\nimport "fmt"\n\nfunc main() {\n    // your code\n}',
 '10',
 3,
 'Dereference the pointer to modify the value: *n = *n * 2.', 'Desreferencia el puntero para modificar el valor: *n = *n * 2.',
 'Pass &x when calling the function.', 'Pasa &x al llamar la función.',
 'double(&x)\nfmt.Println(x)', 'double(&x)\nfmt.Println(x)',
 20, 3, now()),

-- ============================================================
-- DIFFICULTY 3 — 13 exercises (points: 30, penalty: 5)
-- ============================================================

-- 25. interfaces
(gen_random_uuid(),
 'Define an Interface', 'Definir una Interfaz',
 'Define a Shape interface with Area() float64. Implement it for a Rectangle with width=4 and height=5. Print the area.',
 'Define una interfaz Shape con Area() float64. Impleméntala para un Rectangle con width=4 y height=5. Imprime el área.',
 'go', 3, 'interfaces',
 'package main\n\nimport "fmt"\n\nfunc main() {\n    // your code\n}',
 '20',
 3,
 'An interface is satisfied implicitly when all methods are implemented.', 'Una interfaz se satisface implícitamente cuando todos los métodos están implementados.',
 'Define Rectangle struct with Width and Height fields.', 'Define el struct Rectangle con campos Width y Height.',
 'func (r Rectangle) Area() float64 { return r.Width * r.Height }', 'func (r Rectangle) Area() float64 { return r.Width * r.Height }',
 30, 5, now()),

-- 26. goroutines
(gen_random_uuid(),
 'Launch a Goroutine', 'Lanzar una Goroutine',
 'Launch a goroutine that prints "goroutine running". Use a channel to wait for it to finish.',
 'Lanza una goroutine que imprima "goroutine running". Usa un canal para esperar a que termine.',
 'go', 3, 'goroutines',
 'package main\n\nimport "fmt"\n\nfunc main() {\n    // your code\n}',
 'goroutine running',
 3,
 'Use go func() {...}() to launch an anonymous goroutine.', 'Usa go func() {...}() para lanzar una goroutine anónima.',
 'Create a done channel: done := make(chan struct{}).', 'Crea un canal done: done := make(chan struct{}).',
 'Send to done inside the goroutine; receive <-done in main.', 'Envía a done dentro de la goroutine; recibe <-done en main.',
 30, 5, now()),

-- 27. channels
(gen_random_uuid(),
 'Channel Send and Receive', 'Envío y Recepción de Canal',
 'Create an unbuffered int channel. Send 42 from a goroutine and receive and print it in main.',
 'Crea un canal int sin buffer. Envía 42 desde una goroutine y recíbelo e imprímelo en main.',
 'go', 3, 'channels',
 'package main\n\nimport "fmt"\n\nfunc main() {\n    // your code\n}',
 '42',
 3,
 'Create the channel: ch := make(chan int).', 'Crea el canal: ch := make(chan int).',
 'Send in a goroutine: go func() { ch <- 42 }().', 'Envía en una goroutine: go func() { ch <- 42 }().',
 'Receive in main: val := <-ch.', 'Recibe en main: val := <-ch.',
 30, 5, now()),

-- 28. error handling
(gen_random_uuid(),
 'Custom Error Type', 'Tipo de Error Personalizado',
 'Create a ValidationError struct with a Message field. Implement the error interface on it. Return one and print its message.',
 'Crea un struct ValidationError con un campo Message. Implementa la interfaz error en él. Retorna uno e imprime su mensaje.',
 'go', 3, 'error-handling',
 'package main\n\nimport "fmt"\n\nfunc main() {\n    // your code\n}',
 'validation failed: name is empty',
 3,
 'Implement error by defining func (e ValidationError) Error() string.', 'Implementa error definiendo func (e ValidationError) Error() string.',
 'Return the Message field from Error().', 'Retorna el campo Message desde Error().',
 'fmt.Println(err.Error())', 'fmt.Println(err.Error())',
 30, 5, now()),

-- 29. slices
(gen_random_uuid(),
 'Filter a Slice', 'Filtrar un Slice',
 'Filter []int{1,2,3,4,5,6} to keep only even numbers and print the result.',
 'Filtra []int{1,2,3,4,5,6} para conservar solo números pares e imprime el resultado.',
 'go', 3, 'slices',
 'package main\n\nimport "fmt"\n\nfunc main() {\n    // your code\n}',
 '[2 4 6]',
 3,
 'Build a new slice and append elements that satisfy the condition.', 'Construye un nuevo slice y agrega los elementos que cumplen la condición.',
 'Use n%2 == 0 to check if a number is even.', 'Usa n%2 == 0 para verificar si un número es par.',
 'result = append(result, n)', 'result = append(result, n)',
 30, 5, now()),

-- 30. structs
(gen_random_uuid(),
 'Pointer Receiver Method', 'Método con Receptor Puntero',
 'Add a method SetAge(age int) to Person using a pointer receiver. Update age to 35 and print.',
 'Agrega un método SetAge(age int) a Person usando un receptor puntero. Actualiza la edad a 35 e imprime.',
 'go', 3, 'structs',
 'package main\n\nimport "fmt"\n\nfunc main() {\n    // your code\n}',
 '35',
 3,
 'Use a pointer receiver to mutate the struct: func (p *Person) SetAge(age int).', 'Usa un receptor puntero para mutar el struct: func (p *Person) SetAge(age int).',
 'Inside SetAge, assign p.Age = age.', 'Dentro de SetAge, asigna p.Age = age.',
 'p.SetAge(35)\nfmt.Println(p.Age)', 'p.SetAge(35)\nfmt.Println(p.Age)',
 30, 5, now()),

-- 31. maps
(gen_random_uuid(),
 'Word Frequency Count', 'Conteo de Frecuencia de Palabras',
 'Count word frequencies in []string{"go","is","great","go","is","go"}. Print the count for "go".',
 'Cuenta las frecuencias de palabras en []string{"go","is","great","go","is","go"}. Imprime el conteo de "go".',
 'go', 3, 'maps',
 'package main\n\nimport "fmt"\n\nfunc main() {\n    // your code\n}',
 '3',
 3,
 'Use a map[string]int to accumulate counts.', 'Usa un map[string]int para acumular conteos.',
 'Initialize with freq := make(map[string]int).', 'Inicializa con freq := make(map[string]int).',
 'freq[word]++ inside the range loop.', 'freq[word]++ dentro del bucle range.',
 30, 5, now()),

-- 32. goroutines
(gen_random_uuid(),
 'Multiple Goroutines with WaitGroup', 'Múltiples Goroutines con WaitGroup',
 'Launch 3 goroutines each printing their index. Use sync.WaitGroup to wait for all.',
 'Lanza 3 goroutines que impriman su índice. Usa sync.WaitGroup para esperar a todas.',
 'go', 3, 'goroutines',
 'package main\n\nimport (\n    "fmt"\n    "sync"\n)\n\nfunc main() {\n    // your code\n}',
 '0\n1\n2',
 3,
 'Declare var wg sync.WaitGroup and call wg.Add(3).', 'Declara var wg sync.WaitGroup y llama wg.Add(3).',
 'Call wg.Done() at the end of each goroutine.', 'Llama wg.Done() al final de cada goroutine.',
 'wg.Wait() blocks until all goroutines call Done.', 'wg.Wait() bloquea hasta que todas las goroutines llamen Done.',
 30, 5, now()),

-- 33. channels
(gen_random_uuid(),
 'Buffered Channel', 'Canal con Buffer',
 'Create a buffered channel of capacity 3. Send 10, 20, 30 without a goroutine, then receive and print all.',
 'Crea un canal con buffer de capacidad 3. Envía 10, 20, 30 sin goroutine, luego recibe e imprime todos.',
 'go', 3, 'channels',
 'package main\n\nimport "fmt"\n\nfunc main() {\n    // your code\n}',
 '10\n20\n30',
 3,
 'Buffered channels do not block on send until full: make(chan int, 3).', 'Los canales con buffer no bloquean en envío hasta llenarse: make(chan int, 3).',
 'Send with ch <- value three times.', 'Envía con ch <- value tres veces.',
 'Receive with fmt.Println(<-ch) three times.', 'Recibe con fmt.Println(<-ch) tres veces.',
 30, 5, now()),

-- 34. interfaces
(gen_random_uuid(),
 'Interface Polymorphism', 'Polimorfismo con Interfaces',
 'Define Animal interface with Speak() string. Implement for Dog ("Woof") and Cat ("Meow"). Print both via the interface.',
 'Define la interfaz Animal con Speak() string. Impleméntala para Dog ("Woof") y Cat ("Meow"). Imprime ambos mediante la interfaz.',
 'go', 3, 'interfaces',
 'package main\n\nimport "fmt"\n\nfunc main() {\n    // your code\n}',
 'Woof\nMeow',
 3,
 'Both Dog and Cat must have a Speak() string method.', 'Tanto Dog como Cat deben tener un método Speak() string.',
 'Store them in a []Animal slice and iterate.', 'Guárdalos en un slice []Animal e itera.',
 'fmt.Println(a.Speak()) inside the range loop.', 'fmt.Println(a.Speak()) dentro del bucle range.',
 30, 5, now()),

-- 35. error handling
(gen_random_uuid(),
 'Panic and Recover', 'Panic y Recover',
 'Write a function safeDivide(a, b int) that recovers from a divide-by-zero panic and returns 0. Print safeDivide(10, 0).',
 'Escribe una función safeDivide(a, b int) que se recupere de un panic de división por cero y retorne 0. Imprime safeDivide(10, 0).',
 'go', 3, 'error-handling',
 'package main\n\nimport "fmt"\n\nfunc main() {\n    // your code\n}',
 '0',
 3,
 'Use defer with recover() to catch panics.', 'Usa defer con recover() para atrapar panics.',
 'Panic when b == 0 using panic("division by zero").', 'Haz panic cuando b == 0 usando panic("division by zero").',
 'recover() returns the panic value; return 0 from the deferred func.', 'recover() retorna el valor del panic; retorna 0 desde la función diferida.',
 30, 5, now()),

-- 36. fmt
(gen_random_uuid(),
 'Sprintf to Build String', 'Sprintf para Construir Cadena',
 'Use fmt.Sprintf to build the string "Item: apple, Price: 1.50" and print it.',
 'Usa fmt.Sprintf para construir la cadena "Item: apple, Price: 1.50" e imprímela.',
 'go', 3, 'fmt',
 'package main\n\nimport "fmt"\n\nfunc main() {\n    // your code\n}',
 'Item: apple, Price: 1.50',
 3,
 'fmt.Sprintf returns a string instead of printing.', 'fmt.Sprintf retorna una cadena en lugar de imprimir.',
 'Use %s for the item name and %.2f for the price.', 'Usa %s para el nombre del artículo y %.2f para el precio.',
 's := fmt.Sprintf("Item: %s, Price: %.2f", "apple", 1.50)', 's := fmt.Sprintf("Item: %s, Price: %.2f", "apple", 1.50)',
 30, 5, now()),

-- 37. slices
(gen_random_uuid(),
 'Two-Dimensional Slice', 'Slice Bidimensional',
 'Create a 2x3 int matrix initialized to all zeros and print it.',
 'Crea una matriz int de 2x3 inicializada a ceros e imprímela.',
 'go', 3, 'slices',
 'package main\n\nimport "fmt"\n\nfunc main() {\n    // your code\n}',
 '[[0 0 0] [0 0 0]]',
 3,
 'Use make([][]int, rows) then make([]int, cols) per row.', 'Usa make([][]int, rows) y luego make([]int, cols) por fila.',
 'Assign each row in a loop: matrix[i] = make([]int, 3).', 'Asigna cada fila en un bucle: matrix[i] = make([]int, 3).',
 'fmt.Println(matrix) prints the nested slice.', 'fmt.Println(matrix) imprime el slice anidado.',
 30, 5, now()),

-- ============================================================
-- DIFFICULTY 4 — 8 exercises (points: 50, penalty: 10)
-- ============================================================

-- 38. channels
(gen_random_uuid(),
 'Fan-Out with Channels', 'Fan-Out con Canales',
 'Send numbers 1-5 on a channel from one goroutine. Receive and print each in main using a for-range over the channel.',
 'Envía los números 1-5 en un canal desde una goroutine. Recibe e imprime cada uno en main usando for-range sobre el canal.',
 'go', 4, 'channels',
 'package main\n\nimport "fmt"\n\nfunc main() {\n    // your code\n}',
 '1\n2\n3\n4\n5',
 3,
 'Close the channel after sending so for-range knows when to stop.', 'Cierra el canal después de enviar para que for-range sepa cuándo parar.',
 'Use close(ch) at the end of the sender goroutine.', 'Usa close(ch) al final de la goroutine emisora.',
 'for v := range ch { fmt.Println(v) } in main.', 'for v := range ch { fmt.Println(v) } en main.',
 50, 10, now()),

-- 39. goroutines
(gen_random_uuid(),
 'Pipeline Pattern', 'Patrón Pipeline',
 'Build a two-stage pipeline: stage1 generates 1-5 on a channel; stage2 doubles each value; main prints the results.',
 'Construye un pipeline de dos etapas: stage1 genera 1-5 en un canal; stage2 duplica cada valor; main imprime los resultados.',
 'go', 4, 'goroutines',
 'package main\n\nimport "fmt"\n\nfunc main() {\n    // your code\n}',
 '2\n4\n6\n8\n10',
 3,
 'Each stage is a function that receives an input channel and returns an output channel.', 'Cada etapa es una función que recibe un canal de entrada y retorna uno de salida.',
 'Launch stage functions as goroutines; close the channel when done.', 'Lanza las funciones de etapa como goroutines; cierra el canal al terminar.',
 'for v := range out { fmt.Println(v) } reads the final channel.', 'for v := range out { fmt.Println(v) } lee el canal final.',
 50, 10, now()),

-- 40. interfaces
(gen_random_uuid(),
 'Stringer Interface', 'Interfaz Stringer',
 'Implement fmt.Stringer on a Point struct {X, Y int} so fmt.Println(p) prints "(3, 4)".',
 'Implementa fmt.Stringer en un struct Point {X, Y int} para que fmt.Println(p) imprima "(3, 4)".',
 'go', 4, 'interfaces',
 'package main\n\nimport "fmt"\n\nfunc main() {\n    // your code\n}',
 '(3, 4)',
 3,
 'fmt.Stringer requires a String() string method.', 'fmt.Stringer requiere un método String() string.',
 'Use fmt.Sprintf inside String() to format the output.', 'Usa fmt.Sprintf dentro de String() para formatear la salida.',
 'func (p Point) String() string { return fmt.Sprintf("(%d, %d)", p.X, p.Y) }', 'func (p Point) String() string { return fmt.Sprintf("(%d, %d)", p.X, p.Y) }',
 50, 10, now()),

-- 41. goroutines
(gen_random_uuid(),
 'Select Statement', 'Sentencia Select',
 'Create two channels. Send "ping" on ch1 and "pong" on ch2 from goroutines. Use select to receive and print whichever arrives first.',
 'Crea dos canales. Envía "ping" en ch1 y "pong" en ch2 desde goroutines. Usa select para recibir e imprimir el que llegue primero.',
 'go', 4, 'goroutines',
 'package main\n\nimport "fmt"\n\nfunc main() {\n    // your code\n}',
 'ping',
 3,
 'select blocks until one of its cases can proceed.', 'select bloquea hasta que uno de sus casos puede proceder.',
 'case msg := <-ch1: and case msg := <-ch2: are valid select cases.', 'case msg := <-ch1: y case msg := <-ch2: son casos válidos de select.',
 'fmt.Println(msg) prints whichever was received.', 'fmt.Println(msg) imprime el que fue recibido.',
 50, 10, now()),

-- 42. error handling
(gen_random_uuid(),
 'Wrapping Errors', 'Envolver Errores',
 'Use fmt.Errorf with %w to wrap an error. Unwrap it with errors.Is and print "base error found: true".',
 'Usa fmt.Errorf con %w para envolver un error. Desenvuélvelo con errors.Is e imprime "base error found: true".',
 'go', 4, 'error-handling',
 'package main\n\nimport (\n    "errors"\n    "fmt"\n)\n\nfunc main() {\n    // your code\n}',
 'base error found: true',
 3,
 'Create a sentinel error: var ErrBase = errors.New("base").', 'Crea un error centinela: var ErrBase = errors.New("base").',
 'Wrap it: wrapped := fmt.Errorf("operation failed: %w", ErrBase).', 'Envuélvelo: wrapped := fmt.Errorf("operation failed: %w", ErrBase).',
 'errors.Is(wrapped, ErrBase) returns true.', 'errors.Is(wrapped, ErrBase) retorna true.',
 50, 10, now()),

-- 43. maps
(gen_random_uuid(),
 'Group By with Maps', 'Agrupar con Mapas',
 'Group []string{"apple","avocado","banana","blueberry","cherry"} by first letter. Print the group for key "b".',
 'Agrupa []string{"apple","avocado","banana","blueberry","cherry"} por primera letra. Imprime el grupo para la clave "b".',
 'go', 4, 'maps',
 'package main\n\nimport "fmt"\n\nfunc main() {\n    // your code\n}',
 '[banana blueberry]',
 3,
 'Use map[string][]string to map a letter to a slice of words.', 'Usa map[string][]string para mapear una letra a un slice de palabras.',
 'Get the first letter with string(word[0]).', 'Obtén la primera letra con string(word[0]).',
 'groups[key] = append(groups[key], word)', 'groups[key] = append(groups[key], word)',
 50, 10, now()),

-- 44. structs
(gen_random_uuid(),
 'Embedded Structs', 'Structs Embebidos',
 'Embed an Address struct (City, Country) inside a Person struct. Print city and country of a person.',
 'Embebe un struct Address (City, Country) dentro de un struct Person. Imprime ciudad y país de una persona.',
 'go', 4, 'structs',
 'package main\n\nimport "fmt"\n\nfunc main() {\n    // your code\n}',
 'London UK',
 3,
 'Embed by including Address without a field name inside Person.', 'Embebe incluyendo Address sin nombre de campo dentro de Person.',
 'Embedded fields are promoted: p.City works directly.', 'Los campos embebidos son promovidos: p.City funciona directamente.',
 'fmt.Println(p.City, p.Country)', 'fmt.Println(p.City, p.Country)',
 50, 10, now()),

-- 45. concurrency
(gen_random_uuid(),
 'Mutex for Shared State', 'Mutex para Estado Compartido',
 'Use sync.Mutex to safely increment a counter from 100 goroutines. Print the final count.',
 'Usa sync.Mutex para incrementar con seguridad un contador desde 100 goroutines. Imprime el conteo final.',
 'go', 4, 'concurrency',
 'package main\n\nimport (\n    "fmt"\n    "sync"\n)\n\nfunc main() {\n    // your code\n}',
 '100',
 3,
 'Declare var mu sync.Mutex alongside the counter.', 'Declara var mu sync.Mutex junto al contador.',
 'Call mu.Lock() before and mu.Unlock() after modifying the counter.', 'Llama mu.Lock() antes y mu.Unlock() después de modificar el contador.',
 'Use sync.WaitGroup to wait for all goroutines before printing.', 'Usa sync.WaitGroup para esperar a todas las goroutines antes de imprimir.',
 50, 10, now()),

-- ============================================================
-- DIFFICULTY 5 — 5 exercises (points: 100, penalty: 10)
-- ============================================================

-- 46. concurrency
(gen_random_uuid(),
 'Worker Pool', 'Pool de Workers',
 'Implement a worker pool of 3 goroutines processing jobs 1-9 from a jobs channel. Each worker prints "worker <id> processed job <n>". Order may vary.',
 'Implementa un pool de 3 goroutines procesando los trabajos 1-9 desde un canal jobs. Cada worker imprime "worker <id> processed job <n>". El orden puede variar.',
 'go', 5, 'concurrency',
 'package main\n\nimport (\n    "fmt"\n    "sync"\n)\n\nfunc main() {\n    // your code\n}',
 'worker 1 processed job 1',
 3,
 'Create jobs := make(chan int, 9) and send 1-9, then close it.', 'Crea jobs := make(chan int, 9) y envía 1-9, luego ciérralo.',
 'Each worker runs for j := range jobs and processes each job.', 'Cada worker ejecuta for j := range jobs y procesa cada trabajo.',
 'Use sync.WaitGroup to wait for all workers to finish.', 'Usa sync.WaitGroup para esperar a que todos los workers terminen.',
 100, 10, now()),

-- 47. channels
(gen_random_uuid(),
 'Timeout with Select', 'Timeout con Select',
 'Use select with time.After(1*time.Second) to implement a timeout. If no value arrives on ch within 1s print "timeout".',
 'Usa select con time.After(1*time.Second) para implementar un timeout. Si no llega ningún valor en ch dentro de 1s imprime "timeout".',
 'go', 5, 'channels',
 'package main\n\nimport (\n    "fmt"\n    "time"\n)\n\nfunc main() {\n    // your code\n}',
 'timeout',
 3,
 'Create an empty channel that never receives: ch := make(chan int).', 'Crea un canal vacío que nunca recibe: ch := make(chan int).',
 'time.After returns a channel that sends after the duration.', 'time.After retorna un canal que envía después de la duración.',
 'case <-time.After(1 * time.Second): fmt.Println("timeout")', 'case <-time.After(1 * time.Second): fmt.Println("timeout")',
 100, 10, now()),

-- 48. interfaces
(gen_random_uuid(),
 'Type Assertion and Switch', 'Aserción de Tipo y Switch',
 'Write a function describe(i interface{}) that prints "int: <n>", "string: <s>", or "unknown" using a type switch.',
 'Escribe una función describe(i interface{}) que imprima "int: <n>", "string: <s>", o "unknown" usando un type switch.',
 'go', 5, 'interfaces',
 'package main\n\nimport "fmt"\n\nfunc main() {\n    // your code\n}',
 'int: 42\nstring: hello\nunknown',
 3,
 'Use switch v := i.(type) { case int: ... case string: ... default: ... }.', 'Usa switch v := i.(type) { case int: ... case string: ... default: ... }.',
 'v holds the typed value within each case.', 'v contiene el valor tipado dentro de cada case.',
 'Call describe(42), describe("hello"), describe(3.14).', 'Llama a describe(42), describe("hello"), describe(3.14).',
 100, 10, now()),

-- 49. concurrency
(gen_random_uuid(),
 'Rate Limiter with Ticker', 'Limitador de Tasa con Ticker',
 'Use time.NewTicker to process exactly 3 requests at a rate of one per 100ms. Print "request <n> processed" for each.',
 'Usa time.NewTicker para procesar exactamente 3 solicitudes a una tasa de una por 100ms. Imprime "request <n> processed" para cada una.',
 'go', 5, 'concurrency',
 'package main\n\nimport (\n    "fmt"\n    "time"\n)\n\nfunc main() {\n    // your code\n}',
 'request 1 processed\nrequest 2 processed\nrequest 3 processed',
 3,
 'ticker := time.NewTicker(100 * time.Millisecond) creates a ticker.', 'ticker := time.NewTicker(100 * time.Millisecond) crea un ticker.',
 'Read from ticker.C channel each time you want to allow a request.', 'Lee desde el canal ticker.C cada vez que quieras permitir una solicitud.',
 'Call ticker.Stop() when done to free resources.', 'Llama ticker.Stop() al terminar para liberar recursos.',
 100, 10, now()),

-- 50. concurrency
(gen_random_uuid(),
 'Concurrent Map with sync.Map', 'Mapa Concurrente con sync.Map',
 'Use sync.Map to store and load values from 5 goroutines concurrently. Each stores key "worker-<i>" with value i*10. Print all entries.',
 'Usa sync.Map para almacenar y cargar valores desde 5 goroutines concurrentemente. Cada una almacena la clave "worker-<i>" con valor i*10. Imprime todas las entradas.',
 'go', 5, 'concurrency',
 'package main\n\nimport (\n    "fmt"\n    "sync"\n)\n\nfunc main() {\n    // your code\n}',
 'worker-0: 0\nworker-1: 10\nworker-2: 20\nworker-3: 30\nworker-4: 40',
 3,
 'sync.Map has Store(key, value) and Load(key) methods.', 'sync.Map tiene métodos Store(key, value) y Load(key).',
 'Use sync.WaitGroup to wait for all goroutines before ranging.', 'Usa sync.WaitGroup para esperar a todas las goroutines antes de rangear.',
 'm.Range(func(k, v any) bool { fmt.Printf(...); return true }) iterates all entries.', 'm.Range(func(k, v any) bool { fmt.Printf(...); return true }) itera todas las entradas.',
 100, 10, now())

ON CONFLICT DO NOTHING;

COMMIT;
