-- 052_exercises_sql.sql
-- 100 SQL exercises, bilingual EN+ES
-- Distribution: diff1:25, diff2:25, diff3:25, diff4:15, diff5:10
-- Points: 10/20/30/50/100 | Penalty: 3/3/5/10/10

BEGIN;

INSERT INTO exercises (
  id, title_en, title_es, description_en, description_es,
  language, difficulty, category,
  starter_code, expected_output,
  hint_count, hint_1_en, hint_1_es, hint_2_en, hint_2_es, hint_3_en, hint_3_es,
  points, hints_used_penalty, created_at
) VALUES

-- ============================================================
-- DIFFICULTY 1 — 25 exercises (points: 10, penalty: 3)
-- ============================================================

-- 1
(gen_random_uuid(),
 'Select All Columns', 'Seleccionar Todas las Columnas',
 'Write a query to select all columns from the "employees" table.',
 'Escribe una consulta para seleccionar todas las columnas de la tabla "employees".',
 'sql', 1, 'basics',
 'SELECT ___ FROM employees;',
 'SELECT * FROM employees;',
 3,
 'Use a wildcard character to represent all columns.', 'Usa un carácter comodín para representar todas las columnas.',
 'The wildcard symbol in SQL is *.', 'El símbolo comodín en SQL es *.',
 'SELECT * FROM employees;', 'SELECT * FROM employees;',
 10, 3, now()),

-- 2
(gen_random_uuid(),
 'Filter With WHERE Equals', 'Filtrar con WHERE Igual',
 'Select all rows from "products" where the "category" equals ''electronics''.',
 'Selecciona todas las filas de "products" donde "category" sea igual a ''electronics''.',
 'sql', 1, 'basics',
 'SELECT * FROM products WHERE ___ = ___;',
 'SELECT * FROM products WHERE category = ''electronics'';',
 3,
 'Use the WHERE clause to filter rows.', 'Usa la cláusula WHERE para filtrar filas.',
 'Use = for exact string comparison, and wrap the value in single quotes.', 'Usa = para comparación exacta de texto y encierra el valor en comillas simples.',
 'SELECT * FROM products WHERE category = ''electronics'';', 'SELECT * FROM products WHERE category = ''electronics'';',
 10, 3, now()),

-- 3
(gen_random_uuid(),
 'Count All Rows', 'Contar Todas las Filas',
 'Count the total number of rows in the "orders" table.',
 'Cuenta el número total de filas en la tabla "orders".',
 'sql', 1, 'basics',
 'SELECT ___(___) FROM orders;',
 'SELECT COUNT(*) FROM orders;',
 3,
 'Use an aggregate function that counts rows.', 'Usa una función de agregación que cuente filas.',
 'COUNT(*) includes rows with NULL values.', 'COUNT(*) incluye filas con valores NULL.',
 'SELECT COUNT(*) FROM orders;', 'SELECT COUNT(*) FROM orders;',
 10, 3, now()),

-- 4
(gen_random_uuid(),
 'Order By Ascending', 'Ordenar Ascendente',
 'Select all rows from "students" ordered by "last_name" in ascending order.',
 'Selecciona todas las filas de "students" ordenadas por "last_name" en orden ascendente.',
 'sql', 1, 'basics',
 'SELECT * FROM students ORDER BY ___;',
 'SELECT * FROM students ORDER BY last_name ASC;',
 3,
 'ORDER BY is placed at the end of the query.', 'ORDER BY se coloca al final de la consulta.',
 'ASC means ascending order (A to Z, 0 to 9).', 'ASC significa orden ascendente (A a Z, 0 a 9).',
 'SELECT * FROM students ORDER BY last_name ASC;', 'SELECT * FROM students ORDER BY last_name ASC;',
 10, 3, now()),

-- 5
(gen_random_uuid(),
 'Limit Rows Returned', 'Limitar Filas Devueltas',
 'Select the first 10 rows from the "logs" table.',
 'Selecciona las primeras 10 filas de la tabla "logs".',
 'sql', 1, 'basics',
 'SELECT * FROM logs ___;',
 'SELECT * FROM logs LIMIT 10;',
 3,
 'Use a clause that restricts how many rows come back.', 'Usa una cláusula que restrinja cuántas filas se devuelven.',
 'LIMIT is placed at the very end of a SELECT query.', 'LIMIT se coloca al final de una consulta SELECT.',
 'SELECT * FROM logs LIMIT 10;', 'SELECT * FROM logs LIMIT 10;',
 10, 3, now()),

-- 6
(gen_random_uuid(),
 'Select Distinct Values', 'Seleccionar Valores Distintos',
 'Select all unique values from the "city" column in the "customers" table.',
 'Selecciona todos los valores únicos de la columna "city" en la tabla "customers".',
 'sql', 1, 'basics',
 'SELECT ___ city FROM customers;',
 'SELECT DISTINCT city FROM customers;',
 3,
 'Use a keyword between SELECT and the column name to remove duplicates.', 'Usa una palabra clave entre SELECT y el nombre de columna para eliminar duplicados.',
 'The keyword is DISTINCT.', 'La palabra clave es DISTINCT.',
 'SELECT DISTINCT city FROM customers;', 'SELECT DISTINCT city FROM customers;',
 10, 3, now()),

-- 7
(gen_random_uuid(),
 'Filter With AND', 'Filtrar con AND',
 'Select all users where "age" is greater than 21 AND "country" equals ''US''.',
 'Selecciona todos los usuarios donde "age" sea mayor a 21 Y "country" sea igual a ''US''.',
 'sql', 1, 'basics',
 'SELECT * FROM users WHERE ___ AND ___;',
 'SELECT * FROM users WHERE age > 21 AND country = ''US'';',
 3,
 'Use AND to combine multiple conditions in WHERE.', 'Usa AND para combinar múltiples condiciones en WHERE.',
 'Both conditions must be true for a row to be returned.', 'Ambas condiciones deben ser verdaderas para que se devuelva una fila.',
 'SELECT * FROM users WHERE age > 21 AND country = ''US'';', 'SELECT * FROM users WHERE age > 21 AND country = ''US'';',
 10, 3, now()),

-- 8
(gen_random_uuid(),
 'Filter With OR', 'Filtrar con OR',
 'Select all products where "category" equals ''books'' OR ''music''.',
 'Selecciona todos los productos donde "category" sea igual a ''books'' O ''music''.',
 'sql', 1, 'basics',
 'SELECT * FROM products WHERE ___ OR ___;',
 'SELECT * FROM products WHERE category = ''books'' OR category = ''music'';',
 3,
 'Use OR to match at least one of multiple conditions.', 'Usa OR para que al menos una de varias condiciones sea verdadera.',
 'Each side of OR must be a complete condition with its own column name.', 'Cada lado del OR debe ser una condición completa con su propio nombre de columna.',
 'SELECT * FROM products WHERE category = ''books'' OR category = ''music'';', 'SELECT * FROM products WHERE category = ''books'' OR category = ''music'';',
 10, 3, now()),

-- 9
(gen_random_uuid(),
 'Column Alias', 'Alias de Columna',
 'Select "first_name" from "employees" and rename it to "name" in the result.',
 'Selecciona "first_name" de "employees" y renómbralo como "name" en el resultado.',
 'sql', 1, 'basics',
 'SELECT first_name ___ name FROM employees;',
 'SELECT first_name AS name FROM employees;',
 3,
 'Use a keyword after the column name to give it an alias.', 'Usa una palabra clave después del nombre de columna para darle un alias.',
 'The keyword is AS.', 'La palabra clave es AS.',
 'SELECT first_name AS name FROM employees;', 'SELECT first_name AS name FROM employees;',
 10, 3, now()),

-- 10
(gen_random_uuid(),
 'Filter IS NULL', 'Filtrar IS NULL',
 'Select all customers where "phone" is NULL.',
 'Selecciona todos los clientes donde "phone" sea NULL.',
 'sql', 1, 'basics',
 'SELECT * FROM customers WHERE phone ___ NULL;',
 'SELECT * FROM customers WHERE phone IS NULL;',
 3,
 'You cannot use = to check for NULL in SQL.', 'No puedes usar = para verificar NULL en SQL.',
 'Use IS NULL to check for missing values.', 'Usa IS NULL para verificar valores faltantes.',
 'SELECT * FROM customers WHERE phone IS NULL;', 'SELECT * FROM customers WHERE phone IS NULL;',
 10, 3, now()),

-- 11
(gen_random_uuid(),
 'Filter IS NOT NULL', 'Filtrar IS NOT NULL',
 'Select all rows from "employees" where "manager_id" is not NULL.',
 'Selecciona todas las filas de "employees" donde "manager_id" no sea NULL.',
 'sql', 1, 'basics',
 'SELECT * FROM employees WHERE manager_id ___ NULL;',
 'SELECT * FROM employees WHERE manager_id IS NOT NULL;',
 3,
 'The opposite of IS NULL checks for present values.', 'El opuesto de IS NULL verifica valores presentes.',
 'Use IS NOT NULL.', 'Usa IS NOT NULL.',
 'SELECT * FROM employees WHERE manager_id IS NOT NULL;', 'SELECT * FROM employees WHERE manager_id IS NOT NULL;',
 10, 3, now()),

-- 12
(gen_random_uuid(),
 'Filter With IN', 'Filtrar con IN',
 'Select all orders where "status" is one of ''pending'', ''shipped'', or ''delivered''.',
 'Selecciona todos los pedidos donde "status" sea uno de ''pending'', ''shipped'' o ''delivered''.',
 'sql', 1, 'basics',
 'SELECT * FROM orders WHERE status ___ (___);',
 'SELECT * FROM orders WHERE status IN (''pending'', ''shipped'', ''delivered'');',
 3,
 'Use IN to match a column against a list of values.', 'Usa IN para comparar una columna contra una lista de valores.',
 'Enclose the list in parentheses, separated by commas.', 'Encierra la lista entre paréntesis, separada por comas.',
 'SELECT * FROM orders WHERE status IN (''pending'', ''shipped'', ''delivered'');', 'SELECT * FROM orders WHERE status IN (''pending'', ''shipped'', ''delivered'');',
 10, 3, now()),

-- 13
(gen_random_uuid(),
 'Filter With BETWEEN', 'Filtrar con BETWEEN',
 'Select all products where "price" is between 10 and 50 (inclusive).',
 'Selecciona todos los productos donde "price" esté entre 10 y 50 (inclusive).',
 'sql', 1, 'basics',
 'SELECT * FROM products WHERE price ___ 10 ___ 50;',
 'SELECT * FROM products WHERE price BETWEEN 10 AND 50;',
 3,
 'BETWEEN simplifies range checks.', 'BETWEEN simplifica las verificaciones de rango.',
 'BETWEEN is inclusive on both ends.', 'BETWEEN es inclusivo en ambos extremos.',
 'SELECT * FROM products WHERE price BETWEEN 10 AND 50;', 'SELECT * FROM products WHERE price BETWEEN 10 AND 50;',
 10, 3, now()),

-- 14
(gen_random_uuid(),
 'Filter With LIKE', 'Filtrar con LIKE',
 'Select all customers whose "email" ends with ''@gmail.com''.',
 'Selecciona todos los clientes cuyo "email" termine con ''@gmail.com''.',
 'sql', 1, 'basics',
 'SELECT * FROM customers WHERE email LIKE ___;',
 'SELECT * FROM customers WHERE email LIKE ''%@gmail.com'';',
 3,
 'Use LIKE for pattern matching in strings.', 'Usa LIKE para la coincidencia de patrones en cadenas.',
 'The % wildcard matches any sequence of characters.', 'El comodín % coincide con cualquier secuencia de caracteres.',
 'SELECT * FROM customers WHERE email LIKE ''%@gmail.com'';', 'SELECT * FROM customers WHERE email LIKE ''%@gmail.com'';',
 10, 3, now()),

-- 15
(gen_random_uuid(),
 'Simple INSERT', 'INSERT Simple',
 'Insert a new row into "categories" with id=10 and name=''sports''.',
 'Inserta una nueva fila en "categories" con id=10 y name=''sports''.',
 'sql', 1, 'basics',
 'INSERT INTO categories (___, ___) VALUES (___, ___;',
 'INSERT INTO categories (id, name) VALUES (10, ''sports'');',
 3,
 'Use INSERT INTO followed by the table and column list.', 'Usa INSERT INTO seguido de la tabla y lista de columnas.',
 'VALUES must match the column order you listed.', 'VALUES debe coincidir con el orden de columnas que listaste.',
 'INSERT INTO categories (id, name) VALUES (10, ''sports'');', 'INSERT INTO categories (id, name) VALUES (10, ''sports'');',
 10, 3, now()),

-- 16
(gen_random_uuid(),
 'Simple UPDATE', 'UPDATE Simple',
 'Update the "email" of the user with id=5 to ''new@email.com'' in the "users" table.',
 'Actualiza el "email" del usuario con id=5 a ''new@email.com'' en la tabla "users".',
 'sql', 1, 'basics',
 'UPDATE users SET ___ = ___ WHERE id = 5;',
 'UPDATE users SET email = ''new@email.com'' WHERE id = 5;',
 3,
 'Use UPDATE ... SET to change column values.', 'Usa UPDATE ... SET para cambiar valores de columna.',
 'Always include a WHERE clause to avoid updating all rows.', 'Siempre incluye una cláusula WHERE para evitar actualizar todas las filas.',
 'UPDATE users SET email = ''new@email.com'' WHERE id = 5;', 'UPDATE users SET email = ''new@email.com'' WHERE id = 5;',
 10, 3, now()),

-- 17
(gen_random_uuid(),
 'Simple DELETE', 'DELETE Simple',
 'Delete all rows from "sessions" where "expired" equals true.',
 'Elimina todas las filas de "sessions" donde "expired" sea igual a true.',
 'sql', 1, 'basics',
 'DELETE FROM sessions WHERE ___ = ___;',
 'DELETE FROM sessions WHERE expired = true;',
 3,
 'Use DELETE FROM followed by the table name.', 'Usa DELETE FROM seguido del nombre de la tabla.',
 'Add a WHERE clause to target specific rows.', 'Agrega una cláusula WHERE para apuntar a filas específicas.',
 'DELETE FROM sessions WHERE expired = true;', 'DELETE FROM sessions WHERE expired = true;',
 10, 3, now()),

-- 18
(gen_random_uuid(),
 'MAX Aggregate', 'Agregado MAX',
 'Find the highest salary from the "employees" table.',
 'Encuentra el salario más alto de la tabla "employees".',
 'sql', 1, 'basics',
 'SELECT ___(salary) FROM employees;',
 'SELECT MAX(salary) FROM employees;',
 3,
 'Use an aggregate function that returns the largest value.', 'Usa una función de agregación que devuelva el valor más grande.',
 'The function is MAX().', 'La función es MAX().',
 'SELECT MAX(salary) FROM employees;', 'SELECT MAX(salary) FROM employees;',
 10, 3, now()),

-- 19
(gen_random_uuid(),
 'MIN Aggregate', 'Agregado MIN',
 'Find the lowest price from the "products" table.',
 'Encuentra el precio más bajo de la tabla "products".',
 'sql', 1, 'basics',
 'SELECT ___(price) FROM products;',
 'SELECT MIN(price) FROM products;',
 3,
 'Use an aggregate function that returns the smallest value.', 'Usa una función de agregación que devuelva el valor más pequeño.',
 'The function is MIN().', 'La función es MIN().',
 'SELECT MIN(price) FROM products;', 'SELECT MIN(price) FROM products;',
 10, 3, now()),

-- 20
(gen_random_uuid(),
 'SUM Aggregate', 'Agregado SUM',
 'Calculate the total of all "amount" values in the "payments" table.',
 'Calcula el total de todos los valores "amount" en la tabla "payments".',
 'sql', 1, 'basics',
 'SELECT ___(amount) FROM payments;',
 'SELECT SUM(amount) FROM payments;',
 3,
 'Use an aggregate function that totals numeric values.', 'Usa una función de agregación que totalice valores numéricos.',
 'The function is SUM().', 'La función es SUM().',
 'SELECT SUM(amount) FROM payments;', 'SELECT SUM(amount) FROM payments;',
 10, 3, now()),

-- 21
(gen_random_uuid(),
 'AVG Aggregate', 'Agregado AVG',
 'Calculate the average rating from the "reviews" table.',
 'Calcula la calificación promedio de la tabla "reviews".',
 'sql', 1, 'basics',
 'SELECT ___(rating) FROM reviews;',
 'SELECT AVG(rating) FROM reviews;',
 3,
 'Use an aggregate function that computes the mean.', 'Usa una función de agregación que calcule la media.',
 'The function is AVG().', 'La función es AVG().',
 'SELECT AVG(rating) FROM reviews;', 'SELECT AVG(rating) FROM reviews;',
 10, 3, now()),

-- 22
(gen_random_uuid(),
 'Order By Descending', 'Ordenar Descendente',
 'Select all products ordered by "created_at" from newest to oldest.',
 'Selecciona todos los productos ordenados por "created_at" del más nuevo al más antiguo.',
 'sql', 1, 'basics',
 'SELECT * FROM products ORDER BY created_at ___;',
 'SELECT * FROM products ORDER BY created_at DESC;',
 3,
 'Add a keyword after the column name in ORDER BY.', 'Agrega una palabra clave después del nombre de columna en ORDER BY.',
 'DESC means descending — newest (largest) first.', 'DESC significa descendente: el más reciente (mayor) primero.',
 'SELECT * FROM products ORDER BY created_at DESC;', 'SELECT * FROM products ORDER BY created_at DESC;',
 10, 3, now()),

-- 23
(gen_random_uuid(),
 'Filter With NOT IN', 'Filtrar con NOT IN',
 'Select all employees whose "department" is NOT ''HR'' or ''Legal''.',
 'Selecciona todos los empleados cuyo "department" NO sea ''HR'' ni ''Legal''.',
 'sql', 1, 'basics',
 'SELECT * FROM employees WHERE department ___ (''HR'', ''Legal'');',
 'SELECT * FROM employees WHERE department NOT IN (''HR'', ''Legal'');',
 3,
 'Use NOT IN to exclude a set of values.', 'Usa NOT IN para excluir un conjunto de valores.',
 'NOT IN is the logical inverse of IN.', 'NOT IN es el inverso lógico de IN.',
 'SELECT * FROM employees WHERE department NOT IN (''HR'', ''Legal'');', 'SELECT * FROM employees WHERE department NOT IN (''HR'', ''Legal'');',
 10, 3, now()),

-- 24
(gen_random_uuid(),
 'Table Alias', 'Alias de Tabla',
 'Select "name" and "salary" from "employees", using the alias "e" for the table.',
 'Selecciona "name" y "salary" de "employees", usando el alias "e" para la tabla.',
 'sql', 1, 'basics',
 'SELECT e.name, e.salary FROM employees ___;',
 'SELECT e.name, e.salary FROM employees AS e;',
 3,
 'You can give a table a short alias using AS.', 'Puedes darle a una tabla un alias corto usando AS.',
 'Place AS alias_name right after the table name.', 'Coloca AS alias_nombre justo después del nombre de la tabla.',
 'SELECT e.name, e.salary FROM employees AS e;', 'SELECT e.name, e.salary FROM employees AS e;',
 10, 3, now()),

-- 25
(gen_random_uuid(),
 'Concatenate Strings', 'Concatenar Cadenas',
 'Select the full name by concatenating "first_name", a space, and "last_name" from "employees".',
 'Selecciona el nombre completo concatenando "first_name", un espacio y "last_name" de "employees".',
 'sql', 1, 'strings',
 'SELECT first_name ___ '' '' ___ last_name AS full_name FROM employees;',
 'SELECT first_name || '' '' || last_name AS full_name FROM employees;',
 3,
 'Use the string concatenation operator in SQL.', 'Usa el operador de concatenación de cadenas en SQL.',
 'In standard SQL, the || operator concatenates strings.', 'En SQL estándar, el operador || concatena cadenas.',
 'SELECT first_name || '' '' || last_name AS full_name FROM employees;', 'SELECT first_name || '' '' || last_name AS full_name FROM employees;',
 10, 3, now()),

-- ============================================================
-- DIFFICULTY 2 — 25 exercises (points: 20, penalty: 3)
-- ============================================================

-- 26
(gen_random_uuid(),
 'INNER JOIN', 'INNER JOIN',
 'Select "orders.id" and "customers.name" by joining "orders" and "customers" on customer_id.',
 'Selecciona "orders.id" y "customers.name" uniendo "orders" y "customers" por customer_id.',
 'sql', 2, 'basics',
 'SELECT o.id, c.name FROM orders AS o ___ customers AS c ON o.___ = c.id;',
 'SELECT o.id, c.name FROM orders AS o INNER JOIN customers AS c ON o.customer_id = c.id;',
 3,
 'Use a JOIN clause to combine rows from two tables.', 'Usa una cláusula JOIN para combinar filas de dos tablas.',
 'INNER JOIN returns only rows that have a matching value in both tables.', 'INNER JOIN devuelve solo las filas que tienen un valor coincidente en ambas tablas.',
 'SELECT o.id, c.name FROM orders AS o INNER JOIN customers AS c ON o.customer_id = c.id;', 'SELECT o.id, c.name FROM orders AS o INNER JOIN customers AS c ON o.customer_id = c.id;',
 20, 3, now()),

-- 27
(gen_random_uuid(),
 'LEFT JOIN', 'LEFT JOIN',
 'Select all employees and their department name (if any), using a LEFT JOIN between "employees" and "departments" on department_id.',
 'Selecciona todos los empleados y su nombre de departamento (si existe), usando un LEFT JOIN entre "employees" y "departments" por department_id.',
 'sql', 2, 'basics',
 'SELECT e.name, d.name FROM employees e ___ departments d ON e.department_id = d.id;',
 'SELECT e.name, d.name FROM employees e LEFT JOIN departments d ON e.department_id = d.id;',
 3,
 'A LEFT JOIN returns all rows from the left table, with NULLs for missing matches.', 'Un LEFT JOIN devuelve todas las filas de la tabla izquierda, con NULLs donde no hay coincidencia.',
 'The left table is the first table listed (before the JOIN keyword).', 'La tabla izquierda es la primera tabla listada (antes de la palabra clave JOIN).',
 'SELECT e.name, d.name FROM employees e LEFT JOIN departments d ON e.department_id = d.id;', 'SELECT e.name, d.name FROM employees e LEFT JOIN departments d ON e.department_id = d.id;',
 20, 3, now()),

-- 28
(gen_random_uuid(),
 'GROUP BY', 'GROUP BY',
 'Count the number of orders per customer_id from the "orders" table.',
 'Cuenta el número de pedidos por customer_id de la tabla "orders".',
 'sql', 2, 'basics',
 'SELECT customer_id, COUNT(*) AS order_count FROM orders ___ customer_id;',
 'SELECT customer_id, COUNT(*) AS order_count FROM orders GROUP BY customer_id;',
 3,
 'Use GROUP BY to aggregate data per unique value of a column.', 'Usa GROUP BY para agregar datos por cada valor único de una columna.',
 'All non-aggregated columns in SELECT must appear in GROUP BY.', 'Todas las columnas no agregadas en SELECT deben aparecer en GROUP BY.',
 'SELECT customer_id, COUNT(*) AS order_count FROM orders GROUP BY customer_id;', 'SELECT customer_id, COUNT(*) AS order_count FROM orders GROUP BY customer_id;',
 20, 3, now()),

-- 29
(gen_random_uuid(),
 'HAVING Clause', 'Cláusula HAVING',
 'Find all customers who have placed more than 5 orders.',
 'Encuentra todos los clientes que han realizado más de 5 pedidos.',
 'sql', 2, 'basics',
 'SELECT customer_id, COUNT(*) AS cnt FROM orders GROUP BY customer_id ___ COUNT(*) > 5;',
 'SELECT customer_id, COUNT(*) AS cnt FROM orders GROUP BY customer_id HAVING COUNT(*) > 5;',
 3,
 'Use HAVING to filter groups after GROUP BY.', 'Usa HAVING para filtrar grupos después de GROUP BY.',
 'WHERE filters rows before grouping; HAVING filters groups after grouping.', 'WHERE filtra filas antes de agrupar; HAVING filtra grupos después de agrupar.',
 'SELECT customer_id, COUNT(*) AS cnt FROM orders GROUP BY customer_id HAVING COUNT(*) > 5;', 'SELECT customer_id, COUNT(*) AS cnt FROM orders GROUP BY customer_id HAVING COUNT(*) > 5;',
 20, 3, now()),

-- 30
(gen_random_uuid(),
 'Subquery in WHERE', 'Subconsulta en WHERE',
 'Select all products whose price is above the average price of all products.',
 'Selecciona todos los productos cuyo precio sea superior al precio promedio de todos los productos.',
 'sql', 2, 'basics',
 'SELECT * FROM products WHERE price > (SELECT ___(price) FROM products);',
 'SELECT * FROM products WHERE price > (SELECT AVG(price) FROM products);',
 3,
 'A subquery is a SELECT inside another query.', 'Una subconsulta es un SELECT dentro de otra consulta.',
 'Place the subquery inside parentheses in the WHERE clause.', 'Coloca la subconsulta entre paréntesis en la cláusula WHERE.',
 'SELECT * FROM products WHERE price > (SELECT AVG(price) FROM products);', 'SELECT * FROM products WHERE price > (SELECT AVG(price) FROM products);',
 20, 3, now()),

-- 31
(gen_random_uuid(),
 'CASE Expression', 'Expresión CASE',
 'Select employee names and a "level" column: ''junior'' if salary < 40000, else ''senior''.',
 'Selecciona nombres de empleados y una columna "level": ''junior'' si salary < 40000, si no ''senior''.',
 'sql', 2, 'basics',
 'SELECT name, CASE WHEN salary < 40000 THEN ___ ELSE ___ END AS level FROM employees;',
 'SELECT name, CASE WHEN salary < 40000 THEN ''junior'' ELSE ''senior'' END AS level FROM employees;',
 3,
 'CASE WHEN acts like an if/else statement inside SELECT.', 'CASE WHEN actúa como una sentencia if/else dentro de SELECT.',
 'Every CASE must end with END.', 'Todo CASE debe terminar con END.',
 'SELECT name, CASE WHEN salary < 40000 THEN ''junior'' ELSE ''senior'' END AS level FROM employees;', 'SELECT name, CASE WHEN salary < 40000 THEN ''junior'' ELSE ''senior'' END AS level FROM employees;',
 20, 3, now()),

-- 32
(gen_random_uuid(),
 'COALESCE', 'COALESCE',
 'Select "name" and "phone", replacing NULL phone values with ''N/A'' from "customers".',
 'Selecciona "name" y "phone", reemplazando los valores NULL de phone con ''N/A'' de "customers".',
 'sql', 2, 'functions',
 'SELECT name, ___(phone, ''N/A'') AS phone FROM customers;',
 'SELECT name, COALESCE(phone, ''N/A'') AS phone FROM customers;',
 3,
 'COALESCE returns the first non-NULL value from its arguments.', 'COALESCE devuelve el primer valor no NULL de sus argumentos.',
 'COALESCE(column, fallback) replaces NULL with fallback.', 'COALESCE(columna, valor_de_reemplazo) reemplaza NULL con el valor de reemplazo.',
 'SELECT name, COALESCE(phone, ''N/A'') AS phone FROM customers;', 'SELECT name, COALESCE(phone, ''N/A'') AS phone FROM customers;',
 20, 3, now()),

-- 33
(gen_random_uuid(),
 'UPPER and LOWER Functions', 'Funciones UPPER y LOWER',
 'Select all employee names converted to uppercase from the "employees" table.',
 'Selecciona todos los nombres de empleados convertidos a mayúsculas de la tabla "employees".',
 'sql', 2, 'strings',
 'SELECT ___(name) AS name_upper FROM employees;',
 'SELECT UPPER(name) AS name_upper FROM employees;',
 3,
 'SQL has built-in string functions for case conversion.', 'SQL tiene funciones de cadena integradas para convertir mayúsculas/minúsculas.',
 'UPPER(string) converts to uppercase; LOWER(string) converts to lowercase.', 'UPPER(cadena) convierte a mayúsculas; LOWER(cadena) convierte a minúsculas.',
 'SELECT UPPER(name) AS name_upper FROM employees;', 'SELECT UPPER(name) AS name_upper FROM employees;',
 20, 3, now()),

-- 34
(gen_random_uuid(),
 'LENGTH Function', 'Función LENGTH',
 'Select the product name and the number of characters in each name from "products".',
 'Selecciona el nombre del producto y el número de caracteres en cada nombre de "products".',
 'sql', 2, 'strings',
 'SELECT name, ___(name) AS name_length FROM products;',
 'SELECT name, LENGTH(name) AS name_length FROM products;',
 3,
 'Use a string function that counts characters.', 'Usa una función de cadena que cuente caracteres.',
 'LENGTH(string) returns the number of characters.', 'LENGTH(cadena) devuelve el número de caracteres.',
 'SELECT name, LENGTH(name) AS name_length FROM products;', 'SELECT name, LENGTH(name) AS name_length FROM products;',
 20, 3, now()),

-- 35
(gen_random_uuid(),
 'TRIM Function', 'Función TRIM',
 'Select all usernames from "users" with leading and trailing spaces removed.',
 'Selecciona todos los nombres de usuario de "users" con los espacios iniciales y finales eliminados.',
 'sql', 2, 'strings',
 'SELECT ___(username) AS username FROM users;',
 'SELECT TRIM(username) AS username FROM users;',
 3,
 'TRIM removes whitespace from both ends of a string.', 'TRIM elimina los espacios en blanco de ambos extremos de una cadena.',
 'TRIM(string) is the standard SQL function for this purpose.', 'TRIM(cadena) es la función SQL estándar para este propósito.',
 'SELECT TRIM(username) AS username FROM users;', 'SELECT TRIM(username) AS username FROM users;',
 20, 3, now()),

-- 36
(gen_random_uuid(),
 'SUBSTRING Function', 'Función SUBSTRING',
 'Extract the first 3 characters of "code" from the "products" table.',
 'Extrae los primeros 3 caracteres de "code" de la tabla "products".',
 'sql', 2, 'strings',
 'SELECT SUBSTRING(code, ___, ___) AS short_code FROM products;',
 'SELECT SUBSTRING(code, 1, 3) AS short_code FROM products;',
 3,
 'SUBSTRING(string, start, length) extracts a portion of a string.', 'SUBSTRING(cadena, inicio, longitud) extrae una porción de una cadena.',
 'SQL string positions start at 1, not 0.', 'Las posiciones de cadena en SQL comienzan en 1, no en 0.',
 'SELECT SUBSTRING(code, 1, 3) AS short_code FROM products;', 'SELECT SUBSTRING(code, 1, 3) AS short_code FROM products;',
 20, 3, now()),

-- 37
(gen_random_uuid(),
 'UNION Two Queries', 'UNION de Dos Consultas',
 'Combine the "name" column from "customers" and "suppliers" into one result set using UNION.',
 'Combina la columna "name" de "customers" y "suppliers" en un único resultado usando UNION.',
 'sql', 2, 'basics',
 'SELECT name FROM customers ___ SELECT name FROM suppliers;',
 'SELECT name FROM customers UNION SELECT name FROM suppliers;',
 3,
 'UNION combines results from two SELECT queries.', 'UNION combina resultados de dos consultas SELECT.',
 'UNION automatically removes duplicate rows; use UNION ALL to keep them.', 'UNION elimina automáticamente filas duplicadas; usa UNION ALL para conservarlas.',
 'SELECT name FROM customers UNION SELECT name FROM suppliers;', 'SELECT name FROM customers UNION SELECT name FROM suppliers;',
 20, 3, now()),

-- 38
(gen_random_uuid(),
 'CREATE TABLE', 'CREATE TABLE',
 'Create a table "tags" with columns: id (integer, primary key) and name (varchar 50, not null).',
 'Crea una tabla "tags" con columnas: id (entero, clave primaria) y name (varchar 50, no nulo).',
 'sql', 2, 'basics',
 'CREATE TABLE tags (id INTEGER ___, name VARCHAR(50) ___);',
 'CREATE TABLE tags (id INTEGER PRIMARY KEY, name VARCHAR(50) NOT NULL);',
 3,
 'Use CREATE TABLE to define a new table structure.', 'Usa CREATE TABLE para definir una nueva estructura de tabla.',
 'Column constraints like PRIMARY KEY and NOT NULL follow the data type.', 'Las restricciones de columna como PRIMARY KEY y NOT NULL siguen al tipo de dato.',
 'CREATE TABLE tags (id INTEGER PRIMARY KEY, name VARCHAR(50) NOT NULL);', 'CREATE TABLE tags (id INTEGER PRIMARY KEY, name VARCHAR(50) NOT NULL);',
 20, 3, now()),

-- 39
(gen_random_uuid(),
 'ALTER TABLE Add Column', 'ALTER TABLE Agregar Columna',
 'Add a "bio" column of type TEXT to the existing "users" table.',
 'Agrega una columna "bio" de tipo TEXT a la tabla "users" existente.',
 'sql', 2, 'basics',
 'ALTER TABLE users ___ COLUMN bio TEXT;',
 'ALTER TABLE users ADD COLUMN bio TEXT;',
 3,
 'Use ALTER TABLE to modify an existing table structure.', 'Usa ALTER TABLE para modificar una estructura de tabla existente.',
 'ADD COLUMN inserts a new column definition.', 'ADD COLUMN inserta una nueva definición de columna.',
 'ALTER TABLE users ADD COLUMN bio TEXT;', 'ALTER TABLE users ADD COLUMN bio TEXT;',
 20, 3, now()),

-- 40
(gen_random_uuid(),
 'CREATE INDEX', 'CREATE INDEX',
 'Create an index named "idx_orders_customer" on the "customer_id" column of the "orders" table.',
 'Crea un índice llamado "idx_orders_customer" en la columna "customer_id" de la tabla "orders".',
 'sql', 2, 'basics',
 'CREATE INDEX idx_orders_customer ON ___(___);',
 'CREATE INDEX idx_orders_customer ON orders(customer_id);',
 3,
 'Use CREATE INDEX to speed up queries on a specific column.', 'Usa CREATE INDEX para acelerar las consultas en una columna específica.',
 'Syntax: CREATE INDEX name ON table(column).', 'Sintaxis: CREATE INDEX nombre ON tabla(columna).',
 'CREATE INDEX idx_orders_customer ON orders(customer_id);', 'CREATE INDEX idx_orders_customer ON orders(customer_id);',
 20, 3, now()),

-- 41
(gen_random_uuid(),
 'RIGHT JOIN', 'RIGHT JOIN',
 'Select all departments and their employees (if any) using a RIGHT JOIN between "employees" and "departments" on department_id.',
 'Selecciona todos los departamentos y sus empleados (si los hay) usando un RIGHT JOIN entre "employees" y "departments" por department_id.',
 'sql', 2, 'basics',
 'SELECT e.name, d.name FROM employees e ___ departments d ON e.department_id = d.id;',
 'SELECT e.name, d.name FROM employees e RIGHT JOIN departments d ON e.department_id = d.id;',
 3,
 'RIGHT JOIN keeps all rows from the right table.', 'RIGHT JOIN conserva todas las filas de la tabla derecha.',
 'The right table is the second table listed (after the JOIN keyword).', 'La tabla derecha es la segunda tabla listada (después de la palabra clave JOIN).',
 'SELECT e.name, d.name FROM employees e RIGHT JOIN departments d ON e.department_id = d.id;', 'SELECT e.name, d.name FROM employees e RIGHT JOIN departments d ON e.department_id = d.id;',
 20, 3, now()),

-- 42
(gen_random_uuid(),
 'Date Function CURRENT_DATE', 'Función de Fecha CURRENT_DATE',
 'Select all orders placed today by filtering "created_at" equal to the current date.',
 'Selecciona todos los pedidos realizados hoy filtrando "created_at" igual a la fecha actual.',
 'sql', 2, 'functions',
 'SELECT * FROM orders WHERE created_at::date = ___;',
 'SELECT * FROM orders WHERE created_at::date = CURRENT_DATE;',
 3,
 'SQL provides a built-in function to get today''s date.', 'SQL proporciona una función integrada para obtener la fecha de hoy.',
 'CURRENT_DATE returns the current date without a time component.', 'CURRENT_DATE devuelve la fecha actual sin componente de hora.',
 'SELECT * FROM orders WHERE created_at::date = CURRENT_DATE;', 'SELECT * FROM orders WHERE created_at::date = CURRENT_DATE;',
 20, 3, now()),

-- 43
(gen_random_uuid(),
 'ROUND Function', 'Función ROUND',
 'Select product names and prices rounded to 2 decimal places from "products".',
 'Selecciona nombres de productos y precios redondeados a 2 decimales de "products".',
 'sql', 2, 'math',
 'SELECT name, ___(price, 2) AS rounded_price FROM products;',
 'SELECT name, ROUND(price, 2) AS rounded_price FROM products;',
 3,
 'Use a numeric function to control decimal precision.', 'Usa una función numérica para controlar la precisión decimal.',
 'ROUND(number, decimal_places) rounds to the specified number of decimals.', 'ROUND(número, decimales) redondea al número de decimales especificado.',
 'SELECT name, ROUND(price, 2) AS rounded_price FROM products;', 'SELECT name, ROUND(price, 2) AS rounded_price FROM products;',
 20, 3, now()),

-- 44
(gen_random_uuid(),
 'Multiple Column GROUP BY', 'GROUP BY con Múltiples Columnas',
 'Count orders grouped by both "status" and "customer_id" from the "orders" table.',
 'Cuenta los pedidos agrupados por "status" y "customer_id" de la tabla "orders".',
 'sql', 2, 'basics',
 'SELECT status, customer_id, COUNT(*) FROM orders GROUP BY ___, ___;',
 'SELECT status, customer_id, COUNT(*) FROM orders GROUP BY status, customer_id;',
 3,
 'GROUP BY can take multiple columns separated by commas.', 'GROUP BY puede tomar múltiples columnas separadas por comas.',
 'Each unique combination of the grouped columns forms one group.', 'Cada combinación única de las columnas agrupadas forma un grupo.',
 'SELECT status, customer_id, COUNT(*) FROM orders GROUP BY status, customer_id;', 'SELECT status, customer_id, COUNT(*) FROM orders GROUP BY status, customer_id;',
 20, 3, now()),

-- 45
(gen_random_uuid(),
 'OFFSET Pagination', 'Paginación con OFFSET',
 'Select rows 11 through 20 from the "products" table ordered by id.',
 'Selecciona las filas 11 a 20 de la tabla "products" ordenadas por id.',
 'sql', 2, 'basics',
 'SELECT * FROM products ORDER BY id LIMIT 10 ___ 10;',
 'SELECT * FROM products ORDER BY id LIMIT 10 OFFSET 10;',
 3,
 'OFFSET skips a number of rows before starting to return results.', 'OFFSET omite un número de filas antes de comenzar a devolver resultados.',
 'LIMIT 10 OFFSET 10 skips the first 10 rows and returns the next 10.', 'LIMIT 10 OFFSET 10 omite las primeras 10 filas y devuelve las siguientes 10.',
 'SELECT * FROM products ORDER BY id LIMIT 10 OFFSET 10;', 'SELECT * FROM products ORDER BY id LIMIT 10 OFFSET 10;',
 20, 3, now()),

-- 46
(gen_random_uuid(),
 'EXISTS Subquery', 'Subconsulta EXISTS',
 'Select all customers who have at least one order using EXISTS.',
 'Selecciona todos los clientes que tengan al menos un pedido usando EXISTS.',
 'sql', 2, 'basics',
 'SELECT * FROM customers c WHERE ___ (SELECT 1 FROM orders o WHERE o.customer_id = c.id);',
 'SELECT * FROM customers c WHERE EXISTS (SELECT 1 FROM orders o WHERE o.customer_id = c.id);',
 3,
 'EXISTS returns true if the subquery returns at least one row.', 'EXISTS devuelve verdadero si la subconsulta devuelve al menos una fila.',
 'The subquery uses a correlated reference to the outer query.', 'La subconsulta usa una referencia correlacionada a la consulta externa.',
 'SELECT * FROM customers c WHERE EXISTS (SELECT 1 FROM orders o WHERE o.customer_id = c.id);', 'SELECT * FROM customers c WHERE EXISTS (SELECT 1 FROM orders o WHERE o.customer_id = c.id);',
 20, 3, now()),

-- 47
(gen_random_uuid(),
 'NOT EXISTS Subquery', 'Subconsulta NOT EXISTS',
 'Select all customers who have never placed an order.',
 'Selecciona todos los clientes que nunca hayan realizado un pedido.',
 'sql', 2, 'basics',
 'SELECT * FROM customers c WHERE ___ (SELECT 1 FROM orders o WHERE o.customer_id = c.id);',
 'SELECT * FROM customers c WHERE NOT EXISTS (SELECT 1 FROM orders o WHERE o.customer_id = c.id);',
 3,
 'NOT EXISTS is the opposite of EXISTS — it finds rows with no match.', 'NOT EXISTS es lo opuesto de EXISTS: encuentra filas sin coincidencia.',
 'This is a common pattern for finding orphaned records.', 'Este es un patrón común para encontrar registros huérfanos.',
 'SELECT * FROM customers c WHERE NOT EXISTS (SELECT 1 FROM orders o WHERE o.customer_id = c.id);', 'SELECT * FROM customers c WHERE NOT EXISTS (SELECT 1 FROM orders o WHERE o.customer_id = c.id);',
 20, 3, now()),

-- 48
(gen_random_uuid(),
 'CAST Data Type', 'Conversión de Tipo con CAST',
 'Select "price" from "products", casting it to INTEGER.',
 'Selecciona "price" de "products", convirtiéndolo a INTEGER.',
 'sql', 2, 'functions',
 'SELECT ___(price AS INTEGER) FROM products;',
 'SELECT CAST(price AS INTEGER) FROM products;',
 3,
 'CAST converts a value from one data type to another.', 'CAST convierte un valor de un tipo de dato a otro.',
 'Syntax: CAST(value AS new_type).', 'Sintaxis: CAST(valor AS nuevo_tipo).',
 'SELECT CAST(price AS INTEGER) FROM products;', 'SELECT CAST(price AS INTEGER) FROM products;',
 20, 3, now()),

-- 49
(gen_random_uuid(),
 'ILIKE Case-Insensitive Search', 'Búsqueda sin Distinción de Mayúsculas con ILIKE',
 'Select all products whose name contains ''phone'' regardless of case.',
 'Selecciona todos los productos cuyo nombre contenga ''phone'' sin importar mayúsculas.',
 'sql', 2, 'strings',
 'SELECT * FROM products WHERE name ___ ''%phone%'';',
 'SELECT * FROM products WHERE name ILIKE ''%phone%'';',
 3,
 'ILIKE is like LIKE but case-insensitive (PostgreSQL).', 'ILIKE es como LIKE pero sin distinción de mayúsculas (PostgreSQL).',
 'Wrap the search term with % wildcards on both sides to search anywhere in the string.', 'Rodea el término de búsqueda con comodines % en ambos lados para buscar en cualquier parte de la cadena.',
 'SELECT * FROM products WHERE name ILIKE ''%phone%'';', 'SELECT * FROM products WHERE name ILIKE ''%phone%'';',
 20, 3, now()),

-- 50
(gen_random_uuid(),
 'INSERT Multiple Rows', 'INSERT de Múltiples Filas',
 'Insert two rows into "tags": (1, ''sql'') and (2, ''database'') in a single statement.',
 'Inserta dos filas en "tags": (1, ''sql'') y (2, ''database'') en una sola sentencia.',
 'sql', 2, 'basics',
 'INSERT INTO tags (id, name) VALUES ___, ___;',
 'INSERT INTO tags (id, name) VALUES (1, ''sql''), (2, ''database'');',
 3,
 'A single INSERT can add multiple rows by separating value groups with commas.', 'Un solo INSERT puede agregar múltiples filas separando los grupos de valores con comas.',
 'Each row is a separate parenthesized group of values.', 'Cada fila es un grupo de valores entre paréntesis separado.',
 'INSERT INTO tags (id, name) VALUES (1, ''sql''), (2, ''database'');', 'INSERT INTO tags (id, name) VALUES (1, ''sql''), (2, ''database'');',
 20, 3, now()),

-- ============================================================
-- DIFFICULTY 3 — 25 exercises (points: 30, penalty: 5)
-- ============================================================

-- 51
(gen_random_uuid(),
 'Common Table Expression (CTE)', 'Expresión de Tabla Común (CTE)',
 'Use a CTE named "high_earners" to select employees with salary > 80000, then select all from it.',
 'Usa un CTE llamado "high_earners" para seleccionar empleados con salary > 80000, luego selecciona todo de él.',
 'sql', 3, 'patterns',
 'WITH high_earners AS (SELECT * FROM employees WHERE salary > 80000) SELECT ___ FROM ___;',
 'WITH high_earners AS (SELECT * FROM employees WHERE salary > 80000) SELECT * FROM high_earners;',
 3,
 'A CTE uses the WITH keyword to define a named temporary result set.', 'Un CTE usa la palabra clave WITH para definir un conjunto de resultados temporal con nombre.',
 'After the CTE definition, reference it like a regular table.', 'Después de la definición del CTE, refiérelo como una tabla normal.',
 'WITH high_earners AS (SELECT * FROM employees WHERE salary > 80000) SELECT * FROM high_earners;', 'WITH high_earners AS (SELECT * FROM employees WHERE salary > 80000) SELECT * FROM high_earners;',
 30, 5, now()),

-- 52
(gen_random_uuid(),
 'Window Function ROW_NUMBER', 'Función de Ventana ROW_NUMBER',
 'Number each employee row within their department ordered by salary descending.',
 'Numera cada fila de empleado dentro de su departamento ordenada por salary descendente.',
 'sql', 3, 'functions',
 'SELECT name, department_id, ROW_NUMBER() OVER (___ department_id ORDER BY salary DESC) AS rn FROM employees;',
 'SELECT name, department_id, ROW_NUMBER() OVER (PARTITION BY department_id ORDER BY salary DESC) AS rn FROM employees;',
 3,
 'ROW_NUMBER() is a window function that assigns a sequential number to each row.', 'ROW_NUMBER() es una función de ventana que asigna un número secuencial a cada fila.',
 'PARTITION BY divides the result into groups; ORDER BY sets the ranking order within each partition.', 'PARTITION BY divide el resultado en grupos; ORDER BY establece el orden de clasificación dentro de cada partición.',
 'SELECT name, department_id, ROW_NUMBER() OVER (PARTITION BY department_id ORDER BY salary DESC) AS rn FROM employees;', 'SELECT name, department_id, ROW_NUMBER() OVER (PARTITION BY department_id ORDER BY salary DESC) AS rn FROM employees;',
 30, 5, now()),

-- 53
(gen_random_uuid(),
 'Window Function RANK', 'Función de Ventana RANK',
 'Rank all products by price descending, assigning the same rank to ties.',
 'Clasifica todos los productos por precio descendente, asignando el mismo rango a los empates.',
 'sql', 3, 'functions',
 'SELECT name, price, ___ OVER (ORDER BY price DESC) AS price_rank FROM products;',
 'SELECT name, price, RANK() OVER (ORDER BY price DESC) AS price_rank FROM products;',
 3,
 'RANK() is similar to ROW_NUMBER() but handles ties by giving them the same rank.', 'RANK() es similar a ROW_NUMBER() pero maneja los empates dándoles el mismo rango.',
 'After a tie, RANK() skips numbers (e.g., 1, 2, 2, 4).', 'Después de un empate, RANK() salta números (por ejemplo, 1, 2, 2, 4).',
 'SELECT name, price, RANK() OVER (ORDER BY price DESC) AS price_rank FROM products;', 'SELECT name, price, RANK() OVER (ORDER BY price DESC) AS price_rank FROM products;',
 30, 5, now()),

-- 54
(gen_random_uuid(),
 'Window Function SUM OVER', 'Función de Ventana SUM OVER',
 'Calculate a running total of "amount" from "payments" ordered by payment date.',
 'Calcula un total acumulado de "amount" de "payments" ordenado por fecha de pago.',
 'sql', 3, 'functions',
 'SELECT id, amount, SUM(amount) OVER (ORDER BY ___) AS running_total FROM payments;',
 'SELECT id, amount, SUM(amount) OVER (ORDER BY payment_date) AS running_total FROM payments;',
 3,
 'SUM() used as a window function computes a cumulative total.', 'SUM() usado como función de ventana calcula un total acumulado.',
 'Add ORDER BY inside OVER() to make it a running (cumulative) sum.', 'Agrega ORDER BY dentro de OVER() para hacerlo una suma acumulada.',
 'SELECT id, amount, SUM(amount) OVER (ORDER BY payment_date) AS running_total FROM payments;', 'SELECT id, amount, SUM(amount) OVER (ORDER BY payment_date) AS running_total FROM payments;',
 30, 5, now()),

-- 55
(gen_random_uuid(),
 'SELF JOIN', 'SELF JOIN',
 'Select each employee''s name and their manager''s name by joining the "employees" table to itself.',
 'Selecciona el nombre de cada empleado y el nombre de su gerente uniendo la tabla "employees" consigo misma.',
 'sql', 3, 'basics',
 'SELECT e.name AS employee, m.name AS manager FROM employees e ___ employees m ON e.manager_id = m.id;',
 'SELECT e.name AS employee, m.name AS manager FROM employees e LEFT JOIN employees m ON e.manager_id = m.id;',
 3,
 'A self join joins a table to itself using two different aliases.', 'Un self join une una tabla consigo misma usando dos alias diferentes.',
 'Use LEFT JOIN to include employees without a manager.', 'Usa LEFT JOIN para incluir empleados sin gerente.',
 'SELECT e.name AS employee, m.name AS manager FROM employees e LEFT JOIN employees m ON e.manager_id = m.id;', 'SELECT e.name AS employee, m.name AS manager FROM employees e LEFT JOIN employees m ON e.manager_id = m.id;',
 30, 5, now()),

-- 56
(gen_random_uuid(),
 'Subquery in FROM', 'Subconsulta en FROM',
 'Find the average of department-level average salaries using a subquery in FROM.',
 'Encuentra el promedio de los salarios promedio por departamento usando una subconsulta en FROM.',
 'sql', 3, 'basics',
 'SELECT AVG(dept_avg) FROM (SELECT AVG(salary) AS dept_avg FROM employees GROUP BY ___) AS sub;',
 'SELECT AVG(dept_avg) FROM (SELECT AVG(salary) AS dept_avg FROM employees GROUP BY department_id) AS sub;',
 3,
 'A subquery in FROM is called a derived table.', 'Una subconsulta en FROM se llama tabla derivada.',
 'The derived table must be given an alias.', 'La tabla derivada debe tener un alias.',
 'SELECT AVG(dept_avg) FROM (SELECT AVG(salary) AS dept_avg FROM employees GROUP BY department_id) AS sub;', 'SELECT AVG(dept_avg) FROM (SELECT AVG(salary) AS dept_avg FROM employees GROUP BY department_id) AS sub;',
 30, 5, now()),

-- 57
(gen_random_uuid(),
 'Multiple CTEs', 'Múltiples CTEs',
 'Write two CTEs: "cheap" (products price < 20) and "expensive" (products price >= 100), then UNION them.',
 'Escribe dos CTEs: "cheap" (productos precio < 20) y "expensive" (productos precio >= 100), luego únelos con UNION.',
 'sql', 3, 'patterns',
 'WITH cheap AS (SELECT * FROM products WHERE price < 20), expensive AS (___) SELECT * FROM cheap UNION SELECT * FROM expensive;',
 'WITH cheap AS (SELECT * FROM products WHERE price < 20), expensive AS (SELECT * FROM products WHERE price >= 100) SELECT * FROM cheap UNION SELECT * FROM expensive;',
 3,
 'Multiple CTEs are separated by commas after the WITH keyword.', 'Los CTEs múltiples se separan con comas después de la palabra clave WITH.',
 'Only the first CTE uses the WITH keyword; subsequent ones are separated by commas.', 'Solo el primer CTE usa la palabra clave WITH; los siguientes se separan con comas.',
 'WITH cheap AS (SELECT * FROM products WHERE price < 20), expensive AS (SELECT * FROM products WHERE price >= 100) SELECT * FROM cheap UNION SELECT * FROM expensive;', 'WITH cheap AS (SELECT * FROM products WHERE price < 20), expensive AS (SELECT * FROM products WHERE price >= 100) SELECT * FROM cheap UNION SELECT * FROM expensive;',
 30, 5, now()),

-- 58
(gen_random_uuid(),
 'Create View', 'Crear Vista',
 'Create a view named "active_users" that selects all users where "is_active" is true.',
 'Crea una vista llamada "active_users" que seleccione todos los usuarios donde "is_active" sea verdadero.',
 'sql', 3, 'basics',
 'CREATE VIEW active_users AS SELECT * FROM users WHERE ___ = ___;',
 'CREATE VIEW active_users AS SELECT * FROM users WHERE is_active = true;',
 3,
 'A VIEW is a stored query that behaves like a virtual table.', 'Una VISTA es una consulta almacenada que se comporta como una tabla virtual.',
 'CREATE VIEW name AS SELECT ... defines the view.', 'CREATE VIEW nombre AS SELECT ... define la vista.',
 'CREATE VIEW active_users AS SELECT * FROM users WHERE is_active = true;', 'CREATE VIEW active_users AS SELECT * FROM users WHERE is_active = true;',
 30, 5, now()),

-- 59
(gen_random_uuid(),
 'DENSE_RANK Window Function', 'Función de Ventana DENSE_RANK',
 'Rank products by price descending without gaps in ranking after ties.',
 'Clasifica los productos por precio descendente sin brechas en el ranking después de empates.',
 'sql', 3, 'functions',
 'SELECT name, price, ___ OVER (ORDER BY price DESC) AS rnk FROM products;',
 'SELECT name, price, DENSE_RANK() OVER (ORDER BY price DESC) AS rnk FROM products;',
 3,
 'DENSE_RANK() handles ties without skipping subsequent rank numbers.', 'DENSE_RANK() maneja empates sin omitir los números de rango siguientes.',
 'Unlike RANK(), DENSE_RANK() gives 1, 2, 2, 3 instead of 1, 2, 2, 4.', 'A diferencia de RANK(), DENSE_RANK() da 1, 2, 2, 3 en lugar de 1, 2, 2, 4.',
 'SELECT name, price, DENSE_RANK() OVER (ORDER BY price DESC) AS rnk FROM products;', 'SELECT name, price, DENSE_RANK() OVER (ORDER BY price DESC) AS rnk FROM products;',
 30, 5, now()),

-- 60
(gen_random_uuid(),
 'LAG Window Function', 'Función de Ventana LAG',
 'For each payment, show the previous payment amount using a window function.',
 'Para cada pago, muestra el monto del pago anterior usando una función de ventana.',
 'sql', 3, 'functions',
 'SELECT id, amount, ___(amount, 1) OVER (ORDER BY payment_date) AS prev_amount FROM payments;',
 'SELECT id, amount, LAG(amount, 1) OVER (ORDER BY payment_date) AS prev_amount FROM payments;',
 3,
 'LAG() accesses data from a previous row in the result set.', 'LAG() accede a datos de una fila anterior en el conjunto de resultados.',
 'LAG(column, offset) returns the value offset rows back.', 'LAG(columna, desplazamiento) devuelve el valor de las filas anteriores según el desplazamiento.',
 'SELECT id, amount, LAG(amount, 1) OVER (ORDER BY payment_date) AS prev_amount FROM payments;', 'SELECT id, amount, LAG(amount, 1) OVER (ORDER BY payment_date) AS prev_amount FROM payments;',
 30, 5, now()),

-- 61
(gen_random_uuid(),
 'LEAD Window Function', 'Función de Ventana LEAD',
 'For each payment, show the next payment amount using a window function.',
 'Para cada pago, muestra el monto del siguiente pago usando una función de ventana.',
 'sql', 3, 'functions',
 'SELECT id, amount, ___(amount, 1) OVER (ORDER BY payment_date) AS next_amount FROM payments;',
 'SELECT id, amount, LEAD(amount, 1) OVER (ORDER BY payment_date) AS next_amount FROM payments;',
 3,
 'LEAD() accesses data from a following row in the result set.', 'LEAD() accede a datos de una fila siguiente en el conjunto de resultados.',
 'LEAD(column, offset) returns the value offset rows ahead.', 'LEAD(columna, desplazamiento) devuelve el valor de las filas siguientes según el desplazamiento.',
 'SELECT id, amount, LEAD(amount, 1) OVER (ORDER BY payment_date) AS next_amount FROM payments;', 'SELECT id, amount, LEAD(amount, 1) OVER (ORDER BY payment_date) AS next_amount FROM payments;',
 30, 5, now()),

-- 62
(gen_random_uuid(),
 'CASE With Multiple WHEN', 'CASE con Múltiples WHEN',
 'Label each product: ''cheap'' if price < 20, ''mid'' if price < 100, else ''premium''.',
 'Etiqueta cada producto: ''cheap'' si price < 20, ''mid'' si price < 100, si no ''premium''.',
 'sql', 3, 'patterns',
 'SELECT name, CASE WHEN price < 20 THEN ''cheap'' WHEN ___ THEN ''mid'' ELSE ''premium'' END AS tier FROM products;',
 'SELECT name, CASE WHEN price < 20 THEN ''cheap'' WHEN price < 100 THEN ''mid'' ELSE ''premium'' END AS tier FROM products;',
 3,
 'CASE can have multiple WHEN clauses evaluated in order.', 'CASE puede tener múltiples cláusulas WHEN evaluadas en orden.',
 'The first matching WHEN condition is used; subsequent ones are skipped.', 'Se usa la primera condición WHEN que coincida; las siguientes se omiten.',
 'SELECT name, CASE WHEN price < 20 THEN ''cheap'' WHEN price < 100 THEN ''mid'' ELSE ''premium'' END AS tier FROM products;', 'SELECT name, CASE WHEN price < 20 THEN ''cheap'' WHEN price < 100 THEN ''mid'' ELSE ''premium'' END AS tier FROM products;',
 30, 5, now()),

-- 63
(gen_random_uuid(),
 'UPDATE With Subquery', 'UPDATE con Subconsulta',
 'Set all employees'' "bonus" to 500 where their salary is below the company average.',
 'Establece el "bonus" de todos los empleados en 500 donde su salario esté por debajo del promedio de la empresa.',
 'sql', 3, 'basics',
 'UPDATE employees SET bonus = 500 WHERE salary < (SELECT ___(salary) FROM employees);',
 'UPDATE employees SET bonus = 500 WHERE salary < (SELECT AVG(salary) FROM employees);',
 3,
 'A subquery can be used in the WHERE clause of an UPDATE.', 'Una subconsulta puede usarse en la cláusula WHERE de un UPDATE.',
 'The subquery computes the average salary of all employees.', 'La subconsulta calcula el salario promedio de todos los empleados.',
 'UPDATE employees SET bonus = 500 WHERE salary < (SELECT AVG(salary) FROM employees);', 'UPDATE employees SET bonus = 500 WHERE salary < (SELECT AVG(salary) FROM employees);',
 30, 5, now()),

-- 64
(gen_random_uuid(),
 'UNIQUE Constraint', 'Restricción UNIQUE',
 'Create a "users" table with an "email" column that must be unique and not null.',
 'Crea una tabla "users" con una columna "email" que debe ser única y no nula.',
 'sql', 3, 'basics',
 'CREATE TABLE users (id SERIAL PRIMARY KEY, email VARCHAR(255) ___ ___);',
 'CREATE TABLE users (id SERIAL PRIMARY KEY, email VARCHAR(255) UNIQUE NOT NULL);',
 3,
 'UNIQUE ensures no two rows have the same value in that column.', 'UNIQUE garantiza que ninguna de las dos filas tenga el mismo valor en esa columna.',
 'Constraints can be chained: UNIQUE NOT NULL.', 'Las restricciones se pueden encadenar: UNIQUE NOT NULL.',
 'CREATE TABLE users (id SERIAL PRIMARY KEY, email VARCHAR(255) UNIQUE NOT NULL);', 'CREATE TABLE users (id SERIAL PRIMARY KEY, email VARCHAR(255) UNIQUE NOT NULL);',
 30, 5, now()),

-- 65
(gen_random_uuid(),
 'FOREIGN KEY Constraint', 'Restricción FOREIGN KEY',
 'Create an "orders" table with a "user_id" column that references the "id" of the "users" table.',
 'Crea una tabla "orders" con una columna "user_id" que referencia el "id" de la tabla "users".',
 'sql', 3, 'basics',
 'CREATE TABLE orders (id SERIAL PRIMARY KEY, user_id INTEGER ___ (users(id)));',
 'CREATE TABLE orders (id SERIAL PRIMARY KEY, user_id INTEGER REFERENCES users(id));',
 3,
 'A FOREIGN KEY links a column to a primary key in another table.', 'Una FOREIGN KEY vincula una columna a una clave primaria en otra tabla.',
 'Use REFERENCES table(column) after the column definition.', 'Usa REFERENCES tabla(columna) después de la definición de columna.',
 'CREATE TABLE orders (id SERIAL PRIMARY KEY, user_id INTEGER REFERENCES users(id));', 'CREATE TABLE orders (id SERIAL PRIMARY KEY, user_id INTEGER REFERENCES users(id));',
 30, 5, now()),

-- 66
(gen_random_uuid(),
 'NTILE Window Function', 'Función de Ventana NTILE',
 'Divide products into 4 quartiles by price ascending.',
 'Divide los productos en 4 cuartiles por precio ascendente.',
 'sql', 3, 'functions',
 'SELECT name, price, NTILE(___) OVER (ORDER BY price) AS quartile FROM products;',
 'SELECT name, price, NTILE(4) OVER (ORDER BY price) AS quartile FROM products;',
 3,
 'NTILE(n) divides the result set into n roughly equal buckets.', 'NTILE(n) divide el conjunto de resultados en n grupos aproximadamente iguales.',
 'Each row is assigned a bucket number from 1 to n.', 'A cada fila se le asigna un número de cubo del 1 al n.',
 'SELECT name, price, NTILE(4) OVER (ORDER BY price) AS quartile FROM products;', 'SELECT name, price, NTILE(4) OVER (ORDER BY price) AS quartile FROM products;',
 30, 5, now()),

-- 67
(gen_random_uuid(),
 'EXTRACT Date Part', 'EXTRACT de Parte de Fecha',
 'Select the year from the "created_at" column for all orders.',
 'Selecciona el año de la columna "created_at" para todos los pedidos.',
 'sql', 3, 'functions',
 'SELECT id, ___(YEAR FROM created_at) AS order_year FROM orders;',
 'SELECT id, EXTRACT(YEAR FROM created_at) AS order_year FROM orders;',
 3,
 'EXTRACT pulls a specific part of a date/timestamp.', 'EXTRACT extrae una parte específica de una fecha/marca de tiempo.',
 'Syntax: EXTRACT(part FROM column) — common parts: YEAR, MONTH, DAY.', 'Sintaxis: EXTRACT(parte FROM columna) — partes comunes: YEAR, MONTH, DAY.',
 'SELECT id, EXTRACT(YEAR FROM created_at) AS order_year FROM orders;', 'SELECT id, EXTRACT(YEAR FROM created_at) AS order_year FROM orders;',
 30, 5, now()),

-- 68
(gen_random_uuid(),
 'String REPLACE Function', 'Función REPLACE de Cadenas',
 'Replace all occurrences of ''.com'' with ''.net'' in the "website" column of "companies".',
 'Reemplaza todas las ocurrencias de ''.com'' con ''.net'' en la columna "website" de "companies".',
 'sql', 3, 'strings',
 'SELECT REPLACE(website, ___, ___) AS new_site FROM companies;',
 'SELECT REPLACE(website, ''.com'', ''.net'') AS new_site FROM companies;',
 3,
 'REPLACE(string, from, to) substitutes all occurrences of a substring.', 'REPLACE(cadena, de, a) sustituye todas las ocurrencias de una subcadena.',
 'REPLACE is case-sensitive in most SQL databases.', 'REPLACE distingue entre mayúsculas y minúsculas en la mayoría de las bases de datos SQL.',
 'SELECT REPLACE(website, ''.com'', ''.net'') AS new_site FROM companies;', 'SELECT REPLACE(website, ''.com'', ''.net'') AS new_site FROM companies;',
 30, 5, now()),

-- 69
(gen_random_uuid(),
 'UNION ALL Preserve Duplicates', 'UNION ALL Conservar Duplicados',
 'Combine all "name" values from "customers" and "suppliers" keeping duplicates.',
 'Combina todos los valores "name" de "customers" y "suppliers" conservando los duplicados.',
 'sql', 3, 'basics',
 'SELECT name FROM customers ___ SELECT name FROM suppliers;',
 'SELECT name FROM customers UNION ALL SELECT name FROM suppliers;',
 3,
 'UNION ALL does not remove duplicate rows unlike UNION.', 'UNION ALL no elimina filas duplicadas, a diferencia de UNION.',
 'Use UNION ALL when you want all rows from both queries including duplicates.', 'Usa UNION ALL cuando quieras todas las filas de ambas consultas incluyendo duplicados.',
 'SELECT name FROM customers UNION ALL SELECT name FROM suppliers;', 'SELECT name FROM customers UNION ALL SELECT name FROM suppliers;',
 30, 5, now()),

-- 70
(gen_random_uuid(),
 'DELETE With Subquery', 'DELETE con Subconsulta',
 'Delete all orders belonging to customers in the ''inactive'' segment.',
 'Elimina todos los pedidos pertenecientes a clientes en el segmento ''inactive''.',
 'sql', 3, 'basics',
 'DELETE FROM orders WHERE customer_id IN (SELECT id FROM customers WHERE ___ = ''inactive'');',
 'DELETE FROM orders WHERE customer_id IN (SELECT id FROM customers WHERE segment = ''inactive'');',
 3,
 'You can use a subquery with IN to determine which rows to delete.', 'Puedes usar una subconsulta con IN para determinar qué filas eliminar.',
 'The subquery returns a list of customer IDs to target.', 'La subconsulta devuelve una lista de IDs de clientes a quienes apuntar.',
 'DELETE FROM orders WHERE customer_id IN (SELECT id FROM customers WHERE segment = ''inactive'');', 'DELETE FROM orders WHERE customer_id IN (SELECT id FROM customers WHERE segment = ''inactive'');',
 30, 5, now()),

-- 71
(gen_random_uuid(),
 'CHECK Constraint', 'Restricción CHECK',
 'Create a "ratings" table where "score" must be between 1 and 5.',
 'Crea una tabla "ratings" donde "score" deba estar entre 1 y 5.',
 'sql', 3, 'basics',
 'CREATE TABLE ratings (id SERIAL PRIMARY KEY, score INTEGER ___(score BETWEEN 1 AND 5));',
 'CREATE TABLE ratings (id SERIAL PRIMARY KEY, score INTEGER CHECK(score BETWEEN 1 AND 5));',
 3,
 'A CHECK constraint validates column values against a condition.', 'Una restricción CHECK valida los valores de columna contra una condición.',
 'Syntax: column_name datatype CHECK(condition).', 'Sintaxis: nombre_columna tipo_dato CHECK(condición).',
 'CREATE TABLE ratings (id SERIAL PRIMARY KEY, score INTEGER CHECK(score BETWEEN 1 AND 5));', 'CREATE TABLE ratings (id SERIAL PRIMARY KEY, score INTEGER CHECK(score BETWEEN 1 AND 5));',
 30, 5, now()),

-- 72
(gen_random_uuid(),
 'DEFAULT Constraint', 'Restricción DEFAULT',
 'Create a "posts" table where "status" defaults to ''draft'' if not provided.',
 'Crea una tabla "posts" donde "status" tenga como valor predeterminado ''draft'' si no se proporciona.',
 'sql', 3, 'basics',
 'CREATE TABLE posts (id SERIAL PRIMARY KEY, status VARCHAR(20) ___ ''draft'');',
 'CREATE TABLE posts (id SERIAL PRIMARY KEY, status VARCHAR(20) DEFAULT ''draft'');',
 3,
 'A DEFAULT constraint sets a fallback value when no value is inserted.', 'Una restricción DEFAULT establece un valor de reserva cuando no se inserta ningún valor.',
 'Syntax: column_name datatype DEFAULT value.', 'Sintaxis: nombre_columna tipo_dato DEFAULT valor.',
 'CREATE TABLE posts (id SERIAL PRIMARY KEY, status VARCHAR(20) DEFAULT ''draft'');', 'CREATE TABLE posts (id SERIAL PRIMARY KEY, status VARCHAR(20) DEFAULT ''draft'');',
 30, 5, now()),

-- 73
(gen_random_uuid(),
 'FIRST_VALUE Window Function', 'Función de Ventana FIRST_VALUE',
 'For each order, show the very first order amount per customer (ordered by date).',
 'Para cada pedido, muestra el primer monto de pedido por cliente (ordenado por fecha).',
 'sql', 3, 'functions',
 'SELECT id, customer_id, amount, ___(amount) OVER (PARTITION BY customer_id ORDER BY created_at) AS first_amount FROM orders;',
 'SELECT id, customer_id, amount, FIRST_VALUE(amount) OVER (PARTITION BY customer_id ORDER BY created_at) AS first_amount FROM orders;',
 3,
 'FIRST_VALUE() returns the first value in an ordered window partition.', 'FIRST_VALUE() devuelve el primer valor en una partición de ventana ordenada.',
 'Use PARTITION BY customer_id to reset the window per customer.', 'Usa PARTITION BY customer_id para restablecer la ventana por cliente.',
 'SELECT id, customer_id, amount, FIRST_VALUE(amount) OVER (PARTITION BY customer_id ORDER BY created_at) AS first_amount FROM orders;', 'SELECT id, customer_id, amount, FIRST_VALUE(amount) OVER (PARTITION BY customer_id ORDER BY created_at) AS first_amount FROM orders;',
 30, 5, now()),

-- 74
(gen_random_uuid(),
 'ALTER TABLE Rename Column', 'ALTER TABLE Renombrar Columna',
 'Rename the column "phone_number" to "phone" in the "contacts" table.',
 'Renombra la columna "phone_number" a "phone" en la tabla "contacts".',
 'sql', 3, 'basics',
 'ALTER TABLE contacts ___ COLUMN phone_number ___ phone;',
 'ALTER TABLE contacts RENAME COLUMN phone_number TO phone;',
 3,
 'ALTER TABLE RENAME COLUMN renames an existing column.', 'ALTER TABLE RENAME COLUMN renombra una columna existente.',
 'Syntax: ALTER TABLE t RENAME COLUMN old_name TO new_name.', 'Sintaxis: ALTER TABLE t RENAME COLUMN nombre_viejo TO nombre_nuevo.',
 'ALTER TABLE contacts RENAME COLUMN phone_number TO phone;', 'ALTER TABLE contacts RENAME COLUMN phone_number TO phone;',
 30, 5, now()),

-- 75
(gen_random_uuid(),
 'CROSS JOIN', 'CROSS JOIN',
 'Generate all combinations of "colors" and "sizes" tables using a CROSS JOIN.',
 'Genera todas las combinaciones de las tablas "colors" y "sizes" usando un CROSS JOIN.',
 'sql', 3, 'basics',
 'SELECT c.name, s.name FROM colors c ___ sizes s;',
 'SELECT c.name, s.name FROM colors c CROSS JOIN sizes s;',
 3,
 'A CROSS JOIN produces the Cartesian product of two tables.', 'Un CROSS JOIN produce el producto cartesiano de dos tablas.',
 'No ON condition is used — every row from the first table is paired with every row from the second.', 'No se usa condición ON: cada fila de la primera tabla se empareja con cada fila de la segunda.',
 'SELECT c.name, s.name FROM colors c CROSS JOIN sizes s;', 'SELECT c.name, s.name FROM colors c CROSS JOIN sizes s;',
 30, 5, now()),

-- ============================================================
-- DIFFICULTY 4 — 15 exercises (points: 50, penalty: 10)
-- ============================================================

-- 76
(gen_random_uuid(),
 'Recursive CTE', 'CTE Recursivo',
 'Write a recursive CTE to generate numbers 1 through 10.',
 'Escribe un CTE recursivo para generar los números del 1 al 10.',
 'sql', 4, 'algorithms',
 'WITH RECURSIVE nums AS (SELECT 1 AS n UNION ALL SELECT n + 1 FROM nums WHERE n < ___) SELECT n FROM nums;',
 'WITH RECURSIVE nums AS (SELECT 1 AS n UNION ALL SELECT n + 1 FROM nums WHERE n < 10) SELECT n FROM nums;',
 3,
 'A recursive CTE has a base case and a recursive step joined by UNION ALL.', 'Un CTE recursivo tiene un caso base y un paso recursivo unidos por UNION ALL.',
 'The WHERE clause in the recursive step prevents infinite loops.', 'La cláusula WHERE en el paso recursivo evita bucles infinitos.',
 'WITH RECURSIVE nums AS (SELECT 1 AS n UNION ALL SELECT n + 1 FROM nums WHERE n < 10) SELECT n FROM nums;', 'WITH RECURSIVE nums AS (SELECT 1 AS n UNION ALL SELECT n + 1 FROM nums WHERE n < 10) SELECT n FROM nums;',
 50, 10, now()),

-- 77
(gen_random_uuid(),
 'Top N Per Group', 'Top N por Grupo',
 'Select the top 3 highest-paid employees per department using ROW_NUMBER.',
 'Selecciona los 3 empleados mejor pagados por departamento usando ROW_NUMBER.',
 'sql', 4, 'patterns',
 'WITH ranked AS (SELECT *, ROW_NUMBER() OVER (PARTITION BY department_id ORDER BY salary DESC) AS rn FROM employees) SELECT * FROM ranked WHERE ___ <= 3;',
 'WITH ranked AS (SELECT *, ROW_NUMBER() OVER (PARTITION BY department_id ORDER BY salary DESC) AS rn FROM employees) SELECT * FROM ranked WHERE rn <= 3;',
 3,
 'Use a CTE to assign row numbers per group, then filter in the outer query.', 'Usa un CTE para asignar números de fila por grupo, luego filtra en la consulta externa.',
 'You cannot use WHERE on a window function alias directly — wrap it in a CTE or subquery first.', 'No puedes usar WHERE directamente en el alias de una función de ventana — envuélvelo primero en un CTE o subconsulta.',
 'WITH ranked AS (SELECT *, ROW_NUMBER() OVER (PARTITION BY department_id ORDER BY salary DESC) AS rn FROM employees) SELECT * FROM ranked WHERE rn <= 3;', 'WITH ranked AS (SELECT *, ROW_NUMBER() OVER (PARTITION BY department_id ORDER BY salary DESC) AS rn FROM employees) SELECT * FROM ranked WHERE rn <= 3;',
 50, 10, now()),

-- 78
(gen_random_uuid(),
 'Pivot With CASE', 'Pivot con CASE',
 'Pivot the "sales" table to show total amount per quarter (Q1–Q4) as separate columns, grouped by year.',
 'Pivota la tabla "sales" para mostrar el monto total por trimestre (Q1–Q4) como columnas separadas, agrupado por año.',
 'sql', 4, 'patterns',
 'SELECT year, SUM(CASE WHEN quarter = 1 THEN amount ELSE 0 END) AS q1, SUM(CASE WHEN quarter = 2 THEN amount ELSE 0 END) AS q2, ___, ___ FROM sales GROUP BY year;',
 'SELECT year, SUM(CASE WHEN quarter = 1 THEN amount ELSE 0 END) AS q1, SUM(CASE WHEN quarter = 2 THEN amount ELSE 0 END) AS q2, SUM(CASE WHEN quarter = 3 THEN amount ELSE 0 END) AS q3, SUM(CASE WHEN quarter = 4 THEN amount ELSE 0 END) AS q4 FROM sales GROUP BY year;',
 3,
 'Manual pivoting uses conditional aggregation: SUM(CASE WHEN ... THEN value ELSE 0 END).', 'El pivoteo manual usa agregación condicional: SUM(CASE WHEN ... THEN valor ELSE 0 END).',
 'Each column represents one category, summed conditionally, then grouped by the row identifier.', 'Cada columna representa una categoría, sumada condicionalmente, luego agrupada por el identificador de fila.',
 'SELECT year, SUM(CASE WHEN quarter = 1 THEN amount ELSE 0 END) AS q1, SUM(CASE WHEN quarter = 2 THEN amount ELSE 0 END) AS q2, SUM(CASE WHEN quarter = 3 THEN amount ELSE 0 END) AS q3, SUM(CASE WHEN quarter = 4 THEN amount ELSE 0 END) AS q4 FROM sales GROUP BY year;', 'SELECT year, SUM(CASE WHEN quarter = 1 THEN amount ELSE 0 END) AS q1, SUM(CASE WHEN quarter = 2 THEN amount ELSE 0 END) AS q2, SUM(CASE WHEN quarter = 3 THEN amount ELSE 0 END) AS q3, SUM(CASE WHEN quarter = 4 THEN amount ELSE 0 END) AS q4 FROM sales GROUP BY year;',
 50, 10, now()),

-- 79
(gen_random_uuid(),
 'CREATE TRIGGER', 'CREATE TRIGGER',
 'Create a trigger "set_updated_at" on "users" that sets "updated_at" to NOW() before every UPDATE.',
 'Crea un trigger "set_updated_at" en "users" que establezca "updated_at" a NOW() antes de cada UPDATE.',
 'sql', 4, 'patterns',
 'CREATE OR REPLACE FUNCTION set_updated_at() RETURNS trigger AS $$ BEGIN NEW.updated_at = NOW(); RETURN NEW; END; $$ LANGUAGE plpgsql; CREATE TRIGGER set_updated_at ___ UPDATE ON users FOR EACH ROW EXECUTE FUNCTION set_updated_at();',
 'CREATE OR REPLACE FUNCTION set_updated_at() RETURNS trigger AS $$ BEGIN NEW.updated_at = NOW(); RETURN NEW; END; $$ LANGUAGE plpgsql; CREATE TRIGGER set_updated_at BEFORE UPDATE ON users FOR EACH ROW EXECUTE FUNCTION set_updated_at();',
 3,
 'A trigger fires automatically on INSERT, UPDATE, or DELETE events.', 'Un trigger se dispara automáticamente en eventos INSERT, UPDATE o DELETE.',
 'BEFORE UPDATE means the trigger fires before the row is changed, allowing you to modify NEW.', 'BEFORE UPDATE significa que el trigger se dispara antes de que se cambie la fila, permitiéndote modificar NEW.',
 'CREATE OR REPLACE FUNCTION set_updated_at() RETURNS trigger AS $$ BEGIN NEW.updated_at = NOW(); RETURN NEW; END; $$ LANGUAGE plpgsql; CREATE TRIGGER set_updated_at BEFORE UPDATE ON users FOR EACH ROW EXECUTE FUNCTION set_updated_at();', 'CREATE OR REPLACE FUNCTION set_updated_at() RETURNS trigger AS $$ BEGIN NEW.updated_at = NOW(); RETURN NEW; END; $$ LANGUAGE plpgsql; CREATE TRIGGER set_updated_at BEFORE UPDATE ON users FOR EACH ROW EXECUTE FUNCTION set_updated_at();',
 50, 10, now()),

-- 80
(gen_random_uuid(),
 'Transaction with ROLLBACK', 'Transacción con ROLLBACK',
 'Write a transaction that transfers 100 from account 1 to account 2, rolling back if either UPDATE fails.',
 'Escribe una transacción que transfiera 100 de la cuenta 1 a la cuenta 2, haciendo rollback si algún UPDATE falla.',
 'sql', 4, 'patterns',
 'BEGIN; UPDATE accounts SET balance = balance - 100 WHERE id = 1; UPDATE accounts SET balance = balance + 100 WHERE id = ___; COMMIT;',
 'BEGIN; UPDATE accounts SET balance = balance - 100 WHERE id = 1; UPDATE accounts SET balance = balance + 100 WHERE id = 2; COMMIT;',
 3,
 'A transaction groups statements so they all succeed or all fail together.', 'Una transacción agrupa sentencias para que todas tengan éxito o fallen juntas.',
 'BEGIN starts the transaction; COMMIT saves it; ROLLBACK undoes it.', 'BEGIN inicia la transacción; COMMIT la guarda; ROLLBACK la deshace.',
 'BEGIN; UPDATE accounts SET balance = balance - 100 WHERE id = 1; UPDATE accounts SET balance = balance + 100 WHERE id = 2; COMMIT;', 'BEGIN; UPDATE accounts SET balance = balance - 100 WHERE id = 1; UPDATE accounts SET balance = balance + 100 WHERE id = 2; COMMIT;',
 50, 10, now()),

-- 81
(gen_random_uuid(),
 'Correlated Subquery', 'Subconsulta Correlacionada',
 'Select each employee and the average salary of their department using a correlated subquery.',
 'Selecciona cada empleado y el salario promedio de su departamento usando una subconsulta correlacionada.',
 'sql', 4, 'patterns',
 'SELECT name, salary, (SELECT AVG(salary) FROM employees e2 WHERE e2.department_id = ___) AS dept_avg FROM employees e1;',
 'SELECT name, salary, (SELECT AVG(salary) FROM employees e2 WHERE e2.department_id = e1.department_id) AS dept_avg FROM employees e1;',
 3,
 'A correlated subquery references a column from the outer query.', 'Una subconsulta correlacionada hace referencia a una columna de la consulta externa.',
 'It is re-evaluated for each row of the outer query.', 'Se reevalúa por cada fila de la consulta externa.',
 'SELECT name, salary, (SELECT AVG(salary) FROM employees e2 WHERE e2.department_id = e1.department_id) AS dept_avg FROM employees e1;', 'SELECT name, salary, (SELECT AVG(salary) FROM employees e2 WHERE e2.department_id = e1.department_id) AS dept_avg FROM employees e1;',
 50, 10, now()),

-- 82
(gen_random_uuid(),
 'UPSERT with ON CONFLICT', 'UPSERT con ON CONFLICT',
 'Insert a user (id=1, email=''a@b.com'') into "users", updating the email if the id already exists.',
 'Inserta un usuario (id=1, email=''a@b.com'') en "users", actualizando el email si el id ya existe.',
 'sql', 4, 'patterns',
 'INSERT INTO users (id, email) VALUES (1, ''a@b.com'') ON CONFLICT (id) DO UPDATE SET ___ = EXCLUDED.___;',
 'INSERT INTO users (id, email) VALUES (1, ''a@b.com'') ON CONFLICT (id) DO UPDATE SET email = EXCLUDED.email;',
 3,
 'ON CONFLICT DO UPDATE performs an upsert — insert or update if a conflict occurs.', 'ON CONFLICT DO UPDATE realiza un upsert: insertar o actualizar si ocurre un conflicto.',
 'EXCLUDED refers to the row that was proposed for insertion.', 'EXCLUDED hace referencia a la fila que se propuso para inserción.',
 'INSERT INTO users (id, email) VALUES (1, ''a@b.com'') ON CONFLICT (id) DO UPDATE SET email = EXCLUDED.email;', 'INSERT INTO users (id, email) VALUES (1, ''a@b.com'') ON CONFLICT (id) DO UPDATE SET email = EXCLUDED.email;',
 50, 10, now()),

-- 83
(gen_random_uuid(),
 'MATERIALIZED VIEW', 'VISTA MATERIALIZADA',
 'Create a materialized view "monthly_sales" that sums "amount" grouped by month from "orders".',
 'Crea una vista materializada "monthly_sales" que sume "amount" agrupado por mes de "orders".',
 'sql', 4, 'patterns',
 'CREATE ___ VIEW monthly_sales AS SELECT DATE_TRUNC(''month'', created_at) AS month, SUM(amount) FROM orders GROUP BY ___;',
 'CREATE MATERIALIZED VIEW monthly_sales AS SELECT DATE_TRUNC(''month'', created_at) AS month, SUM(amount) FROM orders GROUP BY DATE_TRUNC(''month'', created_at);',
 3,
 'A materialized view stores the query result physically, unlike a regular view.', 'Una vista materializada almacena el resultado de la consulta físicamente, a diferencia de una vista normal.',
 'Use REFRESH MATERIALIZED VIEW to update its data.', 'Usa REFRESH MATERIALIZED VIEW para actualizar sus datos.',
 'CREATE MATERIALIZED VIEW monthly_sales AS SELECT DATE_TRUNC(''month'', created_at) AS month, SUM(amount) FROM orders GROUP BY DATE_TRUNC(''month'', created_at);', 'CREATE MATERIALIZED VIEW monthly_sales AS SELECT DATE_TRUNC(''month'', created_at) AS month, SUM(amount) FROM orders GROUP BY DATE_TRUNC(''month'', created_at);',
 50, 10, now()),

-- 84
(gen_random_uuid(),
 'PERCENT_RANK Window Function', 'Función de Ventana PERCENT_RANK',
 'Compute the percentile rank of each employee''s salary among all employees.',
 'Calcula el rango percentil del salario de cada empleado entre todos los empleados.',
 'sql', 4, 'functions',
 'SELECT name, salary, ___ OVER (ORDER BY salary) AS pct_rank FROM employees;',
 'SELECT name, salary, PERCENT_RANK() OVER (ORDER BY salary) AS pct_rank FROM employees;',
 3,
 'PERCENT_RANK() returns a value between 0 and 1 representing the relative position.', 'PERCENT_RANK() devuelve un valor entre 0 y 1 que representa la posición relativa.',
 'The first row gets 0.0; the last row gets 1.0.', 'La primera fila obtiene 0.0; la última fila obtiene 1.0.',
 'SELECT name, salary, PERCENT_RANK() OVER (ORDER BY salary) AS pct_rank FROM employees;', 'SELECT name, salary, PERCENT_RANK() OVER (ORDER BY salary) AS pct_rank FROM employees;',
 50, 10, now()),

-- 85
(gen_random_uuid(),
 'JSON Column Query', 'Consulta de Columna JSON',
 'Select all orders where the JSON column "metadata" contains a key "source" with value ''mobile''.',
 'Selecciona todos los pedidos donde la columna JSON "metadata" contenga la clave "source" con valor ''mobile''.',
 'sql', 4, 'patterns',
 'SELECT * FROM orders WHERE metadata ->> ___ = ''mobile'';',
 'SELECT * FROM orders WHERE metadata ->> ''source'' = ''mobile'';',
 3,
 'The ->> operator extracts a JSON field as text in PostgreSQL.', 'El operador ->> extrae un campo JSON como texto en PostgreSQL.',
 'Use ->> ''key'' to get the string value of a JSON key.', 'Usa ->> ''clave'' para obtener el valor de cadena de una clave JSON.',
 'SELECT * FROM orders WHERE metadata ->> ''source'' = ''mobile'';', 'SELECT * FROM orders WHERE metadata ->> ''source'' = ''mobile'';',
 50, 10, now()),

-- 86
(gen_random_uuid(),
 'FULL OUTER JOIN', 'FULL OUTER JOIN',
 'Select all rows from both "employees" and "departments", with NULLs where there is no match.',
 'Selecciona todas las filas de "employees" y "departments", con NULLs donde no haya coincidencia.',
 'sql', 4, 'basics',
 'SELECT e.name, d.name FROM employees e ___ departments d ON e.department_id = d.id;',
 'SELECT e.name, d.name FROM employees e FULL OUTER JOIN departments d ON e.department_id = d.id;',
 3,
 'FULL OUTER JOIN combines LEFT JOIN and RIGHT JOIN.', 'FULL OUTER JOIN combina LEFT JOIN y RIGHT JOIN.',
 'Rows without a match in either table are filled with NULLs.', 'Las filas sin coincidencia en ninguna tabla se rellenan con NULLs.',
 'SELECT e.name, d.name FROM employees e FULL OUTER JOIN departments d ON e.department_id = d.id;', 'SELECT e.name, d.name FROM employees e FULL OUTER JOIN departments d ON e.department_id = d.id;',
 50, 10, now()),

-- 87
(gen_random_uuid(),
 'WINDOW Clause Reuse', 'Reutilización de Cláusula WINDOW',
 'Define a named window "w" partitioned by department_id and use it for both ROW_NUMBER and RANK.',
 'Define una ventana llamada "w" particionada por department_id y úsala tanto para ROW_NUMBER como para RANK.',
 'sql', 4, 'functions',
 'SELECT name, ROW_NUMBER() OVER w AS rn, RANK() OVER w AS rnk FROM employees WINDOW w AS (PARTITION BY ___ ORDER BY salary DESC);',
 'SELECT name, ROW_NUMBER() OVER w AS rn, RANK() OVER w AS rnk FROM employees WINDOW w AS (PARTITION BY department_id ORDER BY salary DESC);',
 3,
 'The WINDOW clause defines a named window for reuse across multiple window functions.', 'La cláusula WINDOW define una ventana con nombre para reutilizar en múltiples funciones de ventana.',
 'Place the WINDOW clause at the end of the query, after ORDER BY.', 'Coloca la cláusula WINDOW al final de la consulta, después de ORDER BY.',
 'SELECT name, ROW_NUMBER() OVER w AS rn, RANK() OVER w AS rnk FROM employees WINDOW w AS (PARTITION BY department_id ORDER BY salary DESC);', 'SELECT name, ROW_NUMBER() OVER w AS rn, RANK() OVER w AS rnk FROM employees WINDOW w AS (PARTITION BY department_id ORDER BY salary DESC);',
 50, 10, now()),

-- 88
(gen_random_uuid(),
 'Hierarchical Query with Recursive CTE', 'Consulta Jerárquica con CTE Recursivo',
 'Build an employee hierarchy: find all direct and indirect reports under employee id=1.',
 'Construye una jerarquía de empleados: encuentra todos los subordinados directos e indirectos del empleado id=1.',
 'sql', 4, 'algorithms',
 'WITH RECURSIVE hierarchy AS (SELECT id, name, manager_id FROM employees WHERE id = 1 UNION ALL SELECT e.id, e.name, e.manager_id FROM employees e ___ hierarchy h ON e.manager_id = h.id) SELECT * FROM hierarchy;',
 'WITH RECURSIVE hierarchy AS (SELECT id, name, manager_id FROM employees WHERE id = 1 UNION ALL SELECT e.id, e.name, e.manager_id FROM employees e INNER JOIN hierarchy h ON e.manager_id = h.id) SELECT * FROM hierarchy;',
 3,
 'Recursive CTEs are ideal for tree/graph traversal.', 'Los CTEs recursivos son ideales para recorridos de árboles/grafos.',
 'The recursive step joins the table to the CTE itself to walk down the hierarchy.', 'El paso recursivo une la tabla con el propio CTE para recorrer la jerarquía.',
 'WITH RECURSIVE hierarchy AS (SELECT id, name, manager_id FROM employees WHERE id = 1 UNION ALL SELECT e.id, e.name, e.manager_id FROM employees e INNER JOIN hierarchy h ON e.manager_id = h.id) SELECT * FROM hierarchy;', 'WITH RECURSIVE hierarchy AS (SELECT id, name, manager_id FROM employees WHERE id = 1 UNION ALL SELECT e.id, e.name, e.manager_id FROM employees e INNER JOIN hierarchy h ON e.manager_id = h.id) SELECT * FROM hierarchy;',
 50, 10, now()),

-- 89
(gen_random_uuid(),
 'GENERATE_SERIES Date Range', 'GENERATE_SERIES Rango de Fechas',
 'Generate one row per day between 2024-01-01 and 2024-01-07 using generate_series.',
 'Genera una fila por día entre 2024-01-01 y 2024-01-07 usando generate_series.',
 'sql', 4, 'functions',
 'SELECT ___(''2024-01-01''::date, ''2024-01-07''::date, ''1 day''::interval) AS day;',
 'SELECT generate_series(''2024-01-01''::date, ''2024-01-07''::date, ''1 day''::interval) AS day;',
 3,
 'generate_series produces a set of values between two bounds.', 'generate_series produce un conjunto de valores entre dos límites.',
 'For dates, cast the bounds to date and set the step as an interval.', 'Para fechas, convierte los límites a date y establece el paso como un intervalo.',
 'SELECT generate_series(''2024-01-01''::date, ''2024-01-07''::date, ''1 day''::interval) AS day;', 'SELECT generate_series(''2024-01-01''::date, ''2024-01-07''::date, ''1 day''::interval) AS day;',
 50, 10, now()),

-- 90
(gen_random_uuid(),
 'ARRAY_AGG Function', 'Función ARRAY_AGG',
 'For each customer, aggregate all their order IDs into an array.',
 'Para cada cliente, agrega todos sus IDs de pedido en un arreglo.',
 'sql', 4, 'arrays',
 'SELECT customer_id, ___(id ORDER BY created_at) AS order_ids FROM orders GROUP BY customer_id;',
 'SELECT customer_id, ARRAY_AGG(id ORDER BY created_at) AS order_ids FROM orders GROUP BY customer_id;',
 3,
 'ARRAY_AGG collects values into an array.', 'ARRAY_AGG recopila valores en un arreglo.',
 'You can specify ORDER BY inside ARRAY_AGG to control the order of elements.', 'Puedes especificar ORDER BY dentro de ARRAY_AGG para controlar el orden de los elementos.',
 'SELECT customer_id, ARRAY_AGG(id ORDER BY created_at) AS order_ids FROM orders GROUP BY customer_id;', 'SELECT customer_id, ARRAY_AGG(id ORDER BY created_at) AS order_ids FROM orders GROUP BY customer_id;',
 50, 10, now()),

-- ============================================================
-- DIFFICULTY 5 — 10 exercises (points: 100, penalty: 10)
-- ============================================================

-- 91
(gen_random_uuid(),
 'Gaps and Islands Problem', 'Problema de Huecos e Islas',
 'Find contiguous date ranges (islands) in the "user_logins" table (columns: user_id, login_date). Return the start and end of each island per user.',
 'Encuentra rangos de fechas contiguas (islas) en la tabla "user_logins" (columnas: user_id, login_date). Devuelve el inicio y fin de cada isla por usuario.',
 'sql', 5, 'algorithms',
 'WITH numbered AS (SELECT user_id, login_date, login_date - INTERVAL ''1 day'' * ROW_NUMBER() OVER (PARTITION BY user_id ORDER BY login_date) AS grp FROM user_logins) SELECT user_id, MIN(login_date) AS island_start, ___(login_date) AS island_end FROM numbered GROUP BY user_id, grp ORDER BY user_id, island_start;',
 'WITH numbered AS (SELECT user_id, login_date, login_date - INTERVAL ''1 day'' * ROW_NUMBER() OVER (PARTITION BY user_id ORDER BY login_date) AS grp FROM user_logins) SELECT user_id, MIN(login_date) AS island_start, MAX(login_date) AS island_end FROM numbered GROUP BY user_id, grp ORDER BY user_id, island_start;',
 3,
 'Subtract the row number (as an interval) from each date. Consecutive dates will produce the same result, forming an island group.', 'Resta el número de fila (como intervalo) de cada fecha. Las fechas consecutivas producirán el mismo resultado, formando un grupo isla.',
 'Group by both user_id and the computed group key. MIN/MAX of the date within each group gives the island boundaries.', 'Agrupa por user_id y la clave de grupo calculada. MIN/MAX de la fecha dentro de cada grupo da los límites de la isla.',
 'WITH numbered AS (SELECT user_id, login_date, login_date - INTERVAL ''1 day'' * ROW_NUMBER() OVER (PARTITION BY user_id ORDER BY login_date) AS grp FROM user_logins) SELECT user_id, MIN(login_date) AS island_start, MAX(login_date) AS island_end FROM numbered GROUP BY user_id, grp ORDER BY user_id, island_start;', 'WITH numbered AS (SELECT user_id, login_date, login_date - INTERVAL ''1 day'' * ROW_NUMBER() OVER (PARTITION BY user_id ORDER BY login_date) AS grp FROM user_logins) SELECT user_id, MIN(login_date) AS island_start, MAX(login_date) AS island_end FROM numbered GROUP BY user_id, grp ORDER BY user_id, island_start;',
 100, 10, now()),

-- 92
(gen_random_uuid(),
 'Median Without Built-in Function', 'Mediana Sin Función Nativa',
 'Calculate the median salary from the "employees" table without using a built-in MEDIAN function.',
 'Calcula el salario mediano de la tabla "employees" sin usar una función MEDIAN nativa.',
 'sql', 5, 'algorithms',
 'SELECT AVG(salary) AS median FROM (SELECT salary FROM employees ORDER BY salary LIMIT 2 - MOD(COUNT(*) OVER(), 2) OFFSET ___ FROM employees)) sub;',
 'SELECT AVG(salary) AS median FROM (SELECT salary FROM employees ORDER BY salary LIMIT 2 - MOD((SELECT COUNT(*) FROM employees), 2) OFFSET (SELECT (COUNT(*) - 1) / 2 FROM employees)) sub;',
 3,
 'The median is the middle value. For even counts, it is the average of the two middle values.', 'La mediana es el valor central. Para conteos pares, es el promedio de los dos valores centrales.',
 'Use OFFSET to skip to the middle row: (COUNT(*) - 1) / 2. Use LIMIT 1 or 2 depending on whether the count is odd or even.', 'Usa OFFSET para ir a la fila central: (COUNT(*) - 1) / 2. Usa LIMIT 1 o 2 según si el conteo es impar o par.',
 'SELECT AVG(salary) AS median FROM (SELECT salary FROM employees ORDER BY salary LIMIT 2 - MOD((SELECT COUNT(*) FROM employees), 2) OFFSET (SELECT (COUNT(*) - 1) / 2 FROM employees)) sub;', 'SELECT AVG(salary) AS median FROM (SELECT salary FROM employees ORDER BY salary LIMIT 2 - MOD((SELECT COUNT(*) FROM employees), 2) OFFSET (SELECT (COUNT(*) - 1) / 2 FROM employees)) sub;',
 100, 10, now()),

-- 93
(gen_random_uuid(),
 'Consecutive Wins Streak', 'Racha de Victorias Consecutivas',
 'Find the longest consecutive winning streak per player from the "match_results" table (columns: player_id, match_date, result where result=''win'').',
 'Encuentra la racha de victorias consecutivas más larga por jugador en la tabla "match_results" (columnas: player_id, match_date, result donde result=''win'').',
 'sql', 5, 'algorithms',
 'WITH grp AS (SELECT player_id, match_date, result, ROW_NUMBER() OVER (PARTITION BY player_id ORDER BY match_date) - ROW_NUMBER() OVER (PARTITION BY player_id, result ORDER BY match_date) AS island FROM match_results) SELECT player_id, MAX(streak) AS longest_streak FROM (SELECT player_id, COUNT(*) AS streak FROM grp WHERE result = ''win'' GROUP BY player_id, ___) s GROUP BY player_id;',
 'WITH grp AS (SELECT player_id, match_date, result, ROW_NUMBER() OVER (PARTITION BY player_id ORDER BY match_date) - ROW_NUMBER() OVER (PARTITION BY player_id, result ORDER BY match_date) AS island FROM match_results) SELECT player_id, MAX(streak) AS longest_streak FROM (SELECT player_id, COUNT(*) AS streak FROM grp WHERE result = ''win'' GROUP BY player_id, island) s GROUP BY player_id;',
 3,
 'Use the classic gaps-and-islands trick: subtract two row numbers to identify contiguous groups.', 'Usa el truco clásico de huecos e islas: resta dos números de fila para identificar grupos contiguos.',
 'The difference of (overall row number) - (row number partitioned by result) is constant within each consecutive run.', 'La diferencia de (número de fila global) - (número de fila particionado por resultado) es constante dentro de cada racha consecutiva.',
 'WITH grp AS (SELECT player_id, match_date, result, ROW_NUMBER() OVER (PARTITION BY player_id ORDER BY match_date) - ROW_NUMBER() OVER (PARTITION BY player_id, result ORDER BY match_date) AS island FROM match_results) SELECT player_id, MAX(streak) AS longest_streak FROM (SELECT player_id, COUNT(*) AS streak FROM grp WHERE result = ''win'' GROUP BY player_id, island) s GROUP BY player_id;', 'WITH grp AS (SELECT player_id, match_date, result, ROW_NUMBER() OVER (PARTITION BY player_id ORDER BY match_date) - ROW_NUMBER() OVER (PARTITION BY player_id, result ORDER BY match_date) AS island FROM match_results) SELECT player_id, MAX(streak) AS longest_streak FROM (SELECT player_id, COUNT(*) AS streak FROM grp WHERE result = ''win'' GROUP BY player_id, island) s GROUP BY player_id;',
 100, 10, now()),

-- 94
(gen_random_uuid(),
 'Rolling 7-Day Average', 'Promedio Móvil de 7 Días',
 'Calculate a rolling 7-day average of "daily_sales" for each row in the "sales_daily" table (columns: sale_date, revenue).',
 'Calcula un promedio móvil de 7 días de "revenue" para cada fila en la tabla "sales_daily" (columnas: sale_date, revenue).',
 'sql', 5, 'algorithms',
 'SELECT sale_date, revenue, AVG(revenue) OVER (ORDER BY sale_date ROWS BETWEEN ___ PRECEDING AND CURRENT ROW) AS rolling_7d_avg FROM sales_daily;',
 'SELECT sale_date, revenue, AVG(revenue) OVER (ORDER BY sale_date ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS rolling_7d_avg FROM sales_daily;',
 3,
 'Use a window frame with ROWS BETWEEN to define how many past rows to include.', 'Usa un marco de ventana con ROWS BETWEEN para definir cuántas filas pasadas incluir.',
 '7 days = current row + 6 preceding rows, so ROWS BETWEEN 6 PRECEDING AND CURRENT ROW.', '7 días = fila actual + 6 filas anteriores, por lo que ROWS BETWEEN 6 PRECEDING AND CURRENT ROW.',
 'SELECT sale_date, revenue, AVG(revenue) OVER (ORDER BY sale_date ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS rolling_7d_avg FROM sales_daily;', 'SELECT sale_date, revenue, AVG(revenue) OVER (ORDER BY sale_date ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS rolling_7d_avg FROM sales_daily;',
 100, 10, now()),

-- 95
(gen_random_uuid(),
 'String Aggregation with STRING_AGG', 'Agregación de Cadenas con STRING_AGG',
 'For each department, produce a comma-separated list of employee names sorted alphabetically.',
 'Para cada departamento, produce una lista separada por comas de nombres de empleados ordenada alfabéticamente.',
 'sql', 5, 'strings',
 'SELECT department_id, ___(name, '', '' ORDER BY name) AS employee_list FROM employees GROUP BY department_id;',
 'SELECT department_id, STRING_AGG(name, '', '' ORDER BY name) AS employee_list FROM employees GROUP BY department_id;',
 3,
 'STRING_AGG concatenates values from multiple rows into a single string with a delimiter.', 'STRING_AGG concatena valores de múltiples filas en una sola cadena con un delimitador.',
 'You can include ORDER BY inside STRING_AGG to control the order of elements in the result.', 'Puedes incluir ORDER BY dentro de STRING_AGG para controlar el orden de los elementos en el resultado.',
 'SELECT department_id, STRING_AGG(name, '', '' ORDER BY name) AS employee_list FROM employees GROUP BY department_id;', 'SELECT department_id, STRING_AGG(name, '', '' ORDER BY name) AS employee_list FROM employees GROUP BY department_id;',
 100, 10, now()),

-- 96
(gen_random_uuid(),
 'JSONB Array Unnest and Aggregate', 'Unnest y Agregación de Array JSONB',
 'The "orders" table has a JSONB column "items" that is an array of objects. Unnest and count the total number of items across all orders.',
 'La tabla "orders" tiene una columna JSONB "items" que es un arreglo de objetos. Haz unnest y cuenta el número total de ítems en todos los pedidos.',
 'sql', 5, 'arrays',
 'SELECT COUNT(*) AS total_items FROM orders, ___(items) AS item;',
 'SELECT COUNT(*) AS total_items FROM orders, jsonb_array_elements(items) AS item;',
 3,
 'jsonb_array_elements expands a JSONB array into one row per element.', 'jsonb_array_elements expande un arreglo JSONB en una fila por elemento.',
 'Use a lateral join (comma syntax) to apply jsonb_array_elements to each row.', 'Usa un join lateral (sintaxis de coma) para aplicar jsonb_array_elements a cada fila.',
 'SELECT COUNT(*) AS total_items FROM orders, jsonb_array_elements(items) AS item;', 'SELECT COUNT(*) AS total_items FROM orders, jsonb_array_elements(items) AS item;',
 100, 10, now()),

-- 97
(gen_random_uuid(),
 'Detect Duplicate Rows', 'Detectar Filas Duplicadas',
 'Find all email addresses that appear more than once in the "users" table, along with the count.',
 'Encuentra todas las direcciones de email que aparecen más de una vez en la tabla "users", junto con el conteo.',
 'sql', 5, 'data_structures',
 'SELECT email, COUNT(*) AS cnt FROM users GROUP BY email HAVING ___ > 1 ORDER BY cnt DESC;',
 'SELECT email, COUNT(*) AS cnt FROM users GROUP BY email HAVING COUNT(*) > 1 ORDER BY cnt DESC;',
 3,
 'Use GROUP BY on the column you want to check for duplicates.', 'Usa GROUP BY en la columna que deseas verificar por duplicados.',
 'HAVING COUNT(*) > 1 filters groups that have more than one row.', 'HAVING COUNT(*) > 1 filtra los grupos que tienen más de una fila.',
 'SELECT email, COUNT(*) AS cnt FROM users GROUP BY email HAVING COUNT(*) > 1 ORDER BY cnt DESC;', 'SELECT email, COUNT(*) AS cnt FROM users GROUP BY email HAVING COUNT(*) > 1 ORDER BY cnt DESC;',
 100, 10, now()),

-- 98
(gen_random_uuid(),
 'Delete Duplicate Rows Keep Latest', 'Eliminar Filas Duplicadas Conservar la Más Reciente',
 'Delete duplicate users keeping only the row with the highest id for each email.',
 'Elimina usuarios duplicados conservando solo la fila con el id más alto para cada email.',
 'sql', 5, 'data_structures',
 'DELETE FROM users WHERE id NOT IN (SELECT ___(id) FROM users GROUP BY email);',
 'DELETE FROM users WHERE id NOT IN (SELECT MAX(id) FROM users GROUP BY email);',
 3,
 'Use a subquery to identify which id to keep for each email.', 'Usa una subconsulta para identificar qué id conservar para cada email.',
 'MAX(id) per email returns the most recently inserted row (assuming sequential ids).', 'MAX(id) por email devuelve la fila insertada más recientemente (asumiendo ids secuenciales).',
 'DELETE FROM users WHERE id NOT IN (SELECT MAX(id) FROM users GROUP BY email);', 'DELETE FROM users WHERE id NOT IN (SELECT MAX(id) FROM users GROUP BY email);',
 100, 10, now()),

-- 99
(gen_random_uuid(),
 'Partitioned Rolling Sum Reset Monthly', 'Suma Acumulada por Mes con Reinicio',
 'Compute a running total of "amount" that resets each month, partitioned by user_id from "transactions".',
 'Calcula un total acumulado de "amount" que se reinicia cada mes, particionado por user_id de "transactions".',
 'sql', 5, 'algorithms',
 'SELECT user_id, transaction_date, amount, SUM(amount) OVER (PARTITION BY user_id, DATE_TRUNC(''month'', ___) ORDER BY transaction_date) AS monthly_running_total FROM transactions;',
 'SELECT user_id, transaction_date, amount, SUM(amount) OVER (PARTITION BY user_id, DATE_TRUNC(''month'', transaction_date) ORDER BY transaction_date) AS monthly_running_total FROM transactions;',
 3,
 'Add DATE_TRUNC(''month'', date_column) to the PARTITION BY clause to restart each month.', 'Agrega DATE_TRUNC(''month'', columna_fecha) a la cláusula PARTITION BY para reiniciar cada mes.',
 'PARTITION BY user_id, month creates one window frame per user per month.', 'PARTITION BY user_id, mes crea un marco de ventana por usuario por mes.',
 'SELECT user_id, transaction_date, amount, SUM(amount) OVER (PARTITION BY user_id, DATE_TRUNC(''month'', transaction_date) ORDER BY transaction_date) AS monthly_running_total FROM transactions;', 'SELECT user_id, transaction_date, amount, SUM(amount) OVER (PARTITION BY user_id, DATE_TRUNC(''month'', transaction_date) ORDER BY transaction_date) AS monthly_running_total FROM transactions;',
 100, 10, now()),

-- 100
(gen_random_uuid(),
 'Funnel Analysis with CTEs', 'Análisis de Embudo con CTEs',
 'Compute a conversion funnel: count users who (1) visited, (2) signed_up, (3) purchased — each as a separate step — from the "events" table (columns: user_id, event_type).',
 'Calcula un embudo de conversión: cuenta los usuarios que (1) visitaron, (2) se registraron, (3) compraron — cada uno como un paso separado — de la tabla "events" (columnas: user_id, event_type).',
 'sql', 5, 'challenges',
 'WITH visited AS (SELECT COUNT(DISTINCT user_id) AS cnt FROM events WHERE event_type = ''visit''), signed_up AS (SELECT COUNT(DISTINCT user_id) AS cnt FROM events WHERE event_type = ''signup''), purchased AS (___ COUNT(DISTINCT user_id) AS cnt FROM events WHERE event_type = ''purchase'') SELECT v.cnt AS visitors, s.cnt AS signups, p.cnt AS purchases FROM visited v, signed_up s, purchased p;',
 'WITH visited AS (SELECT COUNT(DISTINCT user_id) AS cnt FROM events WHERE event_type = ''visit''), signed_up AS (SELECT COUNT(DISTINCT user_id) AS cnt FROM events WHERE event_type = ''signup''), purchased AS (SELECT COUNT(DISTINCT user_id) AS cnt FROM events WHERE event_type = ''purchase'') SELECT v.cnt AS visitors, s.cnt AS signups, p.cnt AS purchases FROM visited v, signed_up s, purchased p;',
 3,
 'Break the funnel into one CTE per step, each counting distinct users for that event type.', 'Divide el embudo en un CTE por paso, cada uno contando usuarios distintos para ese tipo de evento.',
 'Cross-join the scalar CTEs (each returns one row) to display all metrics side by side.', 'Haz cross-join de los CTEs escalares (cada uno devuelve una fila) para mostrar todas las métricas en paralelo.',
 'WITH visited AS (SELECT COUNT(DISTINCT user_id) AS cnt FROM events WHERE event_type = ''visit''), signed_up AS (SELECT COUNT(DISTINCT user_id) AS cnt FROM events WHERE event_type = ''signup''), purchased AS (SELECT COUNT(DISTINCT user_id) AS cnt FROM events WHERE event_type = ''purchase'') SELECT v.cnt AS visitors, s.cnt AS signups, p.cnt AS purchases FROM visited v, signed_up s, purchased p;', 'WITH visited AS (SELECT COUNT(DISTINCT user_id) AS cnt FROM events WHERE event_type = ''visit''), signed_up AS (SELECT COUNT(DISTINCT user_id) AS cnt FROM events WHERE event_type = ''signup''), purchased AS (SELECT COUNT(DISTINCT user_id) AS cnt FROM events WHERE event_type = ''purchase'') SELECT v.cnt AS visitors, s.cnt AS signups, p.cnt AS purchases FROM visited v, signed_up s, purchased p;',
 100, 10, now())

ON CONFLICT DO NOTHING;

COMMIT;
