-- 053_exercises_rust.sql
-- 50 Rust programming exercises, bilingual EN+ES
-- Distribution: diff1=12, diff2=12, diff3=13, diff4=8, diff5=5
-- Points: 10/20/30/50/100 | Penalty: 3/3/5/10/10
-- Focus: ownership, borrowing, lifetimes, pattern matching, enums, traits,
--        Result/Option, iterators, closures, structs, impl, macros, concurrency

BEGIN;

INSERT INTO exercises (
  id, title_en, title_es, description_en, description_es,
  language, difficulty, category,
  starter_code, expected_output,
  hint_count, hint_1_en, hint_1_es, hint_2_en, hint_2_es, hint_3_en, hint_3_es,
  points, hints_used_penalty, created_at
) VALUES

-- ============================================================
-- DIFFICULTY 1 — 12 exercises (points: 10, penalty: 3)
-- ============================================================

-- 1. basics
(gen_random_uuid(),
 'Hello Rust', 'Hola Rust',
 'Print "Hello, Rust!" to the console.',
 'Imprime "Hello, Rust!" en la consola.',
 'rust', 1, 'basics',
 'fn main() {\n    // your code\n}',
 'Hello, Rust!',
 3,
 'Use the println! macro to print a line.', 'Usa la macro println! para imprimir una línea.',
 'Pass the string as the first argument to println!.', 'Pasa la cadena como primer argumento a println!.',
 'println!("Hello, Rust!")', 'println!("Hello, Rust!")',
 10, 3, now()),

-- 2. basics
(gen_random_uuid(),
 'Declare a Variable', 'Declarar una Variable',
 'Declare an immutable integer variable named age with value 30 and print it.',
 'Declara una variable entera inmutable llamada age con valor 30 e imprímela.',
 'rust', 1, 'basics',
 'fn main() {\n    // your code\n}',
 '30',
 3,
 'Use let to declare a variable.', 'Usa let para declarar una variable.',
 'Rust infers the type from the value automatically.', 'Rust infiere el tipo del valor automáticamente.',
 'let age = 30;\nprintln!("{}", age);', 'let age = 30;\nprintln!("{}", age);',
 10, 3, now()),

-- 3. basics
(gen_random_uuid(),
 'Mutable Variable', 'Variable Mutable',
 'Declare a mutable variable count with value 0, increment it to 1, and print it.',
 'Declara una variable mutable count con valor 0, increméntala a 1 e imprímela.',
 'rust', 1, 'basics',
 'fn main() {\n    // your code\n}',
 '1',
 3,
 'Variables in Rust are immutable by default.', 'Las variables en Rust son inmutables por defecto.',
 'Add the mut keyword: let mut count = 0;', 'Agrega la palabra clave mut: let mut count = 0;',
 'count += 1;\nprintln!("{}", count);', 'count += 1;\nprintln!("{}", count);',
 10, 3, now()),

-- 4. basics
(gen_random_uuid(),
 'String Formatting', 'Formateo de Cadenas',
 'Use println! to print "Name: Alice, Age: 25" using format placeholders.',
 'Usa println! para imprimir "Name: Alice, Age: 25" con marcadores de formato.',
 'rust', 1, 'basics',
 'fn main() {\n    // your code\n}',
 'Name: Alice, Age: 25',
 3,
 'println! uses {} as a placeholder for any Display value.', 'println! usa {} como marcador para cualquier valor Display.',
 'Pass additional arguments after the format string.', 'Pasa argumentos adicionales tras la cadena de formato.',
 'println!("Name: {}, Age: {}", "Alice", 25);', 'println!("Name: {}, Age: {}", "Alice", 25);',
 10, 3, now()),

-- 5. control-flow
(gen_random_uuid(),
 'If / Else', 'If / Else',
 'Declare x = 10. If x > 5 print "big", else print "small".',
 'Declara x = 10. Si x > 5 imprime "big", si no imprime "small".',
 'rust', 1, 'control-flow',
 'fn main() {\n    // your code\n}',
 'big',
 3,
 'if/else in Rust does not require parentheses around the condition.', 'if/else en Rust no requiere paréntesis alrededor de la condición.',
 'Declare x with let and compare using >.', 'Declara x con let y compara usando >.',
 'if x > 5 { println!("big"); } else { println!("small"); }', 'if x > 5 { println!("big"); } else { println!("small"); }',
 10, 3, now()),

-- 6. control-flow
(gen_random_uuid(),
 'For Loop', 'Bucle For',
 'Print numbers 1 through 5, each on its own line.',
 'Imprime los números del 1 al 5, cada uno en su propia línea.',
 'rust', 1, 'control-flow',
 'fn main() {\n    // your code\n}',
 '1\n2\n3\n4\n5',
 3,
 'Rust ranges use the .. or ..= syntax.', 'Los rangos en Rust usan la sintaxis .. o ..=.',
 'Use for i in 1..=5 to include 5.', 'Usa for i in 1..=5 para incluir el 5.',
 'for i in 1..=5 { println!("{}", i); }', 'for i in 1..=5 { println!("{}", i); }',
 10, 3, now()),

-- 7. functions
(gen_random_uuid(),
 'Simple Function', 'Función Simple',
 'Write a function add(a: i32, b: i32) -> i32 that returns the sum. Call it with 4 and 6 and print the result.',
 'Escribe una función add(a: i32, b: i32) -> i32 que retorne la suma. Llámala con 4 y 6 e imprime el resultado.',
 'rust', 1, 'functions',
 'fn main() {\n    // your code\n}',
 '10',
 3,
 'Define the function outside main using the fn keyword.', 'Define la función fuera de main usando la palabra clave fn.',
 'The return type is declared after -> in the signature.', 'El tipo de retorno se declara después de -> en la firma.',
 'fn add(a: i32, b: i32) -> i32 { a + b }', 'fn add(a: i32, b: i32) -> i32 { a + b }',
 10, 3, now()),

-- 8. ownership
(gen_random_uuid(),
 'String Ownership', 'Propiedad de String',
 'Create a String with value "hello", move it into a variable s2, and print s2.',
 'Crea un String con valor "hello", muévelo a una variable s2 e imprime s2.',
 'rust', 1, 'ownership',
 'fn main() {\n    // your code\n}',
 'hello',
 3,
 'Use String::from("hello") to create a heap-allocated String.', 'Usa String::from("hello") para crear un String en el heap.',
 'Assigning a String moves ownership to the new variable.', 'Asignar un String mueve la propiedad a la nueva variable.',
 'let s1 = String::from("hello");\nlet s2 = s1;\nprintln!("{}", s2);', 'let s1 = String::from("hello");\nlet s2 = s1;\nprintln!("{}", s2);',
 10, 3, now()),

-- 9. basics
(gen_random_uuid(),
 'Tuple Basics', 'Bases de Tuplas',
 'Create a tuple (1, "hello", true) and print each element on its own line.',
 'Crea una tupla (1, "hello", true) e imprime cada elemento en su propia línea.',
 'rust', 1, 'basics',
 'fn main() {\n    // your code\n}',
 '1\nhello\ntrue',
 3,
 'Access tuple elements with dot notation: t.0, t.1, t.2.', 'Accede a los elementos de la tupla con notación de punto: t.0, t.1, t.2.',
 'Assign the tuple to a variable first.', 'Asigna la tupla a una variable primero.',
 'let t = (1, "hello", true);\nprintln!("{}\n{}\n{}", t.0, t.1, t.2);', 'let t = (1, "hello", true);\nprintln!("{}\n{}\n{}", t.0, t.1, t.2);',
 10, 3, now()),

-- 10. arrays
(gen_random_uuid(),
 'Array Basics', 'Bases de Arrays',
 'Create an array of 5 integers [10, 20, 30, 40, 50] and print its length.',
 'Crea un array de 5 enteros [10, 20, 30, 40, 50] e imprime su longitud.',
 'rust', 1, 'arrays',
 'fn main() {\n    // your code\n}',
 '5',
 3,
 'Arrays in Rust have a fixed size known at compile time.', 'Los arrays en Rust tienen tamaño fijo conocido en tiempo de compilación.',
 'Use the .len() method to get the length.', 'Usa el método .len() para obtener la longitud.',
 'let arr = [10, 20, 30, 40, 50];\nprintln!("{}", arr.len());', 'let arr = [10, 20, 30, 40, 50];\nprintln!("{}", arr.len());',
 10, 3, now()),

-- 11. basics
(gen_random_uuid(),
 'While Loop', 'Bucle While',
 'Use a while loop to print numbers 1 through 3.',
 'Usa un bucle while para imprimir los números del 1 al 3.',
 'rust', 1, 'control-flow',
 'fn main() {\n    // your code\n}',
 '1\n2\n3',
 3,
 'Declare a mutable counter variable before the loop.', 'Declara una variable contadora mutable antes del bucle.',
 'while condition { body } — increment inside the body.', 'while condicion { cuerpo } — incrementa dentro del cuerpo.',
 'let mut i = 1;\nwhile i <= 3 { println!("{}", i); i += 1; }', 'let mut i = 1;\nwhile i <= 3 { println!("{}", i); i += 1; }',
 10, 3, now()),

-- 12. basics
(gen_random_uuid(),
 'Constants', 'Constantes',
 'Define a constant MAX_SCORE with value 100 and print it.',
 'Define una constante MAX_SCORE con valor 100 e imprímela.',
 'rust', 1, 'basics',
 'fn main() {\n    // your code\n}',
 '100',
 3,
 'Use const instead of let and provide the type explicitly.', 'Usa const en lugar de let y proporciona el tipo explícitamente.',
 'Constants must be named in SCREAMING_SNAKE_CASE by convention.', 'Las constantes deben nombrarse en SCREAMING_SNAKE_CASE por convención.',
 'const MAX_SCORE: i32 = 100;\nprintln!("{}", MAX_SCORE);', 'const MAX_SCORE: i32 = 100;\nprintln!("{}", MAX_SCORE);',
 10, 3, now()),

-- ============================================================
-- DIFFICULTY 2 — 12 exercises (points: 20, penalty: 3)
-- ============================================================

-- 13. ownership
(gen_random_uuid(),
 'Borrowing', 'Préstamo (Borrowing)',
 'Create a String, pass a reference to a function that prints its length, then print the String again.',
 'Crea un String, pasa una referencia a una función que imprime su longitud, luego imprime el String de nuevo.',
 'rust', 2, 'ownership',
 'fn main() {\n    // your code\n}',
 '5\nhello',
 3,
 'Pass &s to the function to borrow without moving ownership.', 'Pasa &s a la función para prestar sin mover la propiedad.',
 'The function signature should accept &String or &str.', 'La firma de la función debe aceptar &String o &str.',
 'fn print_len(s: &String) { println!("{}", s.len()); }', 'fn print_len(s: &String) { println!("{}", s.len()); }',
 20, 3, now()),

-- 14. structs
(gen_random_uuid(),
 'Define a Struct', 'Definir una Estructura',
 'Define a struct Point with fields x and y (both f64). Create an instance with x=3.0, y=4.0 and print both fields.',
 'Define una estructura Point con campos x e y (ambos f64). Crea una instancia con x=3.0, y=4.0 e imprime ambos campos.',
 'rust', 2, 'structs',
 'fn main() {\n    // your code\n}',
 '3\n4',
 3,
 'Use the struct keyword to define a named data type.', 'Usa la palabra clave struct para definir un tipo de dato nombrado.',
 'Access fields with dot notation: p.x and p.y.', 'Accede a los campos con notación de punto: p.x y p.y.',
 'struct Point { x: f64, y: f64 }\nlet p = Point { x: 3.0, y: 4.0 };', 'struct Point { x: f64, y: f64 }\nlet p = Point { x: 3.0, y: 4.0 };',
 20, 3, now()),

-- 15. enums
(gen_random_uuid(),
 'Basic Enum', 'Enumeración Básica',
 'Define an enum Direction with variants North, South, East, West. Match on Direction::North and print "Going North".',
 'Define un enum Direction con variantes North, South, East, West. Usa match en Direction::North e imprime "Going North".',
 'rust', 2, 'enums',
 'fn main() {\n    // your code\n}',
 'Going North',
 3,
 'Use the enum keyword to define the type with its variants.', 'Usa la palabra clave enum para definir el tipo con sus variantes.',
 'Use a match expression to handle each variant.', 'Usa una expresión match para manejar cada variante.',
 'match dir { Direction::North => println!("Going North"), _ => {} }', 'match dir { Direction::North => println!("Going North"), _ => {} }',
 20, 3, now()),

-- 16. option
(gen_random_uuid(),
 'Option Type', 'Tipo Option',
 'Write a function find_first_even(nums: &[i32]) -> Option<i32> that returns the first even number. Call it with [1,3,4,7] and print the value inside Some.',
 'Escribe una función find_first_even(nums: &[i32]) -> Option<i32> que retorne el primer número par. Llámala con [1,3,4,7] e imprime el valor dentro de Some.',
 'rust', 2, 'option',
 'fn main() {\n    // your code\n}',
 '4',
 3,
 'Iterate with .iter() and use .find() or a manual loop.', 'Itera con .iter() y usa .find() o un bucle manual.',
 'Return Some(n) when found and None at the end.', 'Retorna Some(n) cuando lo encuentres y None al final.',
 'if let Some(n) = find_first_even(&[1,3,4,7]) { println!("{}", n); }', 'if let Some(n) = find_first_even(&[1,3,4,7]) { println!("{}", n); }',
 20, 3, now()),

-- 17. vectors
(gen_random_uuid(),
 'Vector Operations', 'Operaciones con Vectores',
 'Create a Vec<i32>, push values 1 through 5, then print the sum.',
 'Crea un Vec<i32>, agrega los valores del 1 al 5, luego imprime la suma.',
 'rust', 2, 'vectors',
 'fn main() {\n    // your code\n}',
 '15',
 3,
 'Use Vec::new() or vec![] to create a vector.', 'Usa Vec::new() o vec![] para crear un vector.',
 'Use .push() to add elements and .iter().sum() to sum them.', 'Usa .push() para agregar elementos e .iter().sum() para sumarlos.',
 'let sum: i32 = v.iter().sum();\nprintln!("{}", sum);', 'let sum: i32 = v.iter().sum();\nprintln!("{}", sum);',
 20, 3, now()),

-- 18. pattern-matching
(gen_random_uuid(),
 'Match with Guards', 'Match con Guardias',
 'Match an integer n = 15: print "fizzbuzz" if divisible by both 3 and 5, "fizz" if by 3, "buzz" if by 5.',
 'Haz match en un entero n = 15: imprime "fizzbuzz" si es divisible por 3 y 5, "fizz" si por 3, "buzz" si por 5.',
 'rust', 2, 'pattern-matching',
 'fn main() {\n    // your code\n}',
 'fizzbuzz',
 3,
 'Use match with guard conditions: n if n % 3 == 0 && n % 5 == 0.', 'Usa match con condiciones guardia: n if n % 3 == 0 && n % 5 == 0.',
 'Order matters — check divisible by both before checking individually.', 'El orden importa — verifica divisible por ambos antes que individualmente.',
 'match n { n if n%15==0 => println!("fizzbuzz"), n if n%3==0 => println!("fizz"), _ => println!("buzz") }', 'match n { n if n%15==0 => println!("fizzbuzz"), n if n%3==0 => println!("fizz"), _ => println!("buzz") }',
 20, 3, now()),

-- 19. closures
(gen_random_uuid(),
 'Basic Closure', 'Closure Básico',
 'Define a closure that doubles an integer. Apply it to 7 and print the result.',
 'Define un closure que duplique un entero. Aplícalo a 7 e imprime el resultado.',
 'rust', 2, 'closures',
 'fn main() {\n    // your code\n}',
 '14',
 3,
 'Closures use |params| { body } syntax.', 'Los closures usan la sintaxis |params| { body }.',
 'Let the compiler infer the types of the closure parameters.', 'Deja que el compilador infiera los tipos de los parámetros del closure.',
 'let double = |x| x * 2;\nprintln!("{}", double(7));', 'let double = |x| x * 2;\nprintln!("{}", double(7));',
 20, 3, now()),

-- 20. iterators
(gen_random_uuid(),
 'Iterator Map and Collect', 'Iterator Map y Collect',
 'Given [1, 2, 3, 4, 5], use .iter().map() to create a new vector with each value doubled, then print it.',
 'Dado [1, 2, 3, 4, 5], usa .iter().map() para crear un nuevo vector con cada valor duplicado, luego imprímelo.',
 'rust', 2, 'iterators',
 'fn main() {\n    // your code\n}',
 '[2, 4, 6, 8, 10]',
 3,
 'Chain .map(|x| x * 2) after .iter().', 'Encadena .map(|x| x * 2) después de .iter().',
 'Use .collect::<Vec<i32>>() or annotate the result type.', 'Usa .collect::<Vec<i32>>() o anota el tipo del resultado.',
 'let doubled: Vec<i32> = nums.iter().map(|x| x * 2).collect();\nprintln!("{:?}", doubled);', 'let doubled: Vec<i32> = nums.iter().map(|x| x * 2).collect();\nprintln!("{:?}", doubled);',
 20, 3, now()),

-- 21. impl
(gen_random_uuid(),
 'Struct Method', 'Método de Estructura',
 'Add an impl block to a struct Rectangle (width, height: f64) with a method area() -> f64. Print the area of a 5.0 x 3.0 rectangle.',
 'Agrega un bloque impl a una estructura Rectangle (width, height: f64) con un método area() -> f64. Imprime el área de un rectángulo de 5.0 x 3.0.',
 'rust', 2, 'impl',
 'fn main() {\n    // your code\n}',
 '15',
 3,
 'Use impl Rectangle { fn area(&self) -> f64 { ... } }.', 'Usa impl Rectangle { fn area(&self) -> f64 { ... } }.',
 '&self gives read-only access to the struct fields.', '&self otorga acceso de solo lectura a los campos de la estructura.',
 'self.width * self.height', 'self.width * self.height',
 20, 3, now()),

-- 22. strings
(gen_random_uuid(),
 'String Slice vs String', 'String Slice vs String',
 'Write a function that accepts &str and returns the number of characters. Call it with "Rustacean" and print the result.',
 'Escribe una función que acepte &str y retorne el número de caracteres. Llámala con "Rustacean" e imprime el resultado.',
 'rust', 2, 'strings',
 'fn main() {\n    // your code\n}',
 '9',
 3,
 'A string literal in Rust is a &str automatically.', 'Un literal de cadena en Rust es un &str automáticamente.',
 'Use .chars().count() for character count (handles Unicode).', 'Usa .chars().count() para contar caracteres (maneja Unicode).',
 'fn char_count(s: &str) -> usize { s.chars().count() }', 'fn char_count(s: &str) -> usize { s.chars().count() }',
 20, 3, now()),

-- 23. iterators
(gen_random_uuid(),
 'Iterator Filter', 'Iterator Filter',
 'Given [1, 2, 3, 4, 5, 6], use .iter().filter() to collect only even numbers and print the result.',
 'Dado [1, 2, 3, 4, 5, 6], usa .iter().filter() para recopilar solo números pares e imprime el resultado.',
 'rust', 2, 'iterators',
 'fn main() {\n    // your code\n}',
 '[2, 4, 6]',
 3,
 'Use .filter(|x| x % 2 == 0) to keep even numbers.', 'Usa .filter(|x| x % 2 == 0) para conservar los números pares.',
 'Note: .iter() yields references, so the closure receives &&i32.', 'Nota: .iter() produce referencias, por lo que el closure recibe &&i32.',
 'let evens: Vec<&i32> = nums.iter().filter(|x| *x % 2 == 0).collect();', 'let evens: Vec<&i32> = nums.iter().filter(|x| *x % 2 == 0).collect();',
 20, 3, now()),

-- 24. pattern-matching
(gen_random_uuid(),
 'Destructuring Tuples', 'Desestructurar Tuplas',
 'Destructure the tuple (10, 20) into variables a and b using let, then print their sum.',
 'Desestructura la tupla (10, 20) en variables a y b con let, luego imprime su suma.',
 'rust', 2, 'pattern-matching',
 'fn main() {\n    // your code\n}',
 '30',
 3,
 'let (a, b) = tuple; binds both fields at once.', 'let (a, b) = tuple; enlaza ambos campos a la vez.',
 'Declare the tuple first or destructure inline.', 'Declara la tupla primero o desestructura en línea.',
 'let (a, b) = (10, 20);\nprintln!("{}", a + b);', 'let (a, b) = (10, 20);\nprintln!("{}", a + b);',
 20, 3, now()),

-- ============================================================
-- DIFFICULTY 3 — 13 exercises (points: 30, penalty: 5)
-- ============================================================

-- 25. result
(gen_random_uuid(),
 'Result and Error Handling', 'Result y Manejo de Errores',
 'Write a function divide(a: f64, b: f64) -> Result<f64, String> that returns an error if b is 0. Call divide(10.0, 2.0) and print the Ok value.',
 'Escribe una función divide(a: f64, b: f64) -> Result<f64, String> que retorne error si b es 0. Llama a divide(10.0, 2.0) e imprime el valor Ok.',
 'rust', 3, 'result',
 'fn main() {\n    // your code\n}',
 '5',
 3,
 'Return Err(String::from("division by zero")) when b == 0.0.', 'Retorna Err(String::from("division by zero")) cuando b == 0.0.',
 'Return Ok(a / b) for the happy path.', 'Retorna Ok(a / b) para el caso exitoso.',
 'if let Ok(v) = divide(10.0, 2.0) { println!("{}", v); }', 'if let Ok(v) = divide(10.0, 2.0) { println!("{}", v); }',
 30, 5, now()),

-- 26. traits
(gen_random_uuid(),
 'Implement a Trait', 'Implementar un Trait',
 'Define a trait Greet with method greet(&self) -> String. Implement it for a struct Person with a name field. Print the greeting for Person { name: "Alice" }.',
 'Define un trait Greet con el método greet(&self) -> String. Impleméntalo para una estructura Person con campo name. Imprime el saludo para Person { name: "Alice" }.',
 'rust', 3, 'traits',
 'fn main() {\n    // your code\n}',
 'Hello, Alice!',
 3,
 'Define the trait with trait Greet { fn greet(&self) -> String; }.', 'Define el trait con trait Greet { fn greet(&self) -> String; }.',
 'Use impl Greet for Person { ... } to provide the implementation.', 'Usa impl Greet for Person { ... } para proveer la implementación.',
 'format!("Hello, {}!", self.name)', 'format!("Hello, {}!", self.name)',
 30, 5, now()),

-- 27. lifetimes
(gen_random_uuid(),
 'Lifetime Annotation', 'Anotación de Tiempo de Vida',
 'Write a function longest<''a>(x: &''a str, y: &''a str) -> &''a str that returns the longer string. Call with "rust" and "language" and print the result.',
 'Escribe una función longest<''a>(x: &''a str, y: &''a str) -> &''a str que retorne la cadena más larga. Llámala con "rust" y "language" e imprime el resultado.',
 'rust', 3, 'lifetimes',
 'fn main() {\n    // your code\n}',
 'language',
 3,
 'Lifetime parameters start with a single quote: ''a.', 'Los parámetros de tiempo de vida comienzan con comilla simple: ''a.',
 'The function body: if x.len() > y.len() { x } else { y }.', 'El cuerpo de la función: if x.len() > y.len() { x } else { y }.',
 'println!("{}", longest("rust", "language"));', 'println!("{}", longest("rust", "language"));',
 30, 5, now()),

-- 28. enums
(gen_random_uuid(),
 'Enum with Data', 'Enum con Datos',
 'Define an enum Shape with variants Circle(f64) and Rectangle(f64, f64). Write a function area(s: &Shape) -> f64. Print the area of Circle(5.0) (use 3.14 for pi, rounded to 2 decimal places).',
 'Define un enum Shape con variantes Circle(f64) y Rectangle(f64, f64). Escribe una función area(s: &Shape) -> f64. Imprime el área de Circle(5.0) (usa 3.14 para pi, redondeado a 2 decimales).',
 'rust', 3, 'enums',
 'fn main() {\n    // your code\n}',
 '78.50',
 3,
 'Enum variants can hold data: Circle(f64) stores the radius.', 'Las variantes del enum pueden guardar datos: Circle(f64) almacena el radio.',
 'Match on Shape::Circle(r) and Shape::Rectangle(w, h).', 'Haz match en Shape::Circle(r) y Shape::Rectangle(w, h).',
 'println!("{:.2}", area(&Shape::Circle(5.0)));', 'println!("{:.2}", area(&Shape::Circle(5.0)));',
 30, 5, now()),

-- 29. closures
(gen_random_uuid(),
 'Closure Capturing Environment', 'Closure Capturando el Entorno',
 'Define a multiplier value 3. Use a closure that captures it to multiply each element of [1, 2, 3, 4, 5]. Print the resulting vector.',
 'Define un valor multiplicador 3. Usa un closure que lo capture para multiplicar cada elemento de [1, 2, 3, 4, 5]. Imprime el vector resultante.',
 'rust', 3, 'closures',
 'fn main() {\n    // your code\n}',
 '[3, 6, 9, 12, 15]',
 3,
 'Closures can capture variables from the enclosing scope.', 'Los closures pueden capturar variables del ámbito envolvente.',
 'Use .iter().map(|x| x * multiplier).collect().', 'Usa .iter().map(|x| x * multiplier).collect().',
 'let result: Vec<i32> = nums.iter().map(|x| x * multiplier).collect();', 'let result: Vec<i32> = nums.iter().map(|x| x * multiplier).collect();',
 30, 5, now()),

-- 30. pattern-matching
(gen_random_uuid(),
 'Destructuring Structs', 'Desestructurar Estructuras',
 'Define a struct Point { x: i32, y: i32 }. Destructure an instance Point { x: 10, y: 20 } using let and print both fields.',
 'Define una estructura Point { x: i32, y: i32 }. Desestructura una instancia Point { x: 10, y: 20 } usando let e imprime ambos campos.',
 'rust', 3, 'pattern-matching',
 'fn main() {\n    // your code\n}',
 '10\n20',
 3,
 'Use let Point { x, y } = p; to destructure a struct.', 'Usa let Point { x, y } = p; para desestructurar una estructura.',
 'The field names become local variable names automatically.', 'Los nombres de campos se convierten en nombres de variables locales automáticamente.',
 'let Point { x, y } = p;\nprintln!("{}\n{}", x, y);', 'let Point { x, y } = p;\nprintln!("{}\n{}", x, y);',
 30, 5, now()),

-- 31. iterators
(gen_random_uuid(),
 'Iterator Chaining', 'Encadenamiento de Iterators',
 'Given [1, 2, 3, 4, 5, 6, 7, 8], filter even numbers, double them, and print their sum.',
 'Dado [1, 2, 3, 4, 5, 6, 7, 8], filtra los números pares, duplícalos e imprime su suma.',
 'rust', 3, 'iterators',
 'fn main() {\n    // your code\n}',
 '60',
 3,
 'Chain .filter() then .map() on the iterator.', 'Encadena .filter() luego .map() en el iterador.',
 'Collect with .sum::<i32>() instead of .collect().', 'Recoge con .sum::<i32>() en lugar de .collect().',
 'let s: i32 = nums.iter().filter(|x| *x%2==0).map(|x| x*2).sum();', 'let s: i32 = nums.iter().filter(|x| *x%2==0).map(|x| x*2).sum();',
 30, 5, now()),

-- 32. result
(gen_random_uuid(),
 'Question Mark Operator', 'Operador de Signo de Interrogación',
 'Write a function parse_and_double(s: &str) -> Result<i32, std::num::ParseIntError> that parses s as i32 and doubles it using ?. Call with "21" and print the result.',
 'Escribe una función parse_and_double(s: &str) -> Result<i32, std::num::ParseIntError> que parsee s como i32 y lo duplique usando ?. Llámala con "21" e imprime el resultado.',
 'rust', 3, 'result',
 'fn main() {\n    // your code\n}',
 '42',
 3,
 'The ? operator returns early with Err if the result is Err.', 'El operador ? retorna anticipadamente con Err si el resultado es Err.',
 'Use s.parse::<i32>()? to parse and propagate errors.', 'Usa s.parse::<i32>()? para parsear y propagar errores.',
 'let n = s.parse::<i32>()?;\nOk(n * 2)', 'let n = s.parse::<i32>()?;\nOk(n * 2)',
 30, 5, now()),

-- 33. impl
(gen_random_uuid(),
 'Constructor Pattern', 'Patrón Constructor',
 'Add a new() associated function to a struct Circle (radius: f64) that returns a Circle. Create Circle::new(3.0) and print its radius.',
 'Agrega una función asociada new() a una estructura Circle (radius: f64) que retorne un Circle. Crea Circle::new(3.0) e imprime su radio.',
 'rust', 3, 'impl',
 'fn main() {\n    // your code\n}',
 '3',
 3,
 'Associated functions use Self as the return type and have no &self parameter.', 'Las funciones asociadas usan Self como tipo de retorno y no tienen parámetro &self.',
 'fn new(radius: f64) -> Self { Circle { radius } }', 'fn new(radius: f64) -> Self { Circle { radius } }',
 'println!("{}", Circle::new(3.0).radius);', 'println!("{}", Circle::new(3.0).radius);',
 30, 5, now()),

-- 34. option
(gen_random_uuid(),
 'Option Chaining with map', 'Encadenamiento de Option con map',
 'Given Some(5_i32), use .map() to square the value. Print the resulting Option using {:?}.',
 'Dado Some(5_i32), usa .map() para elevar al cuadrado el valor. Imprime el Option resultante usando {:?}.',
 'rust', 3, 'option',
 'fn main() {\n    // your code\n}',
 'Some(25)',
 3,
 '.map() on Option applies a function to the inner value if Some.', '.map() en Option aplica una función al valor interior si es Some.',
 'Use |x| x * x as the closure.', 'Usa |x| x * x como closure.',
 'let result = Some(5_i32).map(|x| x * x);\nprintln!("{:?}", result);', 'let result = Some(5_i32).map(|x| x * x);\nprintln!("{:?}", result);',
 30, 5, now()),

-- 35. macros
(gen_random_uuid(),
 'Vec Macro', 'Macro vec!',
 'Use the vec! macro to create a Vec<i32> with values [10, 20, 30]. Print the third element.',
 'Usa la macro vec! para crear un Vec<i32> con valores [10, 20, 30]. Imprime el tercer elemento.',
 'rust', 3, 'macros',
 'fn main() {\n    // your code\n}',
 '30',
 3,
 'vec![10, 20, 30] creates a heap-allocated vector.', 'vec![10, 20, 30] crea un vector en el heap.',
 'Access elements with zero-based indexing: v[2].', 'Accede a los elementos con índice base cero: v[2].',
 'let v = vec![10, 20, 30];\nprintln!("{}", v[2]);', 'let v = vec![10, 20, 30];\nprintln!("{}", v[2]);',
 30, 5, now()),

-- 36. strings
(gen_random_uuid(),
 'String Methods', 'Métodos de String',
 'Given the string "  hello world  ", trim whitespace, convert to uppercase, and print it.',
 'Dado el string "  hello world  ", elimina los espacios, conviértelo a mayúsculas e imprímelo.',
 'rust', 3, 'strings',
 'fn main() {\n    // your code\n}',
 'HELLO WORLD',
 3,
 'Use .trim() to remove leading and trailing whitespace.', 'Usa .trim() para eliminar espacios iniciales y finales.',
 'Chain .to_uppercase() after .trim().', 'Encadena .to_uppercase() después de .trim().',
 'println!("{}", s.trim().to_uppercase());', 'println!("{}", s.trim().to_uppercase());',
 30, 5, now()),

-- 37. control-flow
(gen_random_uuid(),
 'Loop with Break Value', 'Loop con Valor de Break',
 'Use a loop that counts from 1 upward and breaks when the count reaches 5, returning the count. Print the returned value.',
 'Usa un loop que cuente desde 1 hacia arriba y se rompa cuando el conteo llegue a 5, retornando el conteo. Imprime el valor retornado.',
 'rust', 3, 'control-flow',
 'fn main() {\n    // your code\n}',
 '5',
 3,
 'In Rust, loop can return a value via break expression.', 'En Rust, loop puede retornar un valor mediante la expresión break.',
 'Use break count; inside the loop to return the value.', 'Usa break count; dentro del loop para retornar el valor.',
 'let result = loop { if count == 5 { break count; } count += 1; };', 'let result = loop { if count == 5 { break count; } count += 1; };',
 30, 5, now()),

-- ============================================================
-- DIFFICULTY 4 — 8 exercises (points: 50, penalty: 10)
-- ============================================================

-- 38. lifetimes
(gen_random_uuid(),
 'Struct with Lifetime', 'Estructura con Tiempo de Vida',
 'Define a struct Important<''a> that holds a &''a str field part. Implement a method announce(&self) that prints "Attention: " followed by the part. Create an instance and call it.',
 'Define una estructura Important<''a> que contenga un campo &''a str llamado part. Implementa un método announce(&self) que imprima "Attention: " seguido de part. Crea una instancia y llámalo.',
 'rust', 4, 'lifetimes',
 'fn main() {\n    // your code\n}',
 'Attention: read this',
 3,
 'The struct borrows a string slice, so it needs a lifetime parameter.', 'La estructura toma prestado un slice de cadena, por eso necesita un parámetro de tiempo de vida.',
 'impl<''a> Important<''a> { fn announce(&self) { ... } }', 'impl<''a> Important<''a> { fn announce(&self) { ... } }',
 'println!("Attention: {}", self.part);', 'println!("Attention: {}", self.part);',
 50, 10, now()),

-- 39. traits
(gen_random_uuid(),
 'Display Trait', 'Trait Display',
 'Implement std::fmt::Display for a struct Color { r: u8, g: u8, b: u8 } to print "rgb(R, G, B)". Print Color { r:255, g:128, b:0 }.',
 'Implementa std::fmt::Display para una estructura Color { r: u8, g: u8, b: u8 } para imprimir "rgb(R, G, B)". Imprime Color { r:255, g:128, b:0 }.',
 'rust', 4, 'traits',
 'fn main() {\n    // your code\n}',
 'rgb(255, 128, 0)',
 3,
 'Import std::fmt and implement fmt::Display for Color.', 'Importa std::fmt e implementa fmt::Display para Color.',
 'The trait method signature is fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result.', 'La firma del método del trait es fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result.',
 'write!(f, "rgb({}, {}, {})", self.r, self.g, self.b)', 'write!(f, "rgb({}, {}, {})", self.r, self.g, self.b)',
 50, 10, now()),

-- 40. ownership
(gen_random_uuid(),
 'Mutable Reference', 'Referencia Mutable',
 'Write a function double_value(n: &mut i32) that doubles the value in place. Call it with a mutable variable holding 7 and print the result.',
 'Escribe una función double_value(n: &mut i32) que duplique el valor en su lugar. Llámala con una variable mutable que contenga 7 e imprime el resultado.',
 'rust', 4, 'ownership',
 'fn main() {\n    // your code\n}',
 '14',
 3,
 'Use &mut to create a mutable reference.', 'Usa &mut para crear una referencia mutable.',
 'Inside the function, dereference with *n to modify the value.', 'Dentro de la función, desreferencia con *n para modificar el valor.',
 '*n *= 2;\ndouble_value(&mut x);\nprintln!("{}", x);', '*n *= 2;\ndouble_value(&mut x);\nprintln!("{}", x);',
 50, 10, now()),

-- 41. concurrency
(gen_random_uuid(),
 'Spawn a Thread', 'Crear un Hilo',
 'Spawn a thread that prints "hello from thread". Join the thread in main before exiting.',
 'Crea un hilo que imprima "hello from thread". Une el hilo en main antes de salir.',
 'rust', 4, 'concurrency',
 'fn main() {\n    // your code\n}',
 'hello from thread',
 3,
 'Use std::thread::spawn(|| { ... }) to create a new thread.', 'Usa std::thread::spawn(|| { ... }) para crear un nuevo hilo.',
 'spawn returns a JoinHandle — call .join().unwrap() on it.', 'spawn retorna un JoinHandle — llama a .join().unwrap() sobre él.',
 'let h = std::thread::spawn(|| println!("hello from thread"));\nh.join().unwrap();', 'let h = std::thread::spawn(|| println!("hello from thread"));\nh.join().unwrap();',
 50, 10, now()),

-- 42. iterators
(gen_random_uuid(),
 'Custom Iterator', 'Iterator Personalizado',
 'Implement the Iterator trait for a struct Counter that yields values 1 through 5. Collect the values into a Vec and print it.',
 'Implementa el trait Iterator para una estructura Counter que produzca valores del 1 al 5. Recopila los valores en un Vec e imprímelo.',
 'rust', 4, 'iterators',
 'fn main() {\n    // your code\n}',
 '[1, 2, 3, 4, 5]',
 3,
 'impl Iterator for Counter requires defining type Item and fn next(&mut self) -> Option<Self::Item>.', 'impl Iterator for Counter requiere definir type Item y fn next(&mut self) -> Option<Self::Item>.',
 'Keep a count field in the struct; increment and return Some(count) until 5, then None.', 'Mantén un campo count en la estructura; incrementa y retorna Some(count) hasta 5, luego None.',
 'let v: Vec<u32> = Counter { count: 0 }.collect();\nprintln!("{:?}", v);', 'let v: Vec<u32> = Counter { count: 0 }.collect();\nprintln!("{:?}", v);',
 50, 10, now()),

-- 43. traits
(gen_random_uuid(),
 'Generic Function with Trait Bound', 'Función Genérica con Límite de Trait',
 'Write a generic function largest<T: PartialOrd>(list: &[T]) -> &T that returns the largest element. Call it with &[34, 50, 25, 100, 65] and print the result.',
 'Escribe una función genérica largest<T: PartialOrd>(list: &[T]) -> &T que retorne el elemento más grande. Llámala con &[34, 50, 25, 100, 65] e imprime el resultado.',
 'rust', 4, 'traits',
 'fn main() {\n    // your code\n}',
 '100',
 3,
 'The T: PartialOrd bound allows using > to compare elements.', 'El límite T: PartialOrd permite usar > para comparar elementos.',
 'Start with &list[0] as the candidate and iterate through the rest.', 'Comienza con &list[0] como candidato e itera por el resto.',
 'if item > largest { largest = item; }', 'if item > largest { largest = item; }',
 50, 10, now()),

-- 44. closures
(gen_random_uuid(),
 'Higher-Order Functions', 'Funciones de Orden Superior',
 'Write a function apply_twice<F: Fn(i32) -> i32>(f: F, x: i32) -> i32. Use it with a closure that adds 3 to double the effect on 5. Print the result.',
 'Escribe una función apply_twice<F: Fn(i32) -> i32>(f: F, x: i32) -> i32. Úsala con un closure que sume 3 para duplicar el efecto sobre 5. Imprime el resultado.',
 'rust', 4, 'closures',
 'fn main() {\n    // your code\n}',
 '11',
 3,
 'apply_twice should call f(f(x)) to apply the function twice.', 'apply_twice debe llamar f(f(x)) para aplicar la función dos veces.',
 'The Fn(i32) -> i32 trait bound means the closure takes and returns i32.', 'El límite de trait Fn(i32) -> i32 significa que el closure toma y retorna i32.',
 'fn apply_twice<F: Fn(i32)->i32>(f: F, x: i32) -> i32 { f(f(x)) }', 'fn apply_twice<F: Fn(i32)->i32>(f: F, x: i32) -> i32 { f(f(x)) }',
 50, 10, now()),

-- 45. option
(gen_random_uuid(),
 'Option and_then Chaining', 'Encadenamiento and_then de Option',
 'Parse "42" into an i32 using .parse::<i32>().ok(), then use .and_then() to return None if the number is negative, or Some(n*2) otherwise. Print the result with {:?}.',
 'Parsea "42" en i32 usando .parse::<i32>().ok(), luego usa .and_then() para retornar None si el número es negativo o Some(n*2) si no. Imprime el resultado con {:?}.',
 'rust', 4, 'option',
 'fn main() {\n    // your code\n}',
 'Some(84)',
 3,
 '.ok() converts Result to Option, discarding the error.', '.ok() convierte Result a Option, descartando el error.',
 '.and_then() lets you chain fallible operations on Option.', '.and_then() permite encadenar operaciones falibles en Option.',
 '"42".parse::<i32>().ok().and_then(|n| if n < 0 { None } else { Some(n*2) })', '"42".parse::<i32>().ok().and_then(|n| if n < 0 { None } else { Some(n*2) })',
 50, 10, now()),

-- ============================================================
-- DIFFICULTY 5 — 5 exercises (points: 100, penalty: 10)
-- ============================================================

-- 46. concurrency
(gen_random_uuid(),
 'Channels for Communication', 'Canales para Comunicación',
 'Use std::sync::mpsc to send the value 42 from a spawned thread to the main thread. Print the received value.',
 'Usa std::sync::mpsc para enviar el valor 42 desde un hilo secundario al hilo principal. Imprime el valor recibido.',
 'rust', 5, 'concurrency',
 'fn main() {\n    // your code\n}',
 '42',
 3,
 'Use mpsc::channel() to create a (tx, rx) pair.', 'Usa mpsc::channel() para crear un par (tx, rx).',
 'Move tx into the spawned thread with a move closure.', 'Mueve tx al hilo creado con un closure move.',
 'tx.send(42).unwrap();\nprintln!("{}", rx.recv().unwrap());', 'tx.send(42).unwrap();\nprintln!("{}", rx.recv().unwrap());',
 100, 10, now()),

-- 47. lifetimes
(gen_random_uuid(),
 'Multiple Lifetime Parameters', 'Múltiples Parámetros de Tiempo de Vida',
 'Write a function first_word<''a>(sentence: &''a str) -> &''a str that returns the first word (before any space). Call with "hello world" and print.',
 'Escribe una función first_word<''a>(sentence: &''a str) -> &''a str que retorne la primera palabra (antes de cualquier espacio). Llámala con "hello world" e imprime.',
 'rust', 5, 'lifetimes',
 'fn main() {\n    // your code\n}',
 'hello',
 3,
 'Use .find('' '') to locate the first space character.', 'Usa .find('' '') para localizar el primer espacio.',
 'Return &sentence[..i] where i is the space index, or the whole string if no space.', 'Retorna &sentence[..i] donde i es el índice del espacio, o el string completo si no hay espacio.',
 'let i = sentence.find('' '').unwrap_or(sentence.len());\n&sentence[..i]', 'let i = sentence.find('' '').unwrap_or(sentence.len());\n&sentence[..i]',
 100, 10, now()),

-- 48. concurrency
(gen_random_uuid(),
 'Arc and Mutex', 'Arc y Mutex',
 'Share a counter (initial 0) between 5 threads using Arc<Mutex<i32>>. Each thread increments it by 1. Print the final counter value.',
 'Comparte un contador (inicial 0) entre 5 hilos usando Arc<Mutex<i32>>. Cada hilo lo incrementa en 1. Imprime el valor final del contador.',
 'rust', 5, 'concurrency',
 'fn main() {\n    // your code\n}',
 '5',
 3,
 'Arc (Atomic Reference Counted) allows shared ownership across threads.', 'Arc (Recuento de Referencias Atómico) permite propiedad compartida entre hilos.',
 'Clone the Arc for each thread and lock the Mutex inside the thread.', 'Clona el Arc para cada hilo y bloquea el Mutex dentro del hilo.',
 'let c = Arc::clone(&counter);\nlet mut num = c.lock().unwrap();\n*num += 1;', 'let c = Arc::clone(&counter);\nlet mut num = c.lock().unwrap();\n*num += 1;',
 100, 10, now()),

-- 49. traits
(gen_random_uuid(),
 'Dynamic Dispatch with dyn Trait', 'Despacho Dinámico con dyn Trait',
 'Define a trait Animal with method sound(&self) -> &str. Implement it for Dog and Cat. Store both in a Vec<Box<dyn Animal>> and print each sound.',
 'Define un trait Animal con método sound(&self) -> &str. Impleméntalo para Dog y Cat. Guarda ambos en un Vec<Box<dyn Animal>> e imprime cada sonido.',
 'rust', 5, 'traits',
 'fn main() {\n    // your code\n}',
 'woof\nmeow',
 3,
 'Box<dyn Trait> allows storing different types implementing the same trait.', 'Box<dyn Trait> permite guardar diferentes tipos que implementan el mismo trait.',
 'Use Box::new(Dog{}) and Box::new(Cat{}) when building the vector.', 'Usa Box::new(Dog{}) y Box::new(Cat{}) al construir el vector.',
 'for animal in &animals { println!("{}", animal.sound()); }', 'for animal in &animals { println!("{}", animal.sound()); }',
 100, 10, now()),

-- 50. iterators
(gen_random_uuid(),
 'Custom Iterator Adapter', 'Adaptador de Iterador Personalizado',
 'Implement a Fibonacci iterator struct that yields the first 8 Fibonacci numbers starting with 1, 1. Collect into a Vec and print it.',
 'Implementa una estructura iteradora Fibonacci que produzca los primeros 8 números de Fibonacci empezando con 1, 1. Recoge en un Vec e imprímelo.',
 'rust', 5, 'iterators',
 'fn main() {\n    // your code\n}',
 '[1, 1, 2, 3, 5, 8, 13, 21]',
 3,
 'Store two fields (curr, next) in the struct and swap them each iteration.', 'Guarda dos campos (curr, next) en la estructura e intercámbialos en cada iteración.',
 'In next(), let result = self.curr; then update: self.curr = self.next; self.next = result + self.next;', 'En next(), let result = self.curr; luego actualiza: self.curr = self.next; self.next = result + self.next;',
 'let v: Vec<u64> = Fibonacci { curr:1, next:1 }.take(8).collect();\nprintln!("{:?}", v);', 'let v: Vec<u64> = Fibonacci { curr:1, next:1 }.take(8).collect();\nprintln!("{:?}", v);',
 100, 10, now())

ON CONFLICT DO NOTHING;

COMMIT;
