-- 054_exercises_swift.sql
-- 100 Swift exercises, bilingual EN+ES
-- Distribution: diff1=25, diff2=25, diff3=25, diff4=15, diff5=10
-- Points: 10/20/30/50/100 | Penalty: 3/3/5/10/10
-- Focus: optionals, guard, if let, enums with associated values, protocols,
--        extensions, closures, structs vs classes, generics, error handling,
--        SwiftUI basics, Codable, async/await

BEGIN;

INSERT INTO exercises (
  id, title_en, title_es,
  description_en, description_es,
  language, difficulty, category,
  starter_code, expected_output,
  hint_count,
  hint_1_en, hint_1_es,
  hint_2_en, hint_2_es,
  hint_3_en, hint_3_es,
  points, hints_used_penalty,
  created_at
) VALUES

-- ============================================================
-- DIFFICULTY 1 — 25 exercises (points=10, penalty=3)
-- ============================================================

-- 1. basics
(gen_random_uuid(),
 'Hello Swift', 'Hola Swift',
 'Print "Hello, Swift!" to the console.',
 'Imprime "Hello, Swift!" en la consola.',
 'swift', 1, 'basics',
 'print(___)',
 'Hello, Swift!',
 3,
 'Use the print() function with a string literal.', 'Usa la función print() con un literal de cadena.',
 'String literals in Swift use double quotes.', 'Los literales de cadena en Swift usan comillas dobles.',
 'print("Hello, Swift!")', 'print("Hello, Swift!")',
 10, 3, now()),

-- 2. basics
(gen_random_uuid(),
 'Declare a Constant', 'Declarar una Constante',
 'Declare a constant named language with the value "Swift" and print it.',
 'Declara una constante llamada language con el valor "Swift" e imprímela.',
 'swift', 1, 'basics',
 '___ language = "Swift"\nprint(language)',
 'Swift',
 3,
 'Use the "let" keyword to declare a constant.', 'Usa la palabra clave "let" para declarar una constante.',
 'Constants in Swift cannot be reassigned after declaration.', 'Las constantes en Swift no pueden ser reasignadas después de su declaración.',
 'let language = "Swift"', 'let language = "Swift"',
 10, 3, now()),

-- 3. basics
(gen_random_uuid(),
 'Declare a Variable', 'Declarar una Variable',
 'Declare a variable named score with the value 0, then reassign it to 100 and print it.',
 'Declara una variable llamada score con el valor 0, luego reasígnala a 100 e imprímela.',
 'swift', 1, 'basics',
 '___ score = 0\nscore = 100\nprint(score)',
 '100',
 3,
 'Use the "var" keyword to declare a mutable variable.', 'Usa la palabra clave "var" para declarar una variable mutable.',
 'Variables declared with "var" can be changed; "let" constants cannot.', 'Las variables declaradas con "var" se pueden cambiar; las constantes "let" no.',
 'var score = 0', 'var score = 0',
 10, 3, now()),

-- 4. basics
(gen_random_uuid(),
 'String Interpolation', 'Interpolación de Cadenas',
 'Declare a constant name = "World" and print "Hello, World!" using string interpolation.',
 'Declara una constante name = "World" e imprime "Hello, World!" usando interpolación de cadenas.',
 'swift', 1, 'basics',
 'let name = "World"\nprint("Hello, \\___!")',
 'Hello, World!',
 3,
 'Swift string interpolation uses \\(variableName) syntax inside a string.', 'La interpolación de cadenas en Swift usa la sintaxis \\(nombreVariable) dentro de una cadena.',
 'Place the variable inside \\( ) within the string literal.', 'Coloca la variable dentro de \\( ) dentro del literal de cadena.',
 'print("Hello, \\(name)!")', 'print("Hello, \\(name)!")',
 10, 3, now()),

-- 5. basics
(gen_random_uuid(),
 'Integer Arithmetic', 'Aritmética de Enteros',
 'Declare constants a = 15 and b = 4, then print their remainder using the modulo operator.',
 'Declara constantes a = 15 y b = 4, luego imprime su resto usando el operador módulo.',
 'swift', 1, 'basics',
 'let a = 15\nlet b = 4\nprint(a ___ b)',
 '3',
 3,
 'The modulo operator returns the remainder of a division.', 'El operador módulo devuelve el resto de una división.',
 'In Swift the modulo operator is %.', 'En Swift el operador módulo es %.',
 'print(a % b)', 'print(a % b)',
 10, 3, now()),

-- 6. arrays
(gen_random_uuid(),
 'Create an Array', 'Crear un Array',
 'Declare an array of integers named numbers containing [1, 2, 3, 4, 5] and print its count.',
 'Declara un array de enteros llamado numbers con [1, 2, 3, 4, 5] e imprime su cantidad.',
 'swift', 1, 'arrays',
 'let numbers = [1, 2, 3, 4, 5]\nprint(numbers.___)',
 '5',
 3,
 'Arrays in Swift have a "count" property.', 'Los arrays en Swift tienen una propiedad "count".',
 'Access properties with dot notation: array.count', 'Accede a las propiedades con notación de punto: array.count',
 'print(numbers.count)', 'print(numbers.count)',
 10, 3, now()),

-- 7. arrays
(gen_random_uuid(),
 'Array Append', 'Añadir al Array',
 'Declare a variable array var fruits = ["apple", "banana"], append "cherry", then print the array.',
 'Declara un array variable var fruits = ["apple", "banana"], añade "cherry", luego imprime el array.',
 'swift', 1, 'arrays',
 'var fruits = ["apple", "banana"]\nfruits.___(___)\nprint(fruits)',
 '["apple", "banana", "cherry"]',
 3,
 'Use the append() method to add a single element to the end of an array.', 'Usa el método append() para añadir un elemento al final de un array.',
 'Pass the new element as the argument to append().', 'Pasa el nuevo elemento como argumento a append().',
 'fruits.append("cherry")', 'fruits.append("cherry")',
 10, 3, now()),

-- 8. dictionaries
(gen_random_uuid(),
 'Create a Dictionary', 'Crear un Diccionario',
 'Declare a dictionary var ages = ["Alice": 30, "Bob": 25] and print the value for "Alice".',
 'Declara un diccionario var ages = ["Alice": 30, "Bob": 25] e imprime el valor de "Alice".',
 'swift', 1, 'dictionaries',
 'let ages = ["Alice": 30, "Bob": 25]\nprint(ages[___])',
 'Optional(30)',
 3,
 'Dictionary subscript access with a key returns an Optional value.', 'El acceso mediante subíndice a un diccionario con una clave devuelve un valor Optional.',
 'Use the key as a string inside square brackets.', 'Usa la clave como cadena dentro de corchetes.',
 'print(ages["Alice"])', 'print(ages["Alice"])',
 10, 3, now()),

-- 9. control-flow
(gen_random_uuid(),
 'For-In Loop', 'Bucle For-In',
 'Use a for-in loop to print each number in [1, 2, 3] on its own line.',
 'Usa un bucle for-in para imprimir cada número en [1, 2, 3] en su propia línea.',
 'swift', 1, 'control-flow',
 'for ___ in [1, 2, 3] {\n    print(___)\n}',
 '1\n2\n3',
 3,
 'The loop variable takes each value from the collection in turn.', 'La variable del bucle toma cada valor de la colección por turno.',
 'Use the same variable name inside the loop body.', 'Usa el mismo nombre de variable dentro del cuerpo del bucle.',
 'for num in [1, 2, 3] {\n    print(num)\n}', 'for num in [1, 2, 3] {\n    print(num)\n}',
 10, 3, now()),

-- 10. control-flow
(gen_random_uuid(),
 'While Loop', 'Bucle While',
 'Use a while loop to print numbers 1 through 3 using a counter variable.',
 'Usa un bucle while para imprimir los números del 1 al 3 usando una variable contador.',
 'swift', 1, 'control-flow',
 'var counter = 1\nwhile counter ___ 4 {\n    print(counter)\n    counter += 1\n}',
 '1\n2\n3',
 3,
 'The while condition should keep the loop running while counter is less than 4.', 'La condición while debe mantener el bucle activo mientras counter sea menor que 4.',
 'Use the < operator for the comparison.', 'Usa el operador < para la comparación.',
 'while counter < 4', 'while counter < 4',
 10, 3, now()),

-- 11. functions
(gen_random_uuid(),
 'Basic Function', 'Función Básica',
 'Define a function greet() that prints "Hello from Swift!" and call it.',
 'Define una función greet() que imprima "Hello from Swift!" y llámala.',
 'swift', 1, 'functions',
 '___ greet() {\n    print("Hello from Swift!")\n}\ngreet()',
 'Hello from Swift!',
 3,
 'Use the "func" keyword to define a function.', 'Usa la palabra clave "func" para definir una función.',
 'The function body goes inside curly braces {}.', 'El cuerpo de la función va dentro de llaves {}.',
 'func greet()', 'func greet()',
 10, 3, now()),

-- 12. functions
(gen_random_uuid(),
 'Function with Parameter', 'Función con Parámetro',
 'Define a function square(_ n: Int) -> Int that returns n * n, then print square(7).',
 'Define una función square(_ n: Int) -> Int que devuelva n * n, luego imprime square(7).',
 'swift', 1, 'functions',
 'func square(_ n: Int) -> Int {\n    return ___\n}\nprint(square(7))',
 '49',
 3,
 'The function must return the result of multiplying n by itself.', 'La función debe devolver el resultado de multiplicar n por sí mismo.',
 'Use the * operator for multiplication.', 'Usa el operador * para la multiplicación.',
 'return n * n', 'return n * n',
 10, 3, now()),

-- 13. optionals
(gen_random_uuid(),
 'Optional Declaration', 'Declaración de Optional',
 'Declare an optional String named nickname with no value (nil) and print it.',
 'Declara un String opcional llamado nickname sin valor (nil) e imprímelo.',
 'swift', 1, 'optionals',
 'var nickname: String___ = nil\nprint(nickname)',
 'nil',
 3,
 'Append a ? after the type name to make it optional.', 'Añade ? después del nombre del tipo para hacerlo opcional.',
 'An optional that has no value contains nil.', 'Un opcional sin valor contiene nil.',
 'var nickname: String? = nil', 'var nickname: String? = nil',
 10, 3, now()),

-- 14. optionals
(gen_random_uuid(),
 'Force Unwrap', 'Desenvolvimiento Forzado',
 'Given var city: String? = "Paris", force-unwrap it and print the result.',
 'Dado var city: String? = "Paris", desenvuélvelo forzadamente e imprime el resultado.',
 'swift', 1, 'optionals',
 'var city: String? = "Paris"\nprint(city___)',
 'Paris',
 3,
 'The force-unwrap operator is placed immediately after the variable name.', 'El operador de desenvolvimiento forzado se coloca inmediatamente después del nombre de la variable.',
 'Use ! to force-unwrap an optional (only when you are certain it is not nil).', 'Usa ! para desenvolver forzadamente un opcional (solo cuando estás seguro de que no es nil).',
 'print(city!)', 'print(city!)',
 10, 3, now()),

-- 15. structs
(gen_random_uuid(),
 'Define a Struct', 'Definir una Estructura',
 'Define a struct Point with properties x: Int and y: Int. Create an instance Point(x: 3, y: 4) and print its x property.',
 'Define una estructura Point con propiedades x: Int e y: Int. Crea una instancia Point(x: 3, y: 4) e imprime su propiedad x.',
 'swift', 1, 'structs',
 'struct Point {\n    var x: Int\n    var y: Int\n}\nlet p = Point(x: 3, y: 4)\nprint(p.___)',
 '3',
 3,
 'Access struct properties using dot notation.', 'Accede a las propiedades de una estructura con notación de punto.',
 'The property name is "x".', 'El nombre de la propiedad es "x".',
 'print(p.x)', 'print(p.x)',
 10, 3, now()),

-- 16. structs
(gen_random_uuid(),
 'Struct Method', 'Método de Estructura',
 'Add a method describe() to struct Point that prints "x: 3, y: 4" and call it.',
 'Añade un método describe() a la estructura Point que imprima "x: 3, y: 4" y llámalo.',
 'swift', 1, 'structs',
 'struct Point {\n    var x: Int\n    var y: Int\n    func describe() {\n        print("x: \\(___), y: \\(___)")\n    }\n}\nlet p = Point(x: 3, y: 4)\np.describe()',
 'x: 3, y: 4',
 3,
 'Use string interpolation with \\(propertyName) to embed property values.', 'Usa interpolación de cadenas con \\(nombrePropiedad) para incrustar valores de propiedades.',
 'The properties are named x and y.', 'Las propiedades se llaman x e y.',
 'print("x: \\(x), y: \\(y)")', 'print("x: \\(x), y: \\(y)")',
 10, 3, now()),

-- 17. enums
(gen_random_uuid(),
 'Basic Enum', 'Enum Básico',
 'Define an enum Direction with cases north, south, east, west. Declare a constant dir = Direction.north and print it.',
 'Define un enum Direction con casos north, south, east, west. Declara una constante dir = Direction.north e imprímela.',
 'swift', 1, 'enums',
 'enum Direction {\n    case north, south, east, west\n}\nlet dir = Direction.north\nprint(___)',
 'north',
 3,
 'Printing an enum case without a raw value shows the case name.', 'Imprimir un caso de enum sin valor raw muestra el nombre del caso.',
 'Pass the variable directly to print().', 'Pasa la variable directamente a print().',
 'print(dir)', 'print(dir)',
 10, 3, now()),

-- 18. control-flow
(gen_random_uuid(),
 'Switch on Enum', 'Switch sobre Enum',
 'Using enum Direction, write a switch that prints "Going north" when dir == .north.',
 'Usando el enum Direction, escribe un switch que imprima "Going north" cuando dir == .north.',
 'swift', 1, 'control-flow',
 'enum Direction { case north, south, east, west }\nlet dir = Direction.north\nswitch dir {\n___ .north:\n    print("Going north")\ndefault:\n    print("Other direction")\n}',
 'Going north',
 3,
 'A switch case in Swift uses the "case" keyword.', 'Un caso de switch en Swift usa la palabra clave "case".',
 'Each case is followed by a colon.', 'Cada caso va seguido de dos puntos.',
 'case .north:', 'case .north:',
 10, 3, now()),

-- 19. closures
(gen_random_uuid(),
 'Simple Closure', 'Closure Simple',
 'Declare a closure named double that takes an Int and returns Int (multiplied by 2). Print double(5).',
 'Declara un closure llamado double que tome un Int y devuelva Int (multiplicado por 2). Imprime double(5).',
 'swift', 1, 'closures',
 'let double: (Int) -> Int = { ___ in\n    return ___ * 2\n}\nprint(double(5))',
 '10',
 3,
 'The closure parameter is declared before the "in" keyword.', 'El parámetro del closure se declara antes de la palabra clave "in".',
 'Use the same parameter name on both sides of the expression.', 'Usa el mismo nombre de parámetro en ambos lados de la expresión.',
 'let double: (Int) -> Int = { n in\n    return n * 2\n}', 'let double: (Int) -> Int = { n in\n    return n * 2\n}',
 10, 3, now()),

-- 20. closures
(gen_random_uuid(),
 'Trailing Closure with map', 'Trailing Closure con map',
 'Use map with a trailing closure to double each element in [1, 2, 3] and print the result.',
 'Usa map con un trailing closure para duplicar cada elemento en [1, 2, 3] e imprime el resultado.',
 'swift', 1, 'closures',
 'let doubled = [1, 2, 3].map { ___ in\n    ___ * 2\n}\nprint(doubled)',
 '[2, 4, 6]',
 3,
 'The closure receives each element as its parameter.', 'El closure recibe cada elemento como su parámetro.',
 'Name the parameter anything — use it inside the closure body.', 'Nombra el parámetro como quieras — úsalo dentro del cuerpo del closure.',
 '[1, 2, 3].map { n in\n    n * 2\n}', '[1, 2, 3].map { n in\n    n * 2\n}',
 10, 3, now()),

-- 21. strings
(gen_random_uuid(),
 'String Count', 'Longitud de Cadena',
 'Declare let word = "Swift" and print the number of characters it contains.',
 'Declara let word = "Swift" e imprime el número de caracteres que contiene.',
 'swift', 1, 'strings',
 'let word = "Swift"\nprint(word.___)',
 '5',
 3,
 'Swift strings have a "count" property.', 'Las cadenas Swift tienen una propiedad "count".',
 'Access it with dot notation.', 'Accédela con notación de punto.',
 'print(word.count)', 'print(word.count)',
 10, 3, now()),

-- 22. strings
(gen_random_uuid(),
 'Uppercase String', 'Cadena en Mayúsculas',
 'Declare let msg = "hello" and print it converted to uppercase.',
 'Declara let msg = "hello" e imprímela convertida a mayúsculas.',
 'swift', 1, 'strings',
 'let msg = "hello"\nprint(msg.___)',
 'HELLO',
 3,
 'Swift strings have an uppercased() method.', 'Las cadenas Swift tienen un método uppercased().',
 'Call it with parentheses.', 'Llámalo con paréntesis.',
 'print(msg.uppercased())', 'print(msg.uppercased())',
 10, 3, now()),

-- 23. type-annotations
(gen_random_uuid(),
 'Explicit Type Annotation', 'Anotación de Tipo Explícita',
 'Declare a constant pi of type Double with value 3.14159 and print it.',
 'Declara una constante pi de tipo Double con valor 3.14159 e imprímela.',
 'swift', 1, 'type-annotations',
 'let pi: ___ = 3.14159\nprint(pi)',
 '3.14159',
 3,
 'Use Double for floating-point numbers with double precision.', 'Usa Double para números de coma flotante con doble precisión.',
 'The type annotation goes after the colon following the variable name.', 'La anotación de tipo va después de los dos puntos que siguen al nombre de la variable.',
 'let pi: Double = 3.14159', 'let pi: Double = 3.14159',
 10, 3, now()),

-- 24. tuples
(gen_random_uuid(),
 'Basic Tuple', 'Tupla Básica',
 'Declare a tuple let person = ("Alice", 30) and print the first element.',
 'Declara una tupla let person = ("Alice", 30) e imprime el primer elemento.',
 'swift', 1, 'tuples',
 'let person = ("Alice", 30)\nprint(person.___)',
 'Alice',
 3,
 'Tuple elements are accessed by their zero-based index.', 'Los elementos de una tupla se acceden por su índice base cero.',
 'The first element has index 0.', 'El primer elemento tiene índice 0.',
 'print(person.0)', 'print(person.0)',
 10, 3, now()),

-- 25. ranges
(gen_random_uuid(),
 'Closed Range Loop', 'Bucle con Rango Cerrado',
 'Use a for-in loop with a closed range to print numbers 1 through 5.',
 'Usa un bucle for-in con un rango cerrado para imprimir los números del 1 al 5.',
 'swift', 1, 'ranges',
 'for i in ___...5 {\n    print(i)\n}',
 '1\n2\n3\n4\n5',
 3,
 'A closed range includes both endpoints. The ... operator creates a closed range.', 'Un rango cerrado incluye ambos extremos. El operador ... crea un rango cerrado.',
 'The range should start at 1.', 'El rango debe empezar en 1.',
 'for i in 1...5', 'for i in 1...5',
 10, 3, now()),

-- ============================================================
-- DIFFICULTY 2 — 25 exercises (points=20, penalty=3)
-- ============================================================

-- 26. optionals
(gen_random_uuid(),
 'Optional Binding with if let', 'Enlace de Optional con if let',
 'Given var name: String? = "Swift", use if let to safely unwrap it and print "Hello, Swift!".',
 'Dado var name: String? = "Swift", usa if let para desenvolverlo de forma segura e imprime "Hello, Swift!".',
 'swift', 2, 'optionals',
 'var name: String? = "Swift"\nif ___ unwrapped = name {\n    print("Hello, \\(unwrapped)!")\n}',
 'Hello, Swift!',
 3,
 'if let creates a new non-optional constant inside the if block.', 'if let crea una nueva constante no opcional dentro del bloque if.',
 'The keyword before the new constant name is "let".', 'La palabra clave antes del nuevo nombre de constante es "let".',
 'if let unwrapped = name', 'if let unwrapped = name',
 20, 3, now()),

-- 27. optionals
(gen_random_uuid(),
 'Nil-Coalescing Operator', 'Operador Nil-Coalescing',
 'Given var username: String? = nil, print the username or "Anonymous" if nil using ??.',
 'Dado var username: String? = nil, imprime el username o "Anonymous" si es nil usando ??.',
 'swift', 2, 'optionals',
 'var username: String? = nil\nprint(username ___ "Anonymous")',
 'Anonymous',
 3,
 'The nil-coalescing operator ?? provides a default value when the optional is nil.', 'El operador nil-coalescing ?? provee un valor predeterminado cuando el opcional es nil.',
 'Place ?? between the optional and the default value.', 'Coloca ?? entre el opcional y el valor predeterminado.',
 'print(username ?? "Anonymous")', 'print(username ?? "Anonymous")',
 20, 3, now()),

-- 28. optionals
(gen_random_uuid(),
 'Optional Chaining', 'Encadenamiento de Opcionales',
 'Given var text: String? = "hello", use optional chaining to print the uppercased version or nil.',
 'Dado var text: String? = "hello", usa encadenamiento de opcionales para imprimir la versión en mayúsculas o nil.',
 'swift', 2, 'optionals',
 'var text: String? = "hello"\nprint(text___.uppercased())',
 'Optional("HELLO")',
 3,
 'Optional chaining uses ? after the optional variable before accessing a member.', 'El encadenamiento de opcionales usa ? después de la variable opcional antes de acceder a un miembro.',
 'Place ? between the variable name and the dot.', 'Coloca ? entre el nombre de la variable y el punto.',
 'print(text?.uppercased())', 'print(text?.uppercased())',
 20, 3, now()),

-- 29. guard
(gen_random_uuid(),
 'Guard Let', 'Guard Let',
 'Write a function printLength(_ s: String?) that uses guard let to unwrap s, then prints its character count.',
 'Escribe una función printLength(_ s: String?) que use guard let para desenvolver s, luego imprime su conteo de caracteres.',
 'swift', 2, 'guard',
 'func printLength(_ s: String?) {\n    ___ let value = s else { return }\n    print(value.count)\n}\nprintLength("Swift")',
 '5',
 3,
 'guard let exits the current scope in the else branch when the condition fails.', 'guard let sale del ámbito actual en la rama else cuando la condición falla.',
 'The keyword that starts the guard statement is "guard".', 'La palabra clave que inicia la sentencia guard es "guard".',
 'guard let value = s else { return }', 'guard let value = s else { return }',
 20, 3, now()),

-- 30. guard
(gen_random_uuid(),
 'Guard Condition', 'Condición Guard',
 'Write a function checkAge(_ age: Int) that uses guard to ensure age >= 18, printing "Access granted" or returning early with "Too young".',
 'Escribe una función checkAge(_ age: Int) que use guard para asegurarse de que age >= 18, imprimiendo "Access granted" o retornando antes con "Too young".',
 'swift', 2, 'guard',
 'func checkAge(_ age: Int) {\n    guard age >= 18 ___ {\n        print("Too young")\n        return\n    }\n    print("Access granted")\n}\ncheckAge(20)',
 'Access granted',
 3,
 'The guard else block is executed when the condition is false.', 'El bloque guard else se ejecuta cuando la condición es falsa.',
 'The keyword between the condition and the block is "else".', 'La palabra clave entre la condición y el bloque es "else".',
 'guard age >= 18 else {', 'guard age >= 18 else {',
 20, 3, now()),

-- 31. enums
(gen_random_uuid(),
 'Enum with Raw Values', 'Enum con Valores Raw',
 'Define an enum Planet: Int with cases mercury=1, venus, earth. Print Planet.earth.rawValue.',
 'Define un enum Planet: Int con casos mercury=1, venus, earth. Imprime Planet.earth.rawValue.',
 'swift', 2, 'enums',
 'enum Planet: Int {\n    case mercury = 1, venus, earth\n}\nprint(Planet.earth.___)',
 '3',
 3,
 'Raw values auto-increment from the starting value.', 'Los valores raw se auto-incrementan desde el valor inicial.',
 'Access the raw value with the rawValue property.', 'Accede al valor raw con la propiedad rawValue.',
 'print(Planet.earth.rawValue)', 'print(Planet.earth.rawValue)',
 20, 3, now()),

-- 32. enums
(gen_random_uuid(),
 'Enum with Associated Values', 'Enum con Valores Asociados',
 'Define enum Shape with cases circle(radius: Double) and rectangle(width: Double, height: Double). Create a circle with radius 5.0 and switch on it to print "Circle with radius 5.0".',
 'Define el enum Shape con casos circle(radius: Double) y rectangle(width: Double, height: Double). Crea un círculo con radio 5.0 y haz switch sobre él para imprimir "Circle with radius 5.0".',
 'swift', 2, 'enums',
 'enum Shape {\n    case circle(radius: Double)\n    case rectangle(width: Double, height: Double)\n}\nlet s = Shape.circle(radius: 5.0)\nswitch s {\ncase .circle(let r):\n    print("Circle with radius \\(___)")\ncase .rectangle(let w, let h):\n    print("Rectangle \\(w)x\\(h)")\n}',
 'Circle with radius 5.0',
 3,
 'The associated value is bound to a local constant in the switch case.', 'El valor asociado se enlaza a una constante local en el caso del switch.',
 'The bound constant for radius is named r in this starter.', 'La constante enlazada para el radio se llama r en este inicio.',
 'print("Circle with radius \\(r)")', 'print("Circle with radius \\(r)")',
 20, 3, now()),

-- 33. protocols
(gen_random_uuid(),
 'Define a Protocol', 'Definir un Protocolo',
 'Define a protocol Describable with a method describe() -> String. Implement it in a struct Car with brand "Toyota" returning "Car: Toyota".',
 'Define un protocolo Describable con un método describe() -> String. Impleméntalo en una estructura Car con marca "Toyota" devolviendo "Car: Toyota".',
 'swift', 2, 'protocols',
 'protocol Describable {\n    func describe() -> String\n}\nstruct Car: ___ {\n    let brand = "Toyota"\n    func describe() -> String {\n        return "Car: \\(brand)"\n    }\n}\nlet c = Car()\nprint(c.describe())',
 'Car: Toyota',
 3,
 'A struct adopts a protocol by writing its name after the colon in the struct declaration.', 'Una estructura adopta un protocolo escribiendo su nombre después de los dos puntos en la declaración de la estructura.',
 'The protocol name is Describable.', 'El nombre del protocolo es Describable.',
 'struct Car: Describable', 'struct Car: Describable',
 20, 3, now()),

-- 34. extensions
(gen_random_uuid(),
 'Extend Int', 'Extender Int',
 'Write an extension on Int that adds a computed property isEven: Bool. Print (4).isEven.',
 'Escribe una extensión en Int que añada una propiedad computada isEven: Bool. Imprime (4).isEven.',
 'swift', 2, 'extensions',
 'extension Int {\n    var isEven: Bool {\n        return ___ % 2 == 0\n    }\n}\nprint((4).isEven)',
 'true',
 3,
 'Inside the extension, use "self" to refer to the current Int value.', 'Dentro de la extensión, usa "self" para referirte al valor Int actual.',
 'self % 2 == 0 returns true when the number is divisible by 2.', 'self % 2 == 0 devuelve true cuando el número es divisible por 2.',
 'return self % 2 == 0', 'return self % 2 == 0',
 20, 3, now()),

-- 35. closures
(gen_random_uuid(),
 'Filter with Closure', 'Filter con Closure',
 'Use filter to keep only even numbers from [1, 2, 3, 4, 5, 6] and print the result.',
 'Usa filter para conservar solo los números pares de [1, 2, 3, 4, 5, 6] e imprime el resultado.',
 'swift', 2, 'closures',
 'let evens = [1, 2, 3, 4, 5, 6].filter { ___ % 2 == 0 }\nprint(evens)',
 '[2, 4, 6]',
 3,
 'The shorthand argument $0 refers to the current element in the closure.', 'El argumento abreviado $0 se refiere al elemento actual en el closure.',
 'Alternatively name the parameter and use "n % 2 == 0".', 'Alternativamente nombra el parámetro y usa "n % 2 == 0".',
 '[1, 2, 3, 4, 5, 6].filter { $0 % 2 == 0 }', '[1, 2, 3, 4, 5, 6].filter { $0 % 2 == 0 }',
 20, 3, now()),

-- 36. closures
(gen_random_uuid(),
 'Reduce with Closure', 'Reduce con Closure',
 'Use reduce to sum all elements in [1, 2, 3, 4, 5] and print the result.',
 'Usa reduce para sumar todos los elementos en [1, 2, 3, 4, 5] e imprime el resultado.',
 'swift', 2, 'closures',
 'let sum = [1, 2, 3, 4, 5].reduce(___, { $0 + $1 })\nprint(sum)',
 '15',
 3,
 'The first argument to reduce is the initial value.', 'El primer argumento de reduce es el valor inicial.',
 'For a sum, the initial value should be 0.', 'Para una suma, el valor inicial debe ser 0.',
 '[1, 2, 3, 4, 5].reduce(0, { $0 + $1 })', '[1, 2, 3, 4, 5].reduce(0, { $0 + $1 })',
 20, 3, now()),

-- 37. structs
(gen_random_uuid(),
 'Mutating Method', 'Método Mutating',
 'Define a struct Counter with var count = 0 and a mutating method increment() that adds 1. Print after two increments.',
 'Define una estructura Counter con var count = 0 y un método mutating increment() que añada 1. Imprime después de dos incrementos.',
 'swift', 2, 'structs',
 'struct Counter {\n    var count = 0\n    ___ func increment() {\n        count += 1\n    }\n}\nvar c = Counter()\nc.increment()\nc.increment()\nprint(c.count)',
 '2',
 3,
 'Methods that modify struct properties must be marked with the "mutating" keyword.', 'Los métodos que modifican propiedades de estructuras deben marcarse con la palabra clave "mutating".',
 'Place "mutating" before "func".', 'Coloca "mutating" antes de "func".',
 'mutating func increment()', 'mutating func increment()',
 20, 3, now()),

-- 38. classes
(gen_random_uuid(),
 'Define a Class', 'Definir una Clase',
 'Define a class Animal with a property name: String and an init. Create an instance with name "Cat" and print its name.',
 'Define una clase Animal con una propiedad name: String y un init. Crea una instancia con nombre "Cat" e imprime su nombre.',
 'swift', 2, 'classes',
 'class Animal {\n    var name: String\n    ___(name: String) {\n        self.name = name\n    }\n}\nlet a = Animal(name: "Cat")\nprint(a.name)',
 'Cat',
 3,
 'Classes use the "init" keyword to define an initializer.', 'Las clases usan la palabra clave "init" para definir un inicializador.',
 'The initializer keyword is simply "init".', 'La palabra clave del inicializador es simplemente "init".',
 'init(name: String)', 'init(name: String)',
 20, 3, now()),

-- 39. classes
(gen_random_uuid(),
 'Class Inheritance', 'Herencia de Clase',
 'Define a class Dog that inherits from Animal and overrides a method speak() to print "Woof!". Call speak() on a Dog instance.',
 'Define una clase Dog que herede de Animal y sobreescriba un método speak() para imprimir "Woof!". Llama speak() en una instancia de Dog.',
 'swift', 2, 'classes',
 'class Animal {\n    func speak() { print("...") }\n}\nclass Dog: Animal {\n    ___ func speak() {\n        print("Woof!")\n    }\n}\nlet d = Dog()\nd.speak()',
 'Woof!',
 3,
 'To override a method from a superclass, use the "override" keyword.', 'Para sobreescribir un método de una superclase, usa la palabra clave "override".',
 'Place "override" before "func".', 'Coloca "override" antes de "func".',
 'override func speak()', 'override func speak()',
 20, 3, now()),

-- 40. error-handling
(gen_random_uuid(),
 'Throwing Function', 'Función que Lanza Errores',
 'Define an enum AppError: Error with case invalidInput. Write a func validate(_ n: Int) throws that throws invalidInput when n < 0, then call it with try.',
 'Define un enum AppError: Error con caso invalidInput. Escribe una func validate(_ n: Int) throws que lance invalidInput cuando n < 0, luego llámala con try.',
 'swift', 2, 'error-handling',
 'enum AppError: Error { case invalidInput }\nfunc validate(_ n: Int) throws {\n    if n < 0 { ___ AppError.invalidInput }\n}\ndo {\n    try validate(-1)\n} catch {\n    print("Invalid input")\n}',
 'Invalid input',
 3,
 'The keyword to throw an error is "throw" (not "throws").', 'La palabra clave para lanzar un error es "throw" (no "throws").',
 '"throws" is used in the function signature; "throw" is used inside the body.', '"throws" se usa en la firma de la función; "throw" se usa dentro del cuerpo.',
 'throw AppError.invalidInput', 'throw AppError.invalidInput',
 20, 3, now()),

-- 41. sets
(gen_random_uuid(),
 'Create a Set', 'Crear un Set',
 'Declare a Set<Int> named uniqueNums = [1, 2, 2, 3, 3] and print its count.',
 'Declara un Set<Int> llamado uniqueNums = [1, 2, 2, 3, 3] e imprime su conteo.',
 'swift', 2, 'collections',
 'let uniqueNums: Set<___> = [1, 2, 2, 3, 3]\nprint(uniqueNums.count)',
 '3',
 3,
 'Sets store unique values — duplicates are ignored.', 'Los Sets almacenan valores únicos — los duplicados se ignoran.',
 'The generic type parameter is Int.', 'El parámetro de tipo genérico es Int.',
 'let uniqueNums: Set<Int> = [1, 2, 2, 3, 3]', 'let uniqueNums: Set<Int> = [1, 2, 2, 3, 3]',
 20, 3, now()),

-- 42. higher-order
(gen_random_uuid(),
 'Sorted with Closure', 'Sorted con Closure',
 'Sort ["banana", "apple", "cherry"] alphabetically using sorted(by:) and print the result.',
 'Ordena ["banana", "apple", "cherry"] alfabéticamente usando sorted(by:) e imprime el resultado.',
 'swift', 2, 'higher-order',
 'let fruits = ["banana", "apple", "cherry"]\nlet sorted = fruits.sorted(by: { ___ < ___ })\nprint(sorted)',
 '["apple", "banana", "cherry"]',
 3,
 'The closure receives two elements to compare. Use $0 and $1 as shorthand.', 'El closure recibe dos elementos para comparar. Usa $0 y $1 como abreviatura.',
 'Return true if the first element should come before the second.', 'Devuelve true si el primer elemento debe ir antes que el segundo.',
 'fruits.sorted(by: { $0 < $1 })', 'fruits.sorted(by: { $0 < $1 })',
 20, 3, now()),

-- 43. strings
(gen_random_uuid(),
 'String Contains', 'Cadena Contiene',
 'Check if "Hello, Swift!" contains the substring "Swift" and print the result.',
 'Comprueba si "Hello, Swift!" contiene la subcadena "Swift" e imprime el resultado.',
 'swift', 2, 'strings',
 'let sentence = "Hello, Swift!"\nprint(sentence.___(___("Swift")))',
 'true',
 3,
 'Use the contains() method on a String to check for a substring.', 'Usa el método contains() en un String para comprobar una subcadena.',
 'Pass the substring as a string literal argument.', 'Pasa la subcadena como argumento literal de cadena.',
 'print(sentence.contains("Swift"))', 'print(sentence.contains("Swift"))',
 20, 3, now()),

-- 44. generics
(gen_random_uuid(),
 'Generic Function', 'Función Genérica',
 'Write a generic function swapValues<T>(_ a: inout T, _ b: inout T) that swaps two values. Print after swapping x=1, y=2.',
 'Escribe una función genérica swapValues<T>(_ a: inout T, _ b: inout T) que intercambie dos valores. Imprime después de intercambiar x=1, y=2.',
 'swift', 2, 'generics',
 'func swapValues<T>(_ a: inout T, _ b: inout T) {\n    let temp = ___\n    a = b\n    b = temp\n}\nvar x = 1, y = 2\nswapValues(&x, &y)\nprint(x, y)',
 '2 1',
 3,
 'Store the value of "a" in a temporary constant before overwriting it.', 'Almacena el valor de "a" en una constante temporal antes de sobreescribirlo.',
 'let temp = a', 'let temp = a',
 'let temp = a', 'let temp = a',
 20, 3, now()),

-- 45. tuples
(gen_random_uuid(),
 'Named Tuple', 'Tupla Nombrada',
 'Declare a named tuple let coord = (x: 10, y: 20) and print both values as "10 20".',
 'Declara una tupla nombrada let coord = (x: 10, y: 20) e imprime ambos valores como "10 20".',
 'swift', 2, 'tuples',
 'let coord = (x: 10, y: 20)\nprint(coord.___, coord.___)',
 '10 20',
 3,
 'Access named tuple members using their label names.', 'Accede a los miembros de tuplas nombradas usando sus etiquetas.',
 'The labels are x and y.', 'Las etiquetas son x e y.',
 'print(coord.x, coord.y)', 'print(coord.x, coord.y)',
 20, 3, now()),

-- 46. control-flow
(gen_random_uuid(),
 'Repeat-While Loop', 'Bucle Repeat-While',
 'Use a repeat-while loop to print "tick" exactly 3 times, decrementing a counter from 3 to 1.',
 'Usa un bucle repeat-while para imprimir "tick" exactamente 3 veces, decrementando un contador de 3 a 1.',
 'swift', 2, 'control-flow',
 'var n = 3\n___ {\n    print("tick")\n    n -= 1\n} while n > 0',
 'tick\ntick\ntick',
 3,
 'The repeat-while loop always executes the body at least once.', 'El bucle repeat-while siempre ejecuta el cuerpo al menos una vez.',
 'Start the loop with the "repeat" keyword.', 'Inicia el bucle con la palabra clave "repeat".',
 'repeat {', 'repeat {',
 20, 3, now()),

-- 47. functions
(gen_random_uuid(),
 'Default Parameter', 'Parámetro por Defecto',
 'Define func greet(name: String, greeting: String = "Hello") that prints "Hello, Alice!" when called as greet(name: "Alice").',
 'Define func greet(name: String, greeting: String = "Hello") que imprima "Hello, Alice!" cuando se llama como greet(name: "Alice").',
 'swift', 2, 'functions',
 'func greet(name: String, greeting: String = "Hello") {\n    print("\\(greeting), \\(name)!")\n}\ngreet(name: ___)',
 'Hello, Alice!',
 3,
 'When a parameter has a default value, you can omit it at the call site.', 'Cuando un parámetro tiene un valor predeterminado, puedes omitirlo en el lugar de la llamada.',
 'Pass only the name argument since greeting has a default.', 'Pasa solo el argumento name ya que greeting tiene un valor predeterminado.',
 'greet(name: "Alice")', 'greet(name: "Alice")',
 20, 3, now()),

-- 48. functions
(gen_random_uuid(),
 'Variadic Parameters', 'Parámetros Variádicos',
 'Define func sum(_ numbers: Int...) -> Int that returns the sum of all arguments. Print sum(1, 2, 3, 4).',
 'Define func sum(_ numbers: Int...) -> Int que devuelva la suma de todos los argumentos. Imprime sum(1, 2, 3, 4).',
 'swift', 2, 'functions',
 'func sum(_ numbers: Int...) -> Int {\n    return numbers.___(0, +)\n}\nprint(sum(1, 2, 3, 4))',
 '10',
 3,
 'Use reduce on the variadic parameter which is treated as an array inside the function.', 'Usa reduce sobre el parámetro variádico que se trata como un array dentro de la función.',
 'numbers.reduce(0, +) sums all elements starting from 0.', 'numbers.reduce(0, +) suma todos los elementos comenzando desde 0.',
 'return numbers.reduce(0, +)', 'return numbers.reduce(0, +)',
 20, 3, now()),

-- 49. optionals
(gen_random_uuid(),
 'Optional Map', 'Map sobre Optional',
 'Given var number: Int? = 5, use optional map to get a String? of the doubled value and print it.',
 'Dado var number: Int? = 5, usa map sobre el optional para obtener un String? del valor duplicado e imprímelo.',
 'swift', 2, 'optionals',
 'var number: Int? = 5\nlet result = number.___ { String($0 * 2) }\nprint(result)',
 'Optional("10")',
 3,
 'Optionals have a map method that transforms the wrapped value if it exists.', 'Los opcionales tienen un método map que transforma el valor envuelto si existe.',
 'Use .map { } with a trailing closure.', 'Usa .map { } con un trailing closure.',
 'let result = number.map { String($0 * 2) }', 'let result = number.map { String($0 * 2) }',
 20, 3, now()),

-- 50. protocols
(gen_random_uuid(),
 'Protocol with Property', 'Protocolo con Propiedad',
 'Define a protocol Named with a get-only property name: String. Implement it in struct Person with name "Bob". Print the name.',
 'Define un protocolo Named con una propiedad de solo lectura name: String. Impleméntalo en una estructura Person con nombre "Bob". Imprime el nombre.',
 'swift', 2, 'protocols',
 'protocol Named {\n    var name: String { ___ }\n}\nstruct Person: Named {\n    let name = "Bob"\n}\nlet p = Person()\nprint(p.name)',
 'Bob',
 3,
 'A read-only property requirement in a protocol uses the "get" keyword inside braces.', 'Un requisito de propiedad de solo lectura en un protocolo usa la palabra clave "get" dentro de llaves.',
 'Write "get" inside the curly braces after the property type.', 'Escribe "get" dentro de las llaves después del tipo de propiedad.',
 'var name: String { get }', 'var name: String { get }',
 20, 3, now()),

-- ============================================================
-- DIFFICULTY 3 — 25 exercises (points=30, penalty=5)
-- ============================================================

-- 51. generics
(gen_random_uuid(),
 'Generic Stack', 'Pila Genérica',
 'Implement a generic struct Stack<T> with methods push(_ item: T), pop() -> T?, and a peek computed property. Push 1 and 2, then print peek.',
 'Implementa una estructura genérica Stack<T> con métodos push(_ item: T), pop() -> T? y una propiedad computada peek. Haz push de 1 y 2, luego imprime peek.',
 'swift', 3, 'generics',
 'struct Stack<T> {\n    private var items: [T] = []\n    mutating func push(_ item: T) { items.append(item) }\n    mutating func pop() -> T? { return items.___ }\n    var peek: T? { return items.last }\n}\nvar s = Stack<Int>()\ns.push(1)\ns.push(2)\nprint(s.peek)',
 'Optional(2)',
 3,
 'pop() should remove and return the last element of the items array.', 'pop() debe eliminar y devolver el último elemento del array items.',
 'Arrays have a popLast() method that removes and returns the last element as an Optional.', 'Los arrays tienen un método popLast() que elimina y devuelve el último elemento como Optional.',
 'return items.popLast()', 'return items.popLast()',
 30, 5, now()),

-- 52. generics
(gen_random_uuid(),
 'Generic Constraint', 'Restricción Genérica',
 'Write a generic function largest<T: Comparable>(_ array: [T]) -> T? that returns the largest element. Print largest([3, 1, 4, 1, 5]).',
 'Escribe una función genérica largest<T: Comparable>(_ array: [T]) -> T? que devuelva el elemento más grande. Imprime largest([3, 1, 4, 1, 5]).',
 'swift', 3, 'generics',
 'func largest<T: Comparable>(_ array: [T]) -> T? {\n    return array.___\n}\nprint(largest([3, 1, 4, 1, 5]))',
 'Optional(5)',
 3,
 'Arrays have a built-in max() method that returns the largest element as an Optional.', 'Los arrays tienen un método max() integrado que devuelve el elemento más grande como Optional.',
 'Call max() with no arguments on the array.', 'Llama a max() sin argumentos sobre el array.',
 'return array.max()', 'return array.max()',
 30, 5, now()),

-- 53. protocols
(gen_random_uuid(),
 'Protocol Extension Default', 'Extensión de Protocolo con Default',
 'Define protocol Greetable with func greet() -> String. Add a protocol extension providing a default returning "Hello!". Create struct Guest that conforms but does not implement greet(). Print Guest().greet().',
 'Define el protocolo Greetable con func greet() -> String. Añade una extensión de protocolo que provea un default devolviendo "Hello!". Crea una estructura Guest que conforme pero no implemente greet(). Imprime Guest().greet().',
 'swift', 3, 'protocols',
 'protocol Greetable {\n    func greet() -> String\n}\n___ Greetable {\n    func greet() -> String { return "Hello!" }\n}\nstruct Guest: Greetable {}\nprint(Guest().greet())',
 'Hello!',
 3,
 'Protocol extensions are written with "extension ProtocolName".', 'Las extensiones de protocolo se escriben con "extension NombreProtocolo".',
 'Use the "extension" keyword before the protocol name.', 'Usa la palabra clave "extension" antes del nombre del protocolo.',
 'extension Greetable', 'extension Greetable',
 30, 5, now()),

-- 54. error-handling
(gen_random_uuid(),
 'Custom Error with Message', 'Error Personalizado con Mensaje',
 'Define enum NetworkError: Error with cases timeout, notFound(url: String). Catch notFound and print "Not found: <url>".',
 'Define enum NetworkError: Error con casos timeout y notFound(url: String). Captura notFound e imprime "Not found: <url>".',
 'swift', 3, 'error-handling',
 'enum NetworkError: Error {\n    case timeout\n    case notFound(url: String)\n}\nfunc fetch(_ url: String) throws {\n    throw NetworkError.notFound(url: url)\n}\ndo {\n    try fetch("https://example.com")\n} catch NetworkError.notFound(let url) {\n    print("Not found: \\(___)")\n} catch {\n    print("Other error")\n}',
 'Not found: https://example.com',
 3,
 'The associated value "url" is bound to a local constant in the catch clause.', 'El valor asociado "url" se enlaza a una constante local en la cláusula catch.',
 'The bound constant is named url in this catch.', 'La constante enlazada se llama url en este catch.',
 'print("Not found: \\(url)")', 'print("Not found: \\(url)")',
 30, 5, now()),

-- 55. closures
(gen_random_uuid(),
 'Closure Capturing Values', 'Closure Capturando Valores',
 'Write a function makeCounter() -> () -> Int that returns a closure incrementing a local counter. Print three calls.',
 'Escribe una función makeCounter() -> () -> Int que devuelva un closure que incremente un contador local. Imprime tres llamadas.',
 'swift', 3, 'closures',
 'func makeCounter() -> () -> Int {\n    var count = 0\n    return {\n        count += 1\n        return ___\n    }\n}\nlet counter = makeCounter()\nprint(counter())\nprint(counter())\nprint(counter())',
 '1\n2\n3',
 3,
 'The closure captures "count" by reference, so it persists between calls.', 'El closure captura "count" por referencia, por lo que persiste entre llamadas.',
 'Return the incremented count value.', 'Devuelve el valor de count ya incrementado.',
 'return count', 'return count',
 30, 5, now()),

-- 56. structs-vs-classes
(gen_random_uuid(),
 'Value vs Reference Semantics', 'Semántica de Valor vs Referencia',
 'Demonstrate that structs are value types: assign var a = Point(x:1) to b, change b.x to 9, print a.x (should be 1).',
 'Demuestra que las estructuras son tipos de valor: asigna var a = Point(x:1) a b, cambia b.x a 9, imprime a.x (debe ser 1).',
 'swift', 3, 'structs',
 'struct Point { var x: Int }\nvar a = Point(x: 1)\nvar ___ = a\nb.x = 9\nprint(a.x)',
 '1',
 3,
 'Structs are copied when assigned to a new variable — changes to the copy do not affect the original.', 'Las estructuras se copian al asignarse a una nueva variable — los cambios en la copia no afectan al original.',
 'Declare the second variable as "b".', 'Declara la segunda variable como "b".',
 'var b = a', 'var b = a',
 30, 5, now()),

-- 57. codable
(gen_random_uuid(),
 'Codable Struct', 'Estructura Codable',
 'Define a Codable struct User with properties name: String and age: Int. Encode an instance to JSON and print the JSON string.',
 'Define una estructura Codable User con propiedades name: String y age: Int. Codifica una instancia a JSON e imprime la cadena JSON.',
 'swift', 3, 'codable',
 'import Foundation\nstruct User: Codable {\n    let name: String\n    let age: Int\n}\nlet user = User(name: "Alice", age: 30)\nlet encoder = JSONEncoder()\nif let data = try? encoder.encode(user),\n   let json = ___(data, encoding: .utf8) {\n    print(json)\n}',
 '{"name":"Alice","age":30}',
 3,
 'Convert Data to String using the String(data:encoding:) initializer.', 'Convierte Data a String usando el inicializador String(data:encoding:).',
 'The initializer is String(data: data, encoding: .utf8).', 'El inicializador es String(data: data, encoding: .utf8).',
 'String(data: data, encoding: .utf8)', 'String(data: data, encoding: .utf8)',
 30, 5, now()),

-- 58. codable
(gen_random_uuid(),
 'Decode JSON', 'Decodificar JSON',
 'Decode a JSON string {"score":42} into a struct Result: Codable with property score: Int, then print the score.',
 'Decodifica una cadena JSON {"score":42} en una estructura Result: Codable con propiedad score: Int, luego imprime el score.',
 'swift', 3, 'codable',
 'import Foundation\nstruct Result: Codable { let score: Int }\nlet json = #"{"score":42}"#\nlet data = json.data(using: .utf8)!\nlet decoder = ___Decoder()\nif let r = try? decoder.decode(Result.self, from: data) {\n    print(r.score)\n}',
 '42',
 3,
 'The decoder for JSON is JSONDecoder.', 'El decodificador para JSON es JSONDecoder.',
 'Replace the blank with "JSON".', 'Reemplaza el espacio en blanco con "JSON".',
 'let decoder = JSONDecoder()', 'let decoder = JSONDecoder()',
 30, 5, now()),

-- 59. extensions
(gen_random_uuid(),
 'Extension with Method', 'Extensión con Método',
 'Write an extension on String that adds a method reversed() -> String returning the string in reverse. Print "Swift".reversed().',
 'Escribe una extensión en String que añada un método reversed() -> String que devuelva la cadena al revés. Imprime "Swift".reversed().',
 'swift', 3, 'extensions',
 'extension String {\n    func reversed() -> String {\n        return String(self.___)\n    }\n}\nprint("Swift".reversed())',
 'tfiwS',
 3,
 'String has a reversed() method on its characters that returns a ReversedCollection.', 'String tiene un método reversed() en sus caracteres que devuelve una ReversedCollection.',
 'Wrap self.reversed() with String() to convert back to a String.', 'Envuelve self.reversed() con String() para convertirlo de vuelta a String.',
 'String(self.reversed())', 'String(self.reversed())',
 30, 5, now()),

-- 60. protocols
(gen_random_uuid(),
 'Protocol Composition', 'Composición de Protocolos',
 'Define protocols Named (var name: String { get }) and Aged (var age: Int { get }). Write func describe(_ x: Named & Aged) that prints "Alice is 30". Call it with a struct that conforms to both.',
 'Define los protocolos Named (var name: String { get }) y Aged (var age: Int { get }). Escribe una func describe(_ x: Named & Aged) que imprima "Alice is 30". Llámala con una estructura que conforme a ambos.',
 'swift', 3, 'protocols',
 'protocol Named { var name: String { get } }\nprotocol Aged { var age: Int { get } }\nfunc describe(_ x: Named ___ Aged) {\n    print("\\(x.name) is \\(x.age)")\n}\nstruct Person: Named, Aged {\n    let name = "Alice"\n    let age = 30\n}\ndescribe(Person())',
 'Alice is 30',
 3,
 'Protocol composition in Swift uses the & operator between protocol names.', 'La composición de protocolos en Swift usa el operador & entre nombres de protocolos.',
 'Replace the blank with &.', 'Reemplaza el espacio en blanco con &.',
 'func describe(_ x: Named & Aged)', 'func describe(_ x: Named & Aged)',
 30, 5, now()),

-- 61. closures
(gen_random_uuid(),
 'Function as Argument', 'Función como Argumento',
 'Write a func apply(_ n: Int, _ fn: (Int) -> Int) -> Int that applies fn to n. Pass a closure that adds 10. Print apply(5, { $0 + 10 }).',
 'Escribe una func apply(_ n: Int, _ fn: (Int) -> Int) -> Int que aplique fn a n. Pasa un closure que sume 10. Imprime apply(5, { $0 + 10 }).',
 'swift', 3, 'closures',
 'func apply(_ n: Int, _ fn: (Int) -> Int) -> Int {\n    return ___\n}\nprint(apply(5, { $0 + 10 }))',
 '15',
 3,
 'Call fn with n as the argument and return the result.', 'Llama a fn con n como argumento y devuelve el resultado.',
 'fn(n) calls the closure with the integer n.', 'fn(n) llama al closure con el entero n.',
 'return fn(n)', 'return fn(n)',
 30, 5, now()),

-- 62. enums
(gen_random_uuid(),
 'Enum Computed Property', 'Propiedad Computada en Enum',
 'Add a computed property description: String to enum Coin { case penny, nickel, dime, quarter } returning the value in cents. Print Coin.quarter.description.',
 'Añade una propiedad computada description: String al enum Coin { case penny, nickel, dime, quarter } que devuelva el valor en centavos. Imprime Coin.quarter.description.',
 'swift', 3, 'enums',
 'enum Coin {\n    case penny, nickel, dime, quarter\n    var description: String {\n        switch ___ {\n        case .penny: return "1 cent"\n        case .nickel: return "5 cents"\n        case .dime: return "10 cents"\n        case .quarter: return "25 cents"\n        }\n    }\n}\nprint(Coin.quarter.description)',
 '25 cents',
 3,
 'Inside an enum, use "self" to switch on the current case.', 'Dentro de un enum, usa "self" para hacer switch sobre el caso actual.',
 'The switch expression should be the "self" keyword.', 'La expresión del switch debe ser la palabra clave "self".',
 'switch self', 'switch self',
 30, 5, now()),

-- 63. async-await
(gen_random_uuid(),
 'Async Function', 'Función Async',
 'Define an async function fetchMessage() -> String that returns "Hello async". Call it with await inside a Task and print the result.',
 'Define una función async fetchMessage() -> String que devuelva "Hello async". Llámala con await dentro de un Task e imprime el resultado.',
 'swift', 3, 'async-await',
 'func fetchMessage() ___ -> String {\n    return "Hello async"\n}\nTask {\n    let msg = await fetchMessage()\n    print(msg)\n}',
 'Hello async',
 3,
 'Mark a function as asynchronous using the "async" keyword before the return arrow.', 'Marca una función como asíncrona usando la palabra clave "async" antes de la flecha de retorno.',
 'Place "async" between the closing parenthesis of parameters and the "->".', 'Coloca "async" entre el paréntesis de cierre de los parámetros y el "->".',
 'func fetchMessage() async -> String', 'func fetchMessage() async -> String',
 30, 5, now()),

-- 64. error-handling
(gen_random_uuid(),
 'Try? and Try!', 'Try? y Try!',
 'Use try? to call a throwing function divide(_ a: Int, _ b: Int) -> Int that throws when b == 0. Print the result of divide(10, 2) using try?.',
 'Usa try? para llamar a una función que lanza divide(_ a: Int, _ b: Int) -> Int que lanza cuando b == 0. Imprime el resultado de divide(10, 2) usando try?.',
 'swift', 3, 'error-handling',
 'enum MathError: Error { case divisionByZero }\nfunc divide(_ a: Int, _ b: Int) throws -> Int {\n    guard b != 0 else { throw MathError.divisionByZero }\n    return a / b\n}\nlet result = ___ divide(10, 2)\nprint(result)',
 'Optional(5)',
 3,
 'try? converts the result of a throwing call into an Optional — nil on error.', 'try? convierte el resultado de una llamada que lanza en un Optional — nil en caso de error.',
 'Place try? before the function call.', 'Coloca try? antes de la llamada a la función.',
 'let result = try? divide(10, 2)', 'let result = try? divide(10, 2)',
 30, 5, now()),

-- 65. structs
(gen_random_uuid(),
 'Computed Property', 'Propiedad Computada',
 'Add a computed property area: Double to struct Rectangle { var width: Double; var height: Double } that returns width * height. Print Rectangle(width: 4, height: 5).area.',
 'Añade una propiedad computada area: Double a struct Rectangle { var width: Double; var height: Double } que devuelva width * height. Imprime Rectangle(width: 4, height: 5).area.',
 'swift', 3, 'structs',
 'struct Rectangle {\n    var width: Double\n    var height: Double\n    var area: Double {\n        return ___ * ___\n    }\n}\nprint(Rectangle(width: 4, height: 5).area)',
 '20.0',
 3,
 'A computed property uses a getter body with a return statement.', 'Una propiedad computada usa un cuerpo getter con una sentencia return.',
 'Multiply the width and height properties.', 'Multiplica las propiedades width y height.',
 'return width * height', 'return width * height',
 30, 5, now()),

-- 66. type-casting
(gen_random_uuid(),
 'Type Casting with as?', 'Conversión de Tipo con as?',
 'Given a variable any: Any = "Hello", use as? to conditionally cast it to String and print its count.',
 'Dado una variable any: Any = "Hello", usa as? para convertirlo condicionalmente a String e imprime su conteo.',
 'swift', 3, 'type-casting',
 'let any: Any = "Hello"\nif let str = any ___ String {\n    print(str.count)\n}',
 '5',
 3,
 'Conditional type casting uses the "as?" operator.', 'La conversión de tipo condicional usa el operador "as?".',
 'Place "as?" between the value and the target type.', 'Coloca "as?" entre el valor y el tipo destino.',
 'if let str = any as? String', 'if let str = any as? String',
 30, 5, now()),

-- 67. collections
(gen_random_uuid(),
 'Dictionary compactMapValues', 'compactMapValues en Diccionario',
 'Given ["a": "1", "b": "two", "c": "3"], use compactMapValues { Int($0) } to convert to [String: Int], dropping non-numeric values. Print the result count.',
 'Dado ["a": "1", "b": "two", "c": "3"], usa compactMapValues { Int($0) } para convertir a [String: Int], descartando valores no numéricos. Imprime el conteo del resultado.',
 'swift', 3, 'collections',
 'let raw = ["a": "1", "b": "two", "c": "3"]\nlet nums = raw.___ { Int($0) }\nprint(nums.count)',
 '2',
 3,
 'compactMapValues transforms dictionary values and discards nil results.', 'compactMapValues transforma los valores del diccionario y descarta los resultados nil.',
 'Call .compactMapValues { } with a trailing closure.', 'Llama a .compactMapValues { } con un trailing closure.',
 'raw.compactMapValues { Int($0) }', 'raw.compactMapValues { Int($0) }',
 30, 5, now()),

-- 68. protocols
(gen_random_uuid(),
 'Equatable Protocol', 'Protocolo Equatable',
 'Conform struct Point(x: Int, y: Int) to Equatable by implementing ==. Print whether Point(1,2) == Point(1,2).',
 'Conforma la estructura Point(x: Int, y: Int) a Equatable implementando ==. Imprime si Point(1,2) == Point(1,2).',
 'swift', 3, 'protocols',
 'struct Point: Equatable {\n    let x: Int, y: Int\n    static func == (lhs: Point, rhs: Point) -> Bool {\n        return lhs.x == rhs.x ___ lhs.y == rhs.y\n    }\n}\nprint(Point(x:1,y:2) == Point(x:1,y:2))',
 'true',
 3,
 'Both x and y must be equal for two Points to be equal.', 'Tanto x como y deben ser iguales para que dos Points sean iguales.',
 'Combine both conditions with the && operator.', 'Combina ambas condiciones con el operador &&.',
 'lhs.x == rhs.x && lhs.y == rhs.y', 'lhs.x == rhs.x && lhs.y == rhs.y',
 30, 5, now()),

-- 69. enums
(gen_random_uuid(),
 'CaseIterable Enum', 'Enum CaseIterable',
 'Make enum Season: CaseIterable { case spring, summer, autumn, winter } and print all cases using allCases.',
 'Haz que enum Season: CaseIterable { case spring, summer, autumn, winter } e imprime todos los casos usando allCases.',
 'swift', 3, 'enums',
 'enum Season: CaseIterable {\n    case spring, summer, autumn, winter\n}\nfor s in Season.___ {\n    print(s)\n}',
 'spring\nsummer\nautumn\nwinter',
 3,
 'CaseIterable adds a static property allCases to the enum.', 'CaseIterable añade una propiedad estática allCases al enum.',
 'Iterate over Season.allCases.', 'Itera sobre Season.allCases.',
 'for s in Season.allCases', 'for s in Season.allCases',
 30, 5, now()),

-- 70. pattern-matching
(gen_random_uuid(),
 'Where Clause in Switch', 'Cláusula Where en Switch',
 'Write a switch on an Int that prints "big even" for even numbers >= 100, using a where clause.',
 'Escribe un switch sobre un Int que imprima "big even" para números pares >= 100, usando una cláusula where.',
 'swift', 3, 'pattern-matching',
 'let n = 200\nswitch n {\ncase let x ___ x % 2 == 0 && x >= 100:\n    print("big even")\ndefault:\n    print("other")\n}',
 'big even',
 3,
 'A "where" clause adds an additional condition to a switch case.', 'Una cláusula "where" añade una condición adicional a un caso de switch.',
 'Write "where" after "case let x".', 'Escribe "where" después de "case let x".',
 'case let x where x % 2 == 0 && x >= 100:', 'case let x where x % 2 == 0 && x >= 100:',
 30, 5, now()),

-- 71. closures
(gen_random_uuid(),
 'Escaping Closure', 'Closure Escapante',
 'Write a func delay(action: @escaping () -> Void) that stores the closure in a variable and calls it. Demonstrate with a closure that prints "Executed".',
 'Escribe una func delay(action: @escaping () -> Void) que almacene el closure en una variable y lo llame. Demuéstralo con un closure que imprima "Executed".',
 'swift', 3, 'closures',
 'var stored: (() -> Void)?\nfunc delay(action: ___ () -> Void) {\n    stored = action\n    stored?()\n}\ndelay { print("Executed") }',
 'Executed',
 3,
 'A closure that outlives the function call must be marked with @escaping.', 'Un closure que sobrevive a la llamada de función debe marcarse con @escaping.',
 'Place @escaping before the closure type.', 'Coloca @escaping antes del tipo del closure.',
 'func delay(action: @escaping () -> Void)', 'func delay(action: @escaping () -> Void)',
 30, 5, now()),

-- 72. optionals
(gen_random_uuid(),
 'Flat Map Optional', 'FlatMap sobre Optional',
 'Given var s: String? = "42", use flatMap to convert it to Int?. Print the result.',
 'Dado var s: String? = "42", usa flatMap para convertirlo a Int?. Imprime el resultado.',
 'swift', 3, 'optionals',
 'var s: String? = "42"\nlet n = s.___ { Int($0) }\nprint(n)',
 'Optional(42)',
 3,
 'flatMap on an Optional applies a transformation that itself returns an Optional, avoiding double-wrapping.', 'flatMap sobre un Optional aplica una transformación que devuelve un Optional, evitando el doble envolvimiento.',
 'Use .flatMap { } with a trailing closure.', 'Usa .flatMap { } con un trailing closure.',
 's.flatMap { Int($0) }', 's.flatMap { Int($0) }',
 30, 5, now()),

-- 73. async-await
(gen_random_uuid(),
 'Async Throws Function', 'Función Async Throws',
 'Define async throws func loadData() -> String that throws if a Bool flag fails is true, otherwise returns "Data loaded". Call with try await inside Task.',
 'Define async throws func loadData() -> String que lanza si un flag Bool fails es true, de lo contrario devuelve "Data loaded". Llama con try await dentro de Task.',
 'swift', 3, 'async-await',
 'enum LoadError: Error { case failed }\nfunc loadData() ___ ___ -> String {\n    let fails = false\n    if fails { throw LoadError.failed }\n    return "Data loaded"\n}\nTask {\n    if let result = try? await loadData() {\n        print(result)\n    }\n}',
 'Data loaded',
 3,
 'An async throwing function uses both "async" and "throws" before the return arrow.', 'Una función async que lanza usa tanto "async" como "throws" antes de la flecha de retorno.',
 'Write "async throws" in that order before "->".', 'Escribe "async throws" en ese orden antes de "->".',
 'func loadData() async throws -> String', 'func loadData() async throws -> String',
 30, 5, now()),

-- 74. collections
(gen_random_uuid(),
 'Zip Two Sequences', 'Zip de Dos Secuencias',
 'Zip ["a","b","c"] with [1,2,3] to produce pairs and print each pair.',
 'Combina ["a","b","c"] con [1,2,3] para producir pares e imprime cada par.',
 'swift', 3, 'collections',
 'let keys = ["a","b","c"]\nlet vals = [1,2,3]\nfor (k, v) in ___(keys, vals) {\n    print(k, v)\n}',
 'a 1\nb 2\nc 3',
 3,
 'The zip() function in Swift pairs elements from two sequences.', 'La función zip() en Swift empareja elementos de dos secuencias.',
 'Call zip with the two arrays as arguments.', 'Llama a zip con los dos arrays como argumentos.',
 'for (k, v) in zip(keys, vals)', 'for (k, v) in zip(keys, vals)',
 30, 5, now()),

-- 75. property-observers
(gen_random_uuid(),
 'didSet Property Observer', 'Observador de Propiedad didSet',
 'Add a didSet observer to var temperature: Double in a struct Thermostat that prints "Temperature changed" whenever the value changes. Trigger it by changing temp.',
 'Añade un observador didSet a var temperature: Double en una estructura Thermostat que imprima "Temperature changed" cada vez que cambie el valor. Dispáralo cambiando temp.',
 'swift', 3, 'property-observers',
 'struct Thermostat {\n    var temperature: Double {\n        ___ {\n            print("Temperature changed")\n        }\n    }\n}\nvar t = Thermostat()\nt.temperature = 22.5',
 'Temperature changed',
 3,
 'Property observers use "willSet" and "didSet" inside the property braces.', 'Los observadores de propiedades usan "willSet" y "didSet" dentro de las llaves de la propiedad.',
 'Use "didSet" to react after the value has been set.', 'Usa "didSet" para reaccionar después de que el valor ha sido establecido.',
 'didSet {', 'didSet {',
 30, 5, now()),

-- ============================================================
-- DIFFICULTY 4 — 15 exercises (points=50, penalty=10)
-- ============================================================

-- 76. generics
(gen_random_uuid(),
 'Generic Result Type', 'Tipo Result Genérico',
 'Use Swift''s built-in Result<Success, Failure> type to write a function parseAge(_ s: String) -> Result<Int, Error> that returns .success or .failure. Print success case.',
 'Usa el tipo Result<Success, Failure> integrado de Swift para escribir una función parseAge(_ s: String) -> Result<Int, Error> que devuelva .success o .failure. Imprime el caso success.',
 'swift', 4, 'generics',
 'enum AgeError: Error { case invalid }\nfunc parseAge(_ s: String) -> Result<Int, Error> {\n    guard let n = Int(s), n >= 0 else {\n        return .failure(AgeError.invalid)\n    }\n    return .___(n)\n}\nswitch parseAge("25") {\ncase .success(let age): print("Age: \\(age)")\ncase .failure: print("Error")\n}',
 'Age: 25',
 3,
 'Result has two cases: .success(Value) and .failure(Error).', 'Result tiene dos casos: .success(Valor) y .failure(Error).',
 'Return .success with the parsed integer.', 'Devuelve .success con el entero analizado.',
 'return .success(n)', 'return .success(n)',
 50, 10, now()),

-- 77. protocols
(gen_random_uuid(),
 'Associated Type in Protocol', 'Tipo Asociado en Protocolo',
 'Define a protocol Container with associatedtype Item and method add(_ item: Item). Implement in struct Bag<T> that stores items in an array. Add "pen" and "pencil" then print count.',
 'Define un protocolo Container con associatedtype Item y método add(_ item: Item). Impleméntalo en struct Bag<T> que almacene elementos en un array. Añade "pen" y "pencil" luego imprime el conteo.',
 'swift', 4, 'protocols',
 'protocol Container {\n    ___ Item\n    mutating func add(_ item: Item)\n}\nstruct Bag<T>: Container {\n    typealias Item = T\n    var items: [T] = []\n    mutating func add(_ item: T) { items.append(item) }\n}\nvar b = Bag<String>()\nb.add("pen")\nb.add("pencil")\nprint(b.items.count)',
 '2',
 3,
 'Associated types in protocols use the "associatedtype" keyword.', 'Los tipos asociados en protocolos usan la palabra clave "associatedtype".',
 'Write "associatedtype Item" inside the protocol.', 'Escribe "associatedtype Item" dentro del protocolo.',
 'associatedtype Item', 'associatedtype Item',
 50, 10, now()),

-- 78. async-await
(gen_random_uuid(),
 'Async Let Parallel', 'Async Let Paralelo',
 'Use "async let" to start two async functions concurrently: fetchA() -> "A" and fetchB() -> "B". Await both and print them together.',
 'Usa "async let" para iniciar dos funciones async concurrentemente: fetchA() -> "A" y fetchB() -> "B". Espera ambas e imprímelas juntas.',
 'swift', 4, 'async-await',
 'func fetchA() async -> String { return "A" }\nfunc fetchB() async -> String { return "B" }\nTask {\n    ___ a = await fetchA()\n    async let b = fetchB()\n    let results = await (a, b)\n    print(results.0, results.1)\n}',
 'A B',
 3,
 'async let starts an async task immediately without waiting for it.', 'async let inicia una tarea async de inmediato sin esperar por ella.',
 'Both declarations should use "async let".', 'Ambas declaraciones deben usar "async let".',
 'async let a = fetchA()', 'async let a = fetchA()',
 50, 10, now()),

-- 79. property-wrappers
(gen_random_uuid(),
 'Custom Property Wrapper', 'Property Wrapper Personalizado',
 'Define a @propertyWrapper struct Clamped that ensures a value stays between 0 and 100. Use it on a var score and set it to 150, print the clamped value.',
 'Define un @propertyWrapper struct Clamped que asegure que un valor se mantenga entre 0 y 100. Úsalo en un var score y establécelo en 150, imprime el valor limitado.',
 'swift', 4, 'property-wrappers',
 '@propertyWrapper\nstruct Clamped {\n    private var value: Int = 0\n    var wrappedValue: Int {\n        get { value }\n        set { value = max(0, min(100, newValue)) }\n    }\n}\nstruct Player {\n    @Clamped ___ score: Int\n}\nvar p = Player()\np.score = 150\nprint(p.score)',
 '100',
 3,
 'A property wrapped with @Clamped is declared as a normal variable inside the struct.', 'Una propiedad envuelta con @Clamped se declara como una variable normal dentro de la estructura.',
 'Use "var" to declare the score property.', 'Usa "var" para declarar la propiedad score.',
 '@Clamped var score: Int', '@Clamped var score: Int',
 50, 10, now()),

-- 80. codable
(gen_random_uuid(),
 'Custom Coding Keys', 'Claves de Codificación Personalizadas',
 'Decode JSON {"first_name":"Alice"} into struct Person: Codable with property firstName: String using a CodingKeys enum.',
 'Decodifica el JSON {"first_name":"Alice"} en struct Person: Codable con propiedad firstName: String usando un enum CodingKeys.',
 'swift', 4, 'codable',
 'import Foundation\nstruct Person: Codable {\n    let firstName: String\n    enum CodingKeys: String, CodingKey {\n        case firstName = ___\n    }\n}\nlet json = #"{"first_name":"Alice"}"#\nlet data = json.data(using: .utf8)!\nlet p = try! JSONDecoder().decode(Person.self, from: data)\nprint(p.firstName)',
 'Alice',
 3,
 'CodingKeys maps Swift property names to JSON key names using raw string values.', 'CodingKeys mapea nombres de propiedades Swift a nombres de clave JSON usando valores string raw.',
 'The JSON key for firstName is "first_name".', 'La clave JSON para firstName es "first_name".',
 'case firstName = "first_name"', 'case firstName = "first_name"',
 50, 10, now()),

-- 81. generics
(gen_random_uuid(),
 'Generic Where Clause', 'Cláusula Where Genérica',
 'Write a generic function areEqual<T>(_ a: T, _ b: T) -> Bool where T: Equatable. Return whether the two values are equal. Test with Int and String.',
 'Escribe una función genérica areEqual<T>(_ a: T, _ b: T) -> Bool where T: Equatable. Devuelve si los dos valores son iguales. Prueba con Int y String.',
 'swift', 4, 'generics',
 'func areEqual<T>(_ a: T, _ b: T) -> Bool ___ T: Equatable {\n    return a == b\n}\nprint(areEqual(3, 3))\nprint(areEqual("hi", "bye"))',
 'true\nfalse',
 3,
 'Generic constraints using "where" are placed after the parameter list.', 'Las restricciones genéricas usando "where" se colocan después de la lista de parámetros.',
 'Write "where" before the constraint T: Equatable.', 'Escribe "where" antes de la restricción T: Equatable.',
 'func areEqual<T>(_ a: T, _ b: T) -> Bool where T: Equatable', 'func areEqual<T>(_ a: T, _ b: T) -> Bool where T: Equatable',
 50, 10, now()),

-- 82. actors
(gen_random_uuid(),
 'Actor Declaration', 'Declaración de Actor',
 'Define an actor BankAccount with var balance: Double = 0 and a method deposit(_ amount: Double). Access it asynchronously inside a Task and print the balance after depositing 100.',
 'Define un actor BankAccount con var balance: Double = 0 y un método deposit(_ amount: Double). Accédelo asincrónicamente dentro de un Task e imprime el balance después de depositar 100.',
 'swift', 4, 'actors',
 '___ BankAccount {\n    var balance: Double = 0\n    func deposit(_ amount: Double) {\n        balance += amount\n    }\n}\nTask {\n    let account = BankAccount()\n    await account.deposit(100)\n    print(await account.balance)\n}',
 '100.0',
 3,
 'Actors provide data-race safety for shared mutable state in concurrent code.', 'Los actores proporcionan seguridad frente a condiciones de carrera para el estado mutable compartido en código concurrente.',
 'Declare an actor using the "actor" keyword instead of class or struct.', 'Declara un actor usando la palabra clave "actor" en lugar de class o struct.',
 'actor BankAccount', 'actor BankAccount',
 50, 10, now()),

-- 83. swiftui-basics
(gen_random_uuid(),
 'SwiftUI Text View', 'Vista Text en SwiftUI',
 'Create a SwiftUI View struct HelloView that displays a Text saying "Hello, SwiftUI!" with a large title font modifier.',
 'Crea una Vista SwiftUI struct HelloView que muestre un Text que diga "Hello, SwiftUI!" con un modificador de fuente large title.',
 'swift', 4, 'swiftui',
 'import SwiftUI\nstruct HelloView: View {\n    var body: some View {\n        ___(\"Hello, SwiftUI!\")\n            .font(.largeTitle)\n    }\n}',
 'Hello, SwiftUI!',
 3,
 'The basic text display component in SwiftUI is Text.', 'El componente básico de visualización de texto en SwiftUI es Text.',
 'Text takes a string literal and displays it.', 'Text toma un literal de cadena y lo muestra.',
 'Text("Hello, SwiftUI!")', 'Text("Hello, SwiftUI!")',
 50, 10, now()),

-- 84. swiftui-basics
(gen_random_uuid(),
 'SwiftUI State Property', 'Propiedad State en SwiftUI',
 'Create a SwiftUI view CounterView with a @State var count = 0 and a Button that increments count on tap. The button label shows the current count.',
 'Crea una vista SwiftUI CounterView con @State var count = 0 y un Button que incremente count al tocar. La etiqueta del botón muestra el conteo actual.',
 'swift', 4, 'swiftui',
 'import SwiftUI\nstruct CounterView: View {\n    ___  var count = 0\n    var body: some View {\n        Button("Count: \\(count)") {\n            count += 1\n        }\n    }\n}',
 'Count: 0',
 3,
 '@State is a property wrapper that allows a view to own and mutate local state.', '@State es un property wrapper que permite a una vista poseer y mutar estado local.',
 'Write "@State" before the "var" keyword.', 'Escribe "@State" antes de la palabra clave "var".',
 '@State var count = 0', '@State var count = 0',
 50, 10, now()),

-- 85. result-builders
(gen_random_uuid(),
 'Custom Result Builder', 'Result Builder Personalizado',
 'Define a @resultBuilder struct StringBuilder that combines String components with a newline. Use it in a function buildBlock to join "Line 1" and "Line 2".',
 'Define un @resultBuilder struct StringBuilder que combine componentes String con una nueva línea. Úsalo en una función buildBlock para unir "Line 1" y "Line 2".',
 'swift', 4, 'result-builders',
 '@resultBuilder\nstruct StringBuilder {\n    static func buildBlock(_ components: String...) -> String {\n        components.___(separator: "\\n")\n    }\n}\nfunc build(@StringBuilder _ content: () -> String) -> String {\n    content()\n}\nprint(build {\n    "Line 1"\n    "Line 2"\n})',
 'Line 1\nLine 2',
 3,
 'Join an array of strings with a separator using the joined(separator:) method.', 'Une un array de cadenas con un separador usando el método joined(separator:).',
 'Call .joined(separator: "\\n") on the components array.', 'Llama a .joined(separator: "\\n") sobre el array de components.',
 'components.joined(separator: "\n")', 'components.joined(separator: "\n")',
 50, 10, now()),

-- 86. generics
(gen_random_uuid(),
 'Generic Linked List Node', 'Nodo de Lista Enlazada Genérica',
 'Define a generic class Node<T> with var value: T and var next: Node<T>?. Build a list 1->2->3 and traverse it printing each value.',
 'Define una clase genérica Node<T> con var value: T y var next: Node<T>?. Construye una lista 1->2->3 y recórrela imprimiendo cada valor.',
 'swift', 4, 'generics',
 'class Node<T> {\n    var value: T\n    var next: Node<T>?\n    init(_ value: T) { self.value = value }\n}\nlet n1 = Node(1)\nlet n2 = Node(2)\nlet n3 = Node(3)\nn1.next = n2\nn2.next = n3\nvar current: Node<Int>? = n1\nwhile let node = ___ {\n    print(node.value)\n    current = node.next\n}',
 '1\n2\n3',
 3,
 'Use optional binding in the while condition to safely unwrap "current".', 'Usa enlace de opcionales en la condición while para desenvolver "current" de forma segura.',
 'Write "while let node = current" to unwrap the optional.', 'Escribe "while let node = current" para desenvolver el optional.',
 'while let node = current', 'while let node = current',
 50, 10, now()),

-- 87. protocols
(gen_random_uuid(),
 'Hashable Conformance', 'Conformidad con Hashable',
 'Make struct Point(x: Int, y: Int) conform to Hashable so it can be used as a Dictionary key. Create a dict [Point(1,2): "origin"] and print the value.',
 'Haz que struct Point(x: Int, y: Int) conforme a Hashable para que pueda usarse como clave de Diccionario. Crea un dict [Point(1,2): "origin"] e imprime el valor.',
 'swift', 4, 'protocols',
 'struct Point: Hashable {\n    let x: Int, y: Int\n}\nlet dict = [Point(x:1, y:2): "origin"]\nprint(dict[___(x:1, y:2)])',
 'Optional("origin")',
 3,
 'Structs conforming to Hashable with Hashable stored properties get synthesis automatically.', 'Las estructuras que conforman Hashable con propiedades almacenadas Hashable obtienen síntesis automáticamente.',
 'Access the dictionary with a Point key.', 'Accede al diccionario con una clave Point.',
 'dict[Point(x:1, y:2)]', 'dict[Point(x:1, y:2)]',
 50, 10, now()),

-- 88. memory-management
(gen_random_uuid(),
 'Weak Reference to Avoid Retain Cycle', 'Referencia Débil para Evitar Ciclo de Retención',
 'Define classes Person and Apartment where Person has a var apartment: Apartment? and Apartment has a weak var tenant: Person?. Create both and assign them. Print tenant name after breaking the optional chain.',
 'Define las clases Person y Apartment donde Person tiene var apartment: Apartment? y Apartment tiene weak var tenant: Person?. Crea ambas y asígnalas. Imprime el nombre del tenant después de romper la cadena opcional.',
 'swift', 4, 'memory-management',
 'class Person {\n    let name: String\n    var apartment: Apartment?\n    init(name: String) { self.name = name }\n}\nclass Apartment {\n    ___ var tenant: Person?\n}\nlet alice = Person(name: "Alice")\nlet apt = Apartment()\napt.tenant = alice\nalice.apartment = apt\nprint(apt.tenant?.name)',
 'Optional("Alice")',
 3,
 'Use "weak" for references that should not prevent deallocation.', 'Usa "weak" para referencias que no deben impedir la desasignación.',
 'Place "weak" before "var" on the tenant property.', 'Coloca "weak" antes de "var" en la propiedad tenant.',
 'weak var tenant: Person?', 'weak var tenant: Person?',
 50, 10, now()),

-- 89. pattern-matching
(gen_random_uuid(),
 'if case Pattern Matching', 'Coincidencia de Patrón con if case',
 'Given enum Response { case success(Int), failure(String) }, use "if case" to extract and print the value from Response.success(200).',
 'Dado enum Response { case success(Int), failure(String) }, usa "if case" para extraer e imprimir el valor de Response.success(200).',
 'swift', 4, 'pattern-matching',
 'enum Response { case success(Int), failure(String) }\nlet r = Response.success(200)\n___ case .success(let code) = r {\n    print("Status: \\(code)")\n}',
 'Status: 200',
 3,
 '"if case" is used for pattern matching without a full switch statement.', '"if case" se usa para coincidencia de patrones sin una sentencia switch completa.',
 'Start with "if case".', 'Empieza con "if case".',
 'if case .success(let code) = r', 'if case .success(let code) = r',
 50, 10, now()),

-- 90. swiftui-basics
(gen_random_uuid(),
 'SwiftUI Binding', 'Binding en SwiftUI',
 'Create a parent view that passes @State var text to a child view TextField via a @Binding. The child renders TextField("Enter", text: $text).',
 'Crea una vista padre que pase @State var text a una vista hija TextField via @Binding. El hijo renderiza TextField("Enter", text: $text).',
 'swift', 4, 'swiftui',
 'import SwiftUI\nstruct ChildView: View {\n    ___ var text: String\n    var body: some View {\n        TextField("Enter", text: $text)\n    }\n}\nstruct ParentView: View {\n    @State var text = ""\n    var body: some View {\n        ChildView(text: $text)\n    }\n}',
 '',
 3,
 '@Binding creates a two-way connection between a child view and a parent''s @State.', '@Binding crea una conexión bidireccional entre una vista hija y el @State del padre.',
 'Replace the blank with "@Binding".', 'Reemplaza el espacio en blanco con "@Binding".',
 '@Binding var text: String', '@Binding var text: String',
 50, 10, now()),

-- ============================================================
-- DIFFICULTY 5 — 10 exercises (points=100, penalty=10)
-- ============================================================

-- 91. generics
(gen_random_uuid(),
 'Generic Binary Tree', 'Árbol Binario Genérico',
 'Implement a generic indirect enum BinaryTree<T: Comparable> with cases empty and node(BinaryTree<T>, T, BinaryTree<T>). Write an insert method and collect sorted values via inorder traversal. Insert 5, 3, 7 and print inorder result.',
 'Implementa un enum indirecto genérico BinaryTree<T: Comparable> con casos empty y node(BinaryTree<T>, T, BinaryTree<T>). Escribe un método insert y recoge los valores ordenados mediante recorrido inorder. Inserta 5, 3, 7 e imprime el resultado inorder.',
 'swift', 5, 'generics',
 'indirect enum BinaryTree<T: Comparable> {\n    case empty\n    case node(BinaryTree<T>, T, BinaryTree<T>)\n    func insert(_ val: T) -> BinaryTree<T> {\n        switch self {\n        case .empty: return .node(.empty, val, .empty)\n        case .node(let l, let v, let r):\n            if val < v { return .node(l.insert(val), v, r) }\n            if val > v { return .node(l, v, r.insert(val)) }\n            return self\n        }\n    }\n    func inorder() -> [T] {\n        switch self {\n        case .empty: return []\n        case .node(let l, let v, let r): return ___.inorder() + [v] + r.inorder()\n        }\n    }\n}\nvar t = BinaryTree<Int>.empty\nt = t.insert(5); t = t.insert(3); t = t.insert(7)\nprint(t.inorder())',
 '[3, 5, 7]',
 3,
 'The inorder traversal visits left subtree first, then the current node, then right.', 'El recorrido inorder visita primero el subárbol izquierdo, luego el nodo actual, luego el derecho.',
 'Use "l" (the left subtree) for the first inorder() call.', 'Usa "l" (el subárbol izquierdo) para la primera llamada a inorder().',
 'return l.inorder() + [v] + r.inorder()', 'return l.inorder() + [v] + r.inorder()',
 100, 10, now()),

-- 92. async-await
(gen_random_uuid(),
 'Task Group', 'Grupo de Tareas',
 'Use withTaskGroup to fetch "A", "B", "C" concurrently and collect results in an array. Print the sorted results.',
 'Usa withTaskGroup para obtener "A", "B", "C" concurrentemente y recoge los resultados en un array. Imprime los resultados ordenados.',
 'swift', 5, 'async-await',
 'func fetchItem(_ s: String) async -> String { return s }\nTask {\n    var results: [String] = []\n    await ___(of: String.self) { group in\n        for item in ["A","B","C"] {\n            group.addTask { await fetchItem(item) }\n        }\n        for await r in group { results.append(r) }\n    }\n    print(results.sorted())\n}',
 '["A", "B", "C"]',
 3,
 'withTaskGroup creates a structured concurrency group for parallel child tasks.', 'withTaskGroup crea un grupo de concurrencia estructurada para tareas hijas paralelas.',
 'The function is "withTaskGroup(of:)".', 'La función es "withTaskGroup(of:)".',
 'await withTaskGroup(of: String.self)', 'await withTaskGroup(of: String.self)',
 100, 10, now()),

-- 93. protocols
(gen_random_uuid(),
 'Type Erasure with AnySequence', 'Borrado de Tipo con AnySequence',
 'Write a function makeSequence() -> AnySequence<Int> that wraps [1, 2, 3] in AnySequence to hide the concrete type. Iterate and print.',
 'Escribe una función makeSequence() -> AnySequence<Int> que envuelva [1, 2, 3] en AnySequence para ocultar el tipo concreto. Itera e imprime.',
 'swift', 5, 'protocols',
 'func makeSequence() -> AnySequence<Int> {\n    return ___([ 1, 2, 3 ])\n}\nfor n in makeSequence() {\n    print(n)\n}',
 '1\n2\n3',
 3,
 'AnySequence is a type-erasing wrapper for Sequence implementations.', 'AnySequence es un envoltorio que borra el tipo para implementaciones de Sequence.',
 'Wrap the array with AnySequence().', 'Envuelve el array con AnySequence().',
 'return AnySequence([1, 2, 3])', 'return AnySequence([1, 2, 3])',
 100, 10, now()),

-- 94. property-wrappers
(gen_random_uuid(),
 'Property Wrapper with Projected Value', 'Property Wrapper con Valor Proyectado',
 'Define @propertyWrapper struct Tracked<T> that logs when value changes. It has a projectedValue: Int counting set calls. Use $score to print how many times score was set.',
 'Define @propertyWrapper struct Tracked<T> que registre cuando el valor cambie. Tiene un projectedValue: Int que cuenta las llamadas set. Usa $score para imprimir cuántas veces se estableció score.',
 'swift', 5, 'property-wrappers',
 '@propertyWrapper\nstruct Tracked<T> {\n    private var value: T\n    private(set) var projectedValue: Int = 0\n    var wrappedValue: T {\n        get { value }\n        set { value = newValue; ___ += 1 }\n    }\n    init(wrappedValue: T) { self.value = wrappedValue }\n}\nstruct Game {\n    @Tracked var score: Int = 0\n}\nvar g = Game()\ng.score = 10\ng.score = 20\nprint(g.$score)',
 '2',
 3,
 'The projectedValue counter should increment every time wrappedValue is set.', 'El contador projectedValue debe incrementarse cada vez que wrappedValue se establece.',
 'Increment projectedValue inside the setter using projectedValue += 1.', 'Incrementa projectedValue dentro del setter usando projectedValue += 1.',
 'projectedValue += 1', 'projectedValue += 1',
 100, 10, now()),

-- 95. advanced-closures
(gen_random_uuid(),
 'Memoization with Closures', 'Memoización con Closures',
 'Write a function memoize<T: Hashable, U>(_ fn: @escaping (T) -> U) -> (T) -> U that caches results in a dictionary. Memoize a fibonacci function and call fib(10).',
 'Escribe una función memoize<T: Hashable, U>(_ fn: @escaping (T) -> U) -> (T) -> U que almacene resultados en un diccionario. Memoiza una función fibonacci y llama fib(10).',
 'swift', 5, 'closures',
 'func memoize<T: Hashable, U>(_ fn: @escaping (T) -> U) -> (T) -> U {\n    var cache: [T: U] = [:]\n    return { input in\n        if let cached = cache[input] { return cached }\n        let result = fn(___)\n        cache[input] = result\n        return result\n    }\n}\nvar fib: (Int) -> Int = { _ in 0 }\nfib = memoize { n in n < 2 ? n : fib(n-1) + fib(n-2) }\nprint(fib(10))',
 '55',
 3,
 'The cached function is called with the original input when no cache hit is found.', 'La función en caché se llama con la entrada original cuando no hay un acierto en caché.',
 'Pass "input" to fn().', 'Pasa "input" a fn().',
 'let result = fn(input)', 'let result = fn(input)',
 100, 10, now()),

-- 96. codable
(gen_random_uuid(),
 'Custom Encode and Decode', 'Codificación y Decodificación Personalizadas',
 'Implement a struct Color: Codable with r, g, b Int properties that encodes to/from a single hex string like "FF8800".',
 'Implementa una estructura Color: Codable con propiedades r, g, b Int que codifica hacia/desde una cadena hexadecimal como "FF8800".',
 'swift', 5, 'codable',
 'import Foundation\nstruct Color: Codable {\n    let r, g, b: Int\n    init(r: Int, g: Int, b: Int) { self.r=r; self.g=g; self.b=b }\n    func encode(to encoder: Encoder) throws {\n        var c = encoder.singleValueContainer()\n        try c.encode(String(format: "%02X%02X%02X", r, g, b))\n    }\n    init(from decoder: Decoder) throws {\n        let c = try decoder.singleValueContainer()\n        let hex = try c.decode(String.self)\n        r = Int(hex.prefix(2), radix: 16) ?? 0\n        g = Int(hex.dropFirst(2).___(_:2), radix: 16) ?? 0\n        b = Int(hex.suffix(2), radix: 16) ?? 0\n    }\n}\nlet encoded = try! JSONEncoder().encode(Color(r:255,g:136,b:0))\nprint(String(data: encoded, encoding: .utf8)!)',
 '"FF8800"',
 3,
 'String slicing: to get the middle 2 characters, drop the first 2 then take a prefix of 2.', 'División de cadenas: para obtener los 2 caracteres del medio, descarta los primeros 2 y luego toma un prefijo de 2.',
 'Use prefix(_:) after dropFirst(2).', 'Usa prefix(_:) después de dropFirst(2).',
 'hex.dropFirst(2).prefix(2)', 'hex.dropFirst(2).prefix(2)',
 100, 10, now()),

-- 97. advanced-protocols
(gen_random_uuid(),
 'Opaque Return Type some Protocol', 'Tipo de Retorno Opaco some Protocol',
 'Write a function makeShape() -> some Shape where Shape has area: Double. Return a concrete Circle(radius: 5). Print makeShape().area rounded to 2 decimal places.',
 'Escribe una función makeShape() -> some Shape donde Shape tiene area: Double. Devuelve un Circle(radius: 5) concreto. Imprime makeShape().area redondeado a 2 decimales.',
 'swift', 5, 'protocols',
 'protocol Shape { var area: Double { get } }\nstruct Circle: Shape {\n    let radius: Double\n    var area: Double { Double.pi * radius * radius }\n}\nfunc makeShape() -> ___ Shape {\n    return Circle(radius: 5)\n}\nlet a = makeShape().area\nprint(String(format: "%.2f", a))',
 '78.54',
 3,
 'Opaque return types use the "some" keyword, hiding the concrete type from the caller.', 'Los tipos de retorno opacos usan la palabra clave "some", ocultando el tipo concreto del llamador.',
 'Write "some" before the protocol name in the return type.', 'Escribe "some" antes del nombre del protocolo en el tipo de retorno.',
 'func makeShape() -> some Shape', 'func makeShape() -> some Shape',
 100, 10, now()),

-- 98. async-await
(gen_random_uuid(),
 'MainActor Isolation', 'Aislamiento MainActor',
 'Mark a class UIUpdater with @MainActor to ensure all its methods run on the main thread. Write an async func update() that prints "Updated on main". Call it inside a Task.',
 'Marca una clase UIUpdater con @MainActor para asegurar que todos sus métodos se ejecuten en el hilo principal. Escribe una func async update() que imprima "Updated on main". Llámala dentro de un Task.',
 'swift', 5, 'async-await',
 '___ class UIUpdater {\n    func update() async {\n        print("Updated on main")\n    }\n}\nTask {\n    let updater = UIUpdater()\n    await updater.update()\n}',
 'Updated on main',
 3,
 '@MainActor is a global actor that serializes access to the main dispatch queue.', '@MainActor es un actor global que serializa el acceso a la cola de despacho principal.',
 'Place @MainActor before the class keyword.', 'Coloca @MainActor antes de la palabra clave class.',
 '@MainActor class UIUpdater', '@MainActor class UIUpdater',
 100, 10, now()),

-- 99. advanced-generics
(gen_random_uuid(),
 'Conditional Conformance', 'Conformidad Condicional',
 'Extend Array to conform to Equatable when Element is Equatable. Write extension Array: Equatable where Element: Equatable with == comparing element-by-element. Test [[1,2] == [1,2]].',
 'Extiende Array para conformar Equatable cuando Element sea Equatable. Escribe extension Array: Equatable where Element: Equatable con == comparando elemento a elemento. Prueba [1,2] == [1,2].',
 'swift', 5, 'generics',
 'extension Array: Equatable where Element: Equatable {\n    public static func == (lhs: [Element], rhs: [Element]) -> Bool {\n        guard lhs.count == rhs.count else { return false }\n        return ___(lhs, rhs).allSatisfy { $0 == $1 }\n    }\n}\nprint([1,2] == [1,2])',
 'true',
 3,
 'Use zip to pair corresponding elements from both arrays for comparison.', 'Usa zip para emparejar los elementos correspondientes de ambos arrays para la comparación.',
 'zip(lhs, rhs) produces pairs of corresponding elements.', 'zip(lhs, rhs) produce pares de elementos correspondientes.',
 'return zip(lhs, rhs).allSatisfy { $0 == $1 }', 'return zip(lhs, rhs).allSatisfy { $0 == $1 }',
 100, 10, now()),

-- 100. advanced-architecture
(gen_random_uuid(),
 'Dependency Injection with Protocols', 'Inyección de Dependencias con Protocolos',
 'Define a protocol NetworkService with func fetchUser() -> String. Implement MockNetworkService returning "MockUser". Inject it into a class UserRepository via init. Print repo.getUser().',
 'Define un protocolo NetworkService con func fetchUser() -> String. Implementa MockNetworkService devolviendo "MockUser". Inyéctalo en una clase UserRepository via init. Imprime repo.getUser().',
 'swift', 5, 'architecture',
 'protocol NetworkService {\n    func fetchUser() -> String\n}\nstruct MockNetworkService: NetworkService {\n    func fetchUser() -> String { return "MockUser" }\n}\nclass UserRepository {\n    private let service: ___\n    init(service: NetworkService) { self.service = service }\n    func getUser() -> String { return service.fetchUser() }\n}\nlet repo = UserRepository(service: MockNetworkService())\nprint(repo.getUser())',
 'MockUser',
 3,
 'The stored service property should be typed as the protocol, not the concrete type.', 'La propiedad service almacenada debe tener el tipo del protocolo, no el tipo concreto.',
 'Declare "private let service: NetworkService".', 'Declara "private let service: NetworkService".',
 'private let service: NetworkService', 'private let service: NetworkService',
 100, 10, now())

ON CONFLICT DO NOTHING;

COMMIT;
