-- 055_exercises_kotlin.sql
-- 100 Kotlin exercises, bilingual EN+ES
-- Distribution: diff1=25, diff2=25, diff3=25, diff4=15, diff5=10
-- Points: 10/20/30/50/100 | Penalty: 3/3/5/10/10
-- Focus: null safety, data classes, sealed classes, extension functions,
--        coroutines, when expressions, smart casts, companion objects,
--        lambdas, scope functions (let/run/apply/also), collections

BEGIN;

INSERT INTO exercises (
  id, title_en, title_es,
  description_en, description_es,
  language, difficulty, category,
  starter_code, expected_output,
  hint_count,
  hint_1_en, hint_1_es,
  hint_2_en, hint_2_es,
  hint_3_en, hint_3_es,
  points, hints_used_penalty,
  created_at
) VALUES

-- ============================================================
-- DIFFICULTY 1 — 25 exercises (points=10, penalty=3)
-- ============================================================

-- 1. basics
(gen_random_uuid(),
 'Hello Kotlin', 'Hola Kotlin',
 'Print "Hello, Kotlin!" to the console.',
 'Imprime "Hello, Kotlin!" en la consola.',
 'kotlin', 1, 'basics',
 'fun main() {\n    // your code\n}',
 'Hello, Kotlin!',
 3,
 'Use println() to print with a newline.', 'Usa println() para imprimir con salto de línea.',
 'Pass the string literal directly to println().', 'Pasa el literal de cadena directamente a println().',
 'println("Hello, Kotlin!")', 'println("Hello, Kotlin!")',
 10, 3, now()),

-- 2. basics
(gen_random_uuid(),
 'Declare a Variable', 'Declarar una Variable',
 'Declare an immutable variable named city with the value "Kotlin City" and print it.',
 'Declara una variable inmutable llamada city con el valor "Kotlin City" e imprímela.',
 'kotlin', 1, 'basics',
 'fun main() {\n    // your code\n}',
 'Kotlin City',
 3,
 'Use the val keyword for immutable variables.', 'Usa la palabra clave val para variables inmutables.',
 'val city = "Kotlin City"', 'val city = "Kotlin City"',
 'Then call println(city).', 'Luego llama a println(city).',
 10, 3, now()),

-- 3. basics
(gen_random_uuid(),
 'Mutable Variable', 'Variable Mutable',
 'Declare a mutable variable score with initial value 0, then set it to 100 and print it.',
 'Declara una variable mutable score con valor inicial 0, luego asígnale 100 e imprímela.',
 'kotlin', 1, 'basics',
 'fun main() {\n    // your code\n}',
 '100',
 3,
 'Use the var keyword for mutable variables.', 'Usa la palabra clave var para variables mutables.',
 'Reassign with score = 100 after declaring it.', 'Reasigna con score = 100 después de declararla.',
 'var score = 0; score = 100; println(score)', 'var score = 0; score = 100; println(score)',
 10, 3, now()),

-- 4. basics
(gen_random_uuid(),
 'String Template', 'Plantilla de Cadena',
 'Declare a variable name = "World" and print "Hello, World!" using a string template.',
 'Declara una variable name = "World" e imprime "Hello, World!" usando una plantilla de cadena.',
 'kotlin', 1, 'basics',
 'fun main() {\n    val name = "World"\n    // print using string template\n}',
 'Hello, World!',
 3,
 'String templates use the $ prefix to embed variables.', 'Las plantillas de cadena usan el prefijo $ para insertar variables.',
 'println("Hello, $name!")', 'println("Hello, $name!")',
 'The $ sign is placed directly before the variable name inside the string.', 'El signo $ se coloca directamente antes del nombre de la variable dentro de la cadena.',
 10, 3, now()),

-- 5. math
(gen_random_uuid(),
 'Add Two Numbers', 'Sumar Dos Números',
 'Add 15 and 27 and print the result.',
 'Suma 15 y 27 e imprime el resultado.',
 'kotlin', 1, 'math',
 'fun main() {\n    // your code\n}',
 '42',
 3,
 'Declare a val for the sum using the + operator.', 'Declara un val para la suma usando el operador +.',
 'val result = 15 + 27', 'val result = 15 + 27',
 'Then println(result).', 'Luego println(result).',
 10, 3, now()),

-- 6. math
(gen_random_uuid(),
 'Integer Division', 'División Entera',
 'Divide 20 by 4 and print the result.',
 'Divide 20 entre 4 e imprime el resultado.',
 'kotlin', 1, 'math',
 'fun main() {\n    // your code\n}',
 '5',
 3,
 'Use the / operator between two Int literals.', 'Usa el operador / entre dos literales Int.',
 'Integer division in Kotlin truncates the decimal part.', 'La división entera en Kotlin trunca la parte decimal.',
 'println(20 / 4)', 'println(20 / 4)',
 10, 3, now()),

-- 7. math
(gen_random_uuid(),
 'Modulo Operator', 'Operador Módulo',
 'Find the remainder of 17 divided by 5 and print it.',
 'Encuentra el resto de 17 dividido entre 5 e imprímelo.',
 'kotlin', 1, 'math',
 'fun main() {\n    // your code\n}',
 '2',
 3,
 'Use the % operator for remainder.', 'Usa el operador % para el resto.',
 '17 % 5 gives the remainder after division.', '17 % 5 da el resto después de la división.',
 'println(17 % 5)', 'println(17 % 5)',
 10, 3, now()),

-- 8. basics
(gen_random_uuid(),
 'Type Inference', 'Inferencia de Tipos',
 'Declare val x = 42 and val y = 3.14, then print both on separate lines.',
 'Declara val x = 42 y val y = 3.14, luego imprime ambos en líneas separadas.',
 'kotlin', 1, 'basics',
 'fun main() {\n    // your code\n}',
 '42\n3.14',
 3,
 'Kotlin infers the type automatically from the assigned value.', 'Kotlin infiere el tipo automáticamente del valor asignado.',
 'Use two separate println() calls.', 'Usa dos llamadas a println() separadas.',
 'val x = 42; val y = 3.14; println(x); println(y)', 'val x = 42; val y = 3.14; println(x); println(y)',
 10, 3, now()),

-- 9. control-flow
(gen_random_uuid(),
 'If Expression', 'Expresión If',
 'Declare val n = 10. If n is greater than 5, print "big", otherwise print "small".',
 'Declara val n = 10. Si n es mayor que 5, imprime "big", si no imprime "small".',
 'kotlin', 1, 'control-flow',
 'fun main() {\n    val n = 10\n    // your code\n}',
 'big',
 3,
 'Use an if/else expression or statement.', 'Usa una expresión o sentencia if/else.',
 'Compare n > 5 inside the if condition.', 'Compara n > 5 dentro de la condición if.',
 'if (n > 5) println("big") else println("small")', 'if (n > 5) println("big") else println("small")',
 10, 3, now()),

-- 10. control-flow
(gen_random_uuid(),
 'For Loop Range', 'Bucle For con Rango',
 'Print numbers from 1 to 5 each on a new line using a for loop.',
 'Imprime los números del 1 al 5, cada uno en una nueva línea, usando un bucle for.',
 'kotlin', 1, 'control-flow',
 'fun main() {\n    // your code\n}',
 '1\n2\n3\n4\n5',
 3,
 'Use a for loop with the .. range operator.', 'Usa un bucle for con el operador de rango ..',
 'for (i in 1..5)', 'for (i in 1..5)',
 'Then println(i) inside the loop body.', 'Luego println(i) dentro del cuerpo del bucle.',
 10, 3, now()),

-- 11. control-flow
(gen_random_uuid(),
 'While Loop', 'Bucle While',
 'Use a while loop to print numbers 1 to 4.',
 'Usa un bucle while para imprimir los números del 1 al 4.',
 'kotlin', 1, 'control-flow',
 'fun main() {\n    // your code\n}',
 '1\n2\n3\n4',
 3,
 'Declare var i = 1 and loop while i <= 4.', 'Declara var i = 1 y repite mientras i <= 4.',
 'Increment i with i++ inside the loop.', 'Incrementa i con i++ dentro del bucle.',
 'var i = 1; while (i <= 4) { println(i); i++ }', 'var i = 1; while (i <= 4) { println(i); i++ }',
 10, 3, now()),

-- 12. strings
(gen_random_uuid(),
 'String Length', 'Longitud de Cadena',
 'Declare val word = "Kotlin" and print its length.',
 'Declara val word = "Kotlin" e imprime su longitud.',
 'kotlin', 1, 'strings',
 'fun main() {\n    val word = "Kotlin"\n    // your code\n}',
 '6',
 3,
 'Use the .length property on a String.', 'Usa la propiedad .length en una String.',
 'println(word.length)', 'println(word.length)',
 '"Kotlin" has 6 characters.', '"Kotlin" tiene 6 caracteres.',
 10, 3, now()),

-- 13. strings
(gen_random_uuid(),
 'String Uppercase', 'Cadena en Mayúsculas',
 'Declare val text = "hello" and print it converted to uppercase.',
 'Declara val text = "hello" e imprímela convertida a mayúsculas.',
 'kotlin', 1, 'strings',
 'fun main() {\n    val text = "hello"\n    // your code\n}',
 'HELLO',
 3,
 'Use the .uppercase() function on the string.', 'Usa la función .uppercase() en la cadena.',
 'println(text.uppercase())', 'println(text.uppercase())',
 'In older Kotlin versions this was .toUpperCase().', 'En versiones antiguas de Kotlin era .toUpperCase().',
 10, 3, now()),

-- 14. strings
(gen_random_uuid(),
 'String Concatenation', 'Concatenación de Cadenas',
 'Concatenate "Kot" and "lin" with the + operator and print the result.',
 'Concatena "Kot" y "lin" con el operador + e imprime el resultado.',
 'kotlin', 1, 'strings',
 'fun main() {\n    // your code\n}',
 'Kotlin',
 3,
 'Use the + operator between two string literals.', 'Usa el operador + entre dos literales de cadena.',
 'val result = "Kot" + "lin"', 'val result = "Kot" + "lin"',
 'Then println(result).', 'Luego println(result).',
 10, 3, now()),

-- 15. collections
(gen_random_uuid(),
 'List of Integers', 'Lista de Enteros',
 'Create a list of integers [1, 2, 3, 4, 5] and print its size.',
 'Crea una lista de enteros [1, 2, 3, 4, 5] e imprime su tamaño.',
 'kotlin', 1, 'collections',
 'fun main() {\n    // your code\n}',
 '5',
 3,
 'Use listOf() to create an immutable list.', 'Usa listOf() para crear una lista inmutable.',
 'Access .size on the list to get the number of elements.', 'Accede a .size en la lista para obtener el número de elementos.',
 'val nums = listOf(1,2,3,4,5); println(nums.size)', 'val nums = listOf(1,2,3,4,5); println(nums.size)',
 10, 3, now()),

-- 16. collections
(gen_random_uuid(),
 'Access List Element', 'Acceder a Elemento de Lista',
 'Create val fruits = listOf("apple","banana","cherry") and print the second element.',
 'Crea val fruits = listOf("apple","banana","cherry") e imprime el segundo elemento.',
 'kotlin', 1, 'collections',
 'fun main() {\n    val fruits = listOf("apple", "banana", "cherry")\n    // your code\n}',
 'banana',
 3,
 'Lists are zero-indexed in Kotlin.', 'Las listas están indexadas desde cero en Kotlin.',
 'Use fruits[1] to access the second element.', 'Usa fruits[1] para acceder al segundo elemento.',
 'println(fruits[1])', 'println(fruits[1])',
 10, 3, now()),

-- 17. functions
(gen_random_uuid(),
 'Simple Function', 'Función Simple',
 'Define a function greet() that prints "Hi from Kotlin!" and call it from main.',
 'Define una función greet() que imprima "Hi from Kotlin!" y llámala desde main.',
 'kotlin', 1, 'functions',
 'fun main() {\n    // call greet()\n}\n\n// define greet here',
 'Hi from Kotlin!',
 3,
 'Declare a function with the fun keyword.', 'Declara una función con la palabra clave fun.',
 'fun greet() { println("Hi from Kotlin!") }', 'fun greet() { println("Hi from Kotlin!") }',
 'Call greet() inside main().', 'Llama a greet() dentro de main().',
 10, 3, now()),

-- 18. functions
(gen_random_uuid(),
 'Function with Parameter', 'Función con Parámetro',
 'Define a function sayHello(name: String) that prints "Hello, <name>!" and call it with "Alice".',
 'Define una función sayHello(name: String) que imprima "Hello, <name>!" y llámala con "Alice".',
 'kotlin', 1, 'functions',
 'fun main() {\n    // call sayHello\n}\n\n// define sayHello here',
 'Hello, Alice!',
 3,
 'Parameters in Kotlin are declared as name: Type.', 'Los parámetros en Kotlin se declaran como name: Type.',
 'Use a string template: "Hello, $name!"', 'Usa una plantilla de cadena: "Hello, $name!"',
 'fun sayHello(name: String) { println("Hello, $name!") }', 'fun sayHello(name: String) { println("Hello, $name!") }',
 10, 3, now()),

-- 19. functions
(gen_random_uuid(),
 'Function Return Value', 'Función con Valor de Retorno',
 'Define a function add(a: Int, b: Int): Int that returns their sum. Print add(3, 4).',
 'Define una función add(a: Int, b: Int): Int que retorne la suma. Imprime add(3, 4).',
 'kotlin', 1, 'functions',
 'fun main() {\n    println(add(3, 4))\n}\n\n// define add here',
 '7',
 3,
 'Declare the return type after the parameter list with : Int.', 'Declara el tipo de retorno después de los parámetros con : Int.',
 'Use the return keyword inside the function.', 'Usa la palabra clave return dentro de la función.',
 'fun add(a: Int, b: Int): Int = a + b', 'fun add(a: Int, b: Int): Int = a + b',
 10, 3, now()),

-- 20. null-safety
(gen_random_uuid(),
 'Nullable Variable', 'Variable Anulable',
 'Declare a nullable String variable name = null, then print it.',
 'Declara una variable String anulable name = null, luego imprímela.',
 'kotlin', 1, 'null-safety',
 'fun main() {\n    // your code\n}',
 'null',
 3,
 'Append ? to the type to make it nullable: String?.', 'Añade ? al tipo para hacerlo anulable: String?.',
 'var name: String? = null', 'var name: String? = null',
 'println(name) will print null.', 'println(name) imprimirá null.',
 10, 3, now()),

-- 21. null-safety
(gen_random_uuid(),
 'Elvis Operator Basic', 'Operador Elvis Básico',
 'Declare val name: String? = null. Print name using the Elvis operator with default "Guest".',
 'Declara val name: String? = null. Imprime name usando el operador Elvis con valor por defecto "Guest".',
 'kotlin', 1, 'null-safety',
 'fun main() {\n    val name: String? = null\n    // your code\n}',
 'Guest',
 3,
 'The Elvis operator ?: provides a default when the left side is null.', 'El operador Elvis ?: provee un valor por defecto cuando el lado izquierdo es null.',
 'println(name ?: "Guest")', 'println(name ?: "Guest")',
 'If name is null, "Guest" is used instead.', 'Si name es null, se usa "Guest" en su lugar.',
 10, 3, now()),

-- 22. when
(gen_random_uuid(),
 'When Expression Basic', 'Expresión When Básica',
 'Declare val day = 3. Use a when expression to print "Wednesday" when day is 3.',
 'Declara val day = 3. Usa una expresión when para imprimir "Wednesday" cuando day sea 3.',
 'kotlin', 1, 'when',
 'fun main() {\n    val day = 3\n    // your code\n}',
 'Wednesday',
 3,
 'Use when(day) { ... } to branch on the value.', 'Usa when(day) { ... } para ramificar según el valor.',
 '3 -> println("Wednesday")', '3 -> println("Wednesday")',
 'Add an else branch as a default case.', 'Añade una rama else como caso por defecto.',
 10, 3, now()),

-- 23. collections
(gen_random_uuid(),
 'MutableList Add', 'Agregar a MutableList',
 'Create a mutableListOf("a","b"), add "c" to it, and print the list.',
 'Crea un mutableListOf("a","b"), agrega "c" y imprime la lista.',
 'kotlin', 1, 'collections',
 'fun main() {\n    // your code\n}',
 '[a, b, c]',
 3,
 'Use mutableListOf() to create a list you can modify.', 'Usa mutableListOf() para crear una lista que puedes modificar.',
 'Call .add("c") on the mutable list.', 'Llama a .add("c") en la lista mutable.',
 'val list = mutableListOf("a","b"); list.add("c"); println(list)', 'val list = mutableListOf("a","b"); list.add("c"); println(list)',
 10, 3, now()),

-- 24. basics
(gen_random_uuid(),
 'Boolean Logic', 'Lógica Booleana',
 'Declare val a = true and val b = false. Print the result of a && b and a || b on separate lines.',
 'Declara val a = true y val b = false. Imprime el resultado de a && b y a || b en líneas separadas.',
 'kotlin', 1, 'basics',
 'fun main() {\n    val a = true\n    val b = false\n    // your code\n}',
 'false\ntrue',
 3,
 '&& is logical AND, || is logical OR.', '&& es AND lógico, || es OR lógico.',
 'println(a && b) then println(a || b).', 'println(a && b) luego println(a || b).',
 'true AND false = false; true OR false = true', 'true AND false = false; true OR false = true',
 10, 3, now()),

-- 25. strings
(gen_random_uuid(),
 'String Contains', 'Cadena Contiene',
 'Declare val sentence = "Kotlin is fun". Print whether it contains "fun".',
 'Declara val sentence = "Kotlin is fun". Imprime si contiene "fun".',
 'kotlin', 1, 'strings',
 'fun main() {\n    val sentence = "Kotlin is fun"\n    // your code\n}',
 'true',
 3,
 'Use the .contains() function on a String.', 'Usa la función .contains() en una String.',
 'println(sentence.contains("fun"))', 'println(sentence.contains("fun"))',
 'It returns a Boolean: true or false.', 'Devuelve un Boolean: true o false.',
 10, 3, now()),

-- ============================================================
-- DIFFICULTY 2 — 25 exercises (points=20, penalty=3)
-- ============================================================

-- 26. null-safety
(gen_random_uuid(),
 'Safe Call Operator', 'Operador de Llamada Segura',
 'Declare val name: String? = "Kotlin". Use the safe call operator to print the length.',
 'Declara val name: String? = "Kotlin". Usa el operador de llamada segura para imprimir la longitud.',
 'kotlin', 2, 'null-safety',
 'fun main() {\n    val name: String? = "Kotlin"\n    // your code\n}',
 '6',
 3,
 'The safe call operator ?. only calls the method if the value is not null.', 'El operador ?. solo llama al método si el valor no es null.',
 'println(name?.length)', 'println(name?.length)',
 'If name were null this would print null instead of throwing an exception.', 'Si name fuera null esto imprimiría null en lugar de lanzar una excepción.',
 20, 3, now()),

-- 27. null-safety
(gen_random_uuid(),
 'Non-Null Assertion', 'Aserción No Nula',
 'Declare val value: String? = "Hello". Use the !! operator to access its length and print it.',
 'Declara val value: String? = "Hello". Usa el operador !! para acceder a su longitud e imprimirla.',
 'kotlin', 2, 'null-safety',
 'fun main() {\n    val value: String? = "Hello"\n    // your code\n}',
 '5',
 3,
 'The !! operator asserts that the value is not null.', 'El operador !! afirma que el valor no es null.',
 'println(value!!.length)', 'println(value!!.length)',
 'Use !! only when you are certain the value is not null.', 'Usa !! solo cuando estés seguro de que el valor no es null.',
 20, 3, now()),

-- 28. data-classes
(gen_random_uuid(),
 'Simple Data Class', 'Clase de Datos Simple',
 'Create a data class Point(val x: Int, val y: Int). In main, create Point(3, 4) and print it.',
 'Crea una data class Point(val x: Int, val y: Int). En main, crea Point(3, 4) e imprímela.',
 'kotlin', 2, 'data-classes',
 'fun main() {\n    // create and print a Point\n}\n\n// define Point here',
 'Point(x=3, y=4)',
 3,
 'Prefix the class declaration with the data keyword.', 'Prefija la declaración de clase con la palabra clave data.',
 'data class Point(val x: Int, val y: Int)', 'data class Point(val x: Int, val y: Int)',
 'Data classes auto-generate toString() showing field names and values.', 'Las data class generan automáticamente toString() mostrando nombres y valores.',
 20, 3, now()),

-- 29. data-classes
(gen_random_uuid(),
 'Data Class Copy', 'Copia de Data Class',
 'Create data class Person(val name: String, val age: Int). Create Person("Alice", 30), copy it with age = 31, and print the copy.',
 'Crea data class Person(val name: String, val age: Int). Crea Person("Alice", 30), cópiala con age = 31 e imprime la copia.',
 'kotlin', 2, 'data-classes',
 'fun main() {\n    val p = Person("Alice", 30)\n    // copy with age 31 and print\n}\n\ndata class Person(val name: String, val age: Int)',
 'Person(name=Alice, age=31)',
 3,
 'Data classes have a built-in copy() function.', 'Las data class tienen una función copy() integrada.',
 'Use p.copy(age = 31) to create a modified copy.', 'Usa p.copy(age = 31) para crear una copia modificada.',
 'val p2 = p.copy(age = 31); println(p2)', 'val p2 = p.copy(age = 31); println(p2)',
 20, 3, now()),

-- 30. when
(gen_random_uuid(),
 'When with Ranges', 'When con Rangos',
 'Declare val score = 75. Use when to print "Pass" if score is in 60..100, else print "Fail".',
 'Declara val score = 75. Usa when para imprimir "Pass" si score está en 60..100, si no "Fail".',
 'kotlin', 2, 'when',
 'fun main() {\n    val score = 75\n    // your code\n}',
 'Pass',
 3,
 'In a when expression you can use range checks with in.', 'En una expresión when puedes usar verificaciones de rango con in.',
 'in 60..100 -> println("Pass")', 'in 60..100 -> println("Pass")',
 'Add else -> println("Fail") as the default branch.', 'Añade else -> println("Fail") como rama por defecto.',
 20, 3, now()),

-- 31. when
(gen_random_uuid(),
 'When as Expression', 'When como Expresión',
 'Declare val n = 7. Assign the result of a when expression to a val: "odd" if n % 2 != 0, else "even". Print it.',
 'Declara val n = 7. Asigna el resultado de una expresión when a un val: "odd" si n % 2 != 0, si no "even". Imprímelo.',
 'kotlin', 2, 'when',
 'fun main() {\n    val n = 7\n    // your code\n}',
 'odd',
 3,
 'when can be used as an expression that returns a value.', 'when puede usarse como una expresión que devuelve un valor.',
 'val result = when { n % 2 != 0 -> "odd" else -> "even" }', 'val result = when { n % 2 != 0 -> "odd" else -> "even" }',
 'Then println(result).', 'Luego println(result).',
 20, 3, now()),

-- 32. lambdas
(gen_random_uuid(),
 'Lambda Basics', 'Lambdas Básicos',
 'Declare a lambda val double = { x: Int -> x * 2 } and print double(5).',
 'Declara un lambda val double = { x: Int -> x * 2 } e imprime double(5).',
 'kotlin', 2, 'lambdas',
 'fun main() {\n    // your code\n}',
 '10',
 3,
 'Lambdas in Kotlin are declared inside curly braces { }.', 'Los lambdas en Kotlin se declaran dentro de llaves { }.',
 'The parameter and its type go before the arrow: { x: Int -> ... }', 'El parámetro y su tipo van antes de la flecha: { x: Int -> ... }',
 'val double = { x: Int -> x * 2 }; println(double(5))', 'val double = { x: Int -> x * 2 }; println(double(5))',
 20, 3, now()),

-- 33. collections
(gen_random_uuid(),
 'List map()', 'List map()',
 'Given listOf(1,2,3,4), use map to create a list of squares and print it.',
 'Dado listOf(1,2,3,4), usa map para crear una lista de cuadrados e imprímela.',
 'kotlin', 2, 'collections',
 'fun main() {\n    val nums = listOf(1, 2, 3, 4)\n    // your code\n}',
 '[1, 4, 9, 16]',
 3,
 'Use .map { } on the list with a lambda.', 'Usa .map { } en la lista con un lambda.',
 'Inside the lambda, return it * it (or it.pow(2) does not exist for Int, use it * it).', 'Dentro del lambda, retorna it * it.',
 'println(nums.map { it * it })', 'println(nums.map { it * it })',
 20, 3, now()),

-- 34. collections
(gen_random_uuid(),
 'List filter()', 'List filter()',
 'Given listOf(1,2,3,4,5,6), filter even numbers and print the result.',
 'Dado listOf(1,2,3,4,5,6), filtra los números pares e imprime el resultado.',
 'kotlin', 2, 'collections',
 'fun main() {\n    val nums = listOf(1, 2, 3, 4, 5, 6)\n    // your code\n}',
 '[2, 4, 6]',
 3,
 'Use .filter { } with a predicate lambda.', 'Usa .filter { } con un lambda predicado.',
 'A number is even if it % 2 == 0.', 'Un número es par si it % 2 == 0.',
 'println(nums.filter { it % 2 == 0 })', 'println(nums.filter { it % 2 == 0 })',
 20, 3, now()),

-- 35. collections
(gen_random_uuid(),
 'List forEach()', 'List forEach()',
 'Given listOf("a","b","c"), use forEach to print each element.',
 'Dado listOf("a","b","c"), usa forEach para imprimir cada elemento.',
 'kotlin', 2, 'collections',
 'fun main() {\n    val letters = listOf("a", "b", "c")\n    // your code\n}',
 'a\nb\nc',
 3,
 'Use .forEach { } with a lambda that receives each element as it.', 'Usa .forEach { } con un lambda que recibe cada elemento como it.',
 'letters.forEach { println(it) }', 'letters.forEach { println(it) }',
 'it refers to the current element in the forEach lambda.', 'it se refiere al elemento actual en el lambda forEach.',
 20, 3, now()),

-- 36. extension-functions
(gen_random_uuid(),
 'Extension Function', 'Función de Extensión',
 'Add an extension function square() on Int that returns the number squared. Print 5.square().',
 'Añade una función de extensión square() en Int que retorne el número al cuadrado. Imprime 5.square().',
 'kotlin', 2, 'extension-functions',
 'fun main() {\n    println(5.square())\n}\n\n// define extension here',
 '25',
 3,
 'Extension functions are declared as fun ReceiverType.functionName().', 'Las funciones de extensión se declaran como fun TipoReceptor.nombreFuncion().',
 'fun Int.square(): Int = this * this', 'fun Int.square(): Int = this * this',
 'Inside the extension, this refers to the receiver object.', 'Dentro de la extensión, this se refiere al objeto receptor.',
 20, 3, now()),

-- 37. extension-functions
(gen_random_uuid(),
 'String Extension', 'Extensión de String',
 'Add an extension function isPalindrome() on String. Print "racecar".isPalindrome().',
 'Añade una función de extensión isPalindrome() en String. Imprime "racecar".isPalindrome().',
 'kotlin', 2, 'extension-functions',
 'fun main() {\n    println("racecar".isPalindrome())\n}\n\n// define extension here',
 'true',
 3,
 'A palindrome reads the same forwards and backwards.', 'Un palíndromo se lee igual de adelante hacia atrás y viceversa.',
 'Use this == this.reversed() inside the extension.', 'Usa this == this.reversed() dentro de la extensión.',
 'fun String.isPalindrome(): Boolean = this == this.reversed()', 'fun String.isPalindrome(): Boolean = this == this.reversed()',
 20, 3, now()),

-- 38. scope-functions
(gen_random_uuid(),
 'let Scope Function', 'Función de Alcance let',
 'Declare val name: String? = "Kotlin". Use let to print the uppercased value if not null.',
 'Declara val name: String? = "Kotlin". Usa let para imprimir el valor en mayúsculas si no es null.',
 'kotlin', 2, 'scope-functions',
 'fun main() {\n    val name: String? = "Kotlin"\n    // your code\n}',
 'KOTLIN',
 3,
 'Chain ?. with let so the block only runs when name is not null.', 'Encadena ?. con let para que el bloque solo se ejecute cuando name no sea null.',
 'name?.let { println(it.uppercase()) }', 'name?.let { println(it.uppercase()) }',
 'Inside let, it refers to the non-null value.', 'Dentro de let, it se refiere al valor no nulo.',
 20, 3, now()),

-- 39. scope-functions
(gen_random_uuid(),
 'apply Scope Function', 'Función de Alcance apply',
 'Use apply on a StringBuilder to append "Hello" and " Kotlin", then print the result.',
 'Usa apply en un StringBuilder para agregar "Hello" y " Kotlin", luego imprime el resultado.',
 'kotlin', 2, 'scope-functions',
 'fun main() {\n    // your code\n}',
 'Hello Kotlin',
 3,
 'apply executes a block on the object and returns the object itself.', 'apply ejecuta un bloque sobre el objeto y devuelve el propio objeto.',
 'val sb = StringBuilder().apply { append("Hello"); append(" Kotlin") }', 'val sb = StringBuilder().apply { append("Hello"); append(" Kotlin") }',
 'Then println(sb).', 'Luego println(sb).',
 20, 3, now()),

-- 40. companion-objects
(gen_random_uuid(),
 'Companion Object Constant', 'Constante en Companion Object',
 'Create a class Circle with a companion object that has a constant PI = 3.14. Print Circle.PI.',
 'Crea una clase Circle con un companion object que tenga la constante PI = 3.14. Imprime Circle.PI.',
 'kotlin', 2, 'companion-objects',
 'fun main() {\n    println(Circle.PI)\n}\n\n// define Circle here',
 '3.14',
 3,
 'Declare companion object { } inside the class body.', 'Declara companion object { } dentro del cuerpo de la clase.',
 'const val PI = 3.14 inside the companion object.', 'const val PI = 3.14 dentro del companion object.',
 'class Circle { companion object { const val PI = 3.14 } }', 'class Circle { companion object { const val PI = 3.14 } }',
 20, 3, now()),

-- 41. functions
(gen_random_uuid(),
 'Default Parameter', 'Parámetro por Defecto',
 'Define fun greet(name: String = "World") that prints "Hello, <name>!". Call it with no argument.',
 'Define fun greet(name: String = "World") que imprima "Hello, <name>!". Llámala sin argumento.',
 'kotlin', 2, 'functions',
 'fun main() {\n    greet()\n}\n\n// define greet here',
 'Hello, World!',
 3,
 'Default parameter values are assigned with = in the function signature.', 'Los valores por defecto de parámetros se asignan con = en la firma de la función.',
 'fun greet(name: String = "World") { println("Hello, $name!") }', 'fun greet(name: String = "World") { println("Hello, $name!") }',
 'Calling greet() uses the default value "World".', 'Llamar a greet() usa el valor por defecto "World".',
 20, 3, now()),

-- 42. functions
(gen_random_uuid(),
 'Named Arguments', 'Argumentos con Nombre',
 'Define fun describe(name: String, age: Int) that prints "<name> is <age>". Call it with named args age=25, name="Bob".',
 'Define fun describe(name: String, age: Int) que imprima "<name> is <age>". Llámala con args nombrados age=25, name="Bob".',
 'kotlin', 2, 'functions',
 'fun main() {\n    // call describe with named args\n}\n\n// define describe here',
 'Bob is 25',
 3,
 'Named arguments let you pass values in any order by specifying the parameter name.', 'Los argumentos nombrados te permiten pasar valores en cualquier orden especificando el nombre del parámetro.',
 'describe(age = 25, name = "Bob")', 'describe(age = 25, name = "Bob")',
 'fun describe(name: String, age: Int) { println("$name is $age") }', 'fun describe(name: String, age: Int) { println("$name is $age") }',
 20, 3, now()),

-- 43. collections
(gen_random_uuid(),
 'Map Collection', 'Colección Map',
 'Create a mapOf("one" to 1, "two" to 2, "three" to 3). Print the value for key "two".',
 'Crea un mapOf("one" to 1, "two" to 2, "three" to 3). Imprime el valor para la clave "two".',
 'kotlin', 2, 'collections',
 'fun main() {\n    // your code\n}',
 '2',
 3,
 'Use mapOf() with the to infix function to create key-value pairs.', 'Usa mapOf() con la función infija to para crear pares clave-valor.',
 'Access a value with map["key"].', 'Accede a un valor con map["key"].',
 'val m = mapOf("one" to 1, "two" to 2, "three" to 3); println(m["two"])', 'val m = mapOf("one" to 1, "two" to 2, "three" to 3); println(m["two"])',
 20, 3, now()),

-- 44. collections
(gen_random_uuid(),
 'List reduce()', 'List reduce()',
 'Given listOf(1,2,3,4,5), use reduce to compute the sum and print it.',
 'Dado listOf(1,2,3,4,5), usa reduce para calcular la suma e imprimirla.',
 'kotlin', 2, 'collections',
 'fun main() {\n    val nums = listOf(1, 2, 3, 4, 5)\n    // your code\n}',
 '15',
 3,
 'reduce accumulates a value starting from the first element.', 'reduce acumula un valor comenzando desde el primer elemento.',
 'Use .reduce { acc, n -> acc + n }.', 'Usa .reduce { acc, n -> acc + n }.',
 'println(nums.reduce { acc, n -> acc + n })', 'println(nums.reduce { acc, n -> acc + n })',
 20, 3, now()),

-- 45. smart-casts
(gen_random_uuid(),
 'Smart Cast with is', 'Smart Cast con is',
 'Declare val obj: Any = "Hello Kotlin". Use is to check if it is a String and print its length using a smart cast.',
 'Declara val obj: Any = "Hello Kotlin". Usa is para verificar si es un String e imprime su longitud usando smart cast.',
 'kotlin', 2, 'smart-casts',
 'fun main() {\n    val obj: Any = "Hello Kotlin"\n    // your code\n}',
 '12',
 3,
 'After an is String check in an if block, Kotlin auto-casts obj to String.', 'Después de una verificación is String en un bloque if, Kotlin hace cast automático de obj a String.',
 'if (obj is String) { println(obj.length) }', 'if (obj is String) { println(obj.length) }',
 'Inside the if block obj is automatically treated as String.', 'Dentro del bloque if, obj se trata automáticamente como String.',
 20, 3, now()),

-- 46. control-flow
(gen_random_uuid(),
 'For Loop with Index', 'Bucle For con Índice',
 'Given listOf("x","y","z"), print each element with its index using forEachIndexed.',
 'Dado listOf("x","y","z"), imprime cada elemento con su índice usando forEachIndexed.',
 'kotlin', 2, 'control-flow',
 'fun main() {\n    val items = listOf("x", "y", "z")\n    // your code\n}',
 '0: x\n1: y\n2: z',
 3,
 'Use .forEachIndexed { index, value -> } on the list.', 'Usa .forEachIndexed { index, value -> } en la lista.',
 'println("$index: $value") inside the lambda.', 'println("$index: $value") dentro del lambda.',
 'items.forEachIndexed { i, v -> println("$i: $v") }', 'items.forEachIndexed { i, v -> println("$i: $v") }',
 20, 3, now()),

-- 47. strings
(gen_random_uuid(),
 'String Split', 'Dividir Cadena',
 'Split "a,b,c,d" by comma and print the resulting list.',
 'Divide "a,b,c,d" por coma e imprime la lista resultante.',
 'kotlin', 2, 'strings',
 'fun main() {\n    val csv = "a,b,c,d"\n    // your code\n}',
 '[a, b, c, d]',
 3,
 'Use .split(",") on the string.', 'Usa .split(",") en la cadena.',
 'println(csv.split(","))', 'println(csv.split(","))',
 'split returns a List<String>.', 'split devuelve una List<String>.',
 20, 3, now()),

-- 48. functions
(gen_random_uuid(),
 'Single-Expression Function', 'Función de Expresión Única',
 'Define fun cube(n: Int) = n * n * n. Print cube(3).',
 'Define fun cube(n: Int) = n * n * n. Imprime cube(3).',
 'kotlin', 2, 'functions',
 'fun main() {\n    println(cube(3))\n}\n\n// define cube here',
 '27',
 3,
 'A single-expression function uses = instead of { return }.', 'Una función de expresión única usa = en lugar de { return }.',
 'fun cube(n: Int) = n * n * n', 'fun cube(n: Int) = n * n * n',
 'No return keyword or braces needed.', 'No se necesita la palabra clave return ni llaves.',
 20, 3, now()),

-- 49. collections
(gen_random_uuid(),
 'sortedBy', 'sortedBy',
 'Sort listOf("banana","apple","cherry") alphabetically and print the result.',
 'Ordena listOf("banana","apple","cherry") alfabéticamente e imprime el resultado.',
 'kotlin', 2, 'collections',
 'fun main() {\n    val fruits = listOf("banana", "apple", "cherry")\n    // your code\n}',
 '[apple, banana, cherry]',
 3,
 'Use .sorted() for natural ordering of strings.', 'Usa .sorted() para el orden natural de cadenas.',
 'println(fruits.sorted())', 'println(fruits.sorted())',
 'sorted() returns a new sorted list without modifying the original.', 'sorted() devuelve una nueva lista ordenada sin modificar la original.',
 20, 3, now()),

-- 50. null-safety
(gen_random_uuid(),
 'let with Nullable', 'let con Anulable',
 'Declare val input: String? = "  hello  ". Use let to trim and print the value if not null.',
 'Declara val input: String? = "  hello  ". Usa let para hacer trim e imprimir el valor si no es null.',
 'kotlin', 2, 'null-safety',
 'fun main() {\n    val input: String? = "  hello  "\n    // your code\n}',
 'hello',
 3,
 'Chain ?. let to safely access the value.', 'Encadena ?. let para acceder al valor de forma segura.',
 'input?.let { println(it.trim()) }', 'input?.let { println(it.trim()) }',
 'trim() removes leading and trailing whitespace.', 'trim() elimina los espacios en blanco al inicio y al final.',
 20, 3, now()),

-- ============================================================
-- DIFFICULTY 3 — 25 exercises (points=30, penalty=5)
-- ============================================================

-- 51. sealed-classes
(gen_random_uuid(),
 'Sealed Class Basics', 'Clases Selladas Básicas',
 'Define a sealed class Shape with subclasses Circle(radius: Double) and Rectangle(width: Double, height: Double). Write fun area(s: Shape) using when, and print the area of Circle(5.0). Use Math.PI.',
 'Define una sealed class Shape con subclases Circle(radius: Double) y Rectangle(width: Double, height: Double). Escribe fun area(s: Shape) usando when, e imprime el área de Circle(5.0). Usa Math.PI.',
 'kotlin', 3, 'sealed-classes',
 'fun main() {\n    println(area(Circle(5.0)))\n}\n\n// define sealed class and area() here',
 '78.53981633974483',
 3,
 'sealed class Shape is the parent; declare subclasses in the same file.', 'sealed class Shape es el padre; declara las subclases en el mismo archivo.',
 'In the when expression, check is Circle -> Math.PI * s.radius * s.radius.', 'En la expresión when, verifica is Circle -> Math.PI * s.radius * s.radius.',
 'is Circle -> Math.PI * shape.radius * shape.radius', 'is Circle -> Math.PI * shape.radius * shape.radius',
 30, 5, now()),

-- 52. sealed-classes
(gen_random_uuid(),
 'Sealed Class Result Type', 'Sealed Class Tipo Resultado',
 'Create sealed class Result<T> with Success(val data: T) and Failure(val error: String). Write a function that returns Success("OK") and print the data using a when expression.',
 'Crea sealed class Result<T> con Success(val data: T) y Failure(val error: String). Escribe una función que retorne Success("OK") e imprime el dato usando una expresión when.',
 'kotlin', 3, 'sealed-classes',
 'fun main() {\n    val r = getResult()\n    // print data using when\n}\n\n// define sealed class and getResult here',
 'OK',
 3,
 'A sealed class can have generic type parameters.', 'Una sealed class puede tener parámetros de tipo genérico.',
 'fun getResult(): Result<String> = Success("OK")', 'fun getResult(): Result<String> = Success("OK")',
 'In when: is Success -> println(r.data)', 'En when: is Success -> println(r.data)',
 30, 5, now()),

-- 53. data-classes
(gen_random_uuid(),
 'Data Class Destructuring', 'Destructuración de Data Class',
 'Create data class Point(val x: Int, val y: Int). Destructure Point(10, 20) into (x, y) and print them.',
 'Crea data class Point(val x: Int, val y: Int). Desestructura Point(10, 20) en (x, y) e imprímelos.',
 'kotlin', 3, 'data-classes',
 'fun main() {\n    val p = Point(10, 20)\n    // destructure and print\n}\n\ndata class Point(val x: Int, val y: Int)',
 '10\n20',
 3,
 'Data classes support destructuring declarations.', 'Las data class soportan declaraciones de desestructuración.',
 'val (x, y) = p', 'val (x, y) = p',
 'Then println(x) and println(y).', 'Luego println(x) y println(y).',
 30, 5, now()),

-- 54. coroutines
(gen_random_uuid(),
 'runBlocking Basic', 'runBlocking Básico',
 'Use runBlocking to launch a coroutine that prints "Coroutine running" then prints "Done".',
 'Usa runBlocking para lanzar una corrutina que imprima "Coroutine running" y luego imprima "Done".',
 'kotlin', 3, 'coroutines',
 'import kotlinx.coroutines.*\n\nfun main() {\n    // your code\n}',
 'Coroutine running\nDone',
 3,
 'runBlocking blocks the current thread until the coroutine completes.', 'runBlocking bloquea el hilo actual hasta que la corrutina se complete.',
 'runBlocking { println("Coroutine running") }; println("Done")', 'runBlocking { println("Coroutine running") }; println("Done")',
 'Alternatively put both printlns inside runBlocking.', 'Alternativamente pon ambos println dentro de runBlocking.',
 30, 5, now()),

-- 55. coroutines
(gen_random_uuid(),
 'suspend Function', 'Función suspend',
 'Write a suspend fun fetchData() that returns "data". Call it inside runBlocking and print the result.',
 'Escribe una suspend fun fetchData() que retorne "data". Llámala dentro de runBlocking e imprime el resultado.',
 'kotlin', 3, 'coroutines',
 'import kotlinx.coroutines.*\n\nfun main() = runBlocking {\n    // call fetchData and print\n}\n\n// define fetchData here',
 'data',
 3,
 'A suspend function can only be called from another suspend function or a coroutine.', 'Una función suspend solo puede ser llamada desde otra función suspend o una corrutina.',
 'suspend fun fetchData(): String = "data"', 'suspend fun fetchData(): String = "data"',
 'val result = fetchData(); println(result)', 'val result = fetchData(); println(result)',
 30, 5, now()),

-- 56. scope-functions
(gen_random_uuid(),
 'run Scope Function', 'Función de Alcance run',
 'Use run on a String "  Kotlin  " to trim it and convert to uppercase, then print the result.',
 'Usa run en el String "  Kotlin  " para hacer trim y convertirlo a mayúsculas, luego imprime el resultado.',
 'kotlin', 3, 'scope-functions',
 'fun main() {\n    val result = "  Kotlin  ".run {\n        // your code\n    }\n    println(result)\n}',
 'KOTLIN',
 3,
 'Inside run, this refers to the receiver object.', 'Dentro de run, this se refiere al objeto receptor.',
 'Call trim() then uppercase() and it becomes the return value of run.', 'Llama a trim() luego uppercase() y ese será el valor de retorno de run.',
 '"  Kotlin  ".run { trim().uppercase() }', '"  Kotlin  ".run { trim().uppercase() }',
 30, 5, now()),

-- 57. scope-functions
(gen_random_uuid(),
 'also Scope Function', 'Función de Alcance also',
 'Create a mutableListOf(1,2,3). Use also to print the list before adding 4, then print it after.',
 'Crea un mutableListOf(1,2,3). Usa also para imprimir la lista antes de añadir 4, luego imprímela después.',
 'kotlin', 3, 'scope-functions',
 'fun main() {\n    val list = mutableListOf(1, 2, 3)\n        .also { println(it) }\n    // add 4 and print again\n}',
 '[1, 2, 3]\n[1, 2, 3, 4]',
 3,
 'also receives the object as it and returns the object itself.', 'also recibe el objeto como it y devuelve el propio objeto.',
 'After the also chain, call list.add(4) then println(list).', 'Después de la cadena also, llama a list.add(4) luego println(list).',
 '.also { println(it) } then list.add(4); println(list)', '.also { println(it) } luego list.add(4); println(list)',
 30, 5, now()),

-- 58. extension-functions
(gen_random_uuid(),
 'Extension on Collection', 'Extensión en Colección',
 'Add an extension function second() on List<T> that returns the element at index 1. Print listOf(10,20,30).second().',
 'Añade una función de extensión second() en List<T> que retorne el elemento en índice 1. Imprime listOf(10,20,30).second().',
 'kotlin', 3, 'extension-functions',
 'fun main() {\n    println(listOf(10, 20, 30).second())\n}\n\n// define extension here',
 '20',
 3,
 'fun <T> List<T>.second(): T defines a generic extension on List.', 'fun <T> List<T>.second(): T define una extensión genérica en List.',
 'Return this[1] inside the function body.', 'Retorna this[1] dentro del cuerpo de la función.',
 'fun <T> List<T>.second(): T = this[1]', 'fun <T> List<T>.second(): T = this[1]',
 30, 5, now()),

-- 59. companion-objects
(gen_random_uuid(),
 'Companion Object Factory', 'Fábrica en Companion Object',
 'Create class Temperature(val celsius: Double) with a companion factory fun fromFahrenheit(f: Double). Print fromFahrenheit(212.0).celsius.',
 'Crea class Temperature(val celsius: Double) con una fábrica fun fromFahrenheit(f: Double) en companion. Imprime fromFahrenheit(212.0).celsius.',
 'kotlin', 3, 'companion-objects',
 'fun main() {\n    println(Temperature.fromFahrenheit(212.0).celsius)\n}\n\n// define Temperature here',
 '100.0',
 3,
 'Factory methods in the companion object return instances of the class.', 'Los métodos fábrica en el companion object devuelven instancias de la clase.',
 'Celsius = (f - 32) * 5 / 9', 'Celsius = (f - 32) * 5 / 9',
 'companion object { fun fromFahrenheit(f: Double) = Temperature((f - 32) * 5 / 9) }', 'companion object { fun fromFahrenheit(f: Double) = Temperature((f - 32) * 5 / 9) }',
 30, 5, now()),

-- 60. collections
(gen_random_uuid(),
 'groupBy', 'groupBy',
 'Given listOf("apple","apricot","banana","blueberry","cherry"), group by first letter and print the keys.',
 'Dado listOf("apple","apricot","banana","blueberry","cherry"), agrupa por primera letra e imprime las claves.',
 'kotlin', 3, 'collections',
 'fun main() {\n    val fruits = listOf("apple","apricot","banana","blueberry","cherry")\n    // your code\n}',
 '[a, b, c]',
 3,
 'Use .groupBy { it.first() } to group by the first character.', 'Usa .groupBy { it.first() } para agrupar por el primer carácter.',
 'Access .keys on the resulting Map.', 'Accede a .keys en el Map resultante.',
 'println(fruits.groupBy { it.first() }.keys.toList())', 'println(fruits.groupBy { it.first() }.keys.toList())',
 30, 5, now()),

-- 61. collections
(gen_random_uuid(),
 'flatMap', 'flatMap',
 'Given listOf(listOf(1,2),listOf(3,4),listOf(5)), use flatMap to flatten and print the result.',
 'Dado listOf(listOf(1,2),listOf(3,4),listOf(5)), usa flatMap para aplanar e imprime el resultado.',
 'kotlin', 3, 'collections',
 'fun main() {\n    val nested = listOf(listOf(1,2), listOf(3,4), listOf(5))\n    // your code\n}',
 '[1, 2, 3, 4, 5]',
 3,
 'flatMap transforms each element into a collection and flattens all results.', 'flatMap transforma cada elemento en una colección y aplana todos los resultados.',
 '.flatMap { it } passes each sub-list through unchanged.', '.flatMap { it } pasa cada sublista sin cambios.',
 'println(nested.flatMap { it })', 'println(nested.flatMap { it })',
 30, 5, now()),

-- 62. smart-casts
(gen_random_uuid(),
 'Smart Cast in when', 'Smart Cast en when',
 'Write fun describe(obj: Any): String. Return "Int: <n>" for Int, "String: <s>" for String, else "Other". Print describe(42).',
 'Escribe fun describe(obj: Any): String. Retorna "Int: <n>" para Int, "String: <s>" para String, si no "Other". Imprime describe(42).',
 'kotlin', 3, 'smart-casts',
 'fun main() {\n    println(describe(42))\n}\n\n// define describe here',
 'Int: 42',
 3,
 'Use when(obj) with is Int, is String branches.', 'Usa when(obj) con ramas is Int, is String.',
 'After is Int, obj is smart-cast to Int automatically.', 'Después de is Int, obj se convierte automáticamente a Int.',
 'is Int -> "Int: $obj"; is String -> "String: $obj"; else -> "Other"', 'is Int -> "Int: $obj"; is String -> "String: $obj"; else -> "Other"',
 30, 5, now()),

-- 63. lambdas
(gen_random_uuid(),
 'Higher-Order Function', 'Función de Orden Superior',
 'Write fun applyTwice(x: Int, f: (Int) -> Int): Int that applies f twice. Print applyTwice(2) { it * 3 }.',
 'Escribe fun applyTwice(x: Int, f: (Int) -> Int): Int que aplique f dos veces. Imprime applyTwice(2) { it * 3 }.',
 'kotlin', 3, 'lambdas',
 'fun main() {\n    println(applyTwice(2) { it * 3 })\n}\n\n// define applyTwice here',
 '18',
 3,
 'A higher-order function takes a function as a parameter.', 'Una función de orden superior toma una función como parámetro.',
 'fun applyTwice(x: Int, f: (Int) -> Int): Int = f(f(x))', 'fun applyTwice(x: Int, f: (Int) -> Int): Int = f(f(x))',
 'applyTwice(2){ it*3 } → f(f(2)) = f(6) = 18', 'applyTwice(2){ it*3 } → f(f(2)) = f(6) = 18',
 30, 5, now()),

-- 64. null-safety
(gen_random_uuid(),
 'Chained Safe Calls', 'Llamadas Seguras Encadenadas',
 'Given data class City(val country: Country?) and data class Country(val name: String?), create City(Country("Spain")) and safely print the country name.',
 'Dado data class City(val country: Country?) y data class Country(val name: String?), crea City(Country("Spain")) e imprime de forma segura el nombre del país.',
 'kotlin', 3, 'null-safety',
 'fun main() {\n    val city = City(Country("Spain"))\n    // print country name safely\n}\n\ndata class City(val country: Country?)\ndata class Country(val name: String?)',
 'Spain',
 3,
 'Chain multiple ?. operators to safely traverse nullable properties.', 'Encadena múltiples operadores ?. para recorrer de forma segura propiedades anulables.',
 'city.country?.name', 'city.country?.name',
 'println(city.country?.name)', 'println(city.country?.name)',
 30, 5, now()),

-- 65. coroutines
(gen_random_uuid(),
 'async and await', 'async y await',
 'Use async inside runBlocking to compute 6 * 7 concurrently. Await the result and print it.',
 'Usa async dentro de runBlocking para calcular 6 * 7 de forma concurrente. Espera el resultado e imprímelo.',
 'kotlin', 3, 'coroutines',
 'import kotlinx.coroutines.*\n\nfun main() = runBlocking {\n    // your code\n}',
 '42',
 3,
 'async returns a Deferred; call .await() to get the value.', 'async devuelve un Deferred; llama a .await() para obtener el valor.',
 'val deferred = async { 6 * 7 }', 'val deferred = async { 6 * 7 }',
 'println(deferred.await())', 'println(deferred.await())',
 30, 5, now()),

-- 66. when
(gen_random_uuid(),
 'When with Multiple Conditions', 'When con Múltiples Condiciones',
 'Declare val c = ''\''B''\'' (char). Use when to print "Vowel" if c is in A,E,I,O,U (ignore case), else "Consonant".',
 'Declara val c = ''\''B''\'' (char). Usa when para imprimir "Vowel" si c está en A,E,I,O,U (sin importar mayúsculas), si no "Consonant".',
 'kotlin', 3, 'when',
 'fun main() {\n    val c = ''B''\n    // your code\n}',
 'Consonant',
 3,
 'Use when(c.uppercaseChar()) and list values with commas: ''A'', ''E'', ''I'', ''O'', ''U''.', 'Usa when(c.uppercaseChar()) y lista los valores con comas: ''A'', ''E'', ''I'', ''O'', ''U''.',
 '''A'', ''E'', ''I'', ''O'', ''U'' -> "Vowel"', '''A'', ''E'', ''I'', ''O'', ''U'' -> "Vowel"',
 'else -> "Consonant"', 'else -> "Consonant"',
 30, 5, now()),

-- 67. collections
(gen_random_uuid(),
 'zip Two Lists', 'zip de Dos Listas',
 'Zip listOf("a","b","c") with listOf(1,2,3) and print the resulting pairs.',
 'Combina con zip listOf("a","b","c") con listOf(1,2,3) e imprime los pares resultantes.',
 'kotlin', 3, 'collections',
 'fun main() {\n    val letters = listOf("a", "b", "c")\n    val numbers = listOf(1, 2, 3)\n    // your code\n}',
 '[(a, 1), (b, 2), (c, 3)]',
 3,
 'Use .zip() to combine two lists into a list of Pairs.', 'Usa .zip() para combinar dos listas en una lista de Pares.',
 'println(letters.zip(numbers))', 'println(letters.zip(numbers))',
 'Each element in the result is a Pair<String, Int>.', 'Cada elemento en el resultado es un Pair<String, Int>.',
 30, 5, now()),

-- 68. extension-functions
(gen_random_uuid(),
 'Extension Property', 'Propiedad de Extensión',
 'Add an extension property wordCount on String that returns the number of words. Print "hello world kotlin".wordCount.',
 'Añade una propiedad de extensión wordCount en String que retorne el número de palabras. Imprime "hello world kotlin".wordCount.',
 'kotlin', 3, 'extension-functions',
 'fun main() {\n    println("hello world kotlin".wordCount)\n}\n\n// define extension here',
 '3',
 3,
 'Extension properties are declared with val TypeName.propName: Type get() = ...', 'Las propiedades de extensión se declaran con val TypeName.propName: Type get() = ...',
 'Split by " " and return the size.', 'Divide por " " y retorna el tamaño.',
 'val String.wordCount: Int get() = this.split(" ").size', 'val String.wordCount: Int get() = this.split(" ").size',
 30, 5, now()),

-- 69. scope-functions
(gen_random_uuid(),
 'with Scope Function', 'Función de Alcance with',
 'Use with on a StringBuilder to build "Hello, Kotlin!" by appending "Hello, " and "Kotlin!". Print the result.',
 'Usa with en un StringBuilder para construir "Hello, Kotlin!" agregando "Hello, " y "Kotlin!". Imprime el resultado.',
 'kotlin', 3, 'scope-functions',
 'fun main() {\n    val sb = StringBuilder()\n    val result = with(sb) {\n        // your code\n    }\n    println(result)\n}',
 'Hello, Kotlin!',
 3,
 'with takes the object as first argument and provides it as this inside the block.', 'with toma el objeto como primer argumento y lo provee como this dentro del bloque.',
 'append("Hello, "); append("Kotlin!"); toString()', 'append("Hello, "); append("Kotlin!"); toString()',
 'The last expression in the with block is returned.', 'La última expresión del bloque with es retornada.',
 30, 5, now()),

-- 70. collections
(gen_random_uuid(),
 'partition', 'partition',
 'Partition listOf(1,2,3,4,5,6) into evens and odds, print the evens list.',
 'Particiona listOf(1,2,3,4,5,6) en pares e impares, imprime la lista de pares.',
 'kotlin', 3, 'collections',
 'fun main() {\n    val nums = listOf(1, 2, 3, 4, 5, 6)\n    // your code\n}',
 '[2, 4, 6]',
 3,
 'Use .partition { predicate } which returns a Pair of lists.', 'Usa .partition { predicado } que devuelve un Par de listas.',
 'val (evens, odds) = nums.partition { it % 2 == 0 }', 'val (evens, odds) = nums.partition { it % 2 == 0 }',
 'Then println(evens).', 'Luego println(evens).',
 30, 5, now()),

-- 71. data-classes
(gen_random_uuid(),
 'Data Class equals and hashCode', 'equals y hashCode en Data Class',
 'Create data class Color(val r: Int, val g: Int, val b: Int). Verify that Color(255,0,0) == Color(255,0,0) and print the result.',
 'Crea data class Color(val r: Int, val g: Int, val b: Int). Verifica que Color(255,0,0) == Color(255,0,0) e imprime el resultado.',
 'kotlin', 3, 'data-classes',
 'fun main() {\n    // your code\n}\n\ndata class Color(val r: Int, val g: Int, val b: Int)',
 'true',
 3,
 'Data classes auto-generate equals() based on all constructor properties.', 'Las data class generan automáticamente equals() basándose en todas las propiedades del constructor.',
 'println(Color(255,0,0) == Color(255,0,0))', 'println(Color(255,0,0) == Color(255,0,0))',
 'Two data class instances with the same values are equal.', 'Dos instancias de data class con los mismos valores son iguales.',
 30, 5, now()),

-- 72. lambdas
(gen_random_uuid(),
 'Function References', 'Referencias de Funciones',
 'Define fun isEven(n: Int) = n % 2 == 0. Use it as a reference with filter on listOf(1..6) and print.',
 'Define fun isEven(n: Int) = n % 2 == 0. Úsala como referencia con filter en listOf(1..6) e imprime.',
 'kotlin', 3, 'lambdas',
 'fun main() {\n    println((1..6).toList().filter(::isEven))\n}\n\n// define isEven here',
 '[2, 4, 6]',
 3,
 'Use :: before a function name to create a function reference.', 'Usa :: antes del nombre de una función para crear una referencia de función.',
 'filter(::isEven) passes the function reference as a predicate.', 'filter(::isEven) pasa la referencia de función como predicado.',
 'fun isEven(n: Int) = n % 2 == 0', 'fun isEven(n: Int) = n % 2 == 0',
 30, 5, now()),

-- 73. control-flow
(gen_random_uuid(),
 'Downto and Step', 'Downto y Step',
 'Print even numbers from 10 down to 2 using a for loop with downTo and step.',
 'Imprime los números pares del 10 al 2 (descendente) usando un bucle for con downTo y step.',
 'kotlin', 3, 'control-flow',
 'fun main() {\n    // your code\n}',
 '10\n8\n6\n4\n2',
 3,
 'Use for (i in 10 downTo 2 step 2).', 'Usa for (i in 10 downTo 2 step 2).',
 'downTo goes from high to low, step controls the increment size.', 'downTo va de mayor a menor, step controla el tamaño del incremento.',
 'for (i in 10 downTo 2 step 2) println(i)', 'for (i in 10 downTo 2 step 2) println(i)',
 30, 5, now()),

-- 74. collections
(gen_random_uuid(),
 'sumOf', 'sumOf',
 'Given listOf("apple","fig","pineapple","kiwi"), use sumOf to compute the total character count and print it.',
 'Dado listOf("apple","fig","pineapple","kiwi"), usa sumOf para calcular el total de caracteres e imprímelo.',
 'kotlin', 3, 'collections',
 'fun main() {\n    val fruits = listOf("apple", "fig", "pineapple", "kiwi")\n    // your code\n}',
 '23',
 3,
 'Use .sumOf { it.length } to sum the lengths.', 'Usa .sumOf { it.length } para sumar las longitudes.',
 'println(fruits.sumOf { it.length })', 'println(fruits.sumOf { it.length })',
 '5 + 3 + 9 + 4 = 21... wait: apple=5, fig=3, pineapple=9, kiwi=4 → 21. Recount: a-p-p-l-e=5, f-i-g=3, p-i-n-e-a-p-p-l-e=9, k-i-w-i=4 = 21.', 'apple=5, fig=3, pineapple=9, kiwi=4 → 21.',
 30, 5, now()),

-- 75. scope-functions
(gen_random_uuid(),
 'Chaining Scope Functions', 'Encadenando Funciones de Alcance',
 'Start with "  kotlin  ", use let to trim it, then run to capitalize the first letter, and print the final result.',
 'Comienza con "  kotlin  ", usa let para hacer trim, luego run para capitalizar la primera letra, e imprime el resultado final.',
 'kotlin', 3, 'scope-functions',
 'fun main() {\n    val result = "  kotlin  "\n        .let { it.trim() }\n        .run { /* capitalize */ }\n    println(result)\n}',
 'Kotlin',
 3,
 'let returns the lambda result; run also returns the lambda result.', 'let devuelve el resultado del lambda; run también devuelve el resultado del lambda.',
 'Inside run, use replaceFirstChar { it.uppercase() }.', 'Dentro de run, usa replaceFirstChar { it.uppercase() }.',
 '.run { replaceFirstChar { it.uppercase() } }', '.run { replaceFirstChar { it.uppercase() } }',
 30, 5, now()),

-- ============================================================
-- DIFFICULTY 4 — 15 exercises (points=50, penalty=10)
-- ============================================================

-- 76. sealed-classes
(gen_random_uuid(),
 'Sealed Class Hierarchy', 'Jerarquía de Sealed Class',
 'Model a tree with sealed class Tree<T>: Leaf(val value: T) and Branch(val left: Tree<T>, val right: Tree<T>). Write fun depth(t: Tree<*>): Int. Print depth(Branch(Branch(Leaf(1),Leaf(2)),Leaf(3))).',
 'Modela un árbol con sealed class Tree<T>: Leaf(val value: T) y Branch(val left: Tree<T>, val right: Tree<T>). Escribe fun depth(t: Tree<*>): Int. Imprime depth(Branch(Branch(Leaf(1),Leaf(2)),Leaf(3))).',
 'kotlin', 4, 'sealed-classes',
 'fun main() {\n    val tree = Branch(Branch(Leaf(1), Leaf(2)), Leaf(3))\n    println(depth(tree))\n}\n\n// define sealed class and depth here',
 '3',
 3,
 'For a Leaf the depth is 1. For a Branch it is 1 + max(depth(left), depth(right)).', 'Para un Leaf la profundidad es 1. Para un Branch es 1 + max(depth(left), depth(right)).',
 'Use a when expression inside depth() with is Leaf and is Branch branches.', 'Usa una expresión when dentro de depth() con ramas is Leaf y is Branch.',
 'is Leaf -> 1; is Branch -> 1 + maxOf(depth(t.left), depth(t.right))', 'is Leaf -> 1; is Branch -> 1 + maxOf(depth(t.left), depth(t.right))',
 50, 10, now()),

-- 77. coroutines
(gen_random_uuid(),
 'Parallel Coroutines with async', 'Corrutinas Paralelas con async',
 'Launch two async coroutines that return 100 and 200. Sum the results with await and print 300.',
 'Lanza dos corrutinas async que retornen 100 y 200. Suma los resultados con await e imprime 300.',
 'kotlin', 4, 'coroutines',
 'import kotlinx.coroutines.*\n\nfun main() = runBlocking {\n    // your code\n}',
 '300',
 3,
 'Call async { 100 } and async { 200 } to start both concurrently.', 'Llama a async { 100 } y async { 200 } para iniciarlos concurrentemente.',
 'val a = async { 100 }; val b = async { 200 }', 'val a = async { 100 }; val b = async { 200 }',
 'println(a.await() + b.await())', 'println(a.await() + b.await())',
 50, 10, now()),

-- 78. extension-functions
(gen_random_uuid(),
 'Infix Extension Function', 'Función de Extensión Infix',
 'Write an infix extension function times on Int that repeats a String that many times. Print 3 times "ab".',
 'Escribe una función de extensión infix times en Int que repita un String esa cantidad de veces. Imprime 3 times "ab".',
 'kotlin', 4, 'extension-functions',
 'fun main() {\n    println(3 times "ab")\n}\n\n// define infix extension here',
 'ababab',
 3,
 'Prefix the extension function declaration with the infix keyword.', 'Prefija la declaración de la función de extensión con la palabra clave infix.',
 'infix fun Int.times(s: String): String', 'infix fun Int.times(s: String): String',
 'Return s.repeat(this) inside the function.', 'Retorna s.repeat(this) dentro de la función.',
 50, 10, now()),

-- 79. lambdas
(gen_random_uuid(),
 'Currying with Lambdas', 'Currying con Lambdas',
 'Write fun add(a: Int): (Int) -> Int that returns a lambda adding a to its argument. Print add(3)(4).',
 'Escribe fun add(a: Int): (Int) -> Int que retorne un lambda que sume a a su argumento. Imprime add(3)(4).',
 'kotlin', 4, 'lambdas',
 'fun main() {\n    println(add(3)(4))\n}\n\n// define add here',
 '7',
 3,
 'The return type (Int) -> Int is a function type taking an Int and returning an Int.', 'El tipo de retorno (Int) -> Int es un tipo función que toma un Int y retorna un Int.',
 'fun add(a: Int): (Int) -> Int = { b -> a + b }', 'fun add(a: Int): (Int) -> Int = { b -> a + b }',
 'Calling add(3) returns a lambda; calling that lambda with (4) gives 7.', 'Llamar a add(3) devuelve un lambda; llamar ese lambda con (4) da 7.',
 50, 10, now()),

-- 80. data-classes
(gen_random_uuid(),
 'Data Class with Computed Property', 'Data Class con Propiedad Calculada',
 'Create data class Rectangle(val width: Double, val height: Double) with a computed val area: Double. Print Rectangle(4.0, 5.0).area.',
 'Crea data class Rectangle(val width: Double, val height: Double) con un val area: Double calculado. Imprime Rectangle(4.0, 5.0).area.',
 'kotlin', 4, 'data-classes',
 'fun main() {\n    println(Rectangle(4.0, 5.0).area)\n}\n\n// define Rectangle here',
 '20.0',
 3,
 'Add a body to the data class and declare val area inside it.', 'Añade un cuerpo a la data class y declara val area dentro de él.',
 'val area: Double get() = width * height', 'val area: Double get() = width * height',
 'Computed properties use a custom getter with get() = ...', 'Las propiedades calculadas usan un getter personalizado con get() = ...',
 50, 10, now()),

-- 81. coroutines
(gen_random_uuid(),
 'Flow Basics', 'Fundamentos de Flow',
 'Emit values 1, 2, 3 from a flow and collect them, printing each. Import kotlinx.coroutines.flow.*.',
 'Emite los valores 1, 2, 3 desde un flow y recógelos, imprimiendo cada uno. Importa kotlinx.coroutines.flow.*.',
 'kotlin', 4, 'coroutines',
 'import kotlinx.coroutines.*\nimport kotlinx.coroutines.flow.*\n\nfun main() = runBlocking {\n    // your code\n}',
 '1\n2\n3',
 3,
 'Use flow { emit(1); emit(2); emit(3) } to create a flow.', 'Usa flow { emit(1); emit(2); emit(3) } para crear un flow.',
 'Call .collect { println(it) } to consume the flow.', 'Llama a .collect { println(it) } para consumir el flow.',
 'flow { emit(1); emit(2); emit(3) }.collect { println(it) }', 'flow { emit(1); emit(2); emit(3) }.collect { println(it) }',
 50, 10, now()),

-- 82. companion-objects
(gen_random_uuid(),
 'Singleton via Companion', 'Singleton via Companion',
 'Create class Counter with a companion object holding var count = 0 and fun increment(). Call increment() 3 times and print Counter.count.',
 'Crea class Counter con un companion object con var count = 0 y fun increment(). Llama a increment() 3 veces e imprime Counter.count.',
 'kotlin', 4, 'companion-objects',
 'fun main() {\n    Counter.increment()\n    Counter.increment()\n    Counter.increment()\n    println(Counter.count)\n}\n\n// define Counter here',
 '3',
 3,
 'The companion object shares state across all callers like a static context.', 'El companion object comparte estado entre todos los llamadores como un contexto estático.',
 'companion object { var count = 0; fun increment() { count++ } }', 'companion object { var count = 0; fun increment() { count++ } }',
 'Each call to Counter.increment() increments the shared count.', 'Cada llamada a Counter.increment() incrementa el count compartido.',
 50, 10, now()),

-- 83. scope-functions
(gen_random_uuid(),
 'takeIf and takeUnless', 'takeIf y takeUnless',
 'Declare val n = 42. Use takeIf to return n only if it is even, then use ?: to print "odd" if null, else print the number.',
 'Declara val n = 42. Usa takeIf para retornar n solo si es par, luego usa ?: para imprimir "odd" si es null, si no imprime el número.',
 'kotlin', 4, 'scope-functions',
 'fun main() {\n    val n = 42\n    // your code\n}',
 '42',
 3,
 'takeIf returns the receiver if the predicate is true, otherwise null.', 'takeIf retorna el receptor si el predicado es verdadero, de lo contrario null.',
 'n.takeIf { it % 2 == 0 } ?: "odd"', 'n.takeIf { it % 2 == 0 } ?: "odd"',
 'println(n.takeIf { it % 2 == 0 } ?: "odd")', 'println(n.takeIf { it % 2 == 0 } ?: "odd")',
 50, 10, now()),

-- 84. collections
(gen_random_uuid(),
 'associate and associateBy', 'associate y associateBy',
 'Given listOf("one","two","three"), create a map from word to its length using associateWith and print it.',
 'Dado listOf("one","two","three"), crea un mapa de palabra a su longitud usando associateWith e imprímelo.',
 'kotlin', 4, 'collections',
 'fun main() {\n    val words = listOf("one", "two", "three")\n    // your code\n}',
 '{one=3, two=3, three=5}',
 3,
 'associateWith creates a map where each element is a key and the lambda provides the value.', 'associateWith crea un mapa donde cada elemento es una clave y el lambda provee el valor.',
 'words.associateWith { it.length }', 'words.associateWith { it.length }',
 'println(words.associateWith { it.length })', 'println(words.associateWith { it.length })',
 50, 10, now()),

-- 85. smart-casts
(gen_random_uuid(),
 'Smart Cast after Elvis Return', 'Smart Cast tras Elvis Return',
 'Write fun printLength(s: String?). If s is null, print "null" and return. Otherwise smart cast and print s.length.',
 'Escribe fun printLength(s: String?). Si s es null, imprime "null" y retorna. De lo contrario usa smart cast e imprime s.length.',
 'kotlin', 4, 'smart-casts',
 'fun main() {\n    printLength(null)\n    printLength("Kotlin")\n}\n\n// define printLength here',
 'null\n6',
 3,
 'After a null check with return, Kotlin smart-casts the variable to the non-null type.', 'Después de una verificación nula con return, Kotlin hace smart cast de la variable al tipo no nulo.',
 'if (s == null) { println("null"); return }', 'if (s == null) { println("null"); return }',
 'After that check, s is smart-cast to String, so println(s.length) is safe.', 'Después de esa verificación, s se convierte a String, por lo que println(s.length) es seguro.',
 50, 10, now()),

-- 86. null-safety
(gen_random_uuid(),
 'lateinit Property', 'Propiedad lateinit',
 'Declare a class Greeter with lateinit var message: String. Initialize it before use and print it.',
 'Declara una clase Greeter con lateinit var message: String. Inicialízala antes de usarla e imprímela.',
 'kotlin', 4, 'null-safety',
 'fun main() {\n    val g = Greeter()\n    g.message = "Hello, lateinit!"\n    println(g.message)\n}\n\n// define Greeter here',
 'Hello, lateinit!',
 3,
 'lateinit allows declaring a non-null var that is initialized later.', 'lateinit permite declarar una var no nula que se inicializa más tarde.',
 'class Greeter { lateinit var message: String }', 'class Greeter { lateinit var message: String }',
 'Accessing a lateinit property before initialization throws UninitializedPropertyAccessException.', 'Acceder a una propiedad lateinit antes de inicializarla lanza UninitializedPropertyAccessException.',
 50, 10, now()),

-- 87. collections
(gen_random_uuid(),
 'windowed', 'windowed',
 'Given listOf(1,2,3,4,5), use windowed(size=3, step=1) and print each window.',
 'Dado listOf(1,2,3,4,5), usa windowed(size=3, step=1) e imprime cada ventana.',
 'kotlin', 4, 'collections',
 'fun main() {\n    val nums = listOf(1, 2, 3, 4, 5)\n    // your code\n}',
 '[1, 2, 3]\n[2, 3, 4]\n[3, 4, 5]',
 3,
 'windowed(size, step) produces overlapping sublists of the given size.', 'windowed(size, step) produce sublistas solapadas del tamaño dado.',
 'nums.windowed(3, 1) gives [[1,2,3],[2,3,4],[3,4,5]].', 'nums.windowed(3, 1) da [[1,2,3],[2,3,4],[3,4,5]].',
 'nums.windowed(3, 1).forEach { println(it) }', 'nums.windowed(3, 1).forEach { println(it) }',
 50, 10, now()),

-- 88. lambdas
(gen_random_uuid(),
 'Inline Function', 'Función Inline',
 'Write an inline fun <T> measure(block: () -> T): T that prints "start", runs block, prints "end", and returns the result. Print measure { 42 }.',
 'Escribe una inline fun <T> measure(block: () -> T): T que imprima "start", ejecute el bloque, imprima "end" y retorne el resultado. Imprime measure { 42 }.',
 'kotlin', 4, 'lambdas',
 'fun main() {\n    println(measure { 42 })\n}\n\n// define measure here',
 'start\nend\n42',
 3,
 'Prefix the function with the inline keyword to avoid lambda object overhead.', 'Prefija la función con la palabra clave inline para evitar la sobrecarga del objeto lambda.',
 'inline fun <T> measure(block: () -> T): T { println("start"); val r = block(); println("end"); return r }', 'inline fun <T> measure(block: () -> T): T { println("start"); val r = block(); println("end"); return r }',
 'The inlined block is substituted at the call site by the compiler.', 'El bloque inline es sustituido en el sitio de llamada por el compilador.',
 50, 10, now()),

-- 89. when
(gen_random_uuid(),
 'Exhaustive when on Enum', 'when Exhaustivo sobre Enum',
 'Declare enum class Season { SPRING, SUMMER, AUTUMN, WINTER }. Write fun describe(s: Season): String with a when expression returning a short description for each. Print describe(Season.WINTER).',
 'Declara enum class Season { SPRING, SUMMER, AUTUMN, WINTER }. Escribe fun describe(s: Season): String con una expresión when retornando una descripción corta para cada uno. Imprime describe(Season.WINTER).',
 'kotlin', 4, 'when',
 'fun main() {\n    println(describe(Season.WINTER))\n}\n\nenum class Season { SPRING, SUMMER, AUTUMN, WINTER }\n\n// define describe here',
 'Cold and snowy',
 3,
 'when on a sealed type or enum does not need an else if all cases are covered.', 'when sobre un tipo sellado o enum no necesita else si todos los casos están cubiertos.',
 'Season.WINTER -> "Cold and snowy"', 'Season.WINTER -> "Cold and snowy"',
 'fun describe(s: Season) = when(s) { SPRING -> "..."; SUMMER -> "..."; AUTUMN -> "..."; WINTER -> "Cold and snowy" }', 'fun describe(s: Season) = when(s) { SPRING -> "..."; SUMMER -> "..."; AUTUMN -> "..."; WINTER -> "Cold and snowy" }',
 50, 10, now()),

-- 90. data-classes
(gen_random_uuid(),
 'Data Class componentN', 'componentN en Data Class',
 'Create data class Triple3(val a: Int, val b: Int, val c: Int). Destructure Triple3(1,2,3) into three variables and print their sum.',
 'Crea data class Triple3(val a: Int, val b: Int, val c: Int). Desestructura Triple3(1,2,3) en tres variables e imprime su suma.',
 'kotlin', 4, 'data-classes',
 'fun main() {\n    val t = Triple3(1, 2, 3)\n    // destructure and print sum\n}\n\ndata class Triple3(val a: Int, val b: Int, val c: Int)',
 '6',
 3,
 'Data classes auto-generate component1(), component2(), component3() for destructuring.', 'Las data class generan automáticamente component1(), component2(), component3() para desestructuración.',
 'val (x, y, z) = t', 'val (x, y, z) = t',
 'println(x + y + z)', 'println(x + y + z)',
 50, 10, now()),

-- ============================================================
-- DIFFICULTY 5 — 10 exercises (points=100, penalty=10)
-- ============================================================

-- 91. coroutines
(gen_random_uuid(),
 'Coroutine Channel', 'Canal de Corrutinas',
 'Use a Channel to send integers 1-5 from a producer coroutine and print them in a consumer. Use produce or Channel directly inside runBlocking.',
 'Usa un Channel para enviar enteros del 1 al 5 desde una corrutina productora e imprímelos en un consumidor. Usa produce o Channel directamente dentro de runBlocking.',
 'kotlin', 5, 'coroutines',
 'import kotlinx.coroutines.*\nimport kotlinx.coroutines.channels.*\n\nfun main() = runBlocking {\n    // your code\n}',
 '1\n2\n3\n4\n5',
 3,
 'Create a Channel<Int>(), launch a coroutine to send values, then receive them.', 'Crea un Channel<Int>(), lanza una corrutina para enviar valores, luego recíbelos.',
 'Use channel.send(i) inside a launch block and channel.receive() or for loop to consume.', 'Usa channel.send(i) dentro de un bloque launch y channel.receive() o bucle for para consumir.',
 'val ch = Channel<Int>(); launch { for(i in 1..5) ch.send(i); ch.close() }; for(v in ch) println(v)', 'val ch = Channel<Int>(); launch { for(i in 1..5) ch.send(i); ch.close() }; for(v in ch) println(v)',
 100, 10, now()),

-- 92. sealed-classes
(gen_random_uuid(),
 'Recursive Sealed Class Eval', 'Evaluación Recursiva con Sealed Class',
 'Model expressions: sealed class Expr with Num(val v: Int), Add(val l: Expr, val r: Expr), Mul(val l: Expr, val r: Expr). Write eval(e: Expr): Int. Print eval(Mul(Add(Num(2),Num(3)),Num(4))).',
 'Modela expresiones: sealed class Expr con Num(val v: Int), Add(val l: Expr, val r: Expr), Mul(val l: Expr, val r: Expr). Escribe eval(e: Expr): Int. Imprime eval(Mul(Add(Num(2),Num(3)),Num(4))).',
 'kotlin', 5, 'sealed-classes',
 'fun main() {\n    println(eval(Mul(Add(Num(2), Num(3)), Num(4))))\n}\n\n// define sealed class and eval here',
 '20',
 3,
 'eval is recursive: Num returns v, Add returns eval(l)+eval(r), Mul returns eval(l)*eval(r).', 'eval es recursivo: Num retorna v, Add retorna eval(l)+eval(r), Mul retorna eval(l)*eval(r).',
 'Use a when expression with is Num, is Add, is Mul branches.', 'Usa una expresión when con ramas is Num, is Add, is Mul.',
 '(2+3)*4 = 5*4 = 20', '(2+3)*4 = 5*4 = 20',
 100, 10, now()),

-- 93. extension-functions
(gen_random_uuid(),
 'DSL Builder with Extension Lambdas', 'Builder DSL con Lambdas de Extensión',
 'Build a minimal HTML DSL. Create class Tag(val name: String) with fun text(s: String) that prints "<name>s</name>". Write fun div(block: Tag.() -> Unit). Call div { text("hello") }.',
 'Construye un DSL HTML mínimo. Crea class Tag(val name: String) con fun text(s: String) que imprima "<name>s</name>". Escribe fun div(block: Tag.() -> Unit). Llama a div { text("hello") }.',
 'kotlin', 5, 'extension-functions',
 'fun main() {\n    div { text("hello") }\n}\n\n// define Tag and div here',
 '<div>hello</div>',
 3,
 'Tag.() -> Unit is a lambda with receiver of type Tag.', 'Tag.() -> Unit es un lambda con receptor de tipo Tag.',
 'fun div(block: Tag.() -> Unit) = Tag("div").block()', 'fun div(block: Tag.() -> Unit) = Tag("div").block()',
 'Inside text: println("<$name>$s</$name>")', 'Dentro de text: println("<$name>$s</$name>")',
 100, 10, now()),

-- 94. coroutines
(gen_random_uuid(),
 'StateFlow', 'StateFlow',
 'Create a MutableStateFlow(0). In a coroutine increment it 3 times and collect the first 4 emissions (including initial), printing each.',
 'Crea un MutableStateFlow(0). En una corrutina incrementa 3 veces y recoge las primeras 4 emisiones (incluyendo la inicial), imprimiendo cada una.',
 'kotlin', 5, 'coroutines',
 'import kotlinx.coroutines.*\nimport kotlinx.coroutines.flow.*\n\nfun main() = runBlocking {\n    // your code\n}',
 '0\n1\n2\n3',
 3,
 'MutableStateFlow holds a value and emits on change.', 'MutableStateFlow mantiene un valor y emite al cambiar.',
 'Use .take(4).collect { println(it) } and launch { repeat(3){ flow.value++ } }.', 'Usa .take(4).collect { println(it) } y launch { repeat(3){ flow.value++ } }.',
 'val sf = MutableStateFlow(0); launch { repeat(3){ sf.value++ } }; sf.take(4).collect { println(it) }', 'val sf = MutableStateFlow(0); launch { repeat(3){ sf.value++ } }; sf.take(4).collect { println(it) }',
 100, 10, now()),

-- 95. lambdas
(gen_random_uuid(),
 'Operator Overloading', 'Sobrecarga de Operadores',
 'Create data class Vector(val x: Int, val y: Int). Overload operator fun plus(other: Vector). Print Vector(1,2) + Vector(3,4).',
 'Crea data class Vector(val x: Int, val y: Int). Sobrecarga operator fun plus(other: Vector). Imprime Vector(1,2) + Vector(3,4).',
 'kotlin', 5, 'lambdas',
 'fun main() {\n    println(Vector(1, 2) + Vector(3, 4))\n}\n\n// define Vector here',
 'Vector(x=4, y=6)',
 3,
 'Prefix the function with the operator keyword to overload +.', 'Prefija la función con la palabra clave operator para sobrecargar +.',
 'operator fun plus(other: Vector) = Vector(x + other.x, y + other.y)', 'operator fun plus(other: Vector) = Vector(x + other.x, y + other.y)',
 'data class provides toString() automatically.', 'data class provee toString() automáticamente.',
 100, 10, now()),

-- 96. scope-functions
(gen_random_uuid(),
 'Lazy Initialization', 'Inicialización Perezosa',
 'Declare val expensiveValue: String by lazy { println("computing..."); "result" }. Print expensiveValue twice and verify "computing..." appears only once.',
 'Declara val expensiveValue: String by lazy { println("computing..."); "result" }. Imprime expensiveValue dos veces y verifica que "computing..." aparece solo una vez.',
 'kotlin', 5, 'scope-functions',
 'fun main() {\n    // your code\n}',
 'computing...\nresult\nresult',
 3,
 'by lazy delegates the initializer to a lazy computation, run only once on first access.', 'by lazy delega el inicializador a un cálculo perezoso, ejecutado solo una vez en el primer acceso.',
 'val expensiveValue: String by lazy { println("computing..."); "result" }', 'val expensiveValue: String by lazy { println("computing..."); "result" }',
 'Accessing expensiveValue a second time returns the cached value without re-computing.', 'Acceder a expensiveValue por segunda vez devuelve el valor en caché sin recalcular.',
 100, 10, now()),

-- 97. collections
(gen_random_uuid(),
 'Sequence for Lazy Evaluation', 'Secuencia para Evaluación Perezosa',
 'Use generateSequence starting at 1 with { it + 1 }. Take the first 5 odd numbers and print their sum.',
 'Usa generateSequence comenzando en 1 con { it + 1 }. Toma los primeros 5 números impares e imprime su suma.',
 'kotlin', 5, 'collections',
 'fun main() {\n    // your code\n}',
 '25',
 3,
 'generateSequence creates an infinite lazy sequence; filter and take to bound it.', 'generateSequence crea una secuencia infinita perezosa; usa filter y take para delimitarla.',
 'generateSequence(1) { it + 1 }.filter { it % 2 != 0 }.take(5)', 'generateSequence(1) { it + 1 }.filter { it % 2 != 0 }.take(5)',
 'Sum with .sum(). Odds 1+3+5+7+9 = 25.', 'Suma con .sum(). Impares 1+3+5+7+9 = 25.',
 100, 10, now()),

-- 98. sealed-classes
(gen_random_uuid(),
 'Sealed Interface', 'Interfaz Sellada',
 'Declare sealed interface Notification with data class Email(val to: String) and data class SMS(val phone: String). Write fun send(n: Notification) using when. Print send(Email("a@b.com")).',
 'Declara sealed interface Notification con data class Email(val to: String) y data class SMS(val phone: String). Escribe fun send(n: Notification) usando when. Imprime send(Email("a@b.com")).',
 'kotlin', 5, 'sealed-classes',
 'fun main() {\n    send(Email("a@b.com"))\n}\n\n// define sealed interface and send here',
 'Sending email to a@b.com',
 3,
 'sealed interface works like sealed class but allows multiple inheritance.', 'sealed interface funciona como sealed class pero permite herencia múltiple.',
 'data class Email(val to: String): Notification', 'data class Email(val to: String): Notification',
 'is Email -> println("Sending email to ${n.to}")', 'is Email -> println("Sending email to ${n.to}")',
 100, 10, now()),

-- 99. coroutines
(gen_random_uuid(),
 'withContext Dispatcher Switch', 'Cambio de Dispatcher con withContext',
 'Inside runBlocking, use withContext(Dispatchers.Default) to compute the sum of 1..1000000 and print it.',
 'Dentro de runBlocking, usa withContext(Dispatchers.Default) para calcular la suma de 1..1000000 e imprímela.',
 'kotlin', 5, 'coroutines',
 'import kotlinx.coroutines.*\n\nfun main() = runBlocking {\n    // your code\n}',
 '500000500000',
 3,
 'withContext switches the coroutine to a different dispatcher for its block.', 'withContext cambia la corrutina a un dispatcher diferente para su bloque.',
 'val sum = withContext(Dispatchers.Default) { (1L..1000000L).sum() }', 'val sum = withContext(Dispatchers.Default) { (1L..1000000L).sum() }',
 'println(sum)', 'println(sum)',
 100, 10, now()),

-- 100. smart-casts
(gen_random_uuid(),
 'Sealed Class with Smart Cast and Fold', 'Sealed Class con Smart Cast y Fold',
 'Define sealed class Expr: Num(val v: Int), Add(val l: Expr, val r: Expr). Write fun eval(e: Expr): Int using fold-style recursion. Also write fun stringify(e: Expr): String that produces "(l + r)" or "v". Print stringify(Add(Num(3), Add(Num(4), Num(5)))) and eval(Add(Num(3), Add(Num(4), Num(5)))).',
 'Define sealed class Expr: Num(val v: Int), Add(val l: Expr, val r: Expr). Escribe fun eval(e: Expr): Int con recursión. También escribe fun stringify(e: Expr): String que produzca "(l + r)" o "v". Imprime stringify(Add(Num(3), Add(Num(4), Num(5)))) y eval(Add(Num(3), Add(Num(4), Num(5)))).',
 'kotlin', 5, 'smart-casts',
 'fun main() {\n    val e = Add(Num(3), Add(Num(4), Num(5)))\n    println(stringify(e))\n    println(eval(e))\n}\n\n// define sealed class, eval, and stringify here',
 '(3 + (4 + 5))\n12',
 3,
 'Both eval and stringify use when(e) with is Num and is Add branches with smart casts.', 'Tanto eval como stringify usan when(e) con ramas is Num e is Add con smart casts.',
 'stringify: is Num -> "${e.v}"; is Add -> "(${stringify(e.l)} + ${stringify(e.r)})"', 'stringify: is Num -> "${e.v}"; is Add -> "(${stringify(e.l)} + ${stringify(e.r)})"',
 'eval: is Num -> e.v; is Add -> eval(e.l) + eval(e.r)', 'eval: is Num -> e.v; is Add -> eval(e.l) + eval(e.r)',
 100, 10, now())

ON CONFLICT DO NOTHING;

COMMIT;
