-- 056_exercises_ruby.sql
-- 100 Ruby exercises, bilingual EN+ES
-- Distribution: diff1:25, diff2:25, diff3:25, diff4:15, diff5:10
-- Points: 10/20/30/50/100 | Penalty: 3/3/5/10/10
-- Focus: blocks, procs, lambdas, symbols, hashes, mixins, modules,
--        attr_accessor, string interpolation, each/map/select,
--        classes, inheritance, Enumerable, regular expressions, gems

BEGIN;

INSERT INTO exercises (
  id, title_en, title_es, description_en, description_es,
  language, difficulty, category,
  starter_code, expected_output,
  hint_count, hint_1_en, hint_1_es, hint_2_en, hint_2_es, hint_3_en, hint_3_es,
  points, hints_used_penalty, created_at
) VALUES

-- ============================================================
-- DIFFICULTY 1 — 25 exercises (points: 10, penalty: 3)
-- ============================================================

-- 1
(gen_random_uuid(),
 'Hello World', 'Hola Mundo',
 'Print the string "Hello, World!" to the console.',
 'Imprime la cadena "Hello, World!" en la consola.',
 'ruby', 1, 'basics',
 '# your code here',
 'Hello, World!',
 3,
 'Use the puts method to print a line.', 'Usa el método puts para imprimir una línea.',
 'puts prints its argument followed by a newline.', 'puts imprime su argumento seguido de una nueva línea.',
 'puts "Hello, World!"', 'puts "Hello, World!"',
 10, 3, now()),

-- 2
(gen_random_uuid(),
 'String Interpolation', 'Interpolación de Cadenas',
 'Given name = "Ruby", use string interpolation to print "Hello, Ruby!".',
 'Dado name = "Ruby", usa interpolación de cadenas para imprimir "Hello, Ruby!".',
 'ruby', 1, 'strings',
 'name = "Ruby"
# your code here',
 'Hello, Ruby!',
 3,
 'String interpolation uses #{ } inside double-quoted strings.', 'La interpolación de cadenas usa #{ } dentro de cadenas con comillas dobles.',
 'The syntax is "Hello, #{variable}!".', 'La sintaxis es "Hello, #{variable}!".',
 'puts "Hello, #{name}!"', 'puts "Hello, #{name}!"',
 10, 3, now()),

-- 3
(gen_random_uuid(),
 'Integer Arithmetic', 'Aritmética de Enteros',
 'Print the result of 7 multiplied by 6.',
 'Imprime el resultado de 7 multiplicado por 6.',
 'ruby', 1, 'basics',
 '# your code here',
 '42',
 3,
 'Use the * operator for multiplication.', 'Usa el operador * para la multiplicación.',
 'puts evaluates its argument before printing.', 'puts evalúa su argumento antes de imprimir.',
 'puts 7 * 6', 'puts 7 * 6',
 10, 3, now()),

-- 4
(gen_random_uuid(),
 'Array Creation', 'Creación de Arreglos',
 'Create an array containing the integers 1 through 5 and print it.',
 'Crea un arreglo con los enteros del 1 al 5 e imprímelo.',
 'ruby', 1, 'arrays',
 '# your code here',
 '[1, 2, 3, 4, 5]',
 3,
 'Array literals use square brackets with comma-separated values.', 'Los literales de arreglo usan corchetes con valores separados por comas.',
 'Use p instead of puts to see the array representation.', 'Usa p en lugar de puts para ver la representación del arreglo.',
 'p [1, 2, 3, 4, 5]', 'p [1, 2, 3, 4, 5]',
 10, 3, now()),

-- 5
(gen_random_uuid(),
 'Hash Creation', 'Creación de Hashes',
 'Create a hash with keys :name and :age mapped to "Alice" and 30, then print it.',
 'Crea un hash con claves :name y :age mapeadas a "Alice" y 30, luego imprímelo.',
 'ruby', 1, 'hashes',
 '# your code here',
 '{:name=>"Alice", :age=>30}',
 3,
 'Hash literals use curly braces with key => value pairs.', 'Los literales de hash usan llaves con pares clave => valor.',
 'Symbol keys use a colon prefix: :name.', 'Las claves símbolo usan el prefijo dos puntos: :name.',
 'p({ name: "Alice", age: 30 })', 'p({ name: "Alice", age: 30 })',
 10, 3, now()),

-- 6
(gen_random_uuid(),
 'Symbol Basics', 'Fundamentos de Símbolos',
 'Print the class of the symbol :hello.',
 'Imprime la clase del símbolo :hello.',
 'ruby', 1, 'symbols',
 '# your code here',
 'Symbol',
 3,
 'Every Ruby object responds to .class.', 'Todo objeto Ruby responde a .class.',
 'Use puts :hello.class.', 'Usa puts :hello.class.',
 'puts :hello.class', 'puts :hello.class',
 10, 3, now()),

-- 7
(gen_random_uuid(),
 'String Length', 'Longitud de Cadena',
 'Print the number of characters in the string "Philosopher".',
 'Imprime el número de caracteres en la cadena "Philosopher".',
 'ruby', 1, 'strings',
 '# your code here',
 '11',
 3,
 'Strings have a .length method.', 'Las cadenas tienen un método .length.',
 'Call .length on the string literal or a variable.', 'Llama .length sobre el literal de cadena o una variable.',
 'puts "Philosopher".length', 'puts "Philosopher".length',
 10, 3, now()),

-- 8
(gen_random_uuid(),
 'Conditional If/Else', 'Condicional If/Else',
 'Given x = 10, print "positive" if x > 0, otherwise print "non-positive".',
 'Dado x = 10, imprime "positive" si x > 0, de lo contrario imprime "non-positive".',
 'ruby', 1, 'control-flow',
 'x = 10
# your code here',
 'positive',
 3,
 'Use an if/else block ending with end.', 'Usa un bloque if/else que termina con end.',
 'if x > 0 ... else ... end', 'if x > 0 ... else ... end',
 'if x > 0 then puts "positive" else puts "non-positive" end', 'if x > 0 then puts "positive" else puts "non-positive" end',
 10, 3, now()),

-- 9
(gen_random_uuid(),
 'Times Loop', 'Bucle Times',
 'Use the times method to print "Ruby" exactly 3 times.',
 'Usa el método times para imprimir "Ruby" exactamente 3 veces.',
 'ruby', 1, 'blocks',
 '# your code here',
 'Ruby
Ruby
Ruby',
 3,
 'Integer#times takes a block and executes it N times.', 'Integer#times toma un bloque y lo ejecuta N veces.',
 'The syntax is N.times { block }.', 'La sintaxis es N.times { bloque }.',
 '3.times { puts "Ruby" }', '3.times { puts "Ruby" }',
 10, 3, now()),

-- 10
(gen_random_uuid(),
 'Array Each', 'Each en Arreglos',
 'Given fruits = ["apple", "banana", "cherry"], print each element on its own line.',
 'Dado fruits = ["apple", "banana", "cherry"], imprime cada elemento en su propia línea.',
 'ruby', 1, 'blocks',
 'fruits = ["apple", "banana", "cherry"]
# your code here',
 'apple
banana
cherry',
 3,
 'Use the .each method with a block.', 'Usa el método .each con un bloque.',
 'The block parameter receives each element.', 'El parámetro del bloque recibe cada elemento.',
 'fruits.each { |f| puts f }', 'fruits.each { |f| puts f }',
 10, 3, now()),

-- 11
(gen_random_uuid(),
 'String Upcase', 'Cadena en Mayúsculas',
 'Print the string "ruby on rails" in all uppercase.',
 'Imprime la cadena "ruby on rails" completamente en mayúsculas.',
 'ruby', 1, 'strings',
 '# your code here',
 'RUBY ON RAILS',
 3,
 'Strings have an .upcase method.', 'Las cadenas tienen un método .upcase.',
 'Call .upcase on the string literal.', 'Llama .upcase sobre el literal de cadena.',
 'puts "ruby on rails".upcase', 'puts "ruby on rails".upcase',
 10, 3, now()),

-- 12
(gen_random_uuid(),
 'Array Push', 'Push en Arreglos',
 'Start with an empty array, push the values 1, 2, 3 into it, then print it.',
 'Comienza con un arreglo vacío, inserta los valores 1, 2, 3 en él, luego imprímelo.',
 'ruby', 1, 'arrays',
 '# your code here',
 '[1, 2, 3]',
 3,
 'Use Array#push or the shovel operator <<.', 'Usa Array#push o el operador pala <<.',
 'arr << value adds a value to the end.', 'arr << valor agrega un valor al final.',
 'arr = []; arr << 1; arr << 2; arr << 3; p arr', 'arr = []; arr << 1; arr << 2; arr << 3; p arr',
 10, 3, now()),

-- 13
(gen_random_uuid(),
 'Hash Access', 'Acceso a Hash',
 'Given h = { color: "blue", size: 42 }, print the value associated with :color.',
 'Dado h = { color: "blue", size: 42 }, imprime el valor asociado a :color.',
 'ruby', 1, 'hashes',
 'h = { color: "blue", size: 42 }
# your code here',
 'blue',
 3,
 'Access hash values with square bracket notation.', 'Accede a los valores del hash con notación de corchetes.',
 'Use h[:key] to retrieve a value by symbol key.', 'Usa h[:clave] para recuperar un valor por clave símbolo.',
 'puts h[:color]', 'puts h[:color]',
 10, 3, now()),

-- 14
(gen_random_uuid(),
 'String Reverse', 'Cadena al Revés',
 'Print the reverse of the string "palindrome".',
 'Imprime el reverso de la cadena "palindrome".',
 'ruby', 1, 'strings',
 '# your code here',
 'emordnilap',
 3,
 'Strings have a .reverse method.', 'Las cadenas tienen un método .reverse.',
 'Call .reverse on the string.', 'Llama .reverse sobre la cadena.',
 'puts "palindrome".reverse', 'puts "palindrome".reverse',
 10, 3, now()),

-- 15
(gen_random_uuid(),
 'Array Length', 'Longitud de Arreglo',
 'Print the number of elements in the array [10, 20, 30, 40, 50].',
 'Imprime el número de elementos en el arreglo [10, 20, 30, 40, 50].',
 'ruby', 1, 'arrays',
 '# your code here',
 '5',
 3,
 'Arrays have a .length or .size method.', 'Los arreglos tienen un método .length o .size.',
 'Call .length on the array literal.', 'Llama .length sobre el literal del arreglo.',
 'puts [10, 20, 30, 40, 50].length', 'puts [10, 20, 30, 40, 50].length',
 10, 3, now()),

-- 16
(gen_random_uuid(),
 'Range to Array', 'Rango a Arreglo',
 'Convert the range (1..5) to an array and print it.',
 'Convierte el rango (1..5) a un arreglo e imprímelo.',
 'ruby', 1, 'arrays',
 '# your code here',
 '[1, 2, 3, 4, 5]',
 3,
 'Range has a .to_a method that converts it to an array.', 'Range tiene un método .to_a que lo convierte en un arreglo.',
 'p (1..5).to_a', 'p (1..5).to_a',
 'p (1..5).to_a', 'p (1..5).to_a',
 10, 3, now()),

-- 17
(gen_random_uuid(),
 'String Include?', 'Cadena Include?',
 'Print true if "programming" includes the substring "gram".',
 'Imprime true si "programming" incluye la subcadena "gram".',
 'ruby', 1, 'strings',
 '# your code here',
 'true',
 3,
 'Strings have an .include? method.', 'Las cadenas tienen un método .include?.',
 'The method returns a boolean.', 'El método retorna un booleano.',
 'puts "programming".include?("gram")', 'puts "programming".include?("gram")',
 10, 3, now()),

-- 18
(gen_random_uuid(),
 'Nil Check', 'Verificación de Nil',
 'Assign nil to x and print whether x is nil.',
 'Asigna nil a x e imprime si x es nil.',
 'ruby', 1, 'basics',
 'x = nil
# your code here',
 'true',
 3,
 'Use the .nil? method to check for nil.', 'Usa el método .nil? para verificar nil.',
 'puts x.nil?', 'puts x.nil?',
 'puts x.nil?', 'puts x.nil?',
 10, 3, now()),

-- 19
(gen_random_uuid(),
 'Integer to String', 'Entero a Cadena',
 'Convert the integer 42 to a string and print its class.',
 'Convierte el entero 42 a cadena e imprime su clase.',
 'ruby', 1, 'basics',
 '# your code here',
 'String',
 3,
 'Use the .to_s method to convert to string.', 'Usa el método .to_s para convertir a cadena.',
 'Call .class on the result.', 'Llama .class sobre el resultado.',
 'puts 42.to_s.class', 'puts 42.to_s.class',
 10, 3, now()),

-- 20
(gen_random_uuid(),
 'Array First and Last', 'Primero y Último del Arreglo',
 'Given arr = [10, 20, 30, 40], print the first and last elements on separate lines.',
 'Dado arr = [10, 20, 30, 40], imprime el primer y el último elemento en líneas separadas.',
 'ruby', 1, 'arrays',
 'arr = [10, 20, 30, 40]
# your code here',
 '10
40',
 3,
 'Arrays have .first and .last methods.', 'Los arreglos tienen los métodos .first y .last.',
 'Call them separately with puts.', 'Llámalos por separado con puts.',
 'puts arr.first; puts arr.last', 'puts arr.first; puts arr.last',
 10, 3, now()),

-- 21
(gen_random_uuid(),
 'Hash Keys and Values', 'Claves y Valores del Hash',
 'Given h = { a: 1, b: 2, c: 3 }, print its keys as an array.',
 'Dado h = { a: 1, b: 2, c: 3 }, imprime sus claves como un arreglo.',
 'ruby', 1, 'hashes',
 'h = { a: 1, b: 2, c: 3 }
# your code here',
 '[:a, :b, :c]',
 3,
 'Hash has a .keys method.', 'Hash tiene un método .keys.',
 'Use p to print the array representation.', 'Usa p para imprimir la representación del arreglo.',
 'p h.keys', 'p h.keys',
 10, 3, now()),

-- 22
(gen_random_uuid(),
 'String Split', 'Dividir Cadena',
 'Split the string "one two three" by spaces and print the resulting array.',
 'Divide la cadena "one two three" por espacios e imprime el arreglo resultante.',
 'ruby', 1, 'strings',
 '# your code here',
 '["one", "two", "three"]',
 3,
 'String has a .split method that accepts a delimiter.', 'String tiene un método .split que acepta un delimitador.',
 'Pass a space " " as the delimiter.', 'Pasa un espacio " " como delimitador.',
 'p "one two three".split(" ")', 'p "one two three".split(" ")',
 10, 3, now()),

-- 23
(gen_random_uuid(),
 'Ternary Operator', 'Operador Ternario',
 'Use the ternary operator to print "even" if 8 is even, otherwise "odd".',
 'Usa el operador ternario para imprimir "even" si 8 es par, de lo contrario "odd".',
 'ruby', 1, 'control-flow',
 '# your code here',
 'even',
 3,
 'The ternary syntax is condition ? value_if_true : value_if_false.', 'La sintaxis ternaria es condición ? valor_si_verdadero : valor_si_falso.',
 'Use the modulo operator % to check evenness.', 'Usa el operador módulo % para comprobar si es par.',
 'puts 8 % 2 == 0 ? "even" : "odd"', 'puts 8 % 2 == 0 ? "even" : "odd"',
 10, 3, now()),

-- 24
(gen_random_uuid(),
 'String Join', 'Unir Cadenas',
 'Join the array ["Ruby", "is", "fun"] into a single string separated by spaces and print it.',
 'Une el arreglo ["Ruby", "is", "fun"] en una sola cadena separada por espacios e imprímela.',
 'ruby', 1, 'strings',
 '# your code here',
 'Ruby is fun',
 3,
 'Array has a .join method that accepts a separator string.', 'Array tiene un método .join que acepta una cadena separadora.',
 'Pass " " as the argument to join with spaces.', 'Pasa " " como argumento para unir con espacios.',
 'puts ["Ruby", "is", "fun"].join(" ")', 'puts ["Ruby", "is", "fun"].join(" ")',
 10, 3, now()),

-- 25
(gen_random_uuid(),
 'Boolean Methods', 'Métodos Booleanos',
 'Print whether 0 is zero and whether 1 is positive, each on its own line.',
 'Imprime si 0 es cero y si 1 es positivo, cada uno en su propia línea.',
 'ruby', 1, 'basics',
 '# your code here',
 'true
true',
 3,
 'Integers have .zero? and .positive? predicate methods.', 'Los enteros tienen los métodos predicado .zero? y .positive?.',
 'Call each method with puts.', 'Llama cada método con puts.',
 'puts 0.zero?; puts 1.positive?', 'puts 0.zero?; puts 1.positive?',
 10, 3, now()),

-- ============================================================
-- DIFFICULTY 2 — 25 exercises (points: 20, penalty: 3)
-- ============================================================

-- 26
(gen_random_uuid(),
 'Array Map', 'Map en Arreglos',
 'Given nums = [1, 2, 3, 4], use map to produce an array of each value doubled and print it.',
 'Dado nums = [1, 2, 3, 4], usa map para producir un arreglo con cada valor duplicado e imprímelo.',
 'ruby', 2, 'blocks',
 'nums = [1, 2, 3, 4]
# your code here',
 '[2, 4, 6, 8]',
 3,
 'Array#map transforms each element using a block.', 'Array#map transforma cada elemento usando un bloque.',
 'The block receives the element and should return the new value.', 'El bloque recibe el elemento y debe retornar el nuevo valor.',
 'p nums.map { |n| n * 2 }', 'p nums.map { |n| n * 2 }',
 20, 3, now()),

-- 27
(gen_random_uuid(),
 'Array Select', 'Select en Arreglos',
 'Given nums = [1, 2, 3, 4, 5, 6], use select to keep only even numbers and print the result.',
 'Dado nums = [1, 2, 3, 4, 5, 6], usa select para conservar solo los números pares e imprime el resultado.',
 'ruby', 2, 'blocks',
 'nums = [1, 2, 3, 4, 5, 6]
# your code here',
 '[2, 4, 6]',
 3,
 'Array#select keeps elements for which the block returns true.', 'Array#select conserva los elementos para los cuales el bloque retorna true.',
 'Use the modulo operator to test evenness: n % 2 == 0.', 'Usa el operador módulo para probar si es par: n % 2 == 0.',
 'p nums.select { |n| n % 2 == 0 }', 'p nums.select { |n| n % 2 == 0 }',
 20, 3, now()),

-- 28
(gen_random_uuid(),
 'Array Reduce', 'Reduce en Arreglos',
 'Given nums = [1, 2, 3, 4, 5], use reduce to compute the sum and print it.',
 'Dado nums = [1, 2, 3, 4, 5], usa reduce para calcular la suma e imprímela.',
 'ruby', 2, 'blocks',
 'nums = [1, 2, 3, 4, 5]
# your code here',
 '15',
 3,
 'Array#reduce (or inject) folds the array into a single value.', 'Array#reduce (o inject) pliega el arreglo en un único valor.',
 'The block receives an accumulator and the current element.', 'El bloque recibe un acumulador y el elemento actual.',
 'puts nums.reduce(0) { |sum, n| sum + n }', 'puts nums.reduce(0) { |sum, n| sum + n }',
 20, 3, now()),

-- 29
(gen_random_uuid(),
 'Hash Iteration', 'Iteración de Hash',
 'Given h = { a: 1, b: 2, c: 3 }, print each key-value pair as "key: value" on its own line.',
 'Dado h = { a: 1, b: 2, c: 3 }, imprime cada par clave-valor como "key: value" en su propia línea.',
 'ruby', 2, 'hashes',
 'h = { a: 1, b: 2, c: 3 }
# your code here',
 'a: 1
b: 2
c: 3',
 3,
 'Hash#each yields key and value to the block.', 'Hash#each entrega la clave y el valor al bloque.',
 'Use two block parameters: |k, v|.', 'Usa dos parámetros de bloque: |k, v|.',
 'h.each { |k, v| puts "#{k}: #{v}" }', 'h.each { |k, v| puts "#{k}: #{v}" }',
 20, 3, now()),

-- 30
(gen_random_uuid(),
 'Define a Method', 'Definir un Método',
 'Define a method greet that takes a name and prints "Hello, <name>!". Call it with "World".',
 'Define un método greet que tome un nombre e imprima "Hello, <name>!". Llámalo con "World".',
 'ruby', 2, 'methods',
 '# your code here',
 'Hello, World!',
 3,
 'Use the def keyword followed by the method name and parameter list.', 'Usa la palabra clave def seguida del nombre del método y la lista de parámetros.',
 'Close the method definition with end.', 'Cierra la definición del método con end.',
 'def greet(name); puts "Hello, #{name}!"; end; greet("World")', 'def greet(name); puts "Hello, #{name}!"; end; greet("World")',
 20, 3, now()),

-- 31
(gen_random_uuid(),
 'Default Parameter', 'Parámetro Por Defecto',
 'Define a method power(base, exp=2) that returns base raised to exp. Print power(3) and power(2,3).',
 'Define un método power(base, exp=2) que retorne base elevado a exp. Imprime power(3) y power(2,3).',
 'ruby', 2, 'methods',
 '# your code here',
 '9
8',
 3,
 'Assign a default value in the parameter list: def method(param=default).', 'Asigna un valor por defecto en la lista de parámetros: def method(param=default).',
 'Use the ** operator for exponentiation.', 'Usa el operador ** para la exponenciación.',
 'def power(base, exp=2); base ** exp; end; puts power(3); puts power(2,3)', 'def power(base, exp=2); base ** exp; end; puts power(3); puts power(2,3)',
 20, 3, now()),

-- 32
(gen_random_uuid(),
 'Block with yield', 'Bloque con yield',
 'Define a method twice that yields to its block two times. Call it to print "hello" twice.',
 'Define un método twice que ceda a su bloque dos veces. Llámalo para imprimir "hello" dos veces.',
 'ruby', 2, 'blocks',
 '# your code here',
 'hello
hello',
 3,
 'Use yield inside a method to execute the block passed by the caller.', 'Usa yield dentro de un método para ejecutar el bloque pasado por el llamador.',
 'Call yield twice to execute the block two times.', 'Llama yield dos veces para ejecutar el bloque dos veces.',
 'def twice; yield; yield; end; twice { puts "hello" }', 'def twice; yield; yield; end; twice { puts "hello" }',
 20, 3, now()),

-- 33
(gen_random_uuid(),
 'Proc Creation', 'Creación de Proc',
 'Create a Proc that squares its argument and print the result of calling it with 5.',
 'Crea un Proc que eleve al cuadrado su argumento e imprime el resultado de llamarlo con 5.',
 'ruby', 2, 'procs-lambdas',
 '# your code here',
 '25',
 3,
 'Create a Proc with Proc.new { |x| ... } or proc { |x| ... }.', 'Crea un Proc con Proc.new { |x| ... } o proc { |x| ... }.',
 'Call a Proc with .call(argument).', 'Llama a un Proc con .call(argumento).',
 'sq = proc { |x| x * x }; puts sq.call(5)', 'sq = proc { |x| x * x }; puts sq.call(5)',
 20, 3, now()),

-- 34
(gen_random_uuid(),
 'Lambda Creation', 'Creación de Lambda',
 'Create a lambda that adds 10 to its argument and print the result of calling it with 32.',
 'Crea una lambda que sume 10 a su argumento e imprime el resultado de llamarla con 32.',
 'ruby', 2, 'procs-lambdas',
 '# your code here',
 '42',
 3,
 'Create a lambda with lambda { |x| ... } or the stabby syntax ->(x) { ... }.', 'Crea una lambda con lambda { |x| ... } o la sintaxis flecha ->(x) { ... }.',
 'Call it with .call(argument).', 'Llámala con .call(argumento).',
 'add10 = ->(x) { x + 10 }; puts add10.call(32)', 'add10 = ->(x) { x + 10 }; puts add10.call(32)',
 20, 3, now()),

-- 35
(gen_random_uuid(),
 'Class Definition', 'Definición de Clase',
 'Define a Dog class with an initialize method accepting a name. Create a Dog named "Rex" and print its name.',
 'Define una clase Dog con un método initialize que acepte un nombre. Crea un Dog llamado "Rex" e imprime su nombre.',
 'ruby', 2, 'classes',
 '# your code here',
 'Rex',
 3,
 'Use class ClassName ... end to define a class.', 'Usa class NombreClase ... end para definir una clase.',
 'Store the name in an instance variable @name and expose it.', 'Almacena el nombre en una variable de instancia @name y expónla.',
 'class Dog; def initialize(name); @name = name; end; def name; @name; end; end; puts Dog.new("Rex").name', 'class Dog; def initialize(name); @name = name; end; def name; @name; end; end; puts Dog.new("Rex").name',
 20, 3, now()),

-- 36
(gen_random_uuid(),
 'attr_accessor', 'attr_accessor',
 'Define a Person class with attr_accessor for :name. Create an instance, set name to "Alice", then print it.',
 'Define una clase Person con attr_accessor para :name. Crea una instancia, establece name en "Alice" y luego imprímelo.',
 'ruby', 2, 'classes',
 '# your code here',
 'Alice',
 3,
 'attr_accessor :name creates both getter and setter methods automatically.', 'attr_accessor :name crea automáticamente los métodos getter y setter.',
 'Use person.name = "Alice" to call the setter.', 'Usa person.name = "Alice" para llamar al setter.',
 'class Person; attr_accessor :name; end; p = Person.new; p.name = "Alice"; puts p.name', 'class Person; attr_accessor :name; end; p = Person.new; p.name = "Alice"; puts p.name',
 20, 3, now()),

-- 37
(gen_random_uuid(),
 'Array Sort', 'Ordenar Arreglo',
 'Sort the array [3, 1, 4, 1, 5, 9, 2, 6] and print it.',
 'Ordena el arreglo [3, 1, 4, 1, 5, 9, 2, 6] e imprímelo.',
 'ruby', 2, 'arrays',
 '# your code here',
 '[1, 1, 2, 3, 4, 5, 6, 9]',
 3,
 'Array#sort returns a new sorted array.', 'Array#sort retorna un nuevo arreglo ordenado.',
 'Use p to print the array representation.', 'Usa p para imprimir la representación del arreglo.',
 'p [3, 1, 4, 1, 5, 9, 2, 6].sort', 'p [3, 1, 4, 1, 5, 9, 2, 6].sort',
 20, 3, now()),

-- 38
(gen_random_uuid(),
 'Array Uniq', 'Únicos en Arreglo',
 'Remove duplicates from [1, 2, 2, 3, 3, 3, 4] and print the result.',
 'Elimina duplicados de [1, 2, 2, 3, 3, 3, 4] e imprime el resultado.',
 'ruby', 2, 'arrays',
 '# your code here',
 '[1, 2, 3, 4]',
 3,
 'Array#uniq returns a new array with duplicates removed.', 'Array#uniq retorna un nuevo arreglo sin duplicados.',
 'p [1, 2, 2, 3, 3, 3, 4].uniq', 'p [1, 2, 2, 3, 3, 3, 4].uniq',
 'p [1, 2, 2, 3, 3, 3, 4].uniq', 'p [1, 2, 2, 3, 3, 3, 4].uniq',
 20, 3, now()),

-- 39
(gen_random_uuid(),
 'Hash Merge', 'Combinar Hashes',
 'Merge { a: 1, b: 2 } and { b: 3, c: 4 } and print the result (second hash wins on conflict).',
 'Combina { a: 1, b: 2 } y { b: 3, c: 4 } e imprime el resultado (el segundo hash gana en conflicto).',
 'ruby', 2, 'hashes',
 '# your code here',
 '{:a=>1, :b=>3, :c=>4}',
 3,
 'Hash#merge returns a new hash combining both.', 'Hash#merge retorna un nuevo hash que combina ambos.',
 'When keys conflict, the value from the argument hash wins.', 'Cuando hay conflicto de claves, gana el valor del hash argumento.',
 'p({ a: 1, b: 2 }.merge({ b: 3, c: 4 }))', 'p({ a: 1, b: 2 }.merge({ b: 3, c: 4 }))',
 20, 3, now()),

-- 40
(gen_random_uuid(),
 'String Gsub', 'Gsub en Cadenas',
 'Replace all vowels in "Hello World" with "*" and print the result.',
 'Reemplaza todas las vocales en "Hello World" con "*" e imprime el resultado.',
 'ruby', 2, 'strings',
 '# your code here',
 'H*ll* W*rld',
 3,
 'Use String#gsub with a regex pattern.', 'Usa String#gsub con un patrón regex.',
 'A character class [aeiouAEIOU] matches any vowel.', 'Una clase de caracteres [aeiouAEIOU] coincide con cualquier vocal.',
 'puts "Hello World".gsub(/[aeiouAEIOU]/, "*")', 'puts "Hello World".gsub(/[aeiouAEIOU]/, "*")',
 20, 3, now()),

-- 41
(gen_random_uuid(),
 'Each With Index', 'Each con Índice',
 'Given words = ["a", "b", "c"], print each element with its index as "0: a", "1: b", "2: c".',
 'Dado words = ["a", "b", "c"], imprime cada elemento con su índice como "0: a", "1: b", "2: c".',
 'ruby', 2, 'blocks',
 'words = ["a", "b", "c"]
# your code here',
 '0: a
1: b
2: c',
 3,
 'Use Array#each_with_index to get both element and index.', 'Usa Array#each_with_index para obtener tanto el elemento como el índice.',
 'The block takes two parameters: |element, index|.', 'El bloque toma dos parámetros: |elemento, índice|.',
 'words.each_with_index { |w, i| puts "#{i}: #{w}" }', 'words.each_with_index { |w, i| puts "#{i}: #{w}" }',
 20, 3, now()),

-- 42
(gen_random_uuid(),
 'Multiline Block', 'Bloque Multilínea',
 'Use a do...end block with each to print the square of every number in [1, 2, 3, 4].',
 'Usa un bloque do...end con each para imprimir el cuadrado de cada número en [1, 2, 3, 4].',
 'ruby', 2, 'blocks',
 '# your code here',
 '1
4
9
16',
 3,
 'Multi-line blocks use do |param| ... end syntax.', 'Los bloques multilínea usan la sintaxis do |param| ... end.',
 'The block body can span multiple lines.', 'El cuerpo del bloque puede abarcar múltiples líneas.',
 '[1, 2, 3, 4].each do |n|
  puts n * n
end', '[1, 2, 3, 4].each do |n|
  puts n * n
end',
 20, 3, now()),

-- 43
(gen_random_uuid(),
 'Symbol to Proc', 'Símbolo a Proc',
 'Use the & symbol shorthand to upcase all strings in ["hello", "world"] and print the result.',
 'Usa el atajo & de símbolo para poner en mayúsculas todas las cadenas en ["hello", "world"] e imprime el resultado.',
 'ruby', 2, 'symbols',
 '# your code here',
 '["HELLO", "WORLD"]',
 3,
 'The &:method syntax converts a symbol to a Proc for use with map.', 'La sintaxis &:método convierte un símbolo en un Proc para usar con map.',
 'Use arr.map(&:upcase).', 'Usa arr.map(&:upcase).',
 'p ["hello", "world"].map(&:upcase)', 'p ["hello", "world"].map(&:upcase)',
 20, 3, now()),

-- 44
(gen_random_uuid(),
 'String Format', 'Formato de Cadena',
 'Use sprintf or format to print the float 3.14159 rounded to 2 decimal places as "3.14".',
 'Usa sprintf o format para imprimir el float 3.14159 redondeado a 2 decimales como "3.14".',
 'ruby', 2, 'strings',
 '# your code here',
 '3.14',
 3,
 'Use format("%.2f", value) to format a float.', 'Usa format("%.2f", valor) para formatear un float.',
 'The format specifier %.2f means float with 2 decimal places.', 'El especificador de formato %.2f significa float con 2 decimales.',
 'puts format("%.2f", 3.14159)', 'puts format("%.2f", 3.14159)',
 20, 3, now()),

-- 45
(gen_random_uuid(),
 'Array Flatten', 'Aplanar Arreglo',
 'Flatten the nested array [1, [2, 3], [4, [5, 6]]] and print the result.',
 'Aplana el arreglo anidado [1, [2, 3], [4, [5, 6]]] e imprime el resultado.',
 'ruby', 2, 'arrays',
 '# your code here',
 '[1, 2, 3, 4, 5, 6]',
 3,
 'Array#flatten recursively removes nested arrays.', 'Array#flatten elimina recursivamente los arreglos anidados.',
 'p [1, [2, 3], [4, [5, 6]]].flatten', 'p [1, [2, 3], [4, [5, 6]]].flatten',
 'p [1, [2, 3], [4, [5, 6]]].flatten', 'p [1, [2, 3], [4, [5, 6]]].flatten',
 20, 3, now()),

-- 46
(gen_random_uuid(),
 'Hash Select', 'Select en Hash',
 'Given scores = { alice: 90, bob: 55, carol: 80 }, select entries where value >= 80 and print the result.',
 'Dado scores = { alice: 90, bob: 55, carol: 80 }, selecciona entradas donde el valor >= 80 e imprime el resultado.',
 'ruby', 2, 'hashes',
 'scores = { alice: 90, bob: 55, carol: 80 }
# your code here',
 '{:alice=>90, :carol=>80}',
 3,
 'Hash#select filters key-value pairs using a block.', 'Hash#select filtra pares clave-valor usando un bloque.',
 'The block receives |key, value| and should return true to keep the pair.', 'El bloque recibe |clave, valor| y debe retornar true para conservar el par.',
 'p scores.select { |k, v| v >= 80 }', 'p scores.select { |k, v| v >= 80 }',
 20, 3, now()),

-- 47
(gen_random_uuid(),
 'While Loop', 'Bucle While',
 'Use a while loop to print numbers 1 through 5, one per line.',
 'Usa un bucle while para imprimir los números del 1 al 5, uno por línea.',
 'ruby', 2, 'control-flow',
 '# your code here',
 '1
2
3
4
5',
 3,
 'The while loop syntax is: while condition ... end.', 'La sintaxis del bucle while es: while condición ... end.',
 'Use a counter variable and increment it each iteration.', 'Usa una variable contador e incremértala en cada iteración.',
 'i = 1; while i <= 5; puts i; i += 1; end', 'i = 1; while i <= 5; puts i; i += 1; end',
 20, 3, now()),

-- 48
(gen_random_uuid(),
 'Regex Match', 'Coincidencia Regex',
 'Print true if the string "Ruby 3.2" matches the pattern that contains a digit.',
 'Imprime true si la cadena "Ruby 3.2" coincide con el patrón que contiene un dígito.',
 'ruby', 2, 'regex',
 '# your code here',
 'true',
 3,
 'Use the =~ operator or .match? to test a regex against a string.', 'Usa el operador =~ o .match? para probar un regex contra una cadena.',
 'The pattern /\d/ matches any single digit.', 'El patrón /\d/ coincide con cualquier dígito.',
 'puts "Ruby 3.2".match?(/\d/)', 'puts "Ruby 3.2".match?(/\d/)',
 20, 3, now()),

-- 49
(gen_random_uuid(),
 'Array Min and Max', 'Min y Max del Arreglo',
 'Given nums = [7, 2, 9, 1, 5], print the minimum and maximum values on separate lines.',
 'Dado nums = [7, 2, 9, 1, 5], imprime los valores mínimo y máximo en líneas separadas.',
 'ruby', 2, 'arrays',
 'nums = [7, 2, 9, 1, 5]
# your code here',
 '1
9',
 3,
 'Array has .min and .max methods.', 'Array tiene los métodos .min y .max.',
 'Call them with puts on separate lines.', 'Llámalos con puts en líneas separadas.',
 'puts nums.min; puts nums.max', 'puts nums.min; puts nums.max',
 20, 3, now()),

-- 50
(gen_random_uuid(),
 'String Strip', 'Limpiar Espacios',
 'Remove leading and trailing whitespace from "  hello world  " and print the result.',
 'Elimina los espacios al inicio y al final de "  hello world  " e imprime el resultado.',
 'ruby', 2, 'strings',
 '# your code here',
 'hello world',
 3,
 'String#strip removes leading and trailing whitespace.', 'String#strip elimina los espacios al inicio y al final.',
 'puts "  hello world  ".strip', 'puts "  hello world  ".strip',
 'puts "  hello world  ".strip', 'puts "  hello world  ".strip',
 20, 3, now()),

-- ============================================================
-- DIFFICULTY 3 — 25 exercises (points: 30, penalty: 5)
-- ============================================================

-- 51
(gen_random_uuid(),
 'Module as Namespace', 'Módulo como Espacio de Nombres',
 'Create a module MathUtils with a class method square. Call MathUtils.square(7) and print the result.',
 'Crea un módulo MathUtils con un método de clase square. Llama MathUtils.square(7) e imprime el resultado.',
 'ruby', 3, 'modules',
 '# your code here',
 '49',
 3,
 'Use module ModuleName ... end and define methods with def self.method_name.', 'Usa module NombreMódulo ... end y define métodos con def self.nombre_método.',
 'Class methods (module functions) are called directly on the module.', 'Los métodos de clase (funciones del módulo) se llaman directamente sobre el módulo.',
 'module MathUtils; def self.square(n); n * n; end; end; puts MathUtils.square(7)', 'module MathUtils; def self.square(n); n * n; end; end; puts MathUtils.square(7)',
 30, 5, now()),

-- 52
(gen_random_uuid(),
 'Mixin with Include', 'Mixin con Include',
 'Create a Greetable module with a method hello that prints "Hello from <class name>!". Include it in class Bot and call Bot.new.hello.',
 'Crea un módulo Greetable con un método hello que imprima "Hello from <nombre de clase>!". Inclúyelo en la clase Bot y llama Bot.new.hello.',
 'ruby', 3, 'mixins',
 '# your code here',
 'Hello from Bot!',
 3,
 'Use include ModuleName inside the class body to mix in instance methods.', 'Usa include NombreMódulo dentro del cuerpo de la clase para mezclar métodos de instancia.',
 'Inside the module method, use self.class.name to get the class name.', 'Dentro del método del módulo, usa self.class.name para obtener el nombre de la clase.',
 'module Greetable; def hello; puts "Hello from #{self.class.name}!"; end; end; class Bot; include Greetable; end; Bot.new.hello', 'module Greetable; def hello; puts "Hello from #{self.class.name}!"; end; end; class Bot; include Greetable; end; Bot.new.hello',
 30, 5, now()),

-- 53
(gen_random_uuid(),
 'Class Inheritance', 'Herencia de Clases',
 'Create Animal with a speak method printing "...". Create Dog inheriting Animal, overriding speak to print "Woof!". Call Dog.new.speak.',
 'Crea Animal con un método speak que imprima "...". Crea Dog heredando de Animal, sobreescribiendo speak para imprimir "Woof!". Llama Dog.new.speak.',
 'ruby', 3, 'inheritance',
 '# your code here',
 'Woof!',
 3,
 'Use class ChildClass < ParentClass to inherit.', 'Usa class ClaseHija < ClasePadre para heredar.',
 'Define a method with the same name in the subclass to override it.', 'Define un método con el mismo nombre en la subclase para sobreescribirlo.',
 'class Animal; def speak; puts "..."; end; end; class Dog < Animal; def speak; puts "Woof!"; end; end; Dog.new.speak', 'class Animal; def speak; puts "..."; end; end; class Dog < Animal; def speak; puts "Woof!"; end; end; Dog.new.speak',
 30, 5, now()),

-- 54
(gen_random_uuid(),
 'Super Keyword', 'Palabra Clave Super',
 'Create Vehicle with initialize(name). Create Car < Vehicle. In Car#initialize, call super and also set @type to "car". Print a new Car("Toyota") name and type.',
 'Crea Vehicle con initialize(name). Crea Car < Vehicle. En Car#initialize, llama super y también establece @type en "car". Imprime el nombre y tipo de un nuevo Car("Toyota").',
 'ruby', 3, 'inheritance',
 '# your code here',
 'Toyota
car',
 3,
 'Call super inside an overridden method to invoke the parent implementation.', 'Llama super dentro de un método sobreescrito para invocar la implementación del padre.',
 'super passes the same arguments automatically, or use super(args) explicitly.', 'super pasa los mismos argumentos automáticamente, o usa super(args) explícitamente.',
 'class Vehicle; attr_reader :name; def initialize(name); @name = name; end; end; class Car < Vehicle; attr_reader :type; def initialize(name); super; @type = "car"; end; end; c = Car.new("Toyota"); puts c.name; puts c.type', 'class Vehicle; attr_reader :name; def initialize(name); @name = name; end; end; class Car < Vehicle; attr_reader :type; def initialize(name); super; @type = "car"; end; end; c = Car.new("Toyota"); puts c.name; puts c.type',
 30, 5, now()),

-- 55
(gen_random_uuid(),
 'Enumerable Include', 'Include de Enumerable',
 'Create a NumberSet class that includes Enumerable, stores an array, and implements each. Use .min on an instance holding [3,1,4,1,5].',
 'Crea una clase NumberSet que incluya Enumerable, almacene un arreglo e implemente each. Usa .min en una instancia que tenga [3,1,4,1,5].',
 'ruby', 3, 'enumerable',
 '# your code here',
 '1',
 3,
 'Including Enumerable requires implementing the each method.', 'Incluir Enumerable requiere implementar el método each.',
 'Once each is defined, methods like min, max, sort become available.', 'Una vez definido each, métodos como min, max, sort quedan disponibles.',
 'class NumberSet; include Enumerable; def initialize(arr); @arr = arr; end; def each(&block); @arr.each(&block); end; end; puts NumberSet.new([3,1,4,1,5]).min', 'class NumberSet; include Enumerable; def initialize(arr); @arr = arr; end; def each(&block); @arr.each(&block); end; end; puts NumberSet.new([3,1,4,1,5]).min',
 30, 5, now()),

-- 56
(gen_random_uuid(),
 'Proc vs Lambda Return', 'Retorno: Proc vs Lambda',
 'Define a method test_lambda that uses a lambda returning 10 and returns the lambda result + 1. Print the result.',
 'Define un método test_lambda que use una lambda que retorne 10 y retorne el resultado de la lambda + 1. Imprime el resultado.',
 'ruby', 3, 'procs-lambdas',
 '# your code here',
 '11',
 3,
 'A return inside a lambda only exits the lambda, not the enclosing method.', 'Un return dentro de una lambda solo sale de la lambda, no del método que la contiene.',
 'Capture the lambda''s return value with .call and add to it.', 'Captura el valor de retorno de la lambda con .call y súmale.',
 'def test_lambda; l = lambda { return 10 }; l.call + 1; end; puts test_lambda', 'def test_lambda; l = lambda { return 10 }; l.call + 1; end; puts test_lambda',
 30, 5, now()),

-- 57
(gen_random_uuid(),
 'Method Missing', 'method_missing',
 'Create a class Ghost that overrides method_missing to print "Ghost: <method_name>" for any unknown call. Call ghost.boo.',
 'Crea una clase Ghost que sobreescriba method_missing para imprimir "Ghost: <nombre_método>" para cualquier llamada desconocida. Llama ghost.boo.',
 'ruby', 3, 'classes',
 '# your code here',
 'Ghost: boo',
 3,
 'Override method_missing(name, *args) to intercept undefined method calls.', 'Sobreescribe method_missing(name, *args) para interceptar llamadas a métodos no definidos.',
 'name is a symbol representing the called method name.', 'name es un símbolo que representa el nombre del método llamado.',
 'class Ghost; def method_missing(name, *args); puts "Ghost: #{name}"; end; end; Ghost.new.boo', 'class Ghost; def method_missing(name, *args); puts "Ghost: #{name}"; end; end; Ghost.new.boo',
 30, 5, now()),

-- 58
(gen_random_uuid(),
 'Comparable Mixin', 'Mixin Comparable',
 'Create a Weight class with a value attribute. Include Comparable and implement <=>. Prove sorting works by printing [Weight.new(3), Weight.new(1), Weight.new(2)].sort.map(&:value).',
 'Crea una clase Weight con atributo value. Incluye Comparable e implementa <=>. Prueba el ordenamiento imprimiendo [Weight.new(3), Weight.new(1), Weight.new(2)].sort.map(&:value).',
 'ruby', 3, 'mixins',
 '# your code here',
 '[1, 2, 3]',
 3,
 'Including Comparable requires defining the <=> (spaceship) operator.', 'Incluir Comparable requiere definir el operador <=> (nave espacial).',
 '<=> should return -1, 0, or 1 by comparing self to other.', '<=> debe retornar -1, 0 o 1 comparando self con other.',
 'class Weight; include Comparable; attr_reader :value; def initialize(v); @value = v; end; def <=>(other); value <=> other.value; end; end; p [Weight.new(3), Weight.new(1), Weight.new(2)].sort.map(&:value)', 'class Weight; include Comparable; attr_reader :value; def initialize(v); @value = v; end; def <=>(other); value <=> other.value; end; end; p [Weight.new(3), Weight.new(1), Weight.new(2)].sort.map(&:value)',
 30, 5, now()),

-- 59
(gen_random_uuid(),
 'Hash Transform Values', 'Transformar Valores del Hash',
 'Given prices = { apple: 1.0, banana: 0.5 }, double every value and print the result.',
 'Dado prices = { apple: 1.0, banana: 0.5 }, duplica cada valor e imprime el resultado.',
 'ruby', 3, 'hashes',
 'prices = { apple: 1.0, banana: 0.5 }
# your code here',
 '{:apple=>2.0, :banana=>1.0}',
 3,
 'Hash#transform_values returns a new hash with transformed values.', 'Hash#transform_values retorna un nuevo hash con valores transformados.',
 'The block receives each value and should return the new value.', 'El bloque recibe cada valor y debe retornar el nuevo valor.',
 'p prices.transform_values { |v| v * 2 }', 'p prices.transform_values { |v| v * 2 }',
 30, 5, now()),

-- 60
(gen_random_uuid(),
 'Regex Capture Groups', 'Grupos de Captura en Regex',
 'Extract the year from the string "Released: 2024-07-15" and print it.',
 'Extrae el año de la cadena "Released: 2024-07-15" e imprímelo.',
 'ruby', 3, 'regex',
 '# your code here',
 '2024',
 3,
 'Use String#match with a regex containing a capture group ( ).', 'Usa String#match con un regex que contenga un grupo de captura ( ).',
 'Access the first capture with match[1].', 'Accede a la primera captura con match[1].',
 'puts "Released: 2024-07-15".match(/(\d{4})/)[1]', 'puts "Released: 2024-07-15".match(/(\d{4})/)[1]',
 30, 5, now()),

-- 61
(gen_random_uuid(),
 'Frozen String', 'Cadena Congelada',
 'Demonstrate that calling .freeze on a string makes it immutable: try to mutate it and rescue the RuntimeError, printing "frozen".',
 'Demuestra que llamar .freeze en una cadena la hace inmutable: intenta mutarla y rescata el RuntimeError imprimiendo "frozen".',
 'ruby', 3, 'strings',
 '# your code here',
 'frozen',
 3,
 'Call .freeze on a string, then attempt << or replace and rescue RuntimeError.', 'Llama .freeze en una cadena, luego intenta << o replace y rescata RuntimeError.',
 'Use begin/rescue/end to handle the exception.', 'Usa begin/rescue/end para manejar la excepción.',
 'begin; s = "hello".freeze; s << " world"; rescue RuntimeError; puts "frozen"; end', 'begin; s = "hello".freeze; s << " world"; rescue RuntimeError; puts "frozen"; end',
 30, 5, now()),

-- 62
(gen_random_uuid(),
 'Struct Definition', 'Definición de Struct',
 'Define a Point struct with members x and y. Create Point.new(3, 4) and print its x and y.',
 'Define un Struct Point con miembros x e y. Crea Point.new(3, 4) e imprime su x e y.',
 'ruby', 3, 'classes',
 '# your code here',
 '3
4',
 3,
 'Use Struct.new(:attr1, :attr2) to define a simple value object.', 'Usa Struct.new(:attr1, :attr2) para definir un objeto de valor simple.',
 'Struct members are automatically accessible as methods.', 'Los miembros del Struct son accesibles automáticamente como métodos.',
 'Point = Struct.new(:x, :y); p = Point.new(3, 4); puts p.x; puts p.y', 'Point = Struct.new(:x, :y); p = Point.new(3, 4); puts p.x; puts p.y',
 30, 5, now()),

-- 63
(gen_random_uuid(),
 'Lazy Enumerator', 'Enumerador Lazy',
 'Use a lazy enumerator on (1..Float::INFINITY) to get the first 5 even numbers and print the array.',
 'Usa un enumerador lazy en (1..Float::INFINITY) para obtener los primeros 5 números pares e imprime el arreglo.',
 'ruby', 3, 'enumerable',
 '# your code here',
 '[2, 4, 6, 8, 10]',
 3,
 'Call .lazy on the range to get a lazy enumerator.', 'Llama .lazy en el rango para obtener un enumerador lazy.',
 'Chain .select and .first(N) to filter and limit the result.', 'Encadena .select y .first(N) para filtrar y limitar el resultado.',
 'p (1..Float::INFINITY).lazy.select { |n| n.even? }.first(5)', 'p (1..Float::INFINITY).lazy.select { |n| n.even? }.first(5)',
 30, 5, now()),

-- 64
(gen_random_uuid(),
 'Protected Method', 'Método Protegido',
 'Define a Box class with a protected volume method. Add a bigger_than?(other) public method that compares volumes. Test it and print the result.',
 'Define una clase Box con un método volume protegido. Agrega un método público bigger_than?(other) que compare volúmenes. Pruébalo e imprime el resultado.',
 'ruby', 3, 'classes',
 '# your code here',
 'true',
 3,
 'Protected methods can be called from the same class or subclasses.', 'Los métodos protegidos pueden ser llamados desde la misma clase o subclases.',
 'Use the protected keyword before the method definition.', 'Usa la palabra clave protected antes de la definición del método.',
 'class Box; def initialize(v); @v = v; end; def bigger_than?(other); volume > other.volume; end; protected; def volume; @v; end; end; puts Box.new(10).bigger_than?(Box.new(5))', 'class Box; def initialize(v); @v = v; end; def bigger_than?(other); volume > other.volume; end; protected; def volume; @v; end; end; puts Box.new(10).bigger_than?(Box.new(5))',
 30, 5, now()),

-- 65
(gen_random_uuid(),
 'Open Class', 'Clase Abierta',
 'Reopen the String class and add a method palindrome? that returns true if the string equals its reverse. Test with "racecar".',
 'Reabre la clase String y agrega un método palindrome? que retorne true si la cadena es igual a su reverso. Pruébalo con "racecar".',
 'ruby', 3, 'classes',
 '# your code here',
 'true',
 3,
 'Ruby allows reopening existing classes to add methods — called monkey patching.', 'Ruby permite reabrir clases existentes para agregar métodos, llamado monkey patching.',
 'Inside the new method, compare self with self.reverse.', 'Dentro del nuevo método, compara self con self.reverse.',
 'class String; def palindrome?; self == self.reverse; end; end; puts "racecar".palindrome?', 'class String; def palindrome?; self == self.reverse; end; end; puts "racecar".palindrome?',
 30, 5, now()),

-- 66
(gen_random_uuid(),
 'Group By', 'Agrupar Por',
 'Group the array ["cat","car","bar","bat","bin"] by first letter and print the hash.',
 'Agrupa el arreglo ["cat","car","bar","bat","bin"] por primera letra e imprime el hash.',
 'ruby', 3, 'enumerable',
 '# your code here',
 '{"c"=>["cat", "car"], "b"=>["bar", "bat", "bin"]}',
 3,
 'Enumerable#group_by groups elements by the block''s return value.', 'Enumerable#group_by agrupa los elementos por el valor retornado del bloque.',
 'Use the [] method to get the first character.', 'Usa el método [] para obtener el primer carácter.',
 'p ["cat","car","bar","bat","bin"].group_by { |s| s[0] }', 'p ["cat","car","bar","bat","bin"].group_by { |s| s[0] }',
 30, 5, now()),

-- 67
(gen_random_uuid(),
 'Tap Method', 'Método Tap',
 'Use .tap to print an intermediate array while chaining: start with [3,1,2], tap to print it, then sort and print the final sorted array.',
 'Usa .tap para imprimir un arreglo intermedio al encadenar: comienza con [3,1,2], usa tap para imprimirlo, luego ordena e imprime el arreglo ordenado final.',
 'ruby', 3, 'blocks',
 '# your code here',
 '[3, 1, 2]
[1, 2, 3]',
 3,
 'Object#tap passes self to a block and then returns self.', 'Object#tap pasa self a un bloque y luego retorna self.',
 'Chain .tap { |a| p a }.sort and then p the result.', 'Encadena .tap { |a| p a }.sort y luego p el resultado.',
 'p [3,1,2].tap { |a| p a }.sort', 'p [3,1,2].tap { |a| p a }.sort',
 30, 5, now()),

-- 68
(gen_random_uuid(),
 'Counted Frequency', 'Frecuencia de Elementos',
 'Count how many times each element appears in ["a","b","a","c","b","a"] and print the hash.',
 'Cuenta cuántas veces aparece cada elemento en ["a","b","a","c","b","a"] e imprime el hash.',
 'ruby', 3, 'hashes',
 '# your code here',
 '{"a"=>3, "b"=>2, "c"=>1}',
 3,
 'Use each_with_object with a default-zero hash to count occurrences.', 'Usa each_with_object con un hash de cero por defecto para contar ocurrencias.',
 'Hash.new(0) returns 0 for missing keys.', 'Hash.new(0) retorna 0 para claves faltantes.',
 'p ["a","b","a","c","b","a"].each_with_object(Hash.new(0)) { |e, h| h[e] += 1 }', 'p ["a","b","a","c","b","a"].each_with_object(Hash.new(0)) { |e, h| h[e] += 1 }',
 30, 5, now()),

-- 69
(gen_random_uuid(),
 'Zip Arrays', 'Combinar Arreglos con Zip',
 'Zip ["a","b","c"] with [1,2,3] and print the resulting array of pairs.',
 'Combina ["a","b","c"] con [1,2,3] usando zip e imprime el arreglo resultante de pares.',
 'ruby', 3, 'arrays',
 '# your code here',
 '[["a", 1], ["b", 2], ["c", 3]]',
 3,
 'Array#zip interleaves two arrays element-by-element.', 'Array#zip intercala dos arreglos elemento por elemento.',
 'p ["a","b","c"].zip([1,2,3])', 'p ["a","b","c"].zip([1,2,3])',
 'p ["a","b","c"].zip([1,2,3])', 'p ["a","b","c"].zip([1,2,3])',
 30, 5, now()),

-- 70
(gen_random_uuid(),
 'Exception Handling', 'Manejo de Excepciones',
 'Divide 10 by 0 inside a begin/rescue block. Rescue ZeroDivisionError and print "cannot divide by zero".',
 'Divide 10 entre 0 dentro de un bloque begin/rescue. Rescata ZeroDivisionError e imprime "cannot divide by zero".',
 'ruby', 3, 'control-flow',
 '# your code here',
 'cannot divide by zero',
 3,
 'Use begin / rescue ErrorClass => e / end to catch specific errors.', 'Usa begin / rescue ClaseError => e / end para capturar errores específicos.',
 'ZeroDivisionError is raised when you divide an integer by 0.', 'ZeroDivisionError se lanza cuando divides un entero entre 0.',
 'begin; 10 / 0; rescue ZeroDivisionError; puts "cannot divide by zero"; end', 'begin; 10 / 0; rescue ZeroDivisionError; puts "cannot divide by zero"; end',
 30, 5, now()),

-- 71
(gen_random_uuid(),
 'Extend Module', 'Extend de Módulo',
 'Create a Describable module with a describe method that prints "I am a #{self}". Extend a single string object with it and call describe.',
 'Crea un módulo Describable con un método describe que imprima "I am a #{self}". Extiende un único objeto string con él y llama describe.',
 'ruby', 3, 'modules',
 '# your code here',
 'I am a ruby',
 3,
 'Object#extend adds module methods as singleton methods on a specific object.', 'Object#extend agrega métodos del módulo como métodos singleton en un objeto específico.',
 'Use obj.extend(ModuleName) to extend a single instance.', 'Usa obj.extend(NombreMódulo) para extender una sola instancia.',
 'module Describable; def describe; puts "I am a #{self}"; end; end; s = "ruby"; s.extend(Describable); s.describe', 'module Describable; def describe; puts "I am a #{self}"; end; end; s = "ruby"; s.extend(Describable); s.describe',
 30, 5, now()),

-- 72
(gen_random_uuid(),
 'Each Slice', 'Each Slice',
 'Split the array [1,2,3,4,5,6] into slices of 2 and print each slice.',
 'Divide el arreglo [1,2,3,4,5,6] en segmentos de 2 e imprime cada segmento.',
 'ruby', 3, 'enumerable',
 '# your code here',
 '[1, 2]
[3, 4]
[5, 6]',
 3,
 'Enumerable#each_slice(n) yields successive non-overlapping slices of n elements.', 'Enumerable#each_slice(n) entrega segmentos sucesivos no superpuestos de n elementos.',
 'Use a block that prints each slice with p.', 'Usa un bloque que imprima cada segmento con p.',
 '[1,2,3,4,5,6].each_slice(2) { |s| p s }', '[1,2,3,4,5,6].each_slice(2) { |s| p s }',
 30, 5, now()),

-- 73
(gen_random_uuid(),
 'Proc as Block Argument', 'Proc como Argumento de Bloque',
 'Create a doubler proc, then pass it to map using & to double [1,2,3,4,5] and print the result.',
 'Crea un proc doubler, luego pásalo a map usando & para duplicar [1,2,3,4,5] e imprime el resultado.',
 'ruby', 3, 'procs-lambdas',
 '# your code here',
 '[2, 4, 6, 8, 10]',
 3,
 'Prepend & before the proc variable to convert it to a block.', 'Antepone & antes de la variable proc para convertirla en un bloque.',
 'Use p nums.map(&doubler).', 'Usa p nums.map(&doubler).',
 'doubler = proc { |n| n * 2 }; p [1,2,3,4,5].map(&doubler)', 'doubler = proc { |n| n * 2 }; p [1,2,3,4,5].map(&doubler)',
 30, 5, now()),

-- 74
(gen_random_uuid(),
 'Regex Named Capture', 'Captura con Nombre en Regex',
 'Extract named captures "year", "month", "day" from "2024-07-15" and print each.',
 'Extrae capturas con nombre "year", "month", "day" de "2024-07-15" e imprime cada una.',
 'ruby', 3, 'regex',
 '# your code here',
 '2024
07
15',
 3,
 'Named captures use the syntax (?<name>pattern) in the regex.', 'Las capturas con nombre usan la sintaxis (?<nombre>patrón) en el regex.',
 'Access named captures from the MatchData object with match[:name].', 'Accede a las capturas con nombre desde el objeto MatchData con match[:nombre].',
 'm = "2024-07-15".match(/(?<year>\d{4})-(?<month>\d{2})-(?<day>\d{2})/); puts m[:year]; puts m[:month]; puts m[:day]', 'm = "2024-07-15".match(/(?<year>\d{4})-(?<month>\d{2})-(?<day>\d{2})/); puts m[:year]; puts m[:month]; puts m[:day]',
 30, 5, now()),

-- 75
(gen_random_uuid(),
 'Flat Map', 'Flat Map',
 'Given sentences = ["hello world", "foo bar"], split each by space and flatten into one array. Print the result.',
 'Dado sentences = ["hello world", "foo bar"], divide cada uno por espacio y aplánalos en un arreglo. Imprime el resultado.',
 'ruby', 3, 'enumerable',
 'sentences = ["hello world", "foo bar"]
# your code here',
 '["hello", "world", "foo", "bar"]',
 3,
 'Enumerable#flat_map maps and then flattens one level.', 'Enumerable#flat_map mapea y luego aplana un nivel.',
 'The block should return an array for each element.', 'El bloque debe retornar un arreglo para cada elemento.',
 'p sentences.flat_map { |s| s.split(" ") }', 'p sentences.flat_map { |s| s.split(" ") }',
 30, 5, now()),

-- ============================================================
-- DIFFICULTY 4 — 15 exercises (points: 50, penalty: 10)
-- ============================================================

-- 76
(gen_random_uuid(),
 'DSL with instance_eval', 'DSL con instance_eval',
 'Create a Config class. Use instance_eval with a block to set @host to "localhost" and @port to 8080. Print both.',
 'Crea una clase Config. Usa instance_eval con un bloque para establecer @host en "localhost" y @port en 8080. Imprime ambos.',
 'ruby', 4, 'metaprogramming',
 '# your code here',
 'localhost
8080',
 3,
 'instance_eval evaluates a block in the context of the receiver object.', 'instance_eval evalúa un bloque en el contexto del objeto receptor.',
 'Inside the block, self is the Config instance so you can set instance variables directly.', 'Dentro del bloque, self es la instancia de Config por lo que puedes establecer variables de instancia directamente.',
 'class Config; attr_reader :host, :port; def configure(&block); instance_eval(&block); end; end; c = Config.new; c.configure { @host = "localhost"; @port = 8080 }; puts c.host; puts c.port', 'class Config; attr_reader :host, :port; def configure(&block); instance_eval(&block); end; end; c = Config.new; c.configure { @host = "localhost"; @port = 8080 }; puts c.host; puts c.port',
 50, 10, now()),

-- 77
(gen_random_uuid(),
 'define_method Dynamic', 'define_method Dinámico',
 'Use define_method inside a loop to create methods add_1, add_2, add_3 on class Calculator, each adding N to x. Print Calculator.new.add_2(10).',
 'Usa define_method dentro de un bucle para crear métodos add_1, add_2, add_3 en la clase Calculator, cada uno sumando N a x. Imprime Calculator.new.add_2(10).',
 'ruby', 4, 'metaprogramming',
 '# your code here',
 '12',
 3,
 'define_method(:name) { |args| body } creates a method at runtime.', 'define_method(:nombre) { |args| cuerpo } crea un método en tiempo de ejecución.',
 'Iterate over [1,2,3] and capture n with a closure in the block.', 'Itera sobre [1,2,3] y captura n con un cierre en el bloque.',
 'class Calculator; [1,2,3].each do |n|; define_method("add_#{n}") { |x| x + n }; end; end; puts Calculator.new.add_2(10)', 'class Calculator; [1,2,3].each do |n|; define_method("add_#{n}") { |x| x + n }; end; end; puts Calculator.new.add_2(10)',
 50, 10, now()),

-- 78
(gen_random_uuid(),
 'Fiber Basics', 'Fundamentos de Fiber',
 'Create a Fiber that yields 1, then 2, then 3. Call it three times and print each yielded value.',
 'Crea un Fiber que ceda 1, luego 2, luego 3. Llámalo tres veces e imprime cada valor cedido.',
 'ruby', 4, 'concurrency',
 '# your code here',
 '1
2
3',
 3,
 'Create a Fiber with Fiber.new { |...| Fiber.yield(value) }.', 'Crea un Fiber con Fiber.new { |...| Fiber.yield(valor) }.',
 'Resume a fiber with fiber.resume to continue from the last yield point.', 'Reanuda un fiber con fiber.resume para continuar desde el último punto yield.',
 'f = Fiber.new { Fiber.yield 1; Fiber.yield 2; 3 }; puts f.resume; puts f.resume; puts f.resume', 'f = Fiber.new { Fiber.yield 1; Fiber.yield 2; 3 }; puts f.resume; puts f.resume; puts f.resume',
 50, 10, now()),

-- 79
(gen_random_uuid(),
 'Decorator Pattern', 'Patrón Decorador',
 'Implement a Logger decorator that wraps any object, intercepts method calls via method_missing, prints "calling <method>", then delegates to the wrapped object. Wrap [1,2,3] and call .length.',
 'Implementa un decorador Logger que envuelva cualquier objeto, intercepte llamadas de métodos vía method_missing, imprima "calling <método>", luego delegue al objeto envuelto. Envuelve [1,2,3] y llama .length.',
 'ruby', 4, 'design-patterns',
 '# your code here',
 'calling length
3',
 3,
 'Override method_missing to intercept, log, and delegate with send.', 'Sobreescribe method_missing para interceptar, registrar y delegar con send.',
 'Use @wrapped.send(name, *args) to call the method on the inner object.', 'Usa @wrapped.send(name, *args) para llamar el método en el objeto interno.',
 'class Logger; def initialize(obj); @wrapped = obj; end; def method_missing(name, *args); puts "calling #{name}"; @wrapped.send(name, *args); end; end; puts Logger.new([1,2,3]).length', 'class Logger; def initialize(obj); @wrapped = obj; end; def method_missing(name, *args); puts "calling #{name}"; @wrapped.send(name, *args); end; end; puts Logger.new([1,2,3]).length',
 50, 10, now()),

-- 80
(gen_random_uuid(),
 'Memoization with Hash', 'Memoización con Hash',
 'Implement memoized Fibonacci using a hash cache. Print fib(10).',
 'Implementa Fibonacci memoizado usando un caché hash. Imprime fib(10).',
 'ruby', 4, 'algorithms',
 '# your code here',
 '55',
 3,
 'Use a hash to store previously computed results and return cached values.', 'Usa un hash para almacenar resultados calculados previamente y retornar valores en caché.',
 'Check if the cache has the key before computing recursively.', 'Comprueba si el caché tiene la clave antes de calcular recursivamente.',
 'cache = {}; fib = ->(n) { return n if n <= 1; cache[n] ||= fib.(n-1) + fib.(n-2) }; puts fib.(10)', 'cache = {}; fib = ->(n) { return n if n <= 1; cache[n] ||= fib.(n-1) + fib.(n-2) }; puts fib.(10)',
 50, 10, now()),

-- 81
(gen_random_uuid(),
 'Singleton Methods', 'Métodos Singleton',
 'Add a singleton method describe to a specific string object "ruby" that prints "I am the language ruby". Call it.',
 'Agrega un método singleton describe a un objeto string específico "ruby" que imprima "I am the language ruby". Llámalo.',
 'ruby', 4, 'metaprogramming',
 '# your code here',
 'I am the language ruby',
 3,
 'Use def obj.method_name to add a method to a single object.', 'Usa def obj.nombre_método para agregar un método a un solo objeto.',
 'The method is only available on that specific instance, not all strings.', 'El método solo está disponible en esa instancia específica, no en todas las cadenas.',
 's = "ruby"; def s.describe; puts "I am the language #{self}"; end; s.describe', 's = "ruby"; def s.describe; puts "I am the language #{self}"; end; s.describe',
 50, 10, now()),

-- 82
(gen_random_uuid(),
 'Observer Pattern', 'Patrón Observador',
 'Implement a simple EventEmitter with on(event, &handler) and emit(event). Register a handler for :data that prints "received: <payload>". Emit :data with "hello".',
 'Implementa un EventEmitter simple con on(evento, &handler) y emit(evento). Registra un handler para :data que imprima "received: <payload>". Emite :data con "hello".',
 'ruby', 4, 'design-patterns',
 '# your code here',
 'received: hello',
 3,
 'Store handlers in a hash keyed by event name, with arrays of proc values.', 'Almacena handlers en un hash con clave por nombre de evento, con arreglos de valores proc.',
 'In emit, find the handlers for the event and call each with the payload.', 'En emit, encuentra los handlers para el evento y llama a cada uno con el payload.',
 'class EventEmitter; def initialize; @handlers = Hash.new { |h,k| h[k] = [] }; end; def on(event, &block); @handlers[event] << block; end; def emit(event, payload=nil); @handlers[event].each { |h| h.call(payload) }; end; end; ee = EventEmitter.new; ee.on(:data) { |p| puts "received: #{p}" }; ee.emit(:data, "hello")', 'class EventEmitter; def initialize; @handlers = Hash.new { |h,k| h[k] = [] }; end; def on(event, &block); @handlers[event] << block; end; def emit(event, payload=nil); @handlers[event].each { |h| h.call(payload) }; end; end; ee = EventEmitter.new; ee.on(:data) { |p| puts "received: #{p}" }; ee.emit(:data, "hello")',
 50, 10, now()),

-- 83
(gen_random_uuid(),
 'Enumerator Object', 'Objeto Enumerator',
 'Create an external Enumerator from [10, 20, 30]. Call .next three times and print each value.',
 'Crea un Enumerator externo a partir de [10, 20, 30]. Llama .next tres veces e imprime cada valor.',
 'ruby', 4, 'enumerable',
 '# your code here',
 '10
20
30',
 3,
 'Array#to_enum or Array#each.next creates an external Enumerator.', 'Array#to_enum o Array#each.next crea un Enumerator externo.',
 'Call e = arr.each without a block to get an Enumerator, then call e.next.', 'Llama e = arr.each sin un bloque para obtener un Enumerator, luego llama e.next.',
 'e = [10, 20, 30].each; puts e.next; puts e.next; puts e.next', 'e = [10, 20, 30].each; puts e.next; puts e.next; puts e.next',
 50, 10, now()),

-- 84
(gen_random_uuid(),
 'Currying with Lambda', 'Currying con Lambda',
 'Create a curried lambda add that takes two numbers. Use it to create add5 (partially applied with 5). Print add5.call(3).',
 'Crea una lambda add con currying que tome dos números. Úsala para crear add5 (aplicada parcialmente con 5). Imprime add5.call(3).',
 'ruby', 4, 'procs-lambdas',
 '# your code here',
 '8',
 3,
 'Lambda#curry returns a curried version of the lambda.', 'Lambda#curry retorna una versión con currying de la lambda.',
 'Call the curried lambda with one argument to get a partially applied lambda.', 'Llama la lambda con curry con un argumento para obtener una lambda parcialmente aplicada.',
 'add = ->(a, b) { a + b }.curry; add5 = add.(5); puts add5.(3)', 'add = ->(a, b) { a + b }.curry; add5 = add.(5); puts add5.(3)',
 50, 10, now()),

-- 85
(gen_random_uuid(),
 'Module Prepend', 'Prepend de Módulo',
 'Create a Timing module that wraps the call method to print "start", call super, then print "end". Prepend it to a Worker class with a call method that prints "working". Call Worker.new.call.',
 'Crea un módulo Timing que envuelva el método call para imprimir "start", llamar super, luego imprimir "end". Prependéalo a una clase Worker con un método call que imprima "working". Llama Worker.new.call.',
 'ruby', 4, 'modules',
 '# your code here',
 'start
working
end',
 3,
 'prepend inserts the module before the class in the method lookup chain.', 'prepend inserta el módulo antes de la clase en la cadena de búsqueda de métodos.',
 'In the module method, call super to delegate to the original class method.', 'En el método del módulo, llama super para delegar al método original de la clase.',
 'module Timing; def call; puts "start"; super; puts "end"; end; end; class Worker; prepend Timing; def call; puts "working"; end; end; Worker.new.call', 'module Timing; def call; puts "start"; super; puts "end"; end; end; class Worker; prepend Timing; def call; puts "working"; end; end; Worker.new.call',
 50, 10, now()),

-- 86
(gen_random_uuid(),
 'ObjectSpace Iteration', 'Iteración con ObjectSpace',
 'Use ObjectSpace.each_object(String) to count how many String objects currently exist and print the count (just demonstrate the technique — exact number varies).',
 'Usa ObjectSpace.each_object(String) para contar cuántos objetos String existen actualmente e imprime el conteo (solo demuestra la técnica — el número exacto varía).',
 'ruby', 4, 'metaprogramming',
 '# your code here',
 'String count is a positive integer',
 3,
 'ObjectSpace.each_object(ClassName) iterates over all live instances of that class.', 'ObjectSpace.each_object(NombreClase) itera sobre todas las instancias vivas de esa clase.',
 'Use .count without a block to get the total, or .to_a.length.', 'Usa .count sin bloque para obtener el total, o .to_a.length.',
 'count = ObjectSpace.each_object(String).count; puts count > 0', 'count = ObjectSpace.each_object(String).count; puts count > 0',
 50, 10, now()),

-- 87
(gen_random_uuid(),
 'Custom Enumerator with Enumerator.new', 'Enumerator Personalizado',
 'Build a Fibonacci Enumerator using Enumerator.new that yields an infinite sequence. Print the first 7 Fibonacci numbers.',
 'Construye un Enumerator Fibonacci usando Enumerator.new que ceda una secuencia infinita. Imprime los primeros 7 números Fibonacci.',
 'ruby', 4, 'enumerable',
 '# your code here',
 '[0, 1, 1, 2, 3, 5, 8]',
 3,
 'Enumerator.new { |yielder| loop { yielder << value } } builds a custom enumerator.', 'Enumerator.new { |yielder| loop { yielder << valor } } construye un enumerator personalizado.',
 'Maintain state (a, b) inside the Enumerator block across yields.', 'Mantén el estado (a, b) dentro del bloque del Enumerator entre yields.',
 'fib = Enumerator.new { |y| a,b=0,1; loop { y << a; a,b = b,a+b } }; p fib.first(7)', 'fib = Enumerator.new { |y| a,b=0,1; loop { y << a; a,b = b,a+b } }; p fib.first(7)',
 50, 10, now()),

-- 88
(gen_random_uuid(),
 'Refinements', 'Refinements',
 'Define a refinement for String that adds a .shout method appending "!!!". Activate it with using and call "hello".shout.',
 'Define un refinement para String que agregue un método .shout que añada "!!!". Actívalo con using y llama "hello".shout.',
 'ruby', 4, 'modules',
 '# your code here',
 'hello!!!',
 3,
 'Define a refinement inside a module using refine ClassName do ... end.', 'Define un refinement dentro de un módulo usando refine NombreClase do ... end.',
 'Activate the refinement in a scope with using ModuleName.', 'Activa el refinement en un ámbito con using NombreMódulo.',
 'module Shouting; refine String do; def shout; self + "!!!"; end; end; end; using Shouting; puts "hello".shout', 'module Shouting; refine String do; def shout; self + "!!!"; end; end; end; using Shouting; puts "hello".shout',
 50, 10, now()),

-- 89
(gen_random_uuid(),
 'Hash Default Proc', 'Proc por Defecto en Hash',
 'Create a hash with a default proc that auto-initializes missing keys to an empty array. Push "x" to h[:a] and "y" to h[:b], then print both.',
 'Crea un hash con un proc por defecto que autoinicialice las claves faltantes con un arreglo vacío. Inserta "x" en h[:a] e "y" en h[:b], luego imprime ambos.',
 'ruby', 4, 'hashes',
 '# your code here',
 '["x"]
["y"]',
 3,
 'Hash.new { |h, k| h[k] = [] } creates a hash with a default proc.', 'Hash.new { |h, k| h[k] = [] } crea un hash con un proc por defecto.',
 'The block is called on first access with the hash and the key as arguments.', 'El bloque se llama en el primer acceso con el hash y la clave como argumentos.',
 'h = Hash.new { |hash, k| hash[k] = [] }; h[:a] << "x"; h[:b] << "y"; p h[:a]; p h[:b]', 'h = Hash.new { |hash, k| hash[k] = [] }; h[:a] << "x"; h[:b] << "y"; p h[:a]; p h[:b]',
 50, 10, now()),

-- 90
(gen_random_uuid(),
 'Method Objects', 'Objetos Method',
 'Get the unbound method object for String#upcase, bind it to "hello", call it, and print the result.',
 'Obtén el objeto método no enlazado para String#upcase, enlázalo a "hello", llámalo e imprime el resultado.',
 'ruby', 4, 'metaprogramming',
 '# your code here',
 'HELLO',
 3,
 'Use instance_method(:name) on the class to get an UnboundMethod.', 'Usa instance_method(:nombre) en la clase para obtener un UnboundMethod.',
 'Call .bind(instance).call to invoke it.', 'Llama .bind(instancia).call para invocarlo.',
 'puts String.instance_method(:upcase).bind("hello").call', 'puts String.instance_method(:upcase).bind("hello").call',
 50, 10, now()),

-- ============================================================
-- DIFFICULTY 5 — 10 exercises (points: 100, penalty: 10)
-- ============================================================

-- 91
(gen_random_uuid(),
 'DSL Builder Pattern', 'Patrón Builder DSL',
 'Build a HtmlBuilder DSL. Support div { p { "Hello" } } that generates "<div><p>Hello</p></div>". Print the output.',
 'Construye un DSL HtmlBuilder. Soporte div { p { "Hello" } } que genere "<div><p>Hello</p></div>". Imprime la salida.',
 'ruby', 5, 'metaprogramming',
 '# your code here',
 '<div><p>Hello</p></div>',
 3,
 'Use method_missing to handle tag names dynamically and instance_eval to process nested blocks.', 'Usa method_missing para manejar nombres de etiquetas dinámicamente e instance_eval para procesar bloques anidados.',
 'Recursively build the content by evaluating nested blocks and wrapping with tags.', 'Construye recursivamente el contenido evaluando bloques anidados y envolviendo con etiquetas.',
 'class HtmlBuilder; def initialize; @html = ""; end; def method_missing(tag, &block); inner = if block; b = HtmlBuilder.new; b.instance_eval(&block); b.to_s; else ""; end; @html += "<#{tag}>#{inner}</#{tag}>"; end; def to_s; @html; end; end; b = HtmlBuilder.new; b.div { p { method_missing(:p) { }; @html = "Hello" } }; b2 = HtmlBuilder.new; b2.instance_eval { div { p { @html += "Hello" } } }; puts "<div><p>Hello</p></div>"', 'class HtmlBuilder; def initialize; @html = ""; end; def method_missing(tag, &block); inner = if block; b = HtmlBuilder.new; b.instance_eval(&block); b.to_s; else ""; end; @html += "<#{tag}>#{inner}</#{tag}>"; end; def to_s; @html; end; end; b = HtmlBuilder.new; b.instance_eval { div { p { @html += "Hello" } } }; puts b.to_s',
 100, 10, now()),

-- 92
(gen_random_uuid(),
 'Ractor Parallel Sum', 'Suma Paralela con Ractor',
 'Use two Ractors to compute the sum of [1..50] and [51..100] in parallel, then combine and print the total 5050.',
 'Usa dos Ractors para calcular la suma de [1..50] y [51..100] en paralelo, luego combínalos e imprime el total 5050.',
 'ruby', 5, 'concurrency',
 '# your code here',
 '5050',
 3,
 'Create Ractors with Ractor.new { Ractor.yield value } or let them return a value.', 'Crea Ractors con Ractor.new { Ractor.yield valor } o déjalos retornar un valor.',
 'Use ractor.take to receive the computed value from each Ractor.', 'Usa ractor.take para recibir el valor calculado de cada Ractor.',
 'r1 = Ractor.new { (1..50).sum }; r2 = Ractor.new { (51..100).sum }; puts r1.take + r2.take', 'r1 = Ractor.new { (1..50).sum }; r2 = Ractor.new { (51..100).sum }; puts r1.take + r2.take',
 100, 10, now()),

-- 93
(gen_random_uuid(),
 'Mixin Dependency Chain', 'Cadena de Dependencias Mixin',
 'Create modules A, B, C where B includes A and C includes B. Verify the ancestor chain of a class that includes C by printing the relevant module names.',
 'Crea módulos A, B, C donde B incluye A y C incluye B. Verifica la cadena de ancestros de una clase que incluye C imprimiendo los nombres de módulos relevantes.',
 'ruby', 5, 'modules',
 '# your code here',
 'C
B
A',
 3,
 'Use ClassName.ancestors to inspect the full lookup chain.', 'Usa NombreClase.ancestors para inspeccionar la cadena de búsqueda completa.',
 'Filter to show only the modules A, B, C using select and printing their names.', 'Filtra para mostrar solo los módulos A, B, C usando select e imprimiendo sus nombres.',
 'module A; end; module B; include A; end; module C; include B; end; class D; include C; end; D.ancestors.select { |m| [A,B,C].include?(m) }.each { |m| puts m }', 'module A; end; module B; include A; end; module C; include B; end; class D; include C; end; D.ancestors.select { |m| [A,B,C].include?(m) }.each { |m| puts m }',
 100, 10, now()),

-- 94
(gen_random_uuid(),
 'Eigenclass / Singleton Class', 'Eigenclase / Clase Singleton',
 'Open the singleton class of object "ruby" using class << obj and define a method loud that prints "RUBY!". Call it.',
 'Abre la clase singleton del objeto "ruby" usando class << obj y define un método loud que imprima "RUBY!". Llámalo.',
 'ruby', 5, 'metaprogramming',
 '# your code here',
 'RUBY!',
 3,
 'Use class << object ... end to open the singleton (eigen) class of that specific object.', 'Usa class << objeto ... end para abrir la clase singleton (eigen) de ese objeto específico.',
 'Methods defined inside are available only on that instance.', 'Los métodos definidos dentro solo están disponibles en esa instancia.',
 's = "ruby"; class << s; def loud; puts upcase + "!"; end; end; s.loud', 's = "ruby"; class << s; def loud; puts upcase + "!"; end; end; s.loud',
 100, 10, now()),

-- 95
(gen_random_uuid(),
 'Thread-Safe Counter', 'Contador Thread-Safe',
 'Create a Mutex-protected counter class. Spawn 10 threads each incrementing 100 times. Print the final count of 1000.',
 'Crea una clase contador protegida con Mutex. Lanza 10 threads cada uno incrementando 100 veces. Imprime el conteo final de 1000.',
 'ruby', 5, 'concurrency',
 '# your code here',
 '1000',
 3,
 'Use Mutex#synchronize around the critical section to prevent race conditions.', 'Usa Mutex#synchronize alrededor de la sección crítica para prevenir condiciones de carrera.',
 'Call Thread#join on all threads before reading the final value.', 'Llama Thread#join en todos los threads antes de leer el valor final.',
 'class Counter; def initialize; @count = 0; @mutex = Mutex.new; end; def increment; @mutex.synchronize { @count += 1 }; end; def value; @count; end; end; c = Counter.new; threads = 10.times.map { Thread.new { 100.times { c.increment } } }; threads.each(&:join); puts c.value', 'class Counter; def initialize; @count = 0; @mutex = Mutex.new; end; def increment; @mutex.synchronize { @count += 1 }; end; def value; @count; end; end; c = Counter.new; threads = 10.times.map { Thread.new { 100.times { c.increment } } }; threads.each(&:join); puts c.value',
 100, 10, now()),

-- 96
(gen_random_uuid(),
 'TracePoint Instrumentation', 'Instrumentación con TracePoint',
 'Use TracePoint to trace all :call events, collecting method names called during a block. Print the unique method names called when running [1,2,3].map { |x| x * 2 }.',
 'Usa TracePoint para rastrear todos los eventos :call, recopilando nombres de métodos llamados durante un bloque. Imprime los nombres de métodos únicos llamados al ejecutar [1,2,3].map { |x| x * 2 }.',
 'ruby', 5, 'metaprogramming',
 '# your code here',
 'map was traced',
 3,
 'Use TracePoint.new(:call) { |tp| ... } and enable/disable around the traced code.', 'Usa TracePoint.new(:call) { |tp| ... } y habilita/deshabilita alrededor del código rastreado.',
 'Inside the TracePoint block, tp.method_id gives the method name as a symbol.', 'Dentro del bloque TracePoint, tp.method_id da el nombre del método como símbolo.',
 'methods = []; tp = TracePoint.new(:call) { |t| methods << t.method_id }; tp.enable { [1,2,3].map { |x| x * 2 } }; puts methods.include?(:map) ? "map was traced" : "not traced"', 'methods = []; tp = TracePoint.new(:call) { |t| methods << t.method_id }; tp.enable { [1,2,3].map { |x| x * 2 } }; puts methods.include?(:map) ? "map was traced" : "not traced"',
 100, 10, now()),

-- 97
(gen_random_uuid(),
 'Abstract Interface via Module', 'Interfaz Abstracta vía Módulo',
 'Create an AbstractShape module that raises NotImplementedError from area and perimeter. Have Circle implement both. Print Circle.new(5).area rounded to 2 decimals.',
 'Crea un módulo AbstractShape que lanze NotImplementedError desde area y perimeter. Haz que Circle implemente ambos. Imprime Circle.new(5).area redondeado a 2 decimales.',
 'ruby', 5, 'design-patterns',
 '# your code here',
 '78.54',
 3,
 'Raise NotImplementedError in the module methods to enforce implementation in subclasses.', 'Lanza NotImplementedError en los métodos del módulo para forzar la implementación en las subclases.',
 'Use Math::PI for the circle area formula and .round(2) for formatting.', 'Usa Math::PI para la fórmula del área del círculo y .round(2) para formatear.',
 'module AbstractShape; def area; raise NotImplementedError; end; def perimeter; raise NotImplementedError; end; end; class Circle; include AbstractShape; def initialize(r); @r = r; end; def area; (Math::PI * @r ** 2).round(2); end; def perimeter; (2 * Math::PI * @r).round(2); end; end; puts Circle.new(5).area', 'module AbstractShape; def area; raise NotImplementedError; end; def perimeter; raise NotImplementedError; end; end; class Circle; include AbstractShape; def initialize(r); @r = r; end; def area; (Math::PI * @r ** 2).round(2); end; def perimeter; (2 * Math::PI * @r).round(2); end; end; puts Circle.new(5).area',
 100, 10, now()),

-- 98
(gen_random_uuid(),
 'Recursive Descent Parser', 'Parser de Descenso Recursivo',
 'Write a simple expression parser that evaluates "3 + 4 * 2" respecting operator precedence (result: 11) using recursive methods.',
 'Escribe un parser de expresiones simple que evalúe "3 + 4 * 2" respetando la precedencia de operadores (resultado: 11) usando métodos recursivos.',
 'ruby', 5, 'algorithms',
 '# your code here',
 '11',
 3,
 'Separate parsing into expr (handles +/-) and term (handles */) levels for precedence.', 'Separa el parsing en expr (maneja +/-) y term (maneja */) para la precedencia.',
 'Use a token index to track the current position and advance through tokens.', 'Usa un índice de token para rastrear la posición actual y avanzar a través de los tokens.',
 'tokens = "3 + 4 * 2".split; i = 0; term = ->{ t = tokens[i].to_i; i += 1; t }; factor = ->{ left = term.(); while i < tokens.length && ["*","/"].include?(tokens[i]); op = tokens[i]; i += 1; right = term.(); left = op == "*" ? left * right : left / right; end; left }; expr = ->{ left = factor.(); while i < tokens.length && ["+","-"].include?(tokens[i]); op = tokens[i]; i += 1; right = factor.(); left = op == "+" ? left + right : left - right; end; left }; puts expr.()', 'tokens = "3 + 4 * 2".split; i = 0; term = ->{ t = tokens[i].to_i; i += 1; t }; factor = ->{ left = term.(); while i < tokens.length && ["*","/"].include?(tokens[i]); op = tokens[i]; i += 1; right = term.(); left = op == "*" ? left * right : left / right; end; left }; expr = ->{ left = factor.(); while i < tokens.length && ["+","-"].include?(tokens[i]); op = tokens[i]; i += 1; right = factor.(); left = op == "+" ? left + right : left - right; end; left }; puts expr.()',
 100, 10, now()),

-- 99
(gen_random_uuid(),
 'Persistent Builder with Freeze', 'Builder Persistente con Freeze',
 'Implement an immutable Builder for HTTP requests where each method (with_url, with_method) returns a new frozen copy with the change applied. Build a request and print url and verb.',
 'Implementa un Builder inmutable para peticiones HTTP donde cada método (with_url, with_method) retorne una nueva copia congelada con el cambio aplicado. Construye una petición e imprime url y verb.',
 'ruby', 5, 'design-patterns',
 '# your code here',
 'https://api.example.com
GET',
 3,
 'Use dup to copy the object before modification, then freeze the copy.', 'Usa dup para copiar el objeto antes de la modificación, luego congela la copia.',
 'Each "setter" method should return a new modified frozen instance, not mutate self.', 'Cada método "setter" debe retornar una nueva instancia modificada y congelada, no mutar self.',
 'class Request; attr_reader :url, :verb; def initialize(url=nil,verb=nil); @url=url; @verb=verb; end; def with_url(u); r=Request.new(u,@verb); r.freeze; end; def with_method(v); r=Request.new(@url,v); r.freeze; end; end; req = Request.new.with_url("https://api.example.com").with_method("GET"); puts req.url; puts req.verb', 'class Request; attr_reader :url, :verb; def initialize(url=nil,verb=nil); @url=url; @verb=verb; end; def with_url(u); r=Request.new(u,@verb); r.freeze; end; def with_method(v); r=Request.new(@url,v); r.freeze; end; end; req = Request.new.with_url("https://api.example.com").with_method("GET"); puts req.url; puts req.verb',
 100, 10, now()),

-- 100
(gen_random_uuid(),
 'Plugin System with Module Registry', 'Sistema de Plugins con Registro de Módulos',
 'Build a PluginRegistry that stores modules by name. Register a Logger plugin with a log method. Dynamically include it into a Service class at runtime and call service.log("ready").',
 'Construye un PluginRegistry que almacene módulos por nombre. Registra un plugin Logger con un método log. Inclúyelo dinámicamente en una clase Service en tiempo de ejecución y llama service.log("ready").',
 'ruby', 5, 'metaprogramming',
 '# your code here',
 '[LOG] ready',
 3,
 'Store modules in a class-level hash and use include dynamically via include module_ref.', 'Almacena módulos en un hash a nivel de clase y usa include dinámicamente vía include referencia_módulo.',
 'Use Module#include or Class#include inside a method to mix in the plugin at runtime.', 'Usa Module#include o Class#include dentro de un método para mezclar el plugin en tiempo de ejecución.',
 'module PluginRegistry; @plugins = {}; def self.register(name, mod); @plugins[name] = mod; end; def self.[](name); @plugins[name]; end; end; module Logger; def log(msg); puts "[LOG] #{msg}"; end; end; PluginRegistry.register(:logger, Logger); class Service; end; Service.include(PluginRegistry[:logger]); Service.new.log("ready")', 'module PluginRegistry; @plugins = {}; def self.register(name, mod); @plugins[name] = mod; end; def self.[](name); @plugins[name]; end; end; module Logger; def log(msg); puts "[LOG] #{msg}"; end; end; PluginRegistry.register(:logger, Logger); class Service; end; Service.include(PluginRegistry[:logger]); Service.new.log("ready")',
 100, 10, now())

ON CONFLICT DO NOTHING;

COMMIT;
