-- 057_exercises_php.sql
-- 100 PHP exercises, bilingual EN+ES
-- Distribution: diff1=25, diff2=25, diff3=25, diff4=15, diff5=10
-- Points: 10/20/30/50/100 | Penalty: 3/3/5/10/10
-- Focus: echo/print, arrays, foreach, functions, classes, interfaces, traits,
--        namespaces, PDO, string functions, type hints, match expressions,
--        arrow functions, Composer, Laravel concepts

BEGIN;

INSERT INTO exercises (
  id, title_en, title_es,
  description_en, description_es,
  language, difficulty, category,
  starter_code, expected_output,
  hint_count,
  hint_1_en, hint_1_es,
  hint_2_en, hint_2_es,
  hint_3_en, hint_3_es,
  points, hints_used_penalty,
  created_at
) VALUES

-- ============================================================
-- DIFFICULTY 1 — 25 exercises (points=10, penalty=3)
-- ============================================================

-- 1. basics
(gen_random_uuid(),
 'Hello PHP', 'Hola PHP',
 'Use echo to print "Hello, PHP!" to the screen.',
 'Usa echo para imprimir "Hello, PHP!" en pantalla.',
 'php', 1, 'basics',
 '<?php\n// your code here\n?>',
 'Hello, PHP!',
 3,
 'The echo construct outputs one or more strings.', 'La construcción echo imprime una o más cadenas.',
 'Wrap the string in double or single quotes.', 'Envuelve la cadena entre comillas dobles o simples.',
 'echo "Hello, PHP!";', 'echo "Hello, PHP!";',
 10, 3, now()),

-- 2. basics
(gen_random_uuid(),
 'Print Statement', 'Sentencia Print',
 'Use print to output "PHP is fun!" to the screen.',
 'Usa print para mostrar "PHP is fun!" en pantalla.',
 'php', 1, 'basics',
 '<?php\n// your code here\n?>',
 'PHP is fun!',
 3,
 'print is similar to echo but can only take one argument.', 'print es similar a echo pero solo acepta un argumento.',
 'print returns 1, echo does not return a value.', 'print devuelve 1, echo no devuelve un valor.',
 'print "PHP is fun!";', 'print "PHP is fun!";',
 10, 3, now()),

-- 3. basics
(gen_random_uuid(),
 'String Variable', 'Variable de Cadena',
 'Declare a variable $name with value "Alice" and echo it.',
 'Declara una variable $name con el valor "Alice" y muéstrala con echo.',
 'php', 1, 'basics',
 '<?php\n$name = ___;\necho $name;\n?>',
 'Alice',
 3,
 'PHP variables start with the $ sign.', 'Las variables PHP empiezan con el signo $.',
 'Assign a string literal in quotes.', 'Asigna un literal de cadena entre comillas.',
 '$name = "Alice";', '$name = "Alice";',
 10, 3, now()),

-- 4. basics
(gen_random_uuid(),
 'Integer Variable', 'Variable Entera',
 'Declare a variable $age with value 30 and echo it.',
 'Declara una variable $age con el valor 30 y muéstrala con echo.',
 'php', 1, 'basics',
 '<?php\n$age = ___;\necho $age;\n?>',
 '30',
 3,
 'No quotes needed for integer values.', 'No se necesitan comillas para valores enteros.',
 'PHP is loosely typed — just assign the number directly.', 'PHP es de tipado débil — asigna el número directamente.',
 '$age = 30;', '$age = 30;',
 10, 3, now()),

-- 5. basics
(gen_random_uuid(),
 'String Concatenation', 'Concatenación de Cadenas',
 'Concatenate $first = "Hello" and $second = "World" with a space and echo the result.',
 'Concatena $first = "Hello" y $second = "World" con un espacio y muestra el resultado.',
 'php', 1, 'basics',
 '<?php\n$first = "Hello";\n$second = "World";\necho $first ___ " " ___ $second;\n?>',
 'Hello World',
 3,
 'PHP uses the dot (.) operator for string concatenation.', 'PHP usa el operador punto (.) para concatenar cadenas.',
 'Place the dot between each piece you want to join.', 'Coloca el punto entre cada parte que quieras unir.',
 'echo $first . " " . $second;', 'echo $first . " " . $second;',
 10, 3, now()),

-- 6. basics
(gen_random_uuid(),
 'Boolean Variable', 'Variable Booleana',
 'Declare $isActive = true and echo it. PHP prints 1 for true.',
 'Declara $isActive = true y muéstrala. PHP imprime 1 para true.',
 'php', 1, 'basics',
 '<?php\n$isActive = ___;\necho $isActive;\n?>',
 '1',
 3,
 'Use the keyword true (no quotes).', 'Usa la palabra clave true (sin comillas).',
 'When echoed, true outputs 1 and false outputs nothing.', 'Al hacer echo, true muestra 1 y false no muestra nada.',
 '$isActive = true;', '$isActive = true;',
 10, 3, now()),

-- 7. arrays
(gen_random_uuid(),
 'Indexed Array', 'Array Indexado',
 'Create an array $colors = ["red", "green", "blue"] and echo the first element.',
 'Crea un array $colors = ["red", "green", "blue"] y muestra el primer elemento.',
 'php', 1, 'arrays',
 '<?php\n$colors = ["red", "green", "blue"];\necho $colors[___];\n?>',
 'red',
 3,
 'Array indices in PHP start at 0.', 'Los índices de array en PHP empiezan en 0.',
 'Access the first element with index 0.', 'Accede al primer elemento con el índice 0.',
 'echo $colors[0];', 'echo $colors[0];',
 10, 3, now()),

-- 8. arrays
(gen_random_uuid(),
 'Array Count', 'Contar Array',
 'Given $nums = [1, 2, 3, 4, 5], echo the number of elements using count().',
 'Dado $nums = [1, 2, 3, 4, 5], muestra el número de elementos usando count().',
 'php', 1, 'arrays',
 '<?php\n$nums = [1, 2, 3, 4, 5];\necho ___(  $nums);\n?>',
 '5',
 3,
 'The count() function returns the number of elements.', 'La función count() devuelve el número de elementos.',
 'Pass the array variable directly to count().', 'Pasa la variable del array directamente a count().',
 'echo count($nums);', 'echo count($nums);',
 10, 3, now()),

-- 9. control-flow
(gen_random_uuid(),
 'If Statement', 'Sentencia If',
 'Echo "positive" if $n = 5 is greater than 0.',
 'Muestra "positive" si $n = 5 es mayor que 0.',
 'php', 1, 'control-flow',
 '<?php\n$n = 5;\nif ($n ___ 0) {\n    echo "positive";\n}\n?>',
 'positive',
 3,
 'Use the > operator to compare two numbers.', 'Usa el operador > para comparar dos números.',
 'The condition goes inside the parentheses of if().', 'La condición va dentro de los paréntesis de if().',
 'if ($n > 0)', 'if ($n > 0)',
 10, 3, now()),

-- 10. control-flow
(gen_random_uuid(),
 'While Loop', 'Bucle While',
 'Use a while loop to echo numbers 1 through 3, each on its own line.',
 'Usa un bucle while para mostrar los números del 1 al 3, cada uno en su propia línea.',
 'php', 1, 'control-flow',
 '<?php\n$i = 1;\nwhile ($i <= 3) {\n    echo $i . "\n";\n    ___;\n}\n?>',
 "1\n2\n3",
 3,
 'Increment $i inside the loop to avoid an infinite loop.', 'Incrementa $i dentro del bucle para evitar un bucle infinito.',
 'Use $i++ to increment by 1 each iteration.', 'Usa $i++ para incrementar en 1 cada iteración.',
 '$i++;', '$i++;',
 10, 3, now()),

-- 11. control-flow
(gen_random_uuid(),
 'For Loop', 'Bucle For',
 'Use a for loop to echo "item" three times, each on a new line.',
 'Usa un bucle for para mostrar "item" tres veces, cada una en una nueva línea.',
 'php', 1, 'control-flow',
 '<?php\nfor ($i = 0; $i < 3; $i++) {\n    echo ___ . "\n";\n}\n?>',
 "item\nitem\nitem",
 3,
 'Echo the string literal "item" inside the loop body.', 'Muestra el literal de cadena "item" dentro del cuerpo del bucle.',
 'The loop runs while $i < 3, so it executes 3 times.', 'El bucle se ejecuta mientras $i < 3, por lo que se ejecuta 3 veces.',
 'echo "item" . "\n";', 'echo "item" . "\n";',
 10, 3, now()),

-- 12. strings
(gen_random_uuid(),
 'String Length', 'Longitud de Cadena',
 'Echo the length of the string "PHP" using strlen().',
 'Muestra la longitud de la cadena "PHP" usando strlen().',
 'php', 1, 'strings',
 '<?php\necho ___("PHP");\n?>',
 '3',
 3,
 'The strlen() function returns the number of bytes in a string.', 'La función strlen() devuelve el número de bytes en una cadena.',
 'Pass the string literal directly to strlen().', 'Pasa el literal de cadena directamente a strlen().',
 'echo strlen("PHP");', 'echo strlen("PHP");',
 10, 3, now()),

-- 13. strings
(gen_random_uuid(),
 'String Uppercase', 'Cadena en Mayúsculas',
 'Convert "hello" to uppercase using strtoupper() and echo it.',
 'Convierte "hello" a mayúsculas usando strtoupper() y muéstralo.',
 'php', 1, 'strings',
 '<?php\necho ___("hello");\n?>',
 'HELLO',
 3,
 'The strtoupper() function converts a string to uppercase.', 'La función strtoupper() convierte una cadena a mayúsculas.',
 'Pass the string "hello" as the argument.', 'Pasa la cadena "hello" como argumento.',
 'echo strtoupper("hello");', 'echo strtoupper("hello");',
 10, 3, now()),

-- 14. strings
(gen_random_uuid(),
 'String Lowercase', 'Cadena en Minúsculas',
 'Convert "WORLD" to lowercase using strtolower() and echo it.',
 'Convierte "WORLD" a minúsculas usando strtolower() y muéstralo.',
 'php', 1, 'strings',
 '<?php\necho ___("WORLD");\n?>',
 'world',
 3,
 'strtolower() is the counterpart to strtoupper().', 'strtolower() es la contraparte de strtoupper().',
 'Pass the string "WORLD" as the argument.', 'Pasa la cadena "WORLD" como argumento.',
 'echo strtolower("WORLD");', 'echo strtolower("WORLD");',
 10, 3, now()),

-- 15. strings
(gen_random_uuid(),
 'String Contains', 'Cadena Contiene',
 'Use str_contains() to check if "Hello, PHP!" contains "PHP" and echo "yes" if true.',
 'Usa str_contains() para verificar si "Hello, PHP!" contiene "PHP" y muestra "yes" si es verdadero.',
 'php', 1, 'strings',
 '<?php\nif (str_contains("Hello, PHP!", "PHP")) {\n    echo ___;\n}\n?>',
 'yes',
 3,
 'str_contains() returns true if the needle is found in the haystack.', 'str_contains() devuelve true si encuentra la aguja en el pajar.',
 'Echo the string literal "yes" inside the if block.', 'Muestra el literal "yes" dentro del bloque if.',
 'echo "yes";', 'echo "yes";',
 10, 3, now()),

-- 16. arrays
(gen_random_uuid(),
 'Array Push', 'Agregar al Array',
 'Push the value 4 onto $nums = [1, 2, 3] and echo the last element.',
 'Agrega el valor 4 a $nums = [1, 2, 3] y muestra el último elemento.',
 'php', 1, 'arrays',
 '<?php\n$nums = [1, 2, 3];\narray_push($nums, ___);\necho $nums[count($nums) - 1];\n?>',
 '4',
 3,
 'array_push() appends one or more elements to the end of an array.', 'array_push() agrega uno o más elementos al final de un array.',
 'Pass 4 as the second argument to array_push().', 'Pasa 4 como segundo argumento a array_push().',
 'array_push($nums, 4);', 'array_push($nums, 4);',
 10, 3, now()),

-- 17. arrays
(gen_random_uuid(),
 'Associative Array', 'Array Asociativo',
 'Create $person = ["name" => "Bob", "age" => 25] and echo the name.',
 'Crea $person = ["name" => "Bob", "age" => 25] y muestra el nombre.',
 'php', 1, 'arrays',
 '<?php\n$person = ["name" => "Bob", "age" => 25];\necho $person[___];\n?>',
 'Bob',
 3,
 'Access associative array values using their string key.', 'Accede a los valores del array asociativo usando su clave de cadena.',
 'Use "name" as the key inside square brackets.', 'Usa "name" como clave dentro de los corchetes.',
 'echo $person["name"];', 'echo $person["name"];',
 10, 3, now()),

-- 18. functions
(gen_random_uuid(),
 'Define a Function', 'Definir una Función',
 'Define a function greet() that echoes "Hi there!" and call it.',
 'Define una función greet() que muestre "Hi there!" y llámala.',
 'php', 1, 'functions',
 '<?php\nfunction greet() {\n    echo ___;\n}\ngreet();\n?>',
 'Hi there!',
 3,
 'Use echo inside the function body to output the string.', 'Usa echo dentro del cuerpo de la función para mostrar la cadena.',
 'Enclose the string in double or single quotes.', 'Encierra la cadena entre comillas dobles o simples.',
 'echo "Hi there!";', 'echo "Hi there!";',
 10, 3, now()),

-- 19. functions
(gen_random_uuid(),
 'Function with Parameter', 'Función con Parámetro',
 'Define a function sayHello($name) that echoes "Hello, " followed by the name, then call it with "Eve".',
 'Define una función sayHello($name) que muestre "Hello, " seguido del nombre, luego llámala con "Eve".',
 'php', 1, 'functions',
 '<?php\nfunction sayHello(___) {\n    echo "Hello, " . $name;\n}\nsayHello("Eve");\n?>',
 'Hello, Eve',
 3,
 'Declare $name as the parameter in the function signature.', 'Declara $name como parámetro en la firma de la función.',
 'PHP parameters also use the $ prefix.', 'Los parámetros en PHP también usan el prefijo $.',
 'function sayHello($name)', 'function sayHello($name)',
 10, 3, now()),

-- 20. functions
(gen_random_uuid(),
 'Function Return Value', 'Valor de Retorno de Función',
 'Define a function add($a, $b) that returns $a + $b, then echo add(3, 4).',
 'Define una función add($a, $b) que retorne $a + $b, luego muestra add(3, 4).',
 'php', 1, 'functions',
 '<?php\nfunction add($a, $b) {\n    ___ $a + $b;\n}\necho add(3, 4);\n?>',
 '7',
 3,
 'Use the return keyword to send a value back from the function.', 'Usa la palabra clave return para devolver un valor desde la función.',
 'The returned value can then be used directly inside echo.', 'El valor retornado puede usarse directamente dentro de echo.',
 'return $a + $b;', 'return $a + $b;',
 10, 3, now()),

-- 21. control-flow
(gen_random_uuid(),
 'Else Branch', 'Rama Else',
 'Echo "even" if $n = 4 is divisible by 2, else echo "odd".',
 'Muestra "even" si $n = 4 es divisible por 2, si no muestra "odd".',
 'php', 1, 'control-flow',
 '<?php\n$n = 4;\nif ($n % 2 === 0) {\n    echo "even";\n} ___ {\n    echo "odd";\n}\n?>',
 'even',
 3,
 'Use the else keyword for the alternative branch.', 'Usa la palabra clave else para la rama alternativa.',
 'The modulo operator % gives the remainder of division.', 'El operador módulo % da el resto de la división.',
 'else', 'else',
 10, 3, now()),

-- 22. strings
(gen_random_uuid(),
 'String Trim', 'Recortar Cadena',
 'Use trim() to remove whitespace from "  hello  " and echo the result.',
 'Usa trim() para eliminar espacios en blanco de "  hello  " y muestra el resultado.',
 'php', 1, 'strings',
 '<?php\necho ___("  hello  ");\n?>',
 'hello',
 3,
 'trim() strips whitespace from the beginning and end of a string.', 'trim() elimina los espacios en blanco del principio y el final de una cadena.',
 'Pass the padded string directly to trim().', 'Pasa la cadena con espacios directamente a trim().',
 'echo trim("  hello  ");', 'echo trim("  hello  ");',
 10, 3, now()),

-- 23. basics
(gen_random_uuid(),
 'PHP Constants', 'Constantes PHP',
 'Define a constant PI with value 3.14 using define() and echo it.',
 'Define una constante PI con valor 3.14 usando define() y muéstrala.',
 'php', 1, 'basics',
 '<?php\ndefine("PI", ___);\necho PI;\n?>',
 '3.14',
 3,
 'The second argument to define() is the constant value.', 'El segundo argumento de define() es el valor de la constante.',
 'Constants do not use the $ prefix when accessed.', 'Las constantes no usan el prefijo $ cuando se acceden.',
 'define("PI", 3.14);', 'define("PI", 3.14);',
 10, 3, now()),

-- 24. control-flow
(gen_random_uuid(),
 'Switch Statement', 'Sentencia Switch',
 'Use switch on $day = "Mon" to echo "Monday". Default echoes "Other".',
 'Usa switch sobre $day = "Mon" para mostrar "Monday". El default muestra "Other".',
 'php', 1, 'control-flow',
 '<?php\n$day = "Mon";\nswitch ($day) {\n    case "Mon":\n        echo ___;\n        break;\n    default:\n        echo "Other";\n}\n?>',
 'Monday',
 3,
 'Echo the string literal "Monday" in the matching case.', 'Muestra el literal "Monday" en el caso correspondiente.',
 'Do not forget the break statement after each case.', 'No olvides el break después de cada caso.',
 'echo "Monday";', 'echo "Monday";',
 10, 3, now()),

-- 25. arrays
(gen_random_uuid(),
 'Array Merge', 'Fusionar Arrays',
 'Merge $a = [1, 2] and $b = [3, 4] using array_merge() and echo the third element.',
 'Fusiona $a = [1, 2] y $b = [3, 4] usando array_merge() y muestra el tercer elemento.',
 'php', 1, 'arrays',
 '<?php\n$a = [1, 2];\n$b = [3, 4];\n$c = ___(  $a, $b);\necho $c[2];\n?>',
 '3',
 3,
 'array_merge() combines two or more arrays into one.', 'array_merge() combina dos o más arrays en uno.',
 'The merged result is re-indexed starting at 0.', 'El resultado fusionado se re-indexa empezando en 0.',
 '$c = array_merge($a, $b);', '$c = array_merge($a, $b);',
 10, 3, now()),

-- ============================================================
-- DIFFICULTY 2 — 25 exercises (points=20, penalty=3)
-- ============================================================

-- 26. foreach
(gen_random_uuid(),
 'Foreach Loop', 'Bucle Foreach',
 'Use foreach to echo each value in $fruits = ["apple", "banana", "cherry"] on a new line.',
 'Usa foreach para mostrar cada valor de $fruits = ["apple", "banana", "cherry"] en una nueva línea.',
 'php', 2, 'arrays',
 '<?php\n$fruits = ["apple", "banana", "cherry"];\nforeach ($fruits ___ $fruit) {\n    echo $fruit . "\n";\n}\n?>',
 "apple\nbanana\ncherry",
 3,
 'foreach uses the "as" keyword to assign each element to a variable.', 'foreach usa la palabra clave "as" para asignar cada elemento a una variable.',
 'The syntax is: foreach ($array as $value).', 'La sintaxis es: foreach ($array as $valor).',
 'foreach ($fruits as $fruit)', 'foreach ($fruits as $fruit)',
 20, 3, now()),

-- 27. foreach
(gen_random_uuid(),
 'Foreach Key-Value', 'Foreach Clave-Valor',
 'Use foreach on $scores = ["Alice" => 90, "Bob" => 85] to echo "Alice: 90" and "Bob: 85".',
 'Usa foreach sobre $scores = ["Alice" => 90, "Bob" => 85] para mostrar "Alice: 90" y "Bob: 85".',
 'php', 2, 'arrays',
 '<?php\n$scores = ["Alice" => 90, "Bob" => 85];\nforeach ($scores as $name => $score) {\n    echo $name . ": " . ___ . "\n";\n}\n?>',
 "Alice: 90\nBob: 85",
 3,
 'Use $score to access the value in each iteration.', 'Usa $score para acceder al valor en cada iteración.',
 'The key ($name) and value ($score) are separated by => in the foreach.', 'La clave ($name) y el valor ($score) se separan por => en el foreach.',
 '$score', '$score',
 20, 3, now()),

-- 28. functions
(gen_random_uuid(),
 'Default Parameter', 'Parámetro por Defecto',
 'Define greet($name = "World") that echoes "Hello, World!" when called with no argument.',
 'Define greet($name = "World") que muestre "Hello, World!" cuando se llama sin argumento.',
 'php', 2, 'functions',
 '<?php\nfunction greet($name = ___) {\n    echo "Hello, " . $name . "!";\n}\ngreet();\n?>',
 'Hello, World!',
 3,
 'Default parameter values are assigned in the function signature with =.', 'Los valores de parámetro por defecto se asignan en la firma de la función con =.',
 'The default value "World" is used when no argument is passed.', 'El valor por defecto "World" se usa cuando no se pasa ningún argumento.',
 '"World"', '"World"',
 20, 3, now()),

-- 29. strings
(gen_random_uuid(),
 'String Repeat', 'Repetir Cadena',
 'Use str_repeat() to echo "-" repeated 5 times.',
 'Usa str_repeat() para mostrar "-" repetido 5 veces.',
 'php', 2, 'strings',
 '<?php\necho str_repeat(___, 5);\n?>',
 '-----',
 3,
 'str_repeat($str, $times) repeats a string a given number of times.', 'str_repeat($str, $veces) repite una cadena un número determinado de veces.',
 'Pass "-" as the first argument and 5 as the second.', 'Pasa "-" como primer argumento y 5 como segundo.',
 '"-", 5', '"-", 5',
 20, 3, now()),

-- 30. strings
(gen_random_uuid(),
 'String Replace', 'Reemplazar en Cadena',
 'Use str_replace() to replace "World" with "PHP" in "Hello, World!" and echo the result.',
 'Usa str_replace() para reemplazar "World" con "PHP" en "Hello, World!" y muestra el resultado.',
 'php', 2, 'strings',
 '<?php\necho str_replace("World", ___, "Hello, World!");\n?>',
 'Hello, PHP!',
 3,
 'str_replace($search, $replace, $subject) replaces occurrences of search with replace.', 'str_replace($buscar, $reemplazar, $sujeto) reemplaza ocurrencias de buscar con reemplazar.',
 'Pass "PHP" as the replacement (second argument).', 'Pasa "PHP" como reemplazo (segundo argumento).',
 '"PHP"', '"PHP"',
 20, 3, now()),

-- 31. arrays
(gen_random_uuid(),
 'Array Sort', 'Ordenar Array',
 'Sort $nums = [3, 1, 4, 1, 5] with sort() and echo the first element.',
 'Ordena $nums = [3, 1, 4, 1, 5] con sort() y muestra el primer elemento.',
 'php', 2, 'arrays',
 '<?php\n$nums = [3, 1, 4, 1, 5];\nsort(___);\necho $nums[0];\n?>',
 '1',
 3,
 'sort() sorts an array in place in ascending order.', 'sort() ordena un array en el lugar en orden ascendente.',
 'Pass the array variable $nums to sort().', 'Pasa la variable de array $nums a sort().',
 '$nums', '$nums',
 20, 3, now()),

-- 32. arrays
(gen_random_uuid(),
 'Array Map', 'Array Map',
 'Use array_map() to double each value in $nums = [1, 2, 3] and echo the result as JSON.',
 'Usa array_map() para duplicar cada valor en $nums = [1, 2, 3] y muestra el resultado como JSON.',
 'php', 2, 'arrays',
 '<?php\n$nums = [1, 2, 3];\n$doubled = array_map(function($n) { return $n * 2; }, ___);\necho json_encode($doubled);\n?>',
 '[2,4,6]',
 3,
 'array_map() applies a callback to each element and returns the results.', 'array_map() aplica un callback a cada elemento y devuelve los resultados.',
 'Pass $nums as the second argument to array_map().', 'Pasa $nums como segundo argumento a array_map().',
 '$nums', '$nums',
 20, 3, now()),

-- 33. arrays
(gen_random_uuid(),
 'Array Filter', 'Array Filter',
 'Use array_filter() to keep only even numbers from $nums = [1, 2, 3, 4, 5] and echo them as JSON.',
 'Usa array_filter() para conservar solo los números pares de $nums = [1, 2, 3, 4, 5] y muéstralos como JSON.',
 'php', 2, 'arrays',
 '<?php\n$nums = [1, 2, 3, 4, 5];\n$evens = array_filter($nums, function($n) { return ___ === 0; });\necho json_encode(array_values($evens));\n?>',
 '[2,4]',
 3,
 'Use the modulo operator to check if a number is even.', 'Usa el operador módulo para comprobar si un número es par.',
 '$n % 2 equals 0 for even numbers.', '$n % 2 es igual a 0 para los números pares.',
 '$n % 2', '$n % 2',
 20, 3, now()),

-- 34. arrays
(gen_random_uuid(),
 'Array Keys', 'Claves del Array',
 'Given $data = ["a" => 1, "b" => 2], use array_keys() and echo them as JSON.',
 'Dado $data = ["a" => 1, "b" => 2], usa array_keys() y muéstralos como JSON.',
 'php', 2, 'arrays',
 '<?php\n$data = ["a" => 1, "b" => 2];\necho json_encode(___($data));\n?>',
 '["a","b"]',
 3,
 'array_keys() returns all the keys of an array.', 'array_keys() devuelve todas las claves de un array.',
 'Pass $data directly to array_keys().', 'Pasa $data directamente a array_keys().',
 'array_keys', 'array_keys',
 20, 3, now()),

-- 35. functions
(gen_random_uuid(),
 'Variadic Function', 'Función Variádica',
 'Define sum(...$nums) that returns the sum of all arguments and echo sum(1, 2, 3).',
 'Define sum(...$nums) que retorne la suma de todos los argumentos y muestra sum(1, 2, 3).',
 'php', 2, 'functions',
 '<?php\nfunction sum(___$nums) {\n    return array_sum($nums);\n}\necho sum(1, 2, 3);\n?>',
 '6',
 3,
 'Use ... before the parameter name to collect all arguments into an array.', 'Usa ... antes del nombre del parámetro para recopilar todos los argumentos en un array.',
 'array_sum() calculates the sum of all values in an array.', 'array_sum() calcula la suma de todos los valores en un array.',
 '...', '...',
 20, 3, now()),

-- 36. strings
(gen_random_uuid(),
 'Explode String', 'Separar Cadena',
 'Use explode() to split "a,b,c" by "," and echo the second element.',
 'Usa explode() para dividir "a,b,c" por "," y muestra el segundo elemento.',
 'php', 2, 'strings',
 '<?php\n$parts = explode(",", "a,b,c");\necho $parts[___];\n?>',
 'b',
 3,
 'explode() splits a string into an array by a delimiter.', 'explode() divide una cadena en un array usando un delimitador.',
 'The second element is at index 1.', 'El segundo elemento está en el índice 1.',
 '1', '1',
 20, 3, now()),

-- 37. strings
(gen_random_uuid(),
 'Implode Array', 'Unir Array',
 'Use implode() to join $words = ["PHP", "is", "great"] with a space and echo it.',
 'Usa implode() para unir $words = ["PHP", "is", "great"] con un espacio y muéstralo.',
 'php', 2, 'strings',
 '<?php\n$words = ["PHP", "is", "great"];\necho implode(___, $words);\n?>',
 'PHP is great',
 3,
 'implode($glue, $array) joins array elements with a separator string.', 'implode($pegamento, $array) une elementos del array con una cadena separadora.',
 'Pass a single space " " as the first argument.', 'Pasa un espacio simple " " como primer argumento.',
 '" "', '" "',
 20, 3, now()),

-- 38. type-hints
(gen_random_uuid(),
 'Type Hint: int', 'Tipo Indicado: int',
 'Define multiply(int $a, int $b): int that returns $a * $b and echo multiply(4, 5).',
 'Define multiply(int $a, int $b): int que retorne $a * $b y muestra multiply(4, 5).',
 'php', 2, 'type-hints',
 '<?php\nfunction multiply(int $a, int $b): ___ {\n    return $a * $b;\n}\necho multiply(4, 5);\n?>',
 '20',
 3,
 'The return type hint comes after the closing parenthesis with a colon.', 'El tipo de retorno va después del paréntesis de cierre con dos puntos.',
 'Use int as the return type for integer multiplication.', 'Usa int como tipo de retorno para la multiplicación de enteros.',
 'int', 'int',
 20, 3, now()),

-- 39. type-hints
(gen_random_uuid(),
 'Type Hint: string', 'Tipo Indicado: string',
 'Define getFullName(string $first, string $last): string that returns "$first $last" and echo it for "Jane" "Doe".',
 'Define getFullName(string $first, string $last): string que retorne "$first $last" y muéstralo para "Jane" "Doe".',
 'php', 2, 'type-hints',
 '<?php\nfunction getFullName(string $first, string $last): string {\n    return $first . " " . ___;\n}\necho getFullName("Jane", "Doe");\n?>',
 'Jane Doe',
 3,
 'Concatenate $last to the first name and space using the dot operator.', 'Concatena $last al nombre y al espacio usando el operador punto.',
 'Return the combined string from the function.', 'Devuelve la cadena combinada desde la función.',
 '$last', '$last',
 20, 3, now()),

-- 40. control-flow
(gen_random_uuid(),
 'Ternary Operator', 'Operador Ternario',
 'Use the ternary operator to assign "pass" if $score = 75 >= 50, else "fail", and echo it.',
 'Usa el operador ternario para asignar "pass" si $score = 75 >= 50, si no "fail", y muéstralo.',
 'php', 2, 'control-flow',
 '<?php\n$score = 75;\n$result = $score >= 50 ___ "pass" : "fail";\necho $result;\n?>',
 'pass',
 3,
 'The ternary operator uses ? to separate the condition from the true value.', 'El operador ternario usa ? para separar la condición del valor verdadero.',
 'Syntax: condition ? value_if_true : value_if_false.', 'Sintaxis: condición ? valor_si_verdadero : valor_si_falso.',
 '?', '?',
 20, 3, now()),

-- 41. control-flow
(gen_random_uuid(),
 'Null Coalescing', 'Operador Null Coalescing',
 'Use ?? to output $name if set, otherwise "Guest". $name is not defined.',
 'Usa ?? para mostrar $name si está definido, de lo contrario "Guest". $name no está definido.',
 'php', 2, 'control-flow',
 '<?php\necho $name ___ "Guest";\n?>',
 'Guest',
 3,
 'The null coalescing operator ?? returns the left operand if it exists and is not null.', 'El operador ?? devuelve el operando izquierdo si existe y no es null.',
 'Since $name is undefined, ?? returns the right-hand fallback "Guest".', 'Como $name no está definido, ?? devuelve el valor de reserva "Guest".',
 '??', '??',
 20, 3, now()),

-- 42. strings
(gen_random_uuid(),
 'Substr Function', 'Función Substr',
 'Use substr() to extract "PHP" from "Hello PHP" (starting at index 6) and echo it.',
 'Usa substr() para extraer "PHP" de "Hello PHP" (empezando en el índice 6) y muéstralo.',
 'php', 2, 'strings',
 '<?php\necho substr("Hello PHP", ___);\n?>',
 'PHP',
 3,
 'substr($string, $start) extracts from $start to the end of the string.', 'substr($cadena, $inicio) extrae desde $inicio hasta el final de la cadena.',
 'Index 6 is where "P" in "PHP" begins (0-based).', 'El índice 6 es donde comienza la "P" de "PHP" (base 0).',
 '6', '6',
 20, 3, now()),

-- 43. strings
(gen_random_uuid(),
 'Number Format', 'Formato de Número',
 'Use number_format(1234567.891, 2) to format the number and echo it.',
 'Usa number_format(1234567.891, 2) para formatear el número y muéstralo.',
 'php', 2, 'strings',
 '<?php\necho number_format(___, 2);\n?>',
 '1,234,567.89',
 3,
 'number_format() formats a number with grouped thousands and decimal places.', 'number_format() formatea un número con miles agrupados y decimales.',
 'Pass the float 1234567.891 as the first argument.', 'Pasa el flotante 1234567.891 como primer argumento.',
 '1234567.891', '1234567.891',
 20, 3, now()),

-- 44. arrays
(gen_random_uuid(),
 'Array Unique', 'Valores Únicos del Array',
 'Use array_unique() on [1, 2, 2, 3, 3] and echo the count of the result.',
 'Usa array_unique() sobre [1, 2, 2, 3, 3] y muestra el count del resultado.',
 'php', 2, 'arrays',
 '<?php\n$nums = [1, 2, 2, 3, 3];\n$unique = ___(  $nums);\necho count($unique);\n?>',
 '3',
 3,
 'array_unique() removes duplicate values from an array.', 'array_unique() elimina los valores duplicados de un array.',
 'After removing duplicates from [1,2,2,3,3] you are left with 3 elements.', 'Después de eliminar duplicados de [1,2,2,3,3] quedan 3 elementos.',
 'array_unique', 'array_unique',
 20, 3, now()),

-- 45. functions
(gen_random_uuid(),
 'Anonymous Function', 'Función Anónima',
 'Assign an anonymous function to $double that takes $n and returns $n * 2. Echo $double(7).',
 'Asigna una función anónima a $double que tome $n y retorne $n * 2. Muestra $double(7).',
 'php', 2, 'functions',
 '<?php\n$double = function(___) {\n    return $n * 2;\n};\necho $double(7);\n?>',
 '14',
 3,
 'Anonymous functions are declared with the function keyword without a name.', 'Las funciones anónimas se declaran con la palabra clave function sin nombre.',
 'Declare $n as the parameter inside the parentheses.', 'Declara $n como parámetro dentro de los paréntesis.',
 '$n', '$n',
 20, 3, now()),

-- 46. functions
(gen_random_uuid(),
 'Arrow Function', 'Función Flecha',
 'Use an arrow function fn($n) => $n * 3 assigned to $triple and echo $triple(6).',
 'Usa una función flecha fn($n) => $n * 3 asignada a $triple y muestra $triple(6).',
 'php', 2, 'functions',
 '<?php\n$triple = ___($n) => $n * 3;\necho $triple(6);\n?>',
 '18',
 3,
 'PHP arrow functions use the fn keyword instead of function.', 'Las funciones flecha de PHP usan la palabra clave fn en lugar de function.',
 'Arrow functions implicitly return the expression after =>.', 'Las funciones flecha retornan implícitamente la expresión después de =>.',
 'fn', 'fn',
 20, 3, now()),

-- 47. arrays
(gen_random_uuid(),
 'Array Reduce', 'Reducir Array',
 'Use array_reduce() on [1, 2, 3, 4] to compute the sum starting from 0 and echo it.',
 'Usa array_reduce() sobre [1, 2, 3, 4] para calcular la suma empezando desde 0 y muéstrala.',
 'php', 2, 'arrays',
 '<?php\n$nums = [1, 2, 3, 4];\n$sum = array_reduce($nums, function($carry, $item) {\n    return $carry + ___;\n}, 0);\necho $sum;\n?>',
 '10',
 3,
 'array_reduce() applies a callback cumulatively, with $carry being the running total.', 'array_reduce() aplica un callback acumulativamente, siendo $carry el total acumulado.',
 'Add $item to $carry in each iteration.', 'Suma $item a $carry en cada iteración.',
 '$item', '$item',
 20, 3, now()),

-- 48. strings
(gen_random_uuid(),
 'Sprintf Formatting', 'Formato con Sprintf',
 'Use sprintf() to format "Price: $%.2f" with value 9.5 and echo it.',
 'Usa sprintf() para formatear "Price: $%.2f" con el valor 9.5 y muéstralo.',
 'php', 2, 'strings',
 '<?php\necho sprintf("Price: $%.2f", ___);\n?>',
 'Price: $9.50',
 3,
 'sprintf() returns a formatted string using format specifiers.', 'sprintf() devuelve una cadena formateada usando especificadores de formato.',
 '%.2f formats a float with exactly 2 decimal places.', '%.2f formatea un flotante con exactamente 2 decimales.',
 '9.5', '9.5',
 20, 3, now()),

-- 49. control-flow
(gen_random_uuid(),
 'Match Expression', 'Expresión Match',
 'Use a match expression on $status = 1 to echo "active" for 1, "inactive" for 0, "unknown" by default.',
 'Usa una expresión match sobre $status = 1 para mostrar "active" para 1, "inactive" para 0, "unknown" por defecto.',
 'php', 2, 'control-flow',
 '<?php\n$status = 1;\necho match(___) {\n    1 => "active",\n    0 => "inactive",\n    default => "unknown",\n};\n?>',
 'active',
 3,
 'match() compares the argument against each arm using strict equality.', 'match() compara el argumento con cada rama usando igualdad estricta.',
 'Pass $status as the argument to match().', 'Pasa $status como argumento a match().',
 '$status', '$status',
 20, 3, now()),

-- 50. type-hints
(gen_random_uuid(),
 'Nullable Type', 'Tipo Nullable',
 'Define findUser(?int $id): string that returns "found" if $id is not null, else "none". Echo findUser(null).',
 'Define findUser(?int $id): string que retorne "found" si $id no es null, si no "none". Muestra findUser(null).',
 'php', 2, 'type-hints',
 '<?php\nfunction findUser(___int $id): string {\n    return $id !== null ? "found" : "none";\n}\necho findUser(null);\n?>',
 'none',
 3,
 'Prefix the type with ? to allow null values.', 'Prefija el tipo con ? para permitir valores null.',
 'A nullable type accepts both the specified type and null.', 'Un tipo nullable acepta tanto el tipo especificado como null.',
 '?', '?',
 20, 3, now()),

-- ============================================================
-- DIFFICULTY 3 — 25 exercises (points=30, penalty=5)
-- ============================================================

-- 51. classes
(gen_random_uuid(),
 'Basic Class', 'Clase Básica',
 'Define a class Animal with a public property $name. Instantiate it, set name to "Cat", and echo it.',
 'Define una clase Animal con una propiedad pública $name. Instanciala, establece el nombre en "Cat" y muéstralo.',
 'php', 3, 'classes',
 '<?php\nclass Animal {\n    public string $name;\n}\n$a = new ___();\n$a->name = "Cat";\necho $a->name;\n?>',
 'Cat',
 3,
 'Use the new keyword followed by the class name to create an instance.', 'Usa la palabra clave new seguida del nombre de la clase para crear una instancia.',
 'Access object properties with the -> operator.', 'Accede a las propiedades del objeto con el operador ->.',
 'Animal', 'Animal',
 30, 5, now()),

-- 52. classes
(gen_random_uuid(),
 'Constructor', 'Constructor',
 'Add a __construct($name) to the Animal class that sets $this->name, then echo (new Animal("Dog"))->name.',
 'Agrega un __construct($name) a la clase Animal que establezca $this->name, luego muestra (new Animal("Dog"))->name.',
 'php', 3, 'classes',
 '<?php\nclass Animal {\n    public string $name;\n    public function ___($name) {\n        $this->name = $name;\n    }\n}\necho (new Animal("Dog"))->name;\n?>',
 'Dog',
 3,
 'The constructor is a special method named __construct.', 'El constructor es un método especial llamado __construct.',
 'Use $this->name to assign the property inside the constructor.', 'Usa $this->name para asignar la propiedad dentro del constructor.',
 '__construct', '__construct',
 30, 5, now()),

-- 53. classes
(gen_random_uuid(),
 'Class Method', 'Método de Clase',
 'Add a speak() method to Animal that returns "I am " . $this->name. Echo it for Animal("Bird").',
 'Agrega un método speak() a Animal que retorne "I am " . $this->name. Muéstralo para Animal("Bird").',
 'php', 3, 'classes',
 '<?php\nclass Animal {\n    public function __construct(public string $name) {}\n    public function speak(): string {\n        return "I am " . ___->name;\n    }\n}\necho (new Animal("Bird"))->speak();\n?>',
 'I am Bird',
 3,
 'Use $this to refer to the current object instance inside a method.', 'Usa $this para referirte a la instancia del objeto actual dentro de un método.',
 'Concatenate $this->name with the prefix string.', 'Concatena $this->name con la cadena de prefijo.',
 '$this', '$this',
 30, 5, now()),

-- 54. classes
(gen_random_uuid(),
 'Inheritance', 'Herencia',
 'Define Dog extends Animal and override speak() to return "Woof! I am " . $this->name. Echo it.',
 'Define Dog que extienda Animal y sobreescribe speak() para retornar "Woof! I am " . $this->name. Muéstralo.',
 'php', 3, 'classes',
 '<?php\nclass Animal {\n    public function __construct(public string $name) {}\n    public function speak(): string { return "..."; }\n}\nclass Dog ___ Animal {\n    public function speak(): string {\n        return "Woof! I am " . $this->name;\n    }\n}\necho (new Dog("Rex"))->speak();\n?>',
 'Woof! I am Rex',
 3,
 'Use the extends keyword to inherit from a parent class.', 'Usa la palabra clave extends para heredar de una clase padre.',
 'Child classes can override parent methods by redefining them.', 'Las clases hijas pueden sobreescribir los métodos del padre redefiniéndolos.',
 'extends', 'extends',
 30, 5, now()),

-- 55. interfaces
(gen_random_uuid(),
 'Interface Definition', 'Definición de Interfaz',
 'Define interface Drawable with method draw(): string. Implement it in class Circle to return "Drawing circle". Echo it.',
 'Define la interfaz Drawable con el método draw(): string. Impleméntala en Circle para retornar "Drawing circle". Muéstralo.',
 'php', 3, 'interfaces',
 '<?php\ninterface Drawable {\n    public function draw(): string;\n}\nclass Circle ___ Drawable {\n    public function draw(): string {\n        return "Drawing circle";\n    }\n}\necho (new Circle())->draw();\n?>',
 'Drawing circle',
 3,
 'A class implements an interface using the implements keyword.', 'Una clase implementa una interfaz usando la palabra clave implements.',
 'All methods declared in the interface must be implemented in the class.', 'Todos los métodos declarados en la interfaz deben implementarse en la clase.',
 'implements', 'implements',
 30, 5, now()),

-- 56. traits
(gen_random_uuid(),
 'Trait Usage', 'Uso de Traits',
 'Define trait Logger with method log($msg) that echoes $msg. Use it in class App and call log("started").',
 'Define el trait Logger con el método log($msg) que muestre $msg. Úsalo en la clase App y llama log("started").',
 'php', 3, 'traits',
 '<?php\ntrait Logger {\n    public function log(string $msg): void {\n        echo $msg;\n    }\n}\nclass App {\n    ___ Logger;\n}\n(new App())->log("started");\n?>',
 'started',
 3,
 'Include a trait in a class using the use keyword inside the class body.', 'Incluye un trait en una clase usando la palabra clave use dentro del cuerpo de la clase.',
 'Traits provide reusable method implementations across multiple classes.', 'Los traits proporcionan implementaciones de métodos reutilizables en múltiples clases.',
 'use', 'use',
 30, 5, now()),

-- 57. traits
(gen_random_uuid(),
 'Multiple Traits', 'Múltiples Traits',
 'Define traits Greetable (greet() echoes "Hello") and Farewell (bye() echoes "Goodbye"). Use both in class Host. Call both.',
 'Define los traits Greetable (greet() muestra "Hello") y Farewell (bye() muestra "Goodbye"). Úsalos ambos en Host. Llama a ambos.',
 'php', 3, 'traits',
 '<?php\ntrait Greetable {\n    public function greet(): void { echo "Hello"; }\n}\ntrait Farewell {\n    public function bye(): void { echo "Goodbye"; }\n}\nclass Host {\n    use Greetable, ___;\n}\n$h = new Host();\n$h->greet();\necho " ";\n$h->bye();\n?>',
 'Hello Goodbye',
 3,
 'Separate multiple trait names with a comma inside the use statement.', 'Separa múltiples nombres de trait con coma dentro de la sentencia use.',
 'A class can use as many traits as needed.', 'Una clase puede usar tantos traits como sea necesario.',
 'Farewell', 'Farewell',
 30, 5, now()),

-- 58. namespaces
(gen_random_uuid(),
 'Namespace Declaration', 'Declaración de Namespace',
 'Declare namespace App\Models, define class User with method getName() returning "Alice", and echo it.',
 'Declara el namespace App\Models, define la clase User con el método getName() retornando "Alice" y muéstralo.',
 'php', 3, 'namespaces',
 '<?php\n___ App\\Models;\nclass User {\n    public function getName(): string { return "Alice"; }\n}\necho (new User())->getName();\n?>',
 'Alice',
 3,
 'The namespace keyword must appear at the top of the file after <?php.', 'La palabra clave namespace debe aparecer al inicio del archivo después de <?php.',
 'Namespace parts are separated by backslashes.', 'Las partes del namespace se separan por barras invertidas.',
 'namespace', 'namespace',
 30, 5, now()),

-- 59. namespaces
(gen_random_uuid(),
 'Use Statement', 'Sentencia Use',
 'Given namespace App\Utils with class Formatter, use a "use" alias to import it as Fmt and call Fmt::format().',
 'Dado el namespace App\Utils con la clase Formatter, usa "use" con alias para importarla como Fmt y llama Fmt::format().',
 'php', 3, 'namespaces',
 '<?php\nnamespace App\\Utils;\nclass Formatter {\n    public static function format(): string { return "formatted"; }\n}\n\nnamespace App;\nuse App\\Utils\\Formatter ___ Fmt;\necho Fmt::format();\n?>',
 'formatted',
 3,
 'Use the "as" keyword to create an alias when importing a class.', 'Usa la palabra clave "as" para crear un alias al importar una clase.',
 'Static methods are called with :: (double colon).', 'Los métodos estáticos se llaman con :: (doble dos puntos).',
 'as', 'as',
 30, 5, now()),

-- 60. classes
(gen_random_uuid(),
 'Static Method', 'Método Estático',
 'Define class MathHelper with static method square(int $n): int that returns $n * $n. Echo MathHelper::square(5).',
 'Define la clase MathHelper con el método estático square(int $n): int que retorne $n * $n. Muestra MathHelper::square(5).',
 'php', 3, 'classes',
 '<?php\nclass MathHelper {\n    public ___ function square(int $n): int {\n        return $n * $n;\n    }\n}\necho MathHelper::square(5);\n?>',
 '25',
 3,
 'Use the static keyword before function to define a static method.', 'Usa la palabra clave static antes de function para definir un método estático.',
 'Static methods belong to the class itself, not instances.', 'Los métodos estáticos pertenecen a la clase misma, no a las instancias.',
 'static', 'static',
 30, 5, now()),

-- 61. classes
(gen_random_uuid(),
 'Abstract Class', 'Clase Abstracta',
 'Define abstract class Shape with abstract method area(): float. Implement Square($side) where area = side^2. Echo area of Square(4).',
 'Define la clase abstracta Shape con el método abstracto area(): float. Implementa Square($side) donde area = side^2. Muestra el área de Square(4).',
 'php', 3, 'classes',
 '<?php\n___ class Shape {\n    abstract public function area(): float;\n}\nclass Square extends Shape {\n    public function __construct(private float $side) {}\n    public function area(): float { return $this->side ** 2; }\n}\necho (new Square(4))->area();\n?>',
 '16',
 3,
 'Use the abstract keyword before class to define an abstract class.', 'Usa la palabra clave abstract antes de class para definir una clase abstracta.',
 'Abstract classes cannot be instantiated directly.', 'Las clases abstractas no pueden instanciarse directamente.',
 'abstract', 'abstract',
 30, 5, now()),

-- 62. type-hints
(gen_random_uuid(),
 'Union Types', 'Tipos Unión',
 'Define process(int|string $val): string that returns "num" if int, "str" if string. Echo process(42).',
 'Define process(int|string $val): string que retorne "num" si es int, "str" si es string. Muestra process(42).',
 'php', 3, 'type-hints',
 '<?php\nfunction process(int|string $val): string {\n    return is_int(___) ? "num" : "str";\n}\necho process(42);\n?>',
 'num',
 3,
 'Use is_int() to check whether a value is an integer.', 'Usa is_int() para comprobar si un valor es un entero.',
 'Pass $val to is_int() to check the type at runtime.', 'Pasa $val a is_int() para comprobar el tipo en tiempo de ejecución.',
 '$val', '$val',
 30, 5, now()),

-- 63. type-hints
(gen_random_uuid(),
 'Return Type void', 'Tipo de Retorno void',
 'Define printLine(string $msg): void that echoes $msg and a newline. Call it with "done".',
 'Define printLine(string $msg): void que muestre $msg y una nueva línea. Llámala con "done".',
 'php', 3, 'type-hints',
 '<?php\nfunction printLine(string $msg): ___ {\n    echo $msg . "\n";\n}\nprintLine("done");\n?>',
 "done",
 3,
 'A void return type indicates the function does not return a value.', 'Un tipo de retorno void indica que la función no devuelve un valor.',
 'Functions with void must not have a return statement with a value.', 'Las funciones con void no deben tener una sentencia return con valor.',
 'void', 'void',
 30, 5, now()),

-- 64. match
(gen_random_uuid(),
 'Match with No Default', 'Match sin Default',
 'Use match($code) where $code = 200 to return "OK", 404 to return "Not Found". Echo the result.',
 'Usa match($code) donde $code = 200 para retornar "OK", 404 para retornar "Not Found". Muestra el resultado.',
 'php', 3, 'control-flow',
 '<?php\n$code = 200;\n$msg = match($code) {\n    200 => ___,\n    404 => "Not Found",\n};\necho $msg;\n?>',
 'OK',
 3,
 'Provide the string "OK" as the value for the 200 arm.', 'Proporciona la cadena "OK" como valor para la rama 200.',
 'match arms use => to map a value to its result.', 'Las ramas match usan => para mapear un valor a su resultado.',
 '"OK"', '"OK"',
 30, 5, now()),

-- 65. strings
(gen_random_uuid(),
 'Regex Match', 'Coincidencia Regex',
 'Use preg_match() to check if "php8" matches /[a-z]+\d+/ and echo "match" if it does.',
 'Usa preg_match() para comprobar si "php8" coincide con /[a-z]+\d+/ y muestra "match" si coincide.',
 'php', 3, 'strings',
 '<?php\nif (___(  "/[a-z]+\\d+/", "php8")) {\n    echo "match";\n}\n?>',
 'match',
 3,
 'preg_match() returns 1 if the pattern matches, 0 if it does not.', 'preg_match() devuelve 1 si el patrón coincide, 0 si no.',
 'Pass the pattern as the first argument and the subject string as the second.', 'Pasa el patrón como primer argumento y la cadena sujeto como segundo.',
 'preg_match', 'preg_match',
 30, 5, now()),

-- 66. strings
(gen_random_uuid(),
 'Regex Replace', 'Reemplazar con Regex',
 'Use preg_replace() to replace all digits in "abc123def" with "#" and echo the result.',
 'Usa preg_replace() para reemplazar todos los dígitos en "abc123def" con "#" y muestra el resultado.',
 'php', 3, 'strings',
 '<?php\necho preg_replace("/\\d/", ___, "abc123def");\n?>',
 'abc###def',
 3,
 'The second argument to preg_replace() is the replacement string.', 'El segundo argumento de preg_replace() es la cadena de reemplazo.',
 'Pass "#" as the replacement for each matched digit.', 'Pasa "#" como reemplazo de cada dígito coincidente.',
 '"#"', '"#"',
 30, 5, now()),

-- 67. arrays
(gen_random_uuid(),
 'Multidimensional Array', 'Array Multidimensional',
 'Given $matrix = [[1,2],[3,4]], echo the value at row 1, column 0.',
 'Dado $matrix = [[1,2],[3,4]], muestra el valor en la fila 1, columna 0.',
 'php', 3, 'arrays',
 '<?php\n$matrix = [[1,2],[3,4]];\necho $matrix[___][0];\n?>',
 '3',
 3,
 'Access the second row with index 1.', 'Accede a la segunda fila con el índice 1.',
 'Then access column 0 of that row.', 'Luego accede a la columna 0 de esa fila.',
 '1', '1',
 30, 5, now()),

-- 68. arrays
(gen_random_uuid(),
 'Usort Custom Sort', 'Ordenación Personalizada con Usort',
 'Use usort() to sort $words = ["banana","apple","cherry"] alphabetically and echo the first.',
 'Usa usort() para ordenar $words = ["banana","apple","cherry"] alfabéticamente y muestra el primero.',
 'php', 3, 'arrays',
 '<?php\n$words = ["banana","apple","cherry"];\nusort($words, function($a, $b) { return ___(  $a, $b); });\necho $words[0];\n?>',
 'apple',
 3,
 'usort() sorts using a custom comparison function that returns -1, 0, or 1.', 'usort() ordena usando una función de comparación personalizada que retorna -1, 0 o 1.',
 'strcmp() compares two strings alphabetically.', 'strcmp() compara dos cadenas alfabéticamente.',
 'strcmp', 'strcmp',
 30, 5, now()),

-- 69. classes
(gen_random_uuid(),
 'Magic __toString', 'Método Mágico __toString',
 'Add __toString() to class Point(int $x, int $y) that returns "($x,$y)". Echo new Point(3, 4).',
 'Agrega __toString() a la clase Point(int $x, int $y) que retorne "($x,$y)". Muestra new Point(3, 4).',
 'php', 3, 'classes',
 '<?php\nclass Point {\n    public function __construct(private int $x, private int $y) {}\n    public function ___(): string {\n        return "({$this->x},{$this->y})";\n    }\n}\necho new Point(3, 4);\n?>',
 '(3,4)',
 3,
 '__toString() is called automatically when an object is used in a string context.', '__toString() se llama automáticamente cuando se usa un objeto en contexto de cadena.',
 'Return the formatted string from __toString.', 'Retorna la cadena formateada desde __toString.',
 '__toString', '__toString',
 30, 5, now()),

-- 70. functions
(gen_random_uuid(),
 'Closure Binding', 'Vinculación de Closure',
 'Use use() to capture $prefix = "Hello" in a closure, then echo the closure with " World".',
 'Usa use() para capturar $prefix = "Hello" en un closure, luego muestra el closure con " World".',
 'php', 3, 'functions',
 '<?php\n$prefix = "Hello";\n$greet = function(string $name) ___ ($prefix) {\n    return $prefix . " " . $name;\n};\necho $greet("World");\n?>',
 'Hello World',
 3,
 'Closures capture outer variables using the use() clause.', 'Los closures capturan variables externas usando la cláusula use().',
 'List the variables to capture inside the use() parentheses.', 'Lista las variables a capturar dentro de los paréntesis de use().',
 'use', 'use',
 30, 5, now()),

-- 71. type-hints
(gen_random_uuid(),
 'Array Type Hint', 'Tipo Indicado Array',
 'Define sumArray(array $nums): int that returns array_sum($nums). Echo sumArray([1,2,3,4]).',
 'Define sumArray(array $nums): int que retorne array_sum($nums). Muestra sumArray([1,2,3,4]).',
 'php', 3, 'type-hints',
 '<?php\nfunction sumArray(___ $nums): int {\n    return array_sum($nums);\n}\necho sumArray([1,2,3,4]);\n?>',
 '10',
 3,
 'Use "array" as the type hint to enforce that the parameter is an array.', 'Usa "array" como tipo indicado para exigir que el parámetro sea un array.',
 'This is the built-in array type, not a class name.', 'Este es el tipo array incorporado, no un nombre de clase.',
 'array', 'array',
 30, 5, now()),

-- 72. classes
(gen_random_uuid(),
 'Interface Multiple Implement', 'Implementar Múltiples Interfaces',
 'Define interfaces Serializable (serialize()) and Loggable (log()). Implement both in class Event that echoes "serialized|logged".',
 'Define las interfaces Serializable (serialize()) y Loggable (log()). Implementa ambas en la clase Event que muestre "serialized|logged".',
 'php', 3, 'interfaces',
 '<?php\ninterface Serializable { public function serialize(): void; }\ninterface Loggable { public function log(): void; }\nclass Event implements Serializable, ___ {\n    public function serialize(): void { echo "serialized"; }\n    public function log(): void { echo "|logged"; }\n}\n$e = new Event();\n$e->serialize();\n$e->log();\n?>',
 'serialized|logged',
 3,
 'A class can implement multiple interfaces separated by commas.', 'Una clase puede implementar múltiples interfaces separadas por comas.',
 'List Loggable after the comma in the implements clause.', 'Lista Loggable después de la coma en la cláusula implements.',
 'Loggable', 'Loggable',
 30, 5, now()),

-- 73. strings
(gen_random_uuid(),
 'Heredoc Syntax', 'Sintaxis Heredoc',
 'Use heredoc (<<<EOT) to echo a multiline string "Line 1\nLine 2".',
 'Usa heredoc (<<<EOT) para mostrar una cadena multilínea "Line 1\nLine 2".',
 'php', 3, 'strings',
 '<?php\necho <<<EOT\nLine 1\n___\nEOT;\n?>',
 "Line 1\nLine 2",
 3,
 'Heredoc text is written between the opening <<<EOT and closing EOT; markers.', 'El texto heredoc se escribe entre los marcadores <<<EOT y EOT;.',
 'Each line of the heredoc becomes a literal line in the output.', 'Cada línea del heredoc se convierte en una línea literal en la salida.',
 'Line 2', 'Line 2',
 30, 5, now()),

-- 74. arrays
(gen_random_uuid(),
 'Array Chunk', 'Dividir Array en Trozos',
 'Use array_chunk() to split [1,2,3,4,5] into chunks of 2 and echo the count of chunks.',
 'Usa array_chunk() para dividir [1,2,3,4,5] en trozos de 2 y muestra el número de trozos.',
 'php', 3, 'arrays',
 '<?php\n$chunks = array_chunk([1,2,3,4,5], ___);\necho count($chunks);\n?>',
 '3',
 3,
 'array_chunk() splits an array into chunks of the specified size.', 'array_chunk() divide un array en trozos del tamaño especificado.',
 'Chunks of size 2 from 5 elements gives 3 chunks (2, 2, 1).', 'Trozos de tamaño 2 de 5 elementos da 3 trozos (2, 2, 1).',
 '2', '2',
 30, 5, now()),

-- 75. classes
(gen_random_uuid(),
 'Constructor Property Promotion', 'Promoción de Propiedades en Constructor',
 'Use constructor promotion to define class Product(public string $name, public float $price). Echo (new Product("Book", 12.99))->name.',
 'Usa la promoción de propiedades en el constructor para definir la clase Product(public string $name, public float $price). Muestra (new Product("Book", 12.99))->name.',
 'php', 3, 'classes',
 '<?php\nclass Product {\n    public function __construct(\n        ___ string $name,\n        public float $price\n    ) {}\n}\necho (new Product("Book", 12.99))->name;\n?>',
 'Book',
 3,
 'Constructor property promotion uses visibility keywords (public/private/protected) in the parameter list.', 'La promoción de propiedades usa palabras clave de visibilidad (public/private/protected) en la lista de parámetros.',
 'Add the "public" visibility keyword before the type hint.', 'Agrega la palabra clave de visibilidad "public" antes del tipo indicado.',
 'public', 'public',
 30, 5, now()),

-- ============================================================
-- DIFFICULTY 4 — 15 exercises (points=50, penalty=10)
-- ============================================================

-- 76. PDO
(gen_random_uuid(),
 'PDO Connection', 'Conexión PDO',
 'Write the DSN string to connect to MySQL "mydb" on localhost and assign it to $dsn.',
 'Escribe la cadena DSN para conectar a MySQL "mydb" en localhost y asígnala a $dsn.',
 'php', 4, 'pdo',
 '<?php\n$dsn = ___;\n// $pdo = new PDO($dsn, $user, $pass);\necho $dsn;\n?>',
 'mysql:host=localhost;dbname=mydb',
 3,
 'A PDO DSN for MySQL starts with "mysql:" followed by key=value pairs separated by semicolons.', 'Un DSN de PDO para MySQL empieza con "mysql:" seguido de pares clave=valor separados por punto y coma.',
 'Include host and dbname in the DSN.', 'Incluye host y dbname en el DSN.',
 '"mysql:host=localhost;dbname=mydb"', '"mysql:host=localhost;dbname=mydb"',
 50, 10, now()),

-- 77. PDO
(gen_random_uuid(),
 'PDO Prepared Statement', 'Sentencia Preparada PDO',
 'Given $pdo, write a prepared SELECT with a :id placeholder for "SELECT name FROM users WHERE id = :id".',
 'Dado $pdo, escribe un SELECT preparado con el marcador :id para "SELECT name FROM users WHERE id = :id".',
 'php', 4, 'pdo',
 '<?php\n// assume $pdo is a valid PDO instance\n$stmt = $pdo->___(  "SELECT name FROM users WHERE id = :id");\n$stmt->execute(["id" => 1]);\n?>',
 'SELECT name FROM users WHERE id = :id',
 3,
 'PDO::prepare() compiles the SQL statement and returns a PDOStatement.', 'PDO::prepare() compila la sentencia SQL y devuelve un PDOStatement.',
 'Use named placeholders like :id in the SQL string.', 'Usa marcadores con nombre como :id en la cadena SQL.',
 'prepare', 'prepare',
 50, 10, now()),

-- 78. PDO
(gen_random_uuid(),
 'PDO Fetch Row', 'Obtener Fila con PDO',
 'After executing a statement, use fetch(PDO::FETCH_ASSOC) to retrieve one row and echo $row["name"].',
 'Después de ejecutar una sentencia, usa fetch(PDO::FETCH_ASSOC) para obtener una fila y muestra $row["name"].',
 'php', 4, 'pdo',
 '<?php\n// assume $stmt was executed and contains rows\n$row = $stmt->___(PDO::FETCH_ASSOC);\necho $row["name"];\n?>',
 'Alice',
 3,
 'fetch() retrieves the next row from the result set.', 'fetch() recupera la siguiente fila del conjunto de resultados.',
 'PDO::FETCH_ASSOC returns rows as associative arrays.', 'PDO::FETCH_ASSOC devuelve filas como arrays asociativos.',
 'fetch', 'fetch',
 50, 10, now()),

-- 79. classes
(gen_random_uuid(),
 'Late Static Binding', 'Enlace Estático Tardío',
 'Use static:: instead of self:: so that a child class returns its own class name. Echo Child::create() from class Child extends Base.',
 'Usa static:: en lugar de self:: para que una clase hija devuelva su propio nombre de clase. Muestra Child::create() de Child extends Base.',
 'php', 4, 'classes',
 '<?php\nclass Base {\n    public static function create(): string {\n        return ___::class;\n    }\n}\nclass Child extends Base {}\necho Child::create();\n?>',
 'Child',
 3,
 'static:: resolves at runtime to the class on which the method was called.', 'static:: se resuelve en tiempo de ejecución a la clase desde la que se llamó al método.',
 'self:: always refers to the class where the method is defined.', 'self:: siempre hace referencia a la clase donde se define el método.',
 'static', 'static',
 50, 10, now()),

-- 80. generators
(gen_random_uuid(),
 'Generator Function', 'Función Generadora',
 'Define a generator range_gen($start, $end) that yields each number from $start to $end. Echo values 1 to 3.',
 'Define un generador range_gen($start, $end) que produzca cada número de $start a $end. Muestra los valores del 1 al 3.',
 'php', 4, 'functions',
 '<?php\nfunction range_gen(int $start, int $end): Generator {\n    for ($i = $start; $i <= $end; $i++) {\n        ___ $i;\n    }\n}\nforeach (range_gen(1, 3) as $v) {\n    echo $v . "\n";\n}\n?>',
 "1\n2\n3",
 3,
 'Use the yield keyword to pause the function and return a value.', 'Usa la palabra clave yield para pausar la función y retornar un valor.',
 'A function that contains yield automatically becomes a Generator.', 'Una función que contiene yield se convierte automáticamente en un Generator.',
 'yield', 'yield',
 50, 10, now()),

-- 81. interfaces
(gen_random_uuid(),
 'Interface Type Hint', 'Tipo Indicado de Interfaz',
 'Define interface Printable with method print(): void. Write render(Printable $p) that calls $p->print(). Echo via Document class.',
 'Define la interfaz Printable con el método print(): void. Escribe render(Printable $p) que llame $p->print(). Muestra usando la clase Document.',
 'php', 4, 'interfaces',
 '<?php\ninterface Printable {\n    public function print(): void;\n}\nclass Document implements Printable {\n    public function print(): void { echo "Document printed"; }\n}\nfunction render(___ $p): void {\n    $p->print();\n}\nrender(new Document());\n?>',
 'Document printed',
 3,
 'Use the interface name as the type hint to accept any class that implements it.', 'Usa el nombre de la interfaz como tipo indicado para aceptar cualquier clase que la implemente.',
 'This is called programming to an interface — a key OOP principle.', 'Esto se llama programar contra una interfaz — un principio clave de POO.',
 'Printable', 'Printable',
 50, 10, now()),

-- 82. namespaces
(gen_random_uuid(),
 'Autoloading PSR-4', 'Autocarga PSR-4',
 'Given composer.json maps "App\\" to "src/", what file path would the PSR-4 autoloader look for App\Services\Mailer? Echo the path.',
 'Dado que composer.json mapea "App\\" a "src/", ¿qué ruta de archivo buscará el autocargador PSR-4 para App\Services\Mailer? Muestra la ruta.',
 'php', 4, 'namespaces',
 '<?php\necho ___;\n?>',
 'src/Services/Mailer.php',
 3,
 'PSR-4 maps namespace prefixes to directories, then converts \\ to directory separators.', 'PSR-4 mapea prefijos de namespace a directorios, luego convierte \\ en separadores de directorio.',
 'Strip the "App\\" prefix, replace remaining \\ with /, and append .php.', 'Elimina el prefijo "App\\", reemplaza los \\ restantes con / y agrega .php.',
 '"src/Services/Mailer.php"', '"src/Services/Mailer.php"',
 50, 10, now()),

-- 83. classes
(gen_random_uuid(),
 'Readonly Properties', 'Propiedades de Solo Lectura',
 'Define class Config with readonly string $env. Set it in the constructor. Echo (new Config("production"))->env.',
 'Define la clase Config con la propiedad readonly string $env. Establécela en el constructor. Muestra (new Config("production"))->env.',
 'php', 4, 'classes',
 '<?php\nclass Config {\n    public function __construct(public ___ string $env) {}\n}\necho (new Config("production"))->env;\n?>',
 'production',
 3,
 'readonly properties can only be initialized once, in the constructor.', 'Las propiedades readonly solo pueden inicializarse una vez, en el constructor.',
 'Use the readonly keyword between the visibility modifier and the type.', 'Usa la palabra clave readonly entre el modificador de visibilidad y el tipo.',
 'readonly', 'readonly',
 50, 10, now()),

-- 84. fibers
(gen_random_uuid(),
 'Fiber Basics', 'Conceptos Básicos de Fiber',
 'Create a Fiber that suspends and yields "hello". Start the fiber, then resume it and echo the yielded value.',
 'Crea un Fiber que se suspenda y produzca "hello". Inicia el fiber, luego reanúdalo y muestra el valor producido.',
 'php', 4, 'functions',
 '<?php\n$fiber = new Fiber(function(): void {\n    $val = Fiber::___(  "hello");\n});\n$result = $fiber->start();\necho $result;\n?>',
 'hello',
 3,
 'Fiber::suspend() pauses execution of the fiber and returns a value to the caller.', 'Fiber::suspend() pausa la ejecución del fiber y devuelve un valor al llamador.',
 'The value passed to suspend() is returned by start() or resume().', 'El valor pasado a suspend() es devuelto por start() o resume().',
 'suspend', 'suspend',
 50, 10, now()),

-- 85. composer
(gen_random_uuid(),
 'Composer Require Dev', 'Composer Require Dev',
 'Write the composer command to add phpunit/phpunit as a dev dependency.',
 'Escribe el comando composer para agregar phpunit/phpunit como dependencia de desarrollo.',
 'php', 4, 'composer',
 '<?php\n// What command installs phpunit/phpunit as a dev dependency?\necho ___;\n?>',
 'composer require --dev phpunit/phpunit',
 3,
 'Dev dependencies are only needed during development and testing.', 'Las dependencias de desarrollo solo se necesitan durante el desarrollo y las pruebas.',
 'Use the --dev flag with composer require.', 'Usa la bandera --dev con composer require.',
 '"composer require --dev phpunit/phpunit"', '"composer require --dev phpunit/phpunit"',
 50, 10, now()),

-- 86. classes
(gen_random_uuid(),
 'Named Arguments', 'Argumentos Nombrados',
 'Call htmlspecialchars($str, double_encode: false) using named arguments. $str = "<b>test</b>". Echo the result.',
 'Llama a htmlspecialchars($str, double_encode: false) usando argumentos nombrados. $str = "<b>test</b>". Muestra el resultado.',
 'php', 4, 'classes',
 '<?php\n$str = "<b>test</b>";\necho htmlspecialchars($str, double_encode: ___);\n?>',
 '&lt;b&gt;test&lt;/b&gt;',
 3,
 'Named arguments allow passing arguments in any order by name.', 'Los argumentos nombrados permiten pasar argumentos en cualquier orden por nombre.',
 'Set double_encode to false to prevent double-encoding already-encoded entities.', 'Establece double_encode en false para evitar codificar doble los entities ya codificados.',
 'false', 'false',
 50, 10, now()),

-- 87. arrays
(gen_random_uuid(),
 'Array Spread Operator', 'Operador Spread en Arrays',
 'Merge $a = [1, 2] and $b = [3, 4] using the spread operator and echo as JSON.',
 'Fusiona $a = [1, 2] y $b = [3, 4] usando el operador spread y muéstralos como JSON.',
 'php', 4, 'arrays',
 '<?php\n$a = [1, 2];\n$b = [3, 4];\n$c = [___$a, ...$b];\necho json_encode($c);\n?>',
 '[1,2,3,4]',
 3,
 'The spread operator (...) expands an array into individual elements.', 'El operador spread (...) expande un array en elementos individuales.',
 'Use ...$a to spread the contents of $a into the new array literal.', 'Usa ...$a para expandir el contenido de $a en el nuevo literal de array.',
 '...', '...',
 50, 10, now()),

-- 88. type-hints
(gen_random_uuid(),
 'Intersection Types', 'Tipos de Intersección',
 'Define function process(Countable&Iterator $col): void that echoes count($col). Pass a suitable object.',
 'Define function process(Countable&Iterator $col): void que muestre count($col). Pasa un objeto adecuado.',
 'php', 4, 'type-hints',
 '<?php\nfunction process(Countable_Iterator $col): void {\n    echo count($col);\n}\n$arr = new ArrayObject([1, 2, 3]);\nprocess($arr);\n?>',
 '3',
 3,
 'Intersection types require the value to satisfy all the listed types.', 'Los tipos de intersección requieren que el valor satisfaga todos los tipos listados.',
 'Use & between type names for intersection types.', 'Usa & entre nombres de tipo para los tipos de intersección.',
 'Countable&Iterator', 'Countable&Iterator',
 50, 10, now()),

-- 89. closures
(gen_random_uuid(),
 'Memoization Closure', 'Closure de Memoización',
 'Write a memoize($fn) function returning a closure that caches results in $cache. Call it on a squaring function with input 5.',
 'Escribe una función memoize($fn) que retorne un closure que almacene resultados en $cache. Llámala con una función al cuadrado con entrada 5.',
 'php', 4, 'functions',
 '<?php\nfunction memoize(callable $fn): Closure {\n    $cache = [];\n    return function() ___ ($fn, $cache) {\n        $args = func_get_args();\n        $key = serialize($args);\n        if (!isset($cache[$key])) {\n            $cache[$key] = $fn(...$args);\n        }\n        return $cache[$key];\n    };\n}\n$square = memoize(fn($n) => $n * $n);\necho $square(5);\n?>',
 '25',
 3,
 'Use "use" to capture $fn and $cache by reference or value.', 'Usa "use" para capturar $fn y $cache por referencia o valor.',
 'Capture $cache by reference (&$cache) so updates persist across calls.', 'Captura $cache por referencia (&$cache) para que las actualizaciones persistan entre llamadas.',
 'use', 'use',
 50, 10, now()),

-- 90. classes
(gen_random_uuid(),
 'Covariant Return Types', 'Tipos de Retorno Covariantes',
 'Define Base::create(): Base and Child::create(): Child (covariant). Echo get_class(Child::create()).',
 'Define Base::create(): Base y Child::create(): Child (covariante). Muestra get_class(Child::create()).',
 'php', 4, 'classes',
 '<?php\nclass Base {\n    public static function create(): static {\n        return new ___();\n    }\n}\nclass Child extends Base {}\necho get_class(Child::create());\n?>',
 'Child',
 3,
 'Use "static" as the return type to enable covariant returns in PHP 8.', 'Usa "static" como tipo de retorno para habilitar retornos covariantes en PHP 8.',
 '"new static()" creates an instance of the class it is called on.', '"new static()" crea una instancia de la clase desde la que se llama.',
 'static', 'static',
 50, 10, now()),

-- ============================================================
-- DIFFICULTY 5 — 10 exercises (points=100, penalty=10)
-- ============================================================

-- 91. laravel
(gen_random_uuid(),
 'Laravel Route Closure', 'Ruta Laravel con Closure',
 'Write a Laravel Route::get for "/hello" that returns "Hello from Laravel". Show the full route definition.',
 'Escribe una Route::get de Laravel para "/hello" que retorne "Hello from Laravel". Muestra la definición completa de la ruta.',
 'php', 5, 'laravel',
 '<?php\nuse Illuminate\\Support\\Facades\\Route;\n\nRoute::___(  "/hello", function() {\n    return "Hello from Laravel";\n});\n?>',
 'Hello from Laravel',
 3,
 'Route::get() registers a GET HTTP route with a URI and a callback.', 'Route::get() registra una ruta HTTP GET con una URI y un callback.',
 'The second argument is a closure that returns the response.', 'El segundo argumento es un closure que retorna la respuesta.',
 'get', 'get',
 100, 10, now()),

-- 92. laravel
(gen_random_uuid(),
 'Laravel Eloquent Model', 'Modelo Eloquent de Laravel',
 'Define a Laravel Eloquent model User that connects to table "users". Write the minimal class definition.',
 'Define un modelo Eloquent de Laravel User que se conecte a la tabla "users". Escribe la definición mínima de la clase.',
 'php', 5, 'laravel',
 '<?php\nnamespace App\\Models;\n\nuse Illuminate\\Database\\Eloquent\\___ as Model;\n\nclass User extends Model\n{\n    protected $table = "users";\n}\n?>',
 'App\Models\User',
 3,
 'Eloquent models extend the base Model class from the Illuminate package.', 'Los modelos Eloquent extienden la clase Model base del paquete Illuminate.',
 'Import it from Illuminate\Database\Eloquent\Model.', 'Impórtalo desde Illuminate\Database\Eloquent\Model.',
 'Model', 'Model',
 100, 10, now()),

-- 93. laravel
(gen_random_uuid(),
 'Laravel Middleware', 'Middleware de Laravel',
 'Write a Laravel middleware handle() that adds an X-App-Version header with value "1.0" to the response.',
 'Escribe un middleware de Laravel handle() que agregue el encabezado X-App-Version con valor "1.0" a la respuesta.',
 'php', 5, 'laravel',
 '<?php\npublic function handle($request, Closure $next)\n{\n    $response = $next(___);\n    $response->header("X-App-Version", "1.0");\n    return $response;\n}\n?>',
 '1.0',
 3,
 'Call $next($request) to pass the request to the next layer and get the response.', 'Llama a $next($request) para pasar la solicitud a la siguiente capa y obtener la respuesta.',
 'You can then modify the $response before returning it.', 'Luego puedes modificar el $response antes de retornarlo.',
 '$request', '$request',
 100, 10, now()),

-- 94. design-patterns
(gen_random_uuid(),
 'Singleton Pattern', 'Patrón Singleton',
 'Implement a Singleton class DB with a private constructor and static getInstance() that returns the single instance. Echo get_class(DB::getInstance()).',
 'Implementa la clase Singleton DB con constructor privado y getInstance() estático que retorne la instancia única. Muestra get_class(DB::getInstance()).',
 'php', 5, 'design-patterns',
 '<?php\nclass DB {\n    private static ?DB $instance = null;\n    private function ___() {}\n    public static function getInstance(): static {\n        if (static::$instance === null) {\n            static::$instance = new static();\n        }\n        return static::$instance;\n    }\n}\necho get_class(DB::getInstance());\n?>',
 'DB',
 3,
 'The Singleton pattern restricts instantiation to one object by making the constructor private.', 'El patrón Singleton restringe la instanciación a un objeto haciendo el constructor privado.',
 'The constructor is named __construct.', 'El constructor se llama __construct.',
 '__construct', '__construct',
 100, 10, now()),

-- 95. design-patterns
(gen_random_uuid(),
 'Observer Pattern', 'Patrón Observer',
 'Implement Observer pattern: EventEmitter with subscribe() and emit(). Observer echoes the event name. Emit "login".',
 'Implementa el patrón Observer: EventEmitter con subscribe() y emit(). Observer muestra el nombre del evento. Emite "login".',
 'php', 5, 'design-patterns',
 '<?php\nclass EventEmitter {\n    private array $listeners = [];\n    public function subscribe(string $event, callable $cb): void {\n        $this->listeners[$event][] = $cb;\n    }\n    public function emit(string $event): void {\n        foreach ($this->listeners[$event] ___ [] as $cb) {\n            $cb($event);\n        }\n    }\n}\n$e = new EventEmitter();\n$e->subscribe("login", fn($ev) => print($ev));\n$e->emit("login");\n?>',
 'login',
 3,
 'Use the null coalescing operator to default to an empty array if no listeners exist.', 'Usa el operador null coalescing para usar un array vacío si no hay listeners.',
 'Place ?? [] after $this->listeners[$event] to handle missing keys safely.', 'Coloca ?? [] después de $this->listeners[$event] para manejar claves faltantes de forma segura.',
 '??', '??',
 100, 10, now()),

-- 96. async
(gen_random_uuid(),
 'ReactPHP Promise', 'Promesa ReactPHP',
 'Using ReactPHP''s React\Promise\resolve(), create a resolved promise with value "done" and echo it in then().',
 'Usando React\Promise\resolve() de ReactPHP, crea una promesa resuelta con el valor "done" y muéstralo en then().',
 'php', 5, 'async',
 '<?php\nuse React\\Promise;\n\n___(  "done")->then(function(string $val) {\n    echo $val;\n});\n?>',
 'done',
 3,
 'Promise\resolve() returns an already-resolved promise with the given value.', 'Promise\resolve() retorna una promesa ya resuelta con el valor dado.',
 'Use the fully-qualified function React\Promise\resolve() or import it.', 'Usa la función completamente calificada React\Promise\resolve() o impórtala.',
 'Promise\\resolve', 'Promise\\resolve',
 100, 10, now()),

-- 97. design-patterns
(gen_random_uuid(),
 'Decorator Pattern', 'Patrón Decorator',
 'Define interface Logger with log(). Implement ConsoleLogger (echoes msg). Wrap with TimestampLogger that prepends "[ts] ". Echo TimestampLogger->log("error").',
 'Define la interfaz Logger con log(). Implementa ConsoleLogger (muestra msg). Envuelve con TimestampLogger que antepone "[ts] ". Muestra TimestampLogger->log("error").',
 'php', 5, 'design-patterns',
 '<?php\ninterface Logger { public function log(string $msg): void; }\nclass ConsoleLogger implements Logger {\n    public function log(string $msg): void { echo $msg; }\n}\nclass TimestampLogger implements Logger {\n    public function __construct(private Logger $inner) {}\n    public function log(string $msg): void {\n        $this->inner->log("[ts] " . ___);\n    }\n}\n(new TimestampLogger(new ConsoleLogger()))->log("error");\n?>',
 '[ts] error',
 3,
 'The decorator delegates to the wrapped object after modifying the input or output.', 'El decorator delega al objeto envuelto después de modificar la entrada o salida.',
 'Concatenate "[ts] " with $msg and pass the result to $this->inner->log().', 'Concatena "[ts] " con $msg y pasa el resultado a $this->inner->log().',
 '$msg', '$msg',
 100, 10, now()),

-- 98. advanced-types
(gen_random_uuid(),
 'Enum Backed', 'Enum con Valor',
 'Define a backed enum Status: string with cases Active="active" and Inactive="inactive". Echo Status::Active->value.',
 'Define un enum respaldado Status: string con los casos Active="active" e Inactive="inactive". Muestra Status::Active->value.',
 'php', 5, 'advanced-types',
 '<?php\nenum Status: ___ {\n    case Active = "active";\n    case Inactive = "inactive";\n}\necho Status::Active->value;\n?>',
 'active',
 3,
 'Backed enums have an underlying scalar type declared after the colon.', 'Los enums respaldados tienen un tipo escalar subyacente declarado después de los dos puntos.',
 'Use "string" as the backing type for string-valued enum cases.', 'Usa "string" como tipo de respaldo para los casos de enum con valores de cadena.',
 'string', 'string',
 100, 10, now()),

-- 99. advanced-types
(gen_random_uuid(),
 'First-Class Callable Syntax', 'Sintaxis de Callable de Primera Clase',
 'Use the first-class callable syntax to assign strlen to $fn and echo $fn("hello").',
 'Usa la sintaxis de callable de primera clase para asignar strlen a $fn y muestra $fn("hello").',
 'php', 5, 'advanced-types',
 '<?php\n$fn = strlen(...);\necho ___("hello");\n?>',
 '5',
 3,
 'The ... syntax creates a Closure from any callable in PHP 8.1+.', 'La sintaxis ... crea un Closure a partir de cualquier callable en PHP 8.1+.',
 'Call $fn just like a regular function.', 'Llama a $fn como si fuera una función regular.',
 '$fn', '$fn',
 100, 10, now()),

-- 100. advanced-types
(gen_random_uuid(),
 'Fibers and Concurrency', 'Fibers y Concurrencia',
 'Create two Fibers: one yields "A", another yields "B". Start both and echo their yielded values in order.',
 'Crea dos Fibers: uno produce "A", otro produce "B". Inicia ambos y muestra sus valores producidos en orden.',
 'php', 5, 'advanced-types',
 '<?php\n$f1 = new Fiber(function(): void { Fiber::suspend("A"); });\n$f2 = new Fiber(function(): void { Fiber::suspend(___); });\necho $f1->start();\necho $f2->start();\n?>',
 'AB',
 3,
 'Each Fiber::start() runs the fiber until it hits Fiber::suspend() and returns the suspended value.', 'Cada Fiber::start() ejecuta el fiber hasta que llega a Fiber::suspend() y devuelve el valor suspendido.',
 'Pass "B" to Fiber::suspend() in the second fiber.', 'Pasa "B" a Fiber::suspend() en el segundo fiber.',
 '"B"', '"B"',
 100, 10, now())

ON CONFLICT DO NOTHING;

COMMIT;
