-- 058_exercises_csharp.sql
-- 100 C# programming exercises, bilingual EN+ES
-- Distribution: diff1:25, diff2:25, diff3:25, diff4:15, diff5:10

BEGIN;

INSERT INTO exercises (
  id, title_en, title_es, description_en, description_es,
  language, difficulty, category,
  starter_code, expected_output,
  hint_count, hint_1_en, hint_1_es, hint_2_en, hint_2_es, hint_3_en, hint_3_es,
  points, hints_used_penalty, created_at
) VALUES

-- ============================================================
-- DIFFICULTY 1 — 25 exercises (points: 10, penalty: 3)
-- ============================================================

(gen_random_uuid(),
 'Hello World', 'Hola Mundo',
 'Write a C# program that prints "Hello, World!" to the console.',
 'Escribe un programa en C# que imprima "Hello, World!" en la consola.',
 'csharp', 1, 'basics',
 'using System;\n\nclass Program {\n    static void Main() {\n        // your code\n    }\n}',
 'Hello, World!',
 3,
 'Use Console.WriteLine to print output in C#.', 'Usa Console.WriteLine para imprimir en C#.',
 'Console.WriteLine accepts a string argument.', 'Console.WriteLine acepta un argumento de tipo string.',
 'Console.WriteLine("Hello, World!");', 'Console.WriteLine("Hello, World!");',
 10, 3, now()),

(gen_random_uuid(),
 'Integer Addition', 'Suma de Enteros',
 'Declare two integer variables with values 8 and 5, then print their sum.',
 'Declara dos variables enteras con valores 8 y 5, luego imprime su suma.',
 'csharp', 1, 'math',
 'using System;\n\nclass Program {\n    static void Main() {\n        // your code\n    }\n}',
 '13',
 3,
 'Use the int type to declare integer variables.', 'Usa el tipo int para declarar variables enteras.',
 'Use the + operator to add two numbers.', 'Usa el operador + para sumar dos números.',
 'int a = 8, b = 5; Console.WriteLine(a + b);', 'int a = 8, b = 5; Console.WriteLine(a + b);',
 10, 3, now()),

(gen_random_uuid(),
 'String Concatenation', 'Concatenación de Cadenas',
 'Declare two string variables "Hello" and "World", concatenate them with a space, and print the result.',
 'Declara dos variables string "Hello" y "World", concaténalas con un espacio e imprime el resultado.',
 'csharp', 1, 'strings',
 'using System;\n\nclass Program {\n    static void Main() {\n        // your code\n    }\n}',
 'Hello World',
 3,
 'Use the + operator to concatenate strings.', 'Usa el operador + para concatenar cadenas.',
 'Add a space between the two strings.', 'Agrega un espacio entre las dos cadenas.',
 'Console.WriteLine(a + " " + b);', 'Console.WriteLine(a + " " + b);',
 10, 3, now()),

(gen_random_uuid(),
 'Boolean Variable', 'Variable Booleana',
 'Declare a bool variable set to true and print it.',
 'Declara una variable bool con valor true e imprímela.',
 'csharp', 1, 'basics',
 'using System;\n\nclass Program {\n    static void Main() {\n        // your code\n    }\n}',
 'True',
 3,
 'Use the bool type for true/false values.', 'Usa el tipo bool para valores verdadero/falso.',
 'C# prints bool as "True" or "False" (capital T/F).', 'C# imprime bool como "True" o "False" (T/F mayúscula).',
 'bool flag = true; Console.WriteLine(flag);', 'bool flag = true; Console.WriteLine(flag);',
 10, 3, now()),

(gen_random_uuid(),
 'Float Division', 'División de Decimales',
 'Divide 9.0 by 4.0 and print the result.',
 'Divide 9.0 entre 4.0 e imprime el resultado.',
 'csharp', 1, 'math',
 'using System;\n\nclass Program {\n    static void Main() {\n        // your code\n    }\n}',
 '2.25',
 3,
 'Use double or float to hold decimal values.', 'Usa double o float para almacenar valores decimales.',
 'Use 9.0 / 4.0 to ensure floating-point division.', 'Usa 9.0 / 4.0 para asegurar la división en punto flotante.',
 'Console.WriteLine(9.0 / 4.0);', 'Console.WriteLine(9.0 / 4.0);',
 10, 3, now()),

(gen_random_uuid(),
 'String Length', 'Longitud de Cadena',
 'Declare a string "Hello" and print its length.',
 'Declara una cadena "Hello" e imprime su longitud.',
 'csharp', 1, 'strings',
 'using System;\n\nclass Program {\n    static void Main() {\n        // your code\n    }\n}',
 '5',
 3,
 'Strings have a Length property in C#.', 'Las cadenas tienen una propiedad Length en C#.',
 'Access Length with dot notation: s.Length.', 'Accede a Length con notación de punto: s.Length.',
 'string s = "Hello"; Console.WriteLine(s.Length);', 'string s = "Hello"; Console.WriteLine(s.Length);',
 10, 3, now()),

(gen_random_uuid(),
 'Uppercase String', 'Cadena en Mayúsculas',
 'Convert the string "hello" to uppercase and print it.',
 'Convierte la cadena "hello" a mayúsculas e imprímela.',
 'csharp', 1, 'strings',
 'using System;\n\nclass Program {\n    static void Main() {\n        // your code\n    }\n}',
 'HELLO',
 3,
 'Strings have a ToUpper() method.', 'Las cadenas tienen un método ToUpper().',
 'ToUpper() returns a new string; the original is unchanged.', 'ToUpper() devuelve una nueva cadena; la original no cambia.',
 'Console.WriteLine("hello".ToUpper());', 'Console.WriteLine("hello".ToUpper());',
 10, 3, now()),

(gen_random_uuid(),
 'Modulo Operator', 'Operador Módulo',
 'Print the remainder when 17 is divided by 5.',
 'Imprime el resto cuando 17 se divide entre 5.',
 'csharp', 1, 'math',
 'using System;\n\nclass Program {\n    static void Main() {\n        // your code\n    }\n}',
 '2',
 3,
 'The % operator gives the remainder of integer division.', 'El operador % da el resto de la división entera.',
 '17 % 5 equals the remainder after dividing 17 by 5.', '17 % 5 es el resto después de dividir 17 entre 5.',
 'Console.WriteLine(17 % 5);', 'Console.WriteLine(17 % 5);',
 10, 3, now()),

(gen_random_uuid(),
 'Char Variable', 'Variable de Carácter',
 'Declare a char variable with value ''Z'' and print it.',
 'Declara una variable char con valor ''Z'' e imprímela.',
 'csharp', 1, 'basics',
 'using System;\n\nclass Program {\n    static void Main() {\n        // your code\n    }\n}',
 'Z',
 3,
 'Use single quotes for char literals in C#.', 'Usa comillas simples para literales char en C#.',
 'Declare: char c = ''Z'';', 'Declara: char c = ''Z'';',
 'Console.WriteLine(c);', 'Console.WriteLine(c);',
 10, 3, now()),

(gen_random_uuid(),
 'If-Else Statement', 'Sentencia If-Else',
 'Declare an integer with value 10. Print "Positive" if it is greater than 0, otherwise print "Non-positive".',
 'Declara un entero con valor 10. Imprime "Positive" si es mayor que 0, de lo contrario imprime "Non-positive".',
 'csharp', 1, 'control-flow',
 'using System;\n\nclass Program {\n    static void Main() {\n        // your code\n    }\n}',
 'Positive',
 3,
 'Use an if statement with a comparison operator.', 'Usa una sentencia if con un operador de comparación.',
 'The condition goes inside parentheses after if.', 'La condición va dentro de paréntesis después de if.',
 'if (n > 0) Console.WriteLine("Positive"); else Console.WriteLine("Non-positive");', 'if (n > 0) Console.WriteLine("Positive"); else Console.WriteLine("Non-positive");',
 10, 3, now()),

(gen_random_uuid(),
 'For Loop', 'Bucle For',
 'Use a for loop to print numbers 1 through 5, each on its own line.',
 'Usa un bucle for para imprimir los números del 1 al 5, cada uno en su propia línea.',
 'csharp', 1, 'loops',
 'using System;\n\nclass Program {\n    static void Main() {\n        // your code\n    }\n}',
 '1\n2\n3\n4\n5',
 3,
 'A for loop has init, condition, and increment sections.', 'Un bucle for tiene secciones de inicio, condición e incremento.',
 'Start at 1 and loop while i <= 5.', 'Comienza en 1 y haz el bucle mientras i <= 5.',
 'for (int i = 1; i <= 5; i++) Console.WriteLine(i);', 'for (int i = 1; i <= 5; i++) Console.WriteLine(i);',
 10, 3, now()),

(gen_random_uuid(),
 'While Loop', 'Bucle While',
 'Use a while loop to print the numbers 1, 2, 3.',
 'Usa un bucle while para imprimir los números 1, 2, 3.',
 'csharp', 1, 'loops',
 'using System;\n\nclass Program {\n    static void Main() {\n        // your code\n    }\n}',
 '1\n2\n3',
 3,
 'A while loop repeats as long as its condition is true.', 'Un bucle while se repite mientras su condición sea verdadera.',
 'Declare a counter variable before the loop.', 'Declara una variable contador antes del bucle.',
 'int i = 1; while (i <= 3) { Console.WriteLine(i); i++; }', 'int i = 1; while (i <= 3) { Console.WriteLine(i); i++; }',
 10, 3, now()),

(gen_random_uuid(),
 'Array Declaration', 'Declaración de Array',
 'Declare an integer array with values {2, 4, 6} and print each element.',
 'Declara un array de enteros con valores {2, 4, 6} e imprime cada elemento.',
 'csharp', 1, 'collections',
 'using System;\n\nclass Program {\n    static void Main() {\n        // your code\n    }\n}',
 '2\n4\n6',
 3,
 'Declare an array: int[] arr = {2, 4, 6};', 'Declara un array: int[] arr = {2, 4, 6};',
 'Use a foreach loop to iterate over an array.', 'Usa un bucle foreach para iterar sobre un array.',
 'foreach (int n in arr) Console.WriteLine(n);', 'foreach (int n in arr) Console.WriteLine(n);',
 10, 3, now()),

(gen_random_uuid(),
 'String Interpolation', 'Interpolación de Cadenas',
 'Declare a string variable name = "Alice" and an integer age = 30. Print "Alice is 30 years old." using string interpolation.',
 'Declara una variable string name = "Alice" y un entero age = 30. Imprime "Alice is 30 years old." usando interpolación de cadenas.',
 'csharp', 1, 'strings',
 'using System;\n\nclass Program {\n    static void Main() {\n        // your code\n    }\n}',
 'Alice is 30 years old.',
 3,
 'String interpolation uses the $ prefix before the string literal.', 'La interpolación de cadenas usa el prefijo $ antes del literal de cadena.',
 'Embed variables with {variableName} inside the string.', 'Incrusta variables con {nombreVariable} dentro de la cadena.',
 'Console.WriteLine($"{name} is {age} years old.");', 'Console.WriteLine($"{name} is {age} years old.");',
 10, 3, now()),

(gen_random_uuid(),
 'Ternary Operator', 'Operador Ternario',
 'Use the ternary operator to print "Even" if 8 is even, otherwise "Odd".',
 'Usa el operador ternario para imprimir "Even" si 8 es par, de lo contrario "Odd".',
 'csharp', 1, 'control-flow',
 'using System;\n\nclass Program {\n    static void Main() {\n        // your code\n    }\n}',
 'Even',
 3,
 'The ternary operator has the form: condition ? valueIfTrue : valueIfFalse.', 'El operador ternario tiene la forma: condición ? valorSiVerdadero : valorSiFalso.',
 'Check evenness with n % 2 == 0.', 'Comprueba si es par con n % 2 == 0.',
 'Console.WriteLine(8 % 2 == 0 ? "Even" : "Odd");', 'Console.WriteLine(8 % 2 == 0 ? "Even" : "Odd");',
 10, 3, now()),

(gen_random_uuid(),
 'Math.Max', 'Math.Max',
 'Print the larger of 42 and 17 using Math.Max.',
 'Imprime el mayor entre 42 y 17 usando Math.Max.',
 'csharp', 1, 'math',
 'using System;\n\nclass Program {\n    static void Main() {\n        // your code\n    }\n}',
 '42',
 3,
 'The System namespace provides a Math class with utility methods.', 'El espacio de nombres System provee una clase Math con métodos utilitarios.',
 'Math.Max(a, b) returns the greater of two values.', 'Math.Max(a, b) devuelve el mayor de dos valores.',
 'Console.WriteLine(Math.Max(42, 17));', 'Console.WriteLine(Math.Max(42, 17));',
 10, 3, now()),

(gen_random_uuid(),
 'String Contains', 'Cadena Contains',
 'Check whether the string "programming" contains "gram" and print the result.',
 'Comprueba si la cadena "programming" contiene "gram" e imprime el resultado.',
 'csharp', 1, 'strings',
 'using System;\n\nclass Program {\n    static void Main() {\n        // your code\n    }\n}',
 'True',
 3,
 'Strings have a Contains() method that returns a bool.', 'Las cadenas tienen un método Contains() que devuelve un bool.',
 'Pass the substring to Contains() as an argument.', 'Pasa la subcadena a Contains() como argumento.',
 'Console.WriteLine("programming".Contains("gram"));', 'Console.WriteLine("programming".Contains("gram"));',
 10, 3, now()),

(gen_random_uuid(),
 'Implicit Typed Variable', 'Variable de Tipo Implícito',
 'Use the var keyword to declare a variable holding the integer 99 and print it.',
 'Usa la palabra clave var para declarar una variable que contenga el entero 99 e imprímela.',
 'csharp', 1, 'basics',
 'using System;\n\nclass Program {\n    static void Main() {\n        // your code\n    }\n}',
 '99',
 3,
 'The var keyword lets the compiler infer the type.', 'La palabra clave var permite al compilador inferir el tipo.',
 'var x = 99; infers x as int.', 'var x = 99; infiere x como int.',
 'var x = 99; Console.WriteLine(x);', 'var x = 99; Console.WriteLine(x);',
 10, 3, now()),

(gen_random_uuid(),
 'String Trim', 'String Trim',
 'Remove leading and trailing whitespace from "  hello  " and print the result.',
 'Elimina los espacios al inicio y al final de "  hello  " e imprime el resultado.',
 'csharp', 1, 'strings',
 'using System;\n\nclass Program {\n    static void Main() {\n        // your code\n    }\n}',
 'hello',
 3,
 'Strings have a Trim() method that removes surrounding whitespace.', 'Las cadenas tienen un método Trim() que elimina los espacios alrededor.',
 'Trim() returns a new string without modifying the original.', 'Trim() devuelve una nueva cadena sin modificar la original.',
 'Console.WriteLine("  hello  ".Trim());', 'Console.WriteLine("  hello  ".Trim());',
 10, 3, now()),

(gen_random_uuid(),
 'Increment Operator', 'Operador de Incremento',
 'Declare an integer set to 5, increment it by 1 using the ++ operator, then print it.',
 'Declara un entero con valor 5, increméntalo en 1 usando el operador ++, luego imprímelo.',
 'csharp', 1, 'basics',
 'using System;\n\nclass Program {\n    static void Main() {\n        // your code\n    }\n}',
 '6',
 3,
 'The ++ operator increments a variable by 1.', 'El operador ++ incrementa una variable en 1.',
 'x++ is the post-increment form; ++x is pre-increment.', 'x++ es la forma post-incremento; ++x es pre-incremento.',
 'int x = 5; x++; Console.WriteLine(x);', 'int x = 5; x++; Console.WriteLine(x);',
 10, 3, now()),

(gen_random_uuid(),
 'Array Length', 'Longitud del Array',
 'Create an integer array {10, 20, 30, 40} and print its length.',
 'Crea un array de enteros {10, 20, 30, 40} e imprime su longitud.',
 'csharp', 1, 'collections',
 'using System;\n\nclass Program {\n    static void Main() {\n        // your code\n    }\n}',
 '4',
 3,
 'Arrays have a Length property.', 'Los arrays tienen una propiedad Length.',
 'Access the length with arr.Length.', 'Accede a la longitud con arr.Length.',
 'int[] arr = {10, 20, 30, 40}; Console.WriteLine(arr.Length);', 'int[] arr = {10, 20, 30, 40}; Console.WriteLine(arr.Length);',
 10, 3, now()),

(gen_random_uuid(),
 'String Replace', 'String Replace',
 'Replace "cat" with "dog" in the string "I have a cat" and print the result.',
 'Reemplaza "cat" con "dog" en la cadena "I have a cat" e imprime el resultado.',
 'csharp', 1, 'strings',
 'using System;\n\nclass Program {\n    static void Main() {\n        // your code\n    }\n}',
 'I have a dog',
 3,
 'Strings have a Replace(old, new) method.', 'Las cadenas tienen un método Replace(viejo, nuevo).',
 'Replace() returns a new string with all occurrences substituted.', 'Replace() devuelve una nueva cadena con todas las ocurrencias sustituidas.',
 'Console.WriteLine("I have a cat".Replace("cat", "dog"));', 'Console.WriteLine("I have a cat".Replace("cat", "dog"));',
 10, 3, now()),

(gen_random_uuid(),
 'Math.Abs', 'Math.Abs',
 'Print the absolute value of -15.',
 'Imprime el valor absoluto de -15.',
 'csharp', 1, 'math',
 'using System;\n\nclass Program {\n    static void Main() {\n        // your code\n    }\n}',
 '15',
 3,
 'Use Math.Abs() to get the absolute value of a number.', 'Usa Math.Abs() para obtener el valor absoluto de un número.',
 'Math.Abs(-15) returns 15.', 'Math.Abs(-15) devuelve 15.',
 'Console.WriteLine(Math.Abs(-15));', 'Console.WriteLine(Math.Abs(-15));',
 10, 3, now()),

(gen_random_uuid(),
 'Switch Statement', 'Sentencia Switch',
 'Declare an integer day = 3. Use a switch statement to print "Wednesday".',
 'Declara un entero day = 3. Usa una sentencia switch para imprimir "Wednesday".',
 'csharp', 1, 'control-flow',
 'using System;\n\nclass Program {\n    static void Main() {\n        // your code\n    }\n}',
 'Wednesday',
 3,
 'A switch statement tests a variable against multiple cases.', 'Una sentencia switch compara una variable contra múltiples casos.',
 'Use case 3: to match the value 3.', 'Usa case 3: para coincidir con el valor 3.',
 'switch(day) { case 3: Console.WriteLine("Wednesday"); break; }', 'switch(day) { case 3: Console.WriteLine("Wednesday"); break; }',
 10, 3, now()),

(gen_random_uuid(),
 'Do-While Loop', 'Bucle Do-While',
 'Use a do-while loop to print "Hello" exactly once.',
 'Usa un bucle do-while para imprimir "Hello" exactamente una vez.',
 'csharp', 1, 'loops',
 'using System;\n\nclass Program {\n    static void Main() {\n        // your code\n    }\n}',
 'Hello',
 3,
 'A do-while loop executes its body at least once before checking the condition.', 'Un bucle do-while ejecuta su cuerpo al menos una vez antes de verificar la condición.',
 'Set the condition to false so the loop runs exactly once.', 'Establece la condición en false para que el bucle se ejecute exactamente una vez.',
 'do { Console.WriteLine("Hello"); } while (false);', 'do { Console.WriteLine("Hello"); } while (false);',
 10, 3, now()),

-- ============================================================
-- DIFFICULTY 2 — 25 exercises (points: 20, penalty: 3)
-- ============================================================

(gen_random_uuid(),
 'Auto Property', 'Propiedad Auto',
 'Create a class Person with auto-properties Name (string) and Age (int). Instantiate it with Name="Bob" and Age=25, then print "Bob is 25".',
 'Crea una clase Person con auto-propiedades Name (string) y Age (int). Instanciala con Name="Bob" y Age=25, luego imprime "Bob is 25".',
 'csharp', 2, 'properties',
 'using System;\n\nclass Program {\n    static void Main() {\n        // your code\n    }\n}',
 'Bob is 25',
 3,
 'Auto-properties use { get; set; } without a backing field.', 'Las auto-propiedades usan { get; set; } sin campo de respaldo.',
 'Use an object initializer: new Person { Name="Bob", Age=25 }.', 'Usa un inicializador de objeto: new Person { Name="Bob", Age=25 }.',
 'Console.WriteLine($"{p.Name} is {p.Age}");', 'Console.WriteLine($"{p.Name} is {p.Age}");',
 20, 3, now()),

(gen_random_uuid(),
 'List Collection', 'Colección List',
 'Create a List<int> containing 3, 6, 9. Print each element on its own line.',
 'Crea una List<int> que contenga 3, 6, 9. Imprime cada elemento en su propia línea.',
 'csharp', 2, 'collections',
 'using System;\nusing System.Collections.Generic;\n\nclass Program {\n    static void Main() {\n        // your code\n    }\n}',
 '3\n6\n9',
 3,
 'Use List<T> from System.Collections.Generic.', 'Usa List<T> de System.Collections.Generic.',
 'Initialize with Add() or a collection initializer { 3, 6, 9 }.', 'Inicializa con Add() o un inicializador de colección { 3, 6, 9 }.',
 'foreach (int n in list) Console.WriteLine(n);', 'foreach (int n in list) Console.WriteLine(n);',
 20, 3, now()),

(gen_random_uuid(),
 'Dictionary Lookup', 'Búsqueda en Diccionario',
 'Create a Dictionary<string, int> mapping "apple" to 1, "banana" to 2. Print the value for "banana".',
 'Crea un Dictionary<string, int> que mapee "apple" a 1, "banana" a 2. Imprime el valor para "banana".',
 'csharp', 2, 'collections',
 'using System;\nusing System.Collections.Generic;\n\nclass Program {\n    static void Main() {\n        // your code\n    }\n}',
 '2',
 3,
 'Use Dictionary<TKey, TValue> from System.Collections.Generic.', 'Usa Dictionary<TKey, TValue> de System.Collections.Generic.',
 'Access a value by key: dict["banana"].', 'Accede a un valor por clave: dict["banana"].',
 'Console.WriteLine(dict["banana"]);', 'Console.WriteLine(dict["banana"]);',
 20, 3, now()),

(gen_random_uuid(),
 'Static Method', 'Método Estático',
 'Write a static method Square(int n) that returns n squared. Call it with 7 and print the result.',
 'Escribe un método estático Square(int n) que devuelva n al cuadrado. Llámalo con 7 e imprime el resultado.',
 'csharp', 2, 'methods',
 'using System;\n\nclass Program {\n    static void Main() {\n        // your code\n    }\n}',
 '49',
 3,
 'A static method belongs to the class, not an instance.', 'Un método estático pertenece a la clase, no a una instancia.',
 'Return n * n from the method.', 'Devuelve n * n desde el método.',
 'static int Square(int n) { return n * n; }', 'static int Square(int n) { return n * n; }',
 20, 3, now()),

(gen_random_uuid(),
 'StringBuilder Append', 'StringBuilder Append',
 'Use StringBuilder to build the string "A-B-C" by appending each character with a separator, then print it.',
 'Usa StringBuilder para construir la cadena "A-B-C" agregando cada carácter con un separador, luego imprímela.',
 'csharp', 2, 'strings',
 'using System;\nusing System.Text;\n\nclass Program {\n    static void Main() {\n        // your code\n    }\n}',
 'A-B-C',
 3,
 'StringBuilder is in the System.Text namespace.', 'StringBuilder está en el espacio de nombres System.Text.',
 'Use Append() to add text and ToString() to get the final string.', 'Usa Append() para agregar texto y ToString() para obtener la cadena final.',
 'sb.Append("A"); sb.Append("-"); sb.Append("B"); sb.Append("-"); sb.Append("C");', 'sb.Append("A"); sb.Append("-"); sb.Append("B"); sb.Append("-"); sb.Append("C");',
 20, 3, now()),

(gen_random_uuid(),
 'Nullable Type', 'Tipo Nullable',
 'Declare a nullable integer (int?) set to null. Print "No value" if it is null, otherwise print the value.',
 'Declara un entero nullable (int?) establecido en null. Imprime "No value" si es null, de lo contrario imprime el valor.',
 'csharp', 2, 'nullable-types',
 'using System;\n\nclass Program {\n    static void Main() {\n        // your code\n    }\n}',
 'No value',
 3,
 'Append ? to a value type to make it nullable: int?.', 'Agrega ? a un tipo de valor para hacerlo nullable: int?.',
 'Check for null with == null or the HasValue property.', 'Comprueba si es null con == null o la propiedad HasValue.',
 'int? n = null; Console.WriteLine(n == null ? "No value" : n.ToString());', 'int? n = null; Console.WriteLine(n == null ? "No value" : n.ToString());',
 20, 3, now()),

(gen_random_uuid(),
 'Null Coalescing Operator', 'Operador de Fusión de Nulos',
 'Use the ?? operator to print the value of a nullable string that is null, defaulting to "default".',
 'Usa el operador ?? para imprimir el valor de una cadena nullable que es null, con valor predeterminado "default".',
 'csharp', 2, 'nullable-types',
 'using System;\n\nclass Program {\n    static void Main() {\n        // your code\n    }\n}',
 'default',
 3,
 'The ?? operator returns the left side if not null, otherwise the right side.', 'El operador ?? devuelve el lado izquierdo si no es null, de lo contrario el lado derecho.',
 'string? s = null; s ?? "default" returns "default".', 'string? s = null; s ?? "default" devuelve "default".',
 'string? s = null; Console.WriteLine(s ?? "default");', 'string? s = null; Console.WriteLine(s ?? "default");',
 20, 3, now()),

(gen_random_uuid(),
 'Extension Method', 'Método de Extensión',
 'Write an extension method on string called WordCount() that returns the number of words. Test with "hello world foo" and print the count.',
 'Escribe un método de extensión en string llamado WordCount() que devuelva el número de palabras. Pruébalo con "hello world foo" e imprime el conteo.',
 'csharp', 2, 'extension-methods',
 'using System;\n\nstatic class StringExtensions {\n    // your extension method\n}\n\nclass Program {\n    static void Main() {\n        // your code\n    }\n}',
 '3',
 3,
 'Extension methods are static methods in a static class with the first parameter preceded by this.', 'Los métodos de extensión son métodos estáticos en una clase estática con el primer parámetro precedido de this.',
 'Use Split('' '') to split by spaces and return the Length.', 'Usa Split('' '') para dividir por espacios y devuelve la Length.',
 'public static int WordCount(this string s) { return s.Split('' '').Length; }', 'public static int WordCount(this string s) { return s.Split('' '').Length; }',
 20, 3, now()),

(gen_random_uuid(),
 'Generic Method', 'Método Genérico',
 'Write a generic method Print<T>(T value) that prints any value. Call it with an int 42 and a string "hi".',
 'Escribe un método genérico Print<T>(T value) que imprima cualquier valor. Llámalo con el int 42 y la cadena "hi".',
 'csharp', 2, 'generics',
 'using System;\n\nclass Program {\n    static void Main() {\n        // your code\n    }\n}',
 '42\nhi',
 3,
 'Generic methods use a type parameter in angle brackets: Print<T>.', 'Los métodos genéricos usan un parámetro de tipo entre corchetes angulares: Print<T>.',
 'Inside the method, use Console.WriteLine(value).', 'Dentro del método, usa Console.WriteLine(value).',
 'static void Print<T>(T value) { Console.WriteLine(value); }', 'static void Print<T>(T value) { Console.WriteLine(value); }',
 20, 3, now()),

(gen_random_uuid(),
 'Simple Delegate', 'Delegado Simple',
 'Declare a delegate type MathOp that takes two ints and returns int. Assign it an addition lambda and print the result of calling it with 3 and 4.',
 'Declara un tipo delegado MathOp que tome dos ints y devuelva int. Asígnale una lambda de suma e imprime el resultado de llamarla con 3 y 4.',
 'csharp', 2, 'delegates',
 'using System;\n\nclass Program {\n    delegate int MathOp(int a, int b);\n    static void Main() {\n        // your code\n    }\n}',
 '7',
 3,
 'A delegate is a type-safe function pointer.', 'Un delegado es un puntero de función con seguridad de tipo.',
 'Assign a lambda: MathOp op = (a, b) => a + b;', 'Asigna una lambda: MathOp op = (a, b) => a + b;',
 'Console.WriteLine(op(3, 4));', 'Console.WriteLine(op(3, 4));',
 20, 3, now()),

(gen_random_uuid(),
 'Func Delegate', 'Delegado Func',
 'Use the built-in Func<int, int, int> delegate to multiply two numbers. Print the result of multiplying 6 and 7.',
 'Usa el delegado integrado Func<int, int, int> para multiplicar dos números. Imprime el resultado de multiplicar 6 y 7.',
 'csharp', 2, 'delegates',
 'using System;\n\nclass Program {\n    static void Main() {\n        // your code\n    }\n}',
 '42',
 3,
 'Func<T1, T2, TResult> is a built-in delegate for functions with return values.', 'Func<T1, T2, TResult> es un delegado integrado para funciones con valores de retorno.',
 'The last type parameter is the return type.', 'El último parámetro de tipo es el tipo de retorno.',
 'Func<int, int, int> mul = (a, b) => a * b; Console.WriteLine(mul(6, 7));', 'Func<int, int, int> mul = (a, b) => a * b; Console.WriteLine(mul(6, 7));',
 20, 3, now()),

(gen_random_uuid(),
 'Action Delegate', 'Delegado Action',
 'Use an Action<string> delegate to print "Hello from Action".',
 'Usa un delegado Action<string> para imprimir "Hello from Action".',
 'csharp', 2, 'delegates',
 'using System;\n\nclass Program {\n    static void Main() {\n        // your code\n    }\n}',
 'Hello from Action',
 3,
 'Action<T> is a built-in delegate for void methods.', 'Action<T> es un delegado integrado para métodos void.',
 'Assign a lambda: Action<string> print = msg => Console.WriteLine(msg);', 'Asigna una lambda: Action<string> print = msg => Console.WriteLine(msg);',
 'Action<string> print = msg => Console.WriteLine(msg); print("Hello from Action");', 'Action<string> print = msg => Console.WriteLine(msg); print("Hello from Action");',
 20, 3, now()),

(gen_random_uuid(),
 'Interface Implementation', 'Implementación de Interfaz',
 'Define an interface IGreet with a method Greet() returning string. Implement it in a class English that returns "Hello". Print the result.',
 'Define una interfaz IGreet con un método Greet() que devuelva string. Impleméntala en una clase English que devuelva "Hello". Imprime el resultado.',
 'csharp', 2, 'interfaces',
 'using System;\n\nclass Program {\n    static void Main() {\n        // your code\n    }\n}',
 'Hello',
 3,
 'An interface declares method signatures without implementations.', 'Una interfaz declara firmas de método sin implementaciones.',
 'The implementing class must provide a body for every interface method.', 'La clase implementadora debe proveer un cuerpo para cada método de la interfaz.',
 'IGreet g = new English(); Console.WriteLine(g.Greet());', 'IGreet g = new English(); Console.WriteLine(g.Greet());',
 20, 3, now()),

(gen_random_uuid(),
 'Abstract Class', 'Clase Abstracta',
 'Create an abstract class Shape with an abstract method Area() returning double. Subclass Circle with radius 5 and override Area() returning Math.PI * 25. Print the area rounded to 2 decimal places.',
 'Crea una clase abstracta Shape con un método abstracto Area() que devuelva double. Subclasifica Circle con radio 5 y sobreescribe Area() devolviendo Math.PI * 25. Imprime el área redondeada a 2 decimales.',
 'csharp', 2, 'abstract-classes',
 'using System;\n\nclass Program {\n    static void Main() {\n        // your code\n    }\n}',
 '78.54',
 3,
 'Use the abstract keyword on both the class and the method.', 'Usa la palabra clave abstract tanto en la clase como en el método.',
 'Override the abstract method in the subclass with the override keyword.', 'Sobreescribe el método abstracto en la subclase con la palabra clave override.',
 'Console.WriteLine(Math.Round(new Circle().Area(), 2));', 'Console.WriteLine(Math.Round(new Circle().Area(), 2));',
 20, 3, now()),

(gen_random_uuid(),
 'Record Type', 'Tipo Record',
 'Define a record Point(int X, int Y). Create an instance with X=3, Y=4 and print it.',
 'Define un record Point(int X, int Y). Crea una instancia con X=3, Y=4 e imprímela.',
 'csharp', 2, 'records',
 'using System;\n\nclass Program {\n    static void Main() {\n        // your code\n    }\n}',
 'Point { X = 3, Y = 4 }',
 3,
 'Records are reference types with value-based equality introduced in C# 9.', 'Los records son tipos de referencia con igualdad basada en valor introducidos en C# 9.',
 'Use positional syntax: record Point(int X, int Y);', 'Usa la sintaxis posicional: record Point(int X, int Y);',
 'var p = new Point(3, 4); Console.WriteLine(p);', 'var p = new Point(3, 4); Console.WriteLine(p);',
 20, 3, now()),

(gen_random_uuid(),
 'String Split', 'String Split',
 'Split "one,two,three" by comma and print each part on its own line.',
 'Divide "one,two,three" por coma e imprime cada parte en su propia línea.',
 'csharp', 2, 'strings',
 'using System;\n\nclass Program {\n    static void Main() {\n        // your code\n    }\n}',
 'one\ntwo\nthree',
 3,
 'Use the Split() method on a string, passing the delimiter character.', 'Usa el método Split() en una cadena, pasando el carácter delimitador.',
 'Split('','') splits by comma.', 'Split('','') divide por coma.',
 'foreach (var p in "one,two,three".Split('','')) Console.WriteLine(p);', 'foreach (var p in "one,two,three".Split('','')) Console.WriteLine(p);',
 20, 3, now()),

(gen_random_uuid(),
 'List Sort', 'Ordenar List',
 'Create a List<int> with values {5, 2, 8, 1, 9}. Sort it and print each element.',
 'Crea una List<int> con valores {5, 2, 8, 1, 9}. Ordénala e imprime cada elemento.',
 'csharp', 2, 'collections',
 'using System;\nusing System.Collections.Generic;\n\nclass Program {\n    static void Main() {\n        // your code\n    }\n}',
 '1\n2\n5\n8\n9',
 3,
 'List<T> has a Sort() method that sorts in place.', 'List<T> tiene un método Sort() que ordena en su lugar.',
 'Call list.Sort() before iterating.', 'Llama a list.Sort() antes de iterar.',
 'list.Sort(); foreach (int n in list) Console.WriteLine(n);', 'list.Sort(); foreach (int n in list) Console.WriteLine(n);',
 20, 3, now()),

(gen_random_uuid(),
 'Exception Handling', 'Manejo de Excepciones',
 'Attempt to parse "abc" as an integer using int.Parse inside a try-catch. Print "Invalid input" if a FormatException is caught.',
 'Intenta parsear "abc" como entero usando int.Parse dentro de un try-catch. Imprime "Invalid input" si se captura una FormatException.',
 'csharp', 2, 'exceptions',
 'using System;\n\nclass Program {\n    static void Main() {\n        // your code\n    }\n}',
 'Invalid input',
 3,
 'Wrap risky code in a try block and handle errors in catch.', 'Envuelve el código riesgoso en un bloque try y maneja los errores en catch.',
 'Catch a specific exception type: catch (FormatException).', 'Captura un tipo de excepción específico: catch (FormatException).',
 'try { int.Parse("abc"); } catch (FormatException) { Console.WriteLine("Invalid input"); }', 'try { int.Parse("abc"); } catch (FormatException) { Console.WriteLine("Invalid input"); }',
 20, 3, now()),

(gen_random_uuid(),
 'Enum Declaration', 'Declaración de Enum',
 'Declare an enum Day with values Mon=1 through Sun=7. Print the name and value of Day.Wed.',
 'Declara un enum Day con valores Mon=1 hasta Sun=7. Imprime el nombre y valor de Day.Wed.',
 'csharp', 2, 'basics',
 'using System;\n\nclass Program {\n    static void Main() {\n        // your code\n    }\n}',
 'Wed 3',
 3,
 'Enums are value types that represent named integer constants.', 'Los enums son tipos de valor que representan constantes enteras nombradas.',
 'Cast to int to get the numeric value: (int)Day.Wed.', 'Convierte a int para obtener el valor numérico: (int)Day.Wed.',
 'Console.WriteLine($"{Day.Wed} {(int)Day.Wed}");', 'Console.WriteLine($"{Day.Wed} {(int)Day.Wed}");',
 20, 3, now()),

(gen_random_uuid(),
 'Stack Collection', 'Colección Stack',
 'Push 1, 2, 3 onto a Stack<int> and pop them one by one, printing each popped value.',
 'Apila 1, 2, 3 en un Stack<int> y desapílalos uno por uno, imprimiendo cada valor desapilado.',
 'csharp', 2, 'collections',
 'using System;\nusing System.Collections.Generic;\n\nclass Program {\n    static void Main() {\n        // your code\n    }\n}',
 '3\n2\n1',
 3,
 'Stack<T> follows LIFO — last in, first out.', 'Stack<T> sigue LIFO — último en entrar, primero en salir.',
 'Use Push() to add and Pop() to remove the top element.', 'Usa Push() para agregar y Pop() para eliminar el elemento superior.',
 'while (stack.Count > 0) Console.WriteLine(stack.Pop());', 'while (stack.Count > 0) Console.WriteLine(stack.Pop());',
 20, 3, now()),

(gen_random_uuid(),
 'Queue Collection', 'Colección Queue',
 'Enqueue "first", "second", "third" into a Queue<string> and dequeue them one by one, printing each.',
 'Encola "first", "second", "third" en una Queue<string> y desencólalos uno por uno, imprimiendo cada uno.',
 'csharp', 2, 'collections',
 'using System;\nusing System.Collections.Generic;\n\nclass Program {\n    static void Main() {\n        // your code\n    }\n}',
 'first\nsecond\nthird',
 3,
 'Queue<T> follows FIFO — first in, first out.', 'Queue<T> sigue FIFO — primero en entrar, primero en salir.',
 'Use Enqueue() to add and Dequeue() to remove the front element.', 'Usa Enqueue() para agregar y Dequeue() para eliminar el elemento frontal.',
 'while (queue.Count > 0) Console.WriteLine(queue.Dequeue());', 'while (queue.Count > 0) Console.WriteLine(queue.Dequeue());',
 20, 3, now()),

(gen_random_uuid(),
 'String Format', 'String Format',
 'Use string.Format to produce "Value: 42" and print it.',
 'Usa string.Format para producir "Value: 42" e imprímelo.',
 'csharp', 2, 'strings',
 'using System;\n\nclass Program {\n    static void Main() {\n        // your code\n    }\n}',
 'Value: 42',
 3,
 'string.Format uses {0}, {1} as placeholders for arguments.', 'string.Format usa {0}, {1} como marcadores para los argumentos.',
 'The first argument after the format string maps to {0}.', 'El primer argumento después de la cadena de formato se mapea a {0}.',
 'Console.WriteLine(string.Format("Value: {0}", 42));', 'Console.WriteLine(string.Format("Value: {0}", 42));',
 20, 3, now()),

(gen_random_uuid(),
 'Readonly Property', 'Propiedad Readonly',
 'Create a class Circle with a readonly property Radius set in the constructor. Instantiate with radius 7 and print it.',
 'Crea una clase Circle con una propiedad readonly Radius establecida en el constructor. Instanciala con radio 7 e imprímela.',
 'csharp', 2, 'properties',
 'using System;\n\nclass Program {\n    static void Main() {\n        // your code\n    }\n}',
 '7',
 3,
 'A property with only a getter cannot be set after construction.', 'Una propiedad con solo un getter no se puede establecer después de la construcción.',
 'Use { get; } and set the backing field in the constructor.', 'Usa { get; } y establece el campo de respaldo en el constructor.',
 'Console.WriteLine(new Circle(7).Radius);', 'Console.WriteLine(new Circle(7).Radius);',
 20, 3, now()),

(gen_random_uuid(),
 'String StartsWith', 'String StartsWith',
 'Check whether "CSharp is great" starts with "CSharp" and print the boolean result.',
 'Comprueba si "CSharp is great" comienza con "CSharp" e imprime el resultado booleano.',
 'csharp', 2, 'strings',
 'using System;\n\nclass Program {\n    static void Main() {\n        // your code\n    }\n}',
 'True',
 3,
 'Strings have a StartsWith() method that returns bool.', 'Las cadenas tienen un método StartsWith() que devuelve bool.',
 'Pass the prefix string as the argument.', 'Pasa la cadena de prefijo como argumento.',
 'Console.WriteLine("CSharp is great".StartsWith("CSharp"));', 'Console.WriteLine("CSharp is great".StartsWith("CSharp"));',
 20, 3, now()),

(gen_random_uuid(),
 'HashSet Uniqueness', 'Unicidad con HashSet',
 'Add the values 1, 2, 2, 3, 3, 3 to a HashSet<int> and print the count of unique elements.',
 'Agrega los valores 1, 2, 2, 3, 3, 3 a un HashSet<int> e imprime el conteo de elementos únicos.',
 'csharp', 2, 'collections',
 'using System;\nusing System.Collections.Generic;\n\nclass Program {\n    static void Main() {\n        // your code\n    }\n}',
 '3',
 3,
 'HashSet<T> stores only unique elements; duplicates are silently ignored.', 'HashSet<T> almacena solo elementos únicos; los duplicados se ignoran silenciosamente.',
 'Use .Add() for each value or a collection initializer.', 'Usa .Add() para cada valor o un inicializador de colección.',
 'var set = new HashSet<int>{1,2,2,3,3,3}; Console.WriteLine(set.Count);', 'var set = new HashSet<int>{1,2,2,3,3,3}; Console.WriteLine(set.Count);',
 20, 3, now()),

-- ============================================================
-- DIFFICULTY 3 — 25 exercises (points: 30, penalty: 5)
-- ============================================================

(gen_random_uuid(),
 'LINQ Where Filter', 'Filtro LINQ Where',
 'Use LINQ to filter a list of integers {1,2,3,4,5,6,7,8} to only even numbers and print each on its own line.',
 'Usa LINQ para filtrar una lista de enteros {1,2,3,4,5,6,7,8} a solo los números pares e imprime cada uno en su propia línea.',
 'csharp', 3, 'linq',
 'using System;\nusing System.Collections.Generic;\nusing System.Linq;\n\nclass Program {\n    static void Main() {\n        // your code\n    }\n}',
 '2\n4\n6\n8',
 3,
 'LINQ is in System.Linq namespace.', 'LINQ está en el espacio de nombres System.Linq.',
 'Use .Where(n => n % 2 == 0) to filter even numbers.', 'Usa .Where(n => n % 2 == 0) para filtrar números pares.',
 'foreach (var n in list.Where(n => n % 2 == 0)) Console.WriteLine(n);', 'foreach (var n in list.Where(n => n % 2 == 0)) Console.WriteLine(n);',
 30, 5, now()),

(gen_random_uuid(),
 'LINQ Select Transform', 'Transformación LINQ Select',
 'Use LINQ Select to square each number in {1,2,3,4,5} and print the results.',
 'Usa LINQ Select para elevar al cuadrado cada número en {1,2,3,4,5} e imprime los resultados.',
 'csharp', 3, 'linq',
 'using System;\nusing System.Collections.Generic;\nusing System.Linq;\n\nclass Program {\n    static void Main() {\n        // your code\n    }\n}',
 '1\n4\n9\n16\n25',
 3,
 'LINQ Select projects each element to a new form.', 'LINQ Select proyecta cada elemento a una nueva forma.',
 'Use .Select(n => n * n) to square each element.', 'Usa .Select(n => n * n) para elevar al cuadrado cada elemento.',
 'foreach (var n in nums.Select(n => n * n)) Console.WriteLine(n);', 'foreach (var n in nums.Select(n => n * n)) Console.WriteLine(n);',
 30, 5, now()),

(gen_random_uuid(),
 'LINQ OrderByDescending', 'LINQ OrderByDescending',
 'Sort the list {3, 1, 4, 1, 5, 9} in descending order using LINQ and print the distinct sorted values.',
 'Ordena la lista {3, 1, 4, 1, 5, 9} en orden descendente usando LINQ e imprime los valores distintos ordenados.',
 'csharp', 3, 'linq',
 'using System;\nusing System.Collections.Generic;\nusing System.Linq;\n\nclass Program {\n    static void Main() {\n        // your code\n    }\n}',
 '9\n5\n4\n3\n1',
 3,
 'Use .Distinct() to remove duplicates and .OrderByDescending() to sort.', 'Usa .Distinct() para eliminar duplicados y .OrderByDescending() para ordenar.',
 'Chain LINQ methods: .Distinct().OrderByDescending(n => n).', 'Encadena métodos LINQ: .Distinct().OrderByDescending(n => n).',
 'foreach (var n in list.Distinct().OrderByDescending(n => n)) Console.WriteLine(n);', 'foreach (var n in list.Distinct().OrderByDescending(n => n)) Console.WriteLine(n);',
 30, 5, now()),

(gen_random_uuid(),
 'LINQ Sum and Count', 'LINQ Sum y Count',
 'Given the list {10, 20, 30, 40}, use LINQ to print the sum and the count on separate lines.',
 'Dada la lista {10, 20, 30, 40}, usa LINQ para imprimir la suma y el conteo en líneas separadas.',
 'csharp', 3, 'linq',
 'using System;\nusing System.Collections.Generic;\nusing System.Linq;\n\nclass Program {\n    static void Main() {\n        // your code\n    }\n}',
 '100\n4',
 3,
 'LINQ aggregate methods: Sum(), Count(), Average(), Min(), Max().', 'Métodos de agregación LINQ: Sum(), Count(), Average(), Min(), Max().',
 'Call .Sum() and .Count() on the collection.', 'Llama a .Sum() y .Count() en la colección.',
 'Console.WriteLine(list.Sum()); Console.WriteLine(list.Count());', 'Console.WriteLine(list.Sum()); Console.WriteLine(list.Count());',
 30, 5, now()),

(gen_random_uuid(),
 'LINQ FirstOrDefault', 'LINQ FirstOrDefault',
 'Use LINQ FirstOrDefault to find the first number greater than 10 in {5, 3, 15, 7}. Print the result.',
 'Usa LINQ FirstOrDefault para encontrar el primer número mayor que 10 en {5, 3, 15, 7}. Imprime el resultado.',
 'csharp', 3, 'linq',
 'using System;\nusing System.Collections.Generic;\nusing System.Linq;\n\nclass Program {\n    static void Main() {\n        // your code\n    }\n}',
 '15',
 3,
 'FirstOrDefault returns the first matching element or the default value if none found.', 'FirstOrDefault devuelve el primer elemento que coincide o el valor predeterminado si no se encuentra ninguno.',
 'Pass a predicate lambda: .FirstOrDefault(n => n > 10).', 'Pasa una lambda predicado: .FirstOrDefault(n => n > 10).',
 'Console.WriteLine(list.FirstOrDefault(n => n > 10));', 'Console.WriteLine(list.FirstOrDefault(n => n > 10));',
 30, 5, now()),

(gen_random_uuid(),
 'Async Method', 'Método Async',
 'Write an async method FetchMessageAsync() that returns Task<string> with a simulated delay of 0ms and value "Done". Await it in Main and print the result.',
 'Escribe un método async FetchMessageAsync() que devuelva Task<string> con un retraso simulado de 0ms y valor "Done". Espéralo en Main e imprime el resultado.',
 'csharp', 3, 'async-await',
 'using System;\nusing System.Threading.Tasks;\n\nclass Program {\n    static async Task Main() {\n        // your code\n    }\n}',
 'Done',
 3,
 'Mark the method with async and return Task<T>.', 'Marca el método con async y devuelve Task<T>.',
 'Use await Task.FromResult("Done") or Task.Delay(0) with a return.', 'Usa await Task.FromResult("Done") o Task.Delay(0) con un retorno.',
 'static async Task<string> FetchMessageAsync() { await Task.Delay(0); return "Done"; }', 'static async Task<string> FetchMessageAsync() { await Task.Delay(0); return "Done"; }',
 30, 5, now()),

(gen_random_uuid(),
 'Async Task.WhenAll', 'Async Task.WhenAll',
 'Create two tasks that each return an integer (3 and 7). Use Task.WhenAll to await both and print their sum.',
 'Crea dos tareas que cada una devuelva un entero (3 y 7). Usa Task.WhenAll para esperar ambas e imprime su suma.',
 'csharp', 3, 'async-await',
 'using System;\nusing System.Threading.Tasks;\n\nclass Program {\n    static async Task Main() {\n        // your code\n    }\n}',
 '10',
 3,
 'Task.WhenAll runs tasks concurrently and returns when all complete.', 'Task.WhenAll ejecuta tareas concurrentemente y retorna cuando todas terminan.',
 'Use Task.FromResult(n) to create an already-completed task.', 'Usa Task.FromResult(n) para crear una tarea ya completada.',
 'var results = await Task.WhenAll(Task.FromResult(3), Task.FromResult(7)); Console.WriteLine(results[0] + results[1]);', 'var results = await Task.WhenAll(Task.FromResult(3), Task.FromResult(7)); Console.WriteLine(results[0] + results[1]);',
 30, 5, now()),

(gen_random_uuid(),
 'Pattern Matching is', 'Pattern Matching is',
 'Declare an object holding the integer 42. Use the is pattern to check if it is an int and print the value.',
 'Declara un objeto que contenga el entero 42. Usa el patrón is para verificar si es un int e imprime el valor.',
 'csharp', 3, 'pattern-matching',
 'using System;\n\nclass Program {\n    static void Main() {\n        // your code\n    }\n}',
 '42',
 3,
 'The is pattern matches type and extracts the value: obj is int n.', 'El patrón is hace coincidir el tipo y extrae el valor: obj is int n.',
 'If the pattern matches, the variable n holds the cast value.', 'Si el patrón coincide, la variable n contiene el valor convertido.',
 'object o = 42; if (o is int n) Console.WriteLine(n);', 'object o = 42; if (o is int n) Console.WriteLine(n);',
 30, 5, now()),

(gen_random_uuid(),
 'Switch Expression', 'Expresión Switch',
 'Use a switch expression to map the integer 2 to "Two", 1 to "One", and any other to "Other". Print the result.',
 'Usa una expresión switch para mapear el entero 2 a "Two", 1 a "One", y cualquier otro a "Other". Imprime el resultado.',
 'csharp', 3, 'pattern-matching',
 'using System;\n\nclass Program {\n    static void Main() {\n        // your code\n    }\n}',
 'Two',
 3,
 'Switch expressions use => instead of case/break.', 'Las expresiones switch usan => en lugar de case/break.',
 'Use _ as the discard/default arm.', 'Usa _ como el brazo descarte/predeterminado.',
 'var result = 2 switch { 1 => "One", 2 => "Two", _ => "Other" }; Console.WriteLine(result);', 'var result = 2 switch { 1 => "One", 2 => "Two", _ => "Other" }; Console.WriteLine(result);',
 30, 5, now()),

(gen_random_uuid(),
 'Property Pattern', 'Patrón de Propiedad',
 'Given a record Person(string Name, int Age), use a property pattern to print "Adult" if age >= 18 for a person aged 25.',
 'Dado un record Person(string Name, int Age), usa un patrón de propiedad para imprimir "Adult" si age >= 18 para una persona de 25 años.',
 'csharp', 3, 'pattern-matching',
 'using System;\n\nrecord Person(string Name, int Age);\n\nclass Program {\n    static void Main() {\n        // your code\n    }\n}',
 'Adult',
 3,
 'Property patterns match on the values of an object''s properties.', 'Los patrones de propiedad coinciden con los valores de las propiedades de un objeto.',
 'Use is { Age: >= 18 } to match age >= 18.', 'Usa is { Age: >= 18 } para coincidir con age >= 18.',
 'var p = new Person("Alice", 25); if (p is { Age: >= 18 }) Console.WriteLine("Adult");', 'var p = new Person("Alice", 25); if (p is { Age: >= 18 }) Console.WriteLine("Adult");',
 30, 5, now()),

(gen_random_uuid(),
 'Generic Stack', 'Stack Genérico',
 'Implement a generic class Stack<T> with Push and Pop methods. Push 10 and 20, then pop and print twice.',
 'Implementa una clase genérica Stack<T> con métodos Push y Pop. Apila 10 y 20, luego desapila e imprime dos veces.',
 'csharp', 3, 'generics',
 'using System;\nusing System.Collections.Generic;\n\nclass Program {\n    static void Main() {\n        // your code\n    }\n}',
 '20\n10',
 3,
 'Use a List<T> as the internal storage for the stack.', 'Usa una List<T> como almacenamiento interno para la pila.',
 'Push adds to the end; Pop removes from the end (LIFO).', 'Push agrega al final; Pop elimina desde el final (LIFO).',
 'Pop returns and removes the last element: int last = items[items.Count-1]; items.RemoveAt(items.Count-1);', 'Pop retorna y elimina el último elemento: int last = items[items.Count-1]; items.RemoveAt(items.Count-1);',
 30, 5, now()),

(gen_random_uuid(),
 'Generic Constraint', 'Restricción Genérica',
 'Write a generic method Max<T>(T a, T b) constrained to IComparable<T> that returns the larger value. Test with 5 and 9.',
 'Escribe un método genérico Max<T>(T a, T b) restringido a IComparable<T> que devuelva el valor mayor. Pruébalo con 5 y 9.',
 'csharp', 3, 'generics',
 'using System;\n\nclass Program {\n    static void Main() {\n        // your code\n    }\n}',
 '9',
 3,
 'Use where T : IComparable<T> to constrain the type parameter.', 'Usa where T : IComparable<T> para restringir el parámetro de tipo.',
 'Use a.CompareTo(b) > 0 to compare values.', 'Usa a.CompareTo(b) > 0 para comparar valores.',
 'static T Max<T>(T a, T b) where T : IComparable<T> => a.CompareTo(b) > 0 ? a : b;', 'static T Max<T>(T a, T b) where T : IComparable<T> => a.CompareTo(b) > 0 ? a : b;',
 30, 5, now()),

(gen_random_uuid(),
 'Event and Handler', 'Evento y Manejador',
 'Define a class Button with an event Clicked (EventHandler). Subscribe a handler that prints "Button clicked!". Raise the event.',
 'Define una clase Button con un evento Clicked (EventHandler). Suscribe un manejador que imprima "Button clicked!". Lanza el evento.',
 'csharp', 3, 'events',
 'using System;\n\nclass Program {\n    static void Main() {\n        // your code\n    }\n}',
 'Button clicked!',
 3,
 'Declare an event with: public event EventHandler Clicked;', 'Declara un evento con: public event EventHandler Clicked;',
 'Subscribe with +=: btn.Clicked += (s, e) => Console.WriteLine("Button clicked!");', 'Suscríbete con +=: btn.Clicked += (s, e) => Console.WriteLine("Button clicked!");',
 'Invoke the event null-conditionally: Clicked?.Invoke(this, EventArgs.Empty);', 'Invoca el evento null-condicionalmente: Clicked?.Invoke(this, EventArgs.Empty);',
 30, 5, now()),

(gen_random_uuid(),
 'Custom EventArgs', 'EventArgs Personalizado',
 'Create a MessageEventArgs class with a Text property. Define an event OnMessage that carries MessageEventArgs. Raise it with Text="Hello" and print the text in the handler.',
 'Crea una clase MessageEventArgs con una propiedad Text. Define un evento OnMessage que lleve MessageEventArgs. Lánzalo con Text="Hello" e imprime el texto en el manejador.',
 'csharp', 3, 'events',
 'using System;\n\nclass Program {\n    static void Main() {\n        // your code\n    }\n}',
 'Hello',
 3,
 'Inherit from EventArgs to create custom event data.', 'Hereda de EventArgs para crear datos de evento personalizados.',
 'Use EventHandler<MessageEventArgs> for the event type.', 'Usa EventHandler<MessageEventArgs> para el tipo de evento.',
 'OnMessage?.Invoke(this, new MessageEventArgs { Text = "Hello" });', 'OnMessage?.Invoke(this, new MessageEventArgs { Text = "Hello" });',
 30, 5, now()),

(gen_random_uuid(),
 'LINQ GroupBy', 'LINQ GroupBy',
 'Group the list {"cat","car","dog","door","cab"} by first letter using LINQ. Print each key followed by count.',
 'Agrupa la lista {"cat","car","dog","door","cab"} por primera letra usando LINQ. Imprime cada clave seguida del conteo.',
 'csharp', 3, 'linq',
 'using System;\nusing System.Collections.Generic;\nusing System.Linq;\n\nclass Program {\n    static void Main() {\n        // your code\n    }\n}',
 'c:3\nd:2',
 3,
 'Use .GroupBy(w => w[0]) to group by first character.', 'Usa .GroupBy(w => w[0]) para agrupar por primer carácter.',
 'Each group has a Key and a Count().', 'Cada grupo tiene una Key y un Count().',
 'foreach (var g in words.GroupBy(w => w[0]).OrderBy(g => g.Key)) Console.WriteLine($"{g.Key}:{g.Count()}");', 'foreach (var g in words.GroupBy(w => w[0]).OrderBy(g => g.Key)) Console.WriteLine($"{g.Key}:{g.Count()}");',
 30, 5, now()),

(gen_random_uuid(),
 'LINQ Join', 'LINQ Join',
 'Join a list of product IDs {1,2,3} with a dictionary of names {1:"Apple",2:"Banana",3:"Cherry"} using LINQ and print each name.',
 'Une una lista de IDs de producto {1,2,3} con un diccionario de nombres {1:"Apple",2:"Banana",3:"Cherry"} usando LINQ e imprime cada nombre.',
 'csharp', 3, 'linq',
 'using System;\nusing System.Collections.Generic;\nusing System.Linq;\n\nclass Program {\n    static void Main() {\n        // your code\n    }\n}',
 'Apple\nBanana\nCherry',
 3,
 'Use .Join() or simply .Select() with a dictionary lookup.', 'Usa .Join() o simplemente .Select() con una búsqueda en el diccionario.',
 'ids.Select(id => names[id]) maps each id to its name.', 'ids.Select(id => names[id]) mapea cada id a su nombre.',
 'foreach (var n in ids.Select(id => names[id])) Console.WriteLine(n);', 'foreach (var n in ids.Select(id => names[id])) Console.WriteLine(n);',
 30, 5, now()),

(gen_random_uuid(),
 'StringBuilder Loop', 'StringBuilder en Bucle',
 'Use StringBuilder inside a loop to build "1,2,3,4,5" (comma-separated) and print it.',
 'Usa StringBuilder dentro de un bucle para construir "1,2,3,4,5" (separado por comas) e imprímelo.',
 'csharp', 3, 'strings',
 'using System;\nusing System.Text;\n\nclass Program {\n    static void Main() {\n        // your code\n    }\n}',
 '1,2,3,4,5',
 3,
 'StringBuilder is efficient for repeated string concatenation.', 'StringBuilder es eficiente para concatenación de cadenas repetida.',
 'Append the separator only when it is not the last element.', 'Agrega el separador solo cuando no es el último elemento.',
 'for (int i=1; i<=5; i++) { sb.Append(i); if (i<5) sb.Append(","); }', 'for (int i=1; i<=5; i++) { sb.Append(i); if (i<5) sb.Append(","); }',
 30, 5, now()),

(gen_random_uuid(),
 'Nullable Reference Check', 'Verificación de Referencia Nullable',
 'Write a method Describe(string? s) that returns "null" if s is null, or the string value. Call it with null and "hello" and print both results.',
 'Escribe un método Describe(string? s) que devuelva "null" si s es null, o el valor de la cadena. Llámalo con null y "hello" e imprime ambos resultados.',
 'csharp', 3, 'nullable-types',
 'using System;\n\nclass Program {\n    static void Main() {\n        // your code\n    }\n}',
 'null\nhello',
 3,
 'Use string? to allow null references in nullable reference type contexts.', 'Usa string? para permitir referencias null en contextos de tipos de referencia nullable.',
 'Return s ?? "null" or check s == null explicitly.', 'Devuelve s ?? "null" o verifica s == null explícitamente.',
 'static string Describe(string? s) => s ?? "null";', 'static string Describe(string? s) => s ?? "null";',
 30, 5, now()),

(gen_random_uuid(),
 'Predicate Delegate', 'Delegado Predicate',
 'Use a Predicate<int> to check whether a number is greater than 10. Test with 15 and 5 and print the results.',
 'Usa un Predicate<int> para verificar si un número es mayor que 10. Pruébalo con 15 y 5 e imprime los resultados.',
 'csharp', 3, 'delegates',
 'using System;\n\nclass Program {\n    static void Main() {\n        // your code\n    }\n}',
 'True\nFalse',
 3,
 'Predicate<T> is a delegate that returns bool.', 'Predicate<T> es un delegado que devuelve bool.',
 'Assign a lambda: Predicate<int> isAbove10 = n => n > 10;', 'Asigna una lambda: Predicate<int> isAbove10 = n => n > 10;',
 'Console.WriteLine(isAbove10(15)); Console.WriteLine(isAbove10(5));', 'Console.WriteLine(isAbove10(15)); Console.WriteLine(isAbove10(5));',
 30, 5, now()),

(gen_random_uuid(),
 'MulticastDelegate', 'Delegado Multicast',
 'Declare an Action delegate and assign two methods that print "First" and "Second" respectively. Invoke the combined delegate.',
 'Declara un delegado Action y asigna dos métodos que impriman "First" y "Second" respectivamente. Invoca el delegado combinado.',
 'csharp', 3, 'delegates',
 'using System;\n\nclass Program {\n    static void Main() {\n        // your code\n    }\n}',
 'First\nSecond',
 3,
 'Delegates can be combined with += to create a multicast delegate.', 'Los delegados se pueden combinar con += para crear un delegado multicast.',
 'Invoking a multicast delegate calls all subscribed methods in order.', 'Invocar un delegado multicast llama a todos los métodos suscritos en orden.',
 'Action a = () => Console.WriteLine("First"); a += () => Console.WriteLine("Second"); a();', 'Action a = () => Console.WriteLine("First"); a += () => Console.WriteLine("Second"); a();',
 30, 5, now()),

(gen_random_uuid(),
 'Record With Expression', 'Record With Expression',
 'Define a record Point(int X, int Y). Create a Point(1,2) and use the with expression to create a copy with X=10. Print the new point.',
 'Define un record Point(int X, int Y). Crea un Point(1,2) y usa la expresión with para crear una copia con X=10. Imprime el nuevo punto.',
 'csharp', 3, 'records',
 'using System;\n\nrecord Point(int X, int Y);\n\nclass Program {\n    static void Main() {\n        // your code\n    }\n}',
 'Point { X = 10, Y = 2 }',
 3,
 'Records support non-destructive mutation with the with expression.', 'Los records soportan mutación no destructiva con la expresión with.',
 'var p2 = p1 with { X = 10 }; creates a copy with X changed.', 'var p2 = p1 with { X = 10 }; crea una copia con X cambiado.',
 'var p2 = new Point(1,2) with { X = 10 }; Console.WriteLine(p2);', 'var p2 = new Point(1,2) with { X = 10 }; Console.WriteLine(p2);',
 30, 5, now()),

(gen_random_uuid(),
 'Tuple Deconstruction', 'Deconstrucción de Tupla',
 'Create a method that returns a (string, int) tuple with ("Alice", 30). Deconstruct it and print "Alice: 30".',
 'Crea un método que devuelva una tupla (string, int) con ("Alice", 30). Deconstruyela e imprime "Alice: 30".',
 'csharp', 3, 'basics',
 'using System;\n\nclass Program {\n    static void Main() {\n        // your code\n    }\n}',
 'Alice: 30',
 3,
 'Methods can return multiple values using tuple syntax (T1, T2).', 'Los métodos pueden devolver múltiples valores usando la sintaxis de tupla (T1, T2).',
 'Deconstruct with: var (name, age) = GetPerson();', 'Deconstruye con: var (name, age) = GetPerson();',
 'var (name, age) = GetPerson(); Console.WriteLine($"{name}: {age}");', 'var (name, age) = GetPerson(); Console.WriteLine($"{name}: {age}");',
 30, 5, now()),

(gen_random_uuid(),
 'IEnumerable with Yield', 'IEnumerable con Yield',
 'Write a method GetEven(int max) using yield return that lazily yields even numbers from 2 up to max. Print them for max=8.',
 'Escribe un método GetEven(int max) usando yield return que genere perezosamente números pares desde 2 hasta max. Imprímelos para max=8.',
 'csharp', 3, 'collections',
 'using System;\nusing System.Collections.Generic;\n\nclass Program {\n    static void Main() {\n        // your code\n    }\n}',
 '2\n4\n6\n8',
 3,
 'yield return turns a method into an iterator that produces values lazily.', 'yield return convierte un método en un iterador que produce valores de forma perezosa.',
 'Return IEnumerable<int> and use yield return inside the loop.', 'Devuelve IEnumerable<int> y usa yield return dentro del bucle.',
 'static IEnumerable<int> GetEven(int max) { for (int i=2; i<=max; i+=2) yield return i; }', 'static IEnumerable<int> GetEven(int max) { for (int i=2; i<=max; i+=2) yield return i; }',
 30, 5, now()),

(gen_random_uuid(),
 'LINQ Zip', 'LINQ Zip',
 'Use LINQ Zip to pair {"A","B","C"} with {1,2,3} and print each pair as "A:1", "B:2", "C:3".',
 'Usa LINQ Zip para emparejar {"A","B","C"} con {1,2,3} e imprime cada par como "A:1", "B:2", "C:3".',
 'csharp', 3, 'linq',
 'using System;\nusing System.Collections.Generic;\nusing System.Linq;\n\nclass Program {\n    static void Main() {\n        // your code\n    }\n}',
 'A:1\nB:2\nC:3',
 3,
 'Zip combines two sequences element-by-element using a result selector.', 'Zip combina dos secuencias elemento a elemento usando un selector de resultado.',
 'Use .Zip(second, (a, b) => $"{a}:{b}") to format each pair.', 'Usa .Zip(second, (a, b) => $"{a}:{b}") para formatear cada par.',
 'foreach (var s in letters.Zip(nums, (a,b) => $"{a}:{b}")) Console.WriteLine(s);', 'foreach (var s in letters.Zip(nums, (a,b) => $"{a}:{b}")) Console.WriteLine(s);',
 30, 5, now()),

(gen_random_uuid(),
 'String Verbatim Literal', 'Literal de Cadena Verbatim',
 'Use a verbatim string literal to print a Windows-style path: C:\Users\Alice\Documents',
 'Usa un literal de cadena verbatim para imprimir una ruta estilo Windows: C:\Users\Alice\Documents',
 'csharp', 3, 'strings',
 'using System;\n\nclass Program {\n    static void Main() {\n        // your code\n    }\n}',
 'C:\Users\Alice\Documents',
 3,
 'Prefix the string with @ to create a verbatim literal — backslashes are treated literally.', 'Prefija la cadena con @ para crear un literal verbatim — las barras invertidas se tratan literalmente.',
 '@"C:\Users\Alice\Documents" avoids having to escape each backslash.', '@"C:\Users\Alice\Documents" evita tener que escapar cada barra invertida.',
 'Console.WriteLine(@"C:\Users\Alice\Documents");', 'Console.WriteLine(@"C:\Users\Alice\Documents");',
 30, 5, now()),

-- ============================================================
-- DIFFICULTY 4 — 15 exercises (points: 50, penalty: 10)
-- ============================================================

(gen_random_uuid(),
 'Async Pipeline', 'Pipeline Asíncrono',
 'Chain three async methods: FetchData returning 10, ProcessData(int n) returning n*2, SaveData(int n) printing n. Await them in sequence and print the saved value.',
 'Encadena tres métodos async: FetchData devolviendo 10, ProcessData(int n) devolviendo n*2, SaveData(int n) imprimiendo n. Espéralos en secuencia e imprime el valor guardado.',
 'csharp', 4, 'async-await',
 'using System;\nusing System.Threading.Tasks;\n\nclass Program {\n    static async Task Main() {\n        // your code\n    }\n}',
 '20',
 3,
 'Each async method returns Task<T>; await chains them.', 'Cada método async devuelve Task<T>; await los encadena.',
 'var data = await FetchData(); var processed = await ProcessData(data); await SaveData(processed);', 'var data = await FetchData(); var processed = await ProcessData(data); await SaveData(processed);',
 'static async Task<int> FetchData() => await Task.FromResult(10); static async Task<int> ProcessData(int n) => await Task.FromResult(n*2);', 'static async Task<int> FetchData() => await Task.FromResult(10); static async Task<int> ProcessData(int n) => await Task.FromResult(n*2);',
 50, 10, now()),

(gen_random_uuid(),
 'LINQ Aggregate', 'LINQ Aggregate',
 'Use LINQ Aggregate to compute the product of {1,2,3,4,5} (i.e., 120) and print it.',
 'Usa LINQ Aggregate para calcular el producto de {1,2,3,4,5} (es decir, 120) e imprímelo.',
 'csharp', 4, 'linq',
 'using System;\nusing System.Collections.Generic;\nusing System.Linq;\n\nclass Program {\n    static void Main() {\n        // your code\n    }\n}',
 '120',
 3,
 'Aggregate applies a function cumulatively to a sequence.', 'Aggregate aplica una función acumulativamente a una secuencia.',
 'Aggregate((acc, n) => acc * n) starts with the first element as the seed.', 'Aggregate((acc, n) => acc * n) comienza con el primer elemento como semilla.',
 'Console.WriteLine(new[]{1,2,3,4,5}.Aggregate((acc,n) => acc*n));', 'Console.WriteLine(new[]{1,2,3,4,5}.Aggregate((acc,n) => acc*n));',
 50, 10, now()),

(gen_random_uuid(),
 'Custom Generic Repository', 'Repositorio Genérico Personalizado',
 'Implement a generic Repository<T> class with Add(T item), GetAll() returning IEnumerable<T>. Store ints, add 1 2 3, and print all.',
 'Implementa una clase genérica Repository<T> con Add(T item), GetAll() devolviendo IEnumerable<T>. Almacena ints, agrega 1 2 3 e imprime todos.',
 'csharp', 4, 'generics',
 'using System;\nusing System.Collections.Generic;\n\nclass Program {\n    static void Main() {\n        // your code\n    }\n}',
 '1\n2\n3',
 3,
 'Use a private List<T> as the backing store.', 'Usa una List<T> privada como almacenamiento de respaldo.',
 'GetAll() can return the internal list directly or a copy.', 'GetAll() puede devolver la lista interna directamente o una copia.',
 'class Repository<T> { private List<T> _items = new(); public void Add(T item) => _items.Add(item); public IEnumerable<T> GetAll() => _items; }', 'class Repository<T> { private List<T> _items = new(); public void Add(T item) => _items.Add(item); public IEnumerable<T> GetAll() => _items; }',
 50, 10, now()),

(gen_random_uuid(),
 'Covariant Interface', 'Interfaz Covariante',
 'Define a covariant interface IProducer<out T> with method T Produce(). Implement it for string returning "hello". Assign to IProducer<object> and call Produce(), printing the result.',
 'Define una interfaz covariante IProducer<out T> con método T Produce(). Impleméntala para string devolviendo "hello". Asígna a IProducer<object> y llama a Produce(), imprimiendo el resultado.',
 'csharp', 4, 'generics',
 'using System;\n\nclass Program {\n    static void Main() {\n        // your code\n    }\n}',
 'hello',
 3,
 'The out keyword on a type parameter makes the interface covariant.', 'La palabra clave out en un parámetro de tipo hace que la interfaz sea covariante.',
 'Covariance allows IProducer<string> to be assigned to IProducer<object>.', 'La covarianza permite que IProducer<string> se asigne a IProducer<object>.',
 'IProducer<object> p = new StringProducer(); Console.WriteLine(p.Produce());', 'IProducer<object> p = new StringProducer(); Console.WriteLine(p.Produce());',
 50, 10, now()),

(gen_random_uuid(),
 'Custom Exception', 'Excepción Personalizada',
 'Create a custom exception InsufficientFundsException with a Balance property. Throw it when balance is 0, catch it and print "Insufficient funds: 0".',
 'Crea una excepción personalizada InsufficientFundsException con una propiedad Balance. Lánzala cuando el saldo sea 0, captúrala e imprime "Insufficient funds: 0".',
 'csharp', 4, 'exceptions',
 'using System;\n\nclass Program {\n    static void Main() {\n        // your code\n    }\n}',
 'Insufficient funds: 0',
 3,
 'Inherit from Exception to create a custom exception class.', 'Hereda de Exception para crear una clase de excepción personalizada.',
 'Add a Balance property and pass a message to the base constructor.', 'Agrega una propiedad Balance y pasa un mensaje al constructor base.',
 'catch (InsufficientFundsException ex) { Console.WriteLine($"Insufficient funds: {ex.Balance}"); }', 'catch (InsufficientFundsException ex) { Console.WriteLine($"Insufficient funds: {ex.Balance}"); }',
 50, 10, now()),

(gen_random_uuid(),
 'Expression-Bodied Members', 'Miembros con Cuerpo de Expresión',
 'Create a class Rectangle with Width and Height properties. Add an expression-bodied property Area returning Width*Height and a method Describe() returning a formatted string. Print Describe() for 4x5.',
 'Crea una clase Rectangle con propiedades Width y Height. Agrega una propiedad Area con cuerpo de expresión que devuelva Width*Height y un método Describe() que devuelva una cadena formateada. Imprime Describe() para 4x5.',
 'csharp', 4, 'properties',
 'using System;\n\nclass Program {\n    static void Main() {\n        // your code\n    }\n}',
 'Rectangle 4x5 area=20',
 3,
 'Expression-bodied members use => instead of { return ...; }.', 'Los miembros con cuerpo de expresión usan => en lugar de { return ...; }.',
 'public double Area => Width * Height; is an expression-bodied property.', 'public double Area => Width * Height; es una propiedad con cuerpo de expresión.',
 'public string Describe() => $"Rectangle {Width}x{Height} area={Area}";', 'public string Describe() => $"Rectangle {Width}x{Height} area={Area}";',
 50, 10, now()),

(gen_random_uuid(),
 'LINQ SelectMany', 'LINQ SelectMany',
 'Given a list of string arrays {{"a","b"},{"c","d"},{"e"}}, use SelectMany to flatten it and print each element.',
 'Dada una lista de arrays de string {{"a","b"},{"c","d"},{"e"}}, usa SelectMany para aplanarla e imprime cada elemento.',
 'csharp', 4, 'linq',
 'using System;\nusing System.Collections.Generic;\nusing System.Linq;\n\nclass Program {\n    static void Main() {\n        // your code\n    }\n}',
 'a\nb\nc\nd\ne',
 3,
 'SelectMany flattens a sequence of sequences into a single sequence.', 'SelectMany aplana una secuencia de secuencias en una sola secuencia.',
 'Use .SelectMany(arr => arr) to flatten one level.', 'Usa .SelectMany(arr => arr) para aplanar un nivel.',
 'foreach (var s in data.SelectMany(arr => arr)) Console.WriteLine(s);', 'foreach (var s in data.SelectMany(arr => arr)) Console.WriteLine(s);',
 50, 10, now()),

(gen_random_uuid(),
 'Composite Pattern Matching', 'Pattern Matching Compuesto',
 'Use a switch expression with relational and logical patterns to classify an integer: < 0 = "negative", 0 = "zero", > 0 and <= 100 = "small positive", else "large". Test with -5, 0, 50, 200 and print each.',
 'Usa una expresión switch con patrones relacionales y lógicos para clasificar un entero: < 0 = "negative", 0 = "zero", > 0 y <= 100 = "small positive", sino "large". Prueba con -5, 0, 50, 200 e imprime cada uno.',
 'csharp', 4, 'pattern-matching',
 'using System;\n\nclass Program {\n    static void Main() {\n        // your code\n    }\n}',
 'negative\nzero\nsmall positive\nlarge',
 3,
 'C# 9+ supports relational patterns: < 0, > 0, <= 100.', 'C# 9+ soporta patrones relacionales: < 0, > 0, <= 100.',
 'Use and to combine patterns: > 0 and <= 100.', 'Usa and para combinar patrones: > 0 and <= 100.',
 'n switch { < 0 => "negative", 0 => "zero", > 0 and <= 100 => "small positive", _ => "large" }', 'n switch { < 0 => "negative", 0 => "zero", > 0 and <= 100 => "small positive", _ => "large" }',
 50, 10, now()),

(gen_random_uuid(),
 'Async CancellationToken', 'CancellationToken Asíncrono',
 'Write an async method that accepts a CancellationToken and throws OperationCanceledException when cancelled. Pass an already-cancelled token, catch the exception, and print "Cancelled".',
 'Escribe un método async que acepte un CancellationToken y lance OperationCanceledException cuando se cancele. Pasa un token ya cancelado, captura la excepción e imprime "Cancelled".',
 'csharp', 4, 'async-await',
 'using System;\nusing System.Threading;\nusing System.Threading.Tasks;\n\nclass Program {\n    static async Task Main() {\n        // your code\n    }\n}',
 'Cancelled',
 3,
 'Call token.ThrowIfCancellationRequested() inside the async method.', 'Llama a token.ThrowIfCancellationRequested() dentro del método async.',
 'Create a cancelled token: new CancellationToken(canceled: true).', 'Crea un token cancelado: new CancellationToken(canceled: true).',
 'try { await DoWork(new CancellationToken(true)); } catch (OperationCanceledException) { Console.WriteLine("Cancelled"); }', 'try { await DoWork(new CancellationToken(true)); } catch (OperationCanceledException) { Console.WriteLine("Cancelled"); }',
 50, 10, now()),

(gen_random_uuid(),
 'Fluent Interface Builder', 'Constructor de Interfaz Fluida',
 'Implement a QueryBuilder with fluent methods Select(string col), Where(string cond), Build() returning the query string. Chain them to build "SELECT name WHERE age>18" and print it.',
 'Implementa un QueryBuilder con métodos fluidos Select(string col), Where(string cond), Build() que devuelva la cadena de consulta. Encadénalos para construir "SELECT name WHERE age>18" e imprímelo.',
 'csharp', 4, 'patterns',
 'using System;\n\nclass Program {\n    static void Main() {\n        // your code\n    }\n}',
 'SELECT name WHERE age>18',
 3,
 'Fluent methods return this to allow chaining.', 'Los métodos fluidos devuelven this para permitir el encadenamiento.',
 'Store the column and condition in private fields.', 'Almacena la columna y la condición en campos privados.',
 'Console.WriteLine(new QueryBuilder().Select("name").Where("age>18").Build());', 'Console.WriteLine(new QueryBuilder().Select("name").Where("age>18").Build());',
 50, 10, now()),

(gen_random_uuid(),
 'Observer Pattern', 'Patrón Observador',
 'Implement the observer pattern: a Publisher class with Subscribe(Action<string>) and Publish(string). Subscribe two handlers that each print the message. Publish "event fired" and verify both handlers run.',
 'Implementa el patrón observador: una clase Publisher con Subscribe(Action<string>) y Publish(string). Suscribe dos manejadores que cada uno imprima el mensaje. Publica "event fired" y verifica que ambos manejadores se ejecuten.',
 'csharp', 4, 'patterns',
 'using System;\nusing System.Collections.Generic;\n\nclass Program {\n    static void Main() {\n        // your code\n    }\n}',
 'event fired\nevent fired',
 3,
 'Store subscribers in a List<Action<string>>.', 'Almacena los suscriptores en una List<Action<string>>.',
 'Publish iterates over all subscribers and invokes each one.', 'Publish itera sobre todos los suscriptores e invoca cada uno.',
 'class Publisher { List<Action<string>> _subs = new(); public void Subscribe(Action<string> h) => _subs.Add(h); public void Publish(string msg) { foreach(var s in _subs) s(msg); } }', 'class Publisher { List<Action<string>> _subs = new(); public void Subscribe(Action<string> h) => _subs.Add(h); public void Publish(string msg) { foreach(var s in _subs) s(msg); } }',
 50, 10, now()),

(gen_random_uuid(),
 'Decorator Pattern', 'Patrón Decorador',
 'Create an interface ILogger with Log(string msg). Implement ConsoleLogger and a TimestampDecorator that prepends "[LOG]" before delegating. Print "[LOG] hello" using the decorator.',
 'Crea una interfaz ILogger con Log(string msg). Implementa ConsoleLogger y un TimestampDecorator que anteponga "[LOG]" antes de delegar. Imprime "[LOG] hello" usando el decorador.',
 'csharp', 4, 'patterns',
 'using System;\n\nclass Program {\n    static void Main() {\n        // your code\n    }\n}',
 '[LOG] hello',
 3,
 'The decorator wraps another ILogger and delegates to it.', 'El decorador envuelve otro ILogger y delega en él.',
 'Constructor-inject the inner logger: public TimestampDecorator(ILogger inner).', 'Inyecta el logger interno en el constructor: public TimestampDecorator(ILogger inner).',
 'ILogger logger = new TimestampDecorator(new ConsoleLogger()); logger.Log("hello");', 'ILogger logger = new TimestampDecorator(new ConsoleLogger()); logger.Log("hello");',
 50, 10, now()),

(gen_random_uuid(),
 'Recursive Fibonacci', 'Fibonacci Recursivo',
 'Write a recursive method Fib(int n) that returns the nth Fibonacci number (Fib(0)=0, Fib(1)=1). Print Fib(10).',
 'Escribe un método recursivo Fib(int n) que devuelva el n-ésimo número de Fibonacci (Fib(0)=0, Fib(1)=1). Imprime Fib(10).',
 'csharp', 4, 'algorithms',
 'using System;\n\nclass Program {\n    static void Main() {\n        // your code\n    }\n}',
 '55',
 3,
 'The recursive case: Fib(n) = Fib(n-1) + Fib(n-2).', 'El caso recursivo: Fib(n) = Fib(n-1) + Fib(n-2).',
 'Base cases: Fib(0) returns 0, Fib(1) returns 1.', 'Casos base: Fib(0) devuelve 0, Fib(1) devuelve 1.',
 'static int Fib(int n) => n <= 1 ? n : Fib(n-1) + Fib(n-2);', 'static int Fib(int n) => n <= 1 ? n : Fib(n-1) + Fib(n-2);',
 50, 10, now()),

(gen_random_uuid(),
 'Memoized Fibonacci', 'Fibonacci con Memoización',
 'Implement Fibonacci with memoization using a Dictionary<int,long>. Print Fib(40).',
 'Implementa Fibonacci con memoización usando un Dictionary<int,long>. Imprime Fib(40).',
 'csharp', 4, 'algorithms',
 'using System;\nusing System.Collections.Generic;\n\nclass Program {\n    static Dictionary<int,long> _cache = new();\n    static void Main() {\n        // your code\n    }\n}',
 '102334155',
 3,
 'Check the cache before computing: if (_cache.ContainsKey(n)) return _cache[n];', 'Verifica el caché antes de calcular: if (_cache.ContainsKey(n)) return _cache[n];',
 'Store results: _cache[n] = Fib(n-1) + Fib(n-2);', 'Almacena resultados: _cache[n] = Fib(n-1) + Fib(n-2);',
 'static long Fib(int n) { if (n<=1) return n; if (_cache.ContainsKey(n)) return _cache[n]; return _cache[n]=Fib(n-1)+Fib(n-2); }', 'static long Fib(int n) { if (n<=1) return n; if (_cache.ContainsKey(n)) return _cache[n]; return _cache[n]=Fib(n-1)+Fib(n-2); }',
 50, 10, now()),

(gen_random_uuid(),
 'LINQ Query Syntax', 'Sintaxis de Consulta LINQ',
 'Use LINQ query syntax to select names longer than 4 characters from {"Tom","Alice","Bob","Charlie","Jo"} and print them in alphabetical order.',
 'Usa la sintaxis de consulta LINQ para seleccionar nombres con más de 4 caracteres de {"Tom","Alice","Bob","Charlie","Jo"} e imprímelos en orden alfabético.',
 'csharp', 4, 'linq',
 'using System;\nusing System.Collections.Generic;\nusing System.Linq;\n\nclass Program {\n    static void Main() {\n        // your code\n    }\n}',
 'Alice\nCharlie',
 3,
 'LINQ query syntax uses from, where, orderby, select keywords.', 'La sintaxis de consulta LINQ usa las palabras clave from, where, orderby, select.',
 'Use where name.Length > 4 and orderby name.', 'Usa where name.Length > 4 y orderby name.',
 'var q = from n in names where n.Length > 4 orderby n select n; foreach(var n in q) Console.WriteLine(n);', 'var q = from n in names where n.Length > 4 orderby n select n; foreach(var n in q) Console.WriteLine(n);',
 50, 10, now()),

-- ============================================================
-- DIFFICULTY 5 — 10 exercises (points: 100, penalty: 10)
-- ============================================================

(gen_random_uuid(),
 'Async Semaphore Rate Limiter', 'Limitador de Tasa con Semáforo Async',
 'Implement an async rate limiter using SemaphoreSlim(2,2) that allows at most 2 concurrent tasks. Launch 4 tasks each printing their index when they acquire the semaphore, then releasing it. Show all complete in order.',
 'Implementa un limitador de tasa async usando SemaphoreSlim(2,2) que permita como máximo 2 tareas concurrentes. Lanza 4 tareas que cada una imprima su índice al adquirir el semáforo, luego lo libera. Muestra todos los completos en orden.',
 'csharp', 5, 'async-await',
 'using System;\nusing System.Threading;\nusing System.Threading.Tasks;\n\nclass Program {\n    static async Task Main() {\n        // your code\n    }\n}',
 '0\n1\n2\n3',
 3,
 'SemaphoreSlim(initialCount, maxCount) limits concurrent access.', 'SemaphoreSlim(initialCount, maxCount) limita el acceso concurrente.',
 'Use await sem.WaitAsync() to acquire and sem.Release() to release.', 'Usa await sem.WaitAsync() para adquirir y sem.Release() para liberar.',
 'var sem = new SemaphoreSlim(2,2); var tasks = Enumerable.Range(0,4).Select(async i => { await sem.WaitAsync(); Console.WriteLine(i); sem.Release(); }); await Task.WhenAll(tasks);', 'var sem = new SemaphoreSlim(2,2); var tasks = Enumerable.Range(0,4).Select(async i => { await sem.WaitAsync(); Console.WriteLine(i); sem.Release(); }); await Task.WhenAll(tasks);',
 100, 10, now()),

(gen_random_uuid(),
 'Expression Tree Builder', 'Constructor de Árbol de Expresiones',
 'Build an expression tree using System.Linq.Expressions that represents (x) => x * x + 1. Compile it, invoke with x=4, and print the result.',
 'Construye un árbol de expresiones usando System.Linq.Expressions que represente (x) => x * x + 1. Compílalo, invócalo con x=4 e imprime el resultado.',
 'csharp', 5, 'advanced',
 'using System;\nusing System.Linq.Expressions;\n\nclass Program {\n    static void Main() {\n        // your code\n    }\n}',
 '17',
 3,
 'Use Expression.Parameter, Expression.Multiply, Expression.Add, Expression.Constant.', 'Usa Expression.Parameter, Expression.Multiply, Expression.Add, Expression.Constant.',
 'Build: Expression.Lambda<Func<int,int>>(body, param).Compile().', 'Construye: Expression.Lambda<Func<int,int>>(body, param).Compile().',
 'var x = Expression.Parameter(typeof(int),"x"); var body = Expression.Add(Expression.Multiply(x,x), Expression.Constant(1)); var f = Expression.Lambda<Func<int,int>>(body,x).Compile(); Console.WriteLine(f(4));', 'var x = Expression.Parameter(typeof(int),"x"); var body = Expression.Add(Expression.Multiply(x,x), Expression.Constant(1)); var f = Expression.Lambda<Func<int,int>>(body,x).Compile(); Console.WriteLine(f(4));',
 100, 10, now()),

(gen_random_uuid(),
 'Custom Awaitable', 'Awaitable Personalizado',
 'Implement a custom awaitable struct DelayAwaitable that wraps Task.Delay(0). It must have GetAwaiter() returning a TaskAwaiter. Await it in Main and print "awaited".',
 'Implementa un struct awaitable personalizado DelayAwaitable que envuelva Task.Delay(0). Debe tener GetAwaiter() devolviendo un TaskAwaiter. Espéralo en Main e imprime "awaited".',
 'csharp', 5, 'advanced',
 'using System;\nusing System.Runtime.CompilerServices;\nusing System.Threading.Tasks;\n\nclass Program {\n    static async Task Main() {\n        // your code\n    }\n}',
 'awaited',
 3,
 'GetAwaiter() must return a type implementing INotifyCompletion with IsCompleted, GetResult(), OnCompleted().', 'GetAwaiter() debe devolver un tipo que implemente INotifyCompletion con IsCompleted, GetResult(), OnCompleted().',
 'Task.Delay(0).GetAwaiter() returns a valid TaskAwaiter you can delegate to.', 'Task.Delay(0).GetAwaiter() devuelve un TaskAwaiter válido al que puedes delegar.',
 'struct DelayAwaitable { public TaskAwaiter GetAwaiter() => Task.Delay(0).GetAwaiter(); }', 'struct DelayAwaitable { public TaskAwaiter GetAwaiter() => Task.Delay(0).GetAwaiter(); }',
 100, 10, now()),

(gen_random_uuid(),
 'Generic Monad Maybe', 'Mónada Maybe Genérica',
 'Implement a Maybe<T> monad with a value or nothing state. Provide Bind<U>(Func<T,Maybe<U>>) and static Some(T)/None() factory methods. Chain two Bind calls on Maybe<int>.Some(5) — multiply by 2, then subtract 3 — and print the result.',
 'Implementa una mónada Maybe<T> con estado de valor o nada. Proporciona Bind<U>(Func<T,Maybe<U>>) y métodos de fábrica estáticos Some(T)/None(). Encadena dos llamadas Bind en Maybe<int>.Some(5) — multiplica por 2, luego resta 3 — e imprime el resultado.',
 'csharp', 5, 'advanced',
 'using System;\n\nclass Program {\n    static void Main() {\n        // your code\n    }\n}',
 '7',
 3,
 'Maybe<T> holds a value and a bool hasValue flag.', 'Maybe<T> contiene un valor y una bandera bool hasValue.',
 'Bind applies the function only if HasValue, otherwise propagates None.', 'Bind aplica la función solo si HasValue, de lo contrario propaga None.',
 'Maybe<int>.Some(5).Bind(x => Maybe<int>.Some(x*2)).Bind(x => Maybe<int>.Some(x-3))', 'Maybe<int>.Some(5).Bind(x => Maybe<int>.Some(x*2)).Bind(x => Maybe<int>.Some(x-3))',
 100, 10, now()),

(gen_random_uuid(),
 'Source Generator Simulation', 'Simulación de Source Generator',
 'Simulate a compile-time code generation pattern using T4-style logic at runtime: given a list of property names {"Id","Name","Age"}, generate and print C# property declarations for each.',
 'Simula un patrón de generación de código en tiempo de compilación usando lógica estilo T4 en tiempo de ejecución: dada una lista de nombres de propiedad {"Id","Name","Age"}, genera e imprime declaraciones de propiedad C# para cada uno.',
 'csharp', 5, 'advanced',
 'using System;\nusing System.Collections.Generic;\nusing System.Text;\n\nclass Program {\n    static void Main() {\n        // your code\n    }\n}',
 'public string Id { get; set; }\npublic string Name { get; set; }\npublic string Age { get; set; }',
 3,
 'Use StringBuilder and a loop to generate each property declaration.', 'Usa StringBuilder y un bucle para generar cada declaración de propiedad.',
 'Format: public string {name} { get; set; }', 'Formato: public string {name} { get; set; }',
 'foreach (var p in props) sb.AppendLine($"public string {p} {{ get; set; }}");', 'foreach (var p in props) sb.AppendLine($"public string {p} {{ get; set; }}");',
 100, 10, now()),

(gen_random_uuid(),
 'Concurrent Queue Producer-Consumer', 'Productor-Consumidor con Cola Concurrente',
 'Use ConcurrentQueue<int> with a producer task that enqueues 1-5 and a consumer task that dequeues and prints. Await both tasks and ensure all values are printed.',
 'Usa ConcurrentQueue<int> con una tarea productora que encola 1-5 y una tarea consumidora que desencola e imprime. Espera ambas tareas y asegura que todos los valores se impriman.',
 'csharp', 5, 'async-await',
 'using System;\nusing System.Collections.Concurrent;\nusing System.Threading.Tasks;\n\nclass Program {\n    static async Task Main() {\n        // your code\n    }\n}',
 '1\n2\n3\n4\n5',
 3,
 'ConcurrentQueue<T> is thread-safe for concurrent Enqueue/TryDequeue.', 'ConcurrentQueue<T> es seguro para hilos para Enqueue/TryDequeue concurrente.',
 'The consumer should loop until all items are dequeued; use a count or flag.', 'El consumidor debe iterar hasta que todos los elementos sean desencola dos; usa un conteo o bandera.',
 'while (produced < 5 || !queue.IsEmpty) { if (queue.TryDequeue(out int val)) Console.WriteLine(val); }', 'while (produced < 5 || !queue.IsEmpty) { if (queue.TryDequeue(out int val)) Console.WriteLine(val); }',
 100, 10, now()),

(gen_random_uuid(),
 'Recursive Descent Parser', 'Analizador de Descenso Recursivo',
 'Write a simple recursive descent parser that evaluates arithmetic expressions of the form "a+b" and "a-b" where a and b are single digits. Parse "7+3-2" and print 8.',
 'Escribe un analizador de descenso recursivo simple que evalúe expresiones aritméticas de la forma "a+b" y "a-b" donde a y b son dígitos simples. Analiza "7+3-2" e imprime 8.',
 'csharp', 5, 'algorithms',
 'using System;\n\nclass Program {\n    static void Main() {\n        // your code\n    }\n}',
 '8',
 3,
 'Parse left to right: read digit, then repeat reading operator and digit.', 'Analiza de izquierda a derecha: lee dígito, luego repite leyendo operador y dígito.',
 'Use an index variable to track the current position in the string.', 'Usa una variable de índice para rastrear la posición actual en la cadena.',
 'int pos=0; int result=expr[pos++]-''0''; while(pos<expr.Length){char op=expr[pos++];int n=expr[pos++]-''0''; result = op==''+'' ? result+n : result-n;}', 'int pos=0; int result=expr[pos++]-''0''; while(pos<expr.Length){char op=expr[pos++];int n=expr[pos++]-''0''; result = op==''+'' ? result+n : result-n;}',
 100, 10, now()),

(gen_random_uuid(),
 'Immutable Linked List', 'Lista Enlazada Inmutable',
 'Implement an immutable singly-linked list using records: record Node<T>(T Value, Node<T>? Next). Write a Prepend and a ToList helper. Build list [3,2,1] by prepending, convert to List<T>, and print each value.',
 'Implementa una lista enlazada simplemente enlazada inmutable usando records: record Node<T>(T Value, Node<T>? Next). Escribe helpers Prepend y ToList. Construye la lista [3,2,1] prepending, conviértela a List<T> e imprime cada valor.',
 'csharp', 5, 'advanced',
 'using System;\nusing System.Collections.Generic;\n\nclass Program {\n    static void Main() {\n        // your code\n    }\n}',
 '3\n2\n1',
 3,
 'Prepend creates a new Node<T> with the new value and the existing node as Next.', 'Prepend crea un nuevo Node<T> con el nuevo valor y el nodo existente como Next.',
 'ToList traverses the nodes collecting values until Next is null.', 'ToList recorre los nodos recolectando valores hasta que Next es null.',
 'Node<int>? list = null; list = new Node<int>(1, list); list = new Node<int>(2, list); list = new Node<int>(3, list);', 'Node<int>? list = null; list = new Node<int>(1, list); list = new Node<int>(2, list); list = new Node<int>(3, list);',
 100, 10, now()),

(gen_random_uuid(),
 'Lazy Evaluation with Lazy<T>', 'Evaluación Perezosa con Lazy<T>',
 'Use Lazy<T> to defer expensive initialization. Create a Lazy<string> that initializes with a factory printing "Computing..." and returning "result". Access .Value twice and verify "Computing..." prints only once.',
 'Usa Lazy<T> para diferir la inicialización costosa. Crea un Lazy<string> que inicialice con una fábrica que imprima "Computing..." y devuelva "result". Accede a .Value dos veces y verifica que "Computing..." se imprima solo una vez.',
 'csharp', 5, 'advanced',
 'using System;\n\nclass Program {\n    static void Main() {\n        // your code\n    }\n}',
 'Computing...\nresult\nresult',
 3,
 'Lazy<T> computes its value the first time .Value is accessed.', 'Lazy<T> calcula su valor la primera vez que se accede a .Value.',
 'Subsequent accesses to .Value return the cached result.', 'Los accesos subsecuentes a .Value devuelven el resultado en caché.',
 'var lazy = new Lazy<string>(() => { Console.WriteLine("Computing..."); return "result"; }); Console.WriteLine(lazy.Value); Console.WriteLine(lazy.Value);', 'var lazy = new Lazy<string>(() => { Console.WriteLine("Computing..."); return "result"; }); Console.WriteLine(lazy.Value); Console.WriteLine(lazy.Value);',
 100, 10, now()),

(gen_random_uuid(),
 'Span<T> Stack Allocation', 'Asignación en Pila con Span<T>',
 'Use stackalloc and Span<int> to allocate an array of 5 integers on the stack, fill it with squares (1,4,9,16,25), and print each value.',
 'Usa stackalloc y Span<int> para asignar un array de 5 enteros en la pila, llénalo con cuadrados (1,4,9,16,25) e imprime cada valor.',
 'csharp', 5, 'advanced',
 'using System;\n\nclass Program {\n    static void Main() {\n        // your code\n    }\n}',
 '1\n4\n9\n16\n25',
 3,
 'Span<T> provides a type-safe view over a contiguous region of memory.', 'Span<T> proporciona una vista de tipo seguro sobre una región contigua de memoria.',
 'Use stackalloc int[5] to allocate on the stack: Span<int> span = stackalloc int[5];', 'Usa stackalloc int[5] para asignar en la pila: Span<int> span = stackalloc int[5];',
 'for (int i=0; i<5; i++) span[i] = (i+1)*(i+1); foreach (int v in span) Console.WriteLine(v);', 'for (int i=0; i<5; i++) span[i] = (i+1)*(i+1); foreach (int v in span) Console.WriteLine(v);',
 100, 10, now())

ON CONFLICT DO NOTHING;

COMMIT;
