-- 059_exercises_html_css.sql
-- 100 HTML/CSS exercises, bilingual EN+ES
-- Distribution: diff1:25, diff2:25, diff3:25, diff4:15, diff5:10
-- Points: 10/20/30/50/100 | Penalty: 3/3/5/10/10
-- Topics: tags, forms, tables, semantic HTML, flexbox, grid, animations,
--         media queries, responsive design, accessibility (aria), selectors,
--         pseudo-elements, variables, transitions, transforms

BEGIN;

INSERT INTO exercises (
  id, title_en, title_es,
  description_en, description_es,
  language, difficulty, category,
  starter_code, expected_output,
  hint_count,
  hint_1_en, hint_1_es,
  hint_2_en, hint_2_es,
  hint_3_en, hint_3_es,
  points, hints_used_penalty,
  created_at
) VALUES

-- ============================================================
-- DIFFICULTY 1 — 25 exercises (points=10, penalty=3)
-- ============================================================

-- 1. tags
(gen_random_uuid(),
 'Basic HTML Document', 'Documento HTML Básico',
 'Complete the DOCTYPE declaration to define an HTML5 document.',
 'Completa la declaración DOCTYPE para definir un documento HTML5.',
 'html_css', 1, 'tags',
 '<!___ html>\n<html>\n  <head><title>Page</title></head>\n  <body></body>\n</html>',
 '<!DOCTYPE html>',
 3,
 'DOCTYPE tells the browser which version of HTML to use.', 'DOCTYPE le dice al navegador qué versión de HTML usar.',
 'HTML5 uses a simple DOCTYPE with no version number.', 'HTML5 usa un DOCTYPE simple sin número de versión.',
 '<!DOCTYPE html>', '<!DOCTYPE html>',
 10, 3, now()),

-- 2. tags
(gen_random_uuid(),
 'Heading Tags', 'Etiquetas de Encabezado',
 'Create an h1 heading with the text "Welcome" and an h2 heading with the text "Subtitle".',
 'Crea un encabezado h1 con el texto "Welcome" y un encabezado h2 con el texto "Subtitle".',
 'html_css', 1, 'tags',
 '<___>Welcome</___>\n<___>Subtitle</___>',
 '<h1>Welcome</h1>\n<h2>Subtitle</h2>',
 3,
 'Headings range from h1 (most important) to h6 (least important).', 'Los encabezados van de h1 (más importante) a h6 (menos importante).',
 'h1 is the main title, h2 is a section heading.', 'h1 es el título principal, h2 es un encabezado de sección.',
 '<h1>Welcome</h1>\n<h2>Subtitle</h2>', '<h1>Welcome</h1>\n<h2>Subtitle</h2>',
 10, 3, now()),

-- 3. tags
(gen_random_uuid(),
 'Paragraph Tag', 'Etiqueta de Párrafo',
 'Wrap the text "Hello World" inside a paragraph element.',
 'Encierra el texto "Hello World" dentro de un elemento de párrafo.',
 'html_css', 1, 'tags',
 '<___>Hello World</___>',
 '<p>Hello World</p>',
 3,
 'The paragraph element is one of the most basic HTML elements.', 'El elemento de párrafo es uno de los elementos HTML más básicos.',
 'Paragraphs use a two-letter tag.', 'Los párrafos usan una etiqueta de dos letras.',
 '<p>Hello World</p>', '<p>Hello World</p>',
 10, 3, now()),

-- 4. tags
(gen_random_uuid(),
 'Anchor Link', 'Enlace de Ancla',
 'Create a link to "https://example.com" with the display text "Visit Us".',
 'Crea un enlace a "https://example.com" con el texto visible "Visit Us".',
 'html_css', 1, 'tags',
 '<a ___="https://example.com">Visit Us</a>',
 '<a href="https://example.com">Visit Us</a>',
 3,
 'Links use the <a> tag with an attribute that specifies the destination.', 'Los enlaces usan la etiqueta <a> con un atributo que especifica el destino.',
 'The attribute name stands for "hypertext reference".', 'El nombre del atributo significa "referencia de hipertexto".',
 'href="https://example.com"', 'href="https://example.com"',
 10, 3, now()),

-- 5. tags
(gen_random_uuid(),
 'Image Tag', 'Etiqueta de Imagen',
 'Insert an image using the file "logo.png" with the alt text "Company Logo".',
 'Inserta una imagen usando el archivo "logo.png" con el texto alternativo "Company Logo".',
 'html_css', 1, 'tags',
 '<img ___="logo.png" ___="Company Logo">',
 '<img src="logo.png" alt="Company Logo">',
 3,
 'Images are self-closing and require two key attributes.', 'Las imágenes son auto-cerradas y requieren dos atributos clave.',
 'One attribute sets the file path, the other provides descriptive text.', 'Un atributo establece la ruta del archivo, el otro proporciona texto descriptivo.',
 'src="logo.png" alt="Company Logo"', 'src="logo.png" alt="Company Logo"',
 10, 3, now()),

-- 6. tags
(gen_random_uuid(),
 'Unordered List', 'Lista Desordenada',
 'Create an unordered list with two items: "Apple" and "Banana".',
 'Crea una lista desordenada con dos elementos: "Apple" y "Banana".',
 'html_css', 1, 'tags',
 '<___>\n  <li>Apple</li>\n  <li>___</li>\n</___>',
 '<ul>\n  <li>Apple</li>\n  <li>Banana</li>\n</ul>',
 3,
 'Unordered lists display bullet points by default.', 'Las listas desordenadas muestran viñetas por defecto.',
 'The container tag is ul, and each item uses li.', 'La etiqueta contenedora es ul, y cada elemento usa li.',
 '<ul>\n  <li>Apple</li>\n  <li>Banana</li>\n</ul>', '<ul>\n  <li>Apple</li>\n  <li>Banana</li>\n</ul>',
 10, 3, now()),

-- 7. tags
(gen_random_uuid(),
 'Ordered List', 'Lista Ordenada',
 'Create an ordered list with items "First" and "Second".',
 'Crea una lista ordenada con los elementos "First" y "Second".',
 'html_css', 1, 'tags',
 '<___>\n  <li>First</li>\n  <li>Second</li>\n</___>',
 '<ol>\n  <li>First</li>\n  <li>Second</li>\n</ol>',
 3,
 'Ordered lists display numbers (1, 2, 3...) by default.', 'Las listas ordenadas muestran números (1, 2, 3...) por defecto.',
 'The tag for an ordered list starts with "o".', 'La etiqueta para una lista ordenada comienza con "o".',
 '<ol>\n  <li>First</li>\n  <li>Second</li>\n</ol>', '<ol>\n  <li>First</li>\n  <li>Second</li>\n</ol>',
 10, 3, now()),

-- 8. selectors
(gen_random_uuid(),
 'CSS Color Property', 'Propiedad de Color CSS',
 'Set the text color of all paragraphs to red.',
 'Establece el color del texto de todos los párrafos en rojo.',
 'html_css', 1, 'selectors',
 'p {\n  ___: red;\n}',
 'p {\n  color: red;\n}',
 3,
 'This property sets the foreground color of text.', 'Esta propiedad establece el color del texto en primer plano.',
 'The property is simply named after what it controls.', 'La propiedad lleva el nombre de lo que controla.',
 'color: red;', 'color: red;',
 10, 3, now()),

-- 9. selectors
(gen_random_uuid(),
 'CSS Background Color', 'Color de Fondo CSS',
 'Set the background color of the body to lightblue.',
 'Establece el color de fondo del cuerpo en lightblue.',
 'html_css', 1, 'selectors',
 'body {\n  ___: lightblue;\n}',
 'body {\n  background-color: lightblue;\n}',
 3,
 'Use the background-color property to change the background.', 'Usa la propiedad background-color para cambiar el fondo.',
 'The property name is two words joined by a hyphen.', 'El nombre de la propiedad son dos palabras unidas por un guión.',
 'background-color: lightblue;', 'background-color: lightblue;',
 10, 3, now()),

-- 10. selectors
(gen_random_uuid(),
 'CSS Font Size', 'Tamaño de Fuente CSS',
 'Set the font size of h1 elements to 32px.',
 'Establece el tamaño de fuente de los elementos h1 en 32px.',
 'html_css', 1, 'selectors',
 'h1 {\n  ___: 32px;\n}',
 'h1 {\n  font-size: 32px;\n}',
 3,
 'This property controls how large the text appears.', 'Esta propiedad controla qué tan grande aparece el texto.',
 'The property name is two words: "font" and "size".', 'El nombre de la propiedad son dos palabras: "font" y "size".',
 'font-size: 32px;', 'font-size: 32px;',
 10, 3, now()),

-- 11. selectors
(gen_random_uuid(),
 'Class Selector', 'Selector de Clase',
 'Write a CSS rule targeting the class "highlight" that sets background to yellow.',
 'Escribe una regla CSS que apunte a la clase "highlight" y establezca el fondo en amarillo.',
 'html_css', 1, 'selectors',
 '___ {\n  background-color: yellow;\n}',
 '.highlight {\n  background-color: yellow;\n}',
 3,
 'Class selectors begin with a special character.', 'Los selectores de clase comienzan con un carácter especial.',
 'Use a period (.) before the class name.', 'Usa un punto (.) antes del nombre de la clase.',
 '.highlight { background-color: yellow; }', '.highlight { background-color: yellow; }',
 10, 3, now()),

-- 12. selectors
(gen_random_uuid(),
 'ID Selector', 'Selector de ID',
 'Write a CSS rule targeting the id "header" that sets color to navy.',
 'Escribe una regla CSS que apunte al id "header" y establezca el color en navy.',
 'html_css', 1, 'selectors',
 '___ {\n  color: navy;\n}',
 '#header {\n  color: navy;\n}',
 3,
 'ID selectors begin with a special character.', 'Los selectores de ID comienzan con un carácter especial.',
 'Use a hash (#) before the ID name.', 'Usa un hash (#) antes del nombre del ID.',
 '#header { color: navy; }', '#header { color: navy; }',
 10, 3, now()),

-- 13. tags
(gen_random_uuid(),
 'Bold and Italic Text', 'Texto en Negrita y Cursiva',
 'Make the word "important" bold and the word "note" italic using semantic tags.',
 'Pon en negrita la palabra "important" y en cursiva la palabra "note" usando etiquetas semánticas.',
 'html_css', 1, 'tags',
 '<___>important</___> and <___>note</___>',
 '<strong>important</strong> and <em>note</em>',
 3,
 'Use semantic tags rather than <b> or <i> for accessibility.', 'Usa etiquetas semánticas en lugar de <b> o <i> para accesibilidad.',
 '<strong> conveys importance; <em> conveys emphasis.', '<strong> transmite importancia; <em> transmite énfasis.',
 '<strong>important</strong> and <em>note</em>', '<strong>important</strong> and <em>note</em>',
 10, 3, now()),

-- 14. tags
(gen_random_uuid(),
 'Line Break', 'Salto de Línea',
 'Add a line break between "Line 1" and "Line 2" without using a new paragraph.',
 'Agrega un salto de línea entre "Line 1" y "Line 2" sin usar un nuevo párrafo.',
 'html_css', 1, 'tags',
 'Line 1\n___\nLine 2',
 'Line 1\n<br>\nLine 2',
 3,
 'This is a self-closing (void) element.', 'Este es un elemento auto-cerrado (void).',
 'The tag is two letters: b and r.', 'La etiqueta tiene dos letras: b y r.',
 '<br>', '<br>',
 10, 3, now()),

-- 15. tags
(gen_random_uuid(),
 'Horizontal Rule', 'Línea Horizontal',
 'Add a horizontal divider line between two sections of text.',
 'Agrega una línea divisoria horizontal entre dos secciones de texto.',
 'html_css', 1, 'tags',
 '<p>Section 1</p>\n___\n<p>Section 2</p>',
 '<p>Section 1</p>\n<hr>\n<p>Section 2</p>',
 3,
 'This void element draws a thematic break between content.', 'Este elemento void dibuja una ruptura temática entre contenido.',
 'The tag is two letters: h and r.', 'La etiqueta tiene dos letras: h y r.',
 '<hr>', '<hr>',
 10, 3, now()),

-- 16. selectors
(gen_random_uuid(),
 'CSS Margin', 'Margen CSS',
 'Set the margin on all four sides of a div to 20px.',
 'Establece el margen en los cuatro lados de un div en 20px.',
 'html_css', 1, 'selectors',
 'div {\n  ___: 20px;\n}',
 'div {\n  margin: 20px;\n}',
 3,
 'A single value applies the same space to all four sides.', 'Un solo valor aplica el mismo espacio a los cuatro lados.',
 'The property name is "margin".', 'El nombre de la propiedad es "margin".',
 'margin: 20px;', 'margin: 20px;',
 10, 3, now()),

-- 17. selectors
(gen_random_uuid(),
 'CSS Padding', 'Relleno CSS',
 'Set 10px padding on all sides of elements with class "card".',
 'Establece 10px de relleno en todos los lados de los elementos con clase "card".',
 'html_css', 1, 'selectors',
 '.card {\n  ___: 10px;\n}',
 '.card {\n  padding: 10px;\n}',
 3,
 'Padding adds space inside the element, between content and border.', 'El relleno agrega espacio dentro del elemento, entre el contenido y el borde.',
 'The property name is "padding".', 'El nombre de la propiedad es "padding".',
 'padding: 10px;', 'padding: 10px;',
 10, 3, now()),

-- 18. selectors
(gen_random_uuid(),
 'CSS Text Align', 'Alineación de Texto CSS',
 'Center the text inside all h2 elements.',
 'Centra el texto dentro de todos los elementos h2.',
 'html_css', 1, 'selectors',
 'h2 {\n  ___: center;\n}',
 'h2 {\n  text-align: center;\n}',
 3,
 'This property controls horizontal alignment of text.', 'Esta propiedad controla la alineación horizontal del texto.',
 'The property name is "text-align".', 'El nombre de la propiedad es "text-align".',
 'text-align: center;', 'text-align: center;',
 10, 3, now()),

-- 19. tags
(gen_random_uuid(),
 'HTML Comment', 'Comentario HTML',
 'Add an HTML comment with the text "TODO: add content here".',
 'Agrega un comentario HTML con el texto "TODO: add content here".',
 'html_css', 1, 'tags',
 '___',
 '<!-- TODO: add content here -->',
 3,
 'Comments are not rendered by the browser.', 'Los comentarios no son renderizados por el navegador.',
 'HTML comments begin with <!-- and end with -->.', 'Los comentarios HTML comienzan con <!-- y terminan con -->.',
 '<!-- TODO: add content here -->', '<!-- TODO: add content here -->',
 10, 3, now()),

-- 20. tags
(gen_random_uuid(),
 'Div Container', 'Contenedor Div',
 'Wrap two paragraphs inside a div with the class "wrapper".',
 'Encierra dos párrafos dentro de un div con la clase "wrapper".',
 'html_css', 1, 'tags',
 '<___ class="___">\n  <p>First</p>\n  <p>Second</p>\n</___>',
 '<div class="wrapper">\n  <p>First</p>\n  <p>Second</p>\n</div>',
 3,
 'div is a generic block-level container element.', 'div es un elemento contenedor de bloque genérico.',
 'Add the class attribute inside the opening tag.', 'Agrega el atributo class dentro de la etiqueta de apertura.',
 '<div class="wrapper">', '<div class="wrapper">',
 10, 3, now()),

-- 21. selectors
(gen_random_uuid(),
 'CSS Width and Height', 'Ancho y Alto CSS',
 'Set the width to 200px and height to 100px on elements with class "box".',
 'Establece el ancho en 200px y el alto en 100px en los elementos con clase "box".',
 'html_css', 1, 'selectors',
 '.box {\n  ___: 200px;\n  ___: 100px;\n}',
 '.box {\n  width: 200px;\n  height: 100px;\n}',
 3,
 'Use the "width" and "height" properties.', 'Usa las propiedades "width" y "height".',
 'Both accept pixel values like 200px.', 'Ambas aceptan valores en píxeles como 200px.',
 'width: 200px;\n  height: 100px;', 'width: 200px;\n  height: 100px;',
 10, 3, now()),

-- 22. selectors
(gen_random_uuid(),
 'CSS Border', 'Borde CSS',
 'Add a 1px solid black border to elements with class "frame".',
 'Agrega un borde sólido negro de 1px a los elementos con clase "frame".',
 'html_css', 1, 'selectors',
 '.frame {\n  ___: 1px solid black;\n}',
 '.frame {\n  border: 1px solid black;\n}',
 3,
 'The border shorthand takes width, style, and color.', 'El shorthand de border toma ancho, estilo y color.',
 'The order is: thickness, style (solid/dashed/dotted), color.', 'El orden es: grosor, estilo (solid/dashed/dotted), color.',
 'border: 1px solid black;', 'border: 1px solid black;',
 10, 3, now()),

-- 23. selectors
(gen_random_uuid(),
 'CSS Font Weight', 'Grosor de Fuente CSS',
 'Make the text inside elements with class "label" bold.',
 'Pon en negrita el texto dentro de los elementos con clase "label".',
 'html_css', 1, 'selectors',
 '.label {\n  ___: bold;\n}',
 '.label {\n  font-weight: bold;\n}',
 3,
 'This property controls the thickness of text characters.', 'Esta propiedad controla el grosor de los caracteres del texto.',
 'The property name is "font-weight".', 'El nombre de la propiedad es "font-weight".',
 'font-weight: bold;', 'font-weight: bold;',
 10, 3, now()),

-- 24. tags
(gen_random_uuid(),
 'Span Inline Element', 'Elemento Span en Línea',
 'Wrap the word "special" in a span with class "highlight".',
 'Encierra la palabra "special" en un span con clase "highlight".',
 'html_css', 1, 'tags',
 'This is <___ class="highlight">special</___> text.',
 'This is <span class="highlight">special</span> text.',
 3,
 'span is an inline element used to style a portion of text.', 'span es un elemento en línea usado para estilizar una porción de texto.',
 'Unlike div, span does not create a new line.', 'A diferencia de div, span no crea una nueva línea.',
 '<span class="highlight">special</span>', '<span class="highlight">special</span>',
 10, 3, now()),

-- 25. selectors
(gen_random_uuid(),
 'CSS List Style None', 'Sin Estilo de Lista CSS',
 'Remove the bullet points from a ul element by setting list-style to none.',
 'Elimina los puntos de viñeta de un elemento ul estableciendo list-style en none.',
 'html_css', 1, 'selectors',
 'ul {\n  ___: none;\n}',
 'ul {\n  list-style: none;\n}',
 3,
 'The list-style shorthand controls bullet appearance.', 'El shorthand list-style controla la apariencia de las viñetas.',
 'Setting it to "none" removes the bullet entirely.', 'Establecerlo en "none" elimina la viñeta por completo.',
 'list-style: none;', 'list-style: none;',
 10, 3, now()),

-- ============================================================
-- DIFFICULTY 2 — 25 exercises (points=20, penalty=3)
-- ============================================================

-- 26. forms
(gen_random_uuid(),
 'Text Input Field', 'Campo de Entrada de Texto',
 'Create a text input field with name "username" and placeholder "Enter username".',
 'Crea un campo de entrada de texto con nombre "username" y placeholder "Enter username".',
 'html_css', 2, 'forms',
 '<input type="___" name="___" placeholder="___">',
 '<input type="text" name="username" placeholder="Enter username">',
 3,
 'The type attribute determines what kind of data the input accepts.', 'El atributo type determina qué tipo de datos acepta la entrada.',
 'Text inputs use type="text".', 'Las entradas de texto usan type="text".',
 'type="text" name="username" placeholder="Enter username"', 'type="text" name="username" placeholder="Enter username"',
 20, 3, now()),

-- 27. forms
(gen_random_uuid(),
 'Form Submit Button', 'Botón de Envío de Formulario',
 'Create a form that POSTs to "/login" containing an email input and a submit button labeled "Log In".',
 'Crea un formulario que haga POST a "/login" con una entrada de email y un botón de envío con etiqueta "Log In".',
 'html_css', 2, 'forms',
 '<form method="___" action="___">\n  <input type="email" name="email">\n  <button type="___">Log In</button>\n</form>',
 '<form method="post" action="/login">\n  <input type="email" name="email">\n  <button type="submit">Log In</button>\n</form>',
 3,
 'Forms need a method (get or post) and an action (destination URL).', 'Los formularios necesitan un método (get o post) y una acción (URL destino).',
 'The submit button triggers form submission.', 'El botón submit activa el envío del formulario.',
 'method="post" action="/login" ... type="submit"', 'method="post" action="/login" ... type="submit"',
 20, 3, now()),

-- 28. forms
(gen_random_uuid(),
 'Label for Input', 'Etiqueta para Entrada',
 'Associate a label "Email" with an input field using the "for" attribute and a matching id.',
 'Asocia una etiqueta "Email" con un campo de entrada usando el atributo "for" y un id coincidente.',
 'html_css', 2, 'forms',
 '<label ___="email">Email</label>\n<input type="email" ___="email">',
 '<label for="email">Email</label>\n<input type="email" id="email">',
 3,
 'The label''s "for" must match the input''s "id".', 'El "for" de la etiqueta debe coincidir con el "id" de la entrada.',
 'Clicking the label focuses the associated input.', 'Hacer clic en la etiqueta enfoca la entrada asociada.',
 'for="email" ... id="email"', 'for="email" ... id="email"',
 20, 3, now()),

-- 29. forms
(gen_random_uuid(),
 'Checkbox Input', 'Entrada de Casilla de Verificación',
 'Create a checkbox input with name "agree" that is checked by default.',
 'Crea una entrada de casilla de verificación con nombre "agree" que esté marcada por defecto.',
 'html_css', 2, 'forms',
 '<input type="___" name="agree" ___>',
 '<input type="checkbox" name="agree" checked>',
 3,
 'Checkboxes use type="checkbox".', 'Las casillas de verificación usan type="checkbox".',
 'Add the boolean attribute "checked" to pre-select it.', 'Agrega el atributo booleano "checked" para pre-seleccionarlo.',
 'type="checkbox" ... checked', 'type="checkbox" ... checked',
 20, 3, now()),

-- 30. forms
(gen_random_uuid(),
 'Select Dropdown', 'Menú Desplegable Select',
 'Create a dropdown with options "Red", "Green", "Blue" and name "color".',
 'Crea un menú desplegable con opciones "Red", "Green", "Blue" y nombre "color".',
 'html_css', 2, 'forms',
 '<select name="color">\n  <option ___="red">Red</option>\n  <option ___="green">Green</option>\n  <option ___="blue">Blue</option>\n</select>',
 '<select name="color">\n  <option value="red">Red</option>\n  <option value="green">Green</option>\n  <option value="blue">Blue</option>\n</select>',
 3,
 'Each option needs a value attribute that gets submitted.', 'Cada opción necesita un atributo value que se envía al servidor.',
 'The value attribute can differ from the display text.', 'El atributo value puede diferir del texto visible.',
 'value="red" ... value="green" ... value="blue"', 'value="red" ... value="green" ... value="blue"',
 20, 3, now()),

-- 31. tables
(gen_random_uuid(),
 'Basic HTML Table', 'Tabla HTML Básica',
 'Create a table with a header row containing "Name" and "Age", and one data row with "Alice" and "30".',
 'Crea una tabla con una fila de encabezado con "Name" y "Age", y una fila de datos con "Alice" y "30".',
 'html_css', 2, 'tables',
 '<table>\n  <tr>\n    <___>Name</___>\n    <___>Age</___>\n  </tr>\n  <tr>\n    <td>Alice</td>\n    <td>30</td>\n  </tr>\n</table>',
 '<table>\n  <tr>\n    <th>Name</th>\n    <th>Age</th>\n  </tr>\n  <tr>\n    <td>Alice</td>\n    <td>30</td>\n  </tr>\n</table>',
 3,
 'Table header cells use a different tag than data cells.', 'Las celdas de encabezado de tabla usan una etiqueta diferente a las celdas de datos.',
 'Header cells use <th>, data cells use <td>.', 'Las celdas de encabezado usan <th>, las celdas de datos usan <td>.',
 '<th>Name</th>\n    <th>Age</th>', '<th>Name</th>\n    <th>Age</th>',
 20, 3, now()),

-- 32. tables
(gen_random_uuid(),
 'Table with thead and tbody', 'Tabla con thead y tbody',
 'Wrap the header row in a <thead> and the data rows in a <tbody>.',
 'Envuelve la fila de encabezado en un <thead> y las filas de datos en un <tbody>.',
 'html_css', 2, 'tables',
 '<table>\n  <___>\n    <tr><th>Name</th><th>Score</th></tr>\n  </___>\n  <___>\n    <tr><td>Bob</td><td>95</td></tr>\n  </___>\n</table>',
 '<table>\n  <thead>\n    <tr><th>Name</th><th>Score</th></tr>\n  </thead>\n  <tbody>\n    <tr><td>Bob</td><td>95</td></tr>\n  </tbody>\n</table>',
 3,
 'thead and tbody add semantic structure to tables.', 'thead y tbody agregan estructura semántica a las tablas.',
 'thead wraps header rows, tbody wraps body rows.', 'thead envuelve las filas de encabezado, tbody envuelve las filas del cuerpo.',
 '<thead> ... </thead> ... <tbody> ... </tbody>', '<thead> ... </thead> ... <tbody> ... </tbody>',
 20, 3, now()),

-- 33. semantic HTML
(gen_random_uuid(),
 'Semantic Page Layout', 'Diseño de Página Semántico',
 'Use semantic elements to structure a page with a header, main content area, and footer.',
 'Usa elementos semánticos para estructurar una página con encabezado, área de contenido principal y pie de página.',
 'html_css', 2, 'semantic HTML',
 '<___>Site Title</___>\n<___>\n  <p>Content here</p>\n</___>\n<___>Copyright 2025</___>',
 '<header>Site Title</header>\n<main>\n  <p>Content here</p>\n</main>\n<footer>Copyright 2025</footer>',
 3,
 'HTML5 introduced semantic elements with meaningful names.', 'HTML5 introdujo elementos semánticos con nombres significativos.',
 'Use <header>, <main>, and <footer> instead of generic divs.', 'Usa <header>, <main> y <footer> en lugar de divs genéricos.',
 '<header> ... <main> ... <footer>', '<header> ... <main> ... <footer>',
 20, 3, now()),

-- 34. semantic HTML
(gen_random_uuid(),
 'Nav Element', 'Elemento Nav',
 'Wrap a list of navigation links inside the appropriate semantic element.',
 'Envuelve una lista de enlaces de navegación dentro del elemento semántico apropiado.',
 'html_css', 2, 'semantic HTML',
 '<___>\n  <ul>\n    <li><a href="/">Home</a></li>\n    <li><a href="/about">About</a></li>\n  </ul>\n</___>',
 '<nav>\n  <ul>\n    <li><a href="/">Home</a></li>\n    <li><a href="/about">About</a></li>\n  </ul>\n</nav>',
 3,
 'Navigation menus have a dedicated semantic element.', 'Los menús de navegación tienen un elemento semántico dedicado.',
 'The element is a 3-letter abbreviation of "navigation".', 'El elemento es una abreviatura de 3 letras de "navigation".',
 '<nav> ... </nav>', '<nav> ... </nav>',
 20, 3, now()),

-- 35. selectors
(gen_random_uuid(),
 'Descendant Selector', 'Selector Descendiente',
 'Write a CSS rule that targets only <p> elements inside a .content div.',
 'Escribe una regla CSS que apunte solo a elementos <p> dentro de un div .content.',
 'html_css', 2, 'selectors',
 '___ p {\n  color: gray;\n}',
 '.content p {\n  color: gray;\n}',
 3,
 'A space between selectors creates a descendant relationship.', 'Un espacio entre selectores crea una relación de descendencia.',
 'The left selector is the ancestor, the right is the target.', 'El selector izquierdo es el ancestro, el derecho es el objetivo.',
 '.content p { color: gray; }', '.content p { color: gray; }',
 20, 3, now()),

-- 36. selectors
(gen_random_uuid(),
 'Multiple Selectors', 'Selectores Múltiples',
 'Apply font-weight bold to both h1 and h2 elements using a single rule.',
 'Aplica font-weight bold a los elementos h1 y h2 usando una sola regla.',
 'html_css', 2, 'selectors',
 'h1___ h2 {\n  font-weight: bold;\n}',
 'h1, h2 {\n  font-weight: bold;\n}',
 3,
 'Group selectors by separating them with a comma.', 'Agrupa los selectores separándolos con una coma.',
 'h1, h2 { ... } targets both elements at once.', 'h1, h2 { ... } apunta a ambos elementos a la vez.',
 'h1, h2 { font-weight: bold; }', 'h1, h2 { font-weight: bold; }',
 20, 3, now()),

-- 37. selectors
(gen_random_uuid(),
 'Hover Pseudo-class', 'Pseudo-clase Hover',
 'Change the background color of buttons to darkblue when hovered.',
 'Cambia el color de fondo de los botones a darkblue al pasar el cursor.',
 'html_css', 2, 'selectors',
 'button:___ {\n  background-color: darkblue;\n}',
 'button:hover {\n  background-color: darkblue;\n}',
 3,
 'Pseudo-classes describe element states using a colon.', 'Las pseudo-clases describen estados de elementos usando dos puntos.',
 'The hover state triggers when the mouse is over the element.', 'El estado hover se activa cuando el ratón está sobre el elemento.',
 'button:hover { background-color: darkblue; }', 'button:hover { background-color: darkblue; }',
 20, 3, now()),

-- 38. flexbox
(gen_random_uuid(),
 'Enable Flexbox', 'Activar Flexbox',
 'Make the .container element a flex container.',
 'Haz que el elemento .container sea un contenedor flex.',
 'html_css', 2, 'flexbox',
 '.container {\n  ___: flex;\n}',
 '.container {\n  display: flex;\n}',
 3,
 'Flexbox is activated by setting the display property.', 'Flexbox se activa estableciendo la propiedad display.',
 'Use display: flex on the parent container.', 'Usa display: flex en el contenedor padre.',
 'display: flex;', 'display: flex;',
 20, 3, now()),

-- 39. flexbox
(gen_random_uuid(),
 'Flex Direction Column', 'Dirección Flex en Columna',
 'Make the flex items inside .stack flow in a column (top to bottom).',
 'Haz que los elementos flex dentro de .stack fluyan en columna (de arriba a abajo).',
 'html_css', 2, 'flexbox',
 '.stack {\n  display: flex;\n  ___: column;\n}',
 '.stack {\n  display: flex;\n  flex-direction: column;\n}',
 3,
 'By default, flex items flow in a row. Change the axis with flex-direction.', 'Por defecto, los elementos flex fluyen en fila. Cambia el eje con flex-direction.',
 'Use flex-direction: column for vertical stacking.', 'Usa flex-direction: column para apilar verticalmente.',
 'flex-direction: column;', 'flex-direction: column;',
 20, 3, now()),

-- 40. variables
(gen_random_uuid(),
 'CSS Custom Property (Variable)', 'Propiedad Personalizada CSS (Variable)',
 'Declare a CSS variable --primary-color with value #3498db on :root, then use it on h1.',
 'Declara una variable CSS --primary-color con valor #3498db en :root, luego úsala en h1.',
 'html_css', 2, 'variables',
 ':root {\n  ___: #3498db;\n}\nh1 {\n  color: ___(--primary-color);\n}',
 ':root {\n  --primary-color: #3498db;\n}\nh1 {\n  color: var(--primary-color);\n}',
 3,
 'CSS variables are declared with -- prefix and accessed with var().', 'Las variables CSS se declaran con prefijo -- y se acceden con var().',
 'Declare on :root for global scope, use var(--name) to reference.', 'Declara en :root para alcance global, usa var(--name) para referenciar.',
 '--primary-color: #3498db; ... color: var(--primary-color);', '--primary-color: #3498db; ... color: var(--primary-color);',
 20, 3, now()),

-- 41. transitions
(gen_random_uuid(),
 'CSS Transition', 'Transición CSS',
 'Add a 0.3s ease transition on the background-color of .btn.',
 'Agrega una transición de 0.3s ease en el background-color de .btn.',
 'html_css', 2, 'transitions',
 '.btn {\n  background-color: blue;\n  ___: background-color 0.3s ease;\n}',
 '.btn {\n  background-color: blue;\n  transition: background-color 0.3s ease;\n}',
 3,
 'The transition property animates property changes smoothly.', 'La propiedad transition anima los cambios de propiedades de forma suave.',
 'Syntax: transition: property duration timing-function;', 'Sintaxis: transition: propiedad duración función-de-tiempo;',
 'transition: background-color 0.3s ease;', 'transition: background-color 0.3s ease;',
 20, 3, now()),

-- 42. responsive design
(gen_random_uuid(),
 'Viewport Meta Tag', 'Meta Etiqueta Viewport',
 'Add the viewport meta tag to make a page responsive on mobile devices.',
 'Agrega la meta etiqueta viewport para hacer que una página sea responsiva en dispositivos móviles.',
 'html_css', 2, 'responsive design',
 '<meta name="viewport" content="___=device-width, initial-scale=___">',
 '<meta name="viewport" content="width=device-width, initial-scale=1">',
 3,
 'The viewport meta tag controls how the page is scaled on mobile.', 'La meta etiqueta viewport controla cómo se escala la página en móviles.',
 'Set width=device-width and initial-scale=1 for proper scaling.', 'Establece width=device-width e initial-scale=1 para un escalado correcto.',
 'content="width=device-width, initial-scale=1"', 'content="width=device-width, initial-scale=1"',
 20, 3, now()),

-- 43. accessibility
(gen_random_uuid(),
 'ARIA Label', 'Etiqueta ARIA',
 'Add an aria-label to a button that only contains an icon, describing it as "Close menu".',
 'Agrega un aria-label a un botón que solo contiene un icono, describiéndolo como "Close menu".',
 'html_css', 2, 'accessibility',
 '<button ___="Close menu">&#x2715;</button>',
 '<button aria-label="Close menu">&#x2715;</button>',
 3,
 'ARIA attributes provide accessibility information to screen readers.', 'Los atributos ARIA proporcionan información de accesibilidad a los lectores de pantalla.',
 'aria-label provides a text description for elements without visible text.', 'aria-label proporciona una descripción de texto para elementos sin texto visible.',
 'aria-label="Close menu"', 'aria-label="Close menu"',
 20, 3, now()),

-- 44. selectors
(gen_random_uuid(),
 'Child Combinator', 'Combinador de Hijo Directo',
 'Write a CSS rule that targets only direct <li> children of a <ul> (not nested ones).',
 'Escribe una regla CSS que apunte solo a los hijos directos <li> de un <ul> (no los anidados).',
 'html_css', 2, 'selectors',
 'ul ___ li {\n  color: teal;\n}',
 'ul > li {\n  color: teal;\n}',
 3,
 'The child combinator selects only direct children, not deeper descendants.', 'El combinador de hijo selecciona solo hijos directos, no descendientes más profundos.',
 'Use > between the parent and child selectors.', 'Usa > entre los selectores de padre e hijo.',
 'ul > li { color: teal; }', 'ul > li { color: teal; }',
 20, 3, now()),

-- 45. pseudo-elements
(gen_random_uuid(),
 'Before Pseudo-element', 'Pseudo-elemento Before',
 'Add a decorative star "★" before every h3 element using CSS.',
 'Agrega una estrella decorativa "★" antes de cada elemento h3 usando CSS.',
 'html_css', 2, 'pseudo-elements',
 'h3::___ {\n  content: "★ ";\n}',
 'h3::before {\n  content: "★ ";\n}',
 3,
 'Pseudo-elements use :: (double colon) syntax.', 'Los pseudo-elementos usan :: (doble dos puntos) como sintaxis.',
 '::before inserts content before an element; requires the content property.', '::before inserta contenido antes de un elemento; requiere la propiedad content.',
 'h3::before { content: "★ "; }', 'h3::before { content: "★ "; }',
 20, 3, now()),

-- 46. selectors
(gen_random_uuid(),
 'Attribute Selector', 'Selector de Atributo',
 'Style all input elements of type "email" with a blue border.',
 'Estiliza todos los elementos input de tipo "email" con un borde azul.',
 'html_css', 2, 'selectors',
 'input[type=___] {\n  border: 1px solid blue;\n}',
 'input[type="email"] {\n  border: 1px solid blue;\n}',
 3,
 'Attribute selectors use square brackets to target specific attribute values.', 'Los selectores de atributo usan corchetes para apuntar a valores de atributo específicos.',
 'Syntax: element[attribute="value"]', 'Sintaxis: elemento[atributo="valor"]',
 'input[type="email"] { border: 1px solid blue; }', 'input[type="email"] { border: 1px solid blue; }',
 20, 3, now()),

-- 47. selectors
(gen_random_uuid(),
 'Focus Pseudo-class', 'Pseudo-clase Focus',
 'Add a blue outline to text inputs when they are focused.',
 'Agrega un contorno azul a las entradas de texto cuando están enfocadas.',
 'html_css', 2, 'selectors',
 'input[type="text"]:___ {\n  outline: 2px solid blue;\n}',
 'input[type="text"]:focus {\n  outline: 2px solid blue;\n}',
 3,
 'The :focus pseudo-class targets the currently focused element.', 'La pseudo-clase :focus apunta al elemento actualmente enfocado.',
 'Use :focus to style form fields when clicked or tabbed into.', 'Usa :focus para estilizar campos de formulario cuando se hace clic o se navega con Tab.',
 'input[type="text"]:focus { outline: 2px solid blue; }', 'input[type="text"]:focus { outline: 2px solid blue; }',
 20, 3, now()),

-- 48. selectors
(gen_random_uuid(),
 'nth-child Selector', 'Selector nth-child',
 'Style every even table row with a light gray background.',
 'Estiliza cada fila par de la tabla con un fondo gris claro.',
 'html_css', 2, 'selectors',
 'tr:nth-child(___) {\n  background-color: #f2f2f2;\n}',
 'tr:nth-child(even) {\n  background-color: #f2f2f2;\n}',
 3,
 ':nth-child() accepts keywords "even" and "odd" or a formula like 2n.', ':nth-child() acepta palabras clave "even" y "odd" o una fórmula como 2n.',
 'Use "even" to target 2nd, 4th, 6th... rows.', 'Usa "even" para apuntar a las filas 2ª, 4ª, 6ª...',
 'tr:nth-child(even) { background-color: #f2f2f2; }', 'tr:nth-child(even) { background-color: #f2f2f2; }',
 20, 3, now()),

-- 49. responsive design
(gen_random_uuid(),
 'Percentage Width', 'Ancho en Porcentaje',
 'Make an image responsive by setting its width to 100% and height to auto.',
 'Haz que una imagen sea responsiva estableciendo su ancho al 100% y su alto en auto.',
 'html_css', 2, 'responsive design',
 'img {\n  ___: 100%;\n  ___: auto;\n}',
 'img {\n  width: 100%;\n  height: auto;\n}',
 3,
 'Percentage widths are relative to the parent container.', 'Los anchos en porcentaje son relativos al contenedor padre.',
 'height: auto maintains the original aspect ratio.', 'height: auto mantiene la relación de aspecto original.',
 'width: 100%;\n  height: auto;', 'width: 100%;\n  height: auto;',
 20, 3, now()),

-- 50. selectors
(gen_random_uuid(),
 'CSS Box Shadow', 'Sombra de Caja CSS',
 'Add a box shadow of 2px horizontal, 4px vertical, 8px blur, color rgba(0,0,0,0.2) to .card.',
 'Agrega una sombra de caja de 2px horizontal, 4px vertical, 8px desenfoque, color rgba(0,0,0,0.2) a .card.',
 'html_css', 2, 'selectors',
 '.card {\n  ___: 2px 4px 8px rgba(0,0,0,0.2);\n}',
 '.card {\n  box-shadow: 2px 4px 8px rgba(0,0,0,0.2);\n}',
 3,
 'box-shadow takes: x-offset y-offset blur-radius color.', 'box-shadow recibe: desplazamiento-x desplazamiento-y radio-desenfoque color.',
 'The property name is "box-shadow".', 'El nombre de la propiedad es "box-shadow".',
 'box-shadow: 2px 4px 8px rgba(0,0,0,0.2);', 'box-shadow: 2px 4px 8px rgba(0,0,0,0.2);',
 20, 3, now()),

-- ============================================================
-- DIFFICULTY 3 — 25 exercises (points=30, penalty=5)
-- ============================================================

-- 51. flexbox
(gen_random_uuid(),
 'Centering with Flexbox', 'Centrar con Flexbox',
 'Use flexbox to center a single child element both horizontally and vertically inside .wrapper.',
 'Usa flexbox para centrar un elemento hijo tanto horizontal como verticalmente dentro de .wrapper.',
 'html_css', 3, 'flexbox',
 '.wrapper {\n  display: flex;\n  ___: center;\n  ___: center;\n}',
 '.wrapper {\n  display: flex;\n  justify-content: center;\n  align-items: center;\n}',
 3,
 'Two properties control alignment: one for the main axis, one for the cross axis.', 'Dos propiedades controlan la alineación: una para el eje principal, otra para el eje cruzado.',
 'justify-content centers along the main axis; align-items along the cross axis.', 'justify-content centra a lo largo del eje principal; align-items a lo largo del eje cruzado.',
 'justify-content: center;\n  align-items: center;', 'justify-content: center;\n  align-items: center;',
 30, 5, now()),

-- 52. flexbox
(gen_random_uuid(),
 'Flex Wrap', 'Envoltura Flex',
 'Allow flex items inside .gallery to wrap onto multiple lines when they overflow.',
 'Permite que los elementos flex dentro de .gallery se envuelvan en múltiples líneas cuando desbordan.',
 'html_css', 3, 'flexbox',
 '.gallery {\n  display: flex;\n  ___: wrap;\n}',
 '.gallery {\n  display: flex;\n  flex-wrap: wrap;\n}',
 3,
 'By default, flex items try to fit on one line.', 'Por defecto, los elementos flex intentan caber en una línea.',
 'flex-wrap: wrap allows items to flow to new rows.', 'flex-wrap: wrap permite que los elementos fluyan a nuevas filas.',
 'flex-wrap: wrap;', 'flex-wrap: wrap;',
 30, 5, now()),

-- 53. flexbox
(gen_random_uuid(),
 'Flex Grow', 'Flex Grow',
 'Make the .main-content element take up all remaining space in a flex row next to a .sidebar.',
 'Haz que el elemento .main-content ocupe todo el espacio restante en una fila flex junto a un .sidebar.',
 'html_css', 3, 'flexbox',
 '.main-content {\n  ___: 1;\n}',
 '.main-content {\n  flex-grow: 1;\n}',
 3,
 'flex-grow determines how much remaining space an item claims.', 'flex-grow determina cuánto espacio restante reclama un elemento.',
 'A value of 1 means the item takes all available remaining space.', 'Un valor de 1 significa que el elemento toma todo el espacio disponible restante.',
 'flex-grow: 1;', 'flex-grow: 1;',
 30, 5, now()),

-- 54. grid
(gen_random_uuid(),
 'Enable CSS Grid', 'Activar CSS Grid',
 'Create a 3-column grid layout on .grid-container using equal-width columns.',
 'Crea un diseño de cuadrícula de 3 columnas en .grid-container usando columnas de igual ancho.',
 'html_css', 3, 'grid',
 '.grid-container {\n  display: ___;\n  grid-template-columns: ___ ___ ___;\n}',
 '.grid-container {\n  display: grid;\n  grid-template-columns: 1fr 1fr 1fr;\n}',
 3,
 'CSS Grid is activated with display: grid.', 'CSS Grid se activa con display: grid.',
 'Use the "fr" unit to create equal-width flexible columns.', 'Usa la unidad "fr" para crear columnas flexibles de igual ancho.',
 'display: grid;\n  grid-template-columns: 1fr 1fr 1fr;', 'display: grid;\n  grid-template-columns: 1fr 1fr 1fr;',
 30, 5, now()),

-- 55. grid
(gen_random_uuid(),
 'Grid Gap', 'Espacio de Cuadrícula',
 'Add 20px gap between all grid items in .grid-container.',
 'Agrega 20px de espacio entre todos los elementos de cuadrícula en .grid-container.',
 'html_css', 3, 'grid',
 '.grid-container {\n  display: grid;\n  grid-template-columns: 1fr 1fr;\n  ___: 20px;\n}',
 '.grid-container {\n  display: grid;\n  grid-template-columns: 1fr 1fr;\n  gap: 20px;\n}',
 3,
 'The gap property controls space between grid items.', 'La propiedad gap controla el espacio entre los elementos de la cuadrícula.',
 'A single value applies to both rows and columns.', 'Un solo valor se aplica tanto a filas como a columnas.',
 'gap: 20px;', 'gap: 20px;',
 30, 5, now()),

-- 56. grid
(gen_random_uuid(),
 'Grid Column Span', 'Expansión de Columna en Cuadrícula',
 'Make the .hero element span across all 3 columns of its grid.',
 'Haz que el elemento .hero se extienda por las 3 columnas de su cuadrícula.',
 'html_css', 3, 'grid',
 '.hero {\n  grid-column: 1 / ___;\n}',
 '.hero {\n  grid-column: 1 / 4;\n}',
 3,
 'grid-column shorthand sets start and end grid lines.', 'El shorthand grid-column establece las líneas de cuadrícula de inicio y fin.',
 'In a 3-column grid, there are 4 grid lines (1, 2, 3, 4).', 'En una cuadrícula de 3 columnas, hay 4 líneas de cuadrícula (1, 2, 3, 4).',
 'grid-column: 1 / 4;', 'grid-column: 1 / 4;',
 30, 5, now()),

-- 57. media queries
(gen_random_uuid(),
 'Mobile-First Media Query', 'Media Query Mobile-First',
 'Write a media query that applies styles only when the viewport is at least 768px wide.',
 'Escribe una media query que aplique estilos solo cuando el viewport tenga al menos 768px de ancho.',
 'html_css', 3, 'media queries',
 '@___ (___-width: 768px) {\n  .container {\n    max-width: 1200px;\n  }\n}',
 '@media (min-width: 768px) {\n  .container {\n    max-width: 1200px;\n  }\n}',
 3,
 'Media queries use @media followed by a condition in parentheses.', 'Las media queries usan @media seguido de una condición entre paréntesis.',
 'min-width targets screens equal to or larger than the specified width.', 'min-width apunta a pantallas iguales o más grandes que el ancho especificado.',
 '@media (min-width: 768px) { ... }', '@media (min-width: 768px) { ... }',
 30, 5, now()),

-- 58. media queries
(gen_random_uuid(),
 'Print Media Query', 'Media Query para Impresión',
 'Write a media query that hides the .nav element when the page is printed.',
 'Escribe una media query que oculte el elemento .nav cuando se imprime la página.',
 'html_css', 3, 'media queries',
 '@media ___ {\n  .nav {\n    display: none;\n  }\n}',
 '@media print {\n  .nav {\n    display: none;\n  }\n}',
 3,
 'Media queries can target specific media types like screen, print, or all.', 'Las media queries pueden apuntar a tipos de medios específicos como screen, print o all.',
 'Use @media print to target printed pages.', 'Usa @media print para apuntar a páginas impresas.',
 '@media print { .nav { display: none; } }', '@media print { .nav { display: none; } }',
 30, 5, now()),

-- 59. transforms
(gen_random_uuid(),
 'CSS Rotate Transform', 'Transformación de Rotación CSS',
 'Rotate the .icon element 45 degrees clockwise on hover.',
 'Rota el elemento .icon 45 grados en sentido horario al pasar el cursor.',
 'html_css', 3, 'transforms',
 '.icon:hover {\n  ___: rotate(45deg);\n}',
 '.icon:hover {\n  transform: rotate(45deg);\n}',
 3,
 'CSS transforms apply visual transformations without affecting layout.', 'Las transformaciones CSS aplican transformaciones visuales sin afectar el diseño.',
 'Use transform: rotate(Ndeg) where N is the angle in degrees.', 'Usa transform: rotate(Ngr) donde N es el ángulo en grados.',
 'transform: rotate(45deg);', 'transform: rotate(45deg);',
 30, 5, now()),

-- 60. transforms
(gen_random_uuid(),
 'CSS Scale Transform', 'Transformación de Escala CSS',
 'Scale up the .card element to 1.05 times its size on hover.',
 'Escala el elemento .card a 1.05 veces su tamaño al pasar el cursor.',
 'html_css', 3, 'transforms',
 '.card:hover {\n  ___: scale(1.05);\n}',
 '.card:hover {\n  transform: scale(1.05);\n}',
 3,
 'scale() takes a number where 1 = original size, 2 = double size.', 'scale() recibe un número donde 1 = tamaño original, 2 = doble de tamaño.',
 'Use transform: scale(1.05) for a subtle grow effect.', 'Usa transform: scale(1.05) para un efecto de crecimiento sutil.',
 'transform: scale(1.05);', 'transform: scale(1.05);',
 30, 5, now()),

-- 61. transforms
(gen_random_uuid(),
 'CSS Translate Transform', 'Transformación de Traslación CSS',
 'Move the .tooltip element 10px to the right and 5px upward using transform.',
 'Mueve el elemento .tooltip 10px a la derecha y 5px hacia arriba usando transform.',
 'html_css', 3, 'transforms',
 '.tooltip {\n  ___: translate(10px, -5px);\n}',
 '.tooltip {\n  transform: translate(10px, -5px);\n}',
 3,
 'translate(x, y) moves an element along the X and Y axes.', 'translate(x, y) mueve un elemento a lo largo de los ejes X e Y.',
 'Positive X moves right; negative Y moves up.', 'X positivo mueve a la derecha; Y negativo mueve hacia arriba.',
 'transform: translate(10px, -5px);', 'transform: translate(10px, -5px);',
 30, 5, now()),

-- 62. animations
(gen_random_uuid(),
 'CSS Keyframe Animation', 'Animación con Keyframes CSS',
 'Define a keyframe animation named "fadeIn" that goes from opacity 0 to opacity 1.',
 'Define una animación con keyframes llamada "fadeIn" que va de opacidad 0 a opacidad 1.',
 'html_css', 3, 'animations',
 '@___ fadeIn {\n  from { opacity: 0; }\n  ___ { opacity: 1; }\n}',
 '@keyframes fadeIn {\n  from { opacity: 0; }\n  to { opacity: 1; }\n}',
 3,
 'CSS keyframe animations are defined with @keyframes.', 'Las animaciones con keyframes CSS se definen con @keyframes.',
 'Use "from" and "to" for start and end states.', 'Usa "from" y "to" para los estados inicial y final.',
 '@keyframes fadeIn { from { opacity: 0; } to { opacity: 1; } }', '@keyframes fadeIn { from { opacity: 0; } to { opacity: 1; } }',
 30, 5, now()),

-- 63. animations
(gen_random_uuid(),
 'Apply CSS Animation', 'Aplicar Animación CSS',
 'Apply the "fadeIn" animation to .modal with duration 0.5s and ease-in timing.',
 'Aplica la animación "fadeIn" a .modal con duración 0.5s y temporización ease-in.',
 'html_css', 3, 'animations',
 '.modal {\n  ___: fadeIn 0.5s ease-in;\n}',
 '.modal {\n  animation: fadeIn 0.5s ease-in;\n}',
 3,
 'Use the animation shorthand to apply a named keyframe animation.', 'Usa el shorthand animation para aplicar una animación con nombre.',
 'Syntax: animation: name duration timing-function;', 'Sintaxis: animation: nombre duración función-de-tiempo;',
 'animation: fadeIn 0.5s ease-in;', 'animation: fadeIn 0.5s ease-in;',
 30, 5, now()),

-- 64. pseudo-elements
(gen_random_uuid(),
 'After Pseudo-element', 'Pseudo-elemento After',
 'Add a red asterisk "* " after every label element using CSS to indicate required fields.',
 'Agrega un asterisco rojo "* " después de cada elemento label usando CSS para indicar campos requeridos.',
 'html_css', 3, 'pseudo-elements',
 'label::___ {\n  content: " *";\n  color: red;\n}',
 'label::after {\n  content: " *";\n  color: red;\n}',
 3,
 '::after inserts generated content after an element''s content.', '::after inserta contenido generado después del contenido de un elemento.',
 'Always set the content property, even if empty ("").', 'Siempre establece la propiedad content, aunque sea vacía ("").',
 'label::after { content: " *"; color: red; }', 'label::after { content: " *"; color: red; }',
 30, 5, now()),

-- 65. pseudo-elements
(gen_random_uuid(),
 'First Line Pseudo-element', 'Pseudo-elemento First Line',
 'Make the first line of every paragraph bold using a CSS pseudo-element.',
 'Pon en negrita la primera línea de cada párrafo usando un pseudo-elemento CSS.',
 'html_css', 3, 'pseudo-elements',
 'p::___ {\n  font-weight: bold;\n}',
 'p::first-line {\n  font-weight: bold;\n}',
 3,
 'CSS has a pseudo-element that targets only the first rendered line.', 'CSS tiene un pseudo-elemento que apunta solo a la primera línea renderizada.',
 'The pseudo-element is ::first-line.', 'El pseudo-elemento es ::first-line.',
 'p::first-line { font-weight: bold; }', 'p::first-line { font-weight: bold; }',
 30, 5, now()),

-- 66. accessibility
(gen_random_uuid(),
 'ARIA Role Landmark', 'Rol ARIA de Punto de Referencia',
 'Add the correct ARIA role to a div that functions as the main navigation.',
 'Agrega el rol ARIA correcto a un div que funciona como navegación principal.',
 'html_css', 3, 'accessibility',
 '<div ___="navigation">\n  <a href="/">Home</a>\n</div>',
 '<div role="navigation">\n  <a href="/">Home</a>\n</div>',
 3,
 'ARIA roles communicate element purpose to assistive technologies.', 'Los roles ARIA comunican el propósito del elemento a las tecnologías de asistencia.',
 'Use role="navigation" on non-semantic elements used as nav areas.', 'Usa role="navigation" en elementos no semánticos usados como áreas de navegación.',
 'role="navigation"', 'role="navigation"',
 30, 5, now()),

-- 67. accessibility
(gen_random_uuid(),
 'Skip Navigation Link', 'Enlace de Saltar Navegación',
 'Add a visually-hidden skip link that becomes visible on focus, allowing users to jump to main content.',
 'Agrega un enlace de saltar oculto visualmente que se vuelve visible al enfocarse, permitiendo saltar al contenido principal.',
 'html_css', 3, 'accessibility',
 '<a href="#main-content" class="skip-link">Skip to main content</a>\n\n.skip-link {\n  position: absolute;\n  ___: -9999px;\n}\n.skip-link:focus {\n  ___: 0;\n}',
 '<a href="#main-content" class="skip-link">Skip to main content</a>\n\n.skip-link {\n  position: absolute;\n  left: -9999px;\n}\n.skip-link:focus {\n  left: 0;\n}',
 3,
 'Skip links help keyboard users bypass repetitive navigation.', 'Los enlaces de saltar ayudan a los usuarios de teclado a omitir la navegación repetitiva.',
 'Hide offscreen with left: -9999px, bring back on :focus.', 'Oculta fuera de pantalla con left: -9999px, tráelo de vuelta en :focus.',
 'left: -9999px; ... left: 0;', 'left: -9999px; ... left: 0;',
 30, 5, now()),

-- 68. variables
(gen_random_uuid(),
 'CSS Variable Fallback', 'Fallback de Variable CSS',
 'Use the CSS variable --btn-color with a fallback value of "steelblue" if the variable is not defined.',
 'Usa la variable CSS --btn-color con un valor de fallback de "steelblue" si la variable no está definida.',
 'html_css', 3, 'variables',
 '.btn {\n  background-color: var(___, steelblue);\n}',
 '.btn {\n  background-color: var(--btn-color, steelblue);\n}',
 3,
 'var() accepts an optional second argument as a fallback.', 'var() acepta un segundo argumento opcional como fallback.',
 'Syntax: var(--variable-name, fallback-value)', 'Sintaxis: var(--nombre-variable, valor-fallback)',
 'var(--btn-color, steelblue)', 'var(--btn-color, steelblue)',
 30, 5, now()),

-- 69. responsive design
(gen_random_uuid(),
 'Responsive Typography with clamp()', 'Tipografía Responsiva con clamp()',
 'Set the font-size of h1 to fluidly scale between 1.5rem and 3rem, with a preferred value of 5vw.',
 'Establece el font-size de h1 para que escale fluidamente entre 1.5rem y 3rem, con un valor preferido de 5vw.',
 'html_css', 3, 'responsive design',
 'h1 {\n  font-size: ___(1.5rem, 5vw, 3rem);\n}',
 'h1 {\n  font-size: clamp(1.5rem, 5vw, 3rem);\n}',
 3,
 'clamp(min, preferred, max) creates fluid values that scale with viewport.', 'clamp(min, preferido, max) crea valores fluidos que escalan con el viewport.',
 'The middle argument is the preferred value; the others are the limits.', 'El argumento del medio es el valor preferido; los otros son los límites.',
 'font-size: clamp(1.5rem, 5vw, 3rem);', 'font-size: clamp(1.5rem, 5vw, 3rem);',
 30, 5, now()),

-- 70. selectors
(gen_random_uuid(),
 'CSS :not() Selector', 'Selector CSS :not()',
 'Apply a bottom border to all list items except the last one.',
 'Aplica un borde inferior a todos los elementos de lista excepto al último.',
 'html_css', 3, 'selectors',
 'li:not(:___-child) {\n  border-bottom: 1px solid #ccc;\n}',
 'li:not(:last-child) {\n  border-bottom: 1px solid #ccc;\n}',
 3,
 ':not() negates a selector — it targets elements that do NOT match.', ':not() niega un selector: apunta a elementos que NO coinciden.',
 ':last-child selects the last item; :not() inverts that.', ':last-child selecciona el último elemento; :not() lo invierte.',
 'li:not(:last-child) { border-bottom: 1px solid #ccc; }', 'li:not(:last-child) { border-bottom: 1px solid #ccc; }',
 30, 5, now()),

-- 71. forms
(gen_random_uuid(),
 'Required Form Field', 'Campo de Formulario Requerido',
 'Add HTML5 validation to an email input so it is required and must be a valid email.',
 'Agrega validación HTML5 a una entrada de email para que sea obligatoria y deba ser un email válido.',
 'html_css', 3, 'forms',
 '<input type="___" name="email" ___>',
 '<input type="email" name="email" required>',
 3,
 'HTML5 provides built-in form validation via input types and attributes.', 'HTML5 proporciona validación de formularios incorporada mediante tipos de entrada y atributos.',
 'The "required" attribute prevents submission if the field is empty.', 'El atributo "required" evita el envío si el campo está vacío.',
 'type="email" ... required', 'type="email" ... required',
 30, 5, now()),

-- 72. forms
(gen_random_uuid(),
 'Textarea Element', 'Elemento Textarea',
 'Create a textarea with name "message", 5 rows, 40 columns, and placeholder "Type your message...".',
 'Crea un textarea con nombre "message", 5 filas, 40 columnas y placeholder "Type your message...".',
 'html_css', 3, 'forms',
 '<___ name="message" rows="___" cols="___" placeholder="Type your message..."></___>',
 '<textarea name="message" rows="5" cols="40" placeholder="Type your message..."></textarea>',
 3,
 'textarea is a multi-line text input element.', 'textarea es un elemento de entrada de texto de varias líneas.',
 'Use rows and cols to set default dimensions.', 'Usa rows y cols para establecer las dimensiones por defecto.',
 '<textarea name="message" rows="5" cols="40">', '<textarea name="message" rows="5" cols="40">',
 30, 5, now()),

-- 73. tables
(gen_random_uuid(),
 'Table colspan', 'colspan en Tabla',
 'Create a table cell that spans 2 columns using the colspan attribute.',
 'Crea una celda de tabla que abarque 2 columnas usando el atributo colspan.',
 'html_css', 3, 'tables',
 '<td ___="2">Merged Cell</td>',
 '<td colspan="2">Merged Cell</td>',
 3,
 'colspan merges cells horizontally across multiple columns.', 'colspan fusiona celdas horizontalmente a través de múltiples columnas.',
 'The value indicates how many columns the cell should span.', 'El valor indica cuántas columnas debe abarcar la celda.',
 'colspan="2"', 'colspan="2"',
 30, 5, now()),

-- 74. semantic HTML
(gen_random_uuid(),
 'Article and Section Elements', 'Elementos Article y Section',
 'Wrap a blog post inside an <article>, and two sections inside it using <section>.',
 'Envuelve una entrada de blog dentro de un <article>, y dos secciones dentro de él usando <section>.',
 'html_css', 3, 'semantic HTML',
 '<___>\n  <___>\n    <h2>Intro</h2>\n    <p>Text...</p>\n  </___>\n  <___>\n    <h2>Details</h2>\n    <p>More text...</p>\n  </___>\n</___>',
 '<article>\n  <section>\n    <h2>Intro</h2>\n    <p>Text...</p>\n  </section>\n  <section>\n    <h2>Details</h2>\n    <p>More text...</p>\n  </section>\n</article>',
 3,
 'article is for self-contained content; section groups related content.', 'article es para contenido independiente; section agrupa contenido relacionado.',
 'An article can contain multiple sections.', 'Un article puede contener múltiples secciones.',
 '<article> ... <section> ... </section> ... </article>', '<article> ... <section> ... </section> ... </article>',
 30, 5, now()),

-- 75. animations
(gen_random_uuid(),
 'Infinite Animation Loop', 'Bucle de Animación Infinito',
 'Apply the "spin" keyframe animation to .loader: 1s duration, linear timing, infinite loop.',
 'Aplica la animación con keyframes "spin" a .loader: duración 1s, temporización lineal, bucle infinito.',
 'html_css', 3, 'animations',
 '.loader {\n  animation: spin 1s linear ___;\n}',
 '.loader {\n  animation: spin 1s linear infinite;\n}',
 3,
 'Add a fourth value to the animation shorthand to control iteration count.', 'Agrega un cuarto valor al shorthand animation para controlar el número de iteraciones.',
 'Use "infinite" to loop the animation forever.', 'Usa "infinite" para que la animación se repita indefinidamente.',
 'animation: spin 1s linear infinite;', 'animation: spin 1s linear infinite;',
 30, 5, now()),

-- ============================================================
-- DIFFICULTY 4 — 15 exercises (points=50, penalty=10)
-- ============================================================

-- 76. grid
(gen_random_uuid(),
 'CSS Grid Template Areas', 'Áreas de Plantilla de Cuadrícula CSS',
 'Define a grid layout with named areas: header spanning full width, sidebar on left, content on right, footer spanning full width.',
 'Define un diseño de cuadrícula con áreas nombradas: header abarcando todo el ancho, sidebar a la izquierda, content a la derecha, footer abarcando todo el ancho.',
 'html_css', 4, 'grid',
 '.layout {\n  display: grid;\n  grid-template-columns: 200px 1fr;\n  grid-template-areas:\n    "___  ___"\n    "___  ___"\n    "___  ___";\n}',
 '.layout {\n  display: grid;\n  grid-template-columns: 200px 1fr;\n  grid-template-areas:\n    "header  header"\n    "sidebar content"\n    "footer  footer";\n}',
 3,
 'grid-template-areas assigns names to regions of the grid.', 'grid-template-areas asigna nombres a regiones de la cuadrícula.',
 'Each string in quotes represents a row; repeated names span multiple cells.', 'Cada cadena entre comillas representa una fila; los nombres repetidos abarcan múltiples celdas.',
 '"header header" "sidebar content" "footer footer"', '"header header" "sidebar content" "footer footer"',
 50, 10, now()),

-- 77. grid
(gen_random_uuid(),
 'Place Item in Named Grid Area', 'Colocar Elemento en Área de Cuadrícula Nombrada',
 'Assign the .site-header element to the "header" named grid area.',
 'Asigna el elemento .site-header al área de cuadrícula nombrada "header".',
 'html_css', 4, 'grid',
 '.site-header {\n  ___: header;\n}',
 '.site-header {\n  grid-area: header;\n}',
 3,
 'Use grid-area on a child element to assign it to a named template area.', 'Usa grid-area en un elemento hijo para asignarlo a un área de plantilla nombrada.',
 'The name must match one defined in grid-template-areas.', 'El nombre debe coincidir con uno definido en grid-template-areas.',
 'grid-area: header;', 'grid-area: header;',
 50, 10, now()),

-- 78. animations
(gen_random_uuid(),
 'CSS Pulse Animation', 'Animación de Pulso CSS',
 'Create a "pulse" keyframe animation: at 0% scale(1), at 50% scale(1.1), at 100% scale(1). Apply it to .badge with 1.5s ease-in-out infinite.',
 'Crea una animación con keyframes "pulse": al 0% scale(1), al 50% scale(1.1), al 100% scale(1). Aplícala a .badge con 1.5s ease-in-out infinite.',
 'html_css', 4, 'animations',
 '@keyframes pulse {\n  ___% { transform: scale(1); }\n  ___% { transform: scale(1.1); }\n  ___% { transform: scale(1); }\n}\n.badge {\n  animation: pulse 1.5s ___ infinite;\n}',
 '@keyframes pulse {\n  0% { transform: scale(1); }\n  50% { transform: scale(1.1); }\n  100% { transform: scale(1); }\n}\n.badge {\n  animation: pulse 1.5s ease-in-out infinite;\n}',
 3,
 'Keyframes can use percentage values to define intermediate states.', 'Los keyframes pueden usar valores en porcentaje para definir estados intermedios.',
 '0% is the start, 100% is the end, and you can add stops in between.', '0% es el inicio, 100% es el final, y puedes agregar paradas intermedias.',
 '0% ... 50% ... 100% ... ease-in-out', '0% ... 50% ... 100% ... ease-in-out',
 50, 10, now()),

-- 79. flexbox
(gen_random_uuid(),
 'Sticky Footer with Flexbox', 'Pie de Página Fijo con Flexbox',
 'Use flexbox on the body to push the footer to the bottom of the viewport even when content is short.',
 'Usa flexbox en el body para empujar el footer al fondo del viewport incluso cuando el contenido es corto.',
 'html_css', 4, 'flexbox',
 'body {\n  display: flex;\n  flex-direction: column;\n  min-height: ___;\n}\nfooter {\n  margin-top: ___;\n}',
 'body {\n  display: flex;\n  flex-direction: column;\n  min-height: 100vh;\n}\nfooter {\n  margin-top: auto;\n}',
 3,
 'Set min-height: 100vh on the body to fill the full viewport height.', 'Establece min-height: 100vh en el body para llenar el alto completo del viewport.',
 'margin-top: auto on a flex child pushes it to the far end of the main axis.', 'margin-top: auto en un hijo flex lo empuja al extremo del eje principal.',
 'min-height: 100vh; ... margin-top: auto;', 'min-height: 100vh; ... margin-top: auto;',
 50, 10, now()),

-- 80. responsive design
(gen_random_uuid(),
 'Responsive Grid with auto-fill', 'Cuadrícula Responsiva con auto-fill',
 'Create a responsive grid where columns are at least 250px wide and fill the row using repeat() with auto-fill.',
 'Crea una cuadrícula responsiva donde las columnas tengan al menos 250px de ancho y llenen la fila usando repeat() con auto-fill.',
 'html_css', 4, 'responsive design',
 '.grid {\n  display: grid;\n  grid-template-columns: repeat(___, minmax(___, 1fr));\n}',
 '.grid {\n  display: grid;\n  grid-template-columns: repeat(auto-fill, minmax(250px, 1fr));\n}',
 3,
 'auto-fill creates as many columns as fit in the available width.', 'auto-fill crea tantas columnas como quepan en el ancho disponible.',
 'minmax(250px, 1fr) means: at least 250px, but grow to fill space.', 'minmax(250px, 1fr) significa: al menos 250px, pero crece para llenar el espacio.',
 'repeat(auto-fill, minmax(250px, 1fr))', 'repeat(auto-fill, minmax(250px, 1fr))',
 50, 10, now()),

-- 81. accessibility
(gen_random_uuid(),
 'aria-expanded for Dropdown', 'aria-expanded para Menú Desplegable',
 'Add aria-expanded="false" to a button that controls a dropdown, and toggle it to "true" when the dropdown is open.',
 'Agrega aria-expanded="false" a un botón que controla un menú desplegable, y cámbialo a "true" cuando el menú esté abierto.',
 'html_css', 4, 'accessibility',
 '<button aria-expanded="___" aria-controls="dropdown-menu">Menu</button>\n<ul id="dropdown-menu" hidden>\n  <li>Item 1</li>\n</ul>',
 '<button aria-expanded="false" aria-controls="dropdown-menu">Menu</button>\n<ul id="dropdown-menu" hidden>\n  <li>Item 1</li>\n</ul>',
 3,
 'aria-expanded communicates the open/closed state of expandable elements.', 'aria-expanded comunica el estado abierto/cerrado de elementos expandibles.',
 'Start with "false" (closed), and JavaScript updates it to "true" when opened.', 'Empieza con "false" (cerrado), y JavaScript lo actualiza a "true" cuando se abre.',
 'aria-expanded="false"', 'aria-expanded="false"',
 50, 10, now()),

-- 82. variables
(gen_random_uuid(),
 'CSS Theme with Variables', 'Tema CSS con Variables',
 'Create a dark theme by overriding CSS variables: --bg to #1a1a1a and --text to #ffffff on a .dark-theme class.',
 'Crea un tema oscuro sobreescribiendo variables CSS: --bg a #1a1a1a y --text a #ffffff en una clase .dark-theme.',
 'html_css', 4, 'variables',
 ':root {\n  --bg: #ffffff;\n  --text: #000000;\n}\n.___ {\n  --bg: #1a1a1a;\n  --text: ___;\n}',
 ':root {\n  --bg: #ffffff;\n  --text: #000000;\n}\n.dark-theme {\n  --bg: #1a1a1a;\n  --text: #ffffff;\n}',
 3,
 'CSS variables can be overridden by re-declaring them on a more specific selector.', 'Las variables CSS pueden sobreescribirse redeclarándolas en un selector más específico.',
 'Applying .dark-theme to the body will cascade the new values to all children.', 'Aplicar .dark-theme al body propagará los nuevos valores a todos los hijos.',
 '.dark-theme { --bg: #1a1a1a; --text: #ffffff; }', '.dark-theme { --bg: #1a1a1a; --text: #ffffff; }',
 50, 10, now()),

-- 83. media queries
(gen_random_uuid(),
 'Combined Media Query Conditions', 'Condiciones de Media Query Combinadas',
 'Write a media query that targets landscape orientation on screens no wider than 768px.',
 'Escribe una media query que apunte a orientación horizontal en pantallas de no más de 768px de ancho.',
 'html_css', 4, 'media queries',
 '@media screen ___ (max-width: 768px) ___ (orientation: landscape) {\n  .hero { height: 50vh; }\n}',
 '@media screen and (max-width: 768px) and (orientation: landscape) {\n  .hero { height: 50vh; }\n}',
 3,
 'Use "and" to combine multiple media feature conditions.', 'Usa "and" para combinar múltiples condiciones de características de medios.',
 'orientation: landscape targets wider-than-tall screens.', 'orientation: landscape apunta a pantallas más anchas que altas.',
 '@media screen and (max-width: 768px) and (orientation: landscape)', '@media screen and (max-width: 768px) and (orientation: landscape)',
 50, 10, now()),

-- 84. selectors
(gen_random_uuid(),
 'Specificity: Inline vs Class vs Tag', 'Especificidad: Inline vs Clase vs Etiqueta',
 'Given three conflicting rules for a <p class="intro">, order them from highest to lowest specificity: tag rule, class rule, inline style.',
 'Dados tres reglas en conflicto para un <p class="intro">, ordénalos de mayor a menor especificidad: regla de etiqueta, regla de clase, estilo inline.',
 'html_css', 4, 'selectors',
 '/* Order from highest to lowest: */\n/* 1. ___ */\n/* 2. ___ */\n/* 3. ___ */',
 '/* Order from highest to lowest: */\n/* 1. inline style */\n/* 2. class rule */\n/* 3. tag rule */',
 3,
 'CSS specificity determines which rule wins when multiple rules target the same element.', 'La especificidad CSS determina qué regla gana cuando múltiples reglas apuntan al mismo elemento.',
 'Inline > ID > Class/Attribute > Tag in specificity order.', 'Inline > ID > Clase/Atributo > Etiqueta en orden de especificidad.',
 '1. inline style  2. class rule  3. tag rule', '1. inline style  2. class rule  3. tag rule',
 50, 10, now()),

-- 85. transforms
(gen_random_uuid(),
 'CSS 3D Perspective', 'Perspectiva 3D CSS',
 'Apply a 3D flip effect: set perspective 1000px on .scene, and rotate .card 180deg on the Y axis on hover.',
 'Aplica un efecto de volteo 3D: establece perspectiva 1000px en .scene, y rota .card 180 grados en el eje Y al pasar el cursor.',
 'html_css', 4, 'transforms',
 '.scene {\n  ___: 1000px;\n}\n.card:hover {\n  transform: ___(180deg);\n}',
 '.scene {\n  perspective: 1000px;\n}\n.card:hover {\n  transform: rotateY(180deg);\n}',
 3,
 'perspective on the parent creates a 3D space for child elements.', 'perspective en el padre crea un espacio 3D para los elementos hijos.',
 'rotateY() rotates around the vertical axis, creating a flip effect.', 'rotateY() rota alrededor del eje vertical, creando un efecto de volteo.',
 'perspective: 1000px; ... transform: rotateY(180deg);', 'perspective: 1000px; ... transform: rotateY(180deg);',
 50, 10, now()),

-- 86. animations
(gen_random_uuid(),
 'CSS Animation Fill Mode', 'Modo de Relleno de Animación CSS',
 'Create a slide-in animation and ensure the element retains the final animation state after it completes.',
 'Crea una animación de deslizamiento y asegura que el elemento retenga el estado final de la animación después de que termine.',
 'html_css', 4, 'animations',
 '.slide-in {\n  animation: slideIn 0.4s ease-out ___;\n}\n@keyframes slideIn {\n  from { transform: translateX(-100%); }\n  to { transform: translateX(0); }\n}',
 '.slide-in {\n  animation: slideIn 0.4s ease-out forwards;\n}\n@keyframes slideIn {\n  from { transform: translateX(-100%); }\n  to { transform: translateX(0); }\n}',
 3,
 'animation-fill-mode controls element style before/after animation.', 'animation-fill-mode controla el estilo del elemento antes/después de la animación.',
 '"forwards" retains the final keyframe state after animation ends.', '"forwards" retiene el estado del keyframe final después de que termina la animación.',
 'animation: slideIn 0.4s ease-out forwards;', 'animation: slideIn 0.4s ease-out forwards;',
 50, 10, now()),

-- 87. responsive design
(gen_random_uuid(),
 'Container Queries', 'Consultas de Contenedor',
 'Enable container queries on .card-wrapper, then apply a two-column layout inside it when wider than 400px.',
 'Habilita container queries en .card-wrapper, luego aplica un diseño de dos columnas dentro de él cuando tenga más de 400px de ancho.',
 'html_css', 4, 'responsive design',
 '.card-wrapper {\n  container-type: ___;\n}\n@container (min-width: ___px) {\n  .card-inner {\n    display: grid;\n    grid-template-columns: 1fr 1fr;\n  }\n}',
 '.card-wrapper {\n  container-type: inline-size;\n}\n@container (min-width: 400px) {\n  .card-inner {\n    display: grid;\n    grid-template-columns: 1fr 1fr;\n  }\n}',
 3,
 'Container queries respond to the parent container size rather than the viewport.', 'Las container queries responden al tamaño del contenedor padre en lugar del viewport.',
 'Set container-type: inline-size on the parent, then use @container for the rule.', 'Establece container-type: inline-size en el padre, luego usa @container para la regla.',
 'container-type: inline-size; ... @container (min-width: 400px)', 'container-type: inline-size; ... @container (min-width: 400px)',
 50, 10, now()),

-- 88. accessibility
(gen_random_uuid(),
 'Visually Hidden Class', 'Clase Oculta Visualmente',
 'Write a .visually-hidden CSS class that hides elements from sighted users but keeps them accessible to screen readers.',
 'Escribe una clase CSS .visually-hidden que oculte elementos a usuarios con visión pero los mantenga accesibles para lectores de pantalla.',
 'html_css', 4, 'accessibility',
 '.visually-hidden {\n  position: ___;\n  width: 1px;\n  height: 1px;\n  padding: 0;\n  margin: -1px;\n  overflow: hidden;\n  clip: rect(0,0,0,0);\n  white-space: nowrap;\n  border: 0;\n}',
 '.visually-hidden {\n  position: absolute;\n  width: 1px;\n  height: 1px;\n  padding: 0;\n  margin: -1px;\n  overflow: hidden;\n  clip: rect(0,0,0,0);\n  white-space: nowrap;\n  border: 0;\n}',
 3,
 'This pattern removes the element from visual layout while keeping it in the accessibility tree.', 'Este patrón elimina el elemento del diseño visual manteniéndolo en el árbol de accesibilidad.',
 'Set position: absolute and shrink it to 1x1px clipped area.', 'Establece position: absolute y redúcelo a un área de 1x1px recortada.',
 'position: absolute;', 'position: absolute;',
 50, 10, now()),

-- 89. selectors
(gen_random_uuid(),
 'CSS has() Relational Pseudo-class', 'Pseudo-clase Relacional CSS has()',
 'Style a .form-group that contains an invalid input by adding a red left border.',
 'Estiliza un .form-group que contenga un input inválido agregando un borde izquierdo rojo.',
 'html_css', 4, 'selectors',
 '.form-group:___(input:invalid) {\n  border-left: 3px solid red;\n}',
 '.form-group:has(input:invalid) {\n  border-left: 3px solid red;\n}',
 3,
 ':has() is a relational pseudo-class that selects parents based on their contents.', ':has() es una pseudo-clase relacional que selecciona padres basándose en su contenido.',
 'Use :has(child-selector) to target the parent when its child matches.', 'Usa :has(selector-hijo) para apuntar al padre cuando su hijo coincide.',
 '.form-group:has(input:invalid) { border-left: 3px solid red; }', '.form-group:has(input:invalid) { border-left: 3px solid red; }',
 50, 10, now()),

-- 90. forms
(gen_random_uuid(),
 'Custom Checkbox with CSS', 'Casilla de Verificación Personalizada con CSS',
 'Hide the native checkbox and style a custom one using its adjacent label, showing a checkmark on :checked.',
 'Oculta la casilla de verificación nativa y estiliza una personalizada usando su etiqueta adyacente, mostrando una marca al estar :checked.',
 'html_css', 4, 'forms',
 'input[type="checkbox"] {\n  ___: none;\n}\ninput[type="checkbox"] + label::before {\n  content: " ";\n  display: inline-block;\n  width: 16px;\n  height: 16px;\n  border: 2px solid #333;\n}\ninput[type="checkbox"]:___:checked + label::before {\n  content: "✓";\n}',
 'input[type="checkbox"] {\n  appearance: none;\n}\ninput[type="checkbox"] + label::before {\n  content: " ";\n  display: inline-block;\n  width: 16px;\n  height: 16px;\n  border: 2px solid #333;\n}\ninput[type="checkbox"]:checked + label::before {\n  content: "✓";\n}',
 3,
 'appearance: none removes the native browser styling from a form control.', 'appearance: none elimina el estilo nativo del navegador de un control de formulario.',
 'Use the :checked pseudo-class combined with adjacent sibling (+) to style the label.', 'Usa la pseudo-clase :checked combinada con el hermano adyacente (+) para estilizar la etiqueta.',
 'appearance: none; ... :checked + label::before { content: "✓"; }', 'appearance: none; ... :checked + label::before { content: "✓"; }',
 50, 10, now()),

-- ============================================================
-- DIFFICULTY 5 — 10 exercises (points=100, penalty=10)
-- ============================================================

-- 91. animations
(gen_random_uuid(),
 'CSS Skeleton Screen Animation', 'Animación de Pantalla Esqueleto CSS',
 'Create a shimmer skeleton loading animation using a gradient that sweeps from left to right repeatedly.',
 'Crea una animación de carga esqueleto con brillo usando un gradiente que barre de izquierda a derecha repetidamente.',
 'html_css', 5, 'animations',
 '.skeleton {\n  background: linear-gradient(\n    90deg,\n    #e0e0e0 25%,\n    #f0f0f0 50%,\n    #e0e0e0 75%\n  );\n  background-size: ___% 100%;\n  animation: shimmer 1.5s infinite;\n}\n@keyframes shimmer {\n  0% { background-position: -___% 0; }\n  100% { background-position: ___% 0; }\n}',
 '.skeleton {\n  background: linear-gradient(\n    90deg,\n    #e0e0e0 25%,\n    #f0f0f0 50%,\n    #e0e0e0 75%\n  );\n  background-size: 400% 100%;\n  animation: shimmer 1.5s infinite;\n}\n@keyframes shimmer {\n  0% { background-position: -400% 0; }\n  100% { background-position: 400% 0; }\n}',
 3,
 'Animate background-position to create a moving gradient effect.', 'Anima background-position para crear un efecto de gradiente en movimiento.',
 'background-size: 400% 100% makes the gradient wider than the element, allowing it to slide.', 'background-size: 400% 100% hace el gradiente más ancho que el elemento, permitiéndole deslizarse.',
 'background-size: 400% 100%; ... background-position: -400% 0 to 400% 0', 'background-size: 400% 100%; ... background-position: -400% 0 hasta 400% 0',
 100, 10, now()),

-- 92. grid
(gen_random_uuid(),
 'Holy Grail Layout with CSS Grid', 'Diseño Holy Grail con CSS Grid',
 'Build the full "Holy Grail" layout: a header, three-column middle (nav, main, aside), and a footer, all using a single CSS Grid on .page.',
 'Construye el diseño completo "Holy Grail": un header, tres columnas en el medio (nav, main, aside) y un footer, todo usando un solo CSS Grid en .page.',
 'html_css', 5, 'grid',
 '.page {\n  display: grid;\n  grid-template-rows: auto 1fr auto;\n  grid-template-columns: 200px 1fr 200px;\n  grid-template-areas:\n    "___ ___ ___"\n    "___ ___ ___"\n    "___ ___ ___";\n  min-height: 100vh;\n}',
 '.page {\n  display: grid;\n  grid-template-rows: auto 1fr auto;\n  grid-template-columns: 200px 1fr 200px;\n  grid-template-areas:\n    "header  header  header"\n    "nav     main    aside"\n    "footer  footer  footer";\n  min-height: 100vh;\n}',
 3,
 'The Holy Grail layout is a classic three-column layout with header and footer.', 'El diseño Holy Grail es un diseño clásico de tres columnas con encabezado y pie de página.',
 'Header and footer span all 3 columns; the middle row has nav, main, aside.', 'El encabezado y el pie de página abarcan las 3 columnas; la fila del medio tiene nav, main, aside.',
 '"header header header" "nav main aside" "footer footer footer"', '"header header header" "nav main aside" "footer footer footer"',
 100, 10, now()),

-- 93. responsive design
(gen_random_uuid(),
 'Fluid Typography System', 'Sistema de Tipografía Fluida',
 'Set up a complete fluid type scale using CSS variables on :root with clamp() for h1 (2rem–4rem), h2 (1.5rem–3rem), and p (1rem–1.25rem).',
 'Configura un sistema de escala tipográfica fluida usando variables CSS en :root con clamp() para h1 (2rem–4rem), h2 (1.5rem–3rem) y p (1rem–1.25rem).',
 'html_css', 5, 'responsive design',
 ':root {\n  --fs-xl: clamp(2rem, 4vw, ___);\n  --fs-lg: clamp(1.5rem, 3vw, ___);\n  --fs-base: clamp(1rem, 1.5vw, ___);\n}\nh1 { font-size: var(___); }\nh2 { font-size: var(___); }\np  { font-size: var(___); }',
 ':root {\n  --fs-xl: clamp(2rem, 4vw, 4rem);\n  --fs-lg: clamp(1.5rem, 3vw, 3rem);\n  --fs-base: clamp(1rem, 1.5vw, 1.25rem);\n}\nh1 { font-size: var(--fs-xl); }\nh2 { font-size: var(--fs-lg); }\np  { font-size: var(--fs-base); }',
 3,
 'Combine CSS variables with clamp() to create a reusable fluid type system.', 'Combina variables CSS con clamp() para crear un sistema tipográfico fluido y reutilizable.',
 'Define max values: 4rem for h1, 3rem for h2, 1.25rem for p.', 'Define valores máximos: 4rem para h1, 3rem para h2, 1.25rem para p.',
 '--fs-xl: clamp(2rem,4vw,4rem); --fs-lg: clamp(1.5rem,3vw,3rem); --fs-base: clamp(1rem,1.5vw,1.25rem)', '--fs-xl: clamp(2rem,4vw,4rem); --fs-lg: clamp(1.5rem,3vw,3rem); --fs-base: clamp(1rem,1.5vw,1.25rem)',
 100, 10, now()),

-- 94. accessibility
(gen_random_uuid(),
 'Full Accessible Modal Dialog', 'Diálogo Modal Completamente Accesible',
 'Mark up an accessible modal: role="dialog", aria-modal="true", aria-labelledby pointing to the title id, and aria-describedby pointing to the description id.',
 'Marca un modal accesible: role="dialog", aria-modal="true", aria-labelledby apuntando al id del título, y aria-describedby apuntando al id de la descripción.',
 'html_css', 5, 'accessibility',
 '<div\n  ___="dialog"\n  ___="true"\n  ___="modal-title"\n  ___="modal-desc"\n>\n  <h2 id="modal-title">Confirm Delete</h2>\n  <p id="modal-desc">This action cannot be undone.</p>\n</div>',
 '<div\n  role="dialog"\n  aria-modal="true"\n  aria-labelledby="modal-title"\n  aria-describedby="modal-desc"\n>\n  <h2 id="modal-title">Confirm Delete</h2>\n  <p id="modal-desc">This action cannot be undone.</p>\n</div>',
 3,
 'Accessible modals require several ARIA attributes to communicate their purpose.', 'Los modales accesibles requieren varios atributos ARIA para comunicar su propósito.',
 'role="dialog" + aria-modal="true" declares the modal; labelledby/describedby connect to content.', 'role="dialog" + aria-modal="true" declara el modal; labelledby/describedby conectan al contenido.',
 'role="dialog" aria-modal="true" aria-labelledby="modal-title" aria-describedby="modal-desc"', 'role="dialog" aria-modal="true" aria-labelledby="modal-title" aria-describedby="modal-desc"',
 100, 10, now()),

-- 95. flexbox
(gen_random_uuid(),
 'Card Grid with Equal Height Columns', 'Cuadrícula de Tarjetas con Columnas de Igual Altura',
 'Create a 3-up card layout where all cards in a row share equal height, and each card''s button is pinned to the bottom using flexbox on the card itself.',
 'Crea un diseño de tarjetas de 3 columnas donde todas las tarjetas de una fila comparten igual altura, y el botón de cada tarjeta está anclado al fondo usando flexbox en la propia tarjeta.',
 'html_css', 5, 'flexbox',
 '.card-grid {\n  display: flex;\n  flex-wrap: wrap;\n  gap: 20px;\n}\n.card {\n  flex: 0 0 calc(33.333% - 14px);\n  display: ___;\n  flex-direction: ___;\n}\n.card-body {\n  ___: 1;\n}\n.card-footer {\n  margin-top: ___;\n}',
 '.card-grid {\n  display: flex;\n  flex-wrap: wrap;\n  gap: 20px;\n}\n.card {\n  flex: 0 0 calc(33.333% - 14px);\n  display: flex;\n  flex-direction: column;\n}\n.card-body {\n  flex-grow: 1;\n}\n.card-footer {\n  margin-top: auto;\n}',
 3,
 'Make each card a flex column so its children stack vertically.', 'Haz que cada tarjeta sea una columna flex para que sus hijos se apilen verticalmente.',
 'flex-grow: 1 on the body expands it; margin-top: auto on the footer pushes it down.', 'flex-grow: 1 en el cuerpo lo expande; margin-top: auto en el footer lo empuja hacia abajo.',
 'display: flex; flex-direction: column; ... flex-grow: 1; ... margin-top: auto;', 'display: flex; flex-direction: column; ... flex-grow: 1; ... margin-top: auto;',
 100, 10, now()),

-- 96. animations
(gen_random_uuid(),
 'Staggered List Animation', 'Animación de Lista Escalonada',
 'Animate each list item with a "fadeSlideUp" effect, staggering the delay by 0.1s per item for 5 items using animation-delay.',
 'Anima cada elemento de lista con un efecto "fadeSlideUp", escalonando el retraso 0.1s por elemento para 5 elementos usando animation-delay.',
 'html_css', 5, 'animations',
 '@keyframes fadeSlideUp {\n  from { opacity: 0; transform: translateY(20px); }\n  to   { opacity: 1; transform: translateY(0); }\n}\nli { animation: fadeSlideUp 0.4s ease-out ___ both; }\nli:nth-child(1) { animation-delay: ___s; }\nli:nth-child(2) { animation-delay: ___s; }\nli:nth-child(3) { animation-delay: ___s; }\nli:nth-child(4) { animation-delay: ___s; }\nli:nth-child(5) { animation-delay: ___s; }',
 '@keyframes fadeSlideUp {\n  from { opacity: 0; transform: translateY(20px); }\n  to   { opacity: 1; transform: translateY(0); }\n}\nli { animation: fadeSlideUp 0.4s ease-out forwards both; }\nli:nth-child(1) { animation-delay: 0.0s; }\nli:nth-child(2) { animation-delay: 0.1s; }\nli:nth-child(3) { animation-delay: 0.2s; }\nli:nth-child(4) { animation-delay: 0.3s; }\nli:nth-child(5) { animation-delay: 0.4s; }',
 3,
 'Stagger animations by incrementing animation-delay on each nth-child.', 'Escalonar las animaciones incrementando animation-delay en cada nth-child.',
 'Use "forwards" fill-mode so items stay visible after animating in.', 'Usa el modo de relleno "forwards" para que los elementos permanezcan visibles después de animarse.',
 '0.0s, 0.1s, 0.2s, 0.3s, 0.4s delays with forwards fill-mode', '0.0s, 0.1s, 0.2s, 0.3s, 0.4s retrasos con modo de relleno forwards',
 100, 10, now()),

-- 97. grid
(gen_random_uuid(),
 'Masonry-style Grid with dense auto-placement', 'Cuadrícula Estilo Masonry con Colocación Auto Densa',
 'Set up a CSS Grid where .featured items span 2 rows, and enable dense auto-placement to fill in gaps left by tall items.',
 'Configura un CSS Grid donde los elementos .featured abarquen 2 filas, y habilita la colocación automática densa para llenar los huecos dejados por elementos altos.',
 'html_css', 5, 'grid',
 '.grid {\n  display: grid;\n  grid-template-columns: repeat(3, 1fr);\n  grid-auto-flow: ___ dense;\n  gap: 16px;\n}\n.featured {\n  grid-row: span ___;\n}',
 '.grid {\n  display: grid;\n  grid-template-columns: repeat(3, 1fr);\n  grid-auto-flow: row dense;\n  gap: 16px;\n}\n.featured {\n  grid-row: span 2;\n}',
 3,
 'grid-auto-flow: row dense fills gaps by backtracking to place smaller items.', 'grid-auto-flow: row dense llena huecos retrocediendo para colocar elementos más pequeños.',
 'grid-row: span 2 makes an item occupy 2 grid rows.', 'grid-row: span 2 hace que un elemento ocupe 2 filas de cuadrícula.',
 'grid-auto-flow: row dense; ... grid-row: span 2;', 'grid-auto-flow: row dense; ... grid-row: span 2;',
 100, 10, now()),

-- 98. variables
(gen_random_uuid(),
 'CSS Color Scheme Toggle', 'Alternador de Esquema de Color CSS',
 'Implement a color scheme system: define --surface, --on-surface, --accent variables in :root; override them in [data-theme="dark"]; apply them to body and a.btn.',
 'Implementa un sistema de esquema de colores: define variables --surface, --on-surface, --accent en :root; sobreescríbelas en [data-theme="dark"]; aplícalas a body y a.btn.',
 'html_css', 5, 'variables',
 ':root {\n  --surface: #ffffff;\n  --on-surface: #111111;\n  --accent: #6200ee;\n}\n[data-theme="dark"] {\n  --surface: #121212;\n  --on-surface: #e1e1e1;\n  --accent: #bb86fc;\n}\nbody {\n  background-color: var(___);\n  color: var(___);\n}\na.btn {\n  background-color: var(___);\n}',
 ':root {\n  --surface: #ffffff;\n  --on-surface: #111111;\n  --accent: #6200ee;\n}\n[data-theme="dark"] {\n  --surface: #121212;\n  --on-surface: #e1e1e1;\n  --accent: #bb86fc;\n}\nbody {\n  background-color: var(--surface);\n  color: var(--on-surface);\n}\na.btn {\n  background-color: var(--accent);\n}',
 3,
 'Attribute selectors like [data-theme="dark"] can override CSS variable values.', 'Los selectores de atributo como [data-theme="dark"] pueden sobreescribir los valores de variables CSS.',
 'Apply var(--surface), var(--on-surface), var(--accent) to the appropriate properties.', 'Aplica var(--surface), var(--on-surface), var(--accent) a las propiedades apropiadas.',
 'var(--surface), var(--on-surface), var(--accent)', 'var(--surface), var(--on-surface), var(--accent)',
 100, 10, now()),

-- 99. responsive design
(gen_random_uuid(),
 'Responsive Navigation Pattern', 'Patrón de Navegación Responsiva',
 'Write CSS for a navigation bar that displays horizontally on screens >= 768px, and stacks vertically (hidden by default, shown on .open) on smaller screens.',
 'Escribe CSS para una barra de navegación que se muestre horizontalmente en pantallas >= 768px, y se apile verticalmente (oculta por defecto, mostrada en .open) en pantallas más pequeñas.',
 'html_css', 5, 'responsive design',
 '.nav-links {\n  display: ___;\n  flex-direction: column;\n  ___ /* hidden by default on mobile */\n}\n.nav-links.___ {\n  display: flex;\n}\n@media (min-width: 768px) {\n  .nav-links {\n    display: ___;\n    flex-direction: row;\n  }\n}',
 '.nav-links {\n  display: none;\n  flex-direction: column;\n  /* hidden by default on mobile */\n}\n.nav-links.open {\n  display: flex;\n}\n@media (min-width: 768px) {\n  .nav-links {\n    display: flex;\n    flex-direction: row;\n  }\n}',
 3,
 'Mobile-first: hide nav links by default, show them when .open class is toggled.', 'Mobile-first: oculta los enlaces nav por defecto, muéstralos cuando se activa la clase .open.',
 'On desktop (>=768px), always show the links in a horizontal row regardless of .open.', 'En escritorio (>=768px), siempre muestra los enlaces en una fila horizontal independientemente de .open.',
 'display: none; ... .open { display: flex; } ... @media row { display: flex; flex-direction: row; }', 'display: none; ... .open { display: flex; } ... @media fila { display: flex; flex-direction: row; }',
 100, 10, now()),

-- 100. accessibility
(gen_random_uuid(),
 'Full Accessible Form', 'Formulario Completamente Accesible',
 'Create a fully accessible contact form with: fieldset + legend grouping, labels linked to inputs, aria-required on required fields, aria-describedby linking to an error message span, and a submit button.',
 'Crea un formulario de contacto completamente accesible con: agrupación fieldset + legend, etiquetas vinculadas a entradas, aria-required en campos requeridos, aria-describedby vinculando a un span de mensaje de error, y un botón de envío.',
 'html_css', 5, 'accessibility',
 '<form>\n  <___>\n    <___>Contact Us</___>\n    <label for="name">Name</label>\n    <input type="text" id="name" name="name"\n      ___="true"\n      ___="name-error">\n    <span id="name-error" role="alert"></span>\n    <button type="submit">Send</button>\n  </___>\n</form>',
 '<form>\n  <fieldset>\n    <legend>Contact Us</legend>\n    <label for="name">Name</label>\n    <input type="text" id="name" name="name"\n      aria-required="true"\n      aria-describedby="name-error">\n    <span id="name-error" role="alert"></span>\n    <button type="submit">Send</button>\n  </fieldset>\n</form>',
 3,
 'fieldset/legend groups related fields; aria-required signals mandatory fields to screen readers.', 'fieldset/legend agrupa campos relacionados; aria-required señala campos obligatorios a los lectores de pantalla.',
 'aria-describedby links the input to its error message; role="alert" announces errors immediately.', 'aria-describedby vincula la entrada a su mensaje de error; role="alert" anuncia errores de inmediato.',
 'fieldset + legend + aria-required="true" + aria-describedby="name-error" + role="alert"', 'fieldset + legend + aria-required="true" + aria-describedby="name-error" + role="alert"',
 100, 10, now())

ON CONFLICT DO NOTHING;

COMMIT;
